---
layout: "post"
title: "Find closest point on TinSurface"
date: "2012-07-06 09:04:46"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "AutoCAD Civil 3D 2012"
original_url: "https://adndevblog.typepad.com/infrastructure/2012/07/find-closest-point-on-tinsurface.html "
typepad_basename: "find-closest-point-on-tinsurface"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastrucuture/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>A question came up on how find a point XY on a surface. Actually this is quite easy and direct if the XY coordinate is inside the surface borders, just call <strong>TinSurface</strong> methods to <strong>Find</strong>[<em>Edge/Vertex/Triangle</em>]<strong>AtXY</strong> at a given coordinate, but this method throw an exception when the point is outside its borders.</p>  <p>One idea can be based on <a href="http://en.wikipedia.org/wiki/Brute-force">brute-force</a> algorithm. Of course this can be implemented in many different (and improved) ways, so below is one possible alternative. This also shows how use AutoCAD Geometry classes and methods. The following <strong>FindClosestEdgeAtXY</strong> sample method iterate through the edges and to find the closest from a given point.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">private</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">static</font></span><font color="#000000"> </font><span><font color="#2b91af">TinSurfaceEdge</font></span><font color="#000000"> FindClosestEdgeAtXY(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">TinSurface</font></span><font color="#000000"> surface, </font><span><font color="#2b91af">Point3d</font></span><font color="#000000"> point)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//in case the point is inside the surface</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">try</font></span><font color="#000000"> { </font><span><font color="#0000ff">return</font></span><font color="#000000"> surface.FindEdgeAtXY(point.X, point.Y); }</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">catch</font></span><font color="#000000"> { }</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">double</font></span><font color="#000000"> closestDistance = </font><span><font color="#0000ff">double</font></span><font color="#000000">.MaxValue;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">TinSurfaceEdge</font></span><font color="#000000"> closestEdge = </font><span><font color="#0000ff">null</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">foreach</font></span><font color="#000000"> (</font><span><font color="#2b91af">TinSurfaceTriangle</font></span><font color="#000000"> </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; triangle </font></font><font style="font-size: 8pt"><span><font color="#0000ff">in</font></span><font color="#000000"> surface.Triangles)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">TinSurfaceEdge</font></span><font color="#000000"> edge = </font><span><font color="#0000ff">null</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">double</font></span><font color="#000000"> distance = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; ClosestEdgeOfTriangle(triangle,</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; point, </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ref</font></span><font color="#000000"> edge);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">if</font></span><font color="#000000"> (distance &lt; closestDistance)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; closestDistance = distance;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; closestEdge = edge;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">return</font></span><font color="#000000"> closestEdge;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">private</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">static</font></span><font color="#000000"> </font><span><font color="#0000ff">double</font></span><font color="#000000"> ClosestEdgeOfTriangle(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">TinSurfaceTriangle</font></span><font color="#000000"> triangle, </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Point3d</font></span><font color="#000000"> point, </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ref</font></span><font color="#000000"> </font><span><font color="#2b91af">TinSurfaceEdge</font></span><font color="#000000"> edge)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// closest point on each edge</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Point3d</font></span><font color="#000000"> e1 = ClosestPointOnEdge(triangle.Edge1, point);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Point3d</font></span><font color="#000000"> e2 = ClosestPointOnEdge(triangle.Edge2, point);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Point3d</font></span><font color="#000000"> e3 = ClosestPointOnEdge(triangle.Edge3, point);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// closest of the three points</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">double</font></span><font color="#000000"> d1 = e1.DistanceTo(point);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">double</font></span><font color="#000000"> d2 = e2.DistanceTo(point);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">double</font></span><font color="#000000"> d3 = e3.DistanceTo(point);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">if</font></span><font color="#000000"> (d1 &lt; d2)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">if</font></span><font color="#000000"> (d1 &lt; d3)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; edge = triangle.Edge1;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">return</font></span><font color="#000000"> d1;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#0000ff">else</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; edge = triangle.Edge3;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">return</font></span><font color="#000000"> d3;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#0000ff">else</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; edge = triangle.Edge2;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">return</font></span><font color="#000000"> d2;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">private</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">static</font></span><font color="#000000"> </font><span><font color="#2b91af">Point3d</font></span><font color="#000000"> ClosestPointOnEdge(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">TinSurfaceEdge</font></span><font color="#000000"> edge, </font><span><font color="#2b91af">Point3d</font></span><font color="#000000"> point)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">using</font></span><font color="#000000"> (</font><span><font color="#2b91af">LineSegment3d</font></span><font color="#000000"> lineOverEdge = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">new</font></span><font color="#000000"> </font><span><font color="#2b91af">LineSegment3d</font></span><font color="#000000">(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; edge.Vertex1.Location, edge.Vertex2.Location))</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">using</font></span><font color="#000000"> (</font><span><font color="#2b91af">PointOnCurve3d</font></span><font color="#000000"> closestPointOnCurve =</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; lineOverEdge.GetClosestPointTo(point))</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">return</font></span><font color="#000000"> closestPointOnCurve.Point;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></p> </div>  <p>As this will return a <strong>TinSurfaceEdge</strong> object, the next step is find the closest point coordinate on that edge. Sure this is duplicated as the method already did that, but the following command sample find this point and append a AutoCAD <strong>DBPoint</strong> so it is visible on the drawing.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">[</font></font><font style="font-size: 8pt"><span><font color="#2b91af">CommandMethod</font></span><font color="#000000">(</font><span><font color="#a31515">&quot;findClosestEdge&quot;</font></span><font color="#000000">)]</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">static</font></span><font color="#000000"> </font><span><font color="#0000ff">void</font></span><font color="#000000"> CmdFindClosestEdge()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Editor</font></span><font color="#000000"> ed = </font><span><font color="#2b91af">Application</font></span><font color="#000000">.DocumentManager.</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; MdiActiveDocument.Editor;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// select the surface</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PromptEntityOptions</font></span><font color="#000000"> peoSurface = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">new</font></span><font color="#000000"> </font><span><font color="#2b91af">PromptEntityOptions</font></span><font color="#000000">(</font><span><font color="#a31515">&quot;Select the surface: &quot;</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; peoSurface.SetRejectMessage(</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;\nOnly tin surfaces are allowed&quot;</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; peoSurface.AddAllowedClass(</font></font><font style="font-size: 8pt"><span><font color="#0000ff">typeof</font></span><font color="#000000">(</font><span><font color="#2b91af">TinSurface</font></span><font color="#000000">), </font><span><font color="#0000ff">true</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PromptEntityResult</font></span><font color="#000000"> perSurface = ed.GetEntity(peoSurface);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">if</font></span><font color="#000000"> (perSurface.Status != </font><span><font color="#2b91af">PromptStatus</font></span><font color="#000000">.OK) </font><span><font color="#0000ff">return</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// specify the point</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PromptPointResult</font></span><font color="#000000"> pprPoint = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; ed.GetPoint(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;Specify the point: &quot;</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">if</font></span><font color="#000000"> (pprPoint.Status != </font><span><font color="#2b91af">PromptStatus</font></span><font color="#000000">.OK) </font><span><font color="#0000ff">return</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Point3d</font></span><font color="#000000"> point = pprPoint.Value;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Database</font></span><font color="#000000"> db = </font><span><font color="#2b91af">Application</font></span><font color="#000000">.DocumentManager.</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; MdiActiveDocument.Database;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">using</font></span><font color="#000000"> (</font><span><font color="#2b91af">Transaction</font></span><font color="#000000"> trans = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; db.TransactionManager.StartTransaction())</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// open the surface</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">TinSurface</font></span><font color="#000000"> surface = trans.GetObject(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; perSurface.ObjectId, </font></font><font style="font-size: 8pt"><span><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForRead) </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">as</font></span><font color="#000000"> </font><span><font color="#2b91af">TinSurface</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// find the closest edge</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">TinSurfaceEdge</font></span><font color="#000000"> closestEdge = FindClosestEdgeAtXY(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; surface, point);</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// now (duplicated) find the closest point over the edge</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">using</font></span><font color="#000000"> (</font><span><font color="#2b91af">LineSegment3d</font></span><font color="#000000"> lineOverEdge = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">new</font></span><font color="#000000"> </font><span><font color="#2b91af">LineSegment3d</font></span><font color="#000000">(closestEdge.Vertex1.Location,</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; closestEdge.Vertex2.Location))</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">using</font></span><font color="#000000"> (</font><span><font color="#2b91af">PointOnCurve3d</font></span><font color="#000000"> closestPointOnCurve = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lineOverEdge.GetClosestPointTo(point))</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// get the point</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">Point3d</font></span><font color="#000000"> closestPoint = closestPointOnCurve.Point;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// draw a point for debug</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">BlockTableRecord</font></span><font color="#000000"> curSpace = trans.GetObject(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.CurrentSpaceId, </font></font><font style="font-size: 8pt"><span><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForWrite) </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">as</font></span><font color="#000000"> </font><span><font color="#2b91af">BlockTableRecord</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">DBPoint</font></span><font color="#000000"> newPoint = </font><span><font color="#0000ff">new</font></span><font color="#000000"> </font><span><font color="#2b91af">DBPoint</font></span><font color="#000000">(closestPoint);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; curSpace.AppendEntity(newPoint);</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.AddNewlyCreatedDBObject(newPoint, </font></font><font style="font-size: 8pt"><span><font color="#0000ff">true</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; trans.Commit();</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></p> </div>
