---
layout: "post"
title: "Import DEM to Create Surface in Civil 3D with COM API"
date: "2013-01-28 19:58:11"
author: "Daniel Du"
categories:
  - "AutoCAD Civil 3D 2012"
  - "AutoCAD Civil 3D 2013"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/infrastructure/2013/01/import-dem-to-create-surface-in-civil-3d-with-com-api.html "
typepad_basename: "import-dem-to-create-surface-in-civil-3d-with-com-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/daniel-du.html">Daniel Du</a></p>  <p>Civil 3D provides .NET API and COM API, you are recommended to use .NET API if it is available, although this post will demo how to import DEM with COM API.</p>  <p>To use COM API, you need to add some references with interop, it is convenient to use <a href="http://adndevblog.typepad.com/infrastructure/2012/05/autocad-net-wizard-support-map-3d-civil-3d-autocad-architecture-and-autocad-mep-now.html">AutoCAD .net wizard</a>, it supports Civil 3D as well as other AutoCAD vertical products. Please check following references with wizard, and please note that you may add other references if some are missing. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017d408b92f6970c-pi"><img style="background-image: none; border-right-width: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_5d623e.jpg" width="244" height="210" /></a><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017ee80031fc970d-pi"><img style="background-image: none; border-right-width: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_cac360.jpg" width="244" height="213" /></a></p>  <p>The code snippet goes as below: </p>  <pre style="line-height: normal; text-indent: 0pt; font-family: ; background: white; word-break: normal"><font face="新宋体"><font color="#008000"><span style="line-height: normal; color: ">// (C) Copyright 2013 by Autodesk </span><br /><span style="line-height: normal; color: ">//</span></font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> System;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> Autodesk.AutoCAD.Runtime;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> Autodesk.AutoCAD.ApplicationServices;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> Autodesk.AutoCAD.DatabaseServices;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> Autodesk.AutoCAD.Geometry;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> Autodesk.AutoCAD.EditorInput;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> System.Windows.Forms;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> Autodesk.AECC.Interop.UiLand;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span><font color="#000000"> Autodesk.AutoCAD.Interop;</font><br /><span style="line-height: normal; color: "><font color="#0000ff">using</font></span></font><font face="新宋体"><font color="#000000"> Autodesk.Civil.ApplicationServices;<br /> <br /> </font><br /><span style="line-height: normal; color: "><font color="#008000">// This line is not mandatory, but improves loading performances</font></span><br /><font color="#000000">[</font><span style="line-height: normal; color: "><font color="#0000ff">assembly</font></span><font color="#000000">: </font><span style="line-height: normal; color: "><font color="#2b91af">CommandClass</font></span><font color="#000000">(</font><span style="line-height: normal; color: "><font color="#0000ff">typeof</font></span><font color="#000000">(LoadDEM_demo.</font><span style="line-height: normal; color: "><font color="#2b91af">MyCommands</font></span></font><font face="新宋体"><font color="#000000">))]<br /> </font><br /><span style="line-height: normal; color: "><font color="#0000ff">namespace</font></span></font><font face="新宋体"><font color="#000000"> LoadDEM_demo<br />{<br /> <br /> <br />&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">public</font></span><font color="#000000">&#160;</font><span style="line-height: normal; color: "><font color="#0000ff">class</font></span><font color="#000000">&#160;</font><span style="line-height: normal; color: "><font color="#2b91af">MyCommands</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160; {<br />&#160;<br /> <br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#008000">// COM objects:</font></span><br /><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">private</font></span><font color="#000000"> Autodesk.AutoCAD.Interop.</font><span style="line-height: normal; color: "><font color="#2b91af">IAcadApplication</font></span><font color="#000000"> m_oAcadApp = </font><span style="line-height: normal; color: "><font color="#0000ff">null</font></span></font><font face="新宋体"><font color="#000000">;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">private</font></span><font color="#000000"> Autodesk.AECC.Interop.UiLand.</font><span style="line-height: normal; color: "><font color="#2b91af">IAeccApplication</font></span><font color="#000000"> m_oAeccApp = </font><span style="line-height: normal; color: "><font color="#0000ff">null</font></span></font><font face="新宋体"><font color="#000000">;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">private</font></span><font color="#000000"> Autodesk.AECC.Interop.UiLand.</font><span style="line-height: normal; color: "><font color="#2b91af">IAeccDocument</font></span><font color="#000000"> m_oAeccDoc = </font><span style="line-height: normal; color: "><font color="#0000ff">null</font></span></font><font face="新宋体"><font color="#000000">;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">private</font></span><font color="#000000"> Autodesk.AECC.Interop.Land.</font><span style="line-height: normal; color: "><font color="#2b91af">IAeccDatabase</font></span><font color="#000000"> m_oAeccDb = </font><span style="line-height: normal; color: "><font color="#0000ff">null</font></span></font><font face="新宋体"><font color="#000000">;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">string</font></span><font color="#000000"> m_sAcadProdID = </font><span style="line-height: normal; color: "><font color="#a31515">&quot;AutoCAD.Application&quot;</font></span></font><font face="新宋体"><font color="#000000">;<br />        </font></font><span style="line-height: normal; color: "><font color="#008000">//Civil 3D 2013</font></span><font face="新宋体"><font color="#000000"><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">string</font></span><font color="#000000"> m_sAeccAppProgId = </font><span style="line-height: normal; color: "><font color="#a31515">&quot;AeccXUiLand.AeccApplication.10.0&quot;</font></span><font color="#000000">;<br />        //Civil 3D 2012 </font><br /><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#008000">//string m_sAeccAppProgId = &quot;AeccXUiLand.AeccApplication.9.0&quot;; </font></span><br /><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">private</font></span><font color="#000000">&#160;</font><span style="line-height: normal; color: "><font color="#0000ff">string</font></span><font color="#000000"> m_sMessage = </font><span style="line-height: normal; color: "><font color="#a31515">&quot;&quot;</font></span></font><font face="新宋体"><font color="#000000">;<br /> <br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; [</font><span style="line-height: normal; color: "><font color="#2b91af">CommandMethod</font></span><font color="#000000">(</font><span style="line-height: normal; color: "><font color="#a31515">&quot;LoadDemSurfaceop&quot;</font></span></font><font face="新宋体"><font color="#000000">)]<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">public</font></span><font color="#000000">&#160;</font><span style="line-height: normal; color: "><font color="#0000ff">void</font></span></font><font face="新宋体"><font color="#000000"> LoadDemSurface()<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">try</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#2b91af">OpenFileDialog</font></span><font color="#000000"> ofd = </font><span style="line-height: normal; color: "><font color="#0000ff">new</font></span><font color="#000000">&#160;</font><span style="line-height: normal; color: "><font color="#2b91af">OpenFileDialog</font></span></font><font face="新宋体"><font color="#000000">();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ofd.Filter = </font><span style="line-height: normal; color: "><font color="#a31515">&quot;USGS DEM( *.DEM) |*.dem&quot;</font></span></font><font face="新宋体"><font color="#000000">;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ofd.FilterIndex = 0;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">if</font></span><font color="#000000"> (ofd.ShowDialog() == </font><span style="line-height: normal; color: "><font color="#2b91af">DialogResult</font></span></font><font face="新宋体"><font color="#000000">.OK)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#008000">//use COM</font></span><br /><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_oAcadApp = (</font><span style="line-height: normal; color: "><font color="#2b91af">IAcadApplication</font></span><font color="#000000">)System.Runtime.InteropServices<br />                                  .</font><span style="line-height: normal; color: "><font color="#2b91af">Marshal</font></span></font><font face="新宋体"><font color="#000000">.GetActiveObject(m_sAcadProdID);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">if</font></span><font color="#000000"> (m_oAcadApp != </font><span style="line-height: normal; color: "><font color="#0000ff">null</font></span></font><font face="新宋体"><font color="#000000">)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_oAeccApp = (</font><span style="line-height: normal; color: "><font color="#2b91af">IAeccApplication</font></span></font><font face="新宋体"><font color="#000000">)m_oAcadApp<br />                                         .GetInterfaceObject(m_sAeccAppProgId);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_oAeccDoc = (</font><span style="line-height: normal; color: "><font color="#2b91af">IAeccDocument</font></span></font><font face="新宋体"><font color="#000000">)m_oAeccApp.ActiveDocument;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_oAeccDoc.Surfaces.ImportDEM(ofd.FileName);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_oAeccDoc.Regen(Autodesk.AutoCAD.Interop.Common<br />                                      .</font><span style="line-height: normal; color: "><font color="#2b91af">AcRegenType</font></span></font><font face="新宋体"><font color="#000000">.acActiveViewport);<br /> <br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">else</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">catch</font></span><font color="#000000"> (System.</font><span style="line-height: normal; color: "><font color="#2b91af">Exception</font></span></font><font face="新宋体"><font color="#000000"> e)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#2b91af">MessageBox</font></span></font><font face="新宋体"><font color="#000000">.Show(e.Message);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="line-height: normal; color: "><font color="#0000ff">finally</font></span><br /><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160; <br /> <br /> <br />&#160;&#160;&#160; }<br /> <br />}</font></font><br /></pre>
