---
layout: "post"
title: "Using LINQ with AutoCAD and Civil 3D APIs"
date: "2013-07-05 10:44:42"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "AutoCAD Civil 3D 2014"
original_url: "https://adndevblog.typepad.com/infrastructure/2013/07/using-linq-with-autocad-and-civil-3d-apis.html "
typepad_basename: "using-linq-with-autocad-and-civil-3d-apis"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>In a previous post, I showed an example of <a href="http://adndevblog.typepad.com/infrastructure/2012/05/using-linq-with-civil-3d-activex-objects.html" target="_blank">LINQ</a> with ActiveX object collection. Now, this sample is showing another sample with .NET objects.</p>  <p>This sample show an example where all the Arcs on the Model Space are selected, then we use LINQ to filter only the arcs close to the Alignment (distance from the center of the arc to the alignment smaller than a maximum). But more that that, it also order the arcs by its projected stations (imagine a line from the center of the arc to the alignment, then the station at that point). The result may be like the image below:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01910418eb1c970c-pi"><img title="curve_number" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" border="0" alt="curve_number" src="/assets/image_8f5200.jpg" width="477" height="347" /></a></p>  <p>As a learning point, LINQ have several interesting applications and itâ€™s quite fast. </p>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><font face="Courier New"><span style="color: "><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span style="color: "><font color="#0000ff">Function</font></span><font color="#000000"> FindArcsByDistance(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; alignId </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">ObjectId</font></span><font color="#000000">,</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; maxOffset </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">Double</font></span><font color="#000000">) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">ObjectIdCollection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' returning list</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> curvesIds </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">New</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">ObjectIdCollection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> db </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">Database</font></span><font color="#000000"> = alignId.Database</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Using</font></span><font color="#000000"> trans </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">Transaction</font></span><font color="#000000"> = db.TransactionManager.StartTransaction</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' open the alignment</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> align </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">Alignment</font></span><font color="#000000"> = trans.GetObject(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; alignId, </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForRead)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' open the current space through the Alignment owner</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> mSpace </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span><font color="#000000"> = trans.GetObject(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; align.OwnerId, </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForWrite)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' get all Arc, regardless where</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' you may consider add an aditional filter, e.g by layer</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> curves </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">New</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">DBObjectCollection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">For</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">Each</font></span><font color="#000000"> entityId </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">ObjectId</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">In</font></span><font color="#000000"> mSpace</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> curve </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">Arc</font></span><font color="#000000"> = </font><span style="color: "><font color="#0000ff">TryCast</font></span><font color="#000000">(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.GetObject(entityId, </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForRead), </font><span style="color: "><font color="#2b91af">Arc</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">If</font></span><font color="#000000"> (curve </font><span style="color: "><font color="#0000ff">Is</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">Nothing</font></span><font color="#000000">) </font><span style="color: "><font color="#0000ff">Then</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">Continue For</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' not an Arc, next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; curves.Add(curve)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' use LINQ to filter and order the arcs</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' some of the methods related to geometry are not implemented on </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' the alignment object, so we need to workaround with </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' GetClosestPointTo&#160; and GetDistAtPoint.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> curvesFiltered =</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">From</font></span><font color="#000000"> arc </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">Arc</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">In</font></span><font color="#000000"> curves</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Where</font></span><font color="#000000"> arc.Center.DistanceTo(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; align.GetClosestPointTo(arc.Center, </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">False</font></span><font color="#000000">)) &lt; maxOffset</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Order</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">By</font></span><font color="#000000"> align.GetDistAtPoint(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; align.GetClosestPointTo(arc.Center, </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">False</font></span><font color="#000000">))</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' write a text along the curve</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> cont </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">Integer</font></span><font color="#000000"> = 1</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">For</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">Each</font></span><font color="#000000"> curve </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">Arc</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">In</font></span><font color="#000000"> curvesFiltered</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' return value</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; curvesIds.Add(curve.ObjectId)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' consider a line from the arc start point to end</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> referenceLine </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">New</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">LineSegment3d</font></span><font color="#000000">(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; curve.StartPoint, curve.EndPoint)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' draw a DBText aligned to this line</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> curveLabel </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">New</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">DBText</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; curveLabel.SetDatabaseDefaults()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; curveLabel.TextString = </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">String</font></span><font color="#000000">.Format(</font><span style="color: "><font color="#a31515">&quot;Curve = {0}&quot;</font></span><font color="#000000">, cont)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; curveLabel.HorizontalMode = </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">TextHorizontalMode</font></span><font color="#000000">.TextCenter</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; curveLabel.AlignmentPoint = referenceLine.MidPoint</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; curveLabel.Rotation = referenceLine.Direction.</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetAngleTo(</font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">Vector3d</font></span><font color="#000000">.XAxis)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">' add to the model space</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; mSpace.AppendEntity(curveLabel)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; trans.AddNewlyCreatedDBObject(curveLabel, </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">True</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; cont += 1</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; trans.Commit()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Using</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Return</font></span><font color="#000000"> curvesIds</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="color: "><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Function</font></span></font></p> </div>
