---
layout: "post"
title: "Change surface style with Civil 3D API"
date: "2014-12-29 03:43:05"
author: "Daniel Du"
categories:
  - ".NET"
  - "AutoCAD Civil 3D 2014"
  - "AutoCAD Civil 3D 2015"
  - "Civil 3D"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/infrastructure/2014/12/change-surface-style-with-civil-3d-api.html "
typepad_basename: "change-surface-style-with-civil-3d-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/daniel-du.html">Daniel Du</a></p>  <p>I was asked how to edit the style of surface in Civil 3D, for example, we need to change the color of contours. We can do it with Civil 3D UI by right clicking the surface object and choose “Edit surface style…” and switching to “Display” tab to show the dialogue as below:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d0b3430a970c-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="image" src="/assets/image_05e6e3.jpg" width="452" height="362" /></a> </p>  <p>This is code snippet demonstrating how to do it with API:</p>  <pre style="font-size: 13px; font-family: consolas; background: white; color: black">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;MyGroup&quot;</span>, <span style="color: #a31515">&quot;SurfaceStyleExample&quot;</span>, <br />&#160;&#160;&#160; <span style="color: #a31515">&quot;SurfaceStyleExample&quot;</span>, <span style="color: #2b91af">CommandFlags</span>.Modal)]<br /><span style="color: blue">public</span>&#160;<span style="color: blue">void</span> MyCommand() <span style="color: green">// This method can have any name</span><br />{<br />&#160;<br />&#160;&#160;&#160; <span style="color: #2b91af">Document</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;<br />&#160;&#160;&#160; <br />&#160;&#160;&#160; <span style="color: blue">if</span> (doc != <span style="color: blue">null</span>)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Editor</span> ed = <span style="color: #2b91af">Application</span>.DocumentManager<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .MdiActiveDocument.Editor;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// select a tin surface</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptEntityOptions</span> peo = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">PromptEntityOptions</span>(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\nSelect a tin surface: &quot;</span>);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; peo.SetRejectMessage(<span style="color: #a31515">&quot;\nOnly Tin surface is accepted&quot;</span>);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; peo.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">TinSurface</span>), <span style="color: blue">true</span>);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptEntityResult</span> per = ed.GetEntity(peo);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (per.Status != <span style="color: #2b91af">PromptStatus</span>.OK) <span style="color: blue">return</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">CivilDocument</span> civilDoc = <span style="color: #2b91af">CivilApplication</span>.ActiveDocument;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = doc.TransactionManager<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .StartTransaction())<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">TinSurface</span> surface = trans.GetObject(per.ObjectId, <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">TinSurface</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//exclude invalid points</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surface.BuildOptions.ExecludeMaximumElevation = <span style="color: blue">true</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surface.BuildOptions.MaximumElevation = 5000;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surface.BuildOptions.ExecludeMinimumElevation = <span style="color: blue">true</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surface.BuildOptions.MinimumElevation = 200;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//set the Maximum Triangle Length</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surface.BuildOptions.MaximumTriangleLength = 200;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//change the style</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">ObjectId</span> styleId;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (civilDoc.Styles.SurfaceStyles.Contains(<span style="color: #a31515">&quot;Standard&quot;</span>))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; styleId = civilDoc.Styles.SurfaceStyles[<span style="color: #a31515">&quot;Standard&quot;</span>];<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">else</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// create a new style called 'example style':</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; styleId = civilDoc.Styles.SurfaceStyles<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Add(<span style="color: #a31515">&quot;example style&quot;</span>);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// modify the style</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceStyle</span> surfaceStyle = styleId.GetObject(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForWrite) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">SurfaceStyle</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//countours smoothing </span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.ContourStyle.SmoothContours = <span style="color: blue">true</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.ContourStyle.SmoothingType <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = <span style="color: #2b91af">ContourSmoothingType</span>.AddVertices;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.ContourStyle.SmoothingFactor = 10;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.ContourStyle.MajorContourColorScheme <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = <span style="color: #2b91af">ColorSchemeType</span>.Rainbow;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Major contour, red</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceDisplayStyleType</span>.MajorContour).Color <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = Autodesk.AutoCAD.Colors.<span style="color: #2b91af">Color</span>.FromRgb(255, 0, 0);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Major contour, layer 0</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceDisplayStyleType</span>.MajorContour).Layer = <span style="color: #a31515">&quot;0&quot;</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Mainor contour, gree</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceDisplayStyleType</span>.MinorContour).Color <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = Autodesk.AutoCAD.Colors.<span style="color: #2b91af">Color</span>.FromRgb(0, 255, 0);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Mainor contour, layer 0</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceDisplayStyleType</span>.MajorContour).Layer = <span style="color: #a31515">&quot;0&quot;</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// display major contours:</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .MajorContour).Visible = <span style="color: blue">true</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .MinorContour).Visible = <span style="color: blue">true</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// turn off display of other items:</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .UserContours).Visible = <span style="color: blue">false</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Directions).Visible = <span style="color: blue">false</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Elevations).Visible = <span style="color: blue">false</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Slopes).Visible = <span style="color: blue">false</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .SlopeArrows).Visible = <span style="color: blue">false</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfaceStyle.GetDisplayStylePlan(<span style="color: #2b91af">SurfaceDisplayStyleType</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Watersheds).Visible = <span style="color: blue">false</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//TODO: do the same for all model display settings as well</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//</span><br /> <br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// assign the style to the first surface in the document:</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surface.StyleId = styleId;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// commit the transaction</span><br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit();<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//rebuild the surface </span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; surface.Rebuild();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160; }<br /> <br /> <br /> <br />}<br /></pre>

<p>&#160;</p>

<p>This is how it looks like before editing:</p>

<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d0b34312970c-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="image" src="/assets/image_283fee.jpg" width="396" height="320" /></a> </p>

<p>And here is how it looks like after editing the surface contour style with major contour color to red and monor contour color to green. </p>

<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb07cdcebe970d-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="image" src="/assets/image_dadf49.jpg" width="404" height="332" /></a> </p>

<p></p>

<p></p>

<p>Hope this helps.</p>
