---
layout: "post"
title: "Importing Alignment from Infraworks 360 to Civil 3D"
date: "2014-10-17 07:49:21"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "Infraworks 360"
original_url: "https://adndevblog.typepad.com/infrastructure/2014/10/importing-alignment-from-infraworks-360-to-civil-3d.html "
typepad_basename: "importing-alignment-from-infraworks-360-to-civil-3d"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/augusto-goncalves.html">Augusto Goncalves</a></p>
<p>Now from the interesting experience at AU Russia, I would like to share this cool picture of the <a href="http://en.wikipedia.org/wiki/New_Arbat_Avenue">Новый Арбат (Novyy Arbat)</a> avenue near the Kremlin, I was impressed by the light show at the buildings facade! Cool!</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d07f4050970c-pi"><img alt="Новый Арбат (Nobyy Arbat) avenue in Moscow" border="0" height="359" src="/assets/image_be91ee.jpg" style="display: inline; border: 0px;" title="Новый Арбат (Nobyy Arbat) avenue in Moscow" width="477" /></a></p>
<p>Back to our technical topic, as <a href="http://adndevblog.typepad.com/infrastructure/2014/05/infraworks-360-rest-api-tech-preview-available.html">announced early this year</a>, the Infraworks 360 API Pilot is live. The first sample was around connecting IW360 with other providers (Four Square and Google Maps). Now it’s time for another sample, connecting to Civil 3D.</p>
<p>This sample uses the <a href="https://github.com/ADN-DevTech/Infraworks_API_Samples">Infraworks 360 sample</a> and the <a href="https://github.com/ADN-DevTech/AutodeskOAuthSamples">ADN OAuth sample</a>, both available on Github. Also, as IW360 is using LL84 coordinate system, we need to convert the values to the project coordinate system used on Civil 3D using the code at this <a href="http://adndevblog.typepad.com/infrastructure/2012/10/convert-coordinates-from-gps-ll84-to-civil-3d-active-project-settings.html">blog post</a>.</p>
<p>There are a few steps on the code. (1) Connect to Autodesk server using the user SSO (Autodesk Single Sign On account), after the authentication we have the token that allow access to files, so we can (2) get the IW360 list of models. With the model number, we can (3) get the roads of this model. Note that this list contains only the IDs, so we also need to read the road information to finally (4) create one alignment for each road.</p>
<p>Some comments before you read the code: I’m not creating a fancy interface, just listing the options and asking the user to type a number. Also, to avoid reading all the roads, I’m limiting the number. The alignment is created, which by design contains only 2D data, so if you need elevation data, you’ll need to also create profiles (which was not done here for simplicity). As IW360 may have more than one road with the same name (for instance, for each direction or due intersections), this sample code is only creating the first one, so one improvement may be treat this scenario to merge the roads before creating the alignments.</p>
<p>What is needed to use IW360 API: you need to be part of the Pilot. That involves using the Beta version of Infraworks 360 and a key &amp; secret pair. If you have a project and would like to join, email me at <span style="text-decoration: underline;">augusto.goncalves[AT]autodesk.com</span> with more information about your idea.</p>
<pre style="font-size: 13px; font-family: consolas; background: white; color: black;"><span style="color: green;">// System namespaces</span><span style="color: blue;"><br />using</span> System;<br /><span style="color: blue;">using</span> System.Collections.Generic;<br /><span style="color: blue;">using</span> System.Linq;<br /><span style="color: blue;">using</span> System.Text;<br /> <br /><span style="color: green;">// AutoCAD Namespaces (main code for commands and interface)</span><br /><span style="color: blue;">using</span> Autodesk.AutoCAD.ApplicationServices;<br /><span style="color: blue;">using</span> Autodesk.AutoCAD.Runtime;<br /><span style="color: blue;">using</span> Autodesk.AutoCAD.DatabaseServices;<br /><span style="color: blue;">using</span> Autodesk.AutoCAD.EditorInput;<br /> <br /><span style="color: green;">// Civil 3D namespaces (to create alingmnet)</span><br /><span style="color: blue;">using</span> Autodesk.Civil.ApplicationServices;<br /><span style="color: blue;">using</span> Autodesk.Civil.DatabaseServices;<br /> <br /><span style="color: green;">// Autodesk OAuth namespaces (implemented by ADN)</span><br /><span style="color: blue;">using</span> Autodesk.Adn.OAuthentication;<br /> <br /><span style="color: green;">// Infraworks namespaces (model data implemented by ADN)</span><br /><span style="color: blue;">using</span> Autodesk.Adn.InfraworksService.Service;<br /><span style="color: blue;">using</span> Autodesk.Adn.InfraworksService.Models;<br /><span style="color: blue;">using</span> Autodesk.Adn.InfraworksService.Models.Geometries;<br /><span style="color: blue;">using</span> Autodesk.AutoCAD.Geometry;<br /> <br /><span style="color: blue;">namespace</span> Civil3DSample<br />{<br />&#0160; <span style="color: blue;">public</span>&#0160;<span style="color: blue;">class</span>&#0160;<span style="color: #2b91af;">Commands</span><br />&#0160; {<br />&#0160;&#0160;&#0160; <span style="color: green;">// static variables for local cache</span><br />&#0160;&#0160;&#0160; <span style="color: blue;">private</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: #2b91af;">OAuthService</span> _oauth = <span style="color: blue;">null</span>;<br />&#0160;&#0160;&#0160; <span style="color: blue;">private</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: #2b91af;">InfraworksRestService</span> _iw360 = <span style="color: blue;">null</span>;<br />&#0160;&#0160;&#0160; <span style="color: blue;">private</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: #2b91af;">List</span>&lt;<span style="color: #2b91af;">ModelInfo</span>&gt; _models = <span style="color: blue;">null</span>;<br />&#0160;&#0160;&#0160; <span style="color: blue;">private</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: blue;">int</span> _modelId = 0;<br />&#0160;&#0160;&#0160; <span style="color: blue;">private</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: #2b91af;">List</span>&lt;<span style="color: #2b91af;">Road</span>&gt; _roads = <span style="color: blue;">null</span>;<br /> <br />&#0160;&#0160;&#0160; [<span style="color: #2b91af;">CommandMethod</span>(<span style="color: #a31515;">&quot;importIW360Alignment&quot;</span>)]<br />&#0160;&#0160;&#0160; <span style="color: blue;">public</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: blue;">void</span> CmdImportIW360Alignment()<br />&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// 1. Connect to Autodesk servers</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// connect to Autodesk SSO (Single Sign On) accounts</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// this will request the user to login (username &amp; password)</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (_oauth == <span style="color: blue;">null</span>)<br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _oauth = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">OAuthService</span>(<span style="color: #2b91af;">IW360Constants</span>.CONSUMER_KEY, <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">IW360Constants</span>.CONSUMER_SECRET, <span style="color: #2b91af;">IW360Constants</span>.BASE_OAUTH_URL);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (!_oauth.StartOAuth()) <span style="color: blue;">return</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// connect to Infraworks 360 server</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// using the OAuth authentication from the previous step</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// therefore all the information is specific to this user</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (_iw360 == <span style="color: blue;">null</span>) _iw360 = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">InfraworksRestService</span>(_oauth);<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// 2. Ask user to select one IW360 Model</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// get a list of models</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (_models == <span style="color: blue;">null</span>) _models = _iw360.GetModels();<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// list models</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">int</span> m = 0;<br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">foreach</span> (<span style="color: #2b91af;">ModelInfo</span> mode <span style="color: blue;">in</span> _models)<br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m++;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ed.WriteMessage(<span style="color: #a31515;">&quot;\n{0} - {1}&quot;</span>, m, mode.name);<br />&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// ask the user to choose one model</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">PromptIntegerOptions</span> pio = <span style="color: blue;">new</span>&#0160;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">PromptIntegerOptions</span>(<span style="color: #a31515;">&quot;\nEnter model number: &quot;</span>);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; pio.AllowZero = <span style="color: blue;">false</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; pio.AllowNegative = <span style="color: blue;">false</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; pio.UpperLimit = m;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">PromptIntegerResult</span> pir = ed.GetInteger(pio);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (pir.Status != <span style="color: #2b91af;">PromptStatus</span>.OK) <span style="color: blue;">return</span>;<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">ModelInfo</span> selectedModel = _models[pir.Value - 1]; <span style="color: green;">// zero-based array</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">int</span> selectedModelId = <span style="color: blue;">int</span>.Parse(selectedModel.id);<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// if is NOT the sample model, then the local</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// cache is invalid applies (if exists)</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (selectedModelId != _modelId) _roads = <span style="color: blue;">null</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// and store the selected model ID</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _modelId = selectedModelId;<br />&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// 3. Ask user to select one IW360 Road</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (_roads == <span style="color: blue;">null</span>) <span style="color: green;">// if the local cache is empty</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// get all roads, this list returns IDs </span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">Collection</span> roadsProxy = _iw360.GetItemsByClass(_modelId, <span style="color: #a31515;">&quot;roads&quot;</span>);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (roadsProxy == <span style="color: blue;">null</span>) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ed.WriteMessage(<span style="color: #a31515;">&quot;\nCould not load roads. Please try again.&quot;</span>);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">return</span>; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// from the IDs, let get the full object (which contains the names)</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _roads = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">List</span>&lt;<span style="color: #2b91af;">Road</span>&gt;();<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">foreach</span> (<span style="color: #2b91af;">Item</span> item <span style="color: blue;">in</span> roadsProxy.items)<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">int</span> itemId = <span style="color: blue;">int</span>.Parse(item.id);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">Road</span> road = _iw360.GetModelItem&lt;<span style="color: #2b91af;">Road</span>&gt;(_modelId, <span style="color: #a31515;">&quot;roads&quot;</span>, <span style="color: #a31515;">&quot;roads&quot;</span>, itemId);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (<span style="color: blue;">string</span>.IsNullOrWhiteSpace(road.name)) <span style="color: blue;">continue</span>; <span style="color: green;">// skip roads with no name</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _roads.Add(road);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (_roads.Count &gt; 2) <span style="color: blue;">break</span>; <span style="color: green;">// list only the first 3, due internet speed</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }<br />&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// list all roads</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">int</span> r = 0;<br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">foreach</span> (<span style="color: #2b91af;">Road</span> road <span style="color: blue;">in</span> _roads)<br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; r++;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ed.WriteMessage(<span style="color: #a31515;">&quot;\n{0} - {1} (ID: {2})&quot;</span>, r, road.name, road.id);<br />&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// ask the user to choose one model</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">PromptIntegerOptions</span> pio = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">PromptIntegerOptions</span>(<span style="color: #a31515;">&quot;\nEnter road number: &quot;</span>);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; pio.AllowZero = <span style="color: blue;">true</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; pio.AllowNegative = <span style="color: blue;">false</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; pio.UpperLimit = r;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">PromptIntegerResult</span> pir = ed.GetInteger(pio);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (pir.Status != <span style="color: #2b91af;">PromptStatus</span>.OK) <span style="color: blue;">return</span>;<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// 4. Import points from the selected Road</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// *********************************************</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (pir.Value == 0)<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// create all roads</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">foreach</span>(<span style="color: #2b91af;">Road</span> road <span style="color: blue;">in</span> _roads)<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; CreateCivil3DAlignment(road); <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">else</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// create just the selected road</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; CreateCivil3DAlignment(_roads[pir.Value - 1]); <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }<br />&#0160;&#0160;&#0160;&#0160;&#0160; }<br />&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160; <span style="color: blue;">private</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: blue;">void</span> CreateCivil3DAlignment(<span style="color: #2b91af;">Road</span> road)<br />&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (road.geometry.Type != <span style="color: #2b91af;">AiwGeometryType</span>.LineString) <span style="color: blue;">return</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">AiwLineString</span> lineString = road.geometry <span style="color: blue;">as</span>&#0160;<span style="color: #2b91af;">AiwLineString</span>;<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// start an AutoCAD transaction</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">Database</span> db = <span style="color: #2b91af;">Application</span>.DocumentManager.MdiActiveDocument.Database;<br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">using</span> (<span style="color: #2b91af;">Transaction</span> trans = db.TransactionManager.StartTransaction())<br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// create a polyline with the coordinates</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">Polyline</span> pline = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">Polyline</span>();<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">int</span> p = 0;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">foreach</span> (<span style="color: #2b91af;">AiwCoordinate</span> coordinate <span style="color: blue;">in</span> lineString.Coordinates)<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; pline.AddVertexAt(p,<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">PointConverter</span>.ConvertPointCoordinate(<span style="color: blue;">new</span> Point2d(coordinate.X, coordinate.Y)),<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; 0, 0, 0);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; p++;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// add this polyline to AutoCAD model space</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">BlockTableRecord</span> currentSpace = trans.GetObject(db.CurrentSpaceId,<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">OpenMode</span>.ForWrite) <span style="color: blue;">as</span>&#0160;<span style="color: #2b91af;">BlockTableRecord</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; currentSpace.AppendEntity(pline);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; trans.AddNewlyCreatedDBObject(pline, <span style="color: blue;">true</span>);<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// create the alignment</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; PolylineOptions alignOptions = <span style="color: blue;">new</span> PolylineOptions();<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; alignOptions.EraseExistingEntities = <span style="color: blue;">true</span>;<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; alignOptions.PlineId = pline.Id;<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">CivilDocument</span> civilDoc = <span style="color: #2b91af;">CivilDocument</span>.GetCivilDocument(db);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// create a siteless alignment, at layer 0,<br />       </span><span style="color: green;"> // using Standard style and Standard label set</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">try</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">Alignment</span>.Create(civilDoc, alignOptions, road.name, <span style="color: blue;">string</span>.Empty, <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #a31515;">&quot;0&quot;</span>, <span style="color: #a31515;">&quot;Basic&quot;</span>, <span style="color: #a31515;">&quot;Major and Minor only&quot;</span>);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">catch</span> (System.<span style="color: #2b91af;">Exception</span> ex)<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green;">// skip creating problems, such as duplicated alignment name</span><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ed.WriteMessage(<span style="color: #a31515;">&quot;\nCould not create {0}: {1}&quot;</span>, road.name, ex.Message);<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; trans.Commit();<br />&#0160;&#0160;&#0160;&#0160;&#0160; }<br />&#0160;&#0160;&#0160; }<br /> <br />&#0160;&#0160;&#0160; <span style="color: blue;">private</span>&#0160;<span style="color: blue;">static</span>&#0160;<span style="color: #2b91af;">Editor</span> ed<br />&#0160;&#0160;&#0160; { <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">get</span><br />&#0160;&#0160;&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue;">return</span>&#0160;<span style="color: #2b91af;">Application</span>.DocumentManager.MdiActiveDocument.Editor; <br />&#0160;&#0160;&#0160;&#0160;&#0160; } <br />&#0160;&#0160;&#0160; }<br />&#0160; }<br />}</pre>
<p>To run this code, you’ll need a model on IW360. The following model from Moscow Kremlin area was created using the Model Builder feature.</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb079a62c7970d-pi"><img alt="IW360_Kremlin" border="0" height="275" src="/assets/image_7c4e15.jpg" style="display: inline; border: 0px;" title="IW360_Kremlin" width="468" /></a></p>
<p>After run this code, we’ll have a good number of alignments with the same name as the roads on the IW360 project. Note that the coordinate system was adjusted, I removed the styles labels for simplicity.</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c6f54192970b-pi"><img alt="C3D_Kremlin" border="0" height="188" src="/assets/image_447611.jpg" style="display: inline; border: 0px;" title="C3D_Kremlin" width="470" /></a></p>
