---
layout: "post"
title: "Read coordinates of line features with Map 3D API"
date: "2014-07-10 01:39:15"
author: "Daniel Du"
categories:
  - ".NET"
  - "AutoCAD Civil 3D 2013"
  - "AutoCAD Civil 3D 2014"
  - "AutoCAD Map 3D 2013"
  - "AutoCAD Map 3D 2014"
  - "Daniel Du"
  - "FDO"
  - "Map 3D"
original_url: "https://adndevblog.typepad.com/infrastructure/2014/07/read-coordinates-of-line-features-with-map-3d-api.html "
typepad_basename: "read-coordinates-of-line-features-with-map-3d-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/daniel-du.html">Daniel Du</a></p>  <p>I am asked how to get the coordinates of each vertices from a line feature, for example, a line feature which is created from an AutoCAD polyline .</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a73de9e02c970d-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="image" src="/assets/image_ce77a6.jpg" width="405" height="225" /></a> </p>  <p>For an AutoCAD polyline which only contains lines, when it is converted to feature with Map 3D command “Create from Geometry”, the feature type will be MgCurveString which contains only one linear segments. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a3fd2ede04970b-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="image" src="/assets/image_d02e17.jpg" width="409" height="200" /></a> </p>  <p></p>  <p>For AutoCAD polyline which contains arc, the feature after conversion will be several segments, including arc segments and linear segments. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a511de91f6970c-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="image" src="/assets/image_6efc19.jpg" width="406" height="263" /></a> </p>  <p>&#160;</p>  <p>Here is the code snippet: </p>  <pre style="font-size: 13px; font-family: consolas; background: white; color: black"><span style="color: blue">using</span> System;<br /><span style="color: blue">using</span> Autodesk.AutoCAD.Runtime;<br /><span style="color: blue">using</span> Autodesk.AutoCAD.ApplicationServices;<br /><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;<br /><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;<br /><span style="color: blue">using</span> Autodesk.AutoCAD.EditorInput;<br /><span style="color: blue">using</span> Autodesk.Gis.Map.Platform.Interop;<br /><span style="color: blue">using</span> Autodesk.Gis.Map.Platform;<br /><span style="color: blue">using</span> OSGeo.MapGuide;<br /> <br /><span style="color: green">// This line is not mandatory, but improves loading performances</span><br />[<span style="color: blue">assembly</span>: <span style="color: #2b91af">CommandClass</span>(<span style="color: blue">typeof</span>(GetFeatureType.<span style="color: #2b91af">MyCommands</span>))]<br /> <br /><span style="color: blue">namespace</span> GetFeatureType<br />{<br /> <br /><span style="color: blue">public</span>&#160;<span style="color: blue">class</span>&#160;<span style="color: #2b91af">MyCommands</span><br />{<br /> <br /> <br /><span style="color: green">// Modal Command with localized name</span><br />[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;getPolylineCoordinates&quot;</span>)]<br /><span style="color: blue">public</span>&#160;<span style="color: blue">void</span> MyCommand() <span style="color: green">// This method can have any name</span><br />{<br />&#160;&#160;&#160; <span style="color: #2b91af">Editor</span> ed = Autodesk.AutoCAD.ApplicationServices.<span style="color: #2b91af">Application</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .DocumentManager.MdiActiveDocument.Editor;<br /> <br />&#160;&#160;&#160; <span style="color: #2b91af">Transaction</span> trans = Autodesk.AutoCAD.ApplicationServices.<span style="color: #2b91af">Application</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .DocumentManager.MdiActiveDocument.Database.TransactionManager<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .StartTransaction();<br /> <br />&#160;&#160;&#160; <span style="color: blue">using</span> (trans)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the Map Object</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">AcMapMap</span> currentMap = <span style="color: #2b91af">AcMapMap</span>.GetCurrentMap();<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Prompt user to Select Feature in Map</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptSelectionOptions</span> psop = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">PromptSelectionOptions</span>();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; psop.MessageForAdding = <span style="color: #a31515">&quot;Select the FDO Feature in Map 3D to read Data : &quot;</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; psop.SingleOnly = <span style="color: blue">true</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptSelectionResult</span> psResult = ed.GetSelection(psop);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (psResult.Status == <span style="color: #2b91af">PromptStatus</span>.OK)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SelectionSet</span> selSet = psResult.Value;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get Map Selectionset from AutoCAD SelectionSet</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">MgSelectionBase</span> mapSelBase = <span style="color: #2b91af">AcMapFeatureEntityService</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .GetSelection(selSet);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">AcMapLayer</span> mapLayer = <span style="color: #2b91af">AcMapFeatureEntityService</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .GetLayer(psResult.Value[0].ObjectId);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Get the ID of the selected Parcel</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">MgFeatureReader</span> ftrRdr = mapSelBase.GetSelectedFeatures(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; mapLayer, mapLayer.FeatureClassName, <span style="color: blue">false</span>);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">while</span> (ftrRdr.ReadNext())<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">MgClassDefinition</span> cd = ftrRdr.GetClassDefinition();<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//the geomety property name maybe different for your </span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//data source </span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">MgByteReader</span> byteRdr = ftrRdr.GetGeometry(<span style="color: #a31515">&quot;Geometry&quot;</span>);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">MgAgfReaderWriter</span> wtr = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">MgAgfReaderWriter</span>();<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">MgGeometry</span> geom = wtr.Read(byteRdr);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (geom <span style="color: blue">is</span> OSGeo.MapGuide.<span style="color: #2b91af">MgCurveString</span>)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> cs = geom <span style="color: blue">as</span>&#160;<span style="color: #2b91af">MgCurveString</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;\n geo is MgCurveString.&quot;</span>);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">for</span> (<span style="color: blue">int</span> i = 0, segmentCount = cs.Count; i &lt; segmentCount; i++)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> seg = cs.GetSegment(i);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (seg <span style="color: blue">is</span>&#160;<span style="color: #2b91af">MgArcSegment</span>)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;\nthis is an Arc Segment.&quot;</span>);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> arcSeg = seg <span style="color: blue">as</span>&#160;<span style="color: #2b91af">MgArcSegment</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">string</span> msg = <span style="color: blue">string</span>.Format(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\nstart point: x= {0}, y={1}&quot;</span>,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arcSeg.StartCoordinate.X,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arcSeg.StartCoordinate.Y);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(msg);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; msg = <span style="color: blue">string</span>.Format(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\ncontrol point&#160; x= {0}, y={1}&quot;</span>,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arcSeg.ControlCoordinate.X,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arcSeg.ControlCoordinate.Y);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(msg);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; msg = <span style="color: blue">string</span>.Format(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\nend point: x= {0}, y={1}&quot;</span>,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arcSeg.EndCoordinate.X,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arcSeg.EndCoordinate.Y);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(msg);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (seg <span style="color: blue">is</span>&#160;<span style="color: #2b91af">MgLinearSegment</span>)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;\nthis is a linear Segment.&quot;</span>);<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> linearSeg = seg <span style="color: blue">as</span>&#160;<span style="color: #2b91af">MgLinearSegment</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> interator = linearSeg.GetCoordinates();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">while</span> (interator.MoveNext())<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> x = interator.GetCurrent().X;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> y = interator.GetCurrent().Y;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: blue">string</span>.Format(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\n x = {0}, y={1} &quot;</span>, x, y));<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (geom <span style="color: blue">is</span> OSGeo.MapGuide.<span style="color: #2b91af">MgLineString</span>)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ls = geom <span style="color: blue">as</span>&#160;<span style="color: #2b91af">MgLineString</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> interator = ls.GetCoordinates();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">while</span> (interator.MoveNext())<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> x = interator.GetCurrent().X;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> y = interator.GetCurrent().Y;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: blue">string</span>.Format(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\n x = {0}, y={1} &quot;</span>, x, y));<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit();<br />&#160;&#160;&#160; }<br /> <br />}<br /> <br /> <br /> <br />}<br /> <br />}</pre>

<pre style="font-size: 13px; font-family: consolas; background: white; color: black"><br /></pre>
