---
layout: "post"
title: "Understanding Civil 3D labels and features"
date: "2014-11-14 08:52:28"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "AutoCAD Civil 3D 2015"
original_url: "https://adndevblog.typepad.com/infrastructure/2014/11/understanding-civil-3d-labels-and-features.html "
typepad_basename: "understanding-civil-3d-labels-and-features"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>Civil 3D uses a base class <strong>LabelBase</strong> to handle labels and the features that itâ€™s being labeled. This is done using the <strong>FeatureId</strong> property, which is available for all labels. The following code show a generic approach for this.</p>  <pre style="font-size: 12px; font-family: consolas; background: white; color: black">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;testReadLabelFeature&quot;</span>)]<br /><span style="color: blue">public</span>&#160;<span style="color: blue">void</span> CmdReadLabelFeature()<br />{<br />&#160; <span style="color: #2b91af">Database</span> db = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Database;<br />&#160; <span style="color: #2b91af">Editor</span> ed = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Editor;<br /> <br />&#160; <span style="color: #2b91af">PromptEntityOptions</span> peo = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">PromptEntityOptions</span>(<span style="color: #a31515">&quot;\nSelect a label: &quot;</span>);<br />&#160; peo.SetRejectMessage(<span style="color: #a31515">&quot;\nPlease select a Label, try again.&quot;</span>);<br />&#160; peo.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">LabelBase</span>), <span style="color: blue">true</span>);<br />&#160; <span style="color: #2b91af">PromptEntityResult</span> per = ed.GetEntity(peo);<br />&#160; <span style="color: blue">if</span> (per.Status != <span style="color: #2b91af">PromptStatus</span>.OK) <span style="color: blue">return</span>;<br /> <br />&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> tr = db.TransactionManager.StartTransaction())<br />&#160; {<br />&#160;&#160;&#160; <span style="color: green">// open the label</span><br />&#160;&#160;&#160; <span style="color: #2b91af">LabelBase</span> genericLabel = tr.GetObject(per.ObjectId, <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">LabelBase</span>;<br /> <br />&#160;&#160;&#160; <span style="color: green">// open the entity that this label points to</span><br />&#160;&#160;&#160; Autodesk.AutoCAD.DatabaseServices.<span style="color: #2b91af">Entity</span> featureEnt = tr.GetObject(<br />&#160;&#160;&#160;&#160;&#160; genericLabel.FeatureId, <span style="color: #2b91af">OpenMode</span>.ForRead) <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">as</span> Autodesk.AutoCAD.DatabaseServices.<span style="color: #2b91af">Entity</span>;<br /> <br />&#160;&#160;&#160; <span style="color: blue">if</span> (featureEnt != <span style="color: blue">null</span>)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// now we know this label points to an entity... </span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// is it the one we need?</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (featureEnt <span style="color: blue">is</span>&#160;<span style="color: #2b91af">Pipe</span>)<br />&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// is a Pipe, can do something related to PipeLabel</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PipeLabel</span> pipeLabel = genericLabel <span style="color: blue">as</span>&#160;<span style="color: #2b91af">PipeLabel</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Pipe</span> pipe = featureEnt <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Pipe</span>;<br />&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160; }<br />&#160;&#160;&#160; <span style="color: blue">else</span><br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// make a test to ensure is valid</span><br />&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;\nThis label is not linked to an entity. Sorry&quot;</span>);<br />&#160;&#160;&#160; }<br />&#160;&#160;&#160; tr.Commit();<br />&#160; }<br />}</pre>
