---
layout: "post"
title: "Alignment Sample Line Intersection"
date: "2014-10-31 07:58:00"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "AutoCAD Civil 3D 2015"
original_url: "https://adndevblog.typepad.com/infrastructure/2014/10/alignment-sample-line-intersection.html "
typepad_basename: "alignment-sample-line-intersection"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>This question came from <a href="http://www.maubertec.com.br">Grace Ferrari</a>: from a given alignment (e.g. Alignment 01) with sample lines, how can I find the intersection of each sample line on another alignment (e.g. Alignment 02). The image below show the scenario, thanks Grace for sharing the image.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d087ea55970c-pi"><img title="Explanation" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="Explanation" src="/assets/image_6a2fe8.jpg" width="482" height="301" /></a> </p>  <p>To implement this I decided to try something that I was willing to understand for a while: custom <em>foreach</em> on .NET. Also, we need to use Extensions to make it fun.</p>  <p>The first piece is quite straight forward: select both alignments and open them for read. Also, draw AutoCAD DBPoints (plain points) at each intersection. Below is the code.</p>  <pre style="font-size: 12px; font-family: consolas; background: white; color: black">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;testDrawPointsIntersection&quot;</span>)]<br /><span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: blue">void</span> CmdDrawPointsOnIntersection()<br />{<br />&#160; <span style="color: #2b91af">Editor</span> ed = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Editor;<br /> <br />&#160; <span style="color: green">// select reference alignment</span><br />&#160; <span style="color: green">// this is the alignment with sample lines</span><br />&#160; <span style="color: green">// (for simplicity, this condition is not verified)</span><br />&#160; <span style="color: #2b91af">PromptEntityOptions</span> peo = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">PromptEntityOptions</span>(<br />&#160;&#160;&#160; <span style="color: #a31515">&quot;\nSelect reference alignment (with sample lines): &quot;</span>);<br />&#160; peo.SetRejectMessage(<span style="color: #a31515">&quot;\nOnly alignments&quot;</span>);<br />&#160; peo.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">Alignment</span>), <span style="color: blue">true</span>);<br />&#160; <span style="color: #2b91af">PromptEntityResult</span> per = ed.GetEntity(peo);<br />&#160; <span style="color: blue">if</span> (per.Status != <span style="color: #2b91af">PromptStatus</span>.OK) <span style="color: blue">return</span>;<br />&#160; ObjectId sourceAlignId = per.ObjectId;<br /> <br />&#160; <span style="color: green">// now select the other alignment</span><br />&#160; peo.Message = <span style="color: #a31515">&quot;\nSelect the other alignment: &quot;</span>;<br />&#160; per = ed.GetEntity(peo);<br />&#160; ObjectId otherAlignId = per.ObjectId;<br /> <br />&#160; DrawPointOnSampleLineIntersection(sourceAlignId, otherAlignId);<br />}<br /> <br /><span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: blue">void</span> DrawPointOnSampleLineIntersection(<br />&#160; ObjectId sourceAlignId, ObjectId otherAlignId)<br />{<br />&#160; <span style="color: #2b91af">Database</span> db = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Database;<br />&#160; <span style="color: #2b91af">CivilDocument</span> civilDoc = <span style="color: #2b91af">CivilApplication</span>.ActiveDocument;<br />&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = db.TransactionManager.StartTransaction())<br />&#160; {<br />&#160;&#160;&#160; <span style="color: green">// open both alignments</span><br />&#160;&#160;&#160; <span style="color: #2b91af">Alignment</span> sourceAlign = trans.GetObject(sourceAlignId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Alignment</span>;<br />&#160;&#160;&#160; <span style="color: #2b91af">Alignment</span> otherAlign = trans.GetObject(otherAlignId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Alignment</span>;<br /> <br />&#160;&#160;&#160; <span style="color: green">// open model space (i.e. current space)</span><br />&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> mSpace = trans.GetObject(db.CurrentSpaceId,<br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForWrite) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">BlockTableRecord</span>;<br />&#160;&#160;&#160; <span style="color: blue">foreach</span> (Point3d point <span style="color: blue">in</span> sourceAlign.<strong><span style="background-color: #ffff00">SampleLinesIntersectionWith(otherAlign)</span></strong>)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// point AutoCAD plain points</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">DBPoint</span> newPoint = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">DBPoint</span>(point);<br />&#160;&#160;&#160;&#160;&#160; mSpace.AppendEntity(newPoint);<br />&#160;&#160;&#160;&#160;&#160; trans.AddNewlyCreatedDBObject(newPoint, <span style="color: blue">true</span>);<br />&#160;&#160;&#160; }<br />&#160;&#160;&#160; trans.Commit();<br />&#160; }<br />}</pre>

<p>And now you might wonder: where this <em>SampleLinesIntersectionWith</em> method came from? This is actually a <a href="http://msdn.microsoft.com/en-us/library/bb383977.aspx">extension on .NET</a>. To have this, we need a <em>static public</em> class in C#. We made a <a href="http://adndevblog.typepad.com/autocad/2012/05/extension-methods-in-autocad-2013.html">cool article on this</a>. </p>

<p>Below is the extension class. Note the <em>this</em> on the first parameter, indicating the objects where this extension is applicable.</p>

<pre style="font-size: 12px; font-family: consolas; background: white; color: black"><span style="color: blue">using</span> System;<br /><span style="color: blue">using</span> System.Collections.Generic;<br /><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;<br /><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;<br /><span style="color: blue">using</span> Autodesk.Civil.DatabaseServices;<br /> <br /><span style="color: blue">namespace</span> MyProjectName<br />{<br />&#160; <span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: blue">class</span>&#160;<span style="color: #2b91af">Extensions</span><br />&#160; {<br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;summary&gt;</span><br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Interate on the collection of intersection points</span><br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> from this alignment sample lines on the other alignment</span><br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;/summary&gt;</span><br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;param name=</span><span style="color: gray">&quot;source&quot;</span><span style="color: gray">&gt;</span><span style="color: green">This base/reference alignment</span><span style="color: gray">&lt;/param&gt;</span><br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;param name=</span><span style="color: gray">&quot;other&quot;</span><span style="color: gray">&gt;</span><span style="color: green">Other alignment</span><span style="color: gray">&lt;/param&gt;</span><br />&#160;&#160;&#160; <span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: #2b91af">IEnumerable</span>&lt;Point3d&gt; SampleLinesIntersectionWith(<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">this</span>&#160;<span style="color: #2b91af">Alignment</span> source, <span style="color: #2b91af">Alignment</span> other)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// get the base curve for the base alignment</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Curve</span> baseCurveAlign2 = other.BaseCurve;<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = source.Database.TransactionManager.StartTransaction())<br />&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// get the collection of sample lines on the base alignment</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">ObjectIdCollection</span> sLineGroupIds = source.GetSampleLineGroupIds();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (ObjectId sLineGroupId <span style="color: blue">in</span> sLineGroupIds)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// for each sample line group, get all sample lines</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SampleLineGroup</span> sLineGroup = trans.GetObject(sLineGroupId,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">SampleLineGroup</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">ObjectIdCollection</span> sLineIds = sLineGroup.GetSampleLineIds();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (ObjectId sLineId <span style="color: blue">in</span> sLineIds)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// for each sample line, use the GetBasePLine to get the base curve/pline</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SampleLine</span> sLine = trans.GetObject(sLineId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">SampleLine</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Polyline</span> baseCurveSampleLine = sLine.GetBasePLine())<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// finally find the intersection</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Point3dCollection</span> points = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Point3dCollection</span>();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; baseCurveAlign2.IntersectWith(baseCurveSampleLine,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Intersect</span>.OnBothOperands, points, IntPtr.Zero, IntPtr.Zero);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (points.Count &gt; 0)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">yield</span>&#160;<span style="color: blue">return</span> points[0]; <span style="color: green">// this will yield for each point</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit(); <span style="color: green">// commit, otherwise the outer transaction will abort</span><br />&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;summary&gt;</span><br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Get a Polyline for this SampleLine</span><br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;/summary&gt;</span><br />&#160;&#160;&#160; <span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: #2b91af">Polyline</span> GetBasePLine(<span style="color: blue">this</span>&#160;<span style="color: #2b91af">SampleLine</span> sline)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Polyline</span> pline = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Polyline</span>();<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">int</span> v = 0;<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">SampleLineVertex</span> vertex <span style="color: blue">in</span> sline.Vertices)<br />&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; pline.AddVertexAt(v,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vertex.Location.Convert2d(<span style="color: blue">new</span>&#160;<span style="color: #2b91af">Plane</span>()),<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 0, 0, 0);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; v++;<br />&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> pline;<br />&#160;&#160;&#160; }<br />&#160; }<br />}</pre>
