---
layout: "post"
title: "Read TinVolumeSurface triangles in Civil 3D"
date: "2015-05-14 14:53:30"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "AutoCAD Civil 3D"
original_url: "https://adndevblog.typepad.com/infrastructure/2015/05/read-tinvolumesurface-triangles-in-civil-3d.html "
typepad_basename: "read-tinvolumesurface-triangles-in-civil-3d"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>The TinSurface object has a Triangle property, which allow access to the list of triangles of the surface. But the TinVolumeSurface does not offer this property. The workaround is to use the COM version of this object, AeccTinVolumeSurface, which has a <a href="http://docs.autodesk.com/CIV3D/2012/ENU/API_Reference_Guide/com/AeccXLandLib__IAeccTinVolumeSurface__OutputTriangles@[out,retval]_VARIANT_.htm">OutputTriangles property</a>, that returns a array of doubles, but this need to be interpreted as points (XYZ coordinates). </p>  <p>On C# this property can be used with <a href="https://msdn.microsoft.com/en-us/library/dd264736.aspx">dynamic types</a>, which allow late-binding of COM Interop types. To make the points, it’s a matter of playing with arrays.</p>  <p>At this sample you’ll find a Triangle and TriangleCollection classes to use this array of doubles. This sample also create AutoCAD Faces of each triangle, just for testing.</p>  <pre style="font-size: 13px; font-family: consolas; background: white; color: black">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;getTriangles&quot;</span>)]<br /><span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: blue">void</span> CmdGetTriangles()<br />{<br />&#160; <span style="color: #2b91af">Editor</span> ed = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Editor;<br /> <br />&#160; <span style="color: #2b91af">PromptEntityOptions</span> peo = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">PromptEntityOptions</span>(<br />&#160;&#160;&#160; <span style="color: #a31515">&quot;\nSelect tin volume surface: &quot;</span>);<br />&#160; peo.SetRejectMessage(<span style="color: #a31515">&quot;\nOnly tin volume surface&quot;</span>);<br />&#160; peo.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">TinVolumeSurface</span>), <span style="color: blue">true</span>);<br />&#160; <span style="color: #2b91af">PromptEntityResult</span> per = ed.GetEntity(peo);<br />&#160; <span style="color: blue">if</span> (per.Status != <span style="color: #2b91af">PromptStatus</span>.OK) <span style="color: blue">return</span>;<br /> <br />&#160; <span style="color: #2b91af">Database</span> db = <span style="color: #2b91af">Application</span>.DocumentManager.<br />&#160;&#160;&#160; MdiActiveDocument.Database;<br />&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = db.TransactionManager.<br />&#160;&#160;&#160; StartOpenCloseTransaction())<br />&#160; {<br />&#160;&#160;&#160; <span style="color: #2b91af">TinVolumeSurface</span> tvs = trans.GetObject(<br />&#160;&#160;&#160;&#160;&#160; per.ObjectId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">TinVolumeSurface</span>;<br />&#160;&#160;&#160; <span style="color: blue">dynamic</span> tvsCOM = tvs.AcadObject; <span style="color: green">// get the COM representation</span><br />&#160;&#160;&#160; <span style="color: #2b91af">TriangleCollection</span> triangles = <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">TriangleCollection</span>(tvsCOM.OutputTriangles);<br /> <br />&#160;&#160;&#160; <span style="color: green">// for testing, let's create faces using the triangle data</span><br />&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> currSpace = trans.GetObject(<br />&#160;&#160;&#160;&#160;&#160; db.CurrentSpaceId, <span style="color: #2b91af">OpenMode</span>.ForWrite) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">BlockTableRecord</span>;<br />&#160;&#160;&#160; <span style="color: blue">foreach</span>(<span style="color: #2b91af">Triangle</span> t <span style="color: blue">in</span> triangles)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Face</span> f = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Face</span>(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; t.Vertex1, t.Vertex2, t.Vertex3, <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">true</span>, <span style="color: blue">true</span>, <span style="color: blue">true</span>, <span style="color: blue">true</span>);<br />&#160;&#160;&#160;&#160;&#160; currSpace.AppendEntity(f);<br />&#160;&#160;&#160;&#160;&#160; trans.AddNewlyCreatedDBObject(f, <span style="color: blue">true</span>);<br />&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160; trans.Commit();<br />&#160; }<br />}<br /> <br /><span style="color: blue">public</span>&#160;<span style="color: blue">class</span>&#160;<span style="color: #2b91af">TriangleCollection</span> : <span style="color: #2b91af">List</span>&lt;<span style="color: #2b91af">Triangle</span>&gt;<br />{<br />&#160; <span style="color: blue">public</span> TriangleCollection(<span style="color: blue">double</span>[] arrayDoubles)<br />&#160; {<br />&#160;&#160;&#160; <span style="color: blue">if</span> (arrayDoubles.Length % 9 != 0) <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">throw</span>&#160;<span style="color: blue">new</span>&#160;<span style="color: #2b91af">ArgumentException</span>(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Double array must have mulitple of 9 values.&quot;</span>);<br /> <br />&#160;&#160;&#160; <span style="color: blue">int</span> numberOfDoubles = arrayDoubles.Length;<br />&#160;&#160;&#160; <span style="color: blue">int</span> numberOfPoints = numberOfDoubles / 3 / 3;<br />&#160;&#160;&#160; <span style="color: blue">for</span> (<span style="color: blue">int</span> p = 0; p &lt; numberOfPoints; p++)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span>[] pointValues = <span style="color: blue">new</span>&#160;<span style="color: blue">double</span>[9];<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">for</span> (<span style="color: blue">int</span> v = 0; v &lt; 9; v++)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; pointValues[v] = arrayDoubles[p * 9 + v];<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">base</span>.Add(<span style="color: blue">new</span>&#160;<span style="color: #2b91af">Triangle</span>(pointValues));<br />&#160;&#160;&#160; }<br />&#160; }<br />}<br /> <br /><span style="color: blue">public</span>&#160;<span style="color: blue">struct</span>&#160;<span style="color: #2b91af">Triangle</span><br />{<br />&#160; <span style="color: blue">private</span>&#160;<span style="color: #2b91af">Point3d</span>[] _points;<br /> <br />&#160; <span style="color: blue">public</span> Triangle(<span style="color: blue">double</span>[] values)<br />&#160; {<br />&#160;&#160;&#160; <span style="color: blue">if</span> (values.Length != 9) <span style="color: blue">throw</span>&#160;<span style="color: blue">new</span>&#160;<span style="color: #2b91af">ArgumentException</span>(<br />&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Double array must have 9 values.&quot;</span>);<br /> <br />&#160;&#160;&#160; _points = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Point3d</span>[3];<br />&#160;&#160;&#160; <span style="color: blue">for</span> (<span style="color: blue">int</span> p = 0; p &lt; 3; p++)<br />&#160;&#160;&#160;&#160;&#160; _points[p] = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Point3d</span>(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; values[p * 3],<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; values[p * 3 + 1],<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; values[p * 3 + 2]);<br />&#160; }<br /> <br />&#160; <span style="color: blue">public</span>&#160;<span style="color: #2b91af">Point3d</span> Vertex1 { <span style="color: blue">get</span> { <span style="color: blue">return</span> _points[0]; } }<br />&#160; <span style="color: blue">public</span>&#160;<span style="color: #2b91af">Point3d</span> Vertex2 { <span style="color: blue">get</span> { <span style="color: blue">return</span> _points[1]; } }<br />&#160; <span style="color: blue">public</span>&#160;<span style="color: #2b91af">Point3d</span> Vertex3 { <span style="color: blue">get</span> { <span style="color: blue">return</span> _points[2]; } }<br />}</pre>
