---
layout: "post"
title: "Using JIG with Civil 3D Labels"
date: "2015-07-15 05:30:02"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "AutoCAD Civil 3D"
original_url: "https://adndevblog.typepad.com/infrastructure/2015/07/using-jig-with-civil-3d-labels.html "
typepad_basename: "using-jig-with-civil-3d-labels"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>This is based on <a href="http://through-the-interface.typepad.com/through_the_interface/2008/03/using-a-jig-to.html">Keanâ€™s original post for AutoCAD entities</a>, but adjusted to Move (instead Rotate) and using the Label specific property: <strong>LabelLocation</strong>.</p>  <p>Some background: JIG is an AutoCAD API feature to manipulate objects on screen, but with the ability to actually drag them around (rotate, move, scale, adjust) while seeing the object.</p>  <p>For labels, the final behavior is interesting as we can see the pointer adjusting while the location is also dragged with the cursor. </p>  <p>Enough said, here is the sample code.</p>  <p><span style="color: blue">using</span> Autodesk.AutoCAD.ApplicationServices;     <br /><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;     <br /><span style="color: blue">using</span> Autodesk.AutoCAD.EditorInput;     <br /><span style="color: blue">using</span> Autodesk.AutoCAD.Runtime;     <br /><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;     <br />    <br /><span style="color: blue">using</span> Autodesk.Civil.DatabaseServices;     <br />    <br /><span style="color: blue">namespace</span> SampleTesting     <br />{     <br />&#160; <span style="color: blue">public</span>&#160;<span style="color: blue">class</span>&#160;<span style="color: #2b91af">MovelLabelJig</span> : <span style="color: #2b91af">EntityJig</span>     <br />&#160; {     <br />&#160;&#160;&#160; <span style="color: #2b91af">Point3d</span> _location;     <br />    <br />&#160;&#160;&#160; <span style="color: blue">public</span> MovelLabelJig(<span style="color: #2b91af">Label</span> lbl)     <br />&#160;&#160;&#160;&#160;&#160; : <span style="color: blue">base</span>(lbl.Clone() <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Label</span>)     <br />&#160;&#160;&#160; {     <br />&#160;&#160;&#160;&#160;&#160; _location = lbl.LabelLocation;     <br />&#160;&#160;&#160; }     <br />    <br />&#160;&#160;&#160; <span style="color: blue">protected</span>&#160;<span style="color: blue">override</span>&#160;<span style="color: blue">bool</span> Update()     <br />&#160;&#160;&#160; {     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// adjust the entity on screen</span>     <br />&#160;&#160;&#160;&#160;&#160; ((<span style="color: #2b91af">Label</span>)Entity).LabelLocation = _location;     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: blue">true</span>;     <br />&#160;&#160;&#160; }     <br />    <br />&#160;&#160;&#160; <span style="color: blue">protected</span>&#160;<span style="color: blue">override</span>&#160;<span style="color: #2b91af">SamplerStatus</span> Sampler(     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">JigPrompts</span> prompts)     <br />&#160;&#160;&#160; {     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// get the new location (on cursor move)</span>     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">JigPromptPointOptions</span> jppo =     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">JigPromptPointOptions</span>(<span style="color: #a31515">&quot;Move label: &quot;</span>);     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptPointResult</span> pdr = prompts.AcquirePoint(jppo);     <br />    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// check if is OK</span>     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (pdr.Status != <span style="color: #2b91af">PromptStatus</span>.OK)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">SamplerStatus</span>.Cancel;     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (pdr.Value.DistanceTo(_location)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; &lt; <span style="color: #2b91af">Tolerance</span>.Global.EqualPoint)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">SamplerStatus</span>.NoChange;     <br />    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// and store the new valuye</span>     <br />&#160;&#160;&#160;&#160;&#160; _location = pdr.Value;     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">SamplerStatus</span>.OK;     <br />&#160;&#160;&#160; }     <br />    <br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;summary&gt;</span>     <br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Return the new location, during/after JIG</span>     <br />&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green">&#160;</span><span style="color: gray">&lt;/summary&gt;</span>     <br />&#160;&#160;&#160; <span style="color: blue">public</span>&#160;<span style="color: #2b91af">Point3d</span> Location { <span style="color: blue">get</span> { <span style="color: blue">return</span> _location; } }     <br />    <br />&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;moveLabel&quot;</span>)]     <br />&#160;&#160;&#160; <span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: blue">void</span> CmdMoveLabel()     <br />&#160;&#160;&#160; {     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Editor</span> ed = <span style="color: #2b91af">Application</span>.DocumentManager     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .MdiActiveDocument.Editor;     <br />    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// select the label</span>     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptEntityOptions</span> peo =     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">PromptEntityOptions</span>(<span style="color: #a31515">&quot;\nSelect a label to move: &quot;</span>);     <br />&#160;&#160;&#160;&#160;&#160; peo.SetRejectMessage(<span style="color: #a31515">&quot;\nLabels only&quot;</span>);     <br />&#160;&#160;&#160;&#160;&#160; peo.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">Label</span>), <span style="color: blue">false</span>);     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptEntityResult</span> per = ed.GetEntity(peo);     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (per.Status != <span style="color: #2b91af">PromptStatus</span>.OK) <span style="color: blue">return</span>;     <br />    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// start a transaction</span>     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Database</span> db = <span style="color: #2b91af">Application</span>.DocumentManager     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .MdiActiveDocument.Database;     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = db.     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; TransactionManager.StartTransaction())     <br />&#160;&#160;&#160;&#160;&#160; {     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// open the label object</span>     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Label</span> lbl = trans.GetObject(per.ObjectId,     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Label</span>;     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// start the JIG drag</span>     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">MovelLabelJig</span> jig = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">MovelLabelJig</span>(lbl);     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PromptResult</span> pr = ed.Drag(jig);     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// if not OK, clean return</span>     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (pr.Status != <span style="color: #2b91af">PromptStatus</span>.OK) <span style="color: blue">return</span>;     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// everything ok, update the location</span>     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; lbl.UpgradeOpen();     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; lbl.LabelLocation = jig.Location;     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit();     <br />&#160;&#160;&#160;&#160;&#160; }     <br />&#160;&#160;&#160; }     <br />&#160; }     <br />} </p>
