---
layout: "post"
title: "Spiral Curve Spiral PI &ndash; Playing with Math"
date: "2015-08-07 09:32:53"
author: "Augusto Goncalves"
categories: []
original_url: "https://adndevblog.typepad.com/infrastructure/2015/08/spiral-curve-spiral-pi-playing-with-math.html "
typepad_basename: "spiral-curve-spiral-pi-playing-with-math"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/infrastructure/augusto-goncalves.html">Augusto Goncalves</a> (@<a href="https://twitter.com/augustomaia">augustomaia</a>)</p>  <p>First, from the AutoCAD Civil 3D Knowledge Network, review the topic <a href="http://knowledge.autodesk.com/support/autocad-civil-3d/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Civil3D-UserGuide/files/GUID-DD7C0EA1-8465-45BA-9A39-FC05106FD822-htm.html">About Spiral Definitions</a>. The following image summarize the article. We’re interested in start direction from <u>Spiral In</u> and end direction at <u>Spiral Out</u>.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d14533fb970c-pi"><img title="scs" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="scs" src="/assets/image_12433e.jpg" width="333" height="195" /></a> </p>  <p>At the API we have the <strong>AlignmentSCS</strong> object with only the direction, which is actually an angle, at the <strong>SpiralIn.StartDirection</strong> and <strong>SpiralOut.EndDirection</strong> properties. </p>  <p>Now let’s have some fun with the math piece: the direction vector is the Sin and Cos of this direction (which is actually the tangent). Here an image definition from <a href="https://en.wikipedia.org/wiki/File:Sin-cos-defn-I.svg">Wikipedia</a>:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d1453404970c-pi"><img title="247px-Sin-cos-defn-I.svg[1]" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="247px-Sin-cos-defn-I.svg[1]" src="/assets/image_1c284a.jpg" width="244" height="237" /></a></p>  <p>From this definition we can create a Vector2d at both ends (<strong>SpiralIn.StartDirection</strong> and <strong>SpiralOut.EndDirection</strong>), then use Line2d to create lines and, finally, the intersection. Here is the code:</p>  <pre style="font-size: 13px; font-family: consolas; background: white; color: black"><span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: #2b91af">Point2d</span> PI(<span style="color: blue">this</span>&#160;<span style="color: #2b91af">AlignmentSCS</span> scs)<br />{<br />&#160; <span style="color: green">// vector at SpiralIn.StartDirection</span><br />&#160; <span style="color: #2b91af">Vector2d</span> vectorIn = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Vector2d</span>(<br />&#160;&#160;&#160; <span style="color: #2b91af">Math</span>.Sin(scs.SpiralIn.StartDirection),<br />&#160;&#160;&#160; <span style="color: #2b91af">Math</span>.Cos(scs.SpiralIn.StartDirection));<br /> <br />&#160; <span style="color: green">// vector at SpirtalOut.EndDirection</span><br />&#160; <span style="color: green">// negate to get the inner vector</span><br />&#160; <span style="color: green">// redundant as the line is infinite</span><br />&#160; <span style="color: #2b91af">Vector2d</span> vectorOut = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Vector2d</span>(<br />&#160;&#160;&#160; <span style="color: #2b91af">Math</span>.Sin(scs.SpiralOut.EndDirection),<br />&#160;&#160;&#160; <span style="color: #2b91af">Math</span>.Cos(scs.SpiralOut.EndDirection)).Negate();<br /> <br />&#160; <span style="color: green">// create line from start</span><br />&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Line2d</span> lineIn = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Line2d</span>(<br />&#160;&#160;&#160; scs.SpiralIn.StartPoint, vectorIn))<br />&#160; {<br />&#160;&#160;&#160; <span style="color: green">// and create line from end</span><br />&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Line2d</span> lineOut = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Line2d</span>(<br />&#160;&#160;&#160;&#160;&#160; scs.SpiralOut.EndPoint, vectorOut))<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// now find the intersection</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Point2d</span>[] intersectPoints = lineIn.IntersectWith(lineOut);<br /> <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// some minor error check</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (intersectPoints == <span style="color: blue">null</span> || intersectPoints.Length == 0)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">throw</span>&#160;<span style="color: blue">new</span> Autodesk.Civil.<span style="color: #2b91af">CivilException</span>(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Could not find PI for this SCS&quot;</span>);<br /> <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// should be just one point, return it</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> intersectPoints[0];<br />&#160;&#160;&#160; }<br />&#160; }<br />}</pre>

<p>We can use this method with Extension, as it was declared with <strong>this</strong>. Below is a command method that uses it:</p>

<pre style="font-size: 13px; font-family: consolas; background: white; color: black">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;getSCSPI&quot;</span>)]<br /><span style="color: blue">public</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: blue">void</span> CmdGetSCSPI()<br />{<br /></pre>

<pre style="font-size: 13px; font-family: consolas; background: white; color: black"><span style="color: green">  // minimum error check...</span><br /><br />&#160; <span style="color: #2b91af">Editor</span> ed = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Editor;<br />&#160; <span style="color: #2b91af">ObjectId</span> id = ed.GetEntity(<span style="color: #a31515">&quot;Select alignment: &quot;</span>).ObjectId;<br /> <br />&#160; <span style="color: #2b91af">Database</span> db = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Database;<br />&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> tr = db.TransactionManager.StartTransaction())<br />&#160; {<br />&#160;&#160;&#160; <span style="color: #2b91af">Alignment</span> align = tr.GetObject(id, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Alignment</span>;<br />&#160;&#160;&#160; <span style="color: blue">if</span> (align == <span style="color: blue">null</span>) <span style="color: blue">return</span>;<br /> <br />&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">AlignmentEntity</span> alignEnt <span style="color: blue">in</span> align.Entities)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// for this test, just SCS, skip others</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (alignEnt.EntityType != <br />        <span style="color: #2b91af">AlignmentEntityType</span>.SpiralCurveSpiral) <span style="color: blue">continue</span>;<br /> <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// finally get the PI (using the extension method)</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">AlignmentSCS</span> scs = alignEnt <span style="color: blue">as</span>&#160;<span style="color: #2b91af">AlignmentSCS</span>;<br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Point2d</span> scsPI = scs.PI();<br /> <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// let's add a point to Model Space</span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">DBPoint</span> newPointAtSCS = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">DBPoint</span>(<br />        <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Point3d</span>(<span style="color: blue">new</span>&#160;<span style="color: #2b91af">Plane</span>(), scsPI));<br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> mSpace = tr.GetObject(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SymbolUtilityServices</span>.GetBlockModelSpaceId(db),<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForWrite) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">BlockTableRecord</span>;<br />&#160;&#160;&#160;&#160;&#160; mSpace.AppendEntity(newPointAtSCS);<br />&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(newPointAtSCS, <span style="color: blue">true</span>);<br />&#160;&#160;&#160; }<br />&#160;&#160;&#160; tr.Commit();<br />&#160; }<br />}</pre>
