---
layout: "post"
title: "Creating constraint in Assembly"
date: "2012-08-16 12:50:24"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/creating-constraint-in-assembly.html "
typepad_basename: "creating-constraint-in-assembly"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>The first sample demonstrates the creation of an assembly mate constraint. Before running the sample, you need to open an assembly that contains at least two parts. Select planar faces on the two parts that will be used for the constraint and run the sample code (Set the priority of the Select command and use the Shift-Select to select multiple faces).</p>  <p>Then the second sample demonstrates creating a mate constraint between two occurrences using the work planes within those occurrences. To use the sample,&#160; have an assembly open that contains at least two occurrences (part or subassembly), and run the program.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">private</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">void</font></span><font color="#000000"> MateConstraint()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//Set a reference to the assembly component definintion.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">AssemblyDocument</font></span><font color="#000000"> oAssDoc = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; m_inventorApp.ActiveDocument </font></font><font style="font-size: 8pt"><span><font color="#0000ff">as</font></span><font color="#000000"> </font><span><font color="#2b91af">AssemblyDocument</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">AssemblyComponentDefinition</font></span><font color="#000000"> oAsmCompDef = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oAssDoc.ComponentDefinition;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// Set a reference to the select set.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">SelectSet</font></span><font color="#000000"> oSelectSet = m_inventorApp.ActiveDocument.SelectSet;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//Validate the correct data is in the select set.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">if</font></span><font color="#000000"> (oSelectSet.Count != 2)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; System.Windows.Forms.</font></font><font style="font-size: 8pt"><span><font color="#2b91af">MessageBox</font></span><font color="#000000">.Show(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;You must select the two entities valid for mate.&quot;</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// Get the two entities from the select set.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">object</font></span><font color="#000000"> oBrepEnt1 = oSelectSet[1];</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">object</font></span><font color="#000000"> oBrepEnt2 = oSelectSet[2];</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//Create the insert constraint between the parts.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">MateConstraint</font></span><font color="#000000"> oMate = oAsmCompDef.Constraints.</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; AddMateConstraint(oBrepEnt1, oBrepEnt2, 0,</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">InferredTypeEnum</font></span><font color="#000000">.kNoInference,</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">InferredTypeEnum</font></span><font color="#000000">.kNoInference, </font><span><font color="#0000ff">null</font></span><font color="#000000">, </font><span><font color="#0000ff">null</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">private</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">void</font></span><font color="#000000"> MateConstraintOfWorkPlanes()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">AssemblyDocument</font></span><font color="#000000"> oAssDoc = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; m_inventorApp.ActiveDocument </font></font><font style="font-size: 8pt"><span><font color="#0000ff">as</font></span><font color="#000000"> </font><span><font color="#2b91af">AssemblyDocument</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">AssemblyComponentDefinition</font></span><font color="#000000"> oAsmCompDef =</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oAssDoc.ComponentDefinition;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//Get references to the two occurrences to constrain.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//This arbitrarily gets the first and second occurrence.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">ComponentOccurrence</font></span><font color="#000000"> oOcc1 = oAsmCompDef.Occurrences[1];</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">ComponentOccurrence</font></span><font color="#000000"> oOcc2 = oAsmCompDef.Occurrences[2];</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PartComponentDefinition</font></span><font color="#000000"> oPartDef1 = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; oOcc1.Definition </font></font><font style="font-size: 8pt"><span><font color="#0000ff">as</font></span><font color="#000000"> </font><span><font color="#2b91af">PartComponentDefinition</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PartComponentDefinition</font></span><font color="#000000"> oPartDef2 = </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; oOcc2.Definition </font></font><font style="font-size: 8pt"><span><font color="#0000ff">as</font></span><font color="#000000"> </font><span><font color="#2b91af">PartComponentDefinition</font></span><font color="#000000">;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// Get the XY plane from each occurrence. This goes to the</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//component definition of the part to get this information.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//This is the same as accessing the part document directly.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//The work plane obtained is in the context of the part,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// not the assembly.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">WorkPlane</font></span><font color="#000000"> oPartPlane1 = oPartDef1.WorkPlanes[3];</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">WorkPlane</font></span><font color="#000000"> oPartPlane2 = oPartDef2.WorkPlanes[3];</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// Because we need the work plane in the context of the assembly</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//we need to create proxies for the work planes. The proxies</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// represent the work planes in the context of the assembly.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">object</font></span><font color="#000000"> obj1;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; oOcc1.CreateGeometryProxy(oPartPlane1, </font></font><font style="font-size: 8pt"><span><font color="#0000ff">out</font></span><font color="#000000"> obj1);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">WorkPlaneProxy</font></span><font color="#000000"> oAsmPlane1 = (</font><span><font color="#2b91af">WorkPlaneProxy</font></span><font color="#000000">)obj1;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">object</font></span><font color="#000000"> obj2;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; oOcc2.CreateGeometryProxy(oPartPlane2, </font></font><font style="font-size: 8pt"><span><font color="#0000ff">out</font></span><font color="#000000"> obj2);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">WorkPlaneProxy</font></span><font color="#000000"> oAsmPlane2 = (</font><span><font color="#2b91af">WorkPlaneProxy</font></span><font color="#000000">)obj2;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//Create the constraint using the work plane proxies.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oAsmCompDef.Constraints.AddMateConstraint(oAsmPlane1,</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; oAsmPlane2, 0, </font></font><font style="font-size: 8pt"><span><font color="#2b91af">InferredTypeEnum</font></span><font color="#000000">.kNoInference,</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">InferredTypeEnum</font></span><font color="#000000">.kNoInference, </font><span><font color="#0000ff">null</font></span><font color="#000000">, </font><span><font color="#0000ff">null</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></p> </div>
