---
layout: "post"
title: "delete face from part with the Inventor API"
date: "2012-06-14 02:46:20"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/delete-face-from-part-with-the-inventor-api.html "
typepad_basename: "delete-face-from-part-with-the-inventor-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><b>Issue</b></p>  <p>Is there an example showing how to delete faces from a part using the Inventor API?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>It is possible to delete the face from a part using the Inventor API. This is done by adding the faces to the DeleteFaceFeatures. A FaceCollection object is created and the faces to be deleted are added to the collection. Finally the collection is added to the DeleFaceFeature object. </p>  <p><strong>VBA code:</strong></p>  <p>Sub deleteSideFaces_VBA() </p>  <p>&#160;&#160; 'remove all the side faces   <br />&#160;&#160; Dim aDoc As Document    <br />&#160;&#160; Dim pFets As PartFeatures    <br />&#160;&#160; Dim cdef As ComponentDefinition    <br />&#160;&#160; Dim oExtrude As ExtrudeFeatures    <br />&#160;&#160; Dim oAllface As Face    <br />&#160;&#160; Set aDoc = _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveDocument    <br />&#160;&#160; Set cdef = _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; aDoc.ComponentDefinition    <br />&#160;&#160; Set pFets = _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; cdef.Features    <br />&#160;&#160; Set oExtrude = _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; pFets.ExtrudeFeatures    <br />&#160;&#160; 'FaceCollection to hold the faces to delete    <br />&#160;&#160; Dim oFacecoll As FaceCollection    <br />&#160;&#160; Set oFacecoll = _    <br />&#160;&#160;&#160; ThisApplication.TransientObjects.CreateFaceCollection    <br />&#160;&#160; Dim oFaces As Faces    <br />&#160;&#160; Set oFaces = _    <br />&#160;&#160;&#160; oExtrude.Item(1).SideFaces    <br />&#160;&#160; 'Add all the sideface of the part in    <br />&#160;&#160; ' to the face collection object    <br />&#160;&#160; For Each oAllface In oFaces    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oFacecoll.Add oAllface    <br />&#160;&#160; Next    <br />&#160;&#160; 'delete the faces by adding into the deleteFaceFeatures    <br />&#160;&#160; If oFacecoll.Count &gt; 0 Then    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; pFets.DeleteFaceFeatures.Add oFacecoll, False    <br />&#160;&#160; End If    <br />End Sub</p>  <p>&#160;</p>  <p><strong>VB.NET code:</strong></p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> deleteSideFaces()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">' assume we have had Inventor application</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">'&#160; _InvApplication</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'remove all the side faces&#160;&#160; </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> aDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _InvApplication.ActiveDocument </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> cdef </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ComponentDefinition</span><span style="line-height: 140%"> = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aDoc.ComponentDefinition</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> pFets </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PartFeatures</span><span style="line-height: 140%"> = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cdef.Features</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oExtrude </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ExtrudeFeatures</span><span style="line-height: 140%"> = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pFets.ExtrudeFeatures</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'FaceCollection to hold the faces to delete&#160; </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oFacecoll </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">FaceCollection</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oFacecoll = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _InvApplication.TransientObjects.CreateFaceCollection</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oFaces </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Faces</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oFaces = oExtrude.Item(1).SideFaces</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oAllface </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Face</span><span style="line-height: 140%"> </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Add all the sideface of the part in </span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160;&#160;&#160; â€˜to the face collection object&#160;&#160; </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> oAllface </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> oFaces</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oFacecoll.Add(oAllface)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'delete the faces by adding into the deleteFaceFeatures&#160;&#160; </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oFacecoll.Count &gt; 0 </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pFets.DeleteFaceFeatures.Add(oFacecoll, </span><span style="line-height: 140%; color: blue">False</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>
