---
layout: "post"
title: "Position of iFeature"
date: "2012-07-19 22:51:30"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/07/position-of-ifeature.html "
typepad_basename: "position-of-ifeature"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The iFeatureSketchPlaneInput object supports the SetPosition method which allows you to define several things that control the placement position of the iFeature; the placement point, a vector that defines the axis that will be used as zero, and the rotation angle relative to the defined axis. This provides functionality similar to what you see when you interactively place an iFeature and have the opportunity to move and rotate it on the selected face. </p>  <p>Following code snippet explains the usage of the SetPosition method. To test the first one ensure the path to Cone_Rounded.ide is correct for your installation. This example places the iFeature on the start face of the first extrusion. </p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> PlaceiFeature()</span></p>    <p style="margin: 0px"><span style="line-height: 140%"></span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> _InventorApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%"> =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Runtime.InteropServices.</span><span style="line-height: 140%; color: #2b91af">Marshal</span><span style="line-height: 140%">.GetActiveObject(</span><span style="line-height: 140%; color: #a31515">&quot;Inventor.Application&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oCompDef </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PartComponentDefinition</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oCompDef = _InventorApp.ActiveDocument.ComponentDefinition</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oTG </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">TransientGeometry</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oTG = _InventorApp.TransientGeometry</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Arbitrarily get the start face of the first extrusion. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oFace </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Face</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oFace =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCompDef.Features.ExtrudeFeatures.Item(1).</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StartFaces.Item(1)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oiFeatComps </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">iFeatureComponents</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oiFeatComps = oCompDef.ReferenceComponents.iFeatureComponents</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Create the definition object for the specified ide file. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oiFeatDef </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">iFeatureDefinition</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oiFeatDef = oiFeatComps.CreateDefinition( _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;C:\Users\Public\Documents\Autodesk\Inventor 2012&quot;</span><span style="line-height: 140%"> &amp; _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;\Geometric Shapes\Cone_Rounded.ide&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Set the iFeature input values. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oiFeatInput </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">iFeatureInput</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oParamInput </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">iFeatureParameterInput</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> oiFeatInput </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> oiFeatDef.iFeatureInputs</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Select</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Case</span><span style="line-height: 140%"> oiFeatInput.Prompt</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Case</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #a31515">&quot;Pick a planar face or work plane&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oPlaneInput </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">iFeatureSketchPlaneInput</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPlaneInput = oiFeatInput</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPlaneInput.PlaneInput = oFace</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oPlaneInput.SetPosition(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint(0, 0, 0),</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreateVector(1, 0, 0), 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Case</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #a31515">&quot;Enter Diameter&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oParamInput = oiFeatInput</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oParamInput.Expression = </span><span style="line-height: 140%; color: #a31515">&quot;.75 in&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Case</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #a31515">&quot;Height at theoretical sharp point&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oParamInput = oiFeatInput</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oParamInput.Expression = </span><span style="line-height: 140%; color: #a31515">&quot;.6 in&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Case</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #a31515">&quot;Enter Radius&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oParamInput = oiFeatInput</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oParamInput.Expression = </span><span style="line-height: 140%; color: #a31515">&quot;.1 in&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Select</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Create the iFeature. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oiFeatComps.Add(oiFeatDef)</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>  <p>However, remember that interactively or through the API you're not able to precisely position an iFeature. If you need to precisely position it then you need to define the iFeature such that it is dependent on outside geometry for it's position. For example, if you need to place an iFeature precisely at a certain location then you could make the original sketch of the iFeature dependent on a point (WorkPoint, or Vertex for example). When placing the iFeature you'll then need to identify similar existing geometry to allow their relationships to be created. </p>  <p>   <br />A common misconception is to think that an iFeature is similar to an AutoCAD block. When placing a block you specify the placement point and can also specify an angle which allows you to precisely position the block. iFeature's do not have an origin so specifying a placement point makes not sense since there isn't a defined point in the iFeature to align to the point. An iFeature is really just a group of features and their corresponding sketches. A feature has certain dependencies. For example when you create an extrude feature the feature is dependent on a sketch for its shape and this sketch is dependent on a face or work plane for it's position. The sketch may also have dimension or geometry constraints to geometry outside the sketch to define the position of sketch geometry. An iFeature is essentially a feature with the objects the iFeature is dependent on missing. When you place an iFeature you must identify these missing dependencies and then Inventor is able to create the feature(s) in the iFeature. By creating an iFeature that is dependent on a single point (usually a work point) for its position and possibly a line for its orientation, you can supply this input during placement to precisely control the position of the iFeature. </p>
