---
layout: "post"
title: "Create a document that represents only the external boundary of my Part or Assembly"
date: "2012-09-12 01:55:00"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/09/create-a-document-that-represents-only-the-external-boundary-of-my-part-or-assembly.html "
typepad_basename: "create-a-document-that-represents-only-the-external-boundary-of-my-part-or-assembly"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>
<p><strong>Issue      <br /></strong>I would like to hide the complexity of my assemblies and parts by suppressing all the internal cavities that are present in the Inventor models and show only the visible external geometry. I want to do it, for example, to give to my customers an overview of my models, without actually providing any information about the internal design. How can this be achieved?</p>
<p><a name="section2"></a></p>
<p><strong>Solution      <br /></strong>The following VBA sample addresses this problem by first creating a derived Part from the initial document, this one can be a Part or an Assembly, then it will deletes any internal closed cavity in the model. This transitional derived Part will then be used to create a final non-parametric Part in which the internal geometry is completely suppressed.     <br />The transitional document is also saved on disk by the sample code, under the name “InitialDocName” + “_Boundary.ipt” but this step is not required. You could just generate the final document “InitialDocName” + “_BoudaryFinal.ipt” and close the derived Part without saving it.</p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;">Public Sub CreateExternalBoundary<span style="color: #ff0000;">(</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim oTopDoc As Document       <br />&#0160;&#0160;&#0160; Set oTopDoc = ThisApplication.ActiveDocument       <br />&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim oTrans As Transaction       <br />&#0160;&#0160;&#0160; Set oTrans = ThisApplication.TransactionManager.StartTransaction<span style="color: #ff0000;">(</span>oTopDoc, <span style="color: #ff00ff;">&quot;CreateExternalBoundary&quot;</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim oPartDoc As PartDocument       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; If oTopDoc.DocumentType = kAssemblyDocumentObject Then       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Create a new part document, invisibly.       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oPartDoc = ThisApplication.Documents.Add<span style="color: #ff0000;">(</span>kPartDocumentObject, , True<span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Derive the assembly into the part.       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oDerivedAsmDef As DerivedAssemblyDefinition       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oDerivedAsmDef = oPartDoc.ComponentDefinition.ReferenceComponents.DerivedAssemblyComponents.CreateDefinition<span style="color: #ff0000;">(</span>oTopDoc.FullDocumentName<span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call oPartDoc.ComponentDefinition.ReferenceComponents.DerivedAssemblyComponents.Add<span style="color: #ff0000;">(</span>oDerivedAsmDef<span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Else       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oPartDoc = oTopDoc       <br />&#0160;&#0160;&#0160; End If       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39;Find any voids within the solid and delete them.       <br />&#0160;&#0160;&#0160; Dim oVoidFaces As FaceCollection       <br />&#0160;&#0160;&#0160; Set oVoidFaces = ThisApplication.TransientObjects.CreateFaceCollection       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim oShell As FaceShell       <br />&#0160;&#0160;&#0160; For Each oShell In oPartDoc.ComponentDefinition.SurfaceBodies.Item<span style="color: #ff0000;">(</span><span style="color: #008000;">1</span><span style="color: #ff0000;">)</span>.FaceShells       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If <span style="color: #ff0000;">(</span>oShell.IsVoid = True<span style="color: #ff0000;">)</span> Then       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oFace As Face       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; For Each oFace In oShell.Faces       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oVoidFaces.Add oFace       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Next       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If       <br />&#0160;&#0160;&#0160; Next       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; If oVoidFaces.Count &gt; <span style="color: #008000;">0</span> Then       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call oPartDoc.ComponentDefinition.Features.DeleteFaceFeatures.Add<span style="color: #ff0000;">(</span>oVoidFaces<span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160; End If       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39;Save the doc.       <br />&#0160;&#0160;&#0160; &#39;At this point the internal cavities can still be seen by supressing the <span style="color: #ff00ff;">&quot;DeleteFaceFeature&quot;</span>       <br />&#0160;&#0160;&#0160; Call oPartDoc.SaveAs<span style="color: #ff0000;">(</span>oTopDoc.FullFileName + <span style="color: #ff00ff;">&quot;_Boundary.ipt&quot;</span>, False<span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39;Create the final PartDocument as a NonParametric solid.       <br />&#0160;&#0160;&#0160; &#39;This will definitely suppress the possibility to see the internal geometry of the initial document       <br />&#0160;&#0160;&#0160; Dim oMatrix As Matrix       <br />&#0160;&#0160;&#0160; Set oMatrix = ThisApplication.TransientGeometry.CreateMatrix<span style="color: #ff0000;">(</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim oBody As SurfaceBody       <br />&#0160;&#0160;&#0160; Set oBody = oPartDoc.ComponentDefinition.SurfaceBodies<span style="color: #ff0000;">(</span><span style="color: #008000;">1</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim oPartDocFinal As PartDocument       <br />&#0160;&#0160;&#0160; Set oPartDocFinal = ThisApplication.Documents.Add<span style="color: #ff0000;">(</span>kPartDocumentObject, , True<span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160; Call oPartDocFinal.ComponentDefinition.Features.NonParametricBaseFeatures.Add<span style="color: #ff0000;">(</span>oBody, oMatrix<span style="color: #ff0000;">)</span>       <br />&#0160;&#0160;&#0160; Call oPartDocFinal.SaveAs<span style="color: #ff0000;">(</span>oTopDoc.FullFileName + <span style="color: #ff00ff;">&quot;_BoundaryFinal.ipt&quot;</span>, False<span style="color: #ff0000;">)</span>       <br />      <br />&#0160;&#0160;&#0160; oTrans.End       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />End Sub</span></p>
VB.NET Code
<div style="font-family: courier new; background: white; color: black; font-size: 9pt;">
<p style="margin: 0px;"><span style="line-height: 140%; color: blue;">Public</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">Sub</span><span style="line-height: 140%;"> CreateExternalBoundary()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> m_inventorApp </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> Inventor.</span><span style="line-height: 140%; color: #2b91af;">Application</span><span style="line-height: 140%;"> = </span><span style="line-height: 140%; color: blue;">Nothing</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39; Try to get an active instance of Inventor</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Try</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp = System.Runtime.InteropServices.</span><span style="line-height: 140%; color: #2b91af;">Marshal</span><span style="line-height: 140%;">.GetActiveObject(</span><span style="line-height: 140%; color: #a31515;">&quot;Inventor.Application&quot;</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Catch</span><span style="line-height: 140%;"> ex </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">Exception</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">End</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">Try</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39; If not active, create a new Inventor session</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">If</span><span style="line-height: 140%;"> m_inventorApp </span><span style="line-height: 140%; color: blue;">Is</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">Nothing</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> inventorAppType </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">Type</span><span style="line-height: 140%;"> = System.</span><span style="line-height: 140%; color: #2b91af;">Type</span><span style="line-height: 140%;">.GetTypeFromProgID(</span><span style="line-height: 140%; color: #a31515;">&quot;Inventor.Application&quot;</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp = System.</span><span style="line-height: 140%; color: #2b91af;">Activator</span><span style="line-height: 140%;">.CreateInstance(inventorAppType)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">End</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oTopDoc </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">Document</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oTopDoc = m_inventorApp.ActiveDocument</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oTrans </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">Transaction</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oTrans = m_inventorApp.TransactionManager.StartTransaction(oTopDoc, </span><span style="line-height: 140%; color: #a31515;">&quot;CreateExternalBoundary&quot;</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oPartDoc </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">PartDocument</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">If</span><span style="line-height: 140%;"> oTopDoc.DocumentType = </span><span style="line-height: 140%; color: #2b91af;">DocumentTypeEnum</span><span style="line-height: 140%;">.kAssemblyDocumentObject </span><span style="line-height: 140%; color: blue;">Then</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39; Create a new part document, invisibly.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oPartDoc = m_inventorApp.Documents.Add(</span><span style="line-height: 140%; color: #2b91af;">DocumentTypeEnum</span><span style="line-height: 140%;">.kPartDocumentObject, , </span><span style="line-height: 140%; color: blue;">True</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39; Derive the assembly into the part.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oDerivedAsmDef </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">DerivedAssemblyDefinition</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oDerivedAsmDef = oPartDoc.ComponentDefinition.ReferenceComponents.DerivedAssemblyComponents.CreateDefinition(oTopDoc.FullDocumentName)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Call</span><span style="line-height: 140%;"> oPartDoc.ComponentDefinition.ReferenceComponents.DerivedAssemblyComponents.Add(oDerivedAsmDef)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Else</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oPartDoc = oTopDoc</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">End</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39;Find any voids within the solid and delete them.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oVoidFaces </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">FaceCollection</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oVoidFaces = m_inventorApp.TransientObjects.CreateFaceCollection</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oShell </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">FaceShell</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">For</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">Each</span><span style="line-height: 140%;"> oShell </span><span style="line-height: 140%; color: blue;">In</span><span style="line-height: 140%;"> oPartDoc.ComponentDefinition.SurfaceBodies.item(1).FaceShells</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">If</span><span style="line-height: 140%;"> (oShell.IsVoid = </span><span style="line-height: 140%; color: blue;">True</span><span style="line-height: 140%;">) </span><span style="line-height: 140%; color: blue;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oFace </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">Face</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">For</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">Each</span><span style="line-height: 140%;"> oFace </span><span style="line-height: 140%; color: blue;">In</span><span style="line-height: 140%;"> oShell.Faces</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oVoidFaces.Add(oFace)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Next</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">End</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">If</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Next</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">If</span><span style="line-height: 140%;"> oVoidFaces.count &gt; 0 </span><span style="line-height: 140%; color: blue;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Call</span><span style="line-height: 140%;"> oPartDoc.ComponentDefinition.Features.DeleteFaceFeatures.Add(oVoidFaces)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">End</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39;Save the doc.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39;At this point the internal cavities can still be seen by supressing the &quot;DeleteFaceFeature&quot;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oPartDoc.SaveAs(oTopDoc.FullFileName + </span><span style="line-height: 140%; color: #a31515;">&quot;_Boundary.ipt&quot;</span><span style="line-height: 140%;">, </span><span style="line-height: 140%; color: blue;">False</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39;Create the final PartDocument as a NonParametric solid.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">&#39;This will definitely suppress the possibility to see the internal geometry of the initial document</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oMatrix </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">Matrix</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oMatrix = m_inventorApp.TransientGeometry.CreateMatrix()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oBody </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">SurfaceBody</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oBody = oPartDoc.ComponentDefinition.SurfaceBodies(1)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">Dim</span><span style="line-height: 140%;"> oPartDocFinal </span><span style="line-height: 140%; color: blue;">As</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: #2b91af;">PartDocument</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oPartDocFinal = m_inventorApp.Documents.Add(</span><span style="line-height: 140%; color: #2b91af;">DocumentTypeEnum</span><span style="line-height: 140%;">.kPartDocumentObject, , </span><span style="line-height: 140%; color: blue;">True</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oPartDocFinal.ComponentDefinition.Features.NonParametricBaseFeatures.Add(oBody, oMatrix)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oPartDocFinal.SaveAs(oTopDoc.FullFileName + </span><span style="line-height: 140%; color: #a31515;">&quot;_BoundaryFinal.ipt&quot;</span><span style="line-height: 140%;">, </span><span style="line-height: 140%; color: blue;">False</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; oTrans.End()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%; color: blue;">End</span><span style="line-height: 140%;"> </span><span style="line-height: 140%; color: blue;">Sub</span></p>
</div>
