---
layout: "post"
title: "Changing workplane of hole feature"
date: "2012-05-28 06:23:14"
author: "Philippe Leefsma"
categories:
  - "Inventor"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/changing-workplane-of-hole-feature.html "
typepad_basename: "changing-workplane-of-hole-feature"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p>  <p><strong>Q:</strong></p>  <p>We created a extrusion feature, then we had made changes to the original Extrusion, e.g. create a hole with a cut Extrusion, Now we want to change the Extrusion Feature by moving one of the WorkPlane objects (or to select another one, as it is possible per UI), but we don't want to create a new Workplane object, because in this case I have to create a new extrusion, all changes are lost. So we need to have the possibility to change the extrusion and Inventor &quot;regenerates&quot; this extrusion and all other features in this part are still active.</p>  <p><strong>A:</strong></p>  <p>   <p><b></b></p> The below is a sample of changing the workplane for a hole feature in a part document.</p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Public</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">Sub</font></span><font color="#000000"> ChangeWPlaneOfHole(</font><span style="color: "><font color="#0000ff">ByVal</font></span><font color="#000000"> app </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> Inventor.</font><span style="color: "><font color="#2b91af">Application</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oDef </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">PartComponentDefinition</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oDef = app.ActiveDocument.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Get the hole feature</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oHoleFeat </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">HoleFeature</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oHoleFeat = oDef.Features.HoleFeatures.Item(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Get another workplane, assumes at least 5</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'workplanes exist in the part</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oWorkplane </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">WorkPlane</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oWorkplane = oDef.WorkPlanes.Item(5)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Assign it to the hole feature</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oHoleFeat.SetToFaceExtent(oWorkplane, </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">True</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; color: "><font face="Consolas"><font style="font-size: 8pt" color="#0000ff">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt" class="MsoNormal"><font face="Calibri"><font style="font-size: 11pt" color="#000000">&#160;</font></font></p>
