---
layout: "post"
title: "Horizontal Align Constraint with the Center Point of the Sketch"
date: "2012-05-15 23:35:16"
author: "Xiaodong Liang"
categories: []
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/horizontal-align-constraint-with-the-center-point-of-the-sketch.html "
typepad_basename: "horizontal-align-constraint-with-the-center-point-of-the-sketch"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The code below aligns the middle point of a sketch line with the center point of the sketch.</p>  <p>&#160;</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> AlignPoints(</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%"></span>&#160;<span style="line-height: 140%">&#160;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green"> ' assume we have got Inventor application</span></p>    <p style="margin: 0px">&#160;<span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDocDef </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> PartComponentDefinition = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160; _InvApplication.ActiveDocument.ComponentDefinition()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue"> Dim</span><span style="line-height: 140%"> oSketch </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> PlanarSketch = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDocDef.Sketches(1)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue"> Dim</span><span style="line-height: 140%"> oSketchLine </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> SketchLine = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _InvApplication.ActiveDocument.SelectSet(1)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green"> 'get center workpoint</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue"> Dim</span><span style="line-height: 140%"> oCenterWorkPt </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> WorkPoint = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDocDef.WorkPoints(</span><span style="line-height: 140%; color: #a31515">&quot;Center Point&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green"> 'create the center point on sketch</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue"> Dim</span><span style="line-height: 140%"> oCenterPt </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> SketchPoint = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchPoints.Add( _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.ModelToSketchSpace</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oCenterWorkPt.Point))</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green"> 'create the mid point of the line</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue"> Dim</span><span style="line-height: 140%"> oMidPt </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> SketchPoint = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchPoints.Add( _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketchLine.Geometry.MidPoint)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160; 'fix the center point</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; oSketch.GeometricConstraints.AddGround(oCenterPt)</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160; 'creates a new midpoint constraint between the point </span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160; â€˜and line</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; oSketch.GeometricConstraints.AddMidpoint(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oMidPt,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketchLine)</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green"> 'constraint the midpoint and center point by HorizontalAlign</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160; oSketch.GeometricConstraints.AddHorizontalAlign(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCenterPt,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oMidPt)</span></p>    <p style="margin: 0px">&#160;<span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>
