---
layout: "post"
title: "Set a Spline Curvature at a Specific FitPoint in Inventor API"
date: "2012-08-20 03:04:34"
author: "Barbara Han"
categories:
  - "Barbara Han"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/set-a-spline-curvature-at-a-specific-fitpoint-in-inventor-api.html "
typepad_basename: "set-a-spline-curvature-at-a-specific-fitpoint-in-inventor-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <p><strong>Issue</strong>    <br />How to set the tangent vector (curvature) of a spline at a specific FitPoint through API?</p>  <p><strong>Solution</strong>    <br />The following code sample illustrates how to get and modify the tangent vector of a spline at a specific FitPoint. </p>  <p>In this sample:</p>  <p>1. User should firstly select a spline's FitPoint through UI</p>  <p>2. Use API to get the tangent vector at the selected point by SketchSplineHandle.</p>  <p>3. Change the vector. i.e. offset it by&#160; (0.2, 0.2)</p>  <p>Note: The &quot;SketchSplineHandle&quot; object has been introduced in the 2008 API, so this code is only supported by Inventor versions from 2008 on.</p>  <p><font size="1" face="Courier New">Public Sub SetSplineCurvature()     <br />&#160;&#160;&#160; 'First select the FitPoint of interest through the UI      <br />&#160;&#160;&#160; Dim oFitPoint As SketchPoint      <br />&#160;&#160;&#160; Set oFitPoint = ThisApplication.ActiveDocument.SelectSet.item(1)      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'First constraint of the point is always the 'SplineFitPointConstraint'      <br />&#160;&#160;&#160; Dim oConstraint As SplineFitPointConstraint      <br />&#160;&#160;&#160; Set oConstraint = oFitPoint.Constraints.item(1)</font></p>  <p><font size="1" face="Courier New">&#160;&#160;&#160; 'Retrieves spline from the constraint     <br />&#160;&#160;&#160; Dim oSpline As SketchSpline      <br />&#160;&#160;&#160; Set oSpline = oConstraint.Spline      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'Creates handle      <br />&#160;&#160;&#160; Call oSpline.SetHandleStatus(oFitPoint, True)      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'Gets handle      <br />&#160;&#160;&#160; Dim oSplineHandle As SketchSplineHandle      <br />&#160;&#160;&#160; Set oSplineHandle = oSpline.GetHandle(oFitPoint)      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'Gets tangent vector      <br />&#160;&#160;&#160; Dim oTangent As UnitVector2d      <br />&#160;&#160;&#160; Set oTangent = oSplineHandle.Tangent      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'Sets tangent vector with new value      <br />&#160;&#160;&#160; oSplineHandle.Tangent = ThisApplication.TransientGeometry.CreateUnitVector2d(oTangent.x + 0.2, oTangent.y + 0.2)&#160;&#160;&#160; <br />End Sub</font></p>  <p>VB .NET version:   <br /><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">public</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">static</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">void</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> SetSplineCurvature()</font></span></font></p>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">try</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Inventor.Application app = (Inventor.Application)System.</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; Runtime.InteropServices.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#2b91af">Marshal</font></span><span style="line-height: 11pt"><font color="#000000">.GetActiveObject(</font></span><span style="line-height: 11pt; color: "><font color="#a31515">&quot;Inventor.Application&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; SketchPoint oFitPoint = app.ActiveDocument.SelectSet[1] </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">as</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> SketchPoint;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; SplineFitPointConstraint oConstraint = oFitPoint.Constraints[1] </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">as</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> SplineFitPointConstraint;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">//Retrieves spline from the constraint</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; SketchSpline oSpline = oConstraint.Spline;</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">//Creates handle</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSpline.SetHandleStatus(oFitPoint, </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">true</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">//Gets handle</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; SketchSplineHandle oSplineHandle = oSpline.GetHandle(oFitPoint);</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">//Gets tangent vector</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; UnitVector2d oTangent = oSplineHandle.Tangent;</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">//Sets tangent vector with new value</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSplineHandle.Tangent = app.TransientGeometry.CreateUnitVector2d(oTangent.X + 0.2, oTangent.Y + 0.2);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">catch</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></span></p> </div>
