---
layout: "post"
title: "minimum distance of cone face"
date: "2012-11-21 23:23:50"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/11/minimum-distance-of-cone-face.html "
typepad_basename: "minimum-distance-of-cone-face"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a>     <br /></p>  <p>Issue    <br />I uses GetMinimumDistance to get the distance from a cylinder to a cone face. If the cone has no tip (minor and major radius &gt; 0), the distance looks correct. But if it has tip, the distance is no correct. It looks it chooses a random point on conical surface, instead of the tip point. e.g. as shown in the fig below. The attachment is a code reproduce it.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017d3e0a5126970c-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_96d08c.jpg" width="470" height="266" /></a></p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt">Public Sub GetMinDistance<span style="color: #ff0000">(</span><span style="color: #ff0000">)</span>      <br />      <br />&#160;&#160;&#160; Dim oDoc As PartDocument      <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument      <br />&#160;&#160;&#160; Dim oDef As PartComponentDefinition      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Set oDef = oDoc.ComponentDefinition      <br />      <br />      <br />&#160;&#160;&#160; Dim oTransientBRep As TransientBRep      <br />&#160;&#160;&#160; Set oTransientBRep = ThisApplication.TransientBRep      <br />      <br />&#160;&#160;&#160; ' Create a point representing the center of the bottom of the cone      <br />&#160;&#160;&#160; Dim oBottom As Point      <br />&#160;&#160;&#160; Set oBottom = ThisApplication.TransientGeometry.CreatePoint<span style="color: #ff0000">(</span>0, 0, <span style="color: #008000">0</span><span style="color: #ff0000">)</span>      <br />      <br />&#160;&#160;&#160; ' Create a point representing the tip of the cone      <br />&#160;&#160;&#160; Dim oTop As Point      <br />&#160;&#160;&#160; Set oTop = ThisApplication.TransientGeometry.CreatePoint<span style="color: #ff0000">(</span>0, 2.54, <span style="color: #008000">0</span><span style="color: #ff0000">)</span>      <br />      <br />&#160;&#160;&#160; ' Create a transient cone body      <br />&#160;&#160;&#160; Dim oBody As SurfaceBody      <br />&#160;&#160;&#160; Set oBody = oTransientBRep.CreateSolidCylinderCone<span style="color: #ff0000">(</span>oBottom, oTop, 5, 5, <span style="color: #008000">2</span><span style="color: #ff0000">)</span>      <br />      <br />&#160;&#160;&#160; ' Reset the top and bottom point of the cylinder      <br />&#160;&#160;&#160; Set oTop = ThisApplication.TransientGeometry.CreatePoint<span style="color: #ff0000">(</span>0, 2.54 + 1.27, <span style="color: #008000">0</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; Set oBottom = ThisApplication.TransientGeometry.CreatePoint<span style="color: #ff0000">(</span>0, 2.54 + 1.27 + 2.54, <span style="color: #008000">0</span><span style="color: #ff0000">)</span>      <br />      <br />      <br />&#160;&#160;&#160; ' Create a transient cylinder body      <br />&#160;&#160;&#160; Dim oCylBody As SurfaceBody      <br />&#160;&#160;&#160; 'Set oCylBody = oTransientBRep.CreateSolidCylinderCone<span style="color: #ff0000">(</span>oBottom, oTop, 2.5, 2.5, 2.5<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; Set oCylBody = oTransientBRep.CreateSolidCylinderCone<span style="color: #ff0000">(</span>oBottom, oTop, 2.5, 2.5, <span style="color: #008000">0</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160; <br />&#160; <br />&#160;&#160;&#160; ' Boolean the bodies<span style="background-color: #e6e6e6; color: #800080">; <span style="color: #ff00ff">&quot;oBody&quot;</span> will return the result        <br /></span>&#160;&#160;&#160; Call oTransientBRep.DoBoolean<span style="color: #ff0000">(</span>oBody, oCylBody, kBooleanTypeUnion<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oBaseFeature As NonParametricBaseFeature      <br />&#160;&#160;&#160; Set oBaseFeature = oDef.Features.NonParametricBaseFeatures.Add<span style="color: #ff0000">(</span>oBody<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim ocyl As Face      <br />&#160;&#160;&#160; Dim ocone As Face      <br />&#160;&#160;&#160; Dim f As Face      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; For Each f In oBaseFeature.Faces      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf f.Geometry Is Cone Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set ocone = f      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit For      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Next      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; For Each f In oBaseFeature.Faces      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf f.Geometry Is Cone And <span style="color: #ff0000">(</span>Not f Is ocone<span style="color: #ff0000">)</span> Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set ocyl = f      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit For      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Next      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim cont As NameValueMap      <br />&#160;&#160;&#160; Dim dist As Double      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; ' The distance returned below is same as return By UI      <br />&#160;&#160;&#160; dist = ThisApplication.MeasureTools.GetMinimumDistance<span style="color: #ff0000">(</span>ocone, ocyl, kNoInference, kNoInference, cont<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim pt1 As Point      <br />&#160;&#160;&#160; Set pt1 = cont.Item<span style="color: #ff0000">(</span><span style="color: #008000">2</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; Dim pt2 As Point      <br />&#160;&#160;&#160; Set pt2 = cont.Item<span style="color: #ff0000">(</span><span style="color: #008000">3</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; oDef.WorkPoints.AddFixed pt1      <br />&#160;&#160;&#160; oDef.WorkPoints.AddFixed pt2      <br />&#160;&#160;&#160;&#160; <br />End Sub      <br /></span></p>  <p><strong></strong></p>  <p><strong>Solution</strong></p>  <p>Assume there are one cylinder and one cone (with tip).&#160; The minimum distance between cylindrical face and cone with tip is calculated incorrectly as we have seen. But if we select planar face of cylinder and conical face then distance is shown correctly between tip and planar face. </p>  <p>If we create a 2D model bases on the 3D model like below figure. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017ee57f3c44970d-pi"><img style="border-bottom: 0px; border-left: 0px; display: inline; border-top: 0px; border-right: 0px" title="image" border="0" alt="image" src="/assets/image_5cec88.jpg" width="421" height="472" /></a> </p>  <p>The 2D model is created on a plane which is across the axis of the cone and cylinder, so now we can find that the minimum distance of the conical face and cylindrical face is the same of the minimum distance between the black line and the blue line. So create a line from the top end(red point) of the black line and perpendicular to the blue line like the picture shows, we will get the yellow line, the yellow line is the shortest one between the black line and blue line. </p>  <p>Actually this is affected by the apex angle of the cone(also the position of the cone tip), so like below if the apex angle of the cone is sharp enough that the yellow line has its perpendicular point on the extension of the blue line then the shortest line between the black line and the blue line would be like magenta line in below figure:</p>  <p>&#160;</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017c33dbac26970b-pi"><img style="border-bottom: 0px; border-left: 0px; display: block; float: none; margin-left: auto; border-top: 0px; margin-right: auto; border-right: 0px" title="image" border="0" alt="image" src="/assets/image_fb15ac.jpg" width="148" height="244" /></a></p>
