---
layout: "post"
title: "project geometry from one occurrence to another"
date: "2012-07-21 07:48:35"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/07/project-geometry-from-one-occurrence-to-another.html "
typepad_basename: "project-geometry-from-one-occurrence-to-another"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The PlanarSketch.AddByProjectingEntity can be used in a part environment to project geometry onto a sketch plane. It is also applicable to project geometry from one occurrence to another.</p>  <p>The only issue you need to mote is: you must use a proxy object, not a native object, no matter the geometries or the object which is projected to, such as a sketch.</p>  <p>The following code assumes an assembly has two parts. It projects the first edge of the first surfacebody of the part1 to the first sketch of the part2.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="color: blue">static</span> <span style="color: blue">void</span> Test()</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160;&#160;&#160; _InvApplication = (Inventor.<span style="color: #2b91af">Application</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.Runtime.InteropServices.<span style="color: #2b91af">Marshal</span>.</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetActiveObject(<span style="color: #a31515">&quot;Inventor.Application&quot;</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// assume we have had Inventor application</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">AssemblyDocument</span> asmDoc = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">AssemblyDocument</span>)_InvApplication.ActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">ComponentOccurrence</span> occ1 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; asmDoc.ComponentDefinition.Occurrences[1];</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">ComponentOccurrence</span> occ2 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; asmDoc.ComponentDefinition.Occurrences[2];</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">PartComponentDefinition</span> partDef1 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">PartComponentDefinition</span>)occ1.Definition;&#160;&#160;&#160; </p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">PartComponentDefinition</span> partDef2 =&#160;&#160;&#160;&#160;&#160;&#160; </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">PartComponentDefinition</span>)occ2.Definition;&#160;&#160;&#160; </p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Edge</span> oEdge =&#160; partDef1.SurfaceBodies[1].Edges[1]; </p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">object</span> objedge;</p>    <p style="margin: 0px">&#160;&#160;&#160; occ1.CreateGeometryProxy(oEdge, <span style="color: blue">out</span> objedge);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">EdgeProxy</span> oProxyEdge = (<span style="color: #2b91af">EdgeProxy</span>)objedge;&#160;&#160;&#160; </p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">PlanarSketch</span> mySketch = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">PlanarSketch</span>)partDef2.Sketches[1];</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">object</span> objsketch;</p>    <p style="margin: 0px">&#160;&#160;&#160; occ2.CreateGeometryProxy(mySketch, <span style="color: blue">out</span> objsketch);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">PlanarSketchProxy</span> myProxySketchProxy = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">PlanarSketchProxy</span>)objsketch;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//SketchEntity projEdge = </span></p>    <p style="margin: 0px"><span style="color: green">&#160;&#160;&#160; // mySketch.AddByProjectingEntity(oProxyEdge);</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">SketchEntity</span> projEdge = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; myProxySketchProxy.AddByProjectingEntity</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oProxyEdge); </p>    <p style="margin: 0px">}</p> </div>
