---
layout: "post"
title: "Transparency of ClientGraphics - when RenderStyle is set makes a difference in 2012"
date: "2012-08-23 18:31:37"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/transparency-of-clientgraphics-when-renderstyle-is-set-makes-a-difference-in-2012.html "
typepad_basename: "transparency-of-clientgraphics-when-renderstyle-is-set-makes-a-difference-in-2012"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p><b>Issue</b></p>  <p>I need to create ClientGraphics that are transparent. I use the RenderStyle property of a ClientNode and set it to a render style that is transparent. In Inventor 2012 my ClientGraphics are not transparent. The same code running in Inventor 2011 was transparent. Is there a way to get the ClientGraphics to be transparent in 2012? </p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>The solution in the 2012 release is to call RenderStyle soon after the ClientNode is created. This VBA example that is an update from the help file will help explain. Notice that RenderStyle() for the GraphicsNode is called right after it is created. </p>  <p>Note: Behavior does not occur in Inventor 2013.</p>  <p>Public Sub DrawCustomTriangles()    <br />&#160;&#160;&#160; Dim oDoc As Document     <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument</p>  <p>&#160;&#160;&#160; <font color="#0000ff">' Set a reference to component definition of      <br />&#160;&#160;&#160; ' the active document. This assumes that a part       <br />&#160;&#160;&#160; ' or assembly document is active.       <br /></font>&#160;&#160;&#160; Dim oCompDef As ComponentDefinition     <br />&#160;&#160;&#160; Set oCompDef = ThisApplication.ActiveDocument _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .ComponentDefinition     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">' Check to see if the test graphics data object      <br />&#160;&#160;&#160; ' already exists. If it does clean up by removing       <br />&#160;&#160;&#160; ' all associated of the client graphics from the       <br />&#160;&#160;&#160; 'document. If it doesn't create it and draw a line.       <br /></font>&#160;&#160;&#160; On Error Resume Next     <br />&#160;&#160;&#160; Dim oGraphicsData As GraphicsDataSets     <br />&#160;&#160;&#160; Set oGraphicsData = oDoc.GraphicsDataSetsCollection _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Item (&quot;SampleGraphicsID&quot;)     <br />&#160;&#160;&#160; If Err.Number = 0 Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0     <br />&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' An existing client graphics object was      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'successfully obtained so clean up.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oGraphicsData.Delete     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCompDef.ClientGraphicsCollection.Item _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (&quot;SampleGraphicsID&quot;).Delete     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">&#160; ' update the display to see the results.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveView.Update     <br />&#160;&#160;&#160; Else     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Err.Clear     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Set a reference to the transient geometry      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' object for user later.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oTransGeom As TransientGeometry     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oTransGeom = ThisApplication.TransientGeometry     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Create a graphics data set object.&#160; This object      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' contains all of the       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' information used to define the graphics</font>.     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oDataSets As GraphicsDataSets     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oDataSets = oDoc.GraphicsDataSetsCollection _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Add (&quot;SampleGraphicsID&quot;)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Create a coordinate set.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCoordSet As GraphicsCoordinateSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCoordSet = oDataSets.CreateCoordinateSet(1)</p>  <p>&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Get the number of sides for the cylinder.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim iSideCount As Long     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; iSideCount = InputBox _     <br />(&quot;Enter number of sides for cylinder.(Must be greater than 2.)&quot;, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Cylinder Tolerance&quot;, 25)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim dRadius As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim dHeight As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; dRadius = 3     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; dHeight = 7     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Create an array containing points to used      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' in drawing the cylinder. The points could also       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' be directly defined in a coordinate set, but       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' defining them in array and then setting the       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' coordinates using the       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' array is more efficient for a large set of points.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim adPointCoords() As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ReDim adPointCoords _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (1 To ((iSideCount + 1) * 2) * 3) As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim i As Long     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim dAngle As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Define the points for the outline of      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'the first end of the cylinder.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; dAngle = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 0 To iSideCount - 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords(i * 3 + 1) = dRadius * Cos(dAngle)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords(i * 3 + 2) = dRadius * Sin(dAngle)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords(i * 3 + 3) = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Increment the angle for the next point     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; dAngle = dAngle + _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((2 * 3.14159265358979) / iSideCount)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">&#160; ' Define the points for the outline of the other      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' end of the cylinder.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; dAngle = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = iSideCount To (iSideCount * 2) - 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords(i * 3 + 1) = dRadius * Cos(dAngle)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords(i * 3 + 2) = dRadius * Sin(dAngle)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords(i * 3 + 3) = dHeight     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160;&#160;&#160; ' Increment the angle for the next point      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; dAngle = dAngle + _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((2 * 3.14159265358979) / iSideCount)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Define coordinate at the center of the      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'first end of the cylinder.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords((iSideCount * 2) * 3 + 1) = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords((iSideCount * 2) * 3 + 2) = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords((iSideCount * 2) * 3 + 3) = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Define coordinate at the center of the other      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' end of the cylinder.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords((iSideCount * 2) * 3 + 4) = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords((iSideCount * 2) * 3 + 5) = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; adPointCoords((iSideCount * 2) * 3 + 6) = dHeight</p>  <p>&#160;&#160; <font color="#0000ff">&#160;&#160;&#160;&#160; ' Assign the points to the coordinate set</font>.     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCoordSet.PutCoordinates(adPointCoords)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Create an index set to use for the triangle fan for      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' cap of the first end of the cylinder.&#160; This will       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' serve as in index look-up into the coordinate set.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCap1Index As GraphicsIndexSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCap1Index = oDataSets.CreateIndexSet(1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Set the index values.&#160; This could also be done      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' by setting the value in an array and then using       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' the array to set the values of the index set.       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Using an array is more efficient, but this       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' is used to here to demonstrate the IndexSet       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' object's Add method.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap1Index.Add(1, iSideCount * 2 + 1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap1Index.Add(2, 1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap1Index.Add(3, 2)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 4 To iSideCount + 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap1Index.Add(i, i - 1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap1Index.Add(iSideCount + 2, 1)</p>  <p>&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Create an index set to use for the      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' triangle fan of the other cylinder cap.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCap2Index As GraphicsIndexSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCap2Index = oDataSets.CreateIndexSet(2)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Set the index values.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap2Index.Add(1, iSideCount * 2 + 2)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap2Index.Add(2, iSideCount + 1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap2Index.Add(3, iSideCount + 2)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 4 To iSideCount + 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap2Index.Add(i, i + iSideCount - 1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap2Index.Add(iSideCount + 2, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; iSideCount + 1)</p>  <p><font color="#0000ff">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Create an index set to use for the triangle      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' strip that will       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' define the sides of the cylinder.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCylinderIndex As GraphicsIndexSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCylinderIndex = oDataSets.CreateIndexSet(3)</p>  <p>&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Define the index values in an array.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim iIndexValues() As Long     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ReDim iIndexValues _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (1 To (iSideCount + 1) * 2) As Long     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 0 To iSideCount - 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; iIndexValues(i * 2 + 1) = i + 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; iIndexValues(i * 2 + 2) = i + iSideCount + 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; iIndexValues(((iSideCount + 1) * 2) - 1) = 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; iIndexValues((iSideCount + 1) * 2) = iSideCount + 1</p>  <p>&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Define the index values in the index set      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' using the array.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCylinderIndex.PutIndices(iIndexValues)</p>  <p><font color="#0000ff">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Create the ClientGraphics object.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oClientGraphics As ClientGraphics     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oClientGraphics = oCompDef. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClientGraphicsCollection.Add(&quot;SampleGraphicsID&quot;)     <br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Create a new graphics node within the client      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' graphics objects.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCylinderNode As GraphicsNode     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCylinderNode = oClientGraphics.AddNode(1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; 'WB added      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCylinderNode.Selectable = True     <br />&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">&#160; 'WB transparency works if called here      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCylinderNode.RenderStyle = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.RenderStyles.Item(&quot;Red (clear)&quot;)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160; <font color="#0000ff">&#160;&#160;&#160;&#160;&#160; ' Create a triangle fan for cap 1 of the cylinder.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCap1TriangleFan As TriangleFanGraphics     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCap1TriangleFan = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCylinderNode.AddTriangleFanGraphics     <br />&#160; <font color="#0000ff">&#160;&#160;&#160;&#160;&#160; 'WB it works here      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'oCylinderNode.RenderStyle = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'oDoc.RenderStyles.Item(&quot;Red (clear)&quot;)     <br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">&#160;&#160; ' Set the coordinates and index set for the cap.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCap1TriangleFan.CoordinateSet = oCoordSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCap1TriangleFan.CoordinateIndexSet = oCap1Index     <br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">&#160;&#160;&#160;&#160; ' Create a triangle fan for cap 2 of the cylinder</font>.     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCap2TriangleFan As TriangleFanGraphics     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCap2TriangleFan = oCylinderNode. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AddTriangleFanGraphics</p>  <p>&#160; <font color="#0000ff">&#160;&#160;&#160;&#160;&#160; ' Set the coordinates and index set for the cap</font>.     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCap2TriangleFan.CoordinateSet = oCoordSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCap2TriangleFan.CoordinateIndexSet = oCap2Index     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' WB it works here for the previously added graphics      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'oCylinderNode.RenderStyle = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.RenderStyles.Item (&quot;Red (clear)&quot;)</p>  <p>&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">&#160; ' Create a triangle string for the sides of the cylinder.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCylinderStrip As TriangleStripGraphics     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCylinderStrip = oCylinderNode. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AddTriangleStripGraphics     <br />&#160;&#160; <font color="#0000ff">&#160;&#160;&#160;&#160; 'WB does not work here      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' oCylinderNode.RenderStyle = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; '&#160; oDoc.RenderStyles.Item(&quot;Red (clear)&quot;)</p>  <p>   <br />&#160; <font color="#0000ff">&#160;&#160;&#160;&#160;&#160; ' Set the coordinates and index set for the cap.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCylinderStrip.CoordinateSet = oCoordSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCylinderStrip.CoordinateIndexSet = oCylinderIndex     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'oCylinderNode.RenderStyle = oDoc.RenderStyles.Item(&quot;Purple&quot;)     <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; 'WB Added      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'WB this is not working here       <br /></font>&#160;&#160;&#160;&#160;&#160; '&#160; oCylinderNode.RenderStyle =     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'oDoc.RenderStyles.Item(&quot;Blue (clear)&quot;)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' update the display to see the results.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveView.Update     <br />&#160; <br />&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Define a normal for cap 1.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCap1Normals As GraphicsNormalSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCap1Normals = oDataSets.CreateNormalSet(1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap1Normals.Add _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (1, oTransGeom.CreateUnitVector(0, 0, -1))     <br />&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Assign the normals to the cap.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCap1TriangleFan.NormalSet = oCap1Normals     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Define a normal for cap 2.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCap2Normals As GraphicsNormalSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCap2Normals = oDataSets.CreateNormalSet(2)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCap2Normals.Add _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (1, oTransGeom.CreateUnitVector(0, 0, 1))     <br />&#160;&#160; <br />&#160;&#160; <font color="#0000ff">&#160;&#160;&#160;&#160; ' Assign the normals to the cap.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCap2TriangleFan.NormalSet = oCap2Normals     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">&#160;&#160;&#160;&#160; ' Create an array that contains the normals      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' for each vertex of the cylinder.       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim adNormals() As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ReDim adNormals _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (1 To ((iSideCount + 1) * 2) * 3) As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; dAngle = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 0 To iSideCount     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim dX As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim dY As Double     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; dX = Cos(dAngle)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; dY = Sin(dAngle)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adNormals(i * 6 + 1) = dX     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adNormals(i * 6 + 2) = dY     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adNormals(i * 6 + 3) = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adNormals(i * 6 + 4) = dX     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adNormals(i * 6 + 5) = dY     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; adNormals(i * 6 + 6) = 0</p>  <p>&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160;&#160; ' Increment the angle for the next normal</font>.     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; dAngle = dAngle + _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((2 * 3.14159265358979) / iSideCount)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Create and set the normal set for the cylinder.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCylinderNormals As GraphicsNormalSet     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCylinderNormals = oDataSets.CreateNormalSet(3)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oCylinderNormals.PutNormals(adNormals)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' Assign the normals to the cylinder.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCylinderStrip.NormalSet = oCylinderNormals     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">&#160; ' Does not work here      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' oCylinderNode.RenderStyle = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'oDoc.RenderStyles.Item(&quot;Blue (clear)&quot;)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; <font color="#0000ff">&#160;&#160; ' update the display to see the results.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveView.Update     <br />&#160;&#160;&#160; End If     <br />End Sub</p>
