---
layout: "post"
title: "Use a camera object to set the view of a document before saving it to a bitmap"
date: "2012-08-09 12:05:34"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/use-a-camera-object-to-set-the-view-of-a-document-before-saving-it-to-a-bitmap.html "
typepad_basename: "use-a-camera-object-to-set-the-view-of-a-document-before-saving-it-to-a-bitmap"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p>If you are using Fit method of a view before calling the SaveAsBitmap method of the view you may have noticed that the Fit does not occur until the code has exited and so you do not get the image you expect. To resolve this you can use the Camera object. </p>  <p><strong>VBA Example:</strong></p>  <p>Sub cameraAndSaveAsBitmap()    <br />&#160; If ThisApplication.Documents.count = 0 _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Then Exit Sub     <br />&#160; <br />&#160; Dim oView As view     <br />&#160; Set oView = ThisApplication.ActiveView     <br />&#160; <br />&#160; Dim oCamera As Camera     <br />&#160; Set oCamera = oView.Camera     <br />&#160; <br />&#160; oCamera.Fit     <br />&#160; <br />&#160; oCamera.Apply     <br />' OR oCamera.ApplyWithoutTransition     <br />&#160; <br />&#160; Call oView.SaveAsBitmap _     <br />&#160;&#160;&#160;&#160; (&quot;C:\temp\assembly.bmp&quot;, 400, 400)</p>  <p>End Sub</p>  <p><strong>VB.NET</strong></p>  <div style="font-family: consolas; background: #eeeeee; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Public</span> <span style="color: blue">Class</span> <span style="color: #2b91af">Form1</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> m_inventorApp <span style="color: blue">As</span> Inventor.<span style="color: #2b91af">Application</span> _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = <span style="color: blue">Nothing</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Private</span> <span style="color: blue">Sub</span> Button1_Click(<span style="color: blue">ByVal</span> sender <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.<span style="color: #2b91af">Object</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">ByVal</span> e <span style="color: blue">As</span> System.<span style="color: #2b91af">EventArgs</span>) _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Handles</span> Button1.Click</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Get an active instance of Inventor</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; InteropServices.<span style="color: #2b91af">Marshal</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160; GetActiveObject(<span style="color: #a31515">&quot;Inventor.Application&quot;</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Catch</span> <span style="color: green">'Inventor not started</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.Windows.Forms.<span style="color: #2b91af">MessageBox</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Show(<span style="color: #a31515">&quot;Start an Inventor session&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Exit Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Call the Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cameraAndSaveAsBitmap()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Sub</span> cameraAndSaveAsBitmap()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> m_inventorApp.Documents.Count = 0 _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Then</span> <span style="color: blue">Exit Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oView <span style="color: blue">As</span> <span style="color: #2b91af">view</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oView = m_inventorApp.ActiveView</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oCamera <span style="color: blue">As</span> <span style="color: #2b91af">Camera</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCamera = oView.Camera</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCamera.Fit()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCamera.Apply()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' OR oCamera.ApplyWithoutTransition</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> oView.SaveAsBitmap _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;C:\temp\assembly.bmp&quot;</span>, 400, 400)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Class</span></p> </div>
