---
layout: "post"
title: "Find All Curves on a Drawing View that Corresponds to Bend Center Lines in the Referenced Flat Pattern"
date: "2012-06-04 02:28:01"
author: "Barbara Han"
categories:
  - "Barbara Han"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/find-all-curves-on-a-drawing-view-that-corresponds-to-bend-center-lines-in-the-referenced-flat-pattern.html "
typepad_basename: "find-all-curves-on-a-drawing-view-that-corresponds-to-bend-center-lines-in-the-referenced-flat-pattern"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <p><b>Issue</b></p>  <p>I want to find all drawing curves that correspond to bend center lines in the referenced flat pattern. Is there a easy way to do this? After I have the drawing curve collection, I will make two collections out of it. One has to contain all the horizontal bend center lines and the other collection has to contain all the vertical bend center lines...</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>Below is a VB.NET sample that obtain all the curves on a particular drawing view that correspond to bend center lines in the referenced flat pattern and highlighting those curves. After you get those curves, you then can use DrawingCurveSegment object, which has StartPoint and EndPoint properties, to get horizontal and vertical bend lines.</p>  <p>Assumptions of the sample code:</p>  <ol>   <li>Drawing is active. </li>    <li>The first drawing view in the active drawing is the view of a flat pattern.</li> </ol>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Sub</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> BendLinesInDrawings()</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawing </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingDocument</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oDrawing = m_inApp.ActiveDocument</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawingView </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingView</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oDrawingView = oDrawing.ActiveSheet.DrawingViews.Item(1)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oPartDoc </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> PartDocument</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oPartDoc = oDrawingView.ReferencedDocumentDescriptor.ReferencedDocument</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oFlatPattern </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> FlatPattern</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oFlatPattern = oPartDoc.ComponentDefinition.FlatPattern</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oBendUpEdges </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Edges</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oBendUpEdges = oFlatPattern.GetEdgesOfType(</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; FlatPatternEdgeTypeEnum.kBendUpFlatPatternEdge)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oBendDownEdges </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Edges</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oBendDownEdges = oFlatPattern.GetEdgesOfType(</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; FlatPatternEdgeTypeEnum.kBendDownFlatPatternEdge)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">' Collect up all bend edges</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oBendEdges </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ObjectCollection</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oBendEdges = m_inApp.TransientObjects.CreateObjectCollection</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oEdge </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Edge</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">For</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Each</font></span><span style="line-height: 11pt"><font color="#000000"> oEdge </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">In</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oBendUpEdges</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oBendEdges.Add(oEdge)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">For</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Each</font></span><span style="line-height: 11pt"><font color="#000000"> oEdge </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">In</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oBendDownEdges</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oBendEdges.Add(oEdge)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oHighlight </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> HighlightSet = m_inApp.ActiveDocument.CreateHighlightSet</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oRed </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Color</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oRed = m_inApp.TransientObjects.CreateColor(255, 0, 0)</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oHighlight.Color = oRed</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">For</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Each</font></span><span style="line-height: 11pt"><font color="#000000"> oEdge </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">In</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oBendEdges</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawingCurves </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingCurvesEnumerator</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oDrawingCurves = oDrawingView.DrawingCurves(oEdge)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oCurve </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingCurve</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">For</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Each</font></span><span style="line-height: 11pt"><font color="#000000"> oCurve </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">In</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oDrawingCurves</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oSegment </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingCurveSegment</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">For</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Each</font></span><span style="line-height: 11pt"><font color="#000000"> oSegment </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">In</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oCurve.Segments</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oHighlight.AddItem(oSegment)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p> </div>
