---
layout: "post"
title: "B-Rep information NonParametricBaseFeature"
date: "2012-08-08 12:24:55"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/b-rep-information-nonparametricbasefeature.html "
typepad_basename: "b-rep-information-nonparametricbasefeature"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p>If you import a model from another format there should be NonParametricBaseFeature. You can use this to get B-Rep infromation. (In Inventor 2011 this was the only way to get this information from a model imported from another format.)</p>  <p><a name="section2"></a></p>  <p>Here are VBA and VB.NET examples accessing the surface body of the model from the NonParametricBaseFeature. These examples print out the Brep information in the immediate window.</p>  <p>&#160;</p>  <p>Sub NonParametricBaseFeatures()    <br />&#160; <font color="#0000ff">&#160; 'get the non param feature      <br /></font>&#160;&#160;&#160; Dim nonparamF As NonParametricBaseFeature     <br />&#160;&#160;&#160; Dim basebody As SurfaceBody     <br />&#160;&#160;&#160; Dim pdoc As PartDocument     <br />&#160;&#160;&#160; Set pdoc = ThisApplication.ActiveDocument     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Set nonparamF = pdoc.ComponentDefinition. _     <br />&#160;&#160;&#160;&#160;&#160; Features.NonParametricBaseFeatures.Item(1)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Call nonparamF.Edit     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Set basebody = nonparamF.BaseSolidBody     <br />&#160;&#160;&#160; <font color="#0000ff">'Works too in Inventor 2013      <br />&#160;&#160;&#160; 'Set basebody = pdoc.ComponentDefinition _       <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .SurfaceBodies(1)       <br /></font>&#160;&#160;&#160; Call AnalyseSurfaceBody(basebody)     <br />&#160;&#160;&#160; Call nonparamF.ExitEdit     <br />End Sub</p>  <p>Sub AnalyseSurfaceBody(oSB As SurfaceBody)    <br />&#160;&#160;&#160; Dim I As Long     <br />&#160;&#160;&#160; For I = 1 To oSB.Edges.count     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oEdge As Edge     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oEdge = oSB.Edges(I)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oEdge.CurveType = kCircleCurve Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print oEdge.CurveType &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; -&gt; Circle&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ElseIf (oEdge.CurveType = kLineCurve) Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print oEdge.CurveType &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; -&gt; Line&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print oEdge.CurveType &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; -&gt; Other types or Unknown&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; Next I     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; For I = 1 To oSB.Faces.count     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oFace As Face     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oFace = oSB.Faces(I)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If (oFace.SurfaceType = kCylinderSurface) Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print oFace.SurfaceType &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; -&gt; Cylinder&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ElseIf (oFace.SurfaceType = kPlaneSurface) Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print oFace.SurfaceType &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; -&gt; Plane&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print oFace.SurfaceType &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; -&gt; Other types or Unknown&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; Next I     <br />End Sub</p>  <p><strong>VB.NET</strong></p>  <div style="font-family: consolas; background: #eeeeee; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Public</span> <span style="color: blue">Class</span> <span style="color: #2b91af">Form1</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> m_inventorApp <span style="color: blue">As</span> Inventor.<span style="color: #2b91af">Application</span> _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = <span style="color: blue">Nothing</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Private</span> <span style="color: blue">Sub</span> Button1_Click(<span style="color: blue">ByVal</span> sender <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.<span style="color: #2b91af">Object</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">ByVal</span> e <span style="color: blue">As</span> System.<span style="color: #2b91af">EventArgs</span>) _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Handles</span> Button1.Click</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Get an active instance of Inventor</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; InteropServices.<span style="color: #2b91af">Marshal</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160; GetActiveObject(<span style="color: #a31515">&quot;Inventor.Application&quot;</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Catch</span> <span style="color: green">'Inventor not started</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.Windows.Forms.<span style="color: #2b91af">MessageBox</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Show(<span style="color: #a31515">&quot;Start an Inventor session&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Exit Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Call the Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; NonParametricBaseFeatures()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Sub</span> NonParametricBaseFeatures()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'get the non param feature</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> nonparamF <span style="color: blue">As</span> <span style="color: #2b91af">NonParametricBaseFeature</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> basebody <span style="color: blue">As</span> <span style="color: #2b91af">SurfaceBody</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> pdoc <span style="color: blue">As</span> <span style="color: #2b91af">PartDocument</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pdoc = m_inventorApp.ActiveDocument</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; nonparamF = pdoc.ComponentDefinition. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Features.NonParametricBaseFeatures.Item(1)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> nonparamF.Edit()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; basebody = nonparamF.BaseSolidBody</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Works too in Inventor 2013</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Set basebody = pdoc.ComponentDefinition _</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'.SurfaceBodies(1)</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> AnalyseSurfaceBody(basebody)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> nonparamF.ExitEdit()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Sub</span> AnalyseSurfaceBody(oSB <span style="color: blue">As</span> <span style="color: #2b91af">SurfaceBody</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> I <span style="color: blue">As</span> <span style="color: blue">Long</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">For</span> I = 1 <span style="color: blue">To</span> oSB.Edges.count</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oEdge <span style="color: blue">As</span> <span style="color: #2b91af">Edge</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEdge = oSB.Edges(I)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> oEdge.CurveType = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">CurveTypeEnum</span>.kCircleCurve <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(oEdge.CurveType &amp; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot; -&gt; Circle&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">ElseIf</span> (oEdge.CurveType = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">CurveTypeEnum</span>.kLineCurve) <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(oEdge.CurveType &amp; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot; -&gt; Line&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(oEdge.CurveType &amp; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot; -&gt; Other types or Unknown&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Next</span> I</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">For</span> I = 1 <span style="color: blue">To</span> oSB.Faces.count</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oFace <span style="color: blue">As</span> <span style="color: #2b91af">Face</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oFace = oSB.Faces(I)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> (oFace.SurfaceType = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceTypeEnum</span>.kCylinderSurface) <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(oFace.SurfaceType &amp; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot; -&gt; Cylinder&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">ElseIf</span> (oFace.SurfaceType = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceTypeEnum</span>.kPlaneSurface) <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(oFace.SurfaceType &amp; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot; -&gt; Plane&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(oFace.SurfaceType &amp; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot; -&gt; Other types or Unknown&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Next</span> I</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Class</span></p> </div>
