---
layout: "post"
title: "Extrude the Text in Inventor"
date: "2012-08-27 13:38:20"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/extrude-the-text-in-inventor.html "
typepad_basename: "extrude-the-text-in-inventor"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>Inventor supports the extrusion of Text object. The following sample code demonstrates how to extrude the text.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> ExtrudeText()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'create a part Document</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oPartDoc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">PartDocument</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oPartDoc = m_inventorApplication.Documents.Add( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">DocumentTypeEnum</font></span><font color="#000000">.kPartDocumentObject, _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; m_inventorApplication.FileManager.GetTemplateFile( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">DocumentTypeEnum</font></span><font color="#000000">.kPartDocumentObject))</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oCompDef </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">PartComponentDefinition</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oCompDef = oPartDoc.ComponentDefinition</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'get the xy work plane</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oSketch </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">PlanarSketch</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oSketch = oCompDef.Sketches.Add( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oCompDef.WorkPlanes.Item(3))</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' access the transient geometry object</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oTG </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">TransientGeometry</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oTG = m_inventorApplication.TransientGeometry</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Call</font></span><font color="#000000"> oSketch.SketchLines.AddAsTwoPointRectangle( _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oTG.CreatePoint2d(0, 0), oTG.CreatePoint2d(20, 10))</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' prepare the skecth for extrusion</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oProfile </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">Profile</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oProfile = oSketch.Profiles.AddForSolid</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' create the extrusion</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oExtrudeDef </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">ExtrudeDefinition</font></span><font color="#000000"> = _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oCompDef.Features.ExtrudeFeatures. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; CreateExtrudeDefinition(oProfile, _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PartFeatureOperationEnum</font></span><font color="#000000">.kJoinOperation)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oExtrudeDef.SetDistanceExtent(2, _ </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PartFeatureExtentDirectionEnum</font></span><font color="#000000">.kNegativeExtentDirection)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oExtrude </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">ExtrudeFeature</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' get the active camera and fit the view</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oCamera </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">Camera</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oCamera = m_inventorApplication.ActiveView.Camera</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; oCamera.ViewOrientationType = </font></font><font style="font-size: 8pt"><span><font color="#2b91af">ViewOrientationTypeEnum</font></span><font color="#000000">. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; kIsoTopLeftViewOrientation</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oCamera.Fit()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oCamera.Apply()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Place Sketch Text&#160;&#160; </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oSketch = oCompDef.Sketches.Add( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oExtrude.StartFaces.Item(1))</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oText </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">TextBox</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oText = oSketch.TextBoxes.AddByRectangle( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oTG.CreatePoint2d(0, 0), _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oTG.CreatePoint2d(20, 10), _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;&lt;StyleOverride FontSize='2.54' Bold='True'&gt;&quot;</font></span><font color="#000000"> +</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;Sample&lt;/StyleOverride&gt;&quot;</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oText.HorizontalJustification = _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">HorizontalTextAlignmentEnum</font></span><font color="#000000">.kAlignTextCenter</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oText.VerticalJustification = _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">VerticalTextAlignmentEnum</font></span><font color="#000000">.kAlignTextMiddle</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Extrude Text&#160; </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oProfile = oSketch.Profiles.AddForSolid</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oExtrude = oCompDef.Features.ExtrudeFeatures. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; AddByDistanceExtent(oProfile, 0.5, _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PartFeatureExtentDirectionEnum</font></span><font color="#000000">. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kPositiveExtentDirection, _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">PartFeatureOperationEnum</font></span><font color="#000000">.kJoinOperation)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p> </div>
