---
layout: "post"
title: "Create Leader Note with the Value of User or Model Parameter or Document Property"
date: "2012-07-10 00:57:44"
author: "Barbara Han"
categories:
  - "Barbara Han"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/07/create-leader-note-with-the-value-of-user-or-model-parameter-or-document-property.html "
typepad_basename: "create-leader-note-with-the-value-of-user-or-model-parameter-or-document-property"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <p><strong>Issue</strong>    <br />We are looking for the way of linking the user or model parameter in part file to the leader note text in drawing through API. We have done it manually but we wanted to do that through API. The following picture illustrates the result what we want. The highlighted in red is the parameter to be used.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01676857d9e6970b-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="115" border="0" alt="115" src="/assets/image_d92550.jpg" width="488" height="311" /></a></p>  <p>Solution   <br />The LeaderNote.FormatedText property is writable and supports document property tag and parameter tag.    <br />&#160; <br />First of all, find style override string for the LeaderNote.FormatedText property, for example: (the ComponentIdentifier string is the part file path, which must be different in each case.)&#160; <br /><font size="1" face="Courier New">&lt;StyleOverride Font='Arial'&gt;&lt;Parameter Resolved='True' ComponentIdentifier='C:\Users\hanb\Documents\Disc.ipt' Name='HoleQuantity' Precision='0'&gt;8&lt;/Parameter&gt;&lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt; HOLES ON DIA &lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt;&lt;Parameter Resolved='True' ComponentIdentifier='C:\Users\hanb\Documents\Disc.ipt' Name='HolePCD' Precision='0'&gt;35&lt;/Parameter&gt;&lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt;±0.1 &lt;/StyleOverride&gt;&lt;Br/&gt;&lt;StyleOverride Font='Arial'&gt;WITH &lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt;&lt;Parameter Resolved='True' ComponentIdentifier='C:\Users\hanb\Documents\Disc.ipt' Name='HoleQuantity' Precision='0'&gt;8&lt;/Parameter&gt;&lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt; DIVISIONS&lt;/StyleOverride&gt;     <br /></font>&#160; <br />You can get above string through running the following VBA code after you created a needed Leader note from UI:    <br /><font size="1" face="Courier New">Sub test()     <br />&#160;&#160;&#160; Dim oDoc As DrawingDocument      <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument      <br />&#160;&#160;&#160; Dim s As String      <br />&#160;&#160;&#160; s = oDoc.ActiveSheet.DrawingNotes.LeaderNotes.Item(1).FormattedText      <br />&#160;&#160;&#160; Debug.Print s      <br />End Sub</font>    <br />&#160; <br />Delete that Leader note from UI, then select the curve (circle in this case) to which the LeaderNote is appended, and run the following VBA code to create the LeaderNote through API:</p>  <p>   <br /><font size="1" face="Courier New">Sub CreateLN()     <br />Dim oDoc As DrawingDocument      <br />Set oDoc = ThisApplication.ActiveDocument      <br />Dim s As String      <br />s = &quot;&lt;StyleOverride Font='Arial'&gt;&lt;Parameter Resolved='True' ComponentIdentifier='C:\Users\hanb\Documents\Disc.ipt' Name='HoleQuantity' Precision='0'&gt;8&lt;/Parameter&gt;&lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt; HOLES ON DIA &lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt;&lt;Parameter Resolved='True' ComponentIdentifier='C:\Users\hanb\Documents\Disc.ipt' Name='HolePCD' Precision='0'&gt;35&lt;/Parameter&gt;&lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt;±0.1 &lt;/StyleOverride&gt;&lt;Br/&gt;&lt;StyleOverride Font='Arial'&gt;WITH &lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt;&lt;Parameter Resolved='True' ComponentIdentifier='C:\Users\hanb\Documents\Disc.ipt' Name='HoleQuantity' Precision='0'&gt;8&lt;/Parameter&gt;&lt;/StyleOverride&gt;&lt;StyleOverride Font='Arial'&gt; DIVISIONS&lt;/StyleOverride&gt;&quot;      <br />&#160; <br />Dim curve As DrawingCurve      <br />Set curve = oDoc.SelectSet.Item(1).Parent      <br />Dim oGI1 As GeometryIntent      <br />Set oGI1 = oDoc.ActiveSheet.CreateGeometryIntent(curve, kCenterPointIntent)      <br />&#160; <br />Dim pt As Point2d      <br />Set pt = ThisApplication.TransientGeometry.CreatePoint2d      <br />&#160; <br />pt.X = curve.CenterPoint.X + 3      <br />pt.Y = curve.CenterPoint.Y + 5      <br />&#160; <br />Dim oObjCol As ObjectCollection      <br />Set oObjCol = ThisApplication.TransientObjects.CreateObjectCollection      <br />oObjCol.Add pt      <br />oObjCol.Add oGI1      <br />&#160; <br />Dim oLN As LeaderNote      <br />' create a LeaderNote.      <br />Set oLN = oDoc.ActiveSheet.DrawingNotes.LeaderNotes.Add(oObjCol, &quot;&quot;)      <br />oLN.FormattedText = s      <br />End Sub</font></p>  <p>Note: Above string named &quot;s&quot; can be changed to accommodate other parameter and properties, such as Model parameter, part number property.</p>
