---
layout: "post"
title: "How to Determine Which Drawing Dimensions Belong to a Particular View"
date: "2012-08-16 13:55:00"
author: "Barbara Han"
categories:
  - "Barbara Han"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/how-to-determine-which-drawing-dimensions-belong-to-a-particular-view.html "
typepad_basename: "how-to-determine-which-drawing-dimensions-belong-to-a-particular-view"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <p><b>Issue</b></p>  <p>I want to be able to determine or sort out which drawing dimensions belongs to a view in a drawing. Is there an example that shows how this can be done?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>A DrawingDimension object is not directly related to a particular view, they are just annotations on a Sheet. So there is not a direct way to determine which View a DrawingDimension belongs to. </p>  <p>However you can reach this information through the &quot;Intent&quot; property of the GeneralDimension, which is dependent of the View. </p>  <p>Here is a VBA example that you can run on a drawing document. It will iterate through the DrawingDimensions of the sheet and find out if the dimension belongs to a given View, based on the view's name: </p>  <p>VBA:</p>  <p><font size="1" face="Courier New">Public Function GetDrawingDimForView(oSheet As Sheet, ViewName As String) As ObjectCollection     <br />&#160;&#160;&#160; Dim oDrawDimsForView As ObjectCollection      <br />&#160;&#160;&#160; Set oDrawDimsForView = ThisApplication.TransientObjects.CreateObjectCollection      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oDrawDims As DrawingDimensions      <br />&#160;&#160;&#160; Set oDrawDims = oSheet.DrawingDimensions      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oDrawDimIterator As DrawingDimension      <br />&#160;&#160;&#160; For Each oDrawDimIterator In oDrawDims      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Select Case oDrawDimIterator.Type      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kLinearGeneralDimensionObject      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oLinearDim As LinearGeneralDimension      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oLinearDim = oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oLinearDim.IntentOne.Geometry.Parent.Name = ViewName Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kRadiusGeneralDimensionObject      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oRadiusDim As RadiusGeneralDimension      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oRadiusDim = oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oRadiusDim.Intent.Geometry.Parent.Name = ViewName Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kDiameterGeneralDimensionObject      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oDiameterDim As DiameterGeneralDimension      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oDiameterDim = oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oDiameterDim.Intent.Geometry.Parent.Name = ViewName Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kAngularGeneralDimensionObject      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oAngularDim As AngularGeneralDimension      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oAngularDim = oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oAngularDim.IntentOne.Geometry.Parent.Name = ViewName Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add oDrawDimIterator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case Else      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'Case is not handled...      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End Select      <br />&#160;&#160;&#160; Next      <br />&#160;&#160;&#160; Set GetDrawingDimForView = oDrawDimsForView      <br />End Function</font></p>  <p><font size="1" face="Courier New">'Test function GetDrawingDimForView     <br />Public Sub TestGetDrawingDimensions()      <br />&#160;&#160;&#160; Dim oDoc As DrawingDocument      <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument      <br />&#160;&#160;&#160; Dim oDrawingDimCollec1 As ObjectCollection      <br />&#160;&#160;&#160; Set oDrawingDimCollec1 = GetDrawingDimForView(oDoc.ActiveSheet, &quot;VIEW1&quot;)      <br />&#160;&#160;&#160; Dim oDrawingDimCollec2 As ObjectCollection      <br />&#160;&#160;&#160; Set oDrawingDimCollec2 = GetDrawingDimForView(oDoc.ActiveSheet, &quot;VIEW2&quot;)      <br />End Sub</font></p>  <p>VB.NET:</p>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Function</font></span><span style="line-height: 11pt"><font color="#000000"> GetDrawingDimForView(</font></span><span style="line-height: 11pt; color: "><font color="#0000ff">ByVal</font></span><span style="line-height: 11pt"><font color="#000000"> oSheet </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> Sheet, </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">ByVal</font></span><span style="line-height: 11pt"><font color="#000000"> ViewName </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">String</font></span><span style="line-height: 11pt"><font color="#000000">) </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ObjectCollection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawDimsForView </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ObjectCollection</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oDrawDimsForView = _InvApplication.ActiveDocument.TransientObjects.CreateObjectCollection</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawDims </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingDimensions</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oDrawDims = oSheet.DrawingDimensions</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawDimIterator </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingDimension</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">For</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Each</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawDimIterator </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">In</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oDrawDims</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Select</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Case</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oDrawDimIterator.Type</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Case</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> kLinearGeneralDimensionObject</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oLinearDim </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> LinearGeneralDimension</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLinearDim = oDrawDimIterator</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">If</font></span><span style="line-height: 11pt"><font color="#000000"> oLinearDim.IntentOne.Geometry.Parent.Name = ViewName </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add(oDrawDimIterator)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Case</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> kRadiusGeneralDimensionObject</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oRadiusDim </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> RadiusGeneralDimension</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oRadiusDim = oDrawDimIterator</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">If</font></span><span style="line-height: 11pt"><font color="#000000"> oRadiusDim.Intent.Geometry.Parent.Name = ViewName </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add(oDrawDimIterator)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Case</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> kDiameterGeneralDimensionObject</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDiameterDim </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DiameterGeneralDimension</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDiameterDim = oDrawDimIterator</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">If</font></span><span style="line-height: 11pt"><font color="#000000"> oDiameterDim.Intent.Geometry.Parent.Name = ViewName </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add(oDrawDimIterator)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Case</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> kAngularGeneralDimensionObject</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oAngularDim </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> AngularGeneralDimension</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oAngularDim = oDrawDimIterator</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">If</font></span><span style="line-height: 11pt"><font color="#000000"> oAngularDim.IntentOne.Geometry.Parent.Name = ViewName </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDimsForView.Add(oDrawDimIterator)</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Case Else</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">'Case is not handled... </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Select</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; GetDrawingDimForView = oDrawDimsForView</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Function</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt; color: "><font face="Courier New"><font style="font-size: 8pt" color="#008000">'Test function GetDrawingDimForViewPublic </font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">Sub</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> TestGetDrawingDimensions()</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDoc </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> DrawingDocument</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oDoc = _InvApplication.ActiveDocument.ActiveDocument</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawingDimCollec1 </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ObjectCollection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; oDrawingDimCollec1 = GetDrawingDimForView(oDoc.ActiveSheet, </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#a31515">&quot;VIEW1&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oDrawingDimCollec2 </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ObjectCollection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; oDrawingDimCollec2 = GetDrawingDimForView(oDoc.ActiveSheet, </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#a31515">&quot;VIEW2&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p> </div>  <p>In the case where you have to deal with dimensions that are not GeneralDimensions, the function above is no longer valid and you have no means to sort out these dimensions through that way. However you can still check the &quot;Annotations Visibility-&gt;Drawing Dimensions&quot; setting by right-clicking on a view to activate the dimensions on this particular view, and uncheck the same setting on other views. Then if you run this code: </p>  <p><font size="1" face="Courier New">Dim oDoc As DrawingDocumentSet      <br />oDoc = ThisApplication.ActiveDocument      <br />Dim oDrawDims As DrawingDimensionsSet       <br />oDrawDims = oDoc.ActiveSheet.DrawingDimensions</font>     <br />You will get the complete set of DrawingDimensions that are in the specified view. </p>
