---
layout: "post"
title: "Run Half Section View Command in Assembly through API"
date: "2012-06-11 20:54:39"
author: "Barbara Han"
categories:
  - "Barbara Han"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/run-half-section-view-command-in-assembly-through-api.html "
typepad_basename: "run-half-section-view-command-in-assembly-through-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <div style="line-height: 16px; clear: both" class="clear"><b><font color="#000000">Issue</font></b>    <br /></div>  <div style="line-height: 16px; clear: both" class="clear"><font color="#000000"></font></div>  <div style="line-height: 16px; clear: both" class="clear"><font color="#000000">I would like to run the Half Section View command from the Inventor assembly. If this is no direct API, how can I find the command and run it from the API?</font></div>  <div style="line-height: 16px; clear: both" class="clear"><b><font color="#000000"></font></b></div>  <div style="line-height: 16px; clear: both" class="clear"><b><font color="#000000">Solution</font></b>    <br /></div>  <div style="line-height: 16px; clear: both" class="clear">   <p style="margin: 0px 0px 15px"><font color="#000000">First of all, you may want to know what command in API world is for “Half Section View” command in UI. You can get all commands' information using below several lines of VBA code:</font></p>    <p><font size="1" face="Courier New">Sub printCmdInfo()       <br />&#160;&#160;&#160; Dim oControlDef As ControlDefinition        <br />&#160;&#160;&#160; Open &quot;c:\1.txt&quot; For Output As #1        <br />&#160;&#160;&#160; Dim s As String        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; For Each oControlDef In ThisApplication.CommandManager. _        <br />&#160;&#160;&#160; ControlDefinitions        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; s = oControlDef.InternalName &amp; &quot;:&quot; &amp; _        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oControlDef.DescriptionText        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Write #1, s        <br />&#160;&#160;&#160; Next        <br />&#160;&#160;&#160; Close #1        <br />End Sub</font></p>    <p style="margin: 0px 0px 15px"><font color="#000000">Open the C:\1.txt file created by above code, you can find the name for the Half Section View command in Assembly environment is “AssemblyHalfSectionViewCmd”.</font></p>    <p style="margin: 0px 0px 15px"><font color="#000000">If you have a plane selected before running above line, there will be no user interaction needed when you executing above line. If this is not the case, you can select a work plane via API too, for example:</font></p>    <p><font size="1" face="Courier New">Dim assm As AssemblyDocument       <br />Set assm = ThisApplication.ActiveDocument        <br />ThisApplication.ActiveDocument.SelectSet.Select assm.ComponentDefinition.WorkPlanes.Item(4)</font></p>    <p style="margin: 0px 0px 15px"><font color="#000000">Then you can call this command programmatically like this:</font></p>    <p><font size="1" face="Courier New">ThisApplication.CommandManager.ControlDefinitions.Item(&quot;AssemblyHalfSectionViewCmd&quot;).Execute       <br /></font><font color="#000000"></font></p>    <p><font color="#000000">The Offset dialog will pop up after calling above line of code, you can set a value in the Offset dialog then exit it by SendKeys method, for example:</font></p>   <font size="1" face="Courier New">SendKeys &quot;0.02&quot;     <br />SendKeys &quot;{ENTER}&quot;</font></div>
