---
layout: "post"
title: "ModelToSketchSpace Transformation Matrix"
date: "2012-08-22 11:41:32"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/modeltosketchspace-transformation-matrix.html "
typepad_basename: "modeltosketchspace-transformation-matrix"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>The transformation matrix&#160; for <strong>ModelToSketchSpace</strong> can be obtained from the <strong>PlanarSketch</strong> object. It wouldn't be too difficult to calculate it ourselves, but a combination of the <strong>OriginPointGeometry</strong>, <strong>PlanarEntityGeometry</strong>, <strong>AxisEntityGeometry</strong>, and <strong>AxisIsX</strong> properties give us everything we need to compute this matrix.</p>  <p>The&#160; function shown below accepts a <strong>PlanarSketch</strong> object as an argument and returns Matrix object which is required for Model to Sketch Space transformation. Try go through the code reading the comments.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Function</font></span><font color="#000000"> createModelToSkecthMatrix( _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ByVal</font></span><font color="#000000"> sketch </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">PlanarSketch</font></span><font color="#000000">) </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">Matrix</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' get the sketch origin point</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> origin </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Point</font></span><font color="#000000"> = sketch.OriginPointGeometry</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and the sketch axis</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> lineAxis </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Line</font></span><font color="#000000"> = sketch.AxisEntityGeometry</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' to get the sketch direction</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> direction </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">UnitVector</font></span><font color="#000000"> = lineAxis.Direction</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' now the sketch plane</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> plane </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Plane</font></span><font color="#000000"> = sketch.PlanarEntityGeometry</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' to then get the sketch normal (unit vector)</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> zAxisUnit </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">UnitVector</font></span><font color="#000000"> = plane.Normal</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and get the vector</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> zAxis </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Vector</font></span><font color="#000000"> = zAxisUnit.AsVector</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' finally get the X and Y axis according </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' to the sketch property</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> xAxis </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">Vector</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> yAxis </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">Vector</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">If</font></span><font color="#000000"> (sketch.AxisIsX) </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' X axis along the sketch direction</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; xAxis = direction.AsVector</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and the Y axis as the cross product X-Z</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; yAxis = zAxis.CrossProduct(xAxis)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#0000ff">Else</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' or the Y axis as the sketch direction</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; yAxis = direction.AsVector</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and the X axis as the cross product Y-Z</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; xAxis = yAxis.CrossProduct(zAxis)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' create a blank matrix</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> coordMatrix </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Matrix</font></span><font color="#000000"> = sketch.Application. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; TransientGeometry.CreateMatrix</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' finally set the matrix as a coordinate </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' system matrix using the calculate data</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; coordMatrix.SetCoordinateSystem( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; origin, xAxis, yAxis, zAxis)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Return</font></span><font color="#000000"> coordMatrix</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Function</font></span></font></p> </div>
