---
layout: "post"
title: "Project the cutted edges of an assembly on sketch"
date: "2012-08-23 10:45:47"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/project-the-cutted-edges-of-an-assembly-on-sketch.html "
typepad_basename: "project-the-cutted-edges-of-an-assembly-on-sketch"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>One possible solution is call programmatically the built-in command &quot;<strong>Project Cut Edges...</strong>&quot;, which is available through the user interface.</p>  <p>To do it with the user interface, follow the steps:</p>  <ul>   <li>Select a WorkPlane in your assembly</li>    <li>Using the <strong>Create Component</strong> command a part is created with a default sketch in Edit mode based on the workplane</li>    <li>Select the occurrence you want to project</li>    <li>Use the <strong>Project Cut Edges</strong> command</li> </ul>  <p>To perform the same thing programmatically, there is no direct equivalent in the API currently, however there is a workaround: this is a mix of API calls &amp; user commands called programmatically which is following the workflow described above.</p>  <p>To test it, open an assembly file, select or create a workplane that intersect with the assembly and run the following sample <strong>TestProjectCutEdges</strong> method, replacing &quot;<em>PartTestProjection:1</em>&quot; by the name of the occurrence you want to project as it appears in the browser pane.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> TestProjectCutEdges()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' access the active document as</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' Assembly Document</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">If</font></span><font color="#000000"> (m_inventorApplication.ActiveDocumentType &lt;&gt; _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">DocumentTypeEnum</font></span><font color="#000000">.kAssemblyDocumentObject) </font><span><font color="#0000ff">Then</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Return</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oAsmDoc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">AssemblyDocument</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oAsmDoc = m_inventorApplication. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; ActiveDocument</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' get the workplane</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oWorkPlane </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">WorkPlane</font></span><font color="#000000"> = </font><span><font color="#0000ff">TryCast</font></span><font color="#000000">(</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; m_inventorApplication. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; ActiveDocument.SelectSet.Item(1),&#160; _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">WorkPlane</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">If</font></span><font color="#000000"> (oWorkPlane </font><span><font color="#0000ff">Is</font></span><font color="#000000"> </font><span><font color="#0000ff">Nothing</font></span><font color="#000000">) </font><span><font color="#0000ff">Then</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Return</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' start the method</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; MethodProjectCutEdges(oAsmDoc, _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWorkPlane, _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;PartTestProjection:1&quot;</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> MethodProjectCutEdges( _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ByVal</font></span><font color="#000000"> oAsmDoc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">AssemblyDocument</font></span><font color="#000000">, _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ByVal</font></span><font color="#000000"> oWorkPlane </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">WorkPlane</font></span><font color="#000000">, _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ByVal</font></span><font color="#000000"> OccurenceName </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#0000ff">String</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> xVector </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Vector</font></span><font color="#000000"> = </font></font><span><font style="font-size: 8pt" color="#0000ff">Nothing</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> yVector </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Vector</font></span><font color="#000000"> = </font></font><span><font style="font-size: 8pt" color="#0000ff">Nothing</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> zVector </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Vector</font></span><font color="#000000"> = oWorkPlane.Plane.Normal.AsVector</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Create a coordinate system based on the workplane's normal vector</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; CreateCoordSystem(xVector, yVector, zVector)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' create a transformation matrix</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oMatrix </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Matrix</font></span><font color="#000000"> = m_inventorApplication. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; TransientGeometry.CreateMatrix</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and set the coordinate system</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oMatrix.SetCoordinateSystem( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oWorkPlane.Plane.RootPoint, _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; xVector, yVector, zVector)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' create a new part document</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oPartDoc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">PartDocument</font></span><font color="#000000"> = m_inventorApplication. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; Documents.Add(</font></font><font style="font-size: 8pt"><span><font color="#2b91af">DocumentTypeEnum</font></span><font color="#000000">.kPartDocumentObject, _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApplication.FileManager. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetTemplateFile( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#2b91af">DocumentTypeEnum</font></span><font color="#000000">.kPartDocumentObject), _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">False</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and add as an occurrence to the active assembly document</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oCompOcc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">ComponentOccurrence</font></span><font color="#000000"> = oAsmDoc. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; ComponentDefinition.Occurrences.AddByComponentDefinition( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; oPartDoc.ComponentDefinition, oMatrix)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and start edit mode</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oCompOcc.Edit()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' access the part document component definition</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oPartCompDef </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">PartComponentDefinition</font></span><font color="#000000"> = _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; oCompOcc.Definition</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and create a new sketch</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oSketch </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">Sketch</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oSketch = oPartCompDef.Sketches.Add( _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; oPartCompDef.WorkPlanes.Item(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;XY Plane&quot;</font></span><font color="#000000">))</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oSketch.Edit()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' make the part occurrence as the selection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oSelectedOcc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Object</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oSelectedOcc = oAsmDoc.ComponentDefinition. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; Occurrences.ItemByName(OccurenceName)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oAsmDoc.SelectSet.Clear()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oAsmDoc.SelectSet.Select(oSelectedOcc)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' and execute the built-in command</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; m_inventorApplication.CommandManager. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; ControlDefinitions. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; Item(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;SketchProjectCutEdgesCmd&quot;</font></span><font color="#000000">).Execute()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> CreateCoordSystem(</font><span><font color="#0000ff">ByRef</font></span><font color="#000000"> xVector </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Vector</font></span><font color="#000000">, _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ByRef</font></span><font color="#000000"> yVector </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Vector</font></span><font color="#000000">, _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ByRef</font></span><font color="#000000"> zVector </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Vector</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' get the transient geometry object</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> tg </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">TransientGeometry</font></span><font color="#000000"> = m_inventorApplication. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; TransientGeometry</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> Tolerance </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#0000ff">Double</font></span><font color="#000000"> = 0.000000000001</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Set a tolerance treshold for the normal vector</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">If</font></span><font color="#000000"> </font><span><font color="#2b91af">Math</font></span><font color="#000000">.Abs(zVector.X) &lt; Tolerance </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; zVector.X = 0.0#</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ElseIf</font></span><font color="#000000"> </font><span><font color="#2b91af">Math</font></span><font color="#000000">.Abs(zVector.Y) &lt; Tolerance </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; zVector.Y = 0.0#</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ElseIf</font></span><font color="#000000"> </font><span><font color="#2b91af">Math</font></span><font color="#000000">.Abs(zVector.Z) &lt; Tolerance </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; zVector.Z = 0.0#</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">If</font></span><font color="#000000"> zVector.X &lt;&gt; 0 </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; xVector = tg.CreateVector(-zVector.Y / zVector.X, 1, 0)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; yVector = zVector.CrossProduct(xVector)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ElseIf</font></span><font color="#000000"> zVector.Y &lt;&gt; 0 </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; xVector = tg.CreateVector(0, -zVector.Z / zVector.Y, 1)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; yVector = zVector.CrossProduct(xVector)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">ElseIf</font></span><font color="#000000"> zVector.Z &lt;&gt; 0 </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; xVector = tg.CreateVector(1, 0, 0)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; yVector = zVector.CrossProduct(xVector)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p> </div>
