---
layout: "post"
title: "Get/Set Assembly Properties from AutoCAD Mechanical by API"
date: "2012-07-24 03:31:47"
author: "Barbara Han"
categories:
  - "AutoCAD Mechanical"
  - "Barbara Han"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/07/get-assembly-properties-from-autocad-mechanical-by-api.html "
typepad_basename: "get-assembly-properties-from-autocad-mechanical-by-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <p>When creating a new drawing in AcadM 2013 and running the command &quot;_ampartrefedit&quot; with option &quot;_a&quot; (assembly properties). A dialog shows up and the user can add/define properties. Some of our partner need to access to those property data using API. </p>  <p>The assembly property is associated with the model space block table record. So you can first get the model space ID and use API AcmBOMManager::getPartData() to get the assembly property data. This API is provided by SymBBAuto type library. For AutoCAD Mechanical 2013, you need to add reference to SymBBAuto 4.0 type library.</p>  <p>The following are two VBA samples that you can refer to:</p>  <table border="1" cellspacing="0" cellpadding="2" width="462"><tbody>     <tr>       <td valign="top" width="460">         <p>Sub setgetAssemblyAttributes() </p>          <p>' Set reference to symbol Manager            <br />Dim oSymBBMgr As McadSymbolBBMgr             <br />Set oSymBBMgr = Application.GetInterfaceObject(&quot;SymBBAuto.McadSymbolBBMgr&quot;) </p>          <p>' Set reference to BOM Manager            <br />Dim oBoMMgr As McadBOMMgr             <br />Set oBoMMgr = oSymBBMgr.BOMMgr </p>          <p>           <br />' Check if the assembly properties have been initialized </p>          <p>' Get the assembly attributes from current database modelspace            <br />Dim vdata As Variant             <br />vdata = oBoMMgr.GetPartData(ThisDrawing.ModelSpace) </p>          <p>If VarType(vdata) = vbEmpty Then </p>          <p>'Create the data to be assigned            <br />' Define double array of strings to hold column name and values             <br />Dim sData(0 To 10, 0 To 1) As String             <br />sData(0, 0) = &quot;NOTE&quot;: sData(0, 1) = &quot;MyNote&quot;             <br />sData(1, 0) = &quot;STANDARD2&quot;: sData(1, 1) = &quot;text for standard2&quot;             <br />sData(2, 0) = &quot;DIM&quot;: sData(2, 1) = &quot;10&quot;             <br />sData(3, 0) = &quot;DESCR2&quot;: sData(3, 1) = &quot;10&quot;             <br />sData(4, 0) = &quot;PRICE&quot;: sData(4, 1) = &quot;100&quot;             <br />sData(5, 0) = &quot;MASS&quot;: sData(5, 1) = &quot;101&quot;             <br />sData(6, 0) = &quot;MATERIAL&quot;: sData(6, 1) = &quot;IS:2062&quot;             <br />sData(7, 0) = &quot;VENDOR&quot;: sData(7, 1) = &quot;XYZ&quot;             <br />sData(8, 0) = &quot;DESCR&quot;: sData(8, 1) = &quot;text for description&quot;             <br />sData(9, 0) = &quot;MATERIAL2&quot;: sData(9, 1) = &quot;GOLD&quot;             <br />sData(10, 0) = &quot;STANDARD&quot;: sData(10, 1) = &quot;text for standard&quot;             <br />' Assign the data to current database modelspace             <br />Call oBoMMgr.SetPartData(ThisDrawing.ModelSpace, sData)             <br />Else             <br />' print the existing data             <br />Dim j As Integer             <br />For j = LBound(vdata) To UBound(vdata)             <br />Debug.Print vbTab + vdata(j, LBound(vdata, 2)) + vbTab _             <br />+ vbTab + vbTab + vdata(j, UBound(vdata, 2)) + vbCrLf </p>          <p>Next </p>          <p>End If            <br />End Sub </p>       </td>     </tr>      <tr>       <td valign="top" width="460">         <p>Sub modAssemblyAttributes() </p>          <p>' Set reference to symbol Manager            <br />Dim oSymBBMgr As McadSymbolBBMgr             <br />Set oSymBBMgr = Application.GetInterfaceObject(&quot;SymBBAuto.McadSymbolBBMgr&quot;) </p>          <p>' Set reference to BOM Manager            <br />Dim oBoMMgr As McadBOMMgr             <br />Set oBoMMgr = oSymBBMgr.BOMMgr </p>          <p>' Get the assembly attributes from current database modelspace            <br />Dim vdata As Variant             <br />vdata = oBoMMgr.GetPartData(ThisDrawing.ModelSpace)             <br />If VarType(vdata) &lt;&gt; vbEmpty Then             <br />' Modify material             <br />Dim j As Integer             <br />For j = LBound(vdata) To UBound(vdata)             <br />If vdata(j, LBound(vdata, 2)) = &quot;MATERIAL&quot; Then             <br />vdata(j, UBound(vdata, 2)) = &quot;SILVER&quot;             <br />Exit For             <br />End If             <br />Next             <br />' apply modified material             <br />Call oBoMMgr.SetPartData(ThisDrawing.ModelSpace, vdata)             <br />End If </p>          <p>End Sub</p>       </td>     </tr>   </tbody></table>
