---
layout: "post"
title: "make the client graphics always visible even if they are blocked by other objects"
date: "2012-07-14 23:39:57"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/07/make-the-client-graphics-always-visible-even-if-they-are-blocked-by-other-objects.html "
typepad_basename: "make-the-client-graphics-always-visible-even-if-they-are-blocked-by-other-objects"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><strong>Issue</strong>     <br />I would like to create a similar preview as the Inventor does (for example when extruding text with a green arrow). With my function, I can create this arrow but when the direction is negative or symmetric, the part of the arrow toward the material is not visible (obstructed by the material). Do I have to set temporarely the material as transparent or is there a different way to do it? </p>  <p><strong>Solution      <br /></strong>You just need to set BurnThrough property of the GraphicsPrimitive ( e.g TriangleStripGraphics) to True, thus the graphics are always visible even if they are blocked by other objects. <b>&#160;</b></p>  <p>The code below assumes a part with a body is opened. It copies the body to a new body. It adds each face of the new body to a surface graphics , highlights it. Since the surface graphicsâ€™ BurnThrough is True, it is visible even there is any other faces locate ahead of it. </p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <div style="font-family: courier new; background: white; color: black; font-size: 8pt">     <p style="margin: 0px"><span style="line-height: 140%; color: blue">Public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> Test()</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> partDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PartDocument</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; partDoc = m_inventorApp.ActiveDocument </span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> cg </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ClientGraphics</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Try</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cg = partDoc.ComponentDefinition.ClientGraphicsCollection.Item(</span><span style="line-height: 140%; color: #a31515">&quot;test&quot;</span><span style="line-height: 140%">)</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cg.Delete()</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Catch</span><span style="line-height: 140%"> ex </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Exception</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Try</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; cg = partDoc.ComponentDefinition.ClientGraphicsCollection.Add(</span><span style="line-height: 140%; color: #a31515">&quot;test&quot;</span><span style="line-height: 140%">)</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> body </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SurfaceBody</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; body = partDoc.ComponentDefinition.SurfaceBodies.Item(1)</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> newBody </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SurfaceBody</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; newBody = body.AlternateBody(</span><span style="line-height: 140%; color: #2b91af">SurfaceGeometryFormEnum</span><span style="line-height: 140%">.SurfaceGeometryForm_NURBS)</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> hs </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">HighlightSet</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; hs = partDoc.CreateHighlightSet</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> node </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">GraphicsNode</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; node = cg.AddNode(1)</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> trans </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Matrix</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; trans = node.Transformation</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; trans.Cell(1, 4) = trans.Cell(1, 4) + (body.RangeBox.MaxPoint.X - body.RangeBox.MinPoint.X) + 2</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; node.Transformation = trans</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> f </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Face</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> surfGraphics </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SurfaceGraphics</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> f </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> newBody.Faces</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> newFace </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Face</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; newFace = body.BindTransientKeyToObject(f.TransientKey)</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfGraphics = node.AddSurfaceGraphics(f)</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfGraphics.Color = m_inventorApp.TransientObjects.CreateColor(255, 0, 0)</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfGraphics.BurnThrough = </span><span style="line-height: 140%; color: blue">True</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> hs.AddItem(newFace)</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;Continue?&quot;</span><span style="line-height: 140%">, vbYesNo, </span><span style="line-height: 140%; color: #a31515">&quot;Alternate Body Mapping Test&quot;</span><span style="line-height: 140%">) = vbNo </span><span style="line-height: 140%; color: blue">Then</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; hs.Clear()</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cg.Delete()</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Exit Sub</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; hs.Clear()</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfGraphics.Color = m_inventorApp.TransientObjects.CreateColor(100, 100, 100)</span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; surfGraphics.BurnThrough = </span><span style="line-height: 140%; color: blue">False</span><span style="line-height: 140%"> </span></p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>      <p style="margin: 0px">&#160;</p>      <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; cg.Delete()</span></p>      <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>   </div>    <p style="margin: 0px"><span style="line-height: 140%; color: blue"></span></p> </div>
