---
layout: "post"
title: "create drawing dimension that does not attach to any geometry"
date: "2012-06-10 08:29:58"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/create-drawing-dimension-that-does-not-attach-to-any-geometry.html "
typepad_basename: "create-drawing-dimension-that-does-not-attach-to-any-geometry"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>Let's say I have two points in my sheet (10, 20) and (20, 20), and I want to create a DrawingDimension between those points. There is no geometry intent I can provide, so using any of the &quot;GeneralDimensions.Add&quot; method is not possible.</p>  <p>Still, one way to do it can be to create this dimension to a DrawingSketch, regarding converting the point positions from the sheet space to the sketch space, then use the &quot;GeneralDimensions.Retrieve&quot; method to make the Sketch dimension visible into the Sheet.</p>  <p>Here is a sample that illustrates this workflow in C#:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="color: blue">void</span> addDimWithoutGeo()</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// assume we have had Inventor application</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">DrawingDocument</span> oDrawingDoc = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">DrawingDocument</span>)mApplication.ActiveDocument;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">TransientGeometry</span> oTG = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; mApplication.TransientGeometry;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Create new Drawing Sketch</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">DrawingSketch</span> oSketch = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawingDoc.ActiveSheet.DrawingViews[1].</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Sketches.Add();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Create 2 points in the sheet space</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point2d</span> oSheetPoint1 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(10, 20);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point2d</span> oSheetPoint2 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(20, 20);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Convert points in sketch space</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point2d</span> oInSketchPoint1 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SheetToSketchSpace(oSheetPoint1);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point2d</span> oInSketchPoint2 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SheetToSketchSpace(oSheetPoint2);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Edit sketch</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oSketch.Edit();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Create 2 sketch points</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">SketchPoint</span> oSketchPoint1 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchPoints.Add(oInSketchPoint1, <span style="color: blue">false</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">SketchPoint</span> oSketchPoint2 = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchPoints.Add(oInSketchPoint2, <span style="color: blue">false</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Set position for the text</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point2d</span> oTextPosition = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(0, 0);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Create dimension in sketch</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oSketch.DimensionConstraints.AddTwoPointDistance(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketchPoint1, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketchPoint2,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Inventor.<span style="color: #2b91af">DimensionOrientationEnum</span>.kAlignedDim, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTextPosition, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">false</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Close sketch </span></p>    <p style="margin: 0px">&#160;&#160;&#160; oSketch.ExitEdit();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//Retrieve dimensions of the sketch in the sheet</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">object</span> dummy = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160; oDrawingDoc.ActiveSheet.DrawingDimensions.</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; GeneralDimensions.Retrieve(oSketch, dummy);</p>    <p style="margin: 0px">}</p> </div>
