---
layout: "post"
title: "save client graphics information along with the document and retrieve it back"
date: "2012-06-14 02:17:58"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/save-clientgraphics-information-along-with-the-document-and-retrieve-it-back.html "
typepad_basename: "save-clientgraphics-information-along-with-the-document-and-retrieve-it-back"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>
<p><strong>Issue</strong></p>
<p>Is it possible to save client graphics created in a part document with the Inventor API? Is there an API for redrawing the client graphics using the saved graphics data?</p>
<p><a name="section2"></a></p>
<p><strong>Solution</strong></p>
<p>Using the GraphicsDataSetsCollection.Add2 method will allow ClientGraphics to be saved with the file.&#0160;</p>
<p>If ClientGraphics are added to a ClientFeature along with a data set then the ClientFeature will take care of the redraw. Currently using a ClientFeature is the only way to persist the complete set of ClientGraphics. For more information, please take a look at &quot;Visual Cues - ClientGraphics and InteractionGraphics&quot; in the Overviews section of the Inventor API Help file for better understanding on GraphicsDataSet and how to use them.</p>
<p>To test the code below select a ClientFeature and run the macro. ClientGraphics will be added to the ClientFeature. The attached part file has a ClientFeature named Pocket1 that you can use to test. (Select ClientFeature &quot;Pocket1&quot;).</p>
<p>&#0160; <span class="asset  asset-generic at-xid-6a0167607c2431970b01b7c74dba49970b img-responsive"><a href="http://adndevblog.typepad.com/files/testpart-inventor2015.ipt">Download Testpart-Inventor2015</a></span></p>
<p><strong>C# code</strong>&#0160;</p>
<div style="font-family: courier new; background: white; color: black; font-size: 8pt;">
<p style="margin: 0px;"><span style="line-height: 140%; color: blue;">public</span><span style="line-height: 140%; color: blue;">static</span><span style="line-height: 140%; color: blue;">void</span><span style="line-height: 140%;"> testCS()</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">{&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">// assume we have had Inventor Application</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">// _InventorApp</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">try</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; {&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">ClientFeature</span><span style="line-height: 140%;"> invCF =</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _InventorApp.ActiveDocument.SelectSet[1] </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">as</span><span style="line-height: 140%; color: #2b91af;">ClientFeature</span><span style="line-height: 140%;">;</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">ClientFeatureDefinition</span><span style="line-height: 140%;"> invCFD = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; invCF.Definition;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">if</span><span style="line-height: 140%;"> (invCFD.ClientGraphicsCollection.Count &gt; 0)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">// Delete everything.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">for</span><span style="line-height: 140%;"> (</span><span style="line-height: 140%; color: blue;">int</span><span style="line-height: 140%;"> i = 0; </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; i &lt; invCFD.ClientGraphicsCollection.Count;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; i++)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; invCFD.ClientGraphicsCollection[i].Delete();</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _InventorApp.ActiveView.Update();</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">else</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">// Get an arbitrary point on an edge of the <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; // feature, </span><span style="line-height: 140%; color: green;">if the client feature has any <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; //elements.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Inventor.</span><span style="line-height: 140%; color: #2b91af;">Point</span><span style="line-height: 140%;"> oOrigin = </span><span style="line-height: 140%; color: blue;">null</span><span style="line-height: 140%;">;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">if</span><span style="line-height: 140%;"> (invCFD.ClientFeatureElements.Count &gt; 0)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">PartFeature</span><span style="line-height: 140%;"> element = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; invCFD.ClientFeatureElements[1].Element</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">as</span><span style="line-height: 140%; color: #2b91af;">PartFeature</span><span style="line-height: 140%;">;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oOrigin = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; element.Faces[1].Edges[1].PointOnEdge;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">else</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oOrigin = </span><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _InventorApp.TransientGeometry.CreatePoint(0, 0, 0);</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">GraphicsDataSets</span><span style="line-height: 140%;"> oGraphicsData = </span><span style="line-height: 140%; color: blue;">null</span><span style="line-height: 140%;">;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">try</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oGraphicsData = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _InventorApp.ActiveDocument.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GraphicsDataSetsCollection[</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #a31515;">&quot;Client Feature Test&quot;</span><span style="line-height: 140%;">];</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">catch</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oGraphicsData = </span><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _InventorApp.ActiveDocument.GraphicsDataSetsCollection.Add2(</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #a31515;">&quot;Client Feature Test&quot;</span><span style="line-height: 140%;">, </span><span style="line-height: 140%; color: blue;">true</span><span style="line-height: 140%;">);</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">GraphicsCoordinateSet</span><span style="line-height: 140%;"> oCoordSet = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oGraphicsData.CreateCoordinateSet(2);</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">double</span><span style="line-height: 140%;">[] adPoints = </span><span style="line-height: 140%; color: blue;">new</span><span style="line-height: 140%; color: blue;">double</span><span style="line-height: 140%;">[9];</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[0] = oOrigin.X;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[1] = oOrigin.Y;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[2] = oOrigin.Z;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[3] = oOrigin.X + 1;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[4] = oOrigin.Y;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[5] = oOrigin.Z;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[6] = oOrigin.X + 1;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[7] = oOrigin.Y + 0.5;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints[8] = oOrigin.Z;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oCoordSet.PutCoordinates(</span><span style="line-height: 140%; color: blue;">ref</span><span style="line-height: 140%;"> adPoints);</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">GraphicsNormalSet</span><span style="line-height: 140%;"> oNormalSet = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oGraphicsData.CreateNormalSet(2);</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oNormalSet.Add(1,</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160; _InventorApp.TransientGeometry.CreateUnitVector(0, 0, 1));</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">GraphicsColorSet</span><span style="line-height: 140%;"> oColorSet = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oGraphicsData.CreateColorSet(2);</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oColorSet.Add(1, 255, 255, 0);</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">// Create some client graphics.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">ClientGraphics</span><span style="line-height: 140%;"> oClientGraphics = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; invCFD.ClientGraphicsCollection.Add(</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #a31515;">&quot;Client Feature Test&quot;</span><span style="line-height: 140%;">);</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">GraphicsNode</span><span style="line-height: 140%;"> oNode = </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oClientGraphics.AddNode(2);</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green;">//Create a triangle.</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af;">TriangleGraphics</span><span style="line-height: 140%;"> oTriangle =</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oNode.AddTriangleGraphics();</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.CoordinateSet = oCoordSet;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.NormalSet = oNormalSet;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.ColorSet = oColorSet;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.DepthPriority = 1;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oNode.Selectable = </span><span style="line-height: 140%; color: blue;">true</span><span style="line-height: 140%;">;</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; _InventorApp.ActiveView.Update();</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue;">catch</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; {</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160;&#0160;&#0160; }</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">}</span></p>
</div>
<p><strong>VBA code</strong></p>
<p>Sub testVBA() <br />&#0160;&#0160;&#0160; &#39;get the client feature <br />&#0160;&#0160;&#0160; Dim invCF As ClientFeature <br />&#0160;&#0160;&#0160; Set invCF = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveDocument.SelectSet(1) <br />&#0160;&#0160;&#0160; &#39; get defintion of the client feature <br />&#0160;&#0160;&#0160; Dim invCFD As ClientFeatureDefinition <br />&#0160;&#0160;&#0160; Set invCFD = invCF.Definition <br />&#0160;&#0160;&#0160; If invCFD.ClientGraphicsCollection.Count &gt; 0 Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Delete everything. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim i As Integer <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; For i = 1 To invCFD.ClientGraphicsCollection.Count <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; invCFD.ClientGraphicsCollection.Item(1).Delete <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveView.Update <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Next <br />&#0160;&#0160;&#0160; Else <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Get an arbitrary point on an edge of the feature, <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; if the client feature has any elements. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oOrigin As Point <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If invCFD.ClientFeatureElements.Count &gt; 0 Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oOrigin = invCFD.ClientFeatureElements.Item(1). _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Element.Faces.Item(1).Edges.Item(1).PointOnEdge <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Else <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; There isn&#39;t any geometry so just place <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; the graphics at the model origin. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oOrigin = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.TransientGeometry.CreatePoint <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oGraphicsData As GraphicsDataSets <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; On Error Resume Next <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oGraphicsData = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveDocument. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GraphicsDataSetsCollection.Item(&quot;Client Feature Test&quot;) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If Err Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; then the data will be stored with document saving <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oGraphicsData = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveDocument. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GraphicsDataSetsCollection.Add2( _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &quot;Client Feature Test&quot;, True) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oCoordSet As GraphicsCoordinateSet <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oCoordSet = oGraphicsData.CreateCoordinateSet(2) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim adPoints(8) As Double <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(0) = oOrigin.X <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(1) = oOrigin.Y <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(2) = oOrigin.Z <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(3) = oOrigin.X + 1 <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(4) = oOrigin.Y <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(5) = oOrigin.Z <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(6) = oOrigin.X + 1 <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(7) = oOrigin.Y + 0.5 <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; adPoints(8) = oOrigin.Z <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call oCoordSet.PutCoordinates(adPoints) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oNormalSet As GraphicsNormalSet <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oNormalSet = oGraphicsData.CreateNormalSet(2) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call oNormalSet.Add(1, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.TransientGeometry.CreateUnitVector( _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; 0, 0, 1)) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oColorSet As GraphicsColorSet <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oColorSet = oGraphicsData.CreateColorSet(2) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call oColorSet.Add(1, 255, 255, 0) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Create some client graphics. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oClientGraphics As ClientGraphics <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oClientGraphics = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; invCFD.ClientGraphicsCollection.Add(&quot;Client Feature Test&quot;) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oNode As GraphicsNode <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oNode = oClientGraphics.AddNode(2) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Create a triangle. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oTriangle As TriangleGraphics <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oTriangle = oNode.AddTriangleGraphics <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.CoordinateSet = oCoordSet <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.NormalSet = oNormalSet <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.ColorSet = oColorSet <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTriangle.DepthPriority = 1 <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oNode.Selectable = True <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveView.Update <br />&#0160;&#0160;&#0160; End If <br />End Sub</p>
