---
layout: "post"
title: "Copying a SketchSpline from one sketch to another"
date: "2012-06-05 06:57:16"
author: "Philippe Leefsma"
categories:
  - "Inventor"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/copying-a-sketchspline-from-one-sketch-to-another.html "
typepad_basename: "copying-a-sketchspline-from-one-sketch-to-another"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p>  <p><b>Q:</b></p>  <p>How to copy a SketchSpline from one Sketch to another one?</p>  <p><a name="section2"></a></p>  <p><b>A:</b></p>  <p>The following VB.Net code snippet illustrates how to do that. Note that for clarity error checking has been omitted.</p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><font face="Consolas"><span style="font-family: ; color: "><font color="#0000ff"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Sub</font></font></span><span style="font-family: "><font style="font-size: 8pt"><font color="#000000"> TestCopy(</font><span style="color: "><font color="#0000ff">ByVal</font></span><font color="#000000"> app </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> Inventor.</font><span style="color: "><font color="#2b91af">Application</font></span><font color="#000000">)</font></font></span></font></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> doc </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">PartDocument</font></span><font color="#000000"> = app.ActiveDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> compDef </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">PartComponentDefinition</font></span><font color="#000000"> = doc.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> sketchTo </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">PlanarSketch</font></span><font color="#000000"> = compDef.Sketches.Item(2)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> spline </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">SketchSpline</font></span><font color="#000000"> = </font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; compDef.Sketches.Item(1).SketchSplines.Item(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">CopySpline(app, sketchTo, spline)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Sub</font></span><font color="#000000"> CopySpline(</font><span style="color: "><font color="#0000ff">ByVal</font></span><font color="#000000"> app </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> Inventor.</font><span style="color: "><font color="#2b91af">Application</font></span><font color="#000000">,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">ByRef</font></span><font color="#000000"> sketchTo </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">PlanarSketch</font></span><font color="#000000">,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">ByRef</font></span><font color="#000000"> spline </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">SketchSpline</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> col </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">ObjectCollection</font></span><font color="#000000"> = app.TransientObjects.CreateObjectCollection</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> i </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Integer</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">For</font></span><font color="#000000"> i = 1 </font><span style="color: "><font color="#0000ff">To</font></span><font color="#000000"> spline.FitPointCount</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">col.Add(spline.FitPoint(i).Geometry)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#0000ff">Next</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">sketchTo.SketchSplines.Add(col, spline.FitMethod)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt" class="MsoNormal"><font face="Calibri"><font style="font-size: 11pt" color="#000000">&#160;</font></font></p>
