---
layout: "post"
title: "GetTruePath may not return the correct length"
date: "2012-05-21 00:08:59"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/gettruepath-may-not-return-the-correct-length.html "
typepad_basename: "gettruepath-may-not-return-the-correct-length"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>TrueSweepLength (GetTruePath) in the API help reference is a good sample to calculate the true length of a sweep feature. If the centroid of the sweep profile does not lie on the sweep path, the true length of the sweep feature is not the same as the sum of lengths of the path entities. </p>  <p>In some cases, this code may not work well.even though the centroid of the sweep profile is on the sweep path. e.g. in the screenshots below, the sketch arc is actually the bend from two lines.&#160; The curves from SweepFeatures.GetTruePath returns the original length of the lines, instead of the current length after the bend. So the total length is different to what is measured in the UI.</p>  <p>This is an issue we have logged. To work around it, we need to check the <strong>SweepFeature.Path</strong> and calculate the total length of the paths.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b0168eba602a3970c-pi"><img style="border-bottom: 0px; border-left: 0px; display: inline; border-top: 0px; border-right: 0px" title="image" border="0" alt="image" src="/assets/image_845f6e.jpg" width="485" height="194" /></a> </p>  <p>&#160;</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> TrueSweepLength_bySweepPath()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; _InvApplication = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%"> Runtime.InteropServices.Marshal. _</span></p>    <p style="margin: 0px"><span style="line-height: 140%"> GetActiveObject(</span><span style="line-height: 140%; color: #a31515">&quot;Inventor.Application&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' assumes you have had Inventor application&#160; </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Set a reference to the active part document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> PartDocument =&#160; _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _InvApplication.ActiveDocument</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDef </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> PartComponentDefinition = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160; oDoc.ComponentDefinition</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Check to make sure a sweep feature is selected.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Not</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">TypeOf</span><span style="line-height: 140%"> oDoc.SelectSet.Item(1) _ </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Is</span><span style="line-height: 140%"> SweepFeature </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;A sweep feature must be selected.&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Exit</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Set a reference to the selected feature.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oSweep </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> SweepFeature = _&#160; </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.SelectSet.Item(1)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oPaths </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.Path = _ </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSweep.Path</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> TotalLength </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span><span style="line-height: 140%"> = 0 </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oPathEnt </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> PathEntity</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> oPathEnt </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> oPaths</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' get the evaluator of this path</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oCurveEval </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> CurveEvaluator = _&#160; </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPathEnt.Curve.Evaluator</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> MinParam </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> MaxParam </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> Length </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' get params extents</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oCurveEval.GetParamExtents(MinParam, _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MaxParam)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' get length of the path</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oCurveEval.GetLengthAtParam(MinParam, _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MaxParam, _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Length)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; TotalLength = TotalLength + Length</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Display total sweep length</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;Total sweep length = &quot;</span><span style="line-height: 140%"> &amp; _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _InvApplication.UnitsOfMeasure.GetStringFromValue( _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TotalLength, _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; UnitsTypeEnum.kMillimeterLengthUnits))</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>
