---
layout: "post"
title: "How to use the AddBaseView method with the Camera parameter ?"
date: "2012-05-30 02:40:31"
author: "Philippe Leefsma"
categories:
  - "Inventor"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/how-to-use-the-addbaseview-method-with-the-camera-parameter.html "
typepad_basename: "how-to-use-the-addbaseview-method-with-the-camera-parameter"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p>  <p><b>Q:</b></p>  <p>I want to create a base drawing view with my own camera parameter. How to get the camera object and set its parameters to use with the &quot;AddBaseView&quot; method?</p>  <p><a name="section2"></a></p>  <p><b>A:</b></p>  <p>The following VB.Net code sample illustrates the use of the Camera parameter with the &quot;AddBaseView&quot; method.</p>  <p>Note: The related Part or Assembly document has to be opened in Visible mode in order to retrieve the &quot;Application.ActiveView.Camera&quot; object.</p>  <p>The &quot;ViewOrientation&quot; parameter has to be &quot;kArbitraryViewOrientation&quot; in order to use a custom camera object.</p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><font face="Consolas"><span style="font-family: ; color: "><font color="#0000ff"><font style="font-size: 8pt">&#160;&#160;&#160; Sub</font></font></span><span style="font-family: "><font style="font-size: 8pt"><font color="#000000"> CreateBaseViewWithCamera(</font><span style="color: "><font color="#0000ff">ByVal</font></span><font color="#000000"> app </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> Inventor.</font><span style="color: "><font color="#2b91af">Application</font></span><font color="#000000">)</font></font></span></font></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Open the part to insert in the drawing (Visible mode is required). </font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oPartDoc </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">PartDocument</font></span><font color="#000000"> =</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">app.Documents.Open(</font></font><font style="font-size: 8pt"><span style="color: "><font color="#a31515">&quot;C:\Temp\Part1.ipt&quot;</font></span><font color="#000000">, </font><span style="color: "><font color="#0000ff">True</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Get Camera object </font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oCamera </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">Camera</font></span><font color="#000000"> = app.ActiveView.Camera</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Set your Camera parameters </font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oCamera.Eye = app.TransientGeometry.CreatePoint(0, 10, 10)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oCamera.Target = app.TransientGeometry.CreatePoint(0, 0, 0)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oCamera.UpVector = app.TransientGeometry.CreateUnitVector(0, 1, 0)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Open the Drawing doc </font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oDrawingDoc </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">DrawingDocument</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oDrawingDoc = app.Documents.Open(</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#a31515">&quot;C:\Temp\Drawing1.idw&quot;</font></span><font color="#000000">, </font><span style="color: "><font color="#0000ff">True</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oSheet </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">Sheet</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oSheet = oDrawingDoc.Sheets.Item(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Position base view in middle of the sheet </font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oViewPos </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">Point2d</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oViewPos = app.TransientGeometry.CreatePoint2d(</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSheet.Width / 2, oSheet.Height / 2)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Create view with parameters </font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> oBaseView </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">DrawingView</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oBaseView = oSheet.DrawingViews.AddBaseView(</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oPartDoc,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oViewPos,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">1,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">ViewOrientationTypeEnum</font></span><font color="#000000">.kArbitraryViewOrientation,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">DrawingViewStyleEnum</font></span><font color="#000000">.kHiddenLineDrawingViewStyle,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#a31515">&quot;BaseView1&quot;</font></span><font color="#000000">,</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oCamera)</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="color: "><font style="font-size: 8pt" color="#008000">'Close the part doc </font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oPartDoc.Close()</font></font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; text-autospace: ; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: "><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt" class="MsoNormal"><font face="Calibri"><font style="font-size: 11pt" color="#000000">&#160;</font></font></p>
