---
layout: "post"
title: "Error occurs using SketchLines for a profile when trying to create an extrusion"
date: "2012-06-11 23:06:00"
author: "Gary Wassell"
categories:
  - "Gary Wassell"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/error-occurs-using-sketchlines-for-a-profile-when-trying-to-create-an-extrusion.html "
typepad_basename: "error-occurs-using-sketchlines-for-a-profile-when-trying-to-create-an-extrusion"
typepad_status: "Publish"
---

<p><strong>Issue</strong></p>
<p>I create a sketch to create an extrusion. An error is occurring when using the sketch to create a profile. The error occurs on this line. Why am I getting the error?</p>
<p>Set oProfile1 = tySketch.Profiles.AddForSolid&quot;</p>
<p>Here is the VBA code I am using:</p>
<p>&#0160;</p>
<p>Sub Test() <br />&#0160;&#0160;&#0160; Dim App As Inventor.Application <br />&#0160;&#0160;&#0160; Set App = ThisApplication <br />&#0160;&#0160;&#0160; &#39; this code will only work on an active part <br />&#0160;&#0160;&#0160; Dim Part1 As PartDocument <br />&#0160;&#0160;&#0160; Set Part1 = ThisApplication.ActiveDocument <br />&#0160;&#0160;&#0160; Dim TG As TransientGeometry <br />&#0160;&#0160;&#0160; Set TG = App.TransientGeometry <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39;try to read face with transient id 1 <br />&#0160;&#0160;&#0160; Dim oFace As Face <br />&#0160;&#0160;&#0160; Set oFace = Part1.ComponentDefinition.SurfaceBodies(1).BindTransientKeyToObject(1) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim tySketch As PlanarSketch <br />&#0160;&#0160;&#0160; Dim oWorkPlane As WorkPlane <br />&#0160;&#0160;&#0160; Set oWorkPlane = Part1.ComponentDefinition.WorkPlanes.AddFixed(TG.CreatePoint <br />&#0160;&#0160;&#0160; (oFace.Evaluator.RangeBox.MinPoint.X, 0, 0), TG.CreateUnitVector(0, 1, 0), TG.CreateUnitVector(0, 0, 1), <br />&#0160;&#0160;&#0160; False) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Set oPartCompDef = Part1.ComponentDefinition <br />&#0160;&#0160;&#0160; Set tySketch = oPartCompDef.Sketches.Add(oWorkPlane) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39; create some temporary variables for drawing lines <br />&#0160;&#0160;&#0160; Dim tyStartPoint As Point2d <br />&#0160;&#0160;&#0160; Dim tyEndPoint As Point2d <br />&#0160;&#0160;&#0160; Dim tyTmpPoint As Point2d <br />&#0160;&#0160;&#0160; Dim tyLine As SketchLine <br />&#0160;&#0160;&#0160; Set tyStartPoint = TG.CreatePoint2d(0, 0) <br />&#0160;&#0160;&#0160; Set tyEndPoint = TG.CreatePoint2d(0, 0) <br />&#0160;&#0160;&#0160; Set tyTmpPoint = TG.CreatePoint2d(0, 0) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39;draw some lines to create a shap fo the extrusion <br />&#0160;&#0160;&#0160; Set tyStartPoint = tySketch.ModelToSketchSpace(oFace.Evaluator.RangeBox.MinPoint) <br />&#0160;&#0160;&#0160; Set tyEndPoint = tySketch.ModelToSketchSpace(oFace.Evaluator.RangeBox.MaxPoint) <br />&#0160;&#0160;&#0160; tyTmpPoint.X = tyStartPoint.X <br />&#0160;&#0160;&#0160; tyTmpPoint.Y = tyEndPoint.Y <br />&#0160;&#0160;&#0160; Set tyLine = tySketch.SketchLines.AddByTwoPoints(tyStartPoint, tyTmpPoint) <br />&#0160;&#0160;&#0160; Set tyLine = tySketch.SketchLines.AddByTwoPoints(tyTmpPoint, tyEndPoint) <br />&#0160;&#0160;&#0160; Set tyLine = tySketch.SketchLines.AddByTwoPoints(tyEndPoint, tyStartPoint) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39; try to create a profile <br />&#0160;&#0160;&#0160; Dim oProfile1 As Profile <br />&#0160;&#0160;&#0160; Set oProfile1 = tySketch.Profiles.AddForSolid <br />&#0160;&#0160;&#0160; &#39; Do an extrusion on the solid <br />&#0160;&#0160;&#0160; oExtrusion = oPartCompDef.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, 3, kSymmetricExtentDirection, kJoinOperation, Null)</p>
<p>End Sub</p>
<p>&#0160;</p>
<p><strong>Solution</strong></p>
<p>The error occurs because there are no constraints between the SketchLines. You can use SketchPoint.Merge to add the constraints.&#0160; You can also use a SketchPoint directly as an argument when the Sketch geometry is being created.</p>
<p>&#0160;</p>
<div style="background: white;">
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oFirstline = tySketch.SketchLines.AddByTwoPoints(¡¬¡¬)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oSecondLine = tySketch.SketchLines.AddByTwoPoints(¡¬¡¬)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oLastline = tySketch.SketchLines.AddByTwoPoints(¡¬¡¬)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oFirstline.EndSketchPoint.Merge(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="font-size: 10pt;"><span style="color: #000000;">oSecondLine.StartSketchPoint)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oSecondLine.EndSketchPoint.Merge(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oLastline.StartSketchPoint)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oFirstline.StartSketchPoint.Merge(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oLastline.EndSketchPoint)</span></span></span></p>
</div>
<p>&#0160;</p>
<p>Here is a VB.NET example that creates a sketch, uses SketchPoint.Merge and then creates an extrusion. Before running this code create a part with rectangular faces like a box. This example is from a button on a form in a standalone exe that connects to Inventor from out of process.</p>
<p>&#0160;</p>
<div style="background: white;">
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Imports</span></span><span style="color: #000000;"> Inventor</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Public</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Class</span></span><span style="color: #000000;"> </span></span><span><span style="color: #2b91af; font-size: 10pt;">Form1</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> m_inventorApp </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Inventor.Application = </span></span><span><span style="color: #0000ff; font-size: 10pt;">Nothing</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Private</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Sub</span></span><span style="color: #000000;"> Button1_Click(</span><span><span style="color: #0000ff;">ByVal</span></span><span style="color: #000000;"> sender </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> System.</span><span><span style="color: #2b91af;">Object</span></span><span style="color: #000000;">,</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff;">ByVal</span></span><span style="color: #000000;"> e </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> System.</span><span><span style="color: #2b91af;">EventArgs</span></span><span style="color: #000000;">) </span><span><span style="color: #0000ff;">Handles</span></span><span style="color: #000000;"> Button1.Click</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Try</span></span><span style="color: #000000;"> </span></span><span><span style="color: #008000; font-size: 10pt;">&#39; Try to get an active instance of Inventor</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp = System.Runtime.InteropServices.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span><span style="color: #2b91af;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Marshal</span></span><span style="color: #000000;">.GetActiveObject(</span><span><span style="color: #a31515;">&quot;Inventor.Application&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Catch</span></span><span style="color: #000000;"> </span></span><span><span style="color: #008000; font-size: 10pt;">&#39; If not active, create a new Inventor session</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> inventorAppType </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> </span><span><span style="color: #2b91af;">Type</span></span><span style="color: #000000;"> = System.</span><span><span style="color: #2b91af;">Type</span></span><span style="color: #000000;">.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GetTypeFromProgID(</span><span><span style="color: #a31515;">&quot;Inventor.Application&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp = System.</span></span><span style="font-size: 10pt;"><span><span style="color: #2b91af;">Activator</span></span><span style="color: #000000;">.CreateInstance(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; inventorAppType)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39;Must be set visible explicitly</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp.Visible = </span></span><span><span style="color: #0000ff; font-size: 10pt;">True</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Catch</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; System.Windows.Forms.MessageBox.Show(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;Error: couldn&#39;t create Inventor instance&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Test()</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Sub</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Sub</span></span><span style="color: #000000;"> Test()</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39; this code will only work on an active part </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> Part1 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> PartDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Part1 = m_inventorApp.ActiveDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> TG </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> TransientGeometry</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; TG = m_inventorApp.TransientGeometry</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39;try to read face with transient id 1 </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oFace </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Face</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oFace = Part1.ComponentDefinition.</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; SurfaceBodies(1).BindTransientKeyToObject(1)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> tySketch </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> PlanarSketch</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oWorkPlane </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> WorkPlane</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oWorkPlane = Part1.ComponentDefinition.WorkPlanes.</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; AddFixed(TG.CreatePoint _</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (oFace.Evaluator.RangeBox.MinPoint.X, 0, 0),</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; TG.CreateUnitVector(0, 1, 0), _</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; TG.CreateUnitVector(0, 0, 1), </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">False</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oPartCompDef </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> PartComponentDefinition</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oPartCompDef = Part1.ComponentDefinition</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tySketch = oPartCompDef.Sketches.Add(oWorkPlane)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39;draw some lines to create a shape for the extrusion </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> MinPoint </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Point2d = tySketch.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ModelToSketchSpace(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="font-size: 10pt;"><span style="color: #000000;">oFace.Evaluator.RangeBox.MinPoint)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> MaxPoint </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Point2d = tySketch.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ModelToSketchSpace(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oFace.Evaluator.RangeBox.MaxPoint)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> Pnt2 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Point2d = TG.CreatePoint2d(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MaxPoint.X, MinPoint.Y)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> tyLine1 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> SketchLine = tySketch.SketchLines.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; AddByTwoPoints(MinPoint, Pnt2)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> tyLine2 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> SketchLine = tySketch.SketchLines.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; AddByTwoPoints(Pnt2, MaxPoint)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine1.EndSketchPoint.Merge(</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine2.StartSketchPoint)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> Pnt3 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Point2d = TG.CreatePoint2d(M</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; inPoint.X, MaxPoint.Y)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> tyLine3 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> SketchLine = tySketch.SketchLines.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; AddByTwoPoints(MaxPoint, Pnt3)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine2.EndSketchPoint.Merge(</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine3.StartSketchPoint)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> tyLine4 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> SketchLine = tySketch.SketchLines.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; AddByTwoPoints(Pnt3, MinPoint)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine3.EndSketchPoint.Merge(</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine4.StartSketchPoint)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine4.EndSketchPoint.Merge(</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tyLine1.StartSketchPoint)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39; try to create a profile </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oProfile1 </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Profile</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oProfile1 = tySketch.Profiles.AddForSolid</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39; Do an extrusion on the solid</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oExtrusion </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> ExtrudeFeature</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oExtrusion = oPartCompDef.Features.ExtrudeFeatures.</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; AddByDistanceExtent(oProfile1, 3, _</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; PartFeatureExtentDirectionEnum.kSymmetricExtentDirection, _</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; PartFeatureOperationEnum.kJoinOperation, </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Nothing</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Catch</span></span><span style="color: #000000;"> ex </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> </span></span><span><span style="color: #2b91af; font-size: 10pt;">Exception</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox(ex.ToString())</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Sub</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Class</span></span></span></p>
</div>
