---
layout: "post"
title: "FaceProxy.GetClosestPointTo returns incorrect point"
date: "2012-05-25 14:53:12"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/faceproxygetclosestpointto-returns-incorrect-point.html "
typepad_basename: "faceproxygetclosestpointto-returns-incorrect-point"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p><b>Issue</b></p>  <p>I need to get the closest point on a plane of a component in assembly.&#160; I use FaceProxy.GetClosestPointTo(). The return value is always (0,0,0). Is there a solution for this?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>Note: This issue applies to Inventor 2009. </p>  <p>A workaround is to use MeasureTools.GetMinimumDistance. </p>  <p>Note: There is a difference between the documented behavior of GetClosestPointTo and GetMinimumDistance. When using GetClosestPointTo() the face is bounded and the closest point must be on the face. When using GetMinimumDistance() the face is boundless - it can be extent and the point may not be on the measured face. Here is a VB.NET example:</p>  <div style="font-family: consolas; background: white; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Sub</span> GetClosestPoint()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oFace <span style="color: blue">As</span> <span style="color: #2b91af">FaceProxy</span> = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _invApp.ActiveDocument.SelectSet(1)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oTG <span style="color: blue">As</span> <span style="color: #2b91af">TransientGeometry</span> = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _invApp.TransientGeometry</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oP <span style="color: blue">As</span> <span style="color: #2b91af">Point</span> = oTG.CreatePoint(0, 0, 0)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> vContext <span style="color: blue">As</span> <span style="color: blue">Object</span> = <span style="color: blue">Nothing</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> dDistance <span style="color: blue">As</span> <span style="color: blue">Double</span></p>    <p style="margin: 0px">&#160;&#160;&#160; dDistance = _invApp.MeasureTools. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; GetMinimumDistance(oFace, oP, , , vContext)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(<span style="color: #a31515">&quot;By Minimum Distance:&quot;</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">If</span> <span style="color: blue">Not</span> vContext.Item(<span style="color: #a31515">&quot;IntersectionFound&quot;</span>) <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(vContext.Item _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;ClosestPointOne&quot;</span>).X)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(vContext.Item _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;ClosestPointOne&quot;</span>).Y)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Debug</span>.Print(vContext.Item _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;ClosestPointOne&quot;</span>).Z)</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Sub</span></p> </div>
