---
layout: "post"
title: "Edge or Face by point coordinates"
date: "2012-12-12 23:41:41"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/12/edge-or-face-by-point-coordinates.html "
typepad_basename: "edge-or-face-by-point-coordinates"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a></p>  <p><b>Issue</b></p>  <p>How to find an Edge in the model given a point coordinate that lies on the Edge ?</p>  <p><b>Solution</b></p>  <p>This can be determined by using the 'LocateUsingPoint' method of the SurfaceBody object as shown in the following sample code: Point is defined by workpoint with hardcoded name.</p>  <p><b>C#</b></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><font face="Consolas"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font color="#0000ff"><font style="font-size: 10pt">private</font></font></span><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font style="font-size: 10pt"><font color="#000000"> </font><span><font color="#0000ff">void</font></span><font color="#000000"> button1_Click(</font><span><font color="#0000ff">object</font></span><font color="#000000"> sender, </font><span><font color="#2b91af">EventArgs</font></span><font color="#000000"> e)</font></font></span></font></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font style="font-size: 10pt" color="#000000">{</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">//get reference to active part document</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#2b91af">PartDocument</font></span><font color="#000000"> oDoc = (</font><span><font color="#2b91af">PartDocument</font></span><font color="#000000">)_InventorApp.ActiveDocument;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">//get some workpoint in model by its name</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#2b91af">WorkPoint</font></span><font color="#000000"> wp = oDoc.ComponentDefinition.WorkPoints[</font><span><font color="#a31515">&quot;wp4&quot;</font></span><font color="#000000">];</font></font><span style="mso-spacerun: yes"><font style="font-size: 10pt" color="#000000">&#160;&#160; </font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><span><font style="font-size: 10pt" color="#0000ff">try</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">{</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">//coordinate 3d-point </font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">Inventor.</font></font><font style="font-size: 10pt"><span><font color="#2b91af">Point</font></span><font color="#000000"> pt = wp.Point;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">// try to find edge</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#2b91af">Object</font></span><font color="#000000"> obj = oDoc.ComponentDefinition.SurfaceBodies[1]</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.LocateUsingPoint(</font></font><font style="font-size: 10pt"><span><font color="#2b91af">ObjectTypeEnum</font></span><font color="#000000">.kEdgeObject, pt, 0.1);</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">//// try to find face</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">//Object obj =<span style="mso-spacerun: yes">&#160; </span>oDoc.ComponentDefinition.SurfaceBodies[1] </font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">//<span style="mso-spacerun: yes">&#160;&#160;&#160; </span>.LocateUsingPoint(ObjectTypeEnum.kFaceObject, pt, 0.1);</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">// visualize found object using document select set</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">oDoc.SelectSet.Select(obj);</font><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">}</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><span><font style="font-size: 10pt" color="#0000ff">catch</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">{</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#2b91af">MessageBox</font></span><font color="#000000">.Show(</font><span><font color="#a31515">&quot;Nothing selected at the specified point!&quot;</font></span><font color="#000000">, </font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#a31515">&quot;Find Edge or Face&quot;</font></span><font color="#000000">);</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">}</font><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.5pt"><font face="Consolas"><font style="font-size: 10pt" color="#000000">}</font></font></span></p>  <p>&#160;</p>  <p><b>VB .NET</b></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><font face="Consolas"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font color="#0000ff"><font style="font-size: 10pt">Private</font></font></span><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font style="font-size: 10pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> Button1_Click(sender </font><span><font color="#0000ff">As</font></span><font color="#000000"> System.</font><span><font color="#2b91af">Object</font></span><font color="#000000">, _</font></font></span></font></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">e </font></font><font style="font-size: 10pt"><span><font color="#0000ff">As</font></span><font color="#000000"> System.</font><span><font color="#2b91af">EventArgs</font></span><font color="#000000">) _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#0000ff">Handles</font></span><font color="#000000"> Button1.Click</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">' get reference to active part document</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oDoc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">PartDocument</font></span><font color="#000000"> = </font><span><font color="#0000ff">TryCast</font></span><font color="#000000">(oApp.ActiveDocument, </font><span><font color="#2b91af">PartDocument</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">' get some workpoint in model by its name</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> wp </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">WorkPoint</font></span><font color="#000000"> = oDoc.ComponentDefinition.WorkPoints.Item(</font><span><font color="#a31515">&quot;wp1&quot;</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><span><font style="font-size: 10pt" color="#0000ff">Try</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">' coordinate 3d-point </font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> pt </font><span><font color="#0000ff">As</font></span><font color="#000000"> Inventor.</font><span><font color="#2b91af">Point</font></span><font color="#000000"> = wp.Point</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">' try to find edge</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> obj </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#0000ff">Object</font></span><font color="#000000"> = oDoc.ComponentDefinition.SurfaceBodies.Item(1) _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.LocateUsingPoint(</font></font><font style="font-size: 10pt"><span><font color="#2b91af">ObjectTypeEnum</font></span><font color="#000000">.kEdgeObject, pt, 0.1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">'' try to find face</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">'Dim obj As Object = oDoc.ComponentDefinition.SurfaceBodies.Item(1) _</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">'<span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160; </span>.LocateUsingPoint(ObjectTypeEnum.kFaceObject, pt, 0.1)</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><span><font style="font-size: 10pt" color="#008000">' visualize found object using document select set</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">oDoc.SelectSet.Select(obj)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#0000ff">Catch</font></span><font color="#000000"> ex </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 10pt" color="#2b91af">Exception</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#2b91af">MessageBox</font></span><font color="#000000">.Show(</font><span><font color="#a31515">&quot;Nothing selected at the specified point!&quot;</font></span><font color="#000000">,</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#a31515">&quot;Find Edge or Face&quot;</font></span><font color="#000000">)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font face="Consolas"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font></span><font style="font-size: 10pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 10pt" color="#0000ff">Try</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><font face="Consolas"><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font color="#0000ff"><font style="font-size: 10pt">End</font></font></span><span style="font-family: ; mso-bidi-font-size: 12.0pt"><font style="font-size: 10pt"><font color="#000000"> </font></font><span><font style="font-size: 10pt" color="#0000ff">Sub</font></span></span></font></p>  <p>&#160;</p>  <p><b>VBA</b></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">Sub Find_EdgeByPoint()</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oDoc As PartDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oDoc = ThisApplication.ActiveDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim wp As WorkPoint</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set wp = oDoc.ComponentDefinition.WorkPoints.Item(&quot;wp4&quot;)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim pt As Point</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set pt = wp.Point</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">On Error Resume Next</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim Obj As Object</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set Obj = oDoc.ComponentDefinition.SurfaceBodies.Item(1) _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.LocateUsingPoint(kEdgeObject, pt, 0.1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font style="font-size: 10pt" color="#00b050">'<span style="mso-spacerun: yes">&#160; </span>Set Obj = oDoc.ComponentDefinition.SurfaceBodies.Item(1) _</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font style="font-size: 10pt" color="#00b050">'<span style="mso-spacerun: yes">&#160;&#160;&#160; </span>.LocateUsingPoint(kFaceObject, pt, 0.1)</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">If Err.Number &lt;&gt; 0 Then</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">MsgBox &quot;Nothing selected at the specified point!&quot;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Else</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">oDoc.SelectSet.Select Obj</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">End If</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font face="Lucida Console"><font style="font-size: 10pt" color="#000000">End Sub</font></font></span></p>
