---
layout: "post"
title: "AddCoincident with Two Sketch Points"
date: "2012-05-15 23:22:21"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/addcoincident-with-two-sketch-points.html "
typepad_basename: "addcoincident-with-two-sketch-points"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The UI allows you use the coincident constraint between two points, but if you look at the results, there is no coincident constraint. Inventor deletes one sketch point and changed both lines to share a point. The API does not hide this from the user since the signature calls to return the coincident constraint (but we can't do that via API if no point were really created). So AddCoincident will fail if you try to constraint two sketch points of lines. If you want to merge the sketch points, use SketchPoint.Merge instead. </p>  <p>&#160;</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> mergeTwoPoints(</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// assume we have got Inventor application</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// get current document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PartDocument</span><span style="line-height: 140%"> oPartDoc = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp.ActiveDocument </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PartDocument</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PlanarSketch</span><span style="line-height: 140%"> oSketch = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPartDoc.ComponentDefinition.Sketches[1];</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">TransientGeometry</span><span style="line-height: 140%"> oTG = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp.TransientGeometry;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point2d</span><span style="line-height: 140%"> oLine1St =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(0,0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point2d</span><span style="line-height: 140%"> oLine1End = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(1,0);</span></p>    <p style="margin: 0px">&#160;&#160;&#160; </p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="line-height: 140%; color: green">// create line 1</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SketchLine</span><span style="line-height: 140%"> line1 = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchLines.AddByTwoPoints(oLine1St, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLine1End);&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point2d</span><span style="line-height: 140%"> oLine2St =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(2,2);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point2d</span><span style="line-height: 140%"> oLine2End = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(3,4);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160;&#160; // create line 2</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SketchLine</span><span style="line-height: 140%"> line2&#160; =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchLines.AddByTwoPoints(oLine2St,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLine2End);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// the line will fail</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//oSketch.GeometricConstraints.AddCoincident(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160;&#160; (SketchEntity)line1.StartSketchPoint, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160;&#160; (SketchEntity)line2.EndSketchPoint);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// use this line instead</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; line1.StartSketchPoint.Merge(line2.EndSketchPoint);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div>
