---
layout: "post"
title: "Access to the Bill Of Materials from a Different Level Of Details than Master"
date: "2012-08-14 13:22:00"
author: "Barbara Han"
categories:
  - "Barbara Han"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/access-to-the-bill-of-materials-from-a-different-level-of-details-than-master.html "
typepad_basename: "access-to-the-bill-of-materials-from-a-different-level-of-details-than-master"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>
<p>Though you have access to the BOM object through AssemblyComponentDefinition.BOM even in case of a document which is using a LOD (Level Of Detail) other than the Master, this only provides access to the &quot;Model Data&quot; view (&quot;Unnamed&quot;/kModelDataBOMViewType).</p>
<p>The &quot;Structured&quot; and &quot;Parts Only&quot; BOMView objects can only be accessed from a Master LOD document. So if the currently open assembly document is using a LOD other than the Master, then you can open its Master LOD version in the background and access those BOM views from there.</p>
<p>The below code sample shows how to do it:</p>
<p>VB.NET</p>
<div style="background: white;">
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #0000ff;"><span style="font-size: 8pt;">Public</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">Sub</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;"> BOMQuery()</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">Dim</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> m_inventorApp </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">As</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> Inventor.Application = </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">Nothing</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39; Try to get an active instance of Inventor</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160; m_inventorApp = System.Runtime.InteropServices.Marshal.GetActiveObject(</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #a31515;">&quot;Inventor.Application&quot;</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">Catch</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> ex </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">As</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;"> Exception</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">End</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39; If not active, create a new Inventor session</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">If</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> m_inventorApp </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">Is</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">Nothing</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">Dim</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> inventorAppType </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">As</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> Type = System.Type.GetTypeFromProgID(</span></span><span style="line-height: 11pt;"><span style="color: #a31515;">&quot;Inventor.Application&quot;</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: &#39;Courier New&#39;;"><span style="font-size: 8pt; color: #000000;">&#0160;&#0160;&#0160; m_inventorApp = System.Activator.CreateInstance(inventorAppType)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">End</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">Dim</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> oDoc </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">As</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;"> AssemblyDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">Dim</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> oBOM </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">As</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;"> BOM</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="font-size: 8pt; color: #000000;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39; Set a reference to the assembly document.</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39; This assumes an assembly document is active.</span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: &#39;Courier New&#39;;"><span style="font-size: 8pt; color: #000000;">&#0160; oDoc = m_inventorApp.ActiveDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="font-size: 8pt; color: #000000;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39;Gets back Master LOD</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">Dim</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> oAsmDocMasterLOD </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">As</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;"> AssemblyDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; oAsmDocMasterLOD = m_inventorApp.Documents.Open(oDoc.File.FullFileName, </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">False</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39;Obtains BOM from Master LOD only</span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: &#39;Courier New&#39;;"><span style="font-size: 8pt; color: #000000;">&#0160; oBOM = oAsmDocMasterLOD.ComponentDefinition.BOM</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39;From here you can operate on the BOM object...</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39;Following lines of code are examples only</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39; Set whether first level only or all levels</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; oBOM.StructuredViewFirstLevelOnly = </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">True</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="font-size: 8pt; color: #000000;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #008000;">&#39; Make sure that the structured view is enabled</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; oBOM.StructuredViewEnabled = </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">True</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160; MsgBox(</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #a31515;">&quot;BOM Views: &quot;</span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #000000;"> &amp; oBOM.BOMViews.count)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: &#39;Courier New&#39;;"><span style="line-height: 11pt;"><span style="color: #0000ff;"><span style="font-size: 8pt;">End</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span></span><span style="line-height: 11pt;"><span style="font-size: 8pt; color: #0000ff;">Sub</span></span></span></p>
</div>
<p>VBA</p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">Public Sub BOMQuery() </span></p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">Dim oDoc As AssemblyDocument     <br />Dim oBOM As BOM</span></p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">&#39; Set a reference to the assembly document.     <br />&#39; This assumes an assembly document is active.      <br />Set oDoc = ThisApplication.ActiveDocument</span></p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">&#39;Gets back Master LOD     <br />Dim oAsmDocMasterLOD As AssemblyDocument      <br />Set oAsmDocMasterLOD = ThisApplication.Documents.Open(oDoc.file.FullFileName, False)      <br />&#39;Obtains BOM from Master LOD only      <br />Set oBOM = oAsmDocMasterLOD.ComponentDefinition.BOM</span></p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">&#39;From here you can operate on the BOM object...     <br />&#39;Following lines of code are examples only</span></p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">&#39; Set whether first level only or all levels     <br />oBOM.StructuredViewFirstLevelOnly = True</span></p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">&#39; Make sure that the structured view is enabled     <br />oBOM.StructuredViewEnabled = True</span></p>
<p><span style="font-family: &#39;Courier New&#39;; font-size: xx-small;">MsgBox &quot;BOM Views: &quot; &amp; oBOM.BOMViews.count     <br />End Sub</span></p>
<p>// Edited by <a href="http://adndevblog.typepad.com/manufacturing/adam-nagy.html" target="_self">Adam Nagy</a></p>
