---
layout: "post"
title: "Revolve Feature that sweeps around a work axis"
date: "2012-11-01 00:07:07"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/11/revolve-feature-that-sweeps-around-a-work-axis.html "
typepad_basename: "revolve-feature-that-sweeps-around-a-work-axis"
typepad_status: "Publish"
---

<p><strong>Q</strong>: Is there a way to create a RevolveFeature that sweeps a specified angle around a work axis?</p>  <p><strong>A</strong>: Starting from Inventor 11 the parameter AxisEntity of the method AddByAngle allows applying a work axis as the axis of the revolution. AxisEntity is an input linear entity that defines the axis of the revolution. This can either be a sketch line in the same sketch that was used to generate the profile or a WorkAxis object.</p>  <p>The following VBA sample creates a revolve feature that sweeps the specified angle (2*Pi) around X base work axis. </p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font style="font-size: 10pt" color="#000000" face="Courier New">Sub AddRevolveByAngleAndAxis()</font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font style="font-size: 10pt" color="#000000" face="Courier New">&#160;</font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'Set a reference to the part document</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'This assumes a part document is active</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oPartDoc As PartDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oPartDoc = ThisApplication.ActiveDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oDef As PartComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oDef = oPartDoc.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oTG As TransientGeometry</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oTG = ThisApplication.TransientGeometry</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font style="font-size: 10pt" color="#000000" face="Courier New">&#160; </font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'create new planar sketch on the plane XY</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oPlane As WorkPlane</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oPlane = oDef.WorkPlanes.Item(3)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oSketch As PlanarSketch</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oSketch = oDef.Sketches.Add(oPlane)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font style="font-size: 10pt" color="#000000" face="Courier New">&#160;</font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'circle center</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oCenter As SketchPoint</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oCenter = oSketch.SketchPoints _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.Add(oTG.CreatePoint2d(2, 2), False)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'add sketch circle</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oCircles As SketchCircles</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oCircles = oSketch.SketchCircles</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oCircle As SketchCircle</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oCircle = oCircles.AddByCenterRadius(oCenter, 0.5)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font style="font-size: 10pt" color="#000000" face="Courier New">&#160; </font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'revolve axis</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oWorkAxis As Object</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oWorkAxis = oDef.WorkAxes.Item(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font style="font-size: 10pt" color="#000000" face="Courier New">&#160; </font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'define angle value = 2*Pi</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim Angle As Variant</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Angle = 8 * Math.Atn(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font style="font-size: 10pt" color="#000000" face="Courier New">&#160; </font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">'add revolve feature</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oProfile As Profile</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oProfile = oSketch.Profiles.AddForSolid</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oRevFeature As RevolveFeature</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oRevFeature = oDef.Features.RevolveFeatures _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.AddByAngle(oProfile, oWorkAxis, Angle, _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">PartFeatureExtentDirectionEnum.kNegativeExtentDirection, _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">PartFeatureOperationEnum.kJoinOperation)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><span style="mso-spacerun: yes"><font style="font-size: 10pt" color="#000000" face="Courier New">&#160;&#160;&#160;&#160;&#160; </font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">ThisApplication.ActiveView.Fit</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font color="#000000"><font face="Courier New"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Beep</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 11.0pt"><font style="font-size: 10pt" color="#000000" face="Courier New">End Sub</font></span></p>
