---
layout: "post"
title: "Include sketches from sub-assemblies in a DrawingView using a sketch proxy"
date: "2012-06-08 09:07:53"
author: "Gary Wassell"
categories:
  - "Gary Wassell"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/include-sketches-from-sub-assemblies-in-a-drawingview-using-a-sketch-proxy.html "
typepad_basename: "include-sketches-from-sub-assemblies-in-a-drawingview-using-a-sketch-proxy"
typepad_status: "Publish"
---

<p><strong>Issue</strong></p>
<p>In the User Interface I can right click on a sub assembly in the browser and select &quot;Get Model Sketches&quot; to include a sketch from the sub-assembly. I need to achieve the same thing programmatically. Is there a way to do this?</p>
<p><a name="section2"></a></p>
<p><strong>Solution</strong></p>
<p>To include / exclude entities for a Drawing View the &quot;SetVisibility&quot; method can be used. The ability to include a sketch from an assembly became available in the 2009 release. In prior versions only part sketches can be included using SetVisibility.</p>
<p>When dealing with a sketch contained in a sub-level assembly, you need to create a proxy for the sketch in the top-level assembly context, because the &quot;SetVisibility&quot; method can only handle objects that exist in the assembly that is represented in the view.</p>
<p>This VBA and VB.NET example iterates through the occurrences of the top-level assembly which is referenced by the view and for every assembly occurrence, it creates a SketchProxy object and includes it. The method can be extended to include sketches in deeper level sub-occurrences.</p>
<p>&#0160;</p>
<div style="background: white;">
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Public</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Sub</span></span><span style="color: #000000;"> SetAssemblySketchesVisibility()</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oDrawingDoc </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> DrawingDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> ThisApplication.ActiveDocument.DocumentType &lt;&gt;</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; kDrawingDocumentObject </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox(</span></span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;need to make a drawing the active document&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">End</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oDrawingDoc = ThisApplication.ActiveDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oView </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> DrawingView</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> oDrawingDoc.ActiveSheet.DrawingViews.Count &lt; 1 </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox(</span></span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;Add a view to the drawing&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">End</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oView = oDrawingDoc.ActiveSheet.DrawingViews(1)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oDoc </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Document</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oDoc = oView.ReferencedDocumentDescriptor.ReferencedDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> oDoc.DocumentType &lt;&gt; kAssemblyDocumentObject </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox(</span></span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;View&#39;s Referenced doc needs to be an assembly&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">End</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oAssy </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> AssemblyDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oAssy = oView.ReferencedDocumentDescriptor.ReferencedDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSubOcc </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> ComponentOccurrence</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">For</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Each</span></span><span style="color: #000000;"> oSubOcc </span><span><span style="color: #0000ff;">In</span></span><span style="color: #000000;"> oAssy.ComponentDefinition.Occurrences</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> oSubOcc.DefinitionDocumentType =</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; kAssemblyDocumentObject </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSubAssyDef </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> AssemblyComponentDefinition</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oSubAssyDef = oSubOcc.Definition</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSketch </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> PlanarSketch</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #2b91af;">Debug</span></span><span style="color: #000000;">.Print(oSubAssyDef.Sketches.Count)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">For</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Each</span></span><span style="color: #000000;"> oSketch </span><span><span style="color: #0000ff;">In</span></span><span style="color: #000000;"> oSubAssyDef.Sketches</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSketchProxy </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> PlanarSketchProxy</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oSubOcc.CreateGeometryProxy(oSketch,</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oSketchProxy)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39;Set Visibility of the Proxy Object DOES NOT</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span><span style="color: #008000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ‘support AssemblySketches with release prior</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span><span style="color: #008000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ‘to 2009</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oView.SetVisibility(oSketchProxy, </span><span><span style="color: #0000ff;">True</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Next</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Next</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Sub</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas; color: #0000ff;"><span>&#0160;</span></span></p>
<p>This VB.NET example is from a button on a form in a stand alone exe that access Inventor from out of process.</p>
<div style="background: white;">
<p style="margin: 0px;"><span style="font-family: Consolas;"><span><span style="color: #0000ff;"><span style="font-size: 10pt;">Imports</span></span></span><span style="color: #000000; font-size: 10pt;"> Inventor</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Public</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Class</span></span><span style="color: #000000;"> </span></span><span><span style="color: #2b91af; font-size: 10pt;">Form1</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> m_inventorApp </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Inventor.Application = </span></span><span><span style="color: #0000ff; font-size: 10pt;">Nothing</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Private</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Sub</span></span><span style="color: #000000;"> Button1_Click(</span><span><span style="color: #0000ff;">ByVal</span></span><span style="color: #000000;"> sender </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> System.</span><span><span style="color: #2b91af;">Object</span></span><span style="color: #000000;">,</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff;">ByVal</span></span><span style="color: #000000;"> e </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> System.</span><span><span style="color: #2b91af;">EventArgs</span></span><span style="color: #000000;">) </span><span><span style="color: #0000ff;">Handles</span></span><span style="color: #000000;"> Button1.Click</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Try</span></span><span style="color: #000000;"> </span></span><span><span style="color: #008000; font-size: 10pt;">&#39; Try to get an active instance of Inventor</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp = </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; System.Runtime.InteropServices.</span></span><span style="font-size: 10pt;"><span><span style="color: #2b91af;">Marshal</span></span><span style="color: #000000;">.GetActiveObject</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (</span><span><span style="color: #a31515;">&quot;Inventor.Application&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Catch</span></span><span style="color: #000000;"> </span></span><span><span style="color: #008000; font-size: 10pt;">&#39; If not active, create a new Inventor session</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> inventorAppType </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> </span><span><span style="color: #2b91af;">Type</span></span><span style="color: #000000;"> = </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; System.</span><span><span style="color: #2b91af;">Type</span></span><span style="color: #000000;">.GetTypeFromProgID(</span><span><span style="color: #a31515;">&quot;Inventor.Application&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp = System.</span></span><span style="font-size: 10pt;"><span><span style="color: #2b91af;">Activator</span></span><span style="color: #000000;">.CreateInstance</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (inventorAppType)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39;Must be set visible explicitly</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; m_inventorApp.Visible = </span></span><span><span style="color: #0000ff; font-size: 10pt;">True</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Catch</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; System.Windows.Forms.MessageBox.Show(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;Error: couldn&#39;t create Inventor instance&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Try</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; SetAssemblySketchesVisibility()</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Sub</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Public</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Sub</span></span><span style="color: #000000;"> SetAssemblySketchesVisibility()</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oDrawingDoc </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> DrawingDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> m_inventorApp.ActiveDocument.DocumentType &lt;&gt; </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; DocumentTypeEnum.kDrawingDocumentObject </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox(</span></span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;need to make a drawing the active document&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">End</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oDrawingDoc = m_inventorApp.ActiveDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oView </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> DrawingView</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> oDrawingDoc.ActiveSheet.DrawingViews.Count &lt; 1 </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox(</span></span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;Add a view to the drawing&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">End</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oView = oDrawingDoc.ActiveSheet.DrawingViews(1)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oDoc </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Document</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oDoc = </span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oView.ReferencedDocumentDescriptor.ReferencedDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> oDoc.DocumentType &lt;&gt; </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; DocumentTypeEnum.kAssemblyDocumentObject </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox(</span></span><span style="font-size: 10pt;"><span><span style="color: #a31515;">&quot;View&#39;s Referenced doc needs to be an assembly&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">End</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oAssy </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> AssemblyDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oAssy =</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oView.ReferencedDocumentDescriptor.ReferencedDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSubOcc </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> ComponentOccurrence</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">For</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Each</span></span><span style="color: #000000;"> oSubOcc </span><span><span style="color: #0000ff;">In</span></span><span style="color: #000000;"> oAssy.ComponentDefinition.Occurrences</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">If</span></span><span style="color: #000000;"> oSubOcc.DefinitionDocumentType = </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; DocumentTypeEnum.kAssemblyDocumentObject </span></span><span><span style="color: #0000ff; font-size: 10pt;">Then</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSubAssyDef </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> AssemblyComponentDefinition</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oSubAssyDef = oSubOcc.Definition</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSketch </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> PlanarSketch</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #2b91af;">Debug</span></span><span style="color: #000000;">.Print(oSubAssyDef.Sketches.Count)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">For</span></span><span style="color: #000000;"> </span><span><span style="color: #0000ff;">Each</span></span><span style="color: #000000;"> oSketch </span><span><span style="color: #0000ff;">In</span></span><span style="color: #000000;"> oSubAssyDef.Sketches</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oSketchProxy </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> PlanarSketchProxy =</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Nothing</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oSubOcc.CreateGeometryProxy(oSketch, </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="font-size: 10pt;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oSketchProxy)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000; font-size: 10pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #008000; font-size: 10pt;">&#39;Set Visibility of the Proxy Object DOES NOT</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span><span style="color: #008000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ‘support AssemblySketches with release prior</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span><span style="color: #008000; font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ‘to 2009</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oView.SetVisibility(oSketchProxy, </span><span><span style="color: #0000ff;">True</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Next</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">If</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="color: #0000ff; font-size: 10pt;">Next</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Sub</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: 10pt;">&#0160;&#0160;&#0160; </span></span><span style="font-size: 10pt;"><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff; font-size: 10pt;">Class</span></span></span></p>
</div>
</div>
