---
layout: "post"
title: "include with API a work plane from model inside the drawing"
date: "2012-06-14 02:27:47"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/06/include-with-api-a-work-plane-from-model-inside-the-drawing.html "
typepad_basename: "include-with-api-a-work-plane-from-model-inside-the-drawing"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><b>Issue</b></p>  <p>I want my WorkPlane from my model to be visible in my drawing, how can I achieve this through API?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>If the model is a Part, it is pretty straightforward: you just have to retrieve the relevant WorkPlane object from the PartComponentDefinition and use the DrawingView.SetVisibility method passing this object.</p>  <p>If the model is an Assembly, then you first have to retrieve the WorkPlane object from the corresponding occurrence Definition and create a WorkPlaneProxy in the top level Assembly. Once it is done use again DrawingView.SetVisibility method passing the proxy object.</p>  <p>Here are the samples that illustrate the two situations:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> SetWorkPlaneVisibilityFromPart()</span></p>    <p style="margin: 0px">&#160;</p>    <div style="font-family: courier new; background: white; color: black; font-size: 8pt">     <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160;&#160;&#160; ' assume we have had Inventor application</span></p>      <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160;&#160;&#160; '&#160; _InvApplication</span></p>      <p style="margin: 0px"><span style="line-height: 140%; color: green"></span></p>   </div>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDrawingDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">DrawingDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oDrawingDoc = _InvApplication.ActiveDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Get referenced Part document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oPart </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PartDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oPart = oDrawingDoc.ReferencedDocuments(1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oPartCompDef </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PartComponentDefinition</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oPartCompDef = oPart.ComponentDefinition</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Get YZ WorkPlane, suppose it's perpendicular to the view</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oWP </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">WorkPlane</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oWP = oPartCompDef.WorkPlanes.Item(</span><span style="line-height: 140%; color: #a31515">&quot;YZ Plane&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Set visibility</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oDrawingDoc.Sheets(1).DrawingViews(1).</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; SetVisibility</span><span style="line-height: 140%">(oWP, </span><span style="line-height: 140%; color: blue">True</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue"></span></p> </div>  <p></p>  <p></p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> SetWorkPlaneVisibilityFromAsm()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' assume we have had Inventor application</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'&#160; _InvApplication</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDrawingDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">DrawingDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oDrawingDoc = _InvApplication.ActiveDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Get referenced Assembly document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oAsm </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AssemblyDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oAsm = oDrawingDoc.ReferencedDocuments(1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Get first occurrence, suppose it's a Part</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oOcc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ComponentOccurrence</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oOcc = oAsm.ComponentDefinition.Occurrences(1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oPartCompDef </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PartComponentDefinition</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oPartCompDef = oOcc.Definition</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Get YZ WorkPlane, suppose it's perpendicular to the view</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oWP </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">WorkPlane</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oWP = oPartCompDef.WorkPlanes.Item(</span><span style="line-height: 140%; color: #a31515">&quot;YZ Plane&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Create proxy object</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oWPpx </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">WorkPlaneProxy</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oOcc.CreateGeometryProxy(oWP, oWPpx)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Set visibility </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oDrawingDoc.Sheets(1).DrawingViews(1).</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; SetVisibility(oWPpx, </span><span style="line-height: 140%; color: blue">True</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>
