---
layout: "post"
title: "Finding the angle between two vectors along a given direction (anti-clockwise or clockwise)"
date: "2012-07-14 23:43:29"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/07/finding-the-angle-between-two-vectors-along-a-given-direction-anti-clockwise-or-clockwise.html "
typepad_basename: "finding-the-angle-between-two-vectors-along-a-given-direction-anti-clockwise-or-clockwise"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><b>Issue</b></p>  <p>Question: How to find the angle between two vectors along a particular direction, i.e clockwise or anti-clockwise using the Inventor API?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>The angle between any two vectors (angle being defined as the union of the two vectors) as returned by the &quot;Vector.AngleTo&quot; method is always less than 180 deg irrespective of the directions of the vectors. The angle returned is the included angle between the vectors and hence, is always less than 180 deg. </p>  <p>This angle is the smaller of &quot;theta&quot; and &quot;360-theta&quot; (where &quot;theta&quot; is the angle that you would consider when calculating the dot product or the cross product between the vectors), this applies irrespective of how your coordinate system is defined. </p>  <p>If you want your angles to be returned in a particular &quot;sense&quot; (anti-clockwise or clockwise) then you could define this &quot;sense&quot; as a direction vector. With this direction defined, you could compare the cross product of the vectors (say Vector1 and Vector2) between which you want to measure the angle to this direction vector, if they are the same then the angle is Vector1.AngleTo(Vector2), but, if opposite in direction, then the angle is (2*pi) - Vector1.AngleTo(Vector2).</p>  <p>As an example, let us consider that all vectors lie on the XY plane. If you are looking at the XY plane in such a manner that the positive X direction points to the right and the positive Y direction points towards the top, then the Z direction would be pointing out of the plane towards you. Given this direction of viewing the XY plane, and if you want to measure the angles between all vectors that might be drawn on the XY planes in the anti-clockwise direction only, then the steps are:   <br />1) Define the &quot;sense&quot; or direction vector corresponding to the anti-clockwise measurement; in this case it would be the Z vector.    <br />2) In order to find the angle between any two vectors, e.g. Vector1 and Vector2, find the cross product of the two vectors, i.e. Vector1 x Vector2, if the direction of the cross product vector is the same as the direction vector (in this case the Z direction), then the angle between them in the anti-clockwise direction is Vector1.AngleTo(Vector2) but, if the direction of the cross-product is opposite that of the direction vector, then the angle between the vectors is 2*pi â€“ Vector1.AngleTo(Vector2).</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> VectorAngle()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> Tg </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">TransientGeometry</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; Tg = m_inventorApp.TransientGeometry</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'if you have many vectors on a plane and </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'want to measure angles in the same sense:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'e.g anti-clockwise</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'use two vectors to set up the sense</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> v1 </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Vector</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; v1 = Tg.CreateVector(1, 0, 0)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> v2 </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Vector</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; v2 = Tg.CreateVector(0, 1, 0)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> dir </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Vector</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; dir = v1.CrossProduct(v2)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'use above or reverse it:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'dir.X = -(dir.X)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'dir.Y = -(dir.Y)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'dir.Z = -(dir.Z)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'now use the sense to measure angles </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'between any other vectors on the plane</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> v3 </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Vector</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; v3 = Tg.CreateVector(-1, -1, 0)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oCrossProd </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Vector</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; oCrossProd = v1.CrossProduct(v3)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> angRad </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oCrossProd.DotProduct(dir) &lt; 0 </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; angRad = 2 * </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.PI - v1.AngleTo(v3)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; angRad = v1.AngleTo(v3)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> angDeg </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span><span style="line-height: 140%"> = angRad * 180 / </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.PI</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;Angle between vectors = &quot;</span><span style="line-height: 140%"> + angDeg.ToString())</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p> </div>
