---
layout: "post"
title: "Printing Watermark on Inventor File while Checking it in Vault"
date: "2012-05-28 02:11:41"
author: "Barbara Han"
categories:
  - "AutoCAD Mechanical"
  - "Barbara Han"
  - "Inventor"
  - "Vault"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/printing-watermark-on-inventor-file-while-checking-it-in-vault.html "
typepad_basename: "printing-watermark-on-inventor-file-while-checking-it-in-vault"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <p><strong>Issue</strong></p>  <p>I am trying to put watermark on the Inventor File while check-in to the vault inside Inventor. I am doing this in the &quot;Pre-Check-in event&quot;, but, the file is getting prompted to be checked out. Is it possible to change my file while check-in command is invoked?</p>  <p><strong>Solution</strong>    <br />In this case, the pre event of the web service API, i.e. CheckinFile, is triggered after the file is read by Vault Addin and set to read only, so it's too late to change the file at this moment.</p>  <p>The way is to capture command event, i.e. UserInputEvents.OnActivateCommand, through Inventor API. This event should fire before pre event of the CheckinFile API. If the command name is, i.e. VaultCheckinTop (you can specify other command, of course), you can edit the file and save it, then the change will be saved in Vault file.</p>  <p>The following is a VB.NET sample code that capture the command event from an Inventor AddIn, and add a work point in part file while checking the part file in Vault:</p>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px">     <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"></font></span></font></p>   </p>    <div style="font-family: ; background: white; color: ">     <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">Dim</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> UIEvts </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#2b91af">UserInputEvents</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> = m_inApp.CommandManager.UserInputEvents</font></span></font></p>      <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>      <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">AddHandler</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> UIEvts.OnActivateCommand, </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">AddressOf</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> UIEvts_OnActivateCommand</font></span></font></p>   </div>    <p style="margin: 0px">……</p> </div>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">Private</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Sub</font></span><span style="line-height: 11pt"><font color="#000000"> UIEvts_OnActivateCommand(</font></span><span style="line-height: 11pt; color: "><font color="#0000ff">ByVal</font></span><span style="line-height: 11pt"><font color="#000000"> CommandName </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">String</font></span><span style="line-height: 11pt"><font color="#000000">, </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">ByVal</font></span><span style="line-height: 11pt"><font color="#000000"> Context </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#2b91af">NameValueMap</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">If</font></span><span style="line-height: 11pt"><font color="#000000"> CommandName = </font></span><span style="line-height: 11pt; color: "><font color="#a31515">&quot;VaultCheckinTop&quot;</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> curDoc </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#2b91af">Document</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> = m_inApp.ActiveDocument</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">If</font></span><span style="line-height: 11pt"><font color="#000000"> curDoc.DocumentType = </font></span><span style="line-height: 11pt; color: "><font color="#2b91af">DocumentTypeEnum</font></span><span style="line-height: 11pt"><font color="#000000">.kPartDocumentObject </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> ptDoc </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#2b91af">PartDocument</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> = curDoc</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Call</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ptDoc.ComponentDefinition.WorkPoints.AddFixed(m_inApp.TransientGeometry.CreatePoint(10, 10, 100))</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; ptDoc.Save()</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p> </div>    <p>Actually this method should work with AutoCAD too, but the command event and command name may be different between Inventor and AutoCAD. For AutoCAD, you can capture Document.CommandWillStart event with AutoCAD .NET API, or AcEditorReactor.commandWillStart event with ObjectARX API. </p>
