---
layout: "post"
title: "Create shapes like cones with Client Graphics"
date: "2012-08-15 13:56:09"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/create-shapes-like-cones-with-client-graphics.html "
typepad_basename: "create-shapes-like-cones-with-client-graphics"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p>ClientGraphics in the Inventor API allow you to draw your own graphics through some basic primitive. (other ways are available too). The following VBA and VB.NET examples create a circle or a cone with the ClientGraphics API. (Open a part and run TestProcCG)</p>  <p>This <a href="http://modthemachine.typepad.com/my_weblog/2012/08/discussion-on-client-graphics.html" target="_blank">Mod the Machine post</a> on client graphics may also be of interest.</p>  <p><strong>VBA</strong></p>  <p><font color="#0000ff">'A small utility method that will compute      <br />'a normal vector to the one in input       <br /></font>Public Function GetNormalVector _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oVector As Vector) As UnitVector</p>  <p>&#160;&#160;&#160; Dim oOutput As UnitVector</p>  <p>&#160;&#160;&#160; If oVector.X &lt;&gt; 0 Then    <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oOutput = ThisApplication. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; TransientGeometry.CreateUnitVector _     <br />(-(oVector.Y + oVector.Z) / oVector.X, 0, 1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set GetNormalVector = oOutput     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Else     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oOutput = ThisApplication. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TransientGeometry. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; CreateUnitVector(1, 0, 0)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set GetNormalVector = oOutput     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; End If</p>  <p>End Function</p>  <p>Public Sub DrawCone(oDataSets As GraphicsDataSets, _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oClientGraphics As ClientGraphics, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center As point, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Height As Double, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Normal As Vector, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Radius As Double, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; NbTriangles As Long, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oStyle As RenderStyle)</p>  <p>&#160;&#160;&#160; Dim oTG As TransientGeometry    <br />&#160;&#160;&#160; Set oTG = ThisApplication.TransientGeometry     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oCoordSet As GraphicsCoordinateSet     <br />&#160;&#160;&#160; Set oCoordSet = oDataSets. _     <br />&#160;&#160;&#160;&#160;&#160; CreateCoordinateSet(oDataSets.count + 1)     <br />&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">'Normalize direction      <br /></font>&#160;&#160;&#160; Dim NormalUnit As UnitVector     <br />&#160;&#160;&#160; Set NormalUnit = Normal.AsUnitVector     <br />&#160;&#160;&#160; <br />&#160;<font color="#0000ff">&#160;&#160; 'Get a normal vector to the direction      <br /></font>&#160;&#160;&#160; Dim DirUnit As UnitVector     <br />&#160;&#160;&#160; Set DirUnit = GetNormalVector(Normal)     <br />&#160;&#160;&#160; <br />&#160;<font color="#0000ff">&#160;&#160; 'Angle of rotation      <br /></font>&#160;&#160;&#160; Dim AngleRad As Double     <br />&#160;&#160;&#160; AngleRad = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Math.Atn(1) * 8 / NbTriangles     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' = 2 * Pi / NbTriangles     <br />&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">'Create a rotation matrix to compute      <br />&#160;&#160;&#160; 'triangle points       <br /></font>&#160;&#160;&#160; Dim oRotMatrix As Matrix     <br />&#160;&#160;&#160; Set oRotMatrix = oTG.CreateMatrix     <br />&#160;&#160;&#160; Call oRotMatrix.SetToRotation _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (AngleRad, Normal, Center)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oPointCoords() As Double     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; ReDim oPointCoords _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (1 To 3 * (2 + NbTriangles))     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160; <font color="#0000ff">&#160; 'First point is the center      <br /></font>&#160;&#160;&#160; oPointCoords(1) = _     <br />&#160;&#160;&#160; Center.X + Height * NormalUnit.X     <br />&#160;&#160;&#160; oPointCoords(2) = _     <br />&#160;&#160;&#160; Center.Y + Height * NormalUnit.Y     <br />&#160;&#160;&#160; oPointCoords(3) = _     <br />&#160;&#160;&#160; Center.Z + Height * NormalUnit.Z     <br />&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">'Other points are the base points      <br />&#160;&#160;&#160; 'of the triangles       <br /></font>&#160;&#160;&#160; Dim index As Long     <br />&#160;&#160;&#160; For index = 1 To NbTriangles     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oBasePoint As point     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oBasePoint = oTG.CreatePoint( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.X + DirUnit.X * Radius, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.Y + DirUnit.Y * Radius, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.Z + DirUnit.Z * Radius)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call DirUnit.TransformBy(oRotMatrix)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(3 * index + 1) = oBasePoint.X     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(3 * index + 2) = oBasePoint.Y     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(3 * index + 3) = oBasePoint.Z     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Call oCoordSet.PutCoordinates(oPointCoords)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oGraphicNode As GraphicsNode     <br />&#160;&#160;&#160; Set oGraphicNode = oClientGraphics.AddNode _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oClientGraphics.count + 1)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oTriangleSet As TriangleFanGraphics     <br />&#160;&#160;&#160; Set oTriangleSet = oGraphicNode. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AddTriangleFanGraphics     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oIndex As GraphicsIndexSet     <br />&#160;&#160;&#160; Set oIndex = oDataSets.CreateIndexSet _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oDataSets.count + 1)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; For index = 1 To (NbTriangles + 1)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oIndex.Add(index, index)     <br />&#160;&#160;&#160; Next     <br />&#160;&#160;&#160; <br />&#160;<font color="#0000ff">&#160;&#160; 'Last triangle join the last and first point      <br /></font>&#160;&#160;&#160; Call oIndex.Add(NbTriangles + 2, 2)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; oGraphicNode.RenderStyle = oStyle</p>  <p>&#160;&#160;&#160; oTriangleSet.CoordinateSet = oCoordSet    <br />&#160;&#160;&#160; oTriangleSet.CoordinateIndexSet = oIndex     <br />&#160;&#160;&#160; <br />End Sub</p>  <p>Public Sub TestProcCG()</p>  <p>&#160;&#160;&#160; Dim oDoc As Document    <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oTG As TransientGeometry     <br />&#160;&#160;&#160; Set oTG = ThisApplication.TransientGeometry     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oCompDef As ComponentDefinition     <br />&#160;&#160;&#160; Set oCompDef = oDoc.ComponentDefinition     <br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; On Error Resume Next     <br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oDataSets As GraphicsDataSets     <br />&#160;&#160;&#160; Set oDataSets = oDoc. _     <br />&#160;&#160;&#160;&#160;&#160;&#160; GraphicsDataSetsCollection.Add(&quot;TestCG&quot;)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; If Err Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oDataSets = _     <br />&#160;&#160;&#160;&#160;&#160; oDoc.GraphicsDataSetsCollection(&quot;TestCG&quot;)     <br />&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oClientGraphics As ClientGraphics     <br />&#160;&#160;&#160; Set oClientGraphics = oCompDef. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClientGraphicsCollection.Add(&quot;TestCG&quot;)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; If Err Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oClientGraphics = _     <br />&#160;&#160;&#160; oCompDef.ClientGraphicsCollection(&quot;TestCG&quot;)     <br />&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Call DrawCone(oDataSets, oClientGraphics, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint(0, 0, 0), 10, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreateVector(0, 1, 0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 5, 10, _     <br />&#160;&#160;&#160; oDoc.RenderStyles.Item(&quot;Glass (Limo Tint)&quot;))     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Call DrawCone(oDataSets, oClientGraphics, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint(15, 0, 0), 10, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreateVector(0, 1, 0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 5, 100, _     <br />&#160;&#160; oDoc.RenderStyles.Item(&quot;Glass (Limo Tint)&quot;))     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Call DrawCone(oDataSets, oClientGraphics, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint(30, 0, 0), 0, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreateVector(0, 1, 0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 5, 100, _     <br />&#160;&#160; oDoc.RenderStyles.Item(&quot;Glass (Limo Tint)&quot;))     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; ThisApplication.ActiveView.Update</p>  <p>End Sub</p>  <p><strong>VB.NET</strong></p>  <div style="font-family: consolas; background: #eeeeee; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Public</span> <span style="color: blue">Class</span> <span style="color: #2b91af">Form1</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> m_inventorApp <span style="color: blue">As</span> Inventor.<span style="color: #2b91af">Application</span> _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = <span style="color: blue">Nothing</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Private</span> <span style="color: blue">Sub</span> Button1_Click(<span style="color: blue">ByVal</span> sender <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.<span style="color: #2b91af">Object</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">ByVal</span> e <span style="color: blue">As</span> System.<span style="color: #2b91af">EventArgs</span>) _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Handles</span> Button1.Click</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Get an active instance of Inventor</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; InteropServices.<span style="color: #2b91af">Marshal</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160; GetActiveObject(<span style="color: #a31515">&quot;Inventor.Application&quot;</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Catch</span> <span style="color: green">'Inventor not started</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.Windows.Forms.<span style="color: #2b91af">MessageBox</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Show(<span style="color: #a31515">&quot;Start an Inventor session&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Exit Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Call the Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; TestProcCG()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Public</span> <span style="color: blue">Sub</span> TestProcCG()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oDoc <span style="color: blue">As</span> <span style="color: #2b91af">Document</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_inventorApp.ActiveDocument</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oTG <span style="color: blue">As</span> <span style="color: #2b91af">TransientGeometry</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG = m_inventorApp.TransientGeometry</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oCompDef <span style="color: blue">As</span> <span style="color: #2b91af">ComponentDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCompDef = oDoc.ComponentDefinition</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oDataSets <span style="color: blue">As</span> <span style="color: #2b91af">GraphicsDataSets</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDataSets = oDoc. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GraphicsDataSetsCollection.Add(<span style="color: #a31515">&quot;TestCG&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDataSets = oDoc. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GraphicsDataSetsCollection(<span style="color: #a31515">&quot;TestCG&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oClientGraphics <span style="color: blue">As</span> <span style="color: #2b91af">ClientGraphics</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oClientGraphics = oCompDef. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClientGraphicsCollection.Add(<span style="color: #a31515">&quot;TestCG&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oClientGraphics = oCompDef. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClientGraphicsCollection(<span style="color: #a31515">&quot;TestCG&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; DrawCone(oDataSets, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oClientGraphics, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint(0, 0, 0), 10, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreateVector(0, 1, 0), _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 5, 10, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.RenderStyles.Item(<span style="color: #a31515">&quot;Glass (Limo Tint)&quot;</span>))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; DrawCone(oDataSets, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oClientGraphics, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint(15, 0, 0), 10, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreateVector(0, 1, 0), _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 5, 100, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.RenderStyles.Item(<span style="color: #a31515">&quot;Glass (Limo Tint)&quot;</span>))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; DrawCone(oDataSets, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oClientGraphics, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint(30, 0, 0), 0, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreateVector(0, 1, 0), _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 5, 100, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160; oDoc.RenderStyles.Item(<span style="color: #a31515">&quot;Glass (Limo Tint)&quot;</span>))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp.ActiveView.Update()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Catch</span> ex <span style="color: blue">As</span> <span style="color: #2b91af">Exception</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Catch</span> ex <span style="color: blue">As</span> <span style="color: #2b91af">Exception</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Catch</span> ex <span style="color: blue">As</span> <span style="color: #2b91af">Exception</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">'A small utility method that will </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">'compute a normal vector to the </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">'one in input</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Public</span> <span style="color: blue">Function</span> GetNormalVector _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: blue">ByVal</span> oVector <span style="color: blue">As</span> <span style="color: #2b91af">Vector</span>) <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">UnitVector</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oOutput <span style="color: blue">As</span> <span style="color: #2b91af">UnitVector</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> oVector.X &lt;&gt; 0 <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oOutput = m_inventorApp. _</p>    <p style="margin: 0px">&#160; TransientGeometry.CreateUnitVector _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (-(oVector.Y + oVector.Z) / _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oVector.X, 0, 1)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetNormalVector = oOutput</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oOutput = m_inventorApp. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TransientGeometry. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; CreateUnitVector(1, 0, 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetNormalVector = oOutput</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Function</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Public</span> <span style="color: blue">Sub</span> DrawCone(<span style="color: blue">ByVal</span> oDataSets _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">As</span> <span style="color: #2b91af">GraphicsDataSets</span>, _</p>    <p style="margin: 0px"><span style="color: blue">ByVal</span> oClientGraphics <span style="color: blue">As</span> <span style="color: #2b91af">ClientGraphics</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">ByVal</span> Center <span style="color: blue">As</span> <span style="color: #2b91af">Point</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">ByVal</span> Height <span style="color: blue">As</span> <span style="color: blue">Double</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">ByVal</span> Normal <span style="color: blue">As</span> <span style="color: #2b91af">Vector</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">ByVal</span> Radius <span style="color: blue">As</span> <span style="color: blue">Double</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">ByVal</span> NbTriangles <span style="color: blue">As</span> <span style="color: blue">Long</span>, _</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">ByVal</span> oStyle <span style="color: blue">As</span> <span style="color: #2b91af">RenderStyle</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oTG <span style="color: blue">As</span> <span style="color: #2b91af">TransientGeometry</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG = m_inventorApp. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TransientGeometry</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oCoordSet <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">GraphicsCoordinateSet</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCoordSet = oDataSets. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; CreateCoordinateSet _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oDataSets.Count + 1)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Normalize direction</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> NormalUnit <span style="color: blue">As</span> <span style="color: #2b91af">UnitVector</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; NormalUnit = Normal.AsUnitVector</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Get a normal vector to </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'the direction</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> DirUnit <span style="color: blue">As</span> <span style="color: #2b91af">UnitVector</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; DirUnit = GetNormalVector(Normal)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Angle of rotation</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> AngleRad <span style="color: blue">As</span> <span style="color: blue">Double</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; AngleRad = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Math</span>.Atan(1) * 8 / NbTriangles</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' = 2 * Pi / NbTriangles</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Create a rotation matrix to </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'compute triangle points</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oRotMatrix <span style="color: blue">As</span> <span style="color: #2b91af">Matrix</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oRotMatrix = oTG.CreateMatrix</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> oRotMatrix.SetToRotation _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (AngleRad, Normal, Center)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oPointCoords() <span style="color: blue">As</span> <span style="color: blue">Double</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">ReDim</span> oPointCoords _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (0 <span style="color: blue">To</span> 3 * (2 + NbTriangles))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'First point is the center</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(1) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.X + Height * NormalUnit.X</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(2) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.Y + Height * NormalUnit.Y</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(3) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.Z + Height * NormalUnit.Z</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Other points are the base </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'points of the triangles</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> index <span style="color: blue">As</span> <span style="color: blue">Long</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">For</span> index = 1 <span style="color: blue">To</span> NbTriangles</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oBasePoint <span style="color: blue">As</span> <span style="color: #2b91af">Point</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBasePoint = oTG.CreatePoint( _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.X + DirUnit.X * Radius, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.Y + DirUnit.Y * Radius, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Center.Z + DirUnit.Z * Radius)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> DirUnit.TransformBy _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oRotMatrix)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(3 * index + 1) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBasePoint.X</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(3 * index + 2) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBasePoint.Y</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPointCoords(3 * index + 3) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBasePoint.Z</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Next</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> oCoordSet.PutCoordinates _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oPointCoords)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oGraphicNode <span style="color: blue">As</span> <span style="color: #2b91af">GraphicsNode</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oGraphicNode = oClientGraphics. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AddNode(oClientGraphics.Count + 1)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oTriangleSet <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">TriangleFanGraphics</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTriangleSet = oGraphicNode. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AddTriangleFanGraphics</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oIndex <span style="color: blue">As</span> <span style="color: #2b91af">GraphicsIndexSet</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oIndex = oDataSets.CreateIndexSet _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oDataSets.Count + 1)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">For</span> index = 1 <span style="color: blue">To</span> (NbTriangles + 1)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> oIndex.Add(index, index)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Next</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Last triangle join the last</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' and first point</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> oIndex.Add(NbTriangles + 2, 2)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oGraphicNode.RenderStyle = oStyle</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTriangleSet.CoordinateSet = oCoordSet</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTriangleSet.CoordinateIndexSet = oIndex</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Class</span></p> </div>
