---
layout: "post"
title: "ClientFeature content modification"
date: "2012-05-25 15:07:12"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/clientfeature-content-modification.html "
typepad_basename: "clientfeature-content-modification"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p><b>Issue</b></p>  <p>I created a ClientFeature which contains some objects. I would like to know:</p>  <p>How to empty the ClientFeature without deleting itself.    <br />How to add objects to the ClientFeature again</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>You can use <b>ClientFeatureElement.Delete</b> to empty the elements in this <b>ClientFeatureDefinition</b> without deleting the ClientFeature. Then you can do other operations such as adding other features to the document. If you want to add or modify elements of the ClientFeature, use the ClientFeatureDefinition of the ClientFeature and add the new elements.</p>  <p>The following VB.NET example shows this approach. Suppose a ClientFeature has been created. Its definition contains the first extrude feature in the document. First this code removes the elements of the ClientFeature. Then adds the extrude feature again to the ClientFeature.</p>  <p>Note: After adding the objects, the BrowserNode position of the ClientFeature will change to that of its first element. </p>  <div style="font-family: consolas; background: white; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Sub</span> EmptyElements(<span style="color: blue">ByVal</span> Index)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> doc <span style="color: blue">As</span> <span style="color: #2b91af">PartDocument</span></p>    <p style="margin: 0px">&#160;&#160;&#160; doc = _invApp.ActiveDocument</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> feat <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeature</span></p>    <p style="margin: 0px">&#160;&#160;&#160; feat = doc.ComponentDefinition _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Features.ClientFeatures(Index)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> featDef <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeatureDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160; featDef = feat.Definition</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> elem <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeatureElement</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">For</span> <span style="color: blue">Each</span> elem <span style="color: blue">In</span> featDef.ClientFeatureElements</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; elem.Delete()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Next</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">Sub</span> RedefineClientF(<span style="color: blue">ByVal</span> Index)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> doc <span style="color: blue">As</span> <span style="color: #2b91af">PartDocument</span></p>    <p style="margin: 0px">&#160;&#160;&#160; doc = _invApp.ActiveDocument</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> feat <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeature</span></p>    <p style="margin: 0px">&#160;&#160;&#160; feat = doc.ComponentDefinition _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Features.ClientFeatures(Index)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> featDef <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeatureDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160; featDef = feat.Definition</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">'add the first extrude feature</span></p>    <p style="margin: 0px">&#160;&#160;&#160; featDef.ClientFeatureElements.Add _</p>    <p style="margin: 0px">&#160;&#160;&#160; (doc.ComponentDefinition.Features _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .ExtrudeFeatures(1))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">' If you have not an ClientFeature</span></p>    <p style="margin: 0px"><span style="color: green">' ready for test, please refer to below</span></p>    <p style="margin: 0px"><span style="color: green">' code to create a ClientFeature:</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">Sub</span> createClientFeature()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oDoc <span style="color: blue">As</span> <span style="color: #2b91af">PartDocument</span> = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _invApp.ActiveDocument</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oDef <span style="color: blue">As</span> <span style="color: #2b91af">PartComponentDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oDef = oDoc.ComponentDefinition</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oClientDef <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeatureDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oClientDef = oDef.Features. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClientFeatures.CreateDefinition()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">'add the first extrude feature</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oClientDef.ClientFeatureElements.Add _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oDef.Features.ExtrudeFeatures.Item(1))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oClientFeature <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeature</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oClientFeature = oDef.Features.ClientFeatures _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Add(oClientDef, <span style="color: #a31515">&quot;My node&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160; oClientFeature.Name = <span style="color: #a31515">&quot;Autodesk.com&quot;</span></p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Sub</span></p> </div>
