---
layout: "post"
title: "How to programmatically set the color of an object (e.g. Layer) in Inventor?"
date: "2012-05-15 07:53:45"
author: "Gary Wassell"
categories:
  - "Gary Wassell"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/05/how-to-programmatically-set-the-color-of-an-object-eg-layer-in-inventor.html "
typepad_basename: "how-to-programmatically-set-the-color-of-an-object-eg-layer-in-inventor"
typepad_status: "Publish"
---

<p><strong>Issue</strong></p>
<p>I need to set the color of my newly created Layer object. I use &quot;Layer.Color.SetColor(120,120,0)&quot;, but it does not work. How can the color of a layer be changed?</p>
<p><a name="section2"></a></p>
<p><strong>Solution</strong></p>
<p>To control the color of a layer create a new color object and assign it to the layer using the color property. Use the SetColor property of&#0160; the color object to control the color.</p>
<p>Here is a VBA example:</p>
<div style="background: white;">
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160; </span></span><span><span><span style="color: #0000ff;">Sub</span></span><span style="color: #000000;"> setNewLayerColor()</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oDD </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> DrawingDocument</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oDD = ThisApplication.ActiveDocument</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oL </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Layer</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oL = oDD.StylesManager.Layers(1).Copy(</span></span><span><span><span style="color: #a31515;">&quot;MyNewLayer&quot;</span></span><span style="color: #000000;">)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span><span style="color: #0000ff;">Dim</span></span><span style="color: #000000;"> oC </span><span><span style="color: #0000ff;">As</span></span><span style="color: #000000;"> Inventor.Color</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oC = ThisApplication.TransientObjects.CreateColor(120, 120, 120)</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span><span style="color: #0000ff;">Call</span></span><span style="color: #000000;"> oC.SetColor(120, 120, 0)</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oL.Color = oC</span></span></p>
<p style="margin: 0px;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160; </span></span><span><span><span style="color: #0000ff;">End</span></span><span style="color: #000000;"> </span></span><span><span style="color: #0000ff;">Sub</span></span></span></p>
</div>
<p>In C#.Net</p>
<pre><div style="white-space: normal; background: white;"><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="white-space: normal;"><span style="color: #0000ff;">public</span></span><span style="color: #000000;"> </span><span style="white-space: normal;"><span style="color: #0000ff;">static</span></span><span style="color: #000000;"> </span><span style="white-space: normal;"><span style="color: #0000ff;">void</span></span><span style="color: #000000;"> setNewLayerColor() </span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; { </span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="white-space: normal;"><span style="color: #0000ff;">try</span></span><span style="color: #000000;"> { </span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Inventor.Application app = (Inventor.Application)System.Runtime.InteropServices.</span></span><span><span style="white-space: normal;"><span style="color: #2b91af;">Marshal</span></span><span style="color: #000000;">.GetActiveObject(</span><span style="white-space: normal;"><span style="color: #a31515;">&quot;Inventor.Application&quot;</span></span><span style="color: #000000;">);</span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; DrawingDocument oDD = app.ActiveDocument </span></span><span><span style="white-space: normal;"><span style="color: #0000ff;">as</span></span><span style="color: #000000;"> DrawingDocument;</span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; LayersEnumerator layers = oDD.StylesManager.Layers;</span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Layer oL = layers[1].Copy(</span></span><span><span style="white-space: normal;"><span style="color: #a31515;">&quot;MyNewLayer&quot;</span></span><span style="color: #000000;">) </span><span style="white-space: normal;"><span style="color: #0000ff;">as</span></span><span style="color: #000000;"> Layer;</span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Inventor.Color oC = app.TransientObjects.CreateColor(120, 120, 120, 0);</span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oC.SetColor(120, 120, 0);</span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oL.Color = oC;</span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;"><span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span><span><span style="white-space: normal;"><span style="color: #0000ff;">catch</span></span><span style="color: #000000;"> </span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></span></span></p><p style="margin: 0px; white-space: normal;"><span style="font-family: Consolas;"><span style="color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></span></p></div></pre>
