---
layout: "post"
title: "Offset a WorkPlane that is not Driven by an Offset Parameter"
date: "2012-08-23 02:59:25"
author: "Barbara Han"
categories:
  - "Barbara Han"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/08/offset-a-workplane-that-is-not-driven-by-an-offset-parameter.html "
typepad_basename: "offset-a-workplane-that-is-not-driven-by-an-offset-parameter"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/barbara-han.html" target="_self">Barbara Han</a></p>  <p><b>Issue</b></p>  <p>I need to offset a WorkPlane in a Part Document that is not driven by a model parameter. How can I do it so other work features based on it are offset as well? </p>  <p><b>Solution</b></p>  <p>The following example offsets a selected WorkPlane. After the WorkPlane has been offset it will be driven by a model parameter.</p>  <p>&#160;<em>VBA sample</em>:    <br /><font size="1" face="Courier New">Public Function OffsetPartWorkPlane(oWorkPlane As WorkPlane, Offset As Double)     <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument      <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oWorkPlanes As WorkPlanes      <br />&#160;&#160;&#160; Set oWorkPlanes = oPartDoc.ComponentDefinition.WorkPlanes      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oConstrucWorkPoint As WorkPoint      <br />&#160;&#160;&#160; Set oConstrucWorkPoint = oPartDoc.ComponentDefinition.WorkPoints.AddFixed(oWorkPlane.Plane.RootPoint)      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oConstrucWorkAxis As WorkAxis      <br />&#160;&#160;&#160; Set oConstrucWorkAxis = oPartDoc.ComponentDefinition.WorkAxes.AddFixed(oWorkPlane.Plane.RootPoint, oWorkPlane.Plane.Normal)      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oConstrucWorkPlane As WorkPlane      <br />&#160;&#160;&#160; Set oConstrucWorkPlane = oWorkPlanes.AddByNormalToCurve(oConstrucWorkAxis, oConstrucWorkPoint)      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Call oWorkPlane.SetByPlaneAndOffset(oConstrucWorkPlane, Offset)      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; oConstrucWorkPoint.Visible = False      <br />&#160;&#160;&#160; oConstrucWorkAxis.Visible = False      <br />&#160;&#160;&#160; oConstrucWorkPlane.Visible = False      <br />End Function</font></p>  <pre><p>'Select a WorkPlane and offset it<br />Public Sub TestOffsetPlane()<br />&#160;&#160;&#160; Dim oPartDoc As PartDocument<br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument<br />&#160;&#160;&#160; Dim oWorkPlane As WorkPlane<br />&#160;&#160;&#160; Set oWorkPlane = oPartDoc.SelectSet.Item(1)<br />&#160;&#160;&#160; Call OffsetPartWorkPlane(oWorkPlane, 5)<br />End Sub</p><p><font face="Arial"><em>VB.NET sample:</em></font></p><div style="font-family: ; background: white; color: "><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Sub</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> OffsetPartWorkPlane()</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> m_inventorApp </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> Inventor.Application = </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Nothing</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> m_quitInventor </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Boolean</font></span><span style="line-height: 11pt"><font color="#000000"> = </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">False</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">' Try to get an active instance of Inventor</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Try</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; m_inventorApp = System.Runtime.InteropServices.Marshal.GetActiveObject(</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#a31515">&quot;Inventor.Application&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Catch</font></span><span style="line-height: 11pt"><font color="#000000"> ex </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Exception</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Try</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#008000">' If not active, create a new Inventor session</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">If</font></span><span style="line-height: 11pt"><font color="#000000"> m_inventorApp </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Is</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">Nothing</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> inventorAppType </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span><span style="line-height: 11pt"><font color="#000000"> Type = System.Type.GetTypeFromProgID(</font></span><span style="line-height: 11pt; color: "><font color="#a31515">&quot;Inventor.Application&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)</font></span></font></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; m_inventorApp = System.Activator.CreateInstance(inventorAppType)</font></font></span></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; m_quitInventor = </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">True</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">End</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oPartDoc </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> PartDocument</font></span></font></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oPartDoc = m_inventorApp.ActiveDocument</font></font></span></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oWorkPlane </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> WorkPlane</font></span></font></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oWorkPlane = oPartDoc.SelectSet.Item(1)</font></font></span></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oWorkPlanes </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> WorkPlanes</font></span></font></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oWorkPlanes = oPartDoc.ComponentDefinition.WorkPlanes</font></font></span></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oConstrucWorkPoint </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> WorkPoint</font></span></font></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oConstrucWorkPoint = oPartDoc.ComponentDefinition.WorkPoints.AddFixed(oWorkPlane.Plane.RootPoint)</font></font></span></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oConstrucWorkAxis </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> WorkAxis</font></span></font></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oConstrucWorkAxis = oPartDoc.ComponentDefinition.WorkAxes.AddFixed(oWorkPlane.Plane.RootPoint, oWorkPlane.Plane.Normal)</font></font></span></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt; color: "><font color="#0000ff">Dim</font></span><span style="line-height: 11pt"><font color="#000000"> oConstrucWorkPlane </font></span><span style="line-height: 11pt; color: "><font color="#0000ff">As</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> WorkPlane</font></span></font></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oConstrucWorkPlane = oWorkPlanes.AddByNormalToCurve(oConstrucWorkAxis, oConstrucWorkPoint)</font></font></span></p><p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oWorkPlane.SetByPlaneAndOffset(oConstrucWorkPlane, 5)</font></font></span></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; oConstrucWorkPoint.Visible = </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">False</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; oConstrucWorkAxis.Visible = </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">False</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; oConstrucWorkPlane.Visible = </font></font></span><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">False</font></span></font></p><p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt; color: "><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span></font><span style="line-height: 11pt; color: "><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p></div></pre>
