---
layout: "post"
title: "Create a workplane from a line in a sketch and the sketch plane"
date: "2012-07-18 05:45:22"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2012/07/create-a-workplane-from-a-line-in-a-sketch-and-the-sketch-plane.html "
typepad_basename: "create-a-workplane-from-a-line-in-a-sketch-and-the-sketch-plane"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html" target="_self">Vladimir Ananyev</a></p>  <p><b>Issue</b></p>  <p>I need to create a workplane that is parallel to a line in an existing sketch and rotated a certain angle off of that sketch. Is there an example showing how to do this?</p>  <p><a name="section2"></a><b>Solution</b></p>  <p>The following example will add a new work plane. Before running this example select a line in a sketch. When the code completes a new workplane will be created. The workplane will be parallel to the line and rotated 45 degrees off the sketch plane. </p>  <h1><strong><font size="3">VBA code:</font></strong></h1>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">Private Sub testAddWorkPlane()</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160; </font></span><font style="font-size: 8pt">' Set a reference to the select set of the active document.</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160; </font></span><font style="font-size: 8pt">Dim oSelectSet As SelectSet</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160; </font></span><font style="font-size: 8pt">Set oSelectSet = ThisApplication.ActiveDocument.SelectSet</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160; </font></span><font style="font-size: 8pt">If oSelectSet.Count = 1 Then</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160; </font></span><font style="font-size: 8pt"><span style="mso-spacerun: yes">&#160;</span>If TypeOf oSelectSet.Item(1) Is SketchLine Then</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160; </font></span><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;</font></span></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Dim oPartCompDef As PartComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Set oPartCompDef = ThisApplication _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">.ActiveDocument.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Dim oSketchLine As SketchLine</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Set oSketchLine = oSelectSet.Item(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Dim oSketch As Sketch</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Set oSketch = oSketchLine.Parent</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Debug.Print oSketch.Name</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><span style="mso-spacerun: yes"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Dim oWrkPlane As WorkPlane</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">Set oWrkPlane = oPartCompDef.WorkPlanes _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160; </font></span><font style="font-size: 8pt"><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160; </span>.AddByLinePlaneAndAngle(oSketchLine, oSketch, 45#)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160; </font></span><font style="font-size: 8pt">End If</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160; </font></span><font style="font-size: 8pt">End If</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;; mso-bidi-font-family: arial"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">End Sub</font></font></span></p>  <p>&#160;</p>  <h3><font style="font-weight: bold" size="3">VB.NET code:</font></h3>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><font face="Lucida Console"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> AddWorkPlane()</font></font></span></font></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span><font style="font-size: 8pt" color="#008000">' Set a reference to the select set of the active document.</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oSelectSet </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">SelectSet</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160; </font></span><font style="font-size: 8pt">oSelectSet = m_inventorApp.ActiveDocument.SelectSet</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">If</font></span><font color="#000000"> oSelectSet.Count = 1 </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">If</font></span><font color="#000000"> </font><span><font color="#0000ff">TypeOf</font></span><font color="#000000"> oSelectSet.Item(1) </font><span><font color="#0000ff">Is</font></span><font color="#000000"> </font><span><font color="#2b91af">SketchLine</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oPartCompDef </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">PartComponentDefinition</font></span><font color="#000000"> _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">= m_inventorApp.ActiveDocument.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oSketchLine </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">SketchLine</font></span><font color="#000000"> = oSelectSet.Item(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oSketch </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Sketch</font></span><font color="#000000"> = oSketchLine.Parent</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#2b91af">Debug</font></span><font color="#000000">.Print(oSketch.Name)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font style="font-size: 8pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oWrkPlane </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">WorkPlane</font></span><font color="#000000"> = oPartCompDef _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">.WorkPlanes.AddByLinePlaneAndAngle( _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 8pt">oSketchLine, oSketch, 45.0#)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">If</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font face="Lucida Console"><span style="mso-spacerun: yes"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">If</font></span></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; mso-layout-grid-align: none" class="MsoNormal"><font face="Lucida Console"><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><span style="font-family: ; mso-bidi-font-family: &#39;Lucida Console&#39;"><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Sub</font></span></span></font></p>
