---
layout: "post"
title: "Split Feature without SplitFeature"
date: "2013-12-30 01:12:25"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/12/split-feature-without-splitfeature.html "
typepad_basename: "split-feature-without-splitfeature"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>SplitFeature is also a type of feature. But if you do not want to split a feature without SplitFeature, you could calcuate the new profiles and create the new splitting features. The following is a small code which converts an extrude feature to two extrude features with a middle line, and also creates a surface of the middle line to represent the split plane.</p>  <p>Assume the orignal extrude feature is based on a profile of a rectangle lines. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a5100b1f76970c-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_420431.jpg" width="465" height="277" /></a></p>  <p><em><font size="1">Sub test()</font></em></p>  <p><em><font size="1">&#160;&#160;&#160; Dim oPartDoc As PartDocument       <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oDef As PartComponentDefinition        <br />&#160;&#160;&#160; Set oDef = oPartDoc.ComponentDefinition        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oOldF As ExtrudeFeature        <br />&#160;&#160;&#160; Set oOldF = oDef.Features.ExtrudeFeatures(1)        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oOldFDef As ExtrudeDefinition        <br />&#160;&#160;&#160; Set oOldFDef = oOldF.Definition        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oPath As ProfilePath        <br />&#160;&#160;&#160; Set oPath = oOldFDef.Profile(1)        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oSketchEnt As SketchEntity        <br />&#160;&#160;&#160; Dim oSketch As PlanarSketch        <br />&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSketchLine1 As SketchLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSketchLine1 = oPath(1).SketchEntity        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSketchLine2 As SketchLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSketchLine2 = oPath(2).SketchEntity        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSketchLine3 As SketchLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSketchLine3 = oPath(3).SketchEntity        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSketchLine4 As SketchLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSketchLine4 = oPath(4).SketchEntity        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get sketch        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSketch = oSketchLine1.Parent        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get mid pt of line 1        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oMidPtOfLine1 As Point2d        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMidPtOfLine1 = oSketchLine1.Geometry.MidPoint        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'add sketch mid pt        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oMidSketchPtLine1 As SketchPoint        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMidSketchPtLine1 = oSketch.SketchPoints.Add(oMidPtOfLine1)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oSketch.GeometricConstraints.AddCoincident(oMidSketchPtLine1, oSketchLine1)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get mid pt of line3 which is parallel to line 1        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oMidPtOfLine3 As Point2d        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMidPtOfLine3 = oSketchLine3.Geometry.MidPoint        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'add sketch mid pt        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oMidSketchPtLine3 As SketchPoint        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMidSketchPtLine3 = oSketch.SketchPoints.Add(oMidPtOfLine3)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oSketch.GeometricConstraints.AddCoincident(oMidSketchPtLine3, oSketchLine3)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' create mid line        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oMiddleLine As SketchLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMiddleLine = oSketch.SketchLines.AddByTwoPoints(oMidPtOfLine1, oMidPtOfLine3)        <br />&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oMiddleLine.StartSketchPoint.Merge(oMidSketchPtLine1)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oMiddleLine.EndSketchPoint.Merge(oMidSketchPtLine3)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' create new extrude 1: just change the old feature's profile        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewPaths1 As ObjectCollection        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPaths1 = ThisApplication.TransientObjects.CreateObjectCollection        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths1.Add oSketchLine1        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths1.Add oSketchLine2        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths1.Add oSketchLine3        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths1.Add oMiddleLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewProfile1 As Profile        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewProfile1 = oSketch.Profiles.AddForSolid(False, oNewPaths1)</font></em></p>  <p><em><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oOldFDef.Profile = oNewProfile1       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'create the other extrude feature        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewPaths2 As ObjectCollection        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPaths2 = ThisApplication.TransientObjects.CreateObjectCollection        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths2.Add oSketchLine1        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths2.Add oSketchLine4        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths2.Add oSketchLine3        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths2.Add oMiddleLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewProfile2 As Profile        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewProfile2 = oSketch.Profiles.AddForSolid(False, oNewPaths2)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewExtrudeDef As ExtrudeDefinition        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewExtrudeDef = oDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oNewProfile2, kJoinOperation)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oNewExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewExtrude As ExtrudeFeature        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewExtrude = oDef.Features.ExtrudeFeatures.Add(oNewExtrudeDef)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'create surface on        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewPaths3 As ObjectCollection        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPaths3 = ThisApplication.TransientObjects.CreateObjectCollection        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPaths3.Add oMiddleLine        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oNewProfile3 As Profile        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewProfile3 = oSketch.Profiles.AddForSurface(oMiddleLine)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSurfaceDef As ExtrudeDefinition        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSurfaceDef = oDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oNewProfile3, kSurfaceOperation)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oSurfaceDef.SetDistanceExtent(10, kSymmetricExtentDirection)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSurface As ExtrudeFeature        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSurface = oDef.Features.ExtrudeFeatures.Add(oSurfaceDef)</font></em></p>  <p><font size="1"><em>&#160;&#160;&#160; <br />End Sub</em>      <br /></font></p>  <p>&#160;</p>  <p>After the code, the feature becomes:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a3fb5b4008970b-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_e9d32d.jpg" width="360" height="382" /></a></p>
