---
layout: "post"
title: "Disable BOMs of a 3D-model in a DWF"
date: "2013-11-15 07:33:00"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/11/disable-boms-of-a-3d-model-in-a-dwf-1.html "
typepad_basename: "disable-boms-of-a-3d-model-in-a-dwf-1"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><strong>Question</strong>:</p>  <p>I'm writing a small tool for Inventor 2012 in VB.net, using the TranslatorAddIn, to export a drawing and its 3D-model to DWF. Unfortunately, when I export the drawing of an assembly, the BOM of the model is included as well, wich I would like to disable. The options &quot;BOM_Structured&quot; and &quot;BOM_Parts_Only&quot; seem to work only if I export the 3D-model, not the drawing...</p>  <p><strong>Solution</strong>:</p>  <p>There is not such option for the DWF translator currently. The workaround is to disable the top assemblyâ€™s BOMs temporarily before exporting the drawing to DWF in this case. The following is a VBA demo. It disables the BOM view of all assemblies in the drawing before exporting to DWF, and restore after exporting.</p>  <p>&#160;</p>  <p><em><font size="2">Public Sub PublishDWFWithoutBOM()        <br />&#160;&#160;&#160; ' Get the DWF translator Add-In.         <br />&#160;&#160;&#160; Dim DWFAddIn As TranslatorAddIn         <br />&#160;&#160;&#160; Set DWFAddIn = ThisApplication.ApplicationAddIns.ItemById(&quot;{0AC6FD95-2F4D-42CE-8BE0-8AEA580399E4}&quot;)</font></em></p>  <p><em><font size="2">&#160;&#160;&#160; 'Set a reference to the active document (the document to be published).        <br />&#160;&#160;&#160; Dim oDocument As DrawingDocument         <br />&#160;&#160;&#160; Set oDocument = ThisApplication.ActiveDocument         <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'disables the BOM view of all assemblies in the drawing before exporting to DWF         <br />&#160;&#160;&#160; Dim oEachRefDoc As Document         <br />&#160;&#160;&#160; For Each oEachRefDoc In oDocument.ReferencedDocuments         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf oEachRefDoc Is AssemblyDocument Then         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oAssDoc As AssemblyDocument         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oAssDoc = oEachRefDoc         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oBOM As BOM         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oBOM = oAssDoc.ComponentDefinition.BOM         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBOM.StructuredViewEnabled = False         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBOM.StructuredViewFirstLevelOnly = False         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBOM.PartsOnlyViewEnabled = False         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oAssDoc.Save         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Next&#160;&#160;&#160; </font></em></p>  <p><em><font size="2">&#160;&#160;&#160; oDocument.Update&#160;&#160;&#160; <br />&#160;&#160;&#160; </font></em></p>  <p><em><font size="2">&#160;&#160;&#160; Dim oContext As TranslationContext        <br />&#160;&#160;&#160; Set oContext = ThisApplication.TransientObjects.CreateTranslationContext         <br />&#160;&#160;&#160; oContext.Type = kFileBrowseIOMechanism</font></em></p>  <p><em><font size="2">&#160;&#160;&#160; ' Create a NameValueMap object        <br />&#160;&#160;&#160; Dim oOptions As NameValueMap         <br />&#160;&#160;&#160; Set oOptions = ThisApplication.TransientObjects.CreateNameValueMap</font></em></p>  <p><em><font size="2">&#160;&#160;&#160; ' Create a DataMedium object        <br />&#160;&#160;&#160; Dim oDataMedium As DataMedium         <br />&#160;&#160;&#160; Set oDataMedium = ThisApplication.TransientObjects.CreateDataMedium</font></em></p>  <p><em><font size="2">&#160;&#160;&#160; ' Check whether the translator has 'SaveCopyAs' options        <br />&#160;&#160;&#160; If DWFAddIn.HasSaveCopyAsOptions(oDocument, oContext, oOptions) Then</font></em></p>  <p><em><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oOptions.Value(&quot;Launch_Viewer&quot;) = 1</font></em></p>  <p><em><font size="2">&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf oDocument Is DrawingDocument Then</font></em></p>  <p><em><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Drawing options        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oOptions.Value(&quot;Publish_Mode&quot;) = kCustomDWFPublish         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oOptions.Value(&quot;Publish_All_Sheets&quot;) = 0</font></em></p>  <p><em><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' The specified sheets will be ignored if        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' the option &quot;Publish_All_Sheets&quot; is True (1)         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSheets As NameValueMap         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSheets = ThisApplication.TransientObjects.CreateNameValueMap</font></em></p>  <p><em><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Publish the first sheet AND its 3D model        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSheet1Options As NameValueMap         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSheet1Options = ThisApplication.TransientObjects.CreateNameValueMap</font></em></p>  <p><em><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSheet1Options.Add &quot;Name&quot;, &quot;Sheet:1&quot;        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSheet1Options.Add &quot;3DModel&quot;, True         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSheets.Value(&quot;Sheet1&quot;) = oSheet1Options         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</font></em></p>  <p><em><font size="2">&#160;&#160;&#160; End If</font></em></p>  <p><em><font size="2">&#160;&#160;&#160; 'Set the destination file name        <br />&#160;&#160;&#160; oDataMedium.FileName = &quot;c:\temp\temptest.dwf&quot;</font></em></p>  <p><em><font size="2">&#160;&#160;&#160; 'Publish document.        <br />&#160;&#160;&#160; Call DWFAddIn.SaveCopyAs(oDocument, oContext, oOptions, oDataMedium)         <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'restore after exporting         <br />&#160;&#160;&#160;&#160; For Each oEachRefDoc In oDocument.ReferencedDocuments         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf oEachRefDoc Is AssemblyDocument Then         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oAssDoc = oEachRefDoc </font></em></p>  <p><em><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oBOM = oAssDoc.ComponentDefinition.BOM         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBOM.StructuredViewEnabled = True         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBOM.StructuredViewFirstLevelOnly = True         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBOM.PartsOnlyViewEnabled = True         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oAssDoc.Save         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Next         <br />&#160;&#160;&#160; <br />End Sub</font></em></p>
