---
layout: "post"
title: "Copying a Body from One Part into Another Part"
date: "2013-09-24 17:41:20"
author: "Adam Nagy"
categories:
  - "Brian Ekins"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/09/copying-a-body-from-one-part-into-another-part.html "
typepad_basename: "copying-a-body-from-one-part-into-another-part"
typepad_status: "Publish"
---

<p>By <a href="http://modthemachine.typepad.com/my_weblog/about-the-author.html">Brian Ekins</a></p>  <p><strong>Question</strong>: The “Associative body copy API Sample” in the API help doesn’t work correctly when creating a non-associative solid copy of a body. The body copy is not positioned correctly.</p>  <p><strong>Answer</strong>:&#160; There’s a problem in Inventor where the transformation defined by an occurrence in the assembly is not being taken into account when a SurfaceBodyProxy is copied.</p>  <p>The following is an updated version of the original sample that has a simpler UI and also takes the issue described above into account.</p>  <div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black">Sub AssociativeBodyCopy()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Set a reference to the active assembly document.</strong></font>     <br />&#160;&#160;&#160; Dim asmDoc As AssemblyDocument     <br />&#160;&#160;&#160; Set asmDoc = ThisApplication.ActiveDocument     <br />&#160;&#160;&#160; Dim asmDef As AssemblyComponentDefinition     <br />&#160;&#160;&#160; Set asmDef = asmDoc.ComponentDefinition     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Select the body to copy.&#160; This will be a proxy since it's        <br />&#160;&#160;&#160; ' being selected in the context of the assembly.         <br /></strong></font>&#160;&#160;&#160; Dim sourceBody As SurfaceBodyProxy     <br />&#160;&#160;&#160; Set sourceBody = ThisApplication.CommandManager.Pick( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kPartBodyFilter, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Select a body to copy.&quot;)     <br />&#160;&#160;&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the occurrence to create the new body within.        <br /></strong></font>&#160;&#160;&#160; Dim targetOcc As ComponentOccurrence     <br />&#160;&#160;&#160; Set targetOcc = ThisApplication.CommandManager.Pick( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kAssemblyLeafOccurrenceFilter, _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Select an occurrence to copy the body into.&quot;)     <br />&#160;&#160;&#160; Dim targetDef As PartComponentDefinition     <br />&#160;&#160;&#160; Set targetDef = targetOcc.Definition     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Create a base feature definition.&#160; This is used to define the        <br />&#160;&#160;&#160; ' various inputs needed to create a base feature.         <br /></strong></font>&#160;&#160;&#160; Dim nonPrmFeatures As NonParametricBaseFeatures     <br />&#160;&#160;&#160; Set nonPrmFeatures = targetDef.Features.NonParametricBaseFeatures     <br />&#160;&#160;&#160; Dim featureDef As NonParametricBaseFeatureDefinition     <br />&#160;&#160;&#160; Set featureDef = nonPrmFeatures.CreateDefinition&#160; <br />&#160;&#160;&#160; Dim transObjs As TransientObjects&#160; <br />&#160;&#160;&#160; Set transObjs = ThisApplication.TransientObjects&#160; <br />&#160;&#160;&#160; Dim col As ObjectCollection     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Ask if an associative or non-associative copy should be made.        <br /></strong></font>&#160;&#160;&#160; Dim answer As VbMsgBoxResult     <br />&#160;&#160;&#160; answer = MsgBox(&quot;Choose the type of copy to create.&quot; &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vbCrLf &amp; vbCrLf &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;&#160;&#160; Yes - Associative surface&quot; &amp; vbCrLf &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;&#160;&#160; No - Non-associative solid&quot;, vbYesNoCancel)</div>  <div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black">&#160;&#160;&#160; If answer = vbYes Then    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Define the geometry to be copied.&#160; In this case,        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' it's the selected body.         <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set col = transObjs.CreateObjectCollection     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; col.Add sourceBody     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' This creates an associative copy of the model.&#160; To        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' create an associative copy inventor only supports creating         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' a surface of composite result, not a solid.         <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.BRepEntities = col     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.OutputType = kSurfaceOutputType     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.TargetOccurrence = targetOcc     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.IsAssociative = True     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim baseFeature As NonParametricBaseFeature     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set baseFeature = nonPrmFeatures.AddByDefinition(featureDef)     <br />&#160;&#160;&#160; ElseIf answer = vbNo Then     <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' The selected body is a body proxy in the context of&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' the assembly. However, there's a problem with the</strong></font></div>  <div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black"><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' TransientBrep.Copy method and it creates a copy of the        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' body that ignores the transorm.&#160; The code below creates         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' the copy and then performs an extra step to apply the         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' transform.         <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim newBody As SurfaceBody     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set newBody = ThisApplication.TransientBRep.Copy(sourceBody)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call ThisApplication.TransientBRep.Transform(newBody, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sourceBody.ContainingOccurrence.Transformation)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Transform the body into the parts space of the        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' target occurrence.         <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim trans As Matrix     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set trans = targetOcc.Transformation     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Invert     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call ThisApplication.TransientBRep.Transform(newBody, trans)&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set col = transObjs.CreateObjectCollection     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; col.Add newBody     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' This creates an non-associative copy that is a solid.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.BRepEntities = col&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.OutputType = kSolidOutputType     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.TargetOccurrence = targetOcc     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; featureDef.IsAssociative = False     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set baseFeature = nonPrmFeatures.AddByDefinition(featureDef)     <br />&#160;&#160;&#160; End If     <br />End Sub</div>
