---
layout: "post"
title: "Inventor API: Change the color of a selected face in an assembly document"
date: "2013-07-22 01:29:08"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/07/inventor-api-change-the-color-of-a-selected-face-in-an-assembly-document.html "
typepad_basename: "inventor-api-change-the-color-of-a-selected-face-in-an-assembly-document"
typepad_status: "Publish"
---

<p>Q:&#160; How can I change the color of the face by selecting a face object from an assembly document?</p>  <p><a name="section2"></a>A:&#160; In an assembly document you should use the NativeObject of a face proxy object to obtain the original occurrence. By modifying the NativeObject's color property you can modify the color of the face in the assembly.</p>  <p>Selecting face in an assembly context you really get FaceProxy object of this face. You need to use NativeObject property of this face proxy object to get reference to the original face. Then you are able to modify face color.</p>  <p>The following VBA example demonstrates how this is done.</p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">Sub test()          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Dim oSelectSet As SelectSet           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Set oSelectSet = ThisApplication.ActiveDocument.SelectSet           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>On Error Resume Next           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>If oSelectSet.count &lt;&gt; 1 Then           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>Exit Sub           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>End If           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>' check if it's a face           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Dim oFaceProxy As FaceProxy           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Set oFaceProxy = oSelectSet.Item(1)           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>If oFaceProxy Is Nothing Then           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>Exit Sub           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>End If           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>On Error GoTo 0           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>' get the native object, which resides in the definition of the occurrence           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Dim oFace As Face           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Set oFace = oFaceProxy.NativeObject           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>' get the document where the face belongs           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Dim oDoc As Document           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Set oDoc = oFace.Parent.ComponentDefinition.Document           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>          <br />' NOTE: make sure that the style &quot;myColor&quot; already</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">' exists in the document where the face belongs          <br />' if it does not exist yet then this call will fail</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><span style="mso-spacerun: yes"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; </font></span><font style="font-size: 10pt" color="#000000">Dim oStyle As RenderStyle          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Set oStyle = oDoc.RenderStyles.Item(&quot;myColor&quot;) 'your customized color           <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>          <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>Call oFace.SetRenderStyle(kOverrideRenderStyle, oStyle)           <br />End Sub</font></font></span></p>  <p>&#160;</p> by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a>
