---
layout: "post"
title: "Inventor API: Create constraints for 3D Sketch"
date: "2013-07-30 01:48:37"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/07/inventor-api-create-constraints-for-3d-sketch.html "
typepad_basename: "inventor-api-create-constraints-for-3d-sketch"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a></p>  <p><b>Q: </b>I need an example of creating constraints for Sketch3D entities, and I also need to control these entities through parameters. How can this be done using the API? </p>  <p><a name="section2"></a><b>A: </b>Constraints and dimensions of Sketch3D are similar to those of Sketch 2D. Here is a VBA example. The code will add a new Sketch3D object to an existing Part, then create two lines, add a parallel constraint between them and finally add a length constraint to one of the lines. You can then use the parameter of the length constraint to drive programmatically the dimension of the constrained line.</p>  <p>Note: a part document needs to be the active.</p>  <p>&#160;</p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 9pt" color="#000000">Sub AddSketch3DConstraints()</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160;</font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oDoc As PartDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oDoc = ThisApplication.ActiveDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oCompDef As PartComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oCompDef = oDoc.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Add a new Sketch3D</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oSketch3d As Sketch3D</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oSketch3d = oCompDef.Sketches3D.Add</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oTG As TransientGeometry</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oTG = ThisApplication.TransientGeometry</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Add two lines to the sketch</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oLine1 As SketchLine3D</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oLine2 As SketchLine3D</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oLine1 = oSketch3d.SketchLines3D _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">.AddByTwoPoints(oTG.CreatePoint(0, 0, 0), _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 9pt">oTG.CreatePoint(10, 10, 10))</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oLine2 = oSketch3d.SketchLines3D _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">.AddByTwoPoints(oTG.CreatePoint(0, 10, 0), _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 9pt">oTG.CreatePoint(10, 15, 15))</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">' Create a parallel constraint between the lines</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oParallelConstr3D<span style="mso-spacerun: yes">&#160;&#160; </span>As ParallelConstraint3D</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oParallelConstr3D = oSketch3d _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">.GeometricConstraints3D.AddParallel(oLine1, oLine2)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">' Create length constraint for line 1</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oLineLengthConstr3D As LineLengthDimConstraint3D</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oLineLengthConstr3D = oSketch3d _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">.DimensionConstraints3D.AddLineLength(oLine1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">' Set Driven Property to False so we are sure</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">' Parameter is a ModelParameter</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">oLineLengthConstr3D.Driven = False</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oModelParam As ModelParameter</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oModelParam = oLineLengthConstr3D.Parameter</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'set new value in base units (cm)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">oModelParam.value = 15#</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 9pt" color="#000000">End Sub</font></font></span></p>
