---
layout: "post"
title: "Save extra data in Inventor file &ndash; 1"
date: "2013-03-01 02:01:05"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/03/save-extra-data-in-inventor-file-1.html "
typepad_basename: "save-extra-data-in-inventor-file-1"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>There are three different mechanisms that allow you to store information in a file that is not directly accessible by the end user.    <br />1. iProperties     <br />2. Attribute     <br />3. IStorage &amp; IStream </p>  <p>The first of these and probably the simplest to use are document properties. iProperties is at document level for all kinds of document. There are the standard properties that are visible to the user through the iProperties command (dialog), but you can also create your own property sets and properties. These are not visible through Inventor's user interface.</p>  <p>Many materials are available for iProperties. Iâ€™d recommend&#160; one blog and one video course. </p>  <p><a href="http://modthemachine.typepad.com/my_weblog/2010/02/accessing-iproperties.html">Access IProperty</a>     <br /><a href="http://download.autodesk.com/media/adn/Autodesk_Inventor_API_Module2_Common_Document_Functionality_11March10.zip">Introductory Inventor API_Module 2 - Document</a></p>  <p>iProperties is accessible (read/write) by Inventor API or Apprentice.Following is a small sample which adds a custom property set with some properties. It also shows how to read the information.</p>  <p><strong>VBA</strong></p>  <p><font size="1">Sub AddCustomProperty() </font></p>  <p><font size="1">&#160;&#160;&#160; ' open a document invisble      <br />&#160;&#160;&#160; Dim oDoc As Document       <br />&#160;&#160;&#160; Set oDoc = ThisApplication.Documents.Open(&quot;c:\testpart.ipt&quot;, False)       <br />      <br />&#160;&#160;&#160; ' name of new property set       <br />&#160;&#160;&#160; Dim oNameOfNewPS As String       <br />&#160;&#160;&#160; oNameOfNewPS = &quot;myNewSet&quot;       <br />&#160;&#160;&#160; ' new property set       <br />&#160;&#160;&#160; Dim oNewPS As PropertySet       <br />&#160;&#160;&#160; If oDoc.PropertySets.PropertySetExists(&quot;myNewSet&quot;) Then       <br />&#160;&#160;&#160;&#160;&#160;&#160; ' if the set exists aleady       <br />&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPS = oDoc.PropertySets(&quot;myNewSet&quot;)       <br />&#160;&#160;&#160;&#160;&#160;&#160; ' you can clean up the existing properties       <br />&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' add a new one with a GUID       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPS = oDoc.PropertySets.Add(&quot;myNewSet&quot;,       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;{3FDB7763-80DB-4269-83E4-7F43BC8E9EA7}&quot;)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</font></p> <font size="1">   <p>     <br />&#160;&#160;&#160; 'the values of the properties       <br />&#160;&#160;&#160; Dim oIntProV As Integer       <br />&#160;&#160;&#160; oIntProV = 100       <br />&#160;&#160;&#160; Dim oBoolProV As Boolean       <br />&#160;&#160;&#160; oBoolProV = False       <br />&#160;&#160;&#160; Dim oDoubleProV As Double       <br />&#160;&#160;&#160; oDoubleProV = 3.1415926       <br />&#160;&#160;&#160; Dim oDateProV As Date       <br />&#160;&#160;&#160; oDateProV = &quot;2013-3-1 15:25&quot;       <br />      <br />&#160;&#160;&#160; ' add these properties with the meaningful name       <br />&#160;&#160;&#160; ' assume they do not exist in the property set       <br />&#160;&#160;&#160; Call oNewPS.Add(oIntProV, &quot;ModelCount&quot;)       <br />&#160;&#160;&#160; Call oNewPS.Add(oBoolProV, &quot;ModelUpdateToDate&quot;)       <br />&#160;&#160;&#160; Call oNewPS.Add(oDoubleProV, &quot;ModelBasicLength&quot;)       <br />&#160;&#160;&#160; Call oNewPS.Add(oDateProV, &quot;ModelUpdateDate&quot;)       <br />&#160;&#160;&#160; oDoc.Save       <br />&#160;&#160;&#160; oDoc.Close       <br />End Sub </p> </font>  <p><font size="1">Sub ReadCustomProperty() </font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160; ' open a document invisble      <br />&#160;&#160;&#160; Dim oDoc As Document       <br />&#160;&#160;&#160; Set oDoc = ThisApplication.Documents.Open(&quot;c:\testpart.ipt&quot;, False)       <br />&#160;&#160;&#160; ' name of new property set       <br />&#160;&#160;&#160; Dim oNameOfNewPS As String       <br />&#160;&#160;&#160; oNameOfNewPS = &quot;myNewSet&quot;       <br />&#160;&#160;&#160; ' new property set       <br />&#160;&#160;&#160; Dim oNewPS As PropertySet       <br />&#160;&#160;&#160; If oDoc.PropertySets.PropertySetExists(&quot;myNewSet&quot;) Then       <br />&#160;&#160;&#160;&#160;&#160;&#160; ' if the set exists aleady       <br />&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPS = oDoc.PropertySets(&quot;myNewSet&quot;)       <br />&#160;&#160;&#160;&#160;&#160;&#160; ' you can clean up the existing properties       <br />&#160;&#160;&#160; Else&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;no property named myNewSet&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; Dim oShowStr As String       <br />&#160;&#160;&#160; oShowStr = &quot;&quot;       <br />      <br />&#160;&#160;&#160; 'iterate the properties       <br />&#160;&#160;&#160; Dim oEachP As Property       <br />&#160;&#160;&#160; For Each oEachP In oNewPS       <br />&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; &quot; [Property Name]&#160; &quot; &amp; oEachP.Name       <br />&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; &quot; [Property Value]&#160; &quot; &amp; oEachP.Value &amp; vbCr       <br />&#160;&#160;&#160; Next       <br />&#160;&#160;&#160; MsgBox oShowStr       <br />&#160;&#160;&#160; oDoc.Close       <br />End Sub</font></p>  <p><strong>VB.NET</strong></p>  <div style="font-family: courier new; background: white; color: black; font-size: 9pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> AddCustomProperty()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_inventorApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">Nothing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime.InteropServices.</span><span style="line-height: 140%; color: #2b91af">Marshal</span><span style="line-height: 140%">.GetActiveObject(</span><span style="line-height: 140%; color: #a31515">&quot;Inventor.Application&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document invisble</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_inventorApp.Documents.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: blue">False</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PropertySet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.PropertySets.PropertySetExists(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">) </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.PropertySets(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' add a new one with a GUID</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.PropertySets.Add(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;{3FDB7763-80DB-4269-83E4-7F43BC8E9EA7}&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160; </p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'the values of the properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oIntProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Integer</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oIntProV = 100</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oBoolProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Boolean</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBoolProV = </span><span style="line-height: 140%; color: blue">False</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoubleProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoubleProV = 3.1415926000000001</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDateProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Date</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDateProV = </span><span style="line-height: 140%; color: #a31515">&quot;2013-3-1 15:25&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160; ' add these properties with the meaningful name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' assume they do not exist in the property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oIntProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelCount&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oBoolProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelUpdateToDate&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oDoubleProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelBasicLength&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oDateProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelUpdateDate&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Save()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Close()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> ReadCustomProperty()</span>&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_inventorApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Inventor.</span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">Nothing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime.InteropServices.</span><span style="line-height: 140%; color: #2b91af">Marshal</span><span style="line-height: 140%">.        <br />GetActiveObject(</span><span style="line-height: 140%; color: #a31515">&quot;Inventor.Application&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document invisble</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_inventorApp.Documents.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: blue">False</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PropertySet</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">Nothing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.PropertySets.PropertySetExists(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">) </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.PropertySets(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;no property named myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Exit Sub</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oShowStr </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'iterate the properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oEachP </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">[Property]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> oEachP </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> oNewPS</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr &amp;= </span><span style="line-height: 140%; color: #a31515">&quot; [Property Name]&#160; &quot;</span><span style="line-height: 140%"> &amp;        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEachP.Name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr &amp;= </span><span style="line-height: 140%; color: #a31515">&quot; [Property Value]&#160; &quot;</span><span style="line-height: 140%"> &amp;        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEachP.Value &amp; vbCr</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next        <br />        <br /></span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">MessageBox</span><span style="line-height: 140%">.Show(oShowStr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Close()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>  <p><strong>Apprentice</strong> </p>  <div style="font-family: courier new; background: white; color: black; font-size: 9pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> AddCustomProperty_Apprentice()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_ApprenticeApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%"> =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">New</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%">()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ApprenticeServerDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_ApprenticeApp.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PropertySet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.PropertySets.PropertySetExists(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">) </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.PropertySets(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' add a new one with a GUID</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.PropertySets.Add(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;{3FDB7763-80DB-4269-83E4-7F43BC8E9EA7}&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'the values of the properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oIntProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Integer</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oIntProV = 100</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oBoolProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Boolean</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBoolProV = </span><span style="line-height: 140%; color: blue">False</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoubleProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoubleProV = 3.1415926000000001</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDateProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Date</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDateProV = </span><span style="line-height: 140%; color: #a31515">&quot;2013-3-1 15:25&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">' add these properties with the meaningful name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' assume they do not exist in the property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oIntProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelCount&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oBoolProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelUpdateToDate&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oDoubleProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelBasicLength&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS.Add(oDateProV, </span><span style="line-height: 140%; color: #a31515">&quot;ModelUpdateDate&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' flush the modification. Apprentice requires</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.PropertySets.FlushToFile()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_ApprenticeApp.FileSaveAs.AddFileToSave(oDoc, oDoc.FullDocumentName)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_ApprenticeApp.FileSaveAs.ExecuteSave()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> ReadCustomProperty_Apprentice()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_ApprenticeApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%"> =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">New</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%">()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document invisble</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ApprenticeServerDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_ApprenticeApp.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new property set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PropertySet</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">Nothing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.PropertySets.PropertySetExists(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">) </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.PropertySets(</span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;no property named myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Exit Sub</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oShowStr </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'iterate the properties</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oEachP </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">[Property]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> oEachP </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> oNewPS</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr &amp;= </span><span style="line-height: 140%; color: #a31515">&quot; [Property Name]&#160; &quot;</span><span style="line-height: 140%"> &amp;        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEachP.Name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr &amp;= </span><span style="line-height: 140%; color: #a31515">&quot; [Property Value]&#160; &quot;</span><span style="line-height: 140%"> &amp;        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEachP.Value &amp; vbCr</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">MessageBox</span><span style="line-height: 140%">.Show(oShowStr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Close()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>  <p>&#160;</p>  <p>In the next post, we will introduce the second way: Attribute.   </p>
