---
layout: "post"
title: "&quot;Edit&quot; a feature in a part using API"
date: "2013-01-22 11:08:12"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/01/edit-a-feature-in-a-part-using-api.html "
typepad_basename: "edit-a-feature-in-a-part-using-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>Each Feature has a method called SetEndOfPart which takes boolean as argument. If you want to &quot;Edit&quot; a particular feature, first you need to call SetEndOfPart(true). This moves the &quot;Part End Marker&quot; to above this feature. After this do the necessary changes in the feature you were looking for. After this do not forget to move the &quot;Part End Marker&quot; to the end of this feature by calling SetEndOfPart (False).</p>  <p>The code below changes the workplane of a hole feature in the attached part.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> ChangeOfFace()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oDef </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">PartComponentDefinition</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oDef = m_inventorApplication.ActiveDocument.ComponentDefinition</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Get the hole feature</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oHoleFeat </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">HoleFeature</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oHoleFeat = oDef.Features.HoleFeatures.Item(1)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Move the EndofPart position before Hole feature</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; oHoleFeat.SetEndOfPart(</font></font><font style="font-size: 8pt"><span><font color="#0000ff">True</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> oWorkplane </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#2b91af">WorkPlane</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Change the workplane</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oWorkplane = oDef.WorkPlanes.Item(5)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'?Set it to hole feature</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; oHoleFeat.SetToFaceExtent(oWorkplane, </font></font><font style="font-size: 8pt"><span><font color="#0000ff">True</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Move Back the EndofPart position after last feature</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; oDef.Features.Item(oDef.Features.Count).SetEndOfPart(</font></font><font style="font-size: 8pt"><span><font color="#0000ff">False</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Sub</font></span></font></p> </div>
