---
layout: "post"
title: "Writing Inventor API code that modifies multiple BRep entities"
date: "2013-05-22 00:35:42"
author: "Philippe Leefsma"
categories:
  - "Inventor"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/05/writing-inventor-api-code-that-modifies-multiple-brep-entities.html "
typepad_basename: "writing-inventor-api-code-that-modifies-multiple-brep-entities"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p>  <p>I was dealing with a support case recently where the developer was noticing an unexpected behavior: he was selecting multiple faces and his code was iterating through the SelectSet to create multiple MoveFaceFeatures one after the other. The first feature was created successfully, but the subsequent ones will fail.</p>  <p>There are two reasons why such an approach will fail:</p>  <p>1/ The content of the SelectSet will be cleared after each transacting operation, such as a feature creation, so you should store each selected entity in a collection or your custom data structure if the rest of your code is going to perform transaction, directly or as a result of invoking an API method.</p>  <p>2/ After any operation that is going to modify the BRep, you should assume that any pointer to BRep entities isn’t valid anymore, even if the modification was not involving precisely those entities (Faces, Edges and so on…). The correct approach for that scenario is to store ReferenceKeys of the selected entities prior to do any modification to the BRep and use those later when you need to process the entity.</p>  <p>Here is a VBA sample that illustrates the approach. It assumes the user has selected several faces from the UI and will create MoveFaceFeature for each of them:</p>  <p style="line-height: normal; margin: 0in 0in 0pt"><i><span style="font-family: "><font face="Verdana"><font color="#000000">Sub CreateMoveFace()           <br />            <br />&#160;&#160;&#160; Dim oPart As PartDocument            <br />&#160;&#160;&#160; Set oPart = ThisApplication.ActiveDocument            <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oDef As PartComponentDefinition            <br />&#160;&#160;&#160; Set oDef = oPart.ComponentDefinition            <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oFace As face, colFaces As FaceCollection            <br />&#160;&#160;&#160; Dim oMFD As MoveFaceDefinition, oMF As MoveFaceFeature            <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; ' Get the reference keys for the selected faces.            <br />&#160;&#160;&#160; Dim keyContext As Long            <br />&#160;&#160;&#160; keyContext = oPart.ReferenceKeyManager.CreateKeyContext            <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim keyCollection As New collection            <br />&#160;&#160;&#160; For Each oFace In oPart.SelectSet            <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim key() As Byte            <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oFace.GetReferenceKey(key, keyContext)            <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call keyCollection.Add(key)            <br />&#160;&#160;&#160; Next            <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim tempKey As Variant            <br />&#160;&#160;&#160; For Each tempKey In keyCollection</font></font></span></i></p>  <p style="line-height: normal; margin: 0in 0in 0pt"><i><span style="font-family: "><font face="Verdana"><font color="#000000">           <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; key = tempKey            <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oFace = oPart.ReferenceKeyManager.BindKeyToObject( _</font></font></span></i></p>  <p style="line-height: normal; margin: 0in 0in 0pt"><i><span style="font-family: "><font face="Verdana"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; key, keyContext)</font></font></span></i></p>  <p style="line-height: normal; margin: 0in 0in 0pt"><i><span style="font-family: "><font face="Verdana"><font color="#000000">           <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set colFaces =&#160; _</font></font></span></i></p>  <p style="line-height: normal; margin: 0in 0in 0pt"><i><span style="font-family: "><font face="Verdana"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.TransientObjects.CreateFaceCollection</font></font></span></i></p> <i><span style="font-family: "><font face="Verdana"><font color="#000000">         <p style="line-height: normal; margin: 0in 0in 0pt">           <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call colFaces.Add(oFace)</p>          <p style="line-height: normal; margin: 0in 0in 0pt">           <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMFD = oDef.Features.MoveFaceFeatures.CreateDefinition( _</p>       </font></font></span></i>  <p style="line-height: normal; margin: 0in 0in 0pt"><i><span style="font-family: "><font face="Verdana"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; colFaces)</font></font></span></i></p> <i><span style="font-family: "><font face="Verdana"><font color="#000000">         <p style="line-height: normal; margin: 0in 0in 0pt">           <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oMFD.SetDirectionAndDistanceMoveType(0.1, oFace)</p>          <p style="line-height: normal; margin: 0in 0in 0pt">           <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMF = oDef.Features.MoveFaceFeatures.Add(oMFD)</p>          <p style="line-height: normal; margin: 0in 0in 0pt">           <br />&#160;&#160;&#160; Next</p>       </font></font></span></i>  <p style="line-height: normal; margin: 0in 0in 0pt"><i><span style="font-family: "><font face="Verdana"><font color="#000000">           <br />End Sub</font></font></span></i></p>
