---
layout: "post"
title: "Save extra data in Inventor file &ndash; 2"
date: "2013-03-03 22:52:31"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/03/save-extra-data-in-inventor-file-2.html "
typepad_basename: "save-extra-data-in-inventor-file-2"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The second mechanism is attributes. Attributes allow you to attach    <br />information to a specific object. Attributes can be associated with the Document object so you can use this to store general information associated with the document.</p>  <p>Attributes has been widely introduced in various articles. I’d recommend:</p>  <p>- API help reference &gt;&gt; [Attributes] </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017ee8eaa758970d-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_6346a0.jpg" width="312" height="203" /></a>&#160; </p>  <p>- Introduction to Attributes on Brian’s blog</p>  <p><a title="http://modthemachine.typepad.com/my_weblog/2009/07/introduction-to-attributes.html" href="http://modthemachine.typepad.com/my_weblog/2009/07/introduction-to-attributes.html">http://modthemachine.typepad.com/my_weblog/2009/07/introduction-to-attributes.html</a></p>  <p>In short:</p>  <p><strong>Creating AttributeSet and Attributes</strong></p>  <p>- From AttributeSets Collection add a new AttributeSet : </p>  <p>Public Function Add(    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal AttributeSetName As String,&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Optional ByVal CopyWithOwner As Boolean = False )     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; As AttributeSet </p>  <p>- From AttributeSet Collection add a new Attribute: </p>  <p>Public Function Add(    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal AttributeName As String,     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal ValueType As ValueTypeEnum,     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal Value As Variant ) As Attribute </p>  <p>ValueTypeEnum:&#160; <br />&#160;&#160;&#160; kIntegerType     <br />&#160;&#160;&#160; kDoubleType     <br />&#160;&#160;&#160; kStringType     <br />&#160;&#160;&#160; kByteArrayType     <br />&#160;&#160;&#160; kBooleanType</p>  <p><strong>Querying Attributes      <br /></strong>AttributeManager supports different methods to query for attributes.     <br />Can query based on attribute set name, attribute name, and/or attribute value. </p>  <p>&#160;&#160; FindAttributes    <br />&#160;&#160; FindAttributeSets     <br />&#160;&#160; FindObjects </p>  <p>e.g.    <br />Public Function FindObjects(     <br />&#160;&#160;&#160; Optional ByVal AttributeSetName As String = &quot;*&quot;,&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Optional ByVal AttributeName As String = &quot;*&quot;,&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; Optional ByVal AttributeValue As Variant ) As ObjectCollection</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017ee8eaa7a3970d-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_7c4875.jpg" width="244" height="102" /></a> </p>  <p>&#160;</p>  <p>Similar to the first <a href="http://adndevblog.typepad.com/manufacturing/2013/03/save-extra-data-in-inventor-file-1.html">post</a>, In this post, we write a small demo to add a custom attribute set with some attributes. It also shows how to read the information.</p>  <p><strong>VBA</strong></p>  <p><font size="1">Sub AddCustomAttribute() </font></p>  <p><font size="1">&#160;&#160;&#160; ' open a document invisible      <br />&#160;&#160;&#160; Dim oDoc As Document       <br />&#160;&#160;&#160;&#160; Set oDoc = ThisApplication.Documents.Open(&quot;c:\testpart.ipt&quot;, False)</font></p>  <p><font size="1">&#160;&#160;&#160; ' name of new attribute set      <br />&#160;&#160;&#160; Dim oNameOfNewPS As String       <br />&#160;&#160;&#160; oNameOfNewPS = &quot;myNewSet&quot;       <br />&#160;&#160;&#160; ' new attribute set       <br />&#160;&#160;&#160; Dim oNewPS As AttributeSet       <br />&#160;&#160;&#160; If oDoc.AttributeManager.FindAttributeSets(oNameOfNewPS).Count &gt; 0 Then       <br />&#160;&#160;&#160;&#160;&#160;&#160; ' if the set exists aleady       <br />&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPS = oDoc.AttributeSets(oNameOfNewPS)       <br />&#160;&#160;&#160;&#160;&#160;&#160; ' you can clean up the existing attributes       <br />&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' add a new one       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPS = oDoc.AttributeSets.Add(oNameOfNewPS)       <br />&#160;&#160;&#160;&#160; End If </font></p>  <p><font size="1">&#160;&#160;&#160; 'the values of the attributes      <br />&#160;&#160;&#160; Dim oIntProV As Integer       <br />&#160;&#160;&#160; oIntProV = 100       <br />&#160;&#160;&#160; Dim oByteProV() As Byte       <br />&#160;&#160;&#160; oByteProV = StrConv(&quot;ABCDEFG&quot;, vbFromUnicode)       <br />&#160;&#160;&#160;&#160; Dim oDoubleProV As Double       <br />&#160;&#160;&#160; oDoubleProV = 3.1415926       <br />&#160;&#160;&#160; Dim oDateProV As String       <br />&#160;&#160;&#160; oDateProV = &quot;2013-3-1 15:25&quot; </font></p>  <p><font size="1">&#160;&#160;&#160; ' add these attributes with the meaningful name      <br />&#160;&#160;&#160; ' assume they do not exist in the attribute set       <br />&#160;&#160;&#160; Call oNewPS.Add(&quot;ModelCount&quot;, kIntegerType, oIntProV)       <br />&#160;&#160;&#160; Call oNewPS.Add(&quot;ModelByte&quot;, kByteArrayType, oByteProV)       <br />&#160;&#160;&#160; Call oNewPS.Add(&quot;ModelBasicLength&quot;, kDoubleType, oDoubleProV)       <br />&#160;&#160;&#160; Call oNewPS.Add(&quot;ModelUpdateDate&quot;, kStringType, oDateProV)       <br />&#160;&#160;&#160; oDoc.Save       <br />&#160;&#160;&#160; oDoc.Close       <br />End Sub </font></p>  <p><font size="1">Sub ReadCustomAttribute() </font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160; ' open a document invisible      <br />&#160;&#160;&#160; Dim oDoc As Document       <br />&#160;&#160;&#160; Set oDoc = ThisApplication.Documents.Open(&quot;c:\testpart.ipt&quot;, False)       <br />&#160;&#160;&#160; ' name of new attribute set       <br />&#160;&#160;&#160; Dim oNameOfNewPS As String       <br />&#160;&#160;&#160; oNameOfNewPS = &quot;myNewSet&quot;       <br />&#160;&#160;&#160; ' new attribute set       <br />&#160;&#160;&#160; Dim oNewPS As AttributeSet       <br />&#160;&#160;&#160; If oDoc.AttributeManager.FindAttributeSets(oNameOfNewPS).Count &gt; 0 Then       <br />&#160;&#160;&#160;&#160;&#160;&#160; ' if the set exists aleady       <br />&#160;&#160;&#160;&#160;&#160;&#160; Set oNewPS = oDoc.AttributeSets(oNameOfNewPS)       <br />&#160;&#160;&#160;&#160;&#160; ' you can clean up the existing attributes       <br />&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;no attribute set named myNewSet&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; Dim oShowStr As String       <br />&#160;&#160;&#160; oShowStr = &quot;&quot; </font></p>  <p><font size="1">&#160;&#160;&#160; 'iterate the attributes      <br />&#160;&#160;&#160; Dim oEachAtt As Attribute       <br />&#160;&#160;&#160; For Each oEachAtt In oNewPS       <br />&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; &quot; [Attribute Name]&#160; &quot; &amp; oEachAtt.Name       <br />&#160;&#160;&#160;&#160;&#160;&#160; If oEachAtt.Name = &quot;ModelByte&quot; Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; &quot; [Attribute Value]&#160; &quot; &amp; StrConv(oEachAtt.Value, vbUnicode) &amp; vbCr       <br />&#160;&#160;&#160;&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; &quot; [Attribute Value]&#160; &quot; &amp; oEachAtt.Value &amp; vbCr       <br />&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; Next       <br />&#160;&#160;&#160; MsgBox oShowStr       <br />&#160;&#160;&#160; oDoc.Close       <br />End Sub</font></p>  <p></p>  <p></p>  <p><strong>VB.NET</strong></p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> AddCustomAttribute()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_inventorApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">Nothing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime.InteropServices.</span><span style="line-height: 140%; color: #2b91af">Marshal</span><span style="line-height: 140%">.GetActiveObject(</span><span style="line-height: 140%; color: #a31515">&quot;Inventor.Application&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document invisible</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_inventorApp.Documents.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: blue">False</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AttributeSet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.AttributeManager.FindAttributeSets(oNameOfNewPS).Count &gt; 0 </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.AttributeSets(oNameOfNewPS)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' add a new one</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.AttributeSets.Add(oNameOfNewPS)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'the values of the attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oIntProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Integer</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oIntProV = 100</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oByteProV() </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Byte</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oByteProV = System.Text.</span><span style="line-height: 140%; color: #2b91af">Encoding</span><span style="line-height: 140%">.Default.GetBytes(</span><span style="line-height: 140%; color: #a31515">&quot;ABCDEFG&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoubleProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoubleProV = 3.1415926</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDateProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDateProV = </span><span style="line-height: 140%; color: #a31515">&quot;2013-3-1 15:25&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' add these attributes with the meaningful name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' assume they do not exist in the attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelCount&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kIntegerType, oIntProV)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelByte&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kByteArrayType, oByteProV)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelBasicLength&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kDoubleType, oDoubleProV)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelUpdateDate&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kStringType, oDateProV)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Save()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Close()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> ReadCustomAttribute()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_inventorApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">Nothing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime.InteropServices.</span><span style="line-height: 140%; color: #2b91af">Marshal</span><span style="line-height: 140%">.GetActiveObject(</span><span style="line-height: 140%; color: #a31515">&quot;Inventor.Application&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document invisible</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_inventorApp.Documents.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: blue">False</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AttributeSet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.AttributeManager.FindAttributeSets(oNameOfNewPS).Count &gt; 0 </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.AttributeSets(oNameOfNewPS)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;no attribute set named myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Exit Sub</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oShowStr </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'iterate the attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oEachAtt </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Attribute</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> oEachAtt </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> oNewPS</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; </span><span style="line-height: 140%; color: #a31515">&quot; [Attribute Name]&#160; &quot;</span><span style="line-height: 140%"> &amp; oEachAtt.Name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oEachAtt.Name = </span><span style="line-height: 140%; color: #a31515">&quot;ModelByte&quot;</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; </span><span style="line-height: 140%; color: #a31515">&quot; [Attribute Value]&#160; &quot;</span><span style="line-height: 140%"> &amp; System.Text.</span><span style="line-height: 140%; color: #2b91af">Encoding</span><span style="line-height: 140%">.Default.GetString(oEachAtt.Value) &amp; vbCr</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; </span><span style="line-height: 140%; color: #a31515">&quot; [Attribute Value]&#160; &quot;</span><span style="line-height: 140%"> &amp; oEachAtt.Value &amp; vbCr</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">MessageBox</span><span style="line-height: 140%">.Show(oShowStr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Close()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub        <br />        <br /></span></p>    <p style="margin: 0px"></p> </div> <strong>Apprentice</strong>   <br />  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> AddCustomAttribute_Apprentice()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_ApprenticeApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%"> =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">New</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%">()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document invisble</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ApprenticeServerDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_ApprenticeApp.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AttributeSet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.AttributeManager.FindAttributeSets(oNameOfNewPS).Count &gt; 0 </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.AttributeSets(oNameOfNewPS)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' add a new one</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.AttributeSets.Add(oNameOfNewPS)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'the values of the attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oIntProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Integer</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oIntProV = 100</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oByteProV() </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Byte</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oByteProV = System.Text.</span><span style="line-height: 140%; color: #2b91af">Encoding</span><span style="line-height: 140%">.Default.GetBytes(</span><span style="line-height: 140%; color: #a31515">&quot;ABCDEFG&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoubleProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Double</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoubleProV = 3.1415926</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDateProV </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDateProV = </span><span style="line-height: 140%; color: #a31515">&quot;2013-3-1 15:25&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' add these attributes with the meaningful name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' assume they do not exist in the attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelCount&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kIntegerType, oIntProV)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelByte&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kByteArrayType, oByteProV)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelBasicLength&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kDoubleType, oDoubleProV)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oNewPS.Add(</span><span style="line-height: 140%; color: #a31515">&quot;ModelUpdateDate&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">ValueTypeEnum</span><span style="line-height: 140%">.kStringType, oDateProV)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_ApprenticeApp.FileSaveAs.AddFileToSave(oDoc, oDoc.FullDocumentName)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_ApprenticeApp.FileSaveAs.ExecuteSave()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> ReadCustomAttribute_Apprentice()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> m_ApprenticeApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%"> =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">New</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">ApprenticeServerComponent</span><span style="line-height: 140%">()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document invisble</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' open a document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ApprenticeServerDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc = m_ApprenticeApp.Open(</span><span style="line-height: 140%; color: #a31515">&quot;c:\testpart.ipt&quot;</span><span style="line-height: 140%">) </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' name of new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNameOfNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNameOfNewPS = </span><span style="line-height: 140%; color: #a31515">&quot;myNewSet&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' new attribute set</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oNewPS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AttributeSet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oDoc.AttributeManager.FindAttributeSets(oNameOfNewPS).Count &gt; 0 </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' if the set exists aleady</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNewPS = oDoc.AttributeSets(oNameOfNewPS)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' you can clean up the existing attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;no attribute set named myNewSet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Exit Sub</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oShowStr </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'iterate the attributes</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oEachAtt </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Attribute</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Each</span><span style="line-height: 140%"> oEachAtt </span><span style="line-height: 140%; color: blue">In</span><span style="line-height: 140%"> oNewPS</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; </span><span style="line-height: 140%; color: #a31515">&quot; [Attribute Name]&#160; &quot;</span><span style="line-height: 140%"> &amp; oEachAtt.Name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> oEachAtt.Name = </span><span style="line-height: 140%; color: #a31515">&quot;ModelByte&quot;</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; </span><span style="line-height: 140%; color: #a31515">&quot; [Attribute Value]&#160; &quot;</span><span style="line-height: 140%"> &amp; System.Text.</span><span style="line-height: 140%; color: #2b91af">Encoding</span><span style="line-height: 140%">.Default.GetString(oEachAtt.Value) &amp; vbCr</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oShowStr = oShowStr &amp; </span><span style="line-height: 140%; color: #a31515">&quot; [Attribute Value]&#160; &quot;</span><span style="line-height: 140%"> &amp; oEachAtt.Value &amp; vbCr</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">MessageBox</span><span style="line-height: 140%">.Show(oShowStr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDoc.Close()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>
