---
layout: "post"
title: "Moving TextBox in Inventor"
date: "2013-01-08 11:19:08"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/01/moving-textbox-in-inventor.html "
typepad_basename: "moving-textbox-in-inventor"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>Translation and limited rotation of TextBox can be accomplished by setting the new origin, like shown below.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 10pt">Sub</font></font></span><font style="font-size: 10pt" color="#000000"> MoveTextBox()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> activeDoc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">DrawingDocument</font></span><font color="#000000"> =</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; m_inventorApplication.ActiveDocument</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> newSketch </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">DrawingSketch</font></span><font color="#000000"> =</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; activeDoc.ActiveSheet.Sketches.Add</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; newSketch.Edit()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> textBox </font><span><font color="#0000ff">As</font></span><font color="#000000"> Inventor.</font></font><span><font style="font-size: 10pt" color="#2b91af">TextBox</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; textBox = newSketch.TextBoxes.AddFitted(</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; m_inventorApplication.TransientGeometry.</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; CreatePoint2d(10, 10), </font></font><font style="font-size: 10pt"><span><font color="#a31515">&quot;TestText&quot;</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; textBox.SetColor(255, 255, 0)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><span><font style="font-size: 10pt" color="#008000">' supports only 0, pi/2, pi, 1.5pi</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; textBox.Rotation = </font></font><font style="font-size: 10pt"><span><font color="#2b91af">Math</font></span><font color="#000000">.Atan(1) * 2</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><span><font style="font-size: 10pt" color="#008000">' moves to (20,20)</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; textBox.Origin = m_inventorApplication.</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; TransientGeometry.CreatePoint2d(20, 20)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; newSketch.ExitEdit()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 10pt">End</font></font></span><font style="font-size: 10pt"><font color="#000000"> </font></font><span><font style="font-size: 10pt" color="#0000ff">Sub</font></span></font></p> </div>
