---
layout: "post"
title: "Why can I not convert linear Edges to Lines?"
date: "2013-06-12 14:09:24"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/06/why-can-i-not-convert-linear-edges-to-lines.html "
typepad_basename: "why-can-i-not-convert-linear-edges-to-lines"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>Why can I not convert linear Edges to Lines? Perhaps the name is a bit misleading, but Line in Inventor API represents a straight line with infinite length. It only has a 'RootPoint' and a 'Direction'. In most scenarios, the <strong>LineSegment</strong> object can do the trick.</p>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><font face="Courier New"><span style="color: "><font color="#0000ff"><font style="font-size: 8pt">Dim</font></font></span><font style="font-size: 8pt"><font color="#000000"> oDoc </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">PartDocument</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">oDoc = m_inventorApplication.ActiveDocument</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="color: "><font color="#0000ff"><font style="font-size: 8pt">Dim</font></font></span><font style="font-size: 8pt"><font color="#000000"> oEdge </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">Edge</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">oEdge = oDoc.ComponentDefinition.SurfaceBodies(1).Faces(1).Edges(1)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="color: "><font color="#0000ff"><font style="font-size: 8pt">Dim</font></font></span><font style="font-size: 8pt"><font color="#000000"> oLineSeg </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#2b91af">LineSegment</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="color: "><font color="#0000ff"><font style="font-size: 8pt">If</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span style="color: "><font color="#0000ff">TypeOf</font></span><font color="#000000"> oEdge.Geometry </font><span style="color: "><font color="#0000ff">Is</font></span><font color="#000000"> </font><span style="color: "><font color="#2b91af">LineSegment</font></span><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">Then</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; oLineSeg = oEdge.Geometry</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="color: "><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span style="color: "><font style="font-size: 8pt" color="#0000ff">If</font></span></font></p> </div>
