---
layout: "post"
title: "Manipulate rows and columns of iPart - 2"
date: "2013-03-11 21:20:48"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/03/manipulate-rows-and-columns-of-ipart-2.html "
typepad_basename: "manipulate-rows-and-columns-of-ipart-2"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The <a href="http://adndevblog.typepad.com/manufacturing/2013/02/manipulate-rows-and-columns-of-ipart-1.html">last post</a> introduces how to create and configure the iPart table. In this post, we take a look how to manipulate the existing iPart table. It is very straightforward. You just need to add/remove rows/columns in the Excel sheet. </p>  <p>Following test demo is based on the code in the <a href="http://adndevblog.typepad.com/manufacturing/2013/02/manipulate-rows-and-columns-of-ipart-1.html">last post</a> . We delete the third column, add a row to the end of the iPart table and delete the second row.</p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt">&#160;</span></p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt">Public Sub test<span style="color: #ff0000">(</span><span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Create an iPart table <span style="color: #ff0000">(</span><span style="color: #008000">21</span> row, <span style="color: #008000">6</span> columns<span style="color: #ff0000">)</span>&#160; <br /></span>&#160;&#160;&#160; CreateNewiPartTable&#160; <span style="color: #00ff00">' please refer to the last post&#160; <br /></span>&#160;&#160;&#160; <span style="color: #00ff00">'Delete the third column&#160; <br /></span>&#160;&#160;&#160; DeleteColumn <span style="color: #008000">3</span>&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Add a row to the end of the iPart table&#160; <br /></span>&#160;&#160;&#160; AddRow&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Delete the second row&#160; <br /></span>&#160;&#160;&#160; DeleteRow <span style="color: #008000">2</span>&#160; <br />End Sub&#160; <br />      <br />Private Sub DeleteColumn<span style="color: #ff0000">(</span>indexOfColumn As Integer<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument&#160; <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument&#160; <br />&#160;&#160;&#160; On Error Resume Next&#160; <br />&#160;&#160;&#160; Dim oFactory As iPartFactory&#160; <br />&#160;&#160;&#160; Set oFactory = oPartDoc.ComponentDefinition.iPartFactory&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Get the iPartTable&#160; <br /></span>&#160;&#160;&#160; If Err &gt; <span style="color: #008000">0</span> Or oFactory Is Nothing Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub&#160; <br />&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; On Error GoTo <span style="color: #008000">0</span>&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">' get the column by the index&#160; <br /></span>&#160;&#160;&#160; Dim column As iPartTableColumn&#160; <br />&#160;&#160;&#160; Set column = oFactory.TableColumns.Item<span style="color: #ff0000">(</span>indexOfColumn<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; If Not column Is Nothing Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oWorkSheet As WorkSheet&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oWorkSheet = oFactory.ExcelWorkSheet&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCells As Range&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCells = oWorkSheet.Cells&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCell As Range&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oCell = oWorkSheet.Columns<span style="color: #ff0000">(</span>indexOfColumn<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCell.Delete&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oWB As WorkBook&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oWB = oWorkSheet.Parent&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWB.Save&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWB.Close&#160; <br />&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; MsgBox <span style="color: #ff00ff">&quot;delete a column - done!&quot;</span>&#160; <br />End Sub      <br />      <br />Private Sub DeleteRow<span style="color: #ff0000">(</span>indexOfRow As Integer<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument&#160; <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument&#160; <br />&#160;&#160;&#160; On Error Resume Next&#160; <br />&#160;&#160;&#160; Dim oFactory As iPartFactory&#160; <br />&#160;&#160;&#160; Set oFactory = oPartDoc.ComponentDefinition.iPartFactory&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Get the iPartTable&#160; <br /></span>&#160;&#160;&#160; If Err &gt; <span style="color: #008000">0</span> Or oFactory Is Nothing Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub&#160; <br />&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; On Error GoTo <span style="color: #008000">0</span>&#160; <br />&#160;&#160;&#160; Dim row As iPartTableRow&#160; <br />&#160;&#160;&#160; Set row = oFactory.TableRows.Item<span style="color: #ff0000">(</span>indexOfRow<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; If Not row Is Nothing Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; row.Delete&#160; <br />&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; MsgBox <span style="color: #ff00ff">&quot;delete a row - done!&quot;</span>&#160; <br />End Sub&#160; <br />      <br />Private Sub AddRow<span style="color: #ff0000">(</span><span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument&#160; <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument&#160; <br />&#160;&#160;&#160; On Error Resume Next&#160; <br />&#160;&#160;&#160; Dim oFactory As iPartFactory&#160; <br />&#160;&#160;&#160; Set oFactory = oPartDoc.ComponentDefinition.iPartFactory&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Get the iPartTable&#160; <br /></span>&#160;&#160;&#160; If Err &gt; <span style="color: #008000">0</span> Or oFactory Is Nothing Then&#160; <br />&#160;&#160;&#160;&#160; Exit Sub&#160; <br />&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Get the part number used in the iPart table&#160; <br /></span>&#160;&#160;&#160; Dim row As iPartTableRow&#160; <br />&#160;&#160;&#160; Set row = oFactory.TableRows.Item<span style="color: #ff0000">(</span>oFactory.TableRows.Count<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; Dim sPartNumber As String&#160; <br />&#160;&#160;&#160; If Not row Is Nothing Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; sPartNumber = row.MemberName&#160; <br />&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; Dim pos As Integer&#160; <br />&#160;&#160;&#160; pos = InStrRev<span style="color: #ff0000">(</span>sPartNumber, <span style="color: #ff00ff">&quot;-&quot;</span><span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; Dim str As String&#160; <br />&#160;&#160;&#160; str = Left<span style="color: #ff0000">(</span>sPartNumber, pos<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; Dim iNumber As Integer&#160; <br />&#160;&#160;&#160; iNumber = Right<span style="color: #ff0000">(</span>sPartNumber, Len<span style="color: #ff0000">(</span>sPartNumber<span style="color: #ff0000">)</span> - pos<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">'Assume the offset of the parameter's value <span style="color: #ff0000">(</span>between two rows<span style="color: #ff0000">)</span> is 0.5cm&#160; <br /></span>&#160;&#160;&#160; Dim offset As Double&#160; <br />&#160;&#160;&#160; offset = 0.5&#160; <br />&#160;&#160;&#160; Dim oWorkSheet As WorkSheet&#160; <br />&#160;&#160;&#160; Set oWorkSheet = oFactory.ExcelWorkSheet&#160; <br />&#160;&#160;&#160; Dim oCells As Range&#160; <br />&#160;&#160;&#160; Set oCells = oWorkSheet.Cells&#160; <br />&#160;&#160;&#160; <span style="color: #00ff00">' New row's value...&#160; <br /></span>&#160;&#160;&#160; If <span style="color: #ff0000">(</span>iNumber + <span style="color: #008000">1</span><span style="color: #ff0000">)</span> &lt; <span style="color: #008000">10</span> Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; sPartNumber = str + <span style="color: #ff00ff">&quot;0&quot;</span> + CStr<span style="color: #ff0000">(</span>iNumber + <span style="color: #008000">1</span><span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; Else&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; sPartNumber = str + CStr<span style="color: #ff0000">(</span>iNumber + <span style="color: #008000">1</span><span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; Dim oCell As Range&#160; <br />&#160;&#160;&#160; Set oCell = oCells.Insert<span style="color: #ff0000">(</span>, True<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; oCells.Item<span style="color: #ff0000">(</span>row.Index + 2, <span style="color: #008000">1</span><span style="color: #ff0000">)</span> = sPartNumber&#160; <br />&#160;&#160;&#160; oCells.Item<span style="color: #ff0000">(</span>row.Index + 2, <span style="color: #008000">2</span><span style="color: #ff0000">)</span> = sPartNumber&#160; <br />&#160;&#160;&#160; Dim oUM As UnitsOfMeasure&#160; <br />&#160;&#160;&#160; Set oUM = oPartDoc.UnitsOfMeasure&#160; <br />&#160;&#160;&#160; Dim i As Integer&#160; <br />&#160;&#160;&#160; Dim oParameter As Parameter&#160; <br />&#160;&#160;&#160; For i = <span style="color: #008000">3</span> To oCells.Columns.Count&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oParameter = oPartDoc.ComponentDefinition.Parameters.ModelParameters.Item<span style="color: #ff0000">(</span>oCells.Item<span style="color: #ff0000">(</span>1, i<span style="color: #ff0000">)</span>.Value<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oParameter.Name &lt;&gt; oPartDoc.ComponentDefinition.Parameters.ModelParameters.Item<span style="color: #ff0000">(</span><span style="color: #008000">4</span><span style="color: #ff0000">)</span>.Name Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCells.Item<span style="color: #ff0000">(</span>row.Index + 2, i<span style="color: #ff0000">)</span> = oUM.GetStringFromValue<span style="color: #ff0000">(</span>oParameter.Value + offset * <span style="color: #ff0000">(</span>row.Index<span style="color: #ff0000">)</span>, oParameter.Units<span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCells.Item<span style="color: #ff0000">(</span>row.Index + 2, i<span style="color: #ff0000">)</span> = oPartDoc.ComponentDefinition.Parameters.ModelParameters.Item<span style="color: #ff0000">(</span><span style="color: #008000">4</span><span style="color: #ff0000">)</span>.Expression&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160; Next&#160; <br />&#160;&#160;&#160; Set oUM = Nothing&#160; <br />&#160;&#160;&#160; Dim oWB As WorkBook&#160; <br />&#160;&#160;&#160; Set oWB = oWorkSheet.Parent&#160; <br />&#160;&#160;&#160; oWB.Save&#160; <br />&#160;&#160;&#160; oWB.Close&#160; <br />&#160;&#160;&#160; MsgBox <span style="color: #ff00ff">&quot;Add a row - done!&quot;</span>&#160; <br />End Sub      <br /></span></p>
