---
layout: "post"
title: "Get Model Document from LeaderNote"
date: "2013-04-07 20:22:37"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/04/get-model-document-from-leadernote.html "
typepad_basename: "get-model-document-from-leadernote"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>As we know, the leader note could attach with a drawing curve. If the curve changes, the position and the content of the leader may change as well. Then, how to know which model document (part/assembly) the leader note points to? Actually, the clue is to get the drawing curve the leader note attached with. </p>  <p>Following code demo assumes a leader note is selected. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017d429daff2970c-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_2cbd79.jpg" width="406" height="267" /></a></p>  <p><em>Sub test() </em></p>  <p><em>&#160;&#160;&#160; Dim oDoc As DrawingDocument     <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument      <br />      <br />&#160;&#160;&#160; 'select a leader note      <br />&#160;&#160;&#160; Dim oLeaderNote As LeaderNote      <br />&#160;&#160;&#160; Set oLeaderNote = oDoc.SelectSet(1)      <br />      <br />&#160;&#160;&#160; ' get the last node of the leader which attaches to the drawing curve      <br />&#160;&#160;&#160; Dim oLastNode As LeaderNode      <br />&#160;&#160;&#160; Set oLastNode = oLeaderNote.Leader.AllNodes(oLeaderNote.Leader.AllNodes.Count)      <br />      <br />&#160;&#160;&#160; Dim oGeIntent As GeometryIntent      <br />&#160;&#160;&#160; Dim oAttachedDrawingCurve As DrawingCurve      <br />&#160;&#160;&#160; Dim oDrawingView As DrawingView      <br />&#160;&#160;&#160; Dim oModelG As Object      <br />      <br />&#160;&#160;&#160; 'check if the leader attaches to a drawing curve      <br />&#160;&#160;&#160; If Not oLastNode.AttachedEntity Is Nothing Then      <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get the corresponding curve      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oGeIntent = oLastNode.AttachedEntity      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oAttachedDrawingCurve = oGeIntent.Geometry      <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get the drawing view      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oDrawingView = oAttachedDrawingCurve.Parent      <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' check which model document the curve comes from      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'the model entity      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oModelG = oAttachedDrawingCurve.ModelGeometry      <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf oModelG Is Edge Then      <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'SurfaceBody      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSB As SurfaceBody      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSB = oModelG.Parent      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get the component definition of SurfaceBody      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oDef As ComponentDefinition      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oDef = oSB.ComponentDefinition      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get the document      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSourceDoc As Document      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSourceDoc = oDef.Document      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;drawing view is: &quot; &amp; oDrawingView.Name &amp; vbCr &amp; &quot;the model document is: &quot; &amp; oSourceDoc.FullFileName      <br />      <br />&#160;&#160;&#160; Else      <br />&#160;&#160;&#160;&#160;&#160;&#160; MsgBox (&quot;no any curve is attached with the leader noteÔºÅ&quot;)      <br />&#160;&#160;&#160; End If      <br />End Sub </em></p>
