---
layout: "post"
title: "Add a node to the Model Browser using a ClientFeature"
date: "2013-07-30 16:56:52"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/07/add-a-node-to-the-model-browser-using-a-clientfeature.html "
typepad_basename: "add-a-node-to-the-model-browser-using-a-clientfeature"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p>Inventor allows you to create a custom browser pane and you can add browser nodes on the custom pane, even add all nodes of Model Browser Pane. However you can't add any node directly to the node tree of Model Browser pane and the new browser node can only be added as the top node of the custom pane. </p>  <p>One way to add a node to the Model Browser Pane is to use a Client Feature to add the node. Below is a VB.NET example. After this code runs there will be another node added to the Model browser:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b0191047daf11970c-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_a57161.jpg" width="416" height="246" /></a></p>  <p>&#160; <br /></p>  <div style="font-family: consolas; background: #eeeeee; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Sub</span> addClientFeatureToModelBrowserPane()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> m_inventorApp <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Inventor.<span style="color: #2b91af">Application</span> = <span style="color: blue">Nothing</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' Try to get an active instance of Inventor</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_inventorApp = System.Runtime. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; InteropServices.<span style="color: #2b91af">Marshal</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetActiveObject(<span style="color: #a31515">&quot;Inventor.Application&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Catch</span> ex <span style="color: blue">As</span> <span style="color: #2b91af">Exception</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.Windows.Forms.<span style="color: #2b91af">MessageBox</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Show(<span style="color: #a31515">&quot;Start an Inventor session&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Exit Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oDef <span style="color: blue">As</span> <span style="color: #2b91af">PartComponentDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oDef = m_inventorApp.ActiveDocument. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ComponentDefinition</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oClientDef <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeatureDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oClientDef = oDef.Features.ClientFeatures. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; CreateDefinition()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oClientFeature <span style="color: blue">As</span> <span style="color: #2b91af">ClientFeature</span></p>    <p style="margin: 0px">&#160;&#160;&#160; oClientFeature = oDef.Features. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ClientFeatures.Add(oClientDef, <span style="color: #a31515">&quot;My node&quot;</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; oClientFeature.Name = <span style="color: #a31515">&quot;Testing&quot;</span></p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Sub</span></p> </div>
