---
layout: "post"
title: "Copy iProperties of Model Document to Drawing Document When Placing View"
date: "2013-12-10 21:19:52"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/12/copy-iproperties-of-model-document-to-drawing-document-when-placing-view.html "
typepad_basename: "copy-iproperties-of-model-document-to-drawing-document-when-placing-view"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><strong>Question</strong>:    <br />Within the document settings for a drawing, on the drawing tab, there is a button called &quot;Copy Model iProperty Settings... &quot; this brings you to the settings dialog box which has a check box to enable Copy Model iProperties. Checking the box will enable a list of iProperties found in the drawing which you would like to enable inventor to copy from the model to the drawing's iProperties.</p>  <p>I am looking for a way within the API to check the box highlighted in red and then any iProperties in the list.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b019b028fddbd970b-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_126b93.jpg" width="249" height="350" /></a></p>  <p><strong>Solution</strong>:    <br />The DrawingSettings object has not exposed the relevant API to toogle the [Copy Model Properties]. But with current API, it is feasible to implement the copying when placing the drawing view. The following is a VBA code demo which watches the event of document changing. If it is “Create Drawing View”, get the model document of the drawing view, and copy the specific iProperties to the drawing document. </p>  <p><font style="background-color: #ffff00">Module:</font></p>  <p><em><font size="1">Private cls As clsDocEvent       <br />Sub startcmd()        <br />&#160;&#160;&#160; Set cls = New clsDocEvent        <br />End Sub</font></em></p>  <p><em><font size="1">Sub Endcmd()       <br />&#160;&#160;&#160; Set cls = Nothing        <br />End Sub</font></em></p>  <p><font style="background-color: #ffff00">Event Class:</font></p>  <p><em><font size="1">'document event       <br />Private WithEvents DocEvts As DocumentEvents        <br />'current drawing document        <br />Private thisDrawingDoc As DrawingDocument</font></em></p>  <p>   <br /><em><font size="1">Private Sub Class_Initialize()       <br />&#160;&#160;&#160; 'get the current document        <br />&#160;&#160;&#160; Set thisDrawingDoc = ThisApplication.ActiveDocument        <br />&#160;&#160;&#160; 'get document event        <br />&#160;&#160;&#160; Set DocEvts = thisDrawingDoc.DocumentEvents        <br />&#160;&#160; <br />End Sub</font></em></p>  <p><em><font size="1">Private Sub Class_Terminate()       <br />&#160;&#160;&#160; Set DocEvts = Nothing        <br />End Sub</font></em></p>  <p><em><font size="1">Private Sub DocEvts_OnChange(ByVal ReasonsForChange As CommandTypesEnum, _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal BeforeOrAfter As EventTimingEnum, _        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal Context As NameValueMap, _        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; HandlingCode As HandlingCodeEnum)</font></em></p>  <p>   <br /><em><font size="1">If BeforeOrAfter = kAfter Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'check the context        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim i As Integer        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oEachObj As Variant        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 1 To Context.Count        <br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160; On Error Resume Next        <br />&#160;&#160;&#160;&#160;&#160;&#160; Set oEachObj = Context.Item(i)        <br />&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160; If Err Then        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oName As String        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oName = Context.Item(i)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'if this is fired by placing drawing view        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oName = &quot;Create Drawing View&quot; Then        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get the document the drawing view refers to        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oLastView As DrawingView        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oLastView = thisDrawingDoc.ActiveSheet.DrawingViews(thisDrawingDoc.ActiveSheet.DrawingViews.Count)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oRefDoc As Document        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oRefDoc = oLastView.ReferencedDocumentDescriptor.ReferencedDocument        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'copy some specific iProperties to the drawing document        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' document title        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oTitle As String        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTitle = oRefDoc.PropertySets(&quot;Summary Information&quot;).ItemByPropId(kTitleSummaryInformation).value        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'copy to drawing document        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; thisDrawingDoc.PropertySets(&quot;Summary Information&quot;).ItemByPropId(kTitleSummaryInformation).value = oTitle        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' document description        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oDesc As String        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDesc = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).ItemByPropId(kDescriptionDesignTrackingProperties).value        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'copy to drawing document        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; thisDrawingDoc.PropertySets(&quot;Design Tracking Properties&quot;).ItemByPropId(kDescriptionDesignTrackingProperties).value = oDesc        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Err.Clear        <br />&#160;&#160;&#160;&#160;&#160;&#160; Else        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'if context item is also a NamedValueMap        <br />&#160;&#160;&#160;&#160;&#160;&#160; End If        <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; Next        <br />&#160;&#160; <br />&#160;&#160;&#160; End If        <br />End Sub</font></em></p>
