---
layout: "post"
title: "Get Tags, Prompts and Result strings of Attributes of Acad Block"
date: "2013-01-29 00:34:06"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/01/get-tags-prompts-and-result-strings-of-attributes-of-acad-block.html "
typepad_basename: "get-tags-prompts-and-result-strings-of-attributes-of-acad-block"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The AutoCAD DWG has a type of entity called Block which can encloses with the attributes. It is similar to the prompt string in the Inventor drawing. API allows you to access the relevant information. </p>  <p>Assume we have a DWG file as below:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017d408d54c9970c-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_a6e714.jpg" width="475" height="361" /></a> </p>  <p>The VBA code below dumps the tags, prompts and result strings.</p>  <p>&#160;</p>  <p><em>Public Sub Test1() </em></p>  <p><em>&#160;&#160;&#160; Dim oDoc As DrawingDocument      <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument       <br />&#160;&#160;&#160; Dim oTags() As String       <br />&#160;&#160;&#160; Dim oValues() As String       <br />&#160;&#160;&#160; Dim oAcadBlkDef As AutoCADBlockDefinition       <br />&#160;&#160;&#160; Dim oCnt As Integer       <br />&#160;&#160;&#160; Debug.Print &quot;&quot;       <br />&#160;&#160;&#160; For Each oAcadBlkDef In oDoc.AutoCADBlockDefinitions       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oAcadBlkDef.GetPromptTags(oTags, oValues)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print &quot;Block Name=&quot; &amp; oAcadBlkDef.Name       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim i As Integer       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = LBound(oTags) To UBound(oTags)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print &quot;Tag Name=&quot; &amp; oTags(i) &amp; _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; Prompt= &quot; &amp; oValues(i)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next       <br />&#160;&#160;&#160; Next       <br />&#160;&#160;&#160; Debug.Print &quot;----------------------&quot;       <br />&#160;&#160;&#160; Dim oAcadBlk As AutoCADBlock       <br />&#160;&#160;&#160; For Each oAcadBlk In oDoc.ActiveSheet.AutoCADBlocks       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oAcadBlk.GetPromptTextValues(oTags, oValues)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print &quot;Block Name=&quot; &amp; oAcadBlk.Name       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = LBound(oTags) To UBound(oTags)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print &quot;Tag Name=&quot; &amp; oTags(i) &amp; _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; Prompt= &quot; &amp; oValues(i)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next       <br />&#160;&#160;&#160; Next       <br />&#160;&#160;&#160; Debug.Print &quot;&quot; </em></p>  <p><em>End Sub</em></p>  <p></p>  <p>&#160;</p>  <p>The code above could be used in .NET directly except one detail. The arguments of GetPromptTags or GetPromptTextValues require array which must be initialized correctly. The following code explains:</p>  <p style="line-height: 5.25pt; margin: 0cm 0cm 0pt"><span style="font-family: &quot;Courier New&quot;; color: blue; font-size: 4.5pt" lang="EN-US">&#160;</span></p>  <div style="font-family: courier new; background: white; color: black; font-size: 9pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> Button1_Click(sender </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> System.</span><span style="line-height: 140%; color: #2b91af">Object</span><span style="line-height: 140%">, e </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> System.</span><span style="line-height: 140%; color: #2b91af">EventArgs</span><span style="line-height: 140%">) </span><span style="line-height: 140%; color: blue">Handles</span><span style="line-height: 140%"> Button1.Click</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Connect to a running instance of Inventor. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> invApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">Application</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Check to see if a drawing is active</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; invApp = System.Runtime.InteropServices.</span><span style="line-height: 140%; color: #2b91af">Marshal</span><span style="line-height: 140%">.GetActiveObject(</span><span style="line-height: 140%; color: #a31515">&quot;Inventor.Application&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> invApp.ActiveDocument.DocumentType &lt;&gt; Inventor.</span><span style="line-height: 140%; color: #2b91af">DocumentTypeEnum</span><span style="line-height: 140%">.kDrawingDocumentObject </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</span><span style="line-height: 140%; color: #a31515">&quot;Need to have a drawing document active&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Return</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Create ref to active drawing document</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDrawingDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">DrawingDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawingDoc = invApp.ActiveDocument</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Create ref to AutoCADBlocks collection in the active sheet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> cAcadBlocks </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">AutoCADBlocks</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cAcadBlocks = oDrawingDoc.ActiveSheet.AutoCADBlocks</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Set the name of the block</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> AcadBlockName </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AcadBlockName = </span><span style="line-height: 140%; color: #a31515">&quot;Myblock&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Create ref to the AutoCAD block object in the active sheet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oAcadBlock </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Inventor.</span><span style="line-height: 140%; color: #2b91af">AutoCADBlock</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oAcadBlock = cAcadBlocks.Item(AcadBlockName)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' check to see if block object code is working (it does)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Debug</span><span style="line-height: 140%">.Print(oAcadBlock.Scale)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Debug</span><span style="line-height: 140%">.Print(oAcadBlock.LineWeight)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Debug</span><span style="line-height: 140%">.Print(oAcadBlock.Name)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Debug</span><span style="line-height: 140%">.Print(oAcadBlock.AttributeSets.Count) </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Try and display block tags and values</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'correct</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> sTags() </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">New</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span><span style="line-height: 140%">() {}</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> sAttr() </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">New</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span><span style="line-height: 140%">() {}</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'wrong</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Dim sTags() As String = New Object() {}</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Dim sAttr() As String = New Object() {}</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'correct only when&#160; you have known the count of texts</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' e.g. 23</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Dim sTags(23) As String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Dim sAttr(23) As String</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'wrong</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Dim sTags() As String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Dim sAttr() As String</span></p>    <p style="margin: 0px">&#160; </p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oAcadBlock.GetPromptTextValues(sTags, sAttr)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> i </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Integer</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> iCount </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Integer</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; iCount = UBound(sTags)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Debug</span><span style="line-height: 140%">.Print(</span><span style="line-height: 140%; color: #a31515">&quot;icount = &quot;</span><span style="line-height: 140%"> &amp; iCount)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' display attribute tag and value</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">For</span><span style="line-height: 140%"> i = 0 </span><span style="line-height: 140%; color: blue">To</span><span style="line-height: 140%"> iCount</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(sTags(i) &amp; </span><span style="line-height: 140%; color: #a31515">&quot; = &quot;</span><span style="line-height: 140%"> &amp; sAttr(i))</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; i = i + 1</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Next</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p>    <p style="margin: 0px">&#160;</p> </div>
