---
layout: "post"
title: "Import specific layers of DWG to inventor part sketch"
date: "2013-03-31 21:06:23"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/03/import-specific-layers-of-dwg-to-inventor-part-sketch.html "
typepad_basename: "import-specific-layers-of-dwg-to-inventor-part-sketch"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The option <b>SelectedLayout </b>of the Translator Addin of DWG can specify the layers to import to the sketch. </p>  <p>oOptions.Add &quot;SelectedLayers&quot;, &quot;Layer1&quot; </p>  <p>you can also specify several layers, e.g.</p>  <p>oOptions.Add &quot;SelectedLayers&quot;, &quot;Layer1,Layer2&quot;&#160; <br /></p>  <p>Sub ImportDWGIntoSketch()   <br />&#160;&#160;&#160; 'DWG translator    <br />&#160;&#160;&#160; Dim oDwg As TranslatorAddIn    <br />&#160;&#160;&#160; Set oDwg = ThisApplication.ApplicationAddIns.ItemById(&quot;{C24E3AC2-122E-11D5-8E91-0010B541CD80}&quot;)    <br />&#160;&#160;&#160; Dim oData As DataMedium    <br />&#160;&#160;&#160; Dim oContext As TranslationContext    <br />&#160;&#160;&#160; Dim oOptions As NameValueMap    <br />&#160;&#160;&#160; Set oData = ThisApplication.TransientObjects.CreateDataMedium    <br />&#160;&#160;&#160; Set oContext = ThisApplication.TransientObjects.CreateTranslationContext    <br />&#160;&#160;&#160; Set oOptions = ThisApplication.TransientObjects.CreateNameValueMap    <br />&#160;&#160;&#160; ' Specify a DWG file to import it into sketch, please change the path name as needed    <br />&#160;&#160;&#160; oData.FileName = &quot;C:\Temp\mytest.dwg&quot;    <br />&#160;&#160;&#160; Dim oDoc As PartDocument    <br />&#160;&#160;&#160; Set oDoc = ThisApplication.Documents.Add(kPartDocumentObject)    <br />&#160;&#160;&#160; 'add a new sketch    <br />&#160;&#160;&#160; Dim oSk As PlanarSketch    <br />&#160;&#160;&#160; Set oSk = oDoc.ComponentDefinition.Sketches.Add(oDoc.ComponentDefinition.WorkPlanes(3))    <br />&#160;&#160;&#160; oSk.Edit    <br />&#160;&#160;&#160; oContext.Type = kFileBrowseIOMechanism    <br />&#160;&#160;&#160; oContext.OpenIntoExisting = oSk    <br />    <br />&#160;&#160;&#160; ' Specify the layers to import     <br />&#160; <font color="#ff0000"> oOptions.Add &quot;SelectedLayers&quot;, &quot;Layer1&quot;&#160; <br /></font>&#160; <font color="#00ff00"> â€˜oOptions.Add &quot;SelectedLayers&quot;, &quot;0,Layer2&quot;&#160; <br /></font>&#160;&#160;&#160; oOptions.Add &quot;InvertLayersSelection&quot;, False ' Set if import the selected layers in above setting    <br />&#160;&#160;&#160; ' Set the ConstrainEndPoints    <br />&#160;&#160;&#160; oOptions.Add &quot;ConstrainEndPoints&quot;, True    <br />&#160;&#160;&#160; ' Specify the units of DWG file    <br />&#160;&#160;&#160; oOptions.Add &quot;FileUnits&quot;, &quot;Millimeters&quot;    <br />&#160;&#160;&#160; Call oDwg.Open(oData, oContext, oOptions, oDoc)    <br />End Sub</p>
