---
layout: "post"
title: "Inventor: Access sheet metal part bend information from a drawing view"
date: "2013-08-01 12:42:08"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/08/inventor-access-sheet-metal-part-bend-information-from-a-drawing-view.html "
typepad_basename: "inventor-access-sheet-metal-part-bend-information-from-a-drawing-view"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a></p>  <p>Q: When I select a bend line in a drawing view, I would like to have access to its flat bend results, such as the bend direction, bend angle and bend radius.</p>  <p>A: The following VBA example finds the bend results corresponding to a bend line from a drawing view. Before running this code select a bend line in a drawing document that belongs to the flat bend pattern of a SheetMetal Part.   <br /></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font style="font-size: 9pt" color="#000000">Private Sub GetBendResultFromSelectedCurve()</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oDoc As DrawingDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oDoc = ThisApplication.ActiveDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Gets the selected curve segment</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oDwCurveSegment As DrawingCurveSegment</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oDwCurveSegment = oDoc.SelectSet.Item(1)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Gets full drawing curve from the segment</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oDrawingCurve As DrawingCurve</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oDrawingCurve = oDwCurveSegment.Parent</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Gets edge</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oEdge As Edge</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oEdge = oDrawingCurve.ModelGeometry</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Retrieves component definition from the edge</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oSMDef As SheetMetalComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oSMDef = oEdge.Parent.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oFlatPattern As FlatPattern</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oFlatPattern = oSMDef.FlatPattern</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Gets flat bend result corresponding to the edge</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oBendResult As FlatBendResult</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oBendResult = oFlatPattern.FlatBendResults.Item(oEdge)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">'Prints Flat Bend Results</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;---------------- Flat Bend Infos ----------------&quot;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;Internal Name: &quot; &amp; oBendResult.InternalName</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">If oBendResult.IsOnBottomFace Then</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;Bend On Bottom Face&quot;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Else</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;Bend On Top Face&quot;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">End If</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Dim oUOM As UnitsOfMeasure</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Set oUOM = oDoc.UnitsOfMeasure</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;Bend Angle<span style="mso-spacerun: yes">&#160; </span>= &quot; &amp; oUOM _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">.GetStringFromValue( _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 9pt">oBendResult.Angle, _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 9pt">kDefaultDisplayAngleUnits)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;Bend Radius = &quot; &amp; oUOM _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">.GetStringFromValue( _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 9pt">oBendResult.InnerRadius, _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 9pt">kDefaultDisplayLengthUnits)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">If oBendResult.IsDirectionUp Then</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;Bend Direction: &quot; &amp; &quot;Bend Up&quot;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Else</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160;&#160;&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;Bend Direction: &quot; &amp; &quot;Bend Down&quot;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">End If</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 9pt" color="#000000">&#160;&#160;&#160;&#160;&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Debug.Print &quot;-------------------------------------------------&quot;</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 9pt">&#160; </font></span><font style="font-size: 9pt">Beep</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNoSpacing"><span style="font-family: ; mso-bidi-font-size: 8.0pt"><font face="Consolas"><font style="font-size: 9pt" color="#000000">End Sub</font></font></span></p>
