---
layout: "post"
title: "Create a LightingStyle with a light"
date: "2013-01-16 04:32:12"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/01/create-a-lightingstyle-with-a-light.html "
typepad_basename: "create-a-lightingstyle-with-a-light"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>The sample code below show an example on how create a LightingStyle using VB.NET. The Light is a property of that style, also created and configured on the sample.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 10pt">Public</font></font></span><font style="font-size: 10pt"><font color="#000000"> </font><span><font color="#0000ff">Sub</font></span><font color="#000000"> addLightStyle()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">If</font></span><font color="#000000"> m_inventorApplication.Documents.Count = 0 _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">Then</font></span><font color="#000000"> </font></font><span><font style="font-size: 10pt" color="#0000ff">Exit Sub</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">If</font></span><font color="#000000"> m_inventorApplication.ActiveDocument.DocumentType &lt;&gt; _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font><font style="font-size: 10pt"><span><font color="#2b91af">DocumentTypeEnum</font></span><font color="#000000">.kPartDocumentObject </font><span><font color="#0000ff">Then</font></span><font color="#000000"> _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; </font></font><span><font style="font-size: 10pt" color="#0000ff">Exit Sub</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> pDoc </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">PartDocument</font></span><font color="#000000"> = _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; m_inventorApplication.ActiveDocument</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> lStyle </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font></font><span><font style="font-size: 10pt" color="#2b91af">LightingStyle</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; lStyle = pDoc.LightingStyles.Add(</font></font><font style="font-size: 10pt"><span><font color="#a31515">&quot;Test_L_Style&quot;</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; </font></font><font style="font-size: 10pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> lite1 </font><span><font color="#0000ff">As</font></span><font color="#000000"> </font><span><font color="#2b91af">Light</font></span><font color="#000000"> = lStyle.Lights. _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160;&#160;&#160; Add(</font></font><font style="font-size: 10pt"><span><font color="#2b91af">LightTypeEnum</font></span><font color="#000000">.kViewSpaceLight)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; lite1.Color = m_inventorApplication. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; TransientObjects.CreateColor(255, 0, 0)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; lite1.Intensity = 1</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 10pt">&#160; lite1.On = </font></font><span><font style="font-size: 10pt" color="#0000ff">True</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160; lite1.Position = m_inventorApplication. _</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 10pt" color="#000000">&#160;&#160;&#160; TransientGeometry.CreatePoint(0, 0, 0)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 10pt">End</font></font></span><font style="font-size: 10pt"><font color="#000000"> </font></font><span><font style="font-size: 10pt" color="#0000ff">Sub</font></span></font></p> </div>
