---
layout: "post"
title: "Attach a sketched symbol to a balloon"
date: "2013-01-09 19:43:21"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/01/attach-a-sketched-symbol-to-a-balloon.html "
typepad_basename: "attach-a-sketched-symbol-to-a-balloon"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>I got a question on how to attach a sketched symbol to a balloon. This when the balloon moves, the sketched symbol can also move together. UI can do this, however the customer was struggling to make an API code. </p>  <p>I took some time to dig into. It looks there are some tricks here. Let us firstly take a look at how UI works.</p>  <p>- select the sketched symbol    <br />- in mouse-right-button menu, select [Add Vertex / Leader]</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017c3585ddbd970b-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_6c7331.jpg" width="490" height="324" /></a> </p>  <p>- Inventor will ask you to select a position. When the cursor is closing to the balloon, the cursor will become a cross if it locates on the balloon circle. On other locations such as balloon center or the leader line of the balloon, the cursor will still be an arrow. That means the valid locations on a balloon is the position on the circle. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017c3585ddf9970b-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_d65f7a.jpg" width="481" height="258" /></a> </p>  <p>So we need to make sure to create the geometry intent of balloon with the point on the circumference. While the customerâ€™s code uses center point of the circle. So API failed.</p>  <p>One more thing I found is: in UI, you add the first leader point on balloon, next a position on sketched symbol. But with API, you must add them in the reverse sequence.</p>  <p>The following code assumes you have a drawing with one balloon and one sketched symbol. </p>  <p>VBA:</p>  <p><font size="1">Public Sub AttachSymbolToBalloon() </font></p>  <p><font size="1">&#160; ' Set a reference to the drawing document.      <br />&#160; ' This assumes a drawing document is active.       <br />&#160; Dim oDrawDoc As DrawingDocument       <br />&#160; Set oDrawDoc = ThisApplication.ActiveDocument </font></p>  <p><font size="1">&#160; ' Set a reference to the active sheet.      <br />&#160; Dim oActiveSheet As Sheet       <br />&#160; Set oActiveSheet = oDrawDoc.ActiveSheet </font></p>  <p><font size="1">&#160; ' This assumes that a Balloon and SketchedSymbol are selected      <br />&#160; Dim oBalloon As Balloon       <br />&#160; Set oBalloon = oDrawDoc.SelectSet.Item(1) </font></p>  <p><font size="1">&#160;&#160; Dim oSS As SketchedSymbol      <br />&#160;&#160; Set oSS = oDrawDoc.SelectSet.Item(2) </font></p>  <p><font size="1">&#160;&#160; ' the collection of leader points SketchedSymbol      <br />&#160;&#160; Dim oObjColl As ObjectCollection       <br />&#160;&#160; Set oObjColl = ThisApplication.TransientObjects.CreateObjectCollection()       <br />&#160;&#160; ' first leader point is position of SketchedSymbol       <br />&#160;&#160;&#160; Dim oFirstPt1 As Point2d       <br />&#160;&#160;&#160; Set oFirstPt1 = ThisApplication.TransientGeometry.CreatePoint2d(oSS.Position.X, oSS.Position.Y)       <br />&#160;&#160;&#160; 'second leader point on circumference of Balloon       <br />&#160;&#160;&#160; Dim oPtItent&#160; As Point2d       <br />&#160;&#160;&#160; Set oPtItent = ThisApplication.TransientGeometry.CreatePoint2d( _       <br />&#160;&#160;&#160; oBalloon.Position.X + oBalloon.Style.BalloonDiameter / 2, _       <br />&#160;&#160;&#160;&#160;&#160;&#160; oBalloon.Position.Y)       <br />&#160;&#160;&#160; Dim oBalloonIntent&#160; As GeometryIntent       <br />&#160;&#160;&#160; Set oBalloonIntent = oActiveSheet.CreateGeometryIntent(oBalloon, oPtItent) </font></p>  <p><font size="1">&#160;&#160;&#160;&#160; ' make sure the adding sequence      <br />&#160;&#160;&#160;&#160; Call oObjColl.Add(oFirstPt1)       <br />&#160;&#160;&#160;&#160;&#160; Call oObjColl.Add(oBalloonIntent)       <br />&#160;&#160;&#160; ' add leader.       <br />&#160;&#160;&#160; Call oSS.Leader.AddLeader(oObjColl)       <br />End Sub</font></p>  <p>&#160;</p>  <p>VB.NET </p>  <div style="font-family: courier new; background: white; color: black; font-size: 9pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> AttachSymbolToBalloon()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Set a reference to the drawing document.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' This assumes a drawing document is active.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oDrawDoc </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">DrawingDocument</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrawDoc = ThisApplication.ActiveDocument</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Set a reference to the active sheet.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oActiveSheet </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Sheet</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oActiveSheet = oDrawDoc.ActiveSheet</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' This assumes that a Balloon and SketchedSymbol are selected</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oBalloon </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Balloon</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBalloon = oDrawDoc.SelectSet.Item(1)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oSS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SketchedSymbol</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSS = oDrawDoc.SelectSet.Item(2)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' the collection of leader points SketchedSymbol</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oObjColl </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectCollection</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oObjColl = ThisApplication.TransientObjects.CreateObjectCollection()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' first leader point is position of SketchedSymbol</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oFirstPt1 </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point2d</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oFirstPt1 = ThisApplication.TransientGeometry.CreatePoint2d(oSS.Position.X, oSS.Position.Y)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'second leader point on circumference of Balloon</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oPtItent </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point2d</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPtItent = ThisApplication.TransientGeometry.CreatePoint2d( _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBalloon.Position.X + oBalloon.Style.BalloonDiameter / 2, _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBalloon.Position.Y)</span>&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> oBalloonIntent </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">GeometryIntent</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBalloonIntent = oActiveSheet.CreateGeometryIntent(oBalloon, oPtItent)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' make sure the adding sequence</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oObjColl.Add(oFirstPt1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oObjColl.Add(oBalloonIntent)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' add leader.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Call</span><span style="line-height: 140%"> oSS.Leader.AddLeader(oObjColl)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>  <p>&#160;<a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017c3585de28970b-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="image" border="0" alt="image" src="/assets/image_be2a8f.jpg" width="455" height="228" /></a></p>
