---
layout: "post"
title: "Inventor: Adding WorkAxis by AddByPointAndPlane method"
date: "2013-01-06 08:39:37"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/01/inventor-adding-workaxis-by-addbypointandplane-method.html "
typepad_basename: "inventor-adding-workaxis-by-addbypointandplane-method"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a></p>  <p><b>Issue</b></p>  <p>Are there any examples available showing how to use <font face="Consolas">AddByPointAndPlane</font>? This method is not documented in the help file.</p>  <p><a name="section2"></a><b></b></p>  <p><b>Solution</b></p>  <p>Method <font face="Consolas">AddByPointAndPlane</font> is obsolete and is not recommended starting from the release Inventor 2008. It was replaced by more powerful <font face="Consolas">AddByNormalToSurface</font> method.</p>  <p>The following VBA example illustrates this method. </p>  <p><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">Sub CreateWorkAxis()</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oPart As PartDocument</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oPart = ThisApplication _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.Documents.Add(kPartDocumentObject)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oDef As PartComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oDef = oPart.ComponentDefinition</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oTG As TransientGeometry</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oTG = ThisApplication.TransientGeometry</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oSketch As PlanarSketch</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oSketch = oDef.Sketches _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.Add(oDef.WorkPlanes(1))</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><span style="mso-spacerun: yes"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160; </font></font></span></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oPoint As SketchPoint</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oPoint = oSketch.SketchPoints _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.Add(oTG.CreatePoint2d(2, 2), False)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Dim oAxis As WorkAxis</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160; </font></span><font style="font-size: 10pt">Set oAxis = oDef.WorkAxes _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">.AddByNormalToSurface( _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">oDef.WorkPlanes(2), _</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font color="#000000"><span style="mso-spacerun: yes"><font style="font-size: 10pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></span><font style="font-size: 10pt">oPoint, False)</font></font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">'<span style="mso-spacerun: yes">&#160; </span>This still works but not supported</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">''<span style="mso-spacerun: yes">&#160; </span>Set oAxis = oDef.WorkAxes _</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">''<span style="mso-spacerun: yes">&#160;&#160;&#160; </span>.AddByPointAndPlane( _</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">''<span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160; </span>oPoint, oDef.WorkPlanes(2), False)</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">End Sub</font></font></span></p>  <p style="line-height: normal; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: ; mso-bidi-font-size: 9.0pt; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Consolas"><font style="font-size: 10pt" color="#000000">&#160;</font></font></span></p>  <p>See also this <a href="http://adndevblog.typepad.com/manufacturing/2013/01/creating-work-features-using-the-inventor-api-in-vbnet.html">post</a> on work features in Inventor:</p>
