---
layout: "post"
title: "Set a line type for a specific part in the drawing view"
date: "2013-07-31 06:32:00"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/07/set-a-line-type-for-a-specific-part-in-the-drawing-view.html "
typepad_basename: "set-a-line-type-for-a-specific-part-in-the-drawing-view"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><strong>Issue</strong>    <br />I would like to change the way a linetype appears for a specific part, globally throughout my drawing package. I am currently selecting the part in the model tree in the browser and changing it that way, but I have to do it on multiple views, for multiple pages and am wondering if there is a quicker way.</p>  <p><strong>Solution</strong>    <br />When you select a part of the drawing, it actually gets the corresponding drawing curves appearing in the drawing view and set their line type. So with code, you need to get the curves firstly. Following is a code demo:</p>  <p><font size="2">Sub changeLT()</font></p>  <p>   <br /><font size="2">&#160;&#160;&#160; Dim oDoc As DrawingDocument     <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oEachSheet As Sheet      <br />&#160;&#160;&#160; Dim oEachView As DrawingView      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; For Each oEachSheet In oDoc.Sheets      <br />&#160;&#160;&#160;&#160;&#160; For Each oEachView In oEachSheet.DrawingViews      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;</font><font size="2"><font color="#008000">&#160;&#160; ' if you want to change all drawing curves       <br />&#160;&#160;&#160; ' *****************        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160; Dim oDrwCs As DrawingCurvesEnumerator        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160; Set oDrwCs = oEachView.DrawingCurves()        <br />&#160;&#160;&#160; '        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160; Dim oEachDrwC As DrawingCurve        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160; For Each oEachDrwC In oDrwCs        <br />&#160;&#160;&#160; '        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'change the line type        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEachDrwC.LineType = kDashedHiddenLineType        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' change the line weight        <br />&#160;&#160;&#160; '&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEachDrwC.LineWeight = oEachDrwC.LineWeight * 2        <br />&#160;&#160;&#160; '&#160;&#160; <br />&#160;&#160;&#160; ' ***********************</font>      <br /></font><font size="2"><font color="#008000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; ' if you want to change the curves from specific part, assume the referenced document of        <br />&#160;&#160;&#160; ' the drawing view is from an assembly.        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'get the referenced document</font>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oRefDoc As Document      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oRefDoc = oEachView.ReferencedDocumentDescriptor.ReferencedDocument      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf oRefDoc Is AssemblyDocument Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font size="2"><font color="#008000">&#160;&#160;&#160; ' this is an assemly       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oEachOcc As ComponentOccurrence      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For Each oEachOcc In oRefDoc.ComponentDefinition.Occurrences      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf oEachOcc.Definition.Document Is PartDocument Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font size="2"><font color="#008000"> ' if this is the part you want to change       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oEachOcc.Name = &quot;Part1:1&quot; Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font size="2"><font color="#008000"> 'get the drawing cruves the part generates       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oDrwCs_part As DrawingCurvesEnumerator      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oDrwCs_part = oEachView.DrawingCurves(oEachOcc)      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oDrwC_part As DrawingCurve      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For Each oDrwC_part In oDrwCs_part      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#008000">&#160;&#160;&#160; 'change the line type</font>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrwC_part.LineType = kDashedHiddenLineType      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font size="2"><font color="#008000">&#160;&#160;&#160;&#160; ' change the line weight       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oDrwC_part.LineWeight = oDrwC_part.LineWeight * 2      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160; Next      <br />&#160;&#160;&#160; Next      <br />End Sub</font></p>
