---
layout: "post"
title: "Revolving sketch profile which is closed"
date: "2013-07-10 23:16:37"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2013/07/revolving-sketch-profile-which-is-closed.html "
typepad_basename: "revolving-sketch-profile-which-is-closed"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><strong>Issue</strong>:    <br />I generated programatically a skechs with a series of arcs, straight lines and spline. How can I check through the API that the segments form a closed loop, such that when I use the revole command I will be able to generate a solis from the skech profile?</p>  <p><strong>Solution</strong>:    <br />ProfilePath.Closed tells if the profile is closed or not. The segment from the profile is &quot;ProfileEntity&quot;. You can iterate the ProfilePath object to find all ProfileEntity object. The sample code below accesses the ProfileEntity and create revolve feature. Please note it will create the solid if the profile is closed or the surface if the profile is open.    <br /></p>  <p>Dim oApp As Inventor.Application</p>  <p>Public Sub CreateRevolveFeature()   <br />Set oApp = ThisApplication</p>  <p>Dim oPartDoc As PartDocument   <br />Dim oSketch As PlanarSketch</p>  <p>Set oPartDoc = oApp.ActiveDocument</p>  <p><font color="#00ff00">' Get the sketch you are interested in     <br />' We here select Sketch1...</font>    <br />Set oSketch = oPartDoc.ComponentDefinition.Sketches.Item(1)</p>  <p>Dim oProfile As Profile   <br />On Error Resume Next    <br />Set oProfile = oSketch.Profiles.AddForSolid(True)    <br />If Err.Number &lt;&gt; 0 Then    <br />&#160;&#160; <font color="#00ff00"> ' it appears that the profile is open, so use AddForSurface     <br /></font>&#160;&#160;&#160; Set oProfile = oSketch.Profiles.AddForSurface    <br />&#160;&#160;&#160; Err.Clear    <br />End If</p>  <p>Dim hs As HighlightSet   <br />Set hs = oPartDoc.HighlightSets.Add</p>  <p>Dim oPath As ProfilePath   <br />Set oPath = oProfile.Item(1)</p>  <p>Dim i As Integer   <br />For i = 1 To oPath.Count    <br />&#160;&#160;&#160; Dim oPfEntity As ProfileEntity    <br />&#160;&#160;&#160; Set oPfEntity = oPath.Item(i)    <br />&#160;&#160; <font color="#00ff00"> 'Add a breakpoint here,you can observe the highlighted segments from UI     <br /></font>&#160;&#160;&#160; hs.AddItem oPfEntity.SketchEntity    <br />Next</p>  <p>Dim oTG As TransientGeometry   <br />Set oTG = oApp.TransientGeometry</p>  <p>Dim oLine As SketchLine   <br />Set oLine = oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(0, 0), oTG.CreatePoint2d(0, 10))</p>  <p>Dim oRevFeature As RevolveFeature   <br />&#160; <font color="#00ff00">&#160; 'if the profile is open     <br /></font>If oPath.Closed = False Then    <br />&#160;&#160;&#160; Set oRevFeature = oPartDoc.ComponentDefinition.Features.RevolveFeatures.AddFull(oProfile, oLine, kSurfaceOperation)    <br />Else    <br /><font color="#00ff00">&#160;&#160;&#160; 'if the profile is closed</font>    <br />&#160;&#160;&#160; Set oRevFeature = oPartDoc.ComponentDefinition.Features.RevolveFeatures.AddFull(oProfile, oLine, kJoinOperation)    <br />End If</p>  <p>oApp.ActiveView.Fit   <br />End Sub</p>
