---
layout: "post"
title: "Parent of Mirror Solid"
date: "2014-01-26 19:31:54"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2014/01/parent-of-mirror-solid.html "
typepad_basename: "parent-of-mirror-solid"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>We have two choices when mirroring a solid, either the mirrored body is attached with the original solid, or a new solid is created. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a3fcaa294e970b-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_a02139.jpg" width="282" height="215" /></a></p>      <p>We have two scenarios when mirroring a solid, </p>  <p>1) either the mirrored body is attached with the original solid</p>  <p>2) or a new solid is created </p>  <p>MirrorFeature.MirrorOfBody tells if the mirror feature is from a solid or the features. For scenario 1 above, MirrorFeature. SurfaceBody returns the original solid. For scenario 2, there is not direct API, but we can workaround it by checking the original face of the mirrored face, by which we can get the original solid.</p>  <p>The code below is a small demo. It assumes a mirror feature is selected. It covers the two scenarios.</p>  <p><font size="1"><em>Sub FindOriginalBody()</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Dim oPart As PartDocument</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Set oPart = ThisApplication.ActiveDocument</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160; Dim oPdef As PartComponentDefinition</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Set oPdef = oPart.ComponentDefinition</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Dim oMirrorF As MirrorFeature</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Set oMirrorF = ThisApplication.ActiveDocument.SelectSet(1)</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Dim oFPE As FeaturePatternElement</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Dim oMirrorMatrix As Matrix</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; If oMirrorF.MirrorOfBody Then</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSB As SurfaceBody</em></font></p>  <p><font size="1"><em>‘set end of the feature below the mirror feature</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; oMirrorF.SetEndOfPart True</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; Set oSB = oMirrorF.SurfaceBody</em></font></p>  <p><font size="1"><em>‘set the end of feature back</em></font></p>  <p><font size="1"><em>oPdef.Features(oPdef.Features.Count).SetEndOfPart False</em></font></p>  <p><font size="1"><em>‘scenario 1</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; ' if the mirror feature is built in the same solid</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; If Not oSB Is Nothing Then</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print &quot;the original body for the mirror feature is:&quot; &amp; oSB.Name</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; End If</em></font></p>  <p><font size="1"><em>‘scenario 2</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; 'if the mirror feature is built in a new solid&#160;&#160;&#160;&#160;&#160;&#160;&#160; </em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; Dim oIdentityM As Matrix</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160; Set oIdentityM = ThisApplication.TransientGeometry.CreateMatrix</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160; oIdentityM.SetToIdentity&#160;&#160;&#160; </em></font></p>  <p><font size="1"><em>‘ iterate each item of the mirror elements</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; For Each oFPE In oMirrorF.PatternElements</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' actually only two elements with Mirror feature.</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' one is the original body, the other is the mirror&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oFPE.Transform.IsEqualTo(oIdentityM) = False Then</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' this is the mirror element</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oMirrorMatrix = oFPE.Transform</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160; Next</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oMirrorMatrix.Invert</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oEachF As Face</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oEachBody As SurfaceBody</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' MirrorFeature.Faces contains the faces of mirror feature only</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'just check one face</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oFaceOnMirror As Face</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oFaceOnMirror = oMirrorF.Faces(1)</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oPtInFace As Point</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPtInFace = oFaceOnMirror.PointOnFace</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oPtInFace.TransformBy(oMirrorMatrix)</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error Resume Next</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'find which body contains the orignal face</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For Each oEachBody In oPdef.SurfaceBodies</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oOrignFace As Face</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oOrignFace =        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oEachBody.LocateUsingPoint(kFaceObject, oPtInFace)</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Err.Number = 0 Then</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Not oOrignFace Is Nothing Then</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Debug.Print &quot;the original body for the mirror feature is:&quot; &amp; oEachBody.Name</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'Exit For</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Err.Clear</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </em></font></p>  <p><font size="1"><em>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; End If</em></font></p>  <p><font size="1"><em>End Sub</em></font></p>
