---
layout: "post"
title: "Get Contour of WeldBead"
date: "2014-01-20 03:41:00"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2014/01/get-contour-of-weldbead.html "
typepad_basename: "get-contour-of-weldbead"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>The WeldBead object provides the two faces which generates the weld, and also provides the faces that define the geometric result of the weld bead: <strong>WeldBead.BeadFaces </strong></p>  <p>The following is a small demo that get the faces, add them as a client graphics.</p>  <p><font size="1"><em>Public Sub test()       <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'get document and definition        <br />&#160;&#160;&#160; Dim oDoc As AssemblyDocument        <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument        <br />&#160; <br />&#160;&#160;&#160; Dim oCompDef As AssemblyComponentDefinition        <br />&#160;&#160;&#160; Set oCompDef = oDoc.ComponentDefinition        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'if this is a weld document        <br />&#160;&#160;&#160; If oCompDef.Type = kWeldmentComponentDefinitionObject Then        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim wcd As WeldmentComponentDefinition        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set wcd = oCompDef        <br />&#160;&#160;&#160; Else        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub        <br />&#160;&#160;&#160; End If        <br />&#160;&#160; <br />&#160;&#160;&#160; ' get one weld bead        <br />&#160;&#160;&#160; Dim oWB As WeldBead        <br />&#160;&#160;&#160; Set oWB = wcd.Welds.WeldBeads(1)        <br />&#160; <br />&#160;&#160;&#160; On Error Resume Next        <br />&#160;&#160;&#160; Dim oClientGraphics As ClientGraphics        <br />&#160;&#160;&#160; Set oClientGraphics = oCompDef.ClientGraphicsCollection.Item(&quot;weldbead&quot;)        <br />&#160;&#160;&#160; If Err.Number = 0 Then        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'delete the older client graphics, if any        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oClientGraphics.Delete        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveView.Update        <br />&#160;&#160;&#160; End If        <br />&#160;&#160; <br />&#160;&#160;&#160; Err.Clear        <br />&#160;&#160;&#160; On Error GoTo 0        <br />&#160;&#160; <br />&#160;&#160; ' create a client graphics        <br />&#160;&#160;&#160; Set oClientGraphics = oCompDef.ClientGraphicsCollection.Add(&quot;weldbead&quot;)        <br />&#160;&#160; <br />&#160;&#160;&#160; 'add graphics node        <br />&#160;&#160;&#160; Dim oSurfacesNode As GraphicsNode        <br />&#160;&#160;&#160; Set oSurfacesNode = oClientGraphics.AddNode(1)        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'add the face of WeldBead.BeadFaces        <br />&#160;&#160;&#160; Dim oSurfaceGraphics As SurfaceGraphics        <br />&#160;&#160;&#160; Dim oEachWeldFace As Face        <br />&#160;&#160;&#160; For Each oEachWeldFace In oWB.BeadFaces        <br />&#160;&#160;&#160;&#160;&#160; Set oSurfaceGraphics = oSurfacesNode.AddSurfaceGraphics(oEachWeldFace)        <br />&#160;&#160;&#160; Next        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'set graphics' color. assume “Magenta” exists in the document        <br />&#160;&#160;&#160; oSurfacesNode.Appearance = oDoc.Assets(&quot;Magenta&quot;)        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'transform the client graphics to a location        <br />&#160;&#160;&#160;&#160; Dim oTransGeom As TransientGeometry        <br />&#160;&#160;&#160; Set oTransGeom = ThisApplication.TransientGeometry</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Dim oV As Vector       <br />&#160;&#160;&#160; Set oV = oTransGeom.CreateVector(10, 10, 10)</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; Dim oM As Matrix       <br />&#160;&#160;&#160; Set oM = oTransGeom.CreateMatrix()        <br />&#160;&#160;&#160; Call oM.SetTranslation(oV)</em></font></p>  <p><font size="1"><em>&#160;&#160;&#160; oSurfacesNode.Transformation = oM       <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'update the view        <br />&#160;&#160;&#160; ThisApplication.ActiveView.Update</em></font></p>  <p><font size="1"><em>End Sub</em></font></p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a5112899bd970c-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_7808b0.jpg" width="368" height="198" /></a></p>
