---
layout: "post"
title: "Matrix for complex transformation in model space"
date: "2014-10-06 08:58:12"
author: "Vladimir Ananyev"
categories: []
original_url: "https://adndevblog.typepad.com/manufacturing/2014/10/matrix-for-complex-transformation-in-model-space.html "
typepad_basename: "matrix-for-complex-transformation-in-model-space"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a></p>  <p>Q: I'm trying to create a matrix to do a polar move of block A from point 1 to point 3. In both case the ' axis' of block 'A' stays in line with a vector from the point on the cylinder to the axis through its center. How can I do this?</p>  <p>A: It’s much easier to define separate matrices for rotation and translation and then use the matrix functionality to combine them. Multiplying two matrices together creates a new matrix that contains the transforms of both of them combined. Matrix.TransformBy method can do this for us.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb079382dd970d-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; margin: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="image" src="/assets/image_5035e8.jpg" width="244" height="174" /></a><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d07835d0970c-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="image" src="/assets/image_30e3e6.jpg" width="221" height="173" /></a></p>  <p>The following code sample takes the current matrix for the box and multiplies “rotation” matrix with it. Then the result is transformed by “translation” matrix in the similar way. The order that you multiply matrices makes a difference because the changes are applied in order.</p>  <p>&#160;</p>  <p><font size="1" face="Consolas">Sub Matrix2()</font></p>  <p><font size="1" face="Consolas">Dim oAsmDoc As AssemblyDocument</font></p>  <p><font size="1" face="Consolas">Set oAsmDoc = ThisApplication.ActiveDocument</font></p>  <p><font size="1" face="Consolas">Dim oAsmDef As AssemblyComponentDefinition</font></p>  <p><font size="1" face="Consolas">Set oAsmDef = oAsmDoc.ComponentDefinition</font></p>  <p><font size="1" face="Consolas">Dim oTG As TransientGeometry</font></p>  <p><font size="1" face="Consolas">Set oTG = ThisApplication.TransientGeometry</font></p>  <p><font size="1" face="Consolas">Dim oOccs As ComponentOccurrences</font></p>  <p><font size="1" face="Consolas">Set oOccs = oAsmDef.Occurrences</font></p>  <p><font size="1" face="Consolas">' the 1st component</font></p>  <p><font size="1" face="Consolas">Dim oCylinder As ComponentOccurrence</font></p>  <p><font size="1" face="Consolas">Set oCylinder = oOccs.ItemByName(&quot;Cylinder:1&quot;)</font></p>  <p><font size="1" face="Consolas">' the 2nd component</font></p>  <p><font size="1" face="Consolas">Dim oBox As ComponentOccurrence</font></p>  <p><font size="1" face="Consolas">Set oBox = oOccs.ItemByName(&quot;Box:1&quot;)</font></p>  <p><font size="1" face="Consolas">'Step 1: get the current matrix</font></p>  <p><font size="1" face="Consolas">'&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;</font></p>  <p><font size="1" face="Consolas">'get the current matrix from the box component</font></p>  <p><font size="1" face="Consolas">Dim oMat As Matrix</font></p>  <p><font size="1" face="Consolas">Set oMat = oBox.Transformation</font></p>  <p><font size="1" face="Consolas">'Step 2: add rotation</font></p>  <p><font size="1" face="Consolas">'&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;</font></p>  <p><font size="1" face="Consolas">Dim oMat2 As Matrix</font></p>  <p><font size="1" face="Consolas">Set oMat2 = ThisApplication.TransientGeometry.CreateMatrix</font></p>  <p><font size="1" face="Consolas">'origin point</font></p>  <p><font size="1" face="Consolas">Dim oCenter As Point</font></p>  <p><font size="1" face="Consolas">Set oCenter = oAsmDef.WorkPoints.Item(1).Point</font></p>  <p><font size="1" face="Consolas">'axis of rotation</font></p>  <p><font size="1" face="Consolas">Dim oVector As Vector</font></p>  <p><font size="1" face="Consolas">Set oVector = oAsmDef.WorkAxes.Item(3).Line.Direction.AsVector</font></p>  <p><font size="1" face="Consolas">'angle of rotation</font></p>  <p><font size="1" face="Consolas">Dim Angle As Double</font></p>  <p><font size="1" face="Consolas">Angle = oAsmDef.Parameters.Item(&quot;Angle&quot;).value</font></p>  <p><font size="1" face="Consolas">Call oMat2.SetToRotation(-Angle, oVector, oCenter)</font></p>  <p><font size="1" face="Consolas">'a pre-multiplication of oMat by the matrix oMat2</font></p>  <p><font size="1" face="Consolas">Call oMat.TransformBy(oMat2)</font></p>  <p><font size="1" face="Consolas">'Step 3: add translation</font></p>  <p><font size="1" face="Consolas">'&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;</font></p>  <p><font size="1" face="Consolas">Dim Distance As Double</font></p>  <p><font size="1" face="Consolas">Distance = oAsmDef.Parameters.Item(&quot;Shift&quot;).value 'translation value</font></p>  <p><font size="1" face="Consolas">Call oVector.ScaleBy(-Distance)</font></p>  <p><font size="1" face="Consolas">'apply translation</font></p>  <p><font size="1" face="Consolas">Call oMat2.SetToIdentity</font></p>  <p><font size="1" face="Consolas">Call oMat2.SetTranslation(oVector)</font></p>  <p><font size="1" face="Consolas">Call oMat.TransformBy(oMat2)</font></p>  <p><font size="1" face="Consolas">'Step 4: Create the new instance of the box in the new position defined by oMat</font></p>  <p><font size="1" face="Consolas">'&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;</font></p>  <p><font size="1" face="Consolas">Dim oBox2 As ComponentOccurrence</font></p>  <p><font size="1" face="Consolas">Set oBox2 = oOccs.AddByComponentDefinition(oBox.Definition, oMat)</font></p>  <p><font size="1" face="Consolas">End Sub</font></p>
