---
layout: "post"
title: "Mirror Component in Assembly"
date: "2014-02-09 23:24:15"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2014/02/mirror-component-in-assembly.html "
typepad_basename: "mirror-component-in-assembly"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><strong>Question</strong>:    <br />API allows me to create mirror feature in a part, but it looks not way to create mirror component in an assembly. Is there any method?</p>  <p><strong>Solution</strong>:    <br />This is no direct API function available for this task, but if you observe the built-in behavior of Inventor, you can find the mirror component is actually a derived part from the parent part. So you could create a new file (the derived component) from the parent part, insert the derived component by mirroring about the selected plane.</p>  <p>The challenge is the mirror matrix. There are abundant articles about mirroring(also called reflect transform) on internet. Here is one article I referred to</p>  <p><a href="http://ami.ektf.hu/uploads/papers/finalpdf/AMI_40_from175to186.pdf">http://ami.ektf.hu/uploads/papers/finalpdf/AMI_40_from175to186.pdf</a></p>  <p>and, it indicates the mirror matrix is:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01a51168b329970c-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top: 0px; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_db9e09.jpg" width="394" height="100" /></a></p>  <p>Where, C<sub>x</sub>,<sub> </sub>C<sub>y </sub>C<sub>z </sub>are the normallized values of the workplaneâ€™s normal.</p>  <p>But, it does not consider the translation of the object off the plane. We could just multiply the transformation of the parent component. The following is a small code demo. It assumes a work plane is selected. It mirrors the first component.</p>  <p><em><font size="1">Sub MirrorPartInAss()</font></em></p>  <p><em><font size="1">&#160;&#160;&#160; Dim oAssDoc As AssemblyDocument       <br />&#160;&#160;&#160; Set oAssDoc = ThisApplication.ActiveDocument        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'mirror plane        <br />&#160;&#160;&#160; Dim oMirrorWP As WorkPlane        <br />&#160;&#160;&#160; Set oMirrorWP = oAssDoc.SelectSet(1)        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oPlane As Plane        <br />&#160;&#160;&#160; Set oPlane = oMirrorWP.Plane        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'get normal of the plane        <br />&#160;&#160;&#160; Dim oNormalX As Double        <br />&#160;&#160;&#160; oNormalX = oPlane.Normal.X        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oNormalY As Double        <br />&#160;&#160;&#160; oNormalY = oPlane.Normal.Y        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oNormalZ As Double        <br />&#160;&#160;&#160; oNormalZ = oPlane.Normal.Z        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'create the mirroring matrix        <br />&#160;&#160;&#160; Dim oMirrorMatrix As Matrix        <br />&#160;&#160;&#160; Set oMirrorMatrix = ThisApplication.TransientGeometry.CreateMatrix()        <br />&#160;&#160;&#160; Dim oMatrixData(15) As Double        <br />&#160;&#160;&#160; oMatrixData(0) = 1 - 2 * oNormalX * oNormalX        <br />&#160;&#160;&#160; oMatrixData(1) = -2 * oNormalX * oNormalY        <br />&#160;&#160;&#160; oMatrixData(2) = -2 * oNormalX * oNormalZ        <br />&#160;&#160;&#160; oMatrixData(3) = 0</font></em></p>  <p><em><font size="1">&#160;&#160;&#160; oMatrixData(4) = -2 * oNormalX * oNormalY       <br />&#160;&#160;&#160; oMatrixData(5) = 1 - 2 * oNormalY * oNormalY        <br />&#160;&#160;&#160; oMatrixData(6) = -2 * oNormalZ * oNormalY        <br />&#160;&#160;&#160; oMatrixData(7) = 0</font></em></p>  <p><em><font size="1">&#160;&#160;&#160; oMatrixData(8) = -2 * oNormalX * oNormalZ       <br />&#160;&#160;&#160; oMatrixData(9) = -2 * oNormalZ * oNormalY        <br />&#160;&#160;&#160; oMatrixData(10) = 1 - 2 * oNormalZ * oNormalZ        <br />&#160;&#160;&#160; oMatrixData(11) = 0</font></em></p>  <p><em><font size="1">&#160;&#160;&#160; oMatrixData(12) = 0       <br />&#160;&#160;&#160; oMatrixData(13) = 0        <br />&#160;&#160;&#160; oMatrixData(14) = 0        <br />&#160;&#160;&#160; oMatrixData(15) = 1        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Call oMirrorMatrix.PutMatrixData(oMatrixData)        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'get the first component        <br />&#160;&#160;&#160; Dim oOcc As ComponentOccurrence        <br />&#160;&#160;&#160; Set oOcc = oAssDoc.ComponentDefinition.Occurrences(1)        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; 'multiply with the transformation of the parent component        <br />&#160;&#160;&#160;&#160; oMirrorMatrix.PostMultiplyBy oOcc.Transformation        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim oParentPartPath As String        <br />&#160;&#160;&#160; oParentPartPath = oOcc.Definition.Document.FullFileName        <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; ' Create a new part file to derive the&#160; part in.        <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument        <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))</font></em></p>  <p><em><font size="1">&#160;&#160;&#160;&#160; ' Create a derived definition for the&#160; part.       <br />&#160;&#160;&#160; Dim oDerivedPartDef As DerivedPartTransformDef        <br />&#160;&#160;&#160; Set oDerivedPartDef = oPartDoc.ComponentDefinition.ReferenceComponents.DerivedPartComponents.CreateTransformDef(oParentPartPath)        <br />&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; ' Create the derived part.        <br />&#160;&#160;&#160; Call oPartDoc.ComponentDefinition.ReferenceComponents.DerivedPartComponents.Add(oDerivedPartDef)&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; 'save the derived part.        <br />&#160;&#160;&#160; Call oPartDoc.SaveAs(&quot;c:\temp\mirrorPart.ipt&quot;, False)&#160;&#160;&#160; <br />&#160;&#160; 'add the derived part as a component        <br />&#160;&#160;&#160; Call oAssDoc.ComponentDefinition.Occurrences.Add(oPartDoc.FullFileName, oMirrorMatrix)&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; oPartDoc.Close&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; 'activate the assembly document        <br />&#160;&#160;&#160; oAssDoc.Activate</font></em>    <br /><em><font size="1">End Sub</font></em></p>
