---
layout: "post"
title: "Selecting holes in the drawing view filtered by orientation"
date: "2015-07-31 06:40:50"
author: "Vladimir Ananyev"
categories:
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2015/07/selecting-holes-in-the-drawing-view-filtered-by-orientation.html "
typepad_basename: "selecting-holes-in-the-drawing-view-filtered-by-orientation"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a></p>
<p>Let’s suppose we should select all the hole features on the drawing view that are orthogonal to the view plane.</p>
<p>In other words, for every hole feature that is projected on the drawing view we should check its orientation and if this hole is orthogonal to the drawing view plane we should add all its drawing curve segments to the DrawingDocument.SelectSet collection.</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb085bd144970d-pi"><img alt="image" border="0" height="167" src="/assets/image_1ec826.jpg" style="background-image: none; padding-top: 0px; padding-left: 0px; margin: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="image" width="244" /></a>.</p>
<p>The part model used here has two non-parallel hole features.</p>
<p>There is a pair of places in the code that are worth noting.</p>
<p>1) DrawingView API provides the magic property that returns all the drawing curves within my drawing view filtered to the input model object. Here the HoleFeature objects were used.</p>
<p><span style="font-family: Consolas; font-size: xx-small;">DrawingView.DrawingCurves( [ModelObject] As Variant ) As DrawingCurvesEnumerator</span></p>
<p>2) How we can check if the hole is orthogonal to the view plane or not?&#0160; I did it comparing two vectors. One vector is defined by the view camera orientation. It could be created by two points – Eye and Target.&#0160; Calculations of the second vector depend on the hole placement definition. Here I used the normal to the sketch where the center points were created. Vector.IsParallelTo() method gives the answer if these two vectors are parallel or not. If they are parallel all drawing curve segments projected from this hole feature should be added to the SelectSet collection.</p>
<p>&#0160;</p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000; font-size: xx-small;">Sub HoleSelect()</span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oTG As TransientGeometry</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oTG = ThisApplication.TransientGeometry</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>&#39;active drawing doc</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oDrawDoc As DrawingDocument</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oDrawDoc = ThisApplication.ActiveDocument</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>&#39;active sheet</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oSheet As Sheet</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oSheet = oDrawDoc.ActiveSheet</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>&#39;the 1st drawing view</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oView As DrawingView</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oView = oSheet.DrawingViews.Item(1)</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>&#39;camera</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oCamera As Camera</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oCamera = oView.Camera</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oEye As Point, oTarget As Point</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oEye = oCamera.Eye</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oTarget = oCamera.Target</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oVec As Vector</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oVec = oTG.CreateVector( _</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>oEye.x - oTarget.x, _</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>oEye.y - oTarget.y, _</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>oEye.z - oTarget.z)</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oSSet As SelectSet</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oSSet = oDrawDoc.SelectSet</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Call oSSet.Clear</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>&#39;model document, need to find hole features</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oDoc As PartDocument</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oDoc = oView.ReferencedDocumentDescriptor.ReferencedDocument</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oDef As PartComponentDefinition</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oDef = oDoc.ComponentDefinition</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oHoleFeatures As HoleFeatures</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oHoleFeatures = oDef.Features.HoleFeatures</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>&#39;collection for segments to be selected</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oColl As ObjectCollection</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Set oColl = ThisApplication.TransientObjects.CreateObjectCollection</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Dim oHole As HoleFeature</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160; </span><span style="mso-spacerun: yes;">&#0160;</span>For Each oHole In oHoleFeatures</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Dim oCurves As DrawingCurvesEnumerator</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Set oCurves = oView.DrawingCurves(oHole)</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Debug.Print oHole.name, oCurves.Count</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>If oCurves.Count &gt; 0 Then</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>&#39;this hole feature is seen in the drawing view</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>&#39;so we need to check the hole orientation.</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>&#39;Method depends on the hole placement definition !</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Dim oSketch As PlanarSketch</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Set oSketch = oHole.PlacementDefinition.HoleCenterPoints.Item(1).Parent</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Dim oNormal As UnitVector</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Set oNormal = oSketch.PlanarEntity.Geometry.normal</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>If oVec.IsParallelTo(oNormal.AsVector, 0.0000001) Then</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Debug.Print &quot;Hole is orthogonal&quot;</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>&#39;populate the collection to select segments later</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Dim oCurve As DrawingCurve</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Dim dcs As DrawingCurveSegment</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>For Each oCurve In oCurves</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>For Each dcs In oCurve.Segments</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Call oColl.Add(dcs)</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Next</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Next</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Else</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Debug.Print &quot;Hole is slanted&quot;<span style="mso-spacerun: yes;">&#0160; </span>&#39;do nothing</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>End If</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="mso-spacerun: yes;">&#0160; </span></span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>End If</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Next</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>&#39;select drawing curve segments found</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Beep</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>If oColl.Count &gt; 0 Then</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>Call oSSet.SelectMultiple(oColl)</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>MsgBox &quot;Done :)&quot;</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>Else</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>MsgBox &quot;No orthogonal holes found&quot;</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000;"><span style="font-size: xx-small;"><span style="mso-spacerun: yes;">&#0160;&#0160;&#0160; </span>End If</span></span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="mso-spacerun: yes;"><span style="color: #000000; font-family: Consolas; font-size: xx-small;">&#0160;&#0160;&#0160; </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000; font-size: xx-small;">End Sub</span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;">&#0160;</p>
<p>Output to the Immediate Window:</p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000; font-size: xx-small;">Hole1<span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>8 </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000; font-size: xx-small;">Hole is slanted</span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000; font-size: xx-small;">Hole2<span style="mso-spacerun: yes;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span>2 </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;"><span><span style="font-family: Consolas;"><span style="color: #000000; font-size: xx-small;">Hole is orthogonal </span></span></span></p>
<p class="MsoNoSpacing" style="margin: 0cm 0cm 0pt; line-height: normal;">&#0160;</p>
<p>Selected curves:</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c7b7cc02970b-pi"><img alt="image" border="0" height="158" src="/assets/image_064ecc.jpg" style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border: 0px;" title="image" width="244" /></a></p>
<p><a href="http://adndevblog.typepad.com/files/holeselect.zip">Download HoleSelect</a></p>
