---
layout: "post"
title: "Add Note for Centerline of Work Feature in Drawing"
date: "2015-04-12 20:43:24"
author: "Xiaodong Liang"
categories:
  - "Inventor"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/manufacturing/2015/04/add-note-for-centerline-of-work-feature-in-drawing.html "
typepad_basename: "add-note-for-centerline-of-work-feature-in-drawing"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p>This is a question from a forum post. The customer has the model with some work planes.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c77809d2970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_513b47.jpg" width="394" height="243" /></a></p>  <p>When he inserts the model to a drawing, the [Display Options] allows to include work feature or not.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb081befbf970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_d596b0.jpg" width="404" height="239" /></a></p>  <p>Finally, the work planes can be incldued and displayed in the sheet. </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c7780a6f970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_cf20d5.jpg" width="445" height="188" /></a></p>  <p>However, these lines are not noted. The customer wants to pull the names of each plane from the part and add them along with these lines.</p>  <p>It looks API has not a direct way to enable the name, but such lines are <strong>CenterLine</strong> object in <strong>Sheet</strong>. <strong>Centerline.ModelWorkFeature</strong> tells from which object the center line comes from. So we can get the name from ModelWorkFeature. While the challenge is which object we can create as a note. I think the easiest way would be a <strong>GeneralNote</strong>(DrawingNote). You can simply set its position and formatted text. This is a code demo of VBA. </p>  <p><font size="1">Sub addDrawingNoteForWorkPlane()     <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oDoc As DrawingDocument      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oSheet As Sheet      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oSheet = oDoc.ActiveSheet      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oCenterLine As Centerline      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; For Each oCenterLine In oSheet.Centerlines      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Not oCenterLine.ModelWorkFeature Is Nothing Then      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'select start point or end point as the position for the drawing note      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oPos As Point2d      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oStPos As Point2d      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oStPos = oCenterLine.StartPoint      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oEndPos As Point2d      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oEndPos = oCenterLine.EndPoint      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Math.Abs(oStPos.X - oEndPos.X) &gt; Math.Abs(oStPos.Y - oEndPos.Y) Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' put drawing note at the right of the center line      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oStPos.X &gt; oEndPos.X Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at start point      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oStPos      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at end point      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oEndPos      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' put drawing note at the bottom of the center line      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oStPos.Y &gt; oEndPos.Y Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at end point      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oEndPos      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at start point      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oStPos      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oWP_Name As String      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWP_Name = oCenterLine.ModelWorkFeature.Name      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim sNote As String      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sNote = &quot;&lt;StyleOverride Font='Arial' FontSize='0.2' Bold='True'&gt;&quot; &amp; _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWP_Name &amp; _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;&lt;/StyleOverride&gt;&quot;      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oGeneralNote As GeneralNote      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oGeneralNote = oSheet.DrawingNotes.GeneralNotes.AddFitted(oPos, sNote)      <br />&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next      <br />&#160; <br />&#160;&#160;&#160; End Sub</font></p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c77809d8970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_60f1ef.jpg" width="244" height="230" /></a></p>  <p>The disadvantage of a <strong>GeneralNote</strong> is it is not attached to the center line. So when the center line is change (e.g. the drawing view is moved), the notes cannot be moved accordingly. So we have to delegate OnChange event and move the GeneralNote.</p>  <p>Then I turned to <strong>LeaderNote</strong> which can be attached to a point. You can have the simplest LeaderNote that has not line/arrow. e.g.</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb081befcc970d-pi"><img style="background-image: none; border-right-width: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_0e3fec.jpg" width="244" height="242" /></a></p>  <p>The relevant code is as below. You will need to calculate the best position for the note according to your workflow.</p>  <p><font size="1">Sub addLeaderForWorkPlane()</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Dim oDoc As DrawingDocument</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Dim oTG As TransientGeometry</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Set oTG = ThisApplication.TransientGeometry</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Dim oActiveSheet As Sheet</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Set oActiveSheet = oDoc.ActiveSheet</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Dim oCenterLine As Centerline</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; For Each oCenterLine In oActiveSheet.Centerlines</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Not oCenterLine.ModelWorkFeature Is Nothing Then</font></p>  <p><font size="1"></font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 'select start point or end point as the position for the drawing note</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oPos As Point2d</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oStPos As Point2d</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oStPos = oCenterLine.StartPoint</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oEndPos As Point2d</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oEndPos = oCenterLine.EndPoint</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Math.Abs(oStPos.X - oEndPos.X) &gt; Math.Abs(oStPos.Y - oEndPos.Y) Then</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' put drawing note at the right of the center line</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oStPos.X &gt; oEndPos.X Then</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at start point</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oStPos</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at end point</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oEndPos</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' put drawing note at the bottom of the center line</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If oStPos.Y &gt; oEndPos.Y Then</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at end point</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oEndPos</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' set position of drawing note at start point</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oPos = oStPos</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oWP_Name As String</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWP_Name = oCenterLine.ModelWorkFeature.Name</font></p>  <p><font size="1"></font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oLeaderPoints As ObjectCollection</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oLeaderPoints = ThisApplication.TransientObjects.CreateObjectCollection()</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oLeaderPoints.Add(oTG.CreatePoint2d(oPos.X, oPos.Y))</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Create geometry intent from position</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oGeometryIntent As GeometryIntent</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oGeometryIntent = oActiveSheet.CreateGeometryIntent(oCenterLine, oPos)</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oLeaderPoints.Add(oGeometryIntent)</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' add leader note</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oLeaderNote As LeaderNote</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oActiveSheet.DrawingNotes.LeaderNotes.Add(oLeaderPoints, oWP_Name)</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If</font></p>  <p><font size="1">&#160;&#160;&#160;&#160;&#160;&#160; Next</font></p>  <p><font size="1"></font></p>  <p><font size="1">&#160;&#160; End Sub</font></p>
