---
layout: "post"
title: "Inventor API to Redefine Work Features"
date: "2015-02-28 10:18:00"
author: "Vladimir Ananyev"
categories:
  - "iLogic"
  - "Inventor"
  - "Vladimir Ananyev"
original_url: "https://adndevblog.typepad.com/manufacturing/2015/02/inventor-api-to-redefine-work-features.html "
typepad_basename: "inventor-api-to-redefine-work-features"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/manufacturing/vladimir-ananyev.html">Vladimir Ananyev</a></p>  <p>The work feature collection objects – WorkPoints, WorkAxes, WorkPlanes – provide the wide range of Add methods to create corresponding work features in the part document. Autodesk Inventor API also provides a rich toolset for manipulating existing work features. In particular, you may redefine the existing work feature to re-associate it to another input geometry.</p>  <p>Take for example the work axis Axis1 in a part that was created by the intersection of two planes Plane1 and Plane2.</p> <a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c7567188970b-pi"><img title="Ris_1" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="Ris_1" src="/assets/image_d46505.jpg" width="454" height="252" /></a>   <p>Workaxis.SetByTwoPlanes method allows you to redefine the Axis1 by specifying another pair of work planes – Plane1 and Plane3. </p>  <p><font face="Consolas">Sub RedefineWorkAxis()      <br /></font><font face="Consolas">&#160; Dim oDoc As PartDocument      <br /></font><font face="Consolas">&#160; Set oDoc = ThisApplication.ActiveDocument      <br /></font><font face="Consolas">&#160; Dim oDef As PartComponentDefinition      <br /></font><font face="Consolas">&#160; Set oDef = oDoc.ComponentDefinition      <br /></font><font face="Consolas">&#160; Dim oAxis As WorkAxis      <br /></font><font face="Consolas">&#160; Set oAxis = oDef.WorkAxes.Item(&quot;Axis1&quot;)      <br /></font><font face="Consolas">&#160; Dim oPlane1 As WorkPlane      <br /></font><font face="Consolas">&#160; Set oPlane1 = oDef.WorkPlanes.Item(&quot;Plane1&quot;)      <br /></font><font face="Consolas">&#160; Dim oPlane3 As WorkPlane      <br /></font><font face="Consolas">&#160; Set oPlane3 = oDef.WorkPlanes.Item(&quot;Plane3&quot;)      <br /></font><font face="Consolas">&#160; Call oAxis.SetByTwoPlanes(oPlane1, oPlane3)      <br /></font><font face="Consolas">End Sub</font></p>  <p>Result:<a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d0dfb841970c-pi"><img title="Ris_2" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="Ris_2" src="/assets/image_5973e6.jpg" width="454" height="242" /></a></p>  <p>&#160;</p>  <p>You may redefine work features from iLogic rule as well.    <br />Here is the equivalent iLogic code: </p>  <p><i><font face="Consolas">'parent Part document        <br /></font></i><font face="Consolas"><b>Dim</b> oDoc <b>As</b> PartDocument <b>=</b> <b>ThisDoc</b>.<b>Document        <br /></b></font><i><font face="Consolas">'part document definition        <br /></font></i><font face="Consolas"><b>Dim</b> oDef <b>As</b> PartComponentDefinition <b>=</b> oDoc.ComponentDefinition       <br /></font><i><font face="Consolas">'reference to the existing work axis        <br /></font></i><font face="Consolas"><b>Dim</b> oAxis <b>As</b> WorkAxis <b>=</b> oDef.WorkAxes.Item<b>(</b>&quot;Axis1&quot;<b>)        <br /></b></font><i><font face="Consolas">'1st workplane        <br /></font></i><font face="Consolas"><b>Dim</b> oPlane1 <b>As</b> <b>WorkPlane</b> <b>=</b> oDef.WorkPlanes.Item<b>(</b>&quot;Plane1&quot;<b>)        <br /></b></font><i><font face="Consolas">'2nd workplane        <br /></font></i><font face="Consolas"><b>Dim</b> oPlane3 <b>As</b> <b>WorkPlane</b> <b>=</b> oDef.WorkPlanes.Item<b>(</b>&quot;Plane3&quot;<b>)        <br /></b></font><i><font face="Consolas">'redefine Axis1 to be at the intersection of planes 1 and 3        <br /></font></i><font face="Consolas">oAxis.SetByTwoPlanes<b>(</b>oPlane1, oPlane3<b>)</b></font></p>  <p><strong><font face="Consolas"></font></strong></p>  <p>&#160;</p>  <p>Here is the full list of Add and Set methods available to create and redefine existing work features.</p>  <p>&#160;</p>  <h3>WorkAxis object</h3>  <table cellspacing="0" cellpadding="0" border="1"><tbody>     <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByAnalyticEdge </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByAnalyticEdge </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByLine </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByLine </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByLineAndPlane </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByLineAndPlane </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByLineAndPoint </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByLineAndPoint</font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByNormalToSurface </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByNormalToSurface </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByRevolvedFace </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByRevolvedFace </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByTwoPlanes </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByTwoPlanes </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByTwoPoints </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByTwoPoints </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddFixed </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetFixed</font> </p>       </td>     </tr>   </tbody></table>  <p>&#160;</p>  <h3>WorkPlane</h3>  <table cellspacing="0" cellpadding="0" border="1"><tbody>     <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByLineAndTangent </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByLineAndTangent </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByLinePlaneAndAngle </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByLinePlaneAndAngle </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByNormalToCurve </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByNormalToCurve </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByPlaneAndOffset </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByPlaneAndOffset </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByPlaneAndPoint </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByPlaneAndPoint </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByPlaneAndTangent</font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByPlaneAndTangent </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByPointAndTangent </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByPointAndTangent </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByThreePoints </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByThreePoints </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByTorusMidPlane </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByTorusMidPlane </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByTwoLines </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByTwoLines </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByTwoPlanes </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByTwoPlanes </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddFixed </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetFixed </font></p>       </td>     </tr>   </tbody></table>  <h3>&#160;</h3>  <h3>Workpoint</h3>  <table cellspacing="0" cellpadding="0" border="1"><tbody>     <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddAtCentroid </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetAtCentroid </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByCurveAndEntity </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByCurveAndEntity </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByMidPoint </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByMidPoint </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByPoint </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByPoint </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddBySphereCenterPoint </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetBySphereCenterPoint</font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByThreePlanes </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByThreePlanes </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByTorusCenterPoint </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByTorusCenterPoint </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddByTwoLines </font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetByTwoLines </font></p>       </td>     </tr>      <tr>       <td valign="top" width="413">         <p><font face="Consolas">AddFixed</font></p>       </td>        <td valign="top" width="413">         <p><font face="Consolas">SetFixed</font></p>       </td>     </tr>   </tbody></table>
