---
layout: "post"
title: "Control Rendering Options for Inventor Studio with an Inventor Attribute"
date: "2016-05-24 13:49:32"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2016/05/control-rendering-options-for-inventor-studio-with-an-inventor-attribute.html "
typepad_basename: "control-rendering-options-for-inventor-studio-with-an-inventor-attribute"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p> <p>There is not any Inventor API for Inventor Studio. A work around to control a setting for rendering as shown in this screenshot is to change the value of an Inventor attribute named "com.autodesk.archon.rendering that is stored in the document".</p> <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b7c8626ad0970b-pi"><img title="image" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="image" src="/assets/image_22ddf3.jpg" width="355" height="440"></a>&nbsp; </p> <p>&nbsp;</p> <p>Here is a VBA example that changes the “Render by iteration” setting. </p> <p>&nbsp;</p> <div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black"> <p>Sub InventorStudioRenderOptions_test()<br>&nbsp;&nbsp;&nbsp; Dim oDoc As Document<br>&nbsp;&nbsp;&nbsp; Set oDoc = ThisApplication.ActiveDocument<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; If oDoc.DocumentType &lt;&gt; kPartDocumentObject And _<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oDoc.DocumentType &lt;&gt; kAssemblyDocumentObject Then<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MsgBox "Please open a part or assembly document!"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Exit Sub<br>&nbsp;&nbsp;&nbsp; End If<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Dim oCompDef As ComponentDefinition<br>&nbsp;&nbsp;&nbsp; Set oCompDef = oDoc.ComponentDefinition<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Dim oAttSet As AttributeSet<br>&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; If oCompDef.AttributeSets.NameIsUsed("com.autodesk.archon.rendering") Then<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set oAttSet = oCompDef.AttributeSets("com.autodesk.archon.rendering")<br>&nbsp;&nbsp;&nbsp; Else<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set oAttSet = oCompDef.AttributeSets.Add("com.autodesk.archon.rendering")<br>&nbsp;&nbsp;&nbsp; End If<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Dim oAtt As Inventor.Attribute<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; If oAttSet.NameIsUsed("Options") Then<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set oAtt = oAttSet.Item("Options")</p> <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color="#0000ff">'Get the value of the attribute</font><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim strAttValue As String<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strAttValue = oAtt.Value<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim XDoc As Object<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set XDoc = CreateObject("MSXML2.DOMDocument")<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XDoc.async = False: XDoc.validateOnParse = False<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color="#0000ff">' load the value of the Inventor attribute into the XML doc</font><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XDoc.loadXML strAttValue<br>&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim optionsXMLNodeSel As Object<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set optionsXMLNodeSel = XDoc.selectNodes("Options")<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim optionsXMLElement As IXMLDOMElement<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set optionsXMLElement = optionsXMLNodeSel(0)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim strAtt As String<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strAtt = optionsXMLElement.getAttribute("RayTracingDuration")<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color="#0000ff">' Change the option (XML attribute)<br></font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Call optionsXMLElement.setAttribute("RayTracingDuration", 45)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br><font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'Update the Inventor attribute</font><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oAtt.Value = XDoc.XML</p> <p>&nbsp;&nbsp;&nbsp; Else<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim sWidth As String, sHeight As String<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sWidth = oDoc.Views(1).Width<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sHeight = oDoc.Views(1).Height</p> <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ' Set the Iteration value<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim sIteration As String<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sIteration = "80.0"</p> <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim sValue As String<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sValue = "&lt;?xml version=" &amp; """" &amp; "1.0" &amp; """" &amp; " encoding=" &amp; """" &amp; "UTF-16" &amp; """" &amp; "?&gt;" &amp; vbCrLf<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sValue = sValue &amp; "&lt;Options Version=" &amp; """" &amp; "2" &amp; """" &amp; " RenderW=" &amp; """" &amp; sWidth &amp; """" _<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &amp; " RenderH=" &amp; """" &amp; sHeight &amp; """" &amp; " RayTracingDuration=" &amp; """" &amp; sIteration &amp; """" &amp; "/&gt;"</p> <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set oAtt = oAttSet.Add("Options", kStringType, sValue)<br>&nbsp;&nbsp;&nbsp; End If<br>End Sub<br><font style="background-color: #cccccc"></font></p></div> <p>&nbsp;</p> <p><strong>Here is the example in VB.NET</strong></p> <p>Need to add this imports for the XML objects:</p> <p><em>Imports System.Xml</em></p> <div style="font-size: 10pt; border-top: #000080 1px solid; font-family: consolas, 'Courier New', courier, monospace; border-right: #000080 1px solid; border-bottom: #000080 1px solid; color: #000; border-left: #000080 1px solid"> <div style="overflow: auto; white-space: nowrap; color: #000000; padding-bottom: 2px; padding-top: 2px; padding-left: 5px; padding-right: 5px; max-height: 500px; background-color: #eeeeee"><span style="color: #0000ff">Sub</span> InventorStudioRenderOptions_test()<br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> oDoc <span style="color: #0000ff">As</span> <span style="color: #2b91af">Document</span><br>&nbsp;&nbsp;&nbsp; oDoc = m_inventorApp.ActiveDocument<br><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">If</span> oDoc.DocumentType &lt;&gt; <span style="color: #2b91af">DocumentTypeEnum</span>.kPartDocumentObject <span style="color: #0000ff">And</span> _<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oDoc.DocumentType &lt;&gt; <span style="color: #2b91af">DocumentTypeEnum</span>.kAssemblyDocumentObject <span style="color: #0000ff">Then</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MsgBox(<span style="color: #a31515">"Please open a part or assembly document!"</span>)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Exit Sub</span><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">End</span> <span style="color: #0000ff">If</span><br><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> oCompDef <span style="color: #0000ff">As</span> <span style="color: #2b91af">ComponentDefinition</span><br>&nbsp;&nbsp;&nbsp; oCompDef = oDoc.ComponentDefinition<br><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> oAttSet <span style="color: #0000ff">As</span> <span style="color: #2b91af">AttributeSet</span><br><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">If</span> oCompDef.AttributeSets.NameIsUsed(<span style="color: #a31515">"com.autodesk.archon.rendering"</span>) <span style="color: #0000ff">Then</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oAttSet = oCompDef.AttributeSets(<span style="color: #a31515">"com.autodesk.archon.rendering"</span>)<br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Else</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oAttSet = oCompDef.AttributeSets.Add(<span style="color: #a31515">"com.autodesk.archon.rendering"</span>)<br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">End</span> <span style="color: #0000ff">If</span><br><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> oAtt <span style="color: #0000ff">As</span> Inventor.<span style="color: #2b91af">Attribute</span><br><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">If</span> oAttSet.NameIsUsed(<span style="color: #a31515">"Options"</span>) <span style="color: #0000ff">Then</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oAtt = oAttSet.Item(<span style="color: #a31515">"Options"</span>)<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #008000">'Get the value of the attribute</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> strAttValue <span style="color: #0000ff">As</span> <span style="color: #0000ff">String</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strAttValue = oAtt.Value<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> XDoc <span style="color: #0000ff">As</span> <span style="color: #2b91af">XmlDocument</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XDoc = <span style="color: #0000ff">New</span> <span style="color: #2b91af">XmlDocument</span><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #008000">' load the value of the Inventor attribute into the XML doc</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XDoc.LoadXml(strAttValue)<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> optionsXMLNodeSel <span style="color: #0000ff">As</span> <span style="color: #0000ff">Object</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; optionsXMLNodeSel = XDoc.SelectNodes(<span style="color: #a31515">"Options"</span>)<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> optionsXMLElement <span style="color: #0000ff">As</span> <span style="color: #2b91af">XmlElement</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; optionsXMLElement = optionsXMLNodeSel(0)<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> strAtt <span style="color: #0000ff">As</span> <span style="color: #0000ff">String</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strAtt = optionsXMLElement.GetAttribute(<span style="color: #a31515">"RayTracingDuration"</span>)<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #008000">' Change the option (XML attribute)</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Call</span> optionsXMLElement.SetAttribute(<span style="color: #a31515">"RayTracingDuration"</span>, 45)<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #008000">'Update the Inventor attribute</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oAtt.Value = XDoc.InnerXml<br><br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Else</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> sWidth <span style="color: #0000ff">As</span> <span style="color: #0000ff">String</span>, sHeight <span style="color: #0000ff">As</span> <span style="color: #0000ff">String</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sWidth = oDoc.Views(1).Width<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sHeight = oDoc.Views(1).Height<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #008000">' Set the Iteration value</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> sIteration <span style="color: #0000ff">As</span> <span style="color: #0000ff">String</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sIteration = <span style="color: #a31515">"80.0"</span><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">Dim</span> sValue <span style="color: #0000ff">As</span> <span style="color: #0000ff">String</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sValue = <span style="color: #a31515">"&lt;?xml version="</span> &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">"1.0"</span> &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">" encoding="</span> &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">"UTF-16"</span> &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">"?&gt;"</span> &amp; vbCrLf<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sValue = sValue &amp; <span style="color: #a31515">"&lt;Options Version="</span> &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">"2"</span> &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">" RenderW="</span> &amp; <span style="color: #a31515">""""</span> &amp; sWidth &amp; <span style="color: #a31515">""""</span> _<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &amp; <span style="color: #a31515">" RenderH="</span> &amp; <span style="color: #a31515">""""</span> &amp; sHeight &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">" RayTracingDuration="</span> &amp; <span style="color: #a31515">""""</span> &amp; sIteration &amp; <span style="color: #a31515">""""</span> &amp; <span style="color: #a31515">"/&gt;"</span><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; oAtt = oAttSet.Add(<span style="color: #a31515">"Options"</span>, <span style="color: #2b91af">ValueTypeEnum</span>.kStringType, sValue)<br>&nbsp;&nbsp;&nbsp; <span style="color: #0000ff">End</span> <span style="color: #0000ff">If</span><br><span style="color: #0000ff">End</span> <span style="color: #0000ff">Sub</span></div></div>
