---
layout: "post"
title: "Need to use a Proxy for commands when editing a part in an assembly"
date: "2016-02-18 16:01:58"
author: "Wayne Brill"
categories:
  - "Inventor"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/manufacturing/2016/02/need-to-use-a-proxy-for-commands-when-editing-a-part-in-an-assembly.html "
typepad_basename: "need-to-use-a-proxy-for-commands-when-editing-a-part-in-an-assembly"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/wayne-brill.html" target="_self">Wayne Brill</a></p> <p>In the VBA example below a work plane in a part document is accessed and then the AppLookAtCmd is run. (changes the view to look directly at that WorkPlane) </p> <p>To get AppLookAtCmd to use that WorkPlane it needs to be selected using the SelectSet of the assembly. (not the part) To get the WorkPlane in the assembly space use a WorkPlaneProxy. To create the WorkPlaneProxy use the ActiveOccurrence property of the assembly to get the occurrence of the part that is being edited and then use the CreateGeometryProxy method of the occurrence.&nbsp;&nbsp;&nbsp; </p> <p>Before running this example place a part in an assembly and then right click on the part in the Model browser and select Edit. </p> <p style="font-size: 9pt; font-family: arial; background: #eeeeee; color: black; line-height: 140%">Public Sub selectionTest()<br>&nbsp;&nbsp;&nbsp;&nbsp; <font color="#0000ff">'Get the object currently being edited.<br></font>&nbsp;&nbsp;&nbsp; Dim ActiveObject As Object<br>&nbsp;&nbsp;&nbsp; Set ActiveObject = ThisApplication.ActiveEditObject<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; <font color="#0000ff">'Determine if a the object being edited is a document</font><br>&nbsp;&nbsp;&nbsp; If Not TypeOf ActiveObject Is PartDocument Then<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Exit Sub<br>&nbsp;&nbsp;&nbsp; Else<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim oDoc As Inventor.PartDocument<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set oDoc = ActiveObject<br>&nbsp;&nbsp;&nbsp; End If<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; <font color="#0000ff">'Get the XY Plane of the part being edited<br></font>&nbsp;&nbsp;&nbsp; Dim oWorkPlane As WorkPlane<br>&nbsp;&nbsp;&nbsp; Set oWorkPlane = oDoc.ComponentDefinition.WorkPlanes("XY Plane")<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp; <font color="#0000ff">'Get the active document (an assembly)</font><br>&nbsp;&nbsp;&nbsp; Dim oAsm As AssemblyDocument<br>&nbsp;&nbsp;&nbsp; Set oAsm = ThisApplication.ActiveDocument<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; <font color="#0000ff">' The part that is being edited will be an occurrence</font><br>&nbsp;&nbsp;&nbsp; Dim oOccurrence As ComponentOccurrence<br>&nbsp;&nbsp;&nbsp; Set oOccurrence = oAsm.ComponentDefinition.ActiveOccurrence<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; <font color="#0000ff">' create a WorkPlaneProxy from the work plane in the part</font><br>&nbsp;&nbsp;&nbsp; Dim oWorkPlaneProxy As WorkPlaneProxy<br>&nbsp;&nbsp;&nbsp; oOccurrence.CreateGeometryProxy oWorkPlane, oWorkPlaneProxy<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp; <font color="#0000ff">' Select the WorkPlaneProxy in the assembly</font><br>&nbsp;&nbsp;&nbsp; oAsm.SelectSet.Select oWorkPlaneProxy<br>&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; <font color="#0000ff">' Run the command it will use the work plane (a WorkPlaneProxy)</font><br>&nbsp;&nbsp;&nbsp; ThisApplication.CommandManager.ControlDefinitions.Item("AppLookAtCmd").Execute<br>End Sub </p>
