---
layout: "post"
title: "VBA code to create new Appearance in a Document"
date: "2018-01-15 02:05:24"
author: "Chandra Shekar Gopal"
categories:
  - "Chandra Shekar Gopal"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2018/01/vba-code-to-create-new-appearance-in-a-document.html "
typepad_basename: "vba-code-to-create-new-appearance-in-a-document"
typepad_status: "Publish"
---

<p><span style="font-size: medium;">By </span><a href="http://adndevblog.typepad.com/manufacturing/chandra-shekar-gopal.html" target="_blank" rel="noopener noreferrer"><span style="font-size: medium;">Chandra shekar Gopal</span></a></p>
<p><span style="font-size: medium;">In a Inventor document, An Appearance is a collection of values of different types. In order to create new Appearance, respective AssetValue should be defined and values are assigned. AssetValues would be types like floats, integers, strings, Booleans. Sometimes complex AssetValue types like color, filename(image path name), textures and choices as shown in below image.</span></p>
<p>&nbsp;</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb09e8a506970d-pi"><img width="750" height="635" title="api" style="display: inline; background-image: none;" alt="api" src="/assets/image_31735d.jpg" border="0" /></a></p>
<p><span style="font-size: medium;">The following VBA sample code can be used to create new appearance in a PartDocument. Before running this code, a PartDocument should be opened in Inventor application.</span></p>
<blockquote>
<p>Sub Create_New_Appearance()</p>
<p>&nbsp;&nbsp;&nbsp; Dim oDoc As PartDocument<br />&nbsp;&nbsp;&nbsp;&nbsp; Set oDoc = ThisApplication.ActiveDocument<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim oTG As TransientObjects<br />&nbsp;&nbsp;&nbsp;&nbsp; Set oTG = ThisApplication.TransientObjects<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim docAsset As Assets<br />&nbsp;&nbsp;&nbsp;&nbsp; Set docAsset = oDoc.Assets<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim oAppearance As Asset<br />&nbsp;&nbsp;&nbsp;&nbsp; Set oAppearance = docAsset.Add(kAssetTypeAppearance, "Generic", "Appearences", "New Appearence")<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim generic_color As ColorAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set generic_color = oAppearance.Item("generic_diffuse")<br />&nbsp;&nbsp;&nbsp;&nbsp; generic_color.Value = oTG.CreateColor(255, 95, 15)<br />&nbsp;&nbsp;&nbsp;&nbsp; generic_color.HasConnectedTexture = True<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim generic_texture As AssetTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; Set generic_texture = generic_color.ConnectedTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim generic_image As FilenameAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set generic_image = generic_texture.Item("unifiedbitmap_Bitmap")<br />&nbsp;&nbsp;&nbsp;&nbsp; generic_image.Value = "C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\Textures\2\Mats\272.png"</p>
<p>&nbsp;&nbsp;&nbsp; Dim generic_image_fade As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set generic_image_fade = oAppearance.Item("generic_diffuse_image_fade")<br />&nbsp;&nbsp;&nbsp;&nbsp; generic_image_fade.Value = 0.75<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim generic_glossiness As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set generic_glossiness = oAppearance.Item("generic_glossiness")<br />&nbsp;&nbsp;&nbsp;&nbsp; generic_glossiness.Value = 0.3<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim generic_highlights As BooleanAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set generic_highlights = oAppearance.Item("generic_is_metal")<br />&nbsp;&nbsp;&nbsp;&nbsp; generic_highlights.Value = False<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim reflectivity_direct As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set reflectivity_direct = oAppearance.Item("generic_reflectivity_at_0deg")<br />&nbsp;&nbsp;&nbsp;&nbsp; reflectivity_direct.Value = 0.65<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim reflectivity_oblique As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set reflectivity_oblique = oAppearance.Item("generic_reflectivity_at_90deg")<br />&nbsp;&nbsp;&nbsp;&nbsp; reflectivity_oblique.Value = 0.35<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim transperency_amount As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set transperency_amount = oAppearance.Item("generic_transparency")<br />&nbsp;&nbsp;&nbsp;&nbsp; transperency_amount.Value = 0.62<br />&nbsp;&nbsp;&nbsp;&nbsp; transperency_amount.HasConnectedTexture = True<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim transperency_texture As AssetTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; Set transperency_texture = transperency_amount.ConnectedTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim transperency_image As FilenameAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set transperency_image = transperency_texture.Item("unifiedbitmap_Bitmap")<br />&nbsp;&nbsp;&nbsp;&nbsp; transperency_image.Value = "C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\Textures\2\Mats\532.png"<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim transperency_image_fade As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set transperency_image_fade = oAppearance.Item("generic_transparency_image_fade")<br />&nbsp;&nbsp;&nbsp;&nbsp; transperency_image_fade.Value = 0.65<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim transperency_transluency As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set transperency_transluency = oAppearance.Item("generic_refraction_translucency_weight")<br />&nbsp;&nbsp;&nbsp;&nbsp; transperency_transluency.Value = 0.25<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim transperency_refraction_2 As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set transperency_refraction_2 = oAppearance.Item("generic_refraction_index")<br />&nbsp;&nbsp;&nbsp;&nbsp; transperency_refraction_2.Value = 1.46<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Air&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 1.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Water&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 1.33<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Alcohol&nbsp;&nbsp;&nbsp; -&gt; 1.36<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Quartz&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 1.46<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Glass&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 1.52<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Diamond&nbsp; -&gt; 2.30<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Custom&nbsp;&nbsp;&nbsp; -&gt; Other than the above values<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim cutouts_image As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set cutouts_image = oAppearance.Item("generic_cutout_opacity")<br />&nbsp;&nbsp;&nbsp;&nbsp; cutouts_image.HasConnectedTexture = True<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim cutouts_texture As AssetTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; Set cutouts_texture = cutouts_image.ConnectedTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim cutouts_image_path As FilenameAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set cutouts_image_path = cutouts_texture.Item("unifiedbitmap_Bitmap")<br />&nbsp;&nbsp;&nbsp;&nbsp; cutouts_image_path.Value = "C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\Textures\2\Mats\584.png"<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim self_illum_color As ColorAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set self_illum_color = oAppearance.Item("generic_self_illum_filter_map")<br />&nbsp;&nbsp;&nbsp;&nbsp; self_illum_color.Value = oTG.CreateColor(255, 85, 75)<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim self_illum_luminance As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set self_illum_luminance = oAppearance.Item("generic_self_illum_luminance")<br />&nbsp;&nbsp;&nbsp;&nbsp; self_illum_luminance.Value = 250<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Dim Glow&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 10.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'LED Panel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 100.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'LED Screen&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 140.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Cell phone screen&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 200.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'CRT Television&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 250.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'LampShade Exterior&nbsp; -&gt; 1,300.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'LampShade Interior&nbsp;&nbsp; -&gt; 2,500.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Desk Lamp Lens&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 10,000.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Halogen Lamp Lens&nbsp; -&gt; 10,000.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Frosted Bulb&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 210,000.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Custom&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; Other than the above values<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim self_illum_color_temp As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set self_illum_color_temp = oAppearance.Item("generic_self_illum_color_temperature")<br />&nbsp;&nbsp;&nbsp;&nbsp; self_illum_color_temp.Value = 6000<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Candle&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 1,850.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Incandescent Bulb&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 2,800.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Flood Light&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 3,400.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Moon Light&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 4,100.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Daylight Warm&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 5,000.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Daylight Cool&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 6,000.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Xenon Arc Lamp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 6,420.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'TV Screen&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; 9,320.00<br />&nbsp;&nbsp;&nbsp;&nbsp; 'Custom&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -&gt; Other than the above values<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim bump_image As ColorAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set bump_image = oAppearance.Item("generic_bump_map")<br />&nbsp;&nbsp;&nbsp;&nbsp; bump_image.HasConnectedTexture = True<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim bump_texture As AssetTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; Set bump_texture = bump_image.ConnectedTexture<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim bump_image_path As FilenameAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set bump_image_path = bump_texture.Item("unifiedbitmap_Bitmap")<br />&nbsp;&nbsp;&nbsp;&nbsp; bump_image_path.Value = "C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\Textures\2\Mats\124.png"<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim bump_amount As FloatAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set bump_amount = oAppearance.Item("generic_bump_amount")<br />&nbsp;&nbsp;&nbsp;&nbsp; bump_amount.Value = 0.35<br />&nbsp;&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp;&nbsp;&nbsp; Dim tint_color As ColorAssetValue<br />&nbsp;&nbsp;&nbsp;&nbsp; Set tint_color = oAppearance.Item("common_Tint_color")<br />&nbsp;&nbsp;&nbsp;&nbsp; tint_color.Value = oTG.CreateColor(80, 85, 80)<br />&nbsp;&nbsp;&nbsp;&nbsp; <br /> End Sub</p>
</blockquote>
<p><span style="font-size: medium;">Please refer “Materials and Appearances” overview in the Inventor API Help for additional information on this Appearances.</span></p>
