---
layout: "post"
title: "Copy Model iProperties to Drawing Document via iLogic code"
date: "2018-04-04 03:37:11"
author: "Chandra Shekar Gopal"
categories:
  - "Chandra Shekar Gopal"
  - "iLogic"
  - "Inventor"
original_url: "https://adndevblog.typepad.com/manufacturing/2018/04/copy-model-iproperties-to-drawing-document-via-ilogic-code.html "
typepad_basename: "copy-model-iproperties-to-drawing-document-via-ilogic-code"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/manufacturing/chandra-shekar-gopal.html" rel="noopener noreferrer" target="_blank">Chandra shekar Gopal</a></p>
<p><strong>Question: </strong>Is there any Inventor API to enable <strong>“Copy Model iProperty Settings”</strong> in a Drawing Document as shown in below?</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d2e813fa970c-pi"><img alt="image" border="0" height="789" src="/assets/image_958d39.jpg" style="display: inline; background-image: none;" title="image" width="750" /></a></p>
<p><strong>Answer: </strong>Unfortunately, there is no direct Inventor API to enable <strong>“Copy Model iProperties Settings” </strong>in Drawing Document. But below iLogic code helps to copy iProperties from Model Document to Drawing Document.</p>
<blockquote>
<p>Dim oPropList As ArrayList = New ArrayList()<br />oPropList.Add(&quot;AUTHOR&quot;)<br />oPropList.Add(&quot;AUTHORITY&quot;)<br />oPropList.Add(&quot;CATEGORY&quot;)<br />oPropList.Add(&quot;CHECKED BY&quot;)<br />oPropList.Add(&quot;CHECKED DATE&quot;) <br />oPropList.Add(&quot;COMMENTS&quot;)<br />oPropList.Add(&quot;COMPANY&quot;)<br />oPropList.Add(&quot;COST CENTER&quot;)<br />oPropList.Add(&quot;CREATION DATE&quot;)<br />oPropList.Add(&quot;DESCRIPTION&quot;)<br />oPropList.Add(&quot;DESIGN STATE&quot;)<br />oPropList.Add(&quot;DESIGNER&quot;)<br />oPropList.Add(&quot;ENGR APPROVAL DATE&quot;)<br />oPropList.Add(&quot;ENGR APPROVED BY&quot;)<br />oPropList.Add(&quot;ENGINEER&quot;)<br />oPropList.Add(&quot;ESTIMATED COST&quot;)<br />oPropList.Add(&quot;KEYWORDS&quot;)<br />oPropList.Add(&quot;MANAGER&quot;)<br />oPropList.Add(&quot;MFG APPROVED BY&quot;)<br />oPropList.Add(&quot;MFG APPROVED DATE&quot;)<br />oPropList.Add(&quot;PART NUMBER&quot;)<br />oPropList.Add(&quot;PROJECT&quot;)<br />oPropList.Add(&quot;REVISION NUMBER&quot;)<br />oPropList.Add(&quot;STATUS&quot;)<br />oPropList.Add(&quot;STOCK NUMBER&quot;)<br />oPropList.Add(&quot;SUBJECT&quot;)<br />oPropList.Add(&quot;TITLE&quot;)<br />oPropList.Add(&quot;VENDOR&quot;)<br />oPropList.Add(&quot;WEBLINK&quot;)</p>
<p>sel_iProperty = InputListBox(&quot;CHOOSE iPROPERTY FROM ABOVE LIST&quot;, oPropList, oPropList.Item(0), &quot;iPROPERTY SELECTION&quot;, &quot;LIST OF iPROPERTY&quot;)</p>
<p>oRefDoc = ThisDrawing.ModelDocument</p>
<p><br />Dim oPropValue As String</p>
<p>Select Case sel_iProperty</p>
<p>Case &quot;AUTHOR&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Summary Information&quot;).Item(&quot;Author&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Author&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)</p>
<p>Case &quot;AUTHORITY&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Authority&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Authority&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;CATEGORY&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Document Summary Information&quot;).Item(&quot;Category&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Category&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;CHECKED BY&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Checked By&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Checked By&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;CHECKED DATE&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Date Checked&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Date Checked&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;COMMENTS&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Summary Information&quot;).Item(&quot;Comments&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Comments&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;COMPANY&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Document Summary Information&quot;).Item(&quot;Company&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Company&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;COST CENTER&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Cost Center&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Cost Center&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;CREATION DATE&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Creation Time&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Creation Time&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;DESCRIPTION&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Description&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Description&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;DESIGN STATE&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Design Status&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Design Status&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;DESIGNER&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Designer&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Designer&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;ENGR APPROVAL DATE&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Engr Date Approved&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Engr Date Approved&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;ENGR APPROVED BY&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Engr Approved By&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Engr Approved By&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;ENGINEER&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Engineer&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Engineer&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;ESTIMATED COST&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Cost&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Cost&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;KEYWORDS&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Summary Information&quot;).Item(&quot;Keywords&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Keywords&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;MANAGER&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Document Summary Information&quot;).Item(&quot;Manager&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Manager&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;MFG APPROVED BY&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Mfg Approved By&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Mfg Approved By&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;MFG APPROVED DATE&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Mfg Date Approved&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Mfg Date Approved&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;PART NUMBER&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Part Number&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Part Number&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;PROJECT&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Project&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Project&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;REVISION NUMBER&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Summary Information&quot;).Item(&quot;Revision Number&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Revision Number&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;STATUS&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;User Status&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;User Status&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;STOCK NUMBER&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Stock Number&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Stock Number&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;SUBJECT&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Summary Information&quot;).Item(&quot;Subject&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Subject&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;TITLE&quot;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Summary Information&quot;).Item(&quot;Title&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Summary&quot;, &quot;Title&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;VENDOR&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Vendor&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Vendor&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />Case &quot;WEBLINK&quot;<br />&#0160;&#0160;&#0160;&#0160; oPropValue = oRefDoc.PropertySets(&quot;Design Tracking Properties&quot;).Item(&quot;Catalog Web Link&quot;).value <br />&#0160;&#0160;&#0160;&#0160; iProperties.Value(&quot;Project&quot;, &quot;Catalog Web Link&quot;) = oPropValue<br />&#0160;&#0160;&#0160;&#0160; MessageBox.Show(sel_iProperty + &quot; iProperty updated successfully with value : &quot; + oPropValue, &quot;iProperty&quot;)<br />End Select</p>
</blockquote>
<p>On running above iLogic code, a Input list box appears for selection of iProperty as shown in below image.</p>
<p><a class="asset-img-link" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d2e81431970c-pi" style="display: inline;"><img alt="IProperty selection" border="0" class="asset  asset-image at-xid-6a0167607c2431970b01b8d2e81431970c img-responsive" src="/assets/image_29defc.jpg" title="IProperty selection" /></a></p>
<p>After selecting iProperty from list and clicking “OK” button, respective value of iProperty from Model document will be copied to Drawing document.</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01b8d2e813fa970c-pi">&#0160;</a></p>
