---
layout: "post"
title: "Specifying text alignment"
date: "2012-12-20 19:29:26"
author: "Daniel Du"
categories:
  - ".NET"
  - "2012"
  - "2013"
  - "AutoCAD"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/autocad/2012/12/specifying-text-alignment.html "
typepad_basename: "specifying-text-alignment"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/daniel-du.html">Daniel Du</a></p>  <p><b>Issue</b></p>  <p>How do I set up or change a text entity's alignment?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>When aligning text you need to use the TextAlignmentPoint property as shown in    <br />the following sample code:</p>  <pre style="line-height: normal; widows: 2; text-transform: none; text-indent: 0px; letter-spacing: normal; font-family: ; orphans: 2; color: ; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px"><font color="#000000">Public Sub test()<br />   Dim Text As AcadText<br />   Dim curnam As String<br />   Dim inpt(0 To 2) As Double<br />   Dim ht As Double<br />   <br />   curnam = &quot;This is a string&quot;<br />   inpt(0) = 5<br />   inpt(1) = 5<br />   inpt(2) = 0<br />  <br />   ht = 0.5<br />   <br />   Set Text = ThisDrawing.ModelSpace.AddText(curnam, inpt, ht)<br />   Text.Alignment = acAlignmentMiddleCenter<br />   Text.TextAlignmentPoint = inpt<br />End Sub</font></pre>

<p>&#160;</p>

<p>For .net API, you can use DBText.AlignmentPoint property.Following information comes from the .net API document:</p>

<p>This function sets pt to be the alignment point for the text object. </p>

<p>If vertical mode is AcDb::kTextBase and horizontal mode is either AcDb::kTextLeft, AcDb::kTextAlign, or AcDb::kTextFit, then the <a href="mk:@MSITStore:C:%5CObjectARX%202012%5Cdocs%5Carxref.chm::/AcDbText__position.html">position</a> point (DXF group code 10) is the insertion point for the text object and, for AcDb::kTextLeft, the alignment point is automatically calculated based on the other parameters in the text object. Any setting made by this function are replaced by the newly calculated value. </p>

<p>For all other vertical and horizontal mode combinations, the alignment point is used as the insertion point of the text and the <a href="mk:@MSITStore:C:%5CObjectARX%202012%5Cdocs%5Carxref.chm::/AcDbText__position.html">position</a> point is automatically calculated based on the other parameters in the text object. </p>

<p>The alignment point value is the WCS equivalent of DXF group code 11. </p>

<p>Returns Acad::eOk if successful, or Acad::eNotApplicable if the text object's horizontal mode is AcDb::kTextLeft and vertical mode is AcDb::kTextBase. </p>

<p>Here is the code in .net API:</p>

<pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><span style="color: "><font color="#0000ff"><font style="font-size: 7.8pt">public</font></font></span><font style="font-size: 7.8pt"><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">void</font></span><font color="#000000"> MyCommand() </font><span style="color: "><font color="#008000">// This method can have any name</font></span><br /></font></font><font style="font-size: 7.8pt"><font face="新宋体"><font color="#000000">{<br />&#160;&#160;&#160; </font><span style="color: "><font color="#2b91af">Document</font></span><font color="#000000"> doc = </font><span style="color: "><font color="#2b91af">Application</font></span></font><font face="新宋体"><font color="#000000">.DocumentManager.MdiActiveDocument;<br />&#160;&#160;&#160; </font><span style="color: "><font color="#2b91af">Editor</font></span></font><font face="新宋体"><font color="#000000"> ed = doc.Editor;<br />&#160;&#160;&#160; </font><span style="color: "><font color="#2b91af">Database</font></span></font><font face="新宋体"><font color="#000000"> db = doc.Database;<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">//align point</font></span><br /><font color="#000000">&#160;&#160;&#160; </font><span style="color: "><font color="#2b91af">Point3d</font></span><font color="#000000"> pt = </font><span style="color: "><font color="#0000ff">new</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#2b91af">Point3d</font></span></font><font face="新宋体"><font color="#000000">(15, 15, 0);<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">using</font></span><font color="#000000"> (</font><span style="color: "><font color="#2b91af">DBText</font></span><font color="#000000"> text = </font><span style="color: "><font color="#0000ff">new</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#2b91af">DBText</font></span></font><font face="新宋体"><font color="#000000">())<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.TextString = </font><span style="color: "><font color="#a31515">&quot;This is a db text&quot;</font></span></font><font face="新宋体"><font color="#000000">;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.VerticalMode = </font><span style="color: "><font color="#2b91af">TextVerticalMode</font></span></font><font face="新宋体"><font color="#000000">.TextVerticalMid;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.HorizontalMode = </font><span style="color: "><font color="#2b91af">TextHorizontalMode</font></span></font><font face="新宋体"><font color="#000000">.TextCenter;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.AlignmentPoint = pt;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; AddToModelSpace(text, db);<br />&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />}<br /> </font><br /><span style="color: "><font color="#0000ff">private</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">static</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">void</font></span><font color="#000000"> AddToModelSpace(</font><span style="color: "><font color="#2b91af">Entity</font></span><font color="#000000"> ent, </font><span style="color: "><font color="#2b91af">Database</font></span></font><font face="新宋体"><font color="#000000"> db)<br />{<br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">using</font></span><font color="#000000"> (</font><span style="color: "><font color="#2b91af">Transaction</font></span></font><font face="新宋体"><font color="#000000"> trans = db.TransactionManager.StartTransaction())<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#2b91af">BlockTable</font></span><font color="#000000"> bt = (</font><span style="color: "><font color="#2b91af">BlockTable</font></span></font><font face="新宋体"><font color="#000000">)trans.GetObject(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.BlockTableId, </font><span style="color: "><font color="#2b91af">OpenMode</font></span></font><font face="新宋体"><font color="#000000">.ForRead);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span></font><font face="新宋体"><font color="#000000"> modelSpace = trans.GetObject(<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bt[</font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span></font><font face="新宋体"><font color="#000000">.ModelSpace], <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForWrite) </font><span style="color: "><font color="#0000ff">as</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span></font></font><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000">;<br /> <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; modelSpace.AppendEntity(ent);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.AddNewlyCreatedDBObject(ent, </font><span style="color: "><font color="#0000ff">true</font></span><font color="#000000">);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit();<br />&#160;&#160;&#160; }<br />}</font></font></font></pre>

<p>Hope this helps!</p>
