---
layout: "post"
title: "How to copy cells from one Table to another in .NET?"
date: "2012-06-28 09:26:00"
author: "Marat Mirgaleev"
categories:
  - ".NET"
  - "2012"
  - "2013"
  - "AutoCAD"
  - "Marat Mirgaleev"
original_url: "https://adndevblog.typepad.com/autocad/2012/06/how-to-copy-cells-from-one-table-to-another-in-net.html "
typepad_basename: "how-to-copy-cells-from-one-table-to-another-in-net"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/marat-mirgaleev.html" target="_self">Marat Mirgaleev</a></p>  <p>Q: <em>Is there any way to copy the contents of several rows/cells to another Table?</em></p>  <p>&#160;</p>  <p>A: Yes. You need to use the Table.CopyFrom method and pass two CellRange objects to it.    <br />The following command copies two rows from a selected table to a new table.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: green">// Copy some cells from a table to a new one.</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">//=================================================================</span></p>    <p style="margin: 0px"><span style="line-height: 140%">[</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;_copyCells&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> copyCells()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">PromptEntityOptions</span><span style="line-height: 140%"> opts = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptEntityOptions</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;\nSelect a Table: &quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; opts.SetRejectMessage(</span><span style="line-height: 140%; color: #a31515">&quot;This is not a Table.&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; opts.AddAllowedClass(</span><span style="line-height: 140%; color: blue">typeof</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">Table</span><span style="line-height: 140%">), </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; opts.AllowNone = </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">PromptEntityResult</span><span style="line-height: 140%"> res = ed.GetEntity(opts);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (res.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">PromptPointResult</span><span style="line-height: 140%"> pr = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Editor.GetPoint(</span><span style="line-height: 140%; color: #a31515">&quot;\nEnter table insertion point: &quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (pr.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =doc.TransactionManager.StartTransaction())</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%"> bt = tr.GetObject(doc.Database.BlockTableId, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> ms = tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bt[</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">.ModelSpace],</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Table</span><span style="line-height: 140%"> sourceTb = tr.GetObject(res.ObjectId, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Table</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Create a new Table</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Table</span><span style="line-height: 140%"> newTb = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Table</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; newTb.TableStyle = doc.Database.Tablestyle;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; newTb.SetSize(8, 5); </span><span style="line-height: 140%; color: green">/* In previous versions of AutoCAD </span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; * we did it like this:</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newTb.NumRows = 8;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newTb.NumColumns = 5; */</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; newTb.Position = pr.Value;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Copy two last rows from the selected table to the new one</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; newTb.CopyFrom(sourceTb, </span><span style="line-height: 140%; color: #2b91af">TableCopyOptions</span><span style="line-height: 140%">.FillTarget,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">CellRange</span><span style="line-height: 140%">.Create(sourceTb, sourceTb.Rows.Count-2, 0,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sourceTb.Rows.Count-1, sourceTb.Columns.Count-1),</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">CellRange</span><span style="line-height: 140%">.Create(newTb, 3, 0, 4, sourceTb.Columns.Count-1));</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; newTb.GenerateLayout();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; newTb.Cells[1, 1].Style = newTb.Cells[1, 1].Style;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; ms.AppendEntity(newTb);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(newTb, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">} </span><span style="line-height: 140%; color: green">// End of copyCells()</span></p>    <p style="margin: 0px"></p> </div>
