---
layout: "post"
title: "VBA: How to setup selectionset filters for a block or layer?"
date: "2012-07-24 09:23:50"
author: "Philippe Leefsma"
categories:
  - "ActiveX"
  - "AutoCAD"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/autocad/2012/07/vba-how-to-setup-selectionset-filters-for-a-block-or-layer.html "
typepad_basename: "vba-how-to-setup-selectionset-filters-for-a-block-or-layer"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p>  <p><b>Q:</b></p>  <p>How do I use a selection set filter to select a block with a particular name   <br />that is on a particular layer ?</p>  <p><a name="section2"></a></p>  <p><b>A:</b></p>  <p>The following sample code allows you to select blocks based on this criteria:</p>  <p>1. selectALayer() - create a selectionset with entities on &quot;layer1&quot;   <br />2. selectABlock() - create a selectionset with a block insert &quot;testBlock&quot;    <br />3. selectABlockOnALayer() - create a selectionset with a block insert &quot;testBlock&quot; on &quot;layer1&quot;</p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;">     <br /><font face="Courier New"><font style="font-size: 8pt" color="#000000">Sub selectALayer()</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160; Dim sset As AcadSelectionSet         <br />&#160;&#160; Set sset = ThisDrawing.SelectionSets.Add(&quot;TestSet1&quot;)          <br />&#160;&#160; <br />&#160;&#160; Dim filterType As Variant          <br />&#160;&#160; Dim filterData As Variant          <br />&#160;&#160; Dim p1(0 To 2) As Double          <br />&#160;&#160; Dim p2(0 To 2) As Double          <br />&#160;&#160; <br />&#160;&#160; Dim grpCode(0) As Integer          <br />&#160;&#160; grpCode(0) = 8          <br />&#160;&#160; filterType = grpCode          <br />&#160;&#160; Dim grpValue(0) As Variant          <br />&#160;&#160; grpValue(0) = &quot;Layer1&quot;          <br />&#160;&#160; filterData = grpValue          <br />&#160;&#160;&#160; <br />&#160;&#160; sset.Select acSelectionSetAll, p1, p2, filterType, filterData          <br />&#160;&#160; <br />&#160;&#160; Debug.Print &quot;Entities: &quot; &amp; str(sset.count)          <br />&#160;&#160; <br />&#160;&#160; sset.Delete          <br />&#160;&#160; <br />End Sub</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font color="#000000" face="Courier New"></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Courier New"><font style="font-size: 8pt" color="#000000">Sub selectABlock()</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160; Dim sset As AcadSelectionSet         <br />&#160;&#160; Set sset = ThisDrawing.SelectionSets.Add(&quot;TestSet2&quot;)          <br />&#160;&#160; <br />&#160;&#160; Dim filterType As Variant          <br />&#160;&#160; Dim filterData As Variant          <br />&#160;&#160; Dim p1(0 To 2) As Double          <br />&#160;&#160; Dim p2(0 To 2) As Double          <br />&#160;&#160; <br />&#160;&#160; Dim grpCode(0) As Integer          <br />&#160;&#160; grpCode(0) = 2          <br />&#160;&#160; filterType = grpCode          <br />&#160;&#160; Dim grpValue(0) As Variant          <br />&#160;&#160; grpValue(0) = &quot;testBlock&quot;          <br />&#160;&#160; filterData = grpValue          <br />&#160;&#160;&#160; <br />&#160;&#160; sset.Select acSelectionSetAll, p1, p2, filterType, filterData          <br />&#160;&#160; <br />&#160;&#160; Debug.Print &quot;Entities: &quot; &amp; str(sset.count)          <br />&#160;&#160; <br />&#160;&#160; sset.Delete          <br />&#160;&#160; <br />End Sub</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font color="#000000" face="Courier New"></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Courier New"><font style="font-size: 8pt" color="#000000">Sub selectABlockOnALayer()</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt; background: #dddddd; tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt" class="MsoNormal"><span style="font-family: ; color: ; mso-fareast-font-family: &#39;Times New Roman&#39;"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160; Dim sset As AcadSelectionSet         <br />&#160;&#160; Set sset = ThisDrawing.SelectionSets.Add(&quot;TestSet3&quot;)          <br />&#160;&#160; <br />&#160;&#160; Dim filterType As Variant          <br />&#160;&#160; Dim filterData As Variant          <br />&#160;&#160; Dim p1(0 To 2) As Double          <br />&#160;&#160; Dim p2(0 To 2) As Double          <br />&#160;&#160; <br />&#160;&#160; Dim grpCode(0 To 1) As Integer          <br />&#160;&#160; grpCode(0) = 8          <br />&#160;&#160; grpCode(1) = 2          <br />&#160;&#160; filterType = grpCode          <br />&#160;&#160; <br />&#160;&#160; Dim grpValue(0 To 1) As Variant          <br />&#160;&#160; grpValue(0) = &quot;layer1&quot;          <br />&#160;&#160; grpValue(1) = &quot;testBlock&quot;          <br />&#160;&#160; filterData = grpValue          <br />&#160;&#160; <br />&#160;&#160; sset.Select acSelectionSetAll, p1, p2, filterType, filterData          <br />&#160;&#160; <br />&#160;&#160; Debug.Print &quot;Entities: &quot; &amp; str(sset.count)          <br />&#160;&#160; <br />&#160;&#160; sset.Delete          <br />&#160;&#160; <br />End Sub</font></font></span></p>  <p style="line-height: normal; margin: 0in 0in 0pt" class="MsoNormal"><font face="Calibri"><font style="font-size: 11pt" color="#000000">&#160;</font></font></p>
