---
layout: "post"
title: "Creating a Selection Set using COM Interop"
date: "2012-07-20 05:05:48"
author: "Marat Mirgaleev"
categories:
  - ".NET"
  - "2010"
  - "2011"
  - "2012"
  - "2013"
  - "AutoCAD"
  - "Marat Mirgaleev"
original_url: "https://adndevblog.typepad.com/autocad/2012/07/creating-a-selection-set-using-com-interop.html "
typepad_basename: "creating-a-selection-set-using-com-interop"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/marat-mirgaleev.html" target="_self">Marat Mirgaleev</a></p>  <p><b>Issue</b></p>  <p><em>I'm migrating my VBA code to VB.NET and getting an exception in the AcadSelectionSet.Select(). What am I doing wrong?</em></p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>This is a sample how to select all entities on a given layer:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> FilterType(0) </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Int16 </span><span style="line-height: 140%; color: green">' IMPORTANT: The type must be Int16, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' otherwise you'll get an exception!</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> FilterData(0) </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Object</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> objSS </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Autodesk.AutoCAD.Interop.AcadSelectionSet = </span><span style="line-height: 140%; color: blue">Nothing</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">Try</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; FilterType(0) = 8</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Will select all entities with the given Layer name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; FilterData(0) = </span><span style="line-height: 140%; color: #a31515">&quot;MyLayer&quot;</span><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">' It's the layer name</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> acadApp </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Autodesk.AutoCAD.Interop.AcadApplication = _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.ApplicationServices.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Application.AcadApplication</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; objSS = acadApp.Documents.Application.ActiveDocument.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; SelectionSets.Add(</span><span style="line-height: 140%; color: #a31515">&quot;MySet&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; objSS.Clear()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; objSS.Select(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.Interop.Common.AcSelect.acSelectionSetAll, _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; , , FilterType, FilterData)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; objSS.Highlight(</span><span style="line-height: 140%; color: blue">True</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; MsgBox(objSS.Count &amp; </span><span style="line-height: 140%; color: #a31515">&quot; entities selected.&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">Catch</span><span style="line-height: 140%"> ex </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> Exception</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; MsgBox(ex.Message)</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">Finally</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Not</span><span style="line-height: 140%"> objSS </span><span style="line-height: 140%; color: blue">Is</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Nothing</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; objSS.Delete()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Try</span></p> </div>
