---
layout: "post"
title: "Showing part of the model space in a .NET Form/Dialog"
date: "2012-05-28 04:03:05"
author: "Adam Nagy"
categories:
  - ".NET"
  - "Adam Nagy"
  - "AutoCAD"
original_url: "https://adndevblog.typepad.com/autocad/2012/05/showing-part-of-the-model-space-in-a-net-formdialog.html "
typepad_basename: "showing-part-of-the-model-space-in-a-net-formdialog"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/adam-nagy.html" target="_self">Adam Nagy</a></p>  <p>I would like to show a certain part of the model space in my .NET Form. Is it possible?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>Yes it is. </p>  <p>In the following sample I created a Form called ViewForm and placed a Panel on it called ViewPanel, then used the following code to show a certain part of the model space on it:</p>  <div style="font-family: Courier New; font-size: 8pt; color: black; background: white;"> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Imports</span><span style="line-height: 140%;"> acApp = Autodesk.AutoCAD.ApplicationServices.</span><span style="color: #2b91af; line-height: 140%;">Application</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Imports</span><span style="line-height: 140%;"> Autodesk.AutoCAD.ApplicationServices</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Imports</span><span style="line-height: 140%;"> Autodesk.AutoCAD.GraphicsSystem</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Imports</span><span style="line-height: 140%;"> GI = Autodesk.AutoCAD.GraphicsInterface</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Imports</span><span style="line-height: 140%;"> Autodesk.AutoCAD.DatabaseServices</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Imports</span><span style="line-height: 140%;"> Autodesk.AutoCAD.Geometry</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Public</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Class</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">ViewForm</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> device </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Device</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> view </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">View</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> model </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Model</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> Form_OnLoad( _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> sender </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> System.</span><span style="color: #2b91af; line-height: 140%;">Object</span><span style="line-height: 140%;">, _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> e </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> System.</span><span style="color: #2b91af; line-height: 140%;">EventArgs</span><span style="line-height: 140%;">) _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Handles</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">MyBase</span><span style="line-height: 140%;">.Load</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> doc </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Document</span><span style="line-height: 140%;"> = </span><span style="color: #2b91af; line-height: 140%;">acApp</span><span style="line-height: 140%;">.DocumentManager.MdiActiveDocument</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> db </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Database</span><span style="line-height: 140%;"> = doc.Database</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> gsm </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Manager</span><span style="line-height: 140%;"> = doc.GraphicsManager</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' Create a device that will draw into our panel</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; device = gsm.CreateAutoCADDevice(ViewPanel.Handle)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' Create a view and add it to the device</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; view = </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">View</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; device.Add(view)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; device.Update()</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">Using</span><span style="line-height: 140%;"> tr </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Transaction</span><span style="line-height: 140%;"> = _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; db.TransactionManager.StartTransaction()</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; model = gsm.CreateAutoCADModel()</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> bt </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">BlockTable</span><span style="line-height: 140%;"> = _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; tr.GetObject(db.BlockTableId, </span><span style="color: #2b91af; line-height: 140%;">OpenMode</span><span style="line-height: 140%;">.ForRead)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> ms </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">BlockTableRecord</span><span style="line-height: 140%;"> = _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; tr.GetObject( _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bt(</span><span style="color: #2b91af; line-height: 140%;">BlockTableRecord</span><span style="line-height: 140%;">.ModelSpace), </span><span style="color: #2b91af; line-height: 140%;">OpenMode</span><span style="line-height: 140%;">.ForRead)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' Add the model space to the view</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; view.Add(ms, model)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' Make sure that the area that you want to show </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' lies between these two points</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; view.ZoomExtents( _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Point3d</span><span style="line-height: 140%;">(-10, -10, 0), </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Point3d</span><span style="line-height: 140%;">(200, 200, 0))</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' In case you want to show some solids in shaded mode</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; view.Mode = _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; Autodesk.AutoCAD.GraphicsSystem.</span><span style="color: #2b91af; line-height: 140%;">RenderMode</span><span style="line-height: 140%;">.GouraudShaded</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; view.VisualStyle = _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> GI.</span><span style="color: #2b91af; line-height: 140%;">VisualStyle</span><span style="line-height: 140%;">(GI.</span><span style="color: #2b91af; line-height: 140%;">VisualStyleType</span><span style="line-height: 140%;">.GouraudWithEdges)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' Just to make sure that not perspective but parallel </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' mode is used</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; view.SetView(view.Position, view.Target, _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; view.UpVector, view.FieldWidth, _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; &nbsp; &nbsp; view.FieldHeight, </span><span style="color: #2b91af; line-height: 140%;">Projection</span><span style="line-height: 140%;">.Parallel)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Using</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> Panel_OnPaint( _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> sender </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> System.</span><span style="color: #2b91af; line-height: 140%;">Object</span><span style="line-height: 140%;">, _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> e </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> System.Windows.Forms.</span><span style="color: #2b91af; line-height: 140%;">PaintEventArgs</span><span style="line-height: 140%;">) _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Handles</span><span style="line-height: 140%;"> ViewPanel.Paint</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' Redraw the view</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; view.Invalidate()</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; view.Update()</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> Form_OnClosing( _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> sender </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> System.</span><span style="color: #2b91af; line-height: 140%;">Object</span><span style="line-height: 140%;">, _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> e </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> System.Windows.Forms.</span><span style="color: #2b91af; line-height: 140%;">FormClosingEventArgs</span><span style="line-height: 140%;">) _</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">Handles</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">MyBase</span><span style="line-height: 140%;">.FormClosing</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: green; line-height: 140%;">' Call dispose to free the underlying ObjectARX objects</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; device.Dispose()</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; view.Dispose()</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; model.Dispose()</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Class</span></p> </div>   <p>If you'd like to see a more comprehensive solution then please have a look at the <a href="http://through-the-interface.typepad.com/through_the_interface/2008/06/autocad-net-ver.html">BlockView.NET sample project</a></p>
