---
layout: "post"
title: "MEASURE command in a lisp function is inconsistent"
date: "2012-12-07 06:33:27"
author: "Philippe Leefsma"
categories:
  - "AutoCAD"
  - "LISP"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/autocad/2012/12/measure-command-in-a-lisp-function-is-inconsistent.html "
typepad_basename: "measure-command-in-a-lisp-function-is-inconsistent"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p>  <p><b>Q:</b></p>  <p>I am using the measure&quot; command in a lisp routine. On some polylines the first mark is incorrect for example if I use 10 for the distance the first mark is not 10 units from the begining of the line. Here is the code I am trying to use:</p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt"><span style="color: #ff0000">(</span>Defun c:test <span style="color: #ff0000">(</span><span style="color: #0000ff">/</span><span style="color: #ff0000">)</span>       <br />&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> lineData <span style="color: #ff0000">(</span><span style="color: #0000ff">entsel</span>&#160;<span style="color: #ff00ff">&quot;\nSelect a line:&quot;</span><span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lineObj&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">car</span> lineData<span style="color: #ff0000">)</span>       <br />&#160;&#160; <span style="color: #ff0000">)</span>&#160;<span style="background-color: #e6e6e6; color: #800080">;_ end of setq        <br /></span>&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">command</span>&#160;<span style="color: #ff00ff">&quot;measure&quot;</span> lineObj&#160; <span style="color: #008000">10</span><span style="color: #ff0000">)</span>       <br /><span style="color: #ff0000">)</span>&#160;<span style="background-color: #e6e6e6; color: #800080">;_ end of Defun</span></span></p>  <p><a name="section2"></a></p>  <p><b>A:</b></p>  <p>When you manually use the MEASURE command it starts adding the points nearest to the end of the line where you selected. There does not seem to be a way to consistently control which end of the line the command MEASURE starts measuring from when the entity name is passed to the command in the lisp routine instead of selecting the entity. Another approach to consider would be to use vlax-curve-getPointAtDist. This example places points along the selected polyline at the same location as the Measure command would with a distance of 10. </p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt"><span style="color: #ff0000">(</span>Defun c:test <span style="color: #ff0000">(</span><span style="color: #0000ff">/</span><span style="color: #ff0000">)</span>       <br />&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vl-load-com</span><span style="color: #ff0000">)</span>       <br />&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> acadDoc&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-get-ActiveDocument</span>&#160;<span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-get-Acad-Object</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; mSpace&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-get-modelspace</span> acadDoc<span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; entData&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">entsel</span>&#160;<span style="color: #ff00ff">&quot;\nSelect a polyline:&quot;</span><span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; spdata&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">car</span> entData<span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plineHandle <span style="color: #ff0000">(</span><span style="color: #0000ff">cdr</span>&#160;<span style="color: #ff0000">(</span><span style="color: #0000ff">assoc</span>&#160;<span style="color: #008000">5</span>&#160;<span style="color: #ff0000">(</span><span style="color: #0000ff">entget</span> spData<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plineObj&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-handleToObject</span> acadDoc plineHandle<span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; endSpline&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-curve-getEndParam</span> plineObj<span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pLength&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-curve-getDistAtParam</span> plineObj endSpline<span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; numOfPoints <span style="color: #ff0000">(</span>fix <span style="color: #ff0000">(</span><span style="color: #0000ff">/</span> pLength <span style="color: #008000">10</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>       <br />&#160; <span style="color: #ff0000">)</span>&#160;<span style="background-color: #e6e6e6; color: #800080">;setq        <br /></span>&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> count <span style="color: #008000">1</span><span style="color: #ff0000">)</span>       <br />&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">repeat</span> numOfPoints       <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> dist <span style="color: #ff0000">(</span>* <span style="color: #008000">10</span> count<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> pnt1 <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-curve-getPointAtDist</span> plineObj dist<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-addpoint</span> mspace <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-</span>3d-Point pnt1<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>       <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> count <span style="color: #ff0000">(</span>+ count <span style="color: #008000">1</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>       <br />&#160; <span style="color: #ff0000">)</span>&#160;<span style="background-color: #e6e6e6; color: #800080">;repeat        <br /></span><span style="color: #ff0000">)</span>       <br /></span></p>  <p>The MEASURE command will also allow you to insert a block along the line. The example below inserts a block named &quot;testBlock&quot; and rotates it so that it is close to the rotation of the angle at that point along the line. This could be changed to get a higher degree of accuracy for the angle. You could get a point that is a little behind and a little ahead to determine the required angle.</p>  <p>NOTE: There is no error checking, and the block named &quot;testBlock&quot; needs to be available in the drawing. </p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt"><span style="color: #ff0000">(</span>Defun c:test <span style="color: #ff0000">(</span><span style="color: #0000ff">/</span><span style="color: #ff0000">)</span>      <br />&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vl-load-com</span><span style="color: #ff0000">)</span>      <br />&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> acadDoc&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-get-ActiveDocument</span>&#160;<span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-get-Acad-Object</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; mSpace&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-get-modelspace</span> acadDoc<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; entData&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">entsel</span>&#160;<span style="color: #ff00ff">&quot;\nSelect a polyline:&quot;</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; spdata&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">car</span> entData<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plineHandle <span style="color: #ff0000">(</span><span style="color: #0000ff">cdr</span>&#160;<span style="color: #ff0000">(</span><span style="color: #0000ff">assoc</span>&#160;<span style="color: #008000">5</span>&#160;<span style="color: #ff0000">(</span><span style="color: #0000ff">entget</span> spData<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plineObj&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-handleToObject</span> acadDoc plineHandle<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; endSpline&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-curve-getEndParam</span> plineObj<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pLength&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-curve-getDistAtParam</span> plineObj endSpline<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; numOfPoints <span style="color: #ff0000">(</span>fix <span style="color: #ff0000">(</span><span style="color: #0000ff">/</span> pLength <span style="color: #008000">10</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160; <span style="color: #ff0000">)</span>&#160;<span style="background-color: #e6e6e6; color: #800080">;setq       <br /></span>&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> count <span style="color: #008000">1</span><span style="color: #ff0000">)</span>      <br />&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">repeat</span> numOfPoints      <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> dist <span style="color: #ff0000">(</span>* <span style="color: #008000">10</span> count<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> pnt1 <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-curve-getPointAtDist</span> plineObj dist<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> dist2 <span style="color: #ff0000">(</span>+ dist 0.1<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>&#160; <br />&#160;&#160;&#160; <span style="background-color: #e6e6e6; color: #800080">;; get a sample point that is 0.1 ahead of the point that will </span></span></p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt"><span style="background-color: #e6e6e6; color: #800080">&#160;&#160;&#160; ;;be used for insertion       <br /></span>&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> pnt2 <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-curve-getPointAtDist</span> plineObj dist2<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; <span style="background-color: #e6e6e6; color: #800080">;; get the angle between the insertion point and the sample point       <br /></span>&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> ang1 <span style="color: #ff0000">(</span>angle pnt1 pnt2<span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">vla-insertblock</span> mspace <span style="color: #ff0000">(</span><span style="color: #0000ff">vlax-</span>3d-Point pnt1<span style="color: #ff0000">)</span>&#160;<span style="color: #ff00ff">&quot;testBlock&quot;</span> 1.0 1.0 1.0 ang1<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; <span style="color: #ff0000">(</span><span style="color: #0000ff">setq</span> count <span style="color: #ff0000">(</span>+ count <span style="color: #008000">1</span><span style="color: #ff0000">)</span><span style="color: #ff0000">)</span>      <br />&#160; <span style="color: #ff0000">)</span>&#160;<span style="background-color: #e6e6e6; color: #800080">;repeat       <br /></span><span style="color: #ff0000">)</span>      <br /></span></p>  <pre><br /></pre>
