---
layout: "post"
title: "Inserting a block with attributes to modelspace"
date: "2012-06-18 10:45:07"
author: "Madhukar Moogala"
categories:
  - ".NET"
  - "AutoCAD"
  - "Stephen Preston"
original_url: "https://adndevblog.typepad.com/autocad/2012/06/inserting-a-block-with-attributes-to-modelspace.html "
typepad_basename: "inserting-a-block-with-attributes-to-modelspace"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/stephen-preston.html">Stephen Preston</a></p>  <p>The definition of a block is stored in a BlockTableRecord. If that block has attributes, these are stored in the BlockTableRecord as AttributeDefinitions – just like any other entity is stored in the BlockTableRecord.</p>  <p>When we insert a block into a drawing (e.g. into modelspace), we insert a BlockReference. If the block has attributes, then each (non-constant) AttributeDefinition in the BlockTableRecord has a matching AttributeReference attached to the BlockReference. Constant attributes are treated slightly differently because their text is constant across all instances of the block (across all BlockReferences). They are stored in the BlockTableRecord, and there is no corresponding AttributeReference&#160; attached to the BlockReference.</p>  <p>Here is some simple C# code to insert an instance of a block with attributes into model space. Create a drawing containing a block definition named “CHECK” that has several attributes (some constant, some non-constant) to test the code.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%">[</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;AddBlockTest&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> AddBlockTest()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db = </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument.Database;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> myT = db.TransactionManager.StartTransaction())</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Get the block definition &quot;Check&quot;.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> blockName = </span><span style="line-height: 140%; color: #a31515">&quot;CHECK&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%"> bt = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.BlockTableId.GetObject(</span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> blockDef = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; bt[blockName].GetObject(</span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Also open modelspace - we'll be adding our BlockReference to it</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> ms = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; bt[</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">.ModelSpace].GetObject(</span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite) </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Create new BlockReference, and link it to our block definition</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> point = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(2.0, 4.0, 6.0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">BlockReference</span><span style="line-height: 140%"> blockRef = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">BlockReference</span><span style="line-height: 140%">(point, blockDef.ObjectId))</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Add the block reference to modelspace</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ms.AppendEntity(blockRef);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; myT.AddNewlyCreatedDBObject(blockRef, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Iterate block definition to find all non-constant </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// AttributeDefinitions</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> id </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%">&#160; blockDef)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBObject</span><span style="line-height: 140%"> obj = id.GetObject( </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">AttributeDefinition</span><span style="line-height: 140%"> attDef = obj </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AttributeDefinition</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> ((attDef != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">) &amp;&amp; (!attDef.Constant))</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//This is a non-constant AttributeDefinition </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Create a new AttributeReference</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">AttributeReference</span><span style="line-height: 140%"> attRef = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AttributeReference</span><span style="line-height: 140%">())</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; attRef.SetAttributeFromBlock(attDef, blockRef.BlockTransform);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; attRef.TextString = </span><span style="line-height: 140%; color: #a31515">&quot;Hello World&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Add the AttributeReference to the BlockReference</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; blockRef.AttributeCollection.AppendAttribute(attRef);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; myT.AddNewlyCreatedDBObject(attRef, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Our work here is done</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; myT.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div>  <p>I recommend installing and using the <a href="http://adndevblog.typepad.com/autocad/2012/04/dwg-debugger-mgddbg-app-for-autocad-20122013.html">MdgDbg utility</a> to better understand how objects are stored in the DWG Database.</p>
