---
layout: "post"
title: "Setting the bulge of a polyline using ActiveX in LISP"
date: "2012-09-27 02:39:00"
author: "Xiaodong Liang"
categories:
  - "ActiveX"
  - "AutoCAD"
  - "LISP"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/autocad/2012/09/setting-the-bulge-of-a-polyline-using-activex-in-lisp.html "
typepad_basename: "setting-the-bulge-of-a-polyline-using-activex-in-lisp"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>
<p><strong>Issue      <br /></strong>This is the Visual LISP code I have used to set a bulge for a polyline:</p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;">Command: !pline      <br />#       <br />Command: !mspace       <br />#       <br />Command: <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-SetBulge</span> mSpace pline <span style="color: #008000;">0</span> 0.5<span style="color: #ff0000;">)</span>       <br /><span style="background-color: #e6e6e6; color: #800080;">; error: ActiveX Server returned the error: unknown name: SetBulge        <br /></span>Command: <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-put-SetBulge</span> pline <span style="color: #008000;">0</span> 0.5<span style="color: #ff0000;">)</span>       <br /><span style="background-color: #e6e6e6; color: #800080;">; error: no function definition: VLA-PUT-SETBULGE        <br /></span>Command: <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-invoke-method</span> mspace &#39;setbulge pline <span style="color: #008000;">0</span> 0.5<span style="color: #ff0000;">)</span>       <br /><span style="background-color: #e6e6e6; color: #800080;">; error: ActiveX Server returned the error: unknown name: SETBULGE        <br /></span>Command: <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-put-property</span> pline &#39;setbulge <span style="color: #008000;">0</span> 0.5<span style="color: #ff0000;">)</span>       <br /><span style="background-color: #e6e6e6; color: #800080;">; error: ActiveX Server returned an error: Type mismatch</span></span></p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;"><span style="background-color: #e6e6e6; color: #800080;">&#0160;</span></span></p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;"><span style="background-color: #e6e6e6; color: #800080;">&#0160;</span></span></p>
<p>What is the correct syntax to use? </p>
<p><strong>Solution</strong>     <br />The documentation contains the information to answer this question. In the AutoCAD ActiveX and VBA Reference, go to Object Model -&gt; Polyline Object -&gt; SetBulge Method. </p>
<p>Then refer to the Visual LISP Developer&#39;s Guide: Using Visual LISP Functions with ActiveX Methods -&gt; <a href="http://exchange.autodesk.com/autocad/enu/online-help/search#WS73099cc142f4875516d84be10ebc87a53f-7bfc.htm">Determining How to Call a Function</a>.</p>
<p>After reading these two references, you should notice that SetBulge is a method of the polyline object, not a Property nor a Method of the Model Space Collection (which is what the preceding code shows). </p>
<p>You&#39;ll find that the following code will set the bulge of a Polyline Object: </p>
<p>(vla-SetBulge myPolyObj 1 -0.42080) </p>
<p>Because it is easier to see this in context, code was copied from , and modified it to use the SetBulge method for a polyline:</p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;"><span style="color: #ff0000;">(</span><span style="color: #0000ff;">vl-load-com</span><span style="color: #ff0000;">)</span>      <br /><span style="color: #ff0000;">(</span><span style="color: #0000ff;">defun</span> a_Polyline_wArc<span style="color: #ff0000;">(</span><span style="color: #ff0000;">)</span>      <br />      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> acadapp <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-get-Acad-Object</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160; acaddoc <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-get-ActiveDocument</span> acadapp<span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160; *ModelSpace*&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-get-ModelSpace</span> acaddoc<span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">)</span>      <br />      <br />      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> pt1 <span style="color: #ff0000;">(</span>list 2.93905 1.87048 0.0<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> pt2 <span style="color: #ff0000;">(</span>list 5.54349 4.81627 0.0<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> pt3 <span style="color: #ff0000;">(</span>list 8.78096 4.97892 0.0<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> pt4 <span style="color: #ff0000;">(</span>list 12.6153 1.20181 0.0<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> Points <span style="color: #ff0000;">(</span><span style="color: #0000ff;">apply</span> &#39;append <span style="color: #ff0000;">(</span>list pt1 pt2 pt3 pt4<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> ptlstlen <span style="color: #ff0000;">(</span>length Points<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> PointDataA <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-make-safearray</span> vlax-vbDouble <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">0</span>&#0160;<span style="color: #ff0000;">(</span>1- ptlstlen<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-safearray-fill</span> PointDataA Points<span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> PointData <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-make-variant</span> PointDataA <span style="color: #ff0000;">(</span>logior vlax-vbarray      <br />vlax-vbDouble<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> myPolyObj <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-addPolyline</span> *ModelSpace* PointData<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-Put-Color</span> myPolyObj acBlue<span style="color: #ff0000;">)</span>      <br />      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> strtWidth 1.0 endWidth 1.0 verticies <span style="color: #ff0000;">(</span>1- <span style="color: #ff0000;">(</span><span style="color: #0000ff;">/</span> ptlstlen <span style="color: #008000;">3</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span> indx <span style="color: #008000;">0</span><span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">while</span>&#0160;<span style="color: #ff0000;">(</span>&lt; indx verticies<span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-SetWidth</span> myPolyObj indx strtWidth endWidth<span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> indx <span style="color: #ff0000;">(</span><span style="color: #0000ff;">1+</span> indx<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-SetBulge</span> myPolyObj <span style="color: #008000;">1</span> -0.42080<span style="color: #ff0000;">)</span>      <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-Update</span> myPolyObj<span style="color: #ff0000;">)</span>      <br />&#0160;&#0160; <br />&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span><span style="color: #ff0000;">)</span>      <br /><span style="color: #ff0000;">)</span>      <br /><span style="background-color: #e6e6e6; color: #800080;">; <span style="color: #ff0000;">(</span>a_Polyline_wArc<span style="color: #ff0000;">)</span></span></span></p>
