---
layout: "post"
title: "Setting the Lineweight of a Line in .NET"
date: "2012-06-05 10:49:49"
author: "Madhukar Moogala"
categories:
  - ".NET"
  - "AutoCAD"
  - "Stephen Preston"
original_url: "https://adndevblog.typepad.com/autocad/2012/06/setting-the-lineweight-of-a-line-in-net.html "
typepad_basename: "setting-the-lineweight-of-a-line-in-net"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/stephen-preston.html">Stephen Preston</a></p>  <p>Here’s a simple example, originally posted by <a href="http://adndevblog.typepad.com/autocad/fenton-webb.html">Fenton</a> on the ADN website,&#160; showing how to set the lineweight of a line as you’re adding it to the currently active space (model or paper):</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%">[Autodesk.AutoCAD.Runtime.</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;CreateLine&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">// creates a line and sets the lineweight for it, </span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">//&#160; by Fenton Webb, DevTech, Autodesk</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> CreateLine()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// create a new line</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> line =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(0, 0, 0), </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(100, 100, 0));</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// set the lineweight for it</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; line.LineWeight = </span><span style="line-height: 140%; color: #2b91af">LineWeight</span><span style="line-height: 140%">.LineWeight211;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// add the object to the current space</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument.Database;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// make sure lineweights are turned on</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; db.LineWeightDisplay = </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// start a new transaction</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> myT = db.TransactionManager.StartTransaction())</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// get the current space and open it for write</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)myT.GetObject(db.CurrentSpaceId,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite, </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// add line to the blocktable record</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(line);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// now to the tranaction manager</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; myT.AddNewlyCreatedDBObject(line, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// all ok, lets commit it</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; myT.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">catch</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Handle errors</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div>
