---
layout: "post"
title: "Freeze and Thaw layers in a paperspace viewport"
date: "2012-05-10 16:58:29"
author: "Wayne Brill"
categories:
  - ".NET"
  - "AutoCAD"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/autocad/2012/05/freeze-and-thaw-layers-in-a-paperspace-viewport.html "
typepad_basename: "freeze-and-thaw-layers-in-a-paperspace-viewport"
typepad_status: "Publish"
---

<p>This VB.NET example shows how to freeze or thaw a layer in a layout viewport using the FreezeLayersInViewport() and ThawLayersInViewport() methods. These methods take an ObjectIdCollection which is a collection of ObjectId for the layers to freeze or thaw. </p>  <p>By <a href="http://adndevblog.typepad.com/autocad/wayne-brill.html" target="_self">Wayne Brill</a></p>  <div style="font-family: consolas; background: white; color: black; font-size: 10pt">   <p style="margin: 0px">&lt;CommandMethod(<span style="color: #a31515">&quot;VPFreezeandThaw&quot;</span>)&gt; _</p>    <p style="margin: 0px"><span style="color: blue">Public</span> <span style="color: blue">Sub</span> VPFreezeandThaw()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> doc <span style="color: blue">As</span> <span style="color: #2b91af">Document</span> = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> ed <span style="color: blue">As</span> <span style="color: #2b91af">Editor</span> = doc.Editor</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> db <span style="color: blue">As</span> <span style="color: #2b91af">Database</span> = doc.Database</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> idLay <span style="color: blue">As</span> <span style="color: #2b91af">ObjectId</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> idLayTblRcd <span style="color: blue">As</span> <span style="color: #2b91af">ObjectId</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> lt <span style="color: blue">As</span> <span style="color: #2b91af">LayerTable</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> tm <span style="color: blue">As</span> Autodesk.AutoCAD.ApplicationServices. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">TransactionManager</span> = db.TransactionManager</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> ta <span style="color: blue">As</span> <span style="color: #2b91af">Transaction</span> = tm.StartTransaction()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; idLay = db.LayerTableId</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lt = ta.GetObject(idLay, <span style="color: #2b91af">OpenMode</span>.ForRead)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> lt.Has(<span style="color: #a31515">&quot;wbtest&quot;</span>) <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; idLayTblRcd = lt.Item(<span style="color: #a31515">&quot;wbtest&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;Layer - wbtest not available&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Return</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> idCol <span style="color: blue">As</span> <span style="color: #2b91af">ObjectIdCollection</span> = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">New</span> <span style="color: #2b91af">ObjectIdCollection</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; idCol.Add(idLayTblRcd)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Check that we are in paper space </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> vpid <span style="color: blue">As</span> <span style="color: #2b91af">ObjectId</span> = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.CurrentViewportObjectId</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> vpid.IsNull() <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;No Viewport current.&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Return</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'VP need to be open for write </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oViewport <span style="color: blue">As</span> <span style="color: #2b91af">Viewport</span> = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tm.GetObject(vpid, <span style="color: #2b91af">OpenMode</span>.ForWrite)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> <span style="color: blue">Not</span> oViewport.IsLayerFrozenInViewport _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (idLayTblRcd) <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oViewport.FreezeLayersInViewport _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (idCol.GetEnumerator())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oViewport.ThawLayersInViewport _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (idCol.GetEnumerator())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ta.Commit()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Finally</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ta.Dispose()</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Sub</span></p> </div>
