---
layout: "post"
title: "Why Some Methods in C# fail with an Error &quot;cannot explicitly call operator or accessor&quot;?"
date: "2012-05-09 23:06:22"
author: "Barbara Han"
categories:
  - ".NET"
  - "2010"
  - "2011"
  - "2012"
  - "2013"
  - "Barbara Han"
original_url: "https://adndevblog.typepad.com/autocad/2012/05/why-some-methods-in-c-fail-with-an-error-cannot-explicitly-call-operator-or-accessor.html "
typepad_basename: "why-some-methods-in-c-fail-with-an-error-cannot-explicitly-call-operator-or-accessor"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/barbara-han.html" target="_self">Barbara Han</a></p>  <p>When using C# in .NET., one developer got an error â€œ&quot;cannot explicitly call operator or accessor&quot; when he tried to build his project that uses certain functions. Both utodesk.AutoCAD.DatabaseServices.Entity.get_LayerId and Autodesk.AutoCAD.DatabaseServices.Entity.get_Layer fail with this error.</p>  <p>The reason is that you should not use any get_ methods. To get an entity's layer name, use the Entity.Layer property instead, as demonstrated in the following sample: </p>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">// Modal Command with localized name</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; [</font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">CommandMethod</font></span><font color="#000000">(</font><span style="color: "><font color="#a31515">&quot;MyGroup&quot;</font></span><font color="#000000">, </font><span style="color: "><font color="#a31515">&quot;MyCommand&quot;</font></span><font color="#000000">, </font><span style="color: "><font color="#a31515">&quot;MyCommandLocal&quot;</font></span><font color="#000000">, </font><span style="color: "><font color="#2b91af">CommandFlags</font></span><font color="#000000">.Modal)]</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">public</font></span><font color="#000000"> </font><span style="color: "><font color="#0000ff">void</font></span><font color="#000000"> MyCommand() </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">// This method can have any name</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">// Put your command code here</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">Document</font></span><font color="#000000"> curDoc = </font><span style="color: "><font color="#2b91af">Application</font></span><font color="#000000">.DocumentManager.MdiActiveDocument;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">Database</font></span><font color="#000000"> db = curDoc.Database;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.DatabaseServices.</font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">TransactionManager</font></span><font color="#000000"> tm = db.TransactionManager;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">using</font></span><font color="#000000"> (</font><span style="color: "><font color="#2b91af">Transaction</font></span><font color="#000000"> myT = tm.StartTransaction())</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">BlockTable</font></span><font color="#000000"> bt = (</font><span style="color: "><font color="#2b91af">BlockTable</font></span><font color="#000000">)tm.GetObject(db.BlockTableId, </font><span style="color: "><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForRead, </font><span style="color: "><font color="#0000ff">false</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">BlockTableRecord</font></span><font color="#000000"> btr = (</font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span><font color="#000000">)tm.GetObject(bt[</font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span><font color="#000000">.ModelSpace], </font><span style="color: "><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForRead,</font><span style="color: "><font color="#0000ff">false</font></span><font color="#000000">);</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">foreach</font></span><font color="#000000"> (</font><span style="color: "><font color="#2b91af">ObjectId</font></span><font color="#000000"> acObjId </font><span style="color: "><font color="#0000ff">in</font></span><font color="#000000"> btr)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#2b91af">Entity</font></span><font color="#000000"> ent = (</font><span style="color: "><font color="#2b91af">Entity</font></span><font color="#000000">)myT.GetObject(acObjId, </font><span style="color: "><font color="#2b91af">OpenMode</font></span><font color="#000000">.ForRead); </font></font></font></p>    <div style="font-family: ; background: white; color: ">     <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">string</font></span><font color="#000000"> myLayName;</font></font></font></p>      <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; myLayName = ent.Layer;</font></font></p>   </div>    <p style="margin: 0px"></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000"></font></font></p>   <font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font>        <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; myT.Commit();</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; }&#160;&#160;&#160; </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></p> </div>  <p>This is same for other methods, for example get_LinetypeScale(). </p>  <div style="font-family: ; background: white; color: ">   <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span style="color: "><font color="#0000ff">double</font></span><font color="#000000"> myScale;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">//myScale = ent.get_LinetypeScale();</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span style="color: "><font style="font-size: 8pt" color="#008000">//Use .LinetypeScale instead</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; myScale = ent.LinetypeScale;</font></font></p> </div>
