---
layout: "post"
title: "Changing xref paths from absolute to relative"
date: "2012-07-25 17:07:32"
author: "Madhukar Moogala"
categories:
  - ".NET"
  - "AutoCAD"
  - "Stephen Preston"
original_url: "https://adndevblog.typepad.com/autocad/2012/07/changing-xref-paths-from-absolute-to-relative.html "
typepad_basename: "changing-xref-paths-from-absolute-to-relative"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/stephen-preston.html">Stephen Preston</a></p>  <p>I was just checking recent comments on the blog (as part of my ongoing war on spammers <img style="border-bottom-style: none; border-right-style: none; border-top-style: none; border-left-style: none" class="wlEmoticon wlEmoticon-smile" alt="Smile" src="/assets/image_756045.jpg" />), and noticed a new comment by Gautham <a href="http://adndevblog.typepad.com/autocad/2012/06/finding-all-xrefs-in-the-current-database-using-cnet.html" target="_blank">on an old post of mine</a> which reminded me I’d forgotten to respond to the original question he asked about that post.</p>  <p>To change the path of an xref from absolute to relative, you simply have to edit the BlockTableRecord.PathName to a string that defines the relative path you need (or to have no path at all, if you want to rely on FindFile to locate your Xref). Here’s some simple code written by <a href="http://adndevblog.typepad.com/autocad/balaji-ramamoorthy.html">Balaji</a> in response to a similar question from an ADN partner:</p>  <div style="font-family: consolas; background: white; color: black; font-size: 14pt">   <p style="margin: 0px"><font size="2">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;ChangeXRefPath&quot;</span>)] </font></p>    <p style="margin: 0px"><font size="2"><span style="color: blue">public</span> <span style="color: blue">void</span> ChangeXRefPathMethod() </font></p>    <p style="margin: 0px"><font size="2">{</font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: #2b91af">Document</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument; </font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: #2b91af">Editor</span> ed = doc.Editor; </font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: #2b91af">ObjectIdCollection</span> collection = <span style="color: blue">new</span> <span style="color: #2b91af">ObjectIdCollection</span>(); </font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Database</span> db = <span style="color: blue">new</span> <span style="color: #2b91af">Database</span>(<span style="color: blue">false</span>, <span style="color: blue">true</span>)) </font></p>    <p style="margin: 0px"><font size="2">&#160; { </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; db.ReadDwgFile(<span style="color: #a31515">&quot;c:\\Temp\\Test.dwg&quot;</span>, </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">FileOpenMode</span>.OpenForReadAndWriteNoShare, <span style="color: blue">false</span>, <span style="color: #a31515">&quot;&quot;</span>); </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> tr = db.TransactionManager.StartTransaction()) </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; { </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">BlockTable</span> bt = tr.GetObject(db.BlockTableId, <span style="color: #2b91af">OpenMode</span>.ForRead) </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">as</span> <span style="color: #2b91af">BlockTable</span>; </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">ObjectId</span> btrId <span style="color: blue">in</span> bt) </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; { </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> btr = tr.GetObject(btrId, <span style="color: #2b91af">OpenMode</span>.ForRead) </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">as</span> <span style="color: #2b91af">BlockTableRecord</span>; </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (btr.IsFromExternalReference) </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; { </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.UpgradeOpen(); </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">String</span> oldPath = btr.PathName;</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">String</span> newPath = oldPath.Replace(<span style="color: #a31515">@&quot;C:\Temp&quot;</span>, <span style="color: #a31515">&quot;.&quot;</span>); </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.PathName = newPath; </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; collection.Add(btrId); </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #2b91af">String</span>.Format(<span style="color: #a31515">&quot;{0}Old Path : {1} New Path : {2}&quot;</span>, </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Environment</span>.NewLine, oldPath, newPath)); </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; } </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; } </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; tr.Commit(); </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; } </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: blue">if</span> (collection.Count &gt; 0) </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; { </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Perform the reload operation </span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; db.ReloadXrefs(collection); </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; } </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; db.SaveAs(db.OriginalFileName, <span style="color: blue">true</span>, db.OriginalFileVersion, </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.SecurityParameters); </font></p>    <p style="margin: 0px"><font size="2">&#160; } </font></p>    <p style="margin: 0px"><font size="2">} </font></p> </div>  <p>The code is quite simple in that it assumes a drawing is located in c:\temp, and that the xrefs are in a subfolder of that. Its also loading the drawing being processed as a side database, which means that (in this example) the drawing mustn’t be open in the AutoCAD editor when you run the command.</p>  <p>I’ll leave it as an exercise to the reader to edit it to be more generic. I don’t have time for that just now because I’m off home to spend some quality time with the latest addition to my family. He’s the one on the left <img style="border-bottom-style: none; border-right-style: none; border-top-style: none; border-left-style: none" class="wlEmoticon wlEmoticon-smile" alt="Smile" src="/assets/image_756045.jpg" /> -</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b0177439c66de970d-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; margin-left: auto; border-top: 0px; margin-right: auto; border-right: 0px; padding-top: 0px" title="photo" border="0" alt="photo" src="/assets/image_743528.jpg" width="389" height="293" /></a></p>
