---
layout: "post"
title: "Finding the entities that intersect a polyline"
date: "2012-12-31 19:05:07"
author: "Gopinath Taget"
categories:
  - "2010"
  - "2011"
  - "2012"
  - "2013"
  - "AutoCAD"
  - "Gopinath Taget"
  - "ObjectARX"
original_url: "https://adndevblog.typepad.com/autocad/2012/12/finding-the-entities-that-intersect-a-polyline.html "
typepad_basename: "finding-the-entities-that-intersect-a-polyline"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/gopinath-taget.html">Gopinath Taget</a></p>  <p>To find the entities that intersect a selected polyline (LWPOLYLINE in this case), use a selection set containing the entities that cross the polyline using the acedSSGet() function coupled with the 'F' (Fence) options. (See code below.)</p>  <p>In the application listed below, the user is asked to select a polyline (LWPOLYLINE) entity. Having selected the polyline entity and verified that the selection is an AcDbPolyline entity, proceed and retrieve the entities bounding box. </p>  <p>I will explain the purpose of these later and possible alternatives to getting the bounding box of the entity. Next we iterate through the polyline and place all the vertices of the polyline in an AcGePoint3dArray. In order to use the function acedSSGet() with the 'F' option, we need to pass in as the second argument to acedSSGet() a resbuf linked list that contains all the points that make up our &quot;Fence&quot; point which is essentially the vertices that make up our selected LWPOLYLINE entity. Using a 'for' loop we step through our AcGePoint3dArray and build a linked list of result buffers (of type RT3DPOINT). The variable 'pPointList' is that list of result buffers. This list of point is passed to the acedSSGet() function as the second argument. The resulting selection set is returned in 'interSS'.</p>  <p>In this case the selection set 'interSS' will contain one entity which is our selected AcDbPolyline entity. After all it is part of the 'Fence'. In the final 'for' loop I walk through the selection set and get the objectId of each entity and compare it to the objectId of the current entity to that of our selected LWPOLYLINE, if they are the same I simply 'continue' at that point. Here I just inform the user how many entities intersect our AcDbPolyline and print out to the command prompt the kinds of entity found.</p>  <p>Here is the code for the first part, I will explain the bounding box next:</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#008000">// Here are your new AutoCAD functions. Add your code.</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#008000">//////////////////////////////////////////////////////</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">void</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> fencepoly () </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">{</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcDbObject *pObj;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcDbPolyline *pPolyEnt;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcDbObjectId polyId, objId;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGePoint3dArray arPolyPoints;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGePoint3d polyPoint;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeBoundBlock2d polyBox;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGePoint2d minPolyBox, maxPolyBox;</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">struct</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> resbuf *pPointList, *pTemp;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> ads_name ename;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> ads_name interSS;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> ads_point pickpt, curPoint;</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">int</font></span><span style="line-height: 11pt"><font color="#000000"> rc; </font></span><span style="line-height: 11pt"><font color="#0000ff">long</font></span><span style="line-height: 11pt"><font color="#000000"> len; </font></span><span style="line-height: 11pt"><font color="#0000ff">long</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> count;</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Select the Window entity to get its handle</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"> rc = acedEntSel(L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nSelect LWPOLYLINE entity &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, ename, pickpt);</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(rc != RTNORM)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> {</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; acutPrintf(L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nError selecting LWPOLYLINE entity &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> }</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Get the entity object ID</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acdbGetObjectId(polyId, ename);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Open the entity for a read operation</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acdbOpenObject(pObj, polyId, AcDb::kForRead);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Is pObj an AcDbPolyline object ?</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> pPolyEnt = AcDbPolyline::cast(pObj);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(!pPolyEnt)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> {</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; acutPrintf(L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nEntity selected is not a LWPOLYLINE &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; pObj-&gt;close();</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"></font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> polyBox = getPolylineBoundBox(pPolyEnt);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> polyBox.getMinMaxPoints(minPolyBox, maxPolyBox);</font></font></span><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"> acedCommand(RTSTR, L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;_ZOOM&quot;</font></span><span style="line-height: 11pt"><font color="#000000">, RTSTR, L</font></span><span style="line-height: 11pt"><font color="#a31515">&quot;_W&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; RTPOINT, asDblArray(minPolyBox),</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; RTPOINT, asDblArray(maxPolyBox), RTNONE);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">for</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(count = 0; count &lt; pPolyEnt-&gt;numVerts(); count++)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; pPolyEnt-&gt;getPointAt(count, polyPoint);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; arPolyPoints.append(polyPoint);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> pPolyEnt-&gt;close();</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">for</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(count = 0; count &lt; arPolyPoints.length(); count++)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; polyPoint = arPolyPoints.at(count);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; acdbPointSet(asDblArray(polyPoint), curPoint);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(count == 0)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; pPointList = acutNewRb(RT3DPOINT);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; acdbPointSet(curPoint, pPointList-&gt;resval.rpoint);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; pTemp = pPointList;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">else</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; pTemp-&gt;rbnext = acutNewRb(RT3DPOINT);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; pTemp = pTemp-&gt;rbnext;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; acdbPointSet(curPoint, pTemp-&gt;resval.rpoint);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> }</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// pPointList is now a linked list of resbuf</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// containing points</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"> rc = acedSSGet(L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;_F&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, pPointList, NULL, NULL, interSS);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acutRelRb(pPointList);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acedSSLength(interSS, &amp;len);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acutPrintf(</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nThere are %d entities crossing your selected LWPOLYLINE entity.&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; len - 1); </font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">for</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(count = 0; count &lt; len; count++)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; acedSSName(interSS, count, ename);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; acdbGetObjectId(objId, ename);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; acdbOpenObject(pObj, objId, AcDb::kForRead);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(objId == polyId)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; pObj-&gt;close();</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">continue</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"></font></font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">const</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> TCHAR *cstr = pObj-&gt;isA()-&gt;name();</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; acutPrintf(</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160; L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nThe entity crossing your LWPOLYLINE is a %s.&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; cstr); </font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; pObj-&gt;close();</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">}</font></font></span></p> </div>  <p>Let's move on and discuss the user-defined function 'getPolylineBoundBox()', here is how its called from 'fencepoly':</p>  <p><font face="Consolas"><font style="font-size: 8pt" color="#000000">polyBox = getPolylineBoundBox(pPolyEnt);</font></font></p>  <p>Refer to the code below. This function takes as a parameter the selected AcDbPolyline. You then step through all of the segments of the polyline in a 'for' loop and test to see if the segments are 'arc' or 'line' based. These are all added to an AcGeVoidPointerArray. If you are dealing with a single segment polyline, cast the first element of 'geCurves' to an AcGeCurve2d geometric entity, otherwise, create a single AcGeCompositeCurve2d, which is a single curve made up of a collection of sub curves. The 'orthoBoundBlock()' will give you the bounding box of the curve that is parallel to the coordinate axis. Having returned the bounding box, get the lower left and upper right point for the box. These are the points to which you execute 'acedCommand()' with the 'ZOOM' window option. Here is the 'getPolylineBoundBox()' function:</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">AcGeBoundBlock2d getPolylineBoundBox(AcDbPolyline* pPoly) {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeVector3d normal;</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">int</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> nSegs;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeLineSeg2d *pLine;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeLineSeg2d line;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeCircArc2d *pArc;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeCircArc2d arc;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeVoidPointerArray geCurves;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeCurve2d *pPolyGeCurve;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeBoundBlock2d polyBoundBox; </font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> nSegs = pPoly-&gt;numVerts() - 1; </font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">for</font></span><span style="line-height: 11pt"><font color="#000000">(</font></span><span style="line-height: 11pt"><font color="#0000ff">int</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> i = 0; i &lt; nSegs; i++)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> { </font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(pPoly-&gt;segType(i) == AcDbPolyline::kLine)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; pPoly-&gt;getLineSegAt(i, line);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160; pLine = </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> AcGeLineSeg2d(line);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; geCurves.append(pLine); </font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">else</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(pPoly-&gt;segType(i) == AcDbPolyline::kArc)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; pPoly-&gt;getArcSegAt(i, arc);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160; pArc = </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> AcGeCircArc2d(arc);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;&#160; geCurves.append( pArc );</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"> }</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// for</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(geCurves.length() == 1)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; pPolyGeCurve = (AcGeCurve2d*)(geCurves[0]);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">else</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; pPolyGeCurve = </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> AcGeCompositeCurve2d(geCurves); </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> polyBoundBox = pPolyGeCurve-&gt;orthoBoundBlock();</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> polyBoundBox;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">}</font></font></span></p> </div>  <p>As an alternative to getting the bounding box of the polyline, you can simply execute a zoom extents. The reason a zoom extents or zoom to the extents of the polyline is required is that if you are zoomed in on the polyline and some entities cross the polyline but are not in the view screen (display screen), they will not be reported even though all the vertices of the polyline for the point list as the second argument of acedSSGet() can be extracted.</p>
