---
layout: "post"
title: "Forming a selection set of entities and access their picked points"
date: "2012-12-20 18:04:54"
author: "Daniel Du"
categories:
  - "2010"
  - "2011"
  - "2012"
  - "2013"
  - "AutoCAD"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/autocad/2012/12/forming-a-selection-set-of-entities-and-access-their-picked-points.html "
typepad_basename: "forming-a-selection-set-of-entities-and-access-their-picked-points"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/daniel-du.html">Daniel Du</a></p>  <p><b>Issue</b></p>  <p>How do I access the coordinates of the point picked on each of the selection set entities? I am using the 'SelectionOnScreen' VBA method, which prompts the user to select objects in AutoCAD, then returns a set containing these objects. I want to also access the coordinates of the point picked on each of the selection set entities.</p>  <p><b>Solution</b></p>  <p>A SelectOnScreen selection cannot be used to ascertain the pickpoint of selected entities. Instead, you need to perform the construction of the selection set in two stages. First, prompt the user to choose an entity. This action has the advantage of reporting not only a chosen entity, but also the selected point.    <br />The GetEntity method off the utility object obtains both picked point and entity.</p>  <p>Secondly, if the selection is valid (no random keystrokes or selection of a non-entity point), then try adding the entity to a selection set. As long as the entity is not already present in the set, the selection set will expand and the corresponding pick point can then be appended to an array.</p>  <p>Then when you get a valid entity selection, you should store the entity reference into the selection set, and the picked point into an array.</p>  <p>The code below demonstrates how it should be done in a VBA macro.</p>  <p>&#160;</p>  <p>Public Sub getSelPt()    <br />&#160;&#160; Dim selPts() As Variant, Pt As Variant     <br />&#160;&#160; Dim msgOut As String     <br />&#160;&#160; <br />&#160;&#160; Dim selEntity As AcadEntity     <br />&#160;&#160; Dim sset As AcadSelectionSet, ArraySize As Integer     <br />&#160; <br />&#160;&#160; ' Creates an empty selection set.     <br />&#160;&#160; Set sset = ThisDrawing.SelectionSets.Add(&quot;mySelSet&quot;)     <br />&#160;&#160; oldSize = 0: newSize = 0     <br />&#160;&#160; Err.Clear     <br />&#160;&#160; ArraySize = 1     <br />&#160;&#160; <br />&#160;&#160; <br />&#160;&#160; On Error GoTo makeSetHndlr     <br />&#160;&#160;&#160; ' Keep prompting for entity selection until bad pick or escape     <br />&#160;&#160;&#160; While True     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Fake entity selection     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisDrawing.Utility.GetEntity selEntity, Pt, &quot;Pick an entity (enter to stop)&quot;     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Do the real entity selection by using the point returned from the API call above     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; sset.SelectAtPoint Pt     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; newSize = sset.Count     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' If the selection growled, then store the picked point into the array     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If newSize &gt; oldSize Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ReDim Preserve selPts(1 To ArraySize)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; selPts(ArraySize) = Pt     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; selEntity.Highlight True     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oldSize = newSize     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ArraySize = ArraySize + 1     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; Wend     <br />&#160;&#160; <br />makeSetHndlr:     <br />&#160;&#160; Err.Clear     <br />&#160;&#160; msgOut = &quot;DONE: &quot; &amp; sset.Count &amp; &quot; unique entities in selset&quot;     <br />&#160;&#160; For Each selPt In selPts     <br />&#160;&#160;&#160; msgOut = msgOut &amp; Chr(13) &amp; &quot;at &quot; &amp; Format(selPt(0), &quot;.###&quot;) &amp; &quot; , &quot; &amp; Format(selPt(1), &quot;.###&quot;)     <br />&#160;&#160; Next selPt     <br />&#160;&#160; MsgBox msgOut     <br />End Sub     <br /></p>  <p>&#160;</p>  <p>For .net API, you can use PromptEntityResult.PickedPoint. </p>  <p>Hope this helps.</p>
