---
layout: "post"
title: "Return nil to indicate an error condition in a .NET LispFunction"
date: "2012-05-25 11:19:33"
author: "Wayne Brill"
categories:
  - ".NET"
  - "AutoCAD"
  - "LISP"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/autocad/2012/05/return-nil-to-indicate-an-error-condition-in-a-net-lispfunction.html "
typepad_basename: "return-nil-to-indicate-an-error-condition-in-a-net-lispfunction"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p><b>Issue</b></p>  <p>I am implementing functionality in .NET that I am using from AutoLISP. How can I return an error condition from the .NET function?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>One suggestion is to return nil from the .NET function using the LispDataType. If the function does return nil you could then handle that appropriately. (Or you could return an integer and respond to that value in the LISP function)</p>  <p>Here is an excerpt from the AutoCAD .NET Managed Class Reference guide for the LispDataType:</p>  <p>Public Enum LispDataType    <br />&#160; Angle = &amp;H138c     <br />&#160; DottedPair = &amp;H139a     <br />&#160; Double = &amp;H1389     <br />&#160; Int16 = &amp;H138b     <br />&#160; Int32 = &amp;H1392     <br />&#160; ListBegin = &amp;H1398     <br />&#160; ListEnd = &amp;H1399     <br />&#160; Nil = &amp;H139b     <br />&#160; None = &amp;H1388     <br />&#160; ObjectId = &amp;H138e     <br />&#160; Orientation = &amp;H1390     <br />&#160; Point2d = &amp;H138a     <br />&#160; Point3d = &amp;H1391     <br />&#160; SelectionSet = &amp;H138f     <br />&#160; T_atom = &amp;H139d     <br />&#160; Text = &amp;H138d     <br />&#160; Void = &amp;H1396     <br />End Enum</p>  <p>Here is a VB example. Notice that if the entity is not selected ok, the routine returns nil.</p>  <div style="font-family: consolas; background: white; color: black; font-size: 10pt">   <p style="margin: 0px">&lt;LispFunction(<span style="color: #a31515">&quot;getId&quot;</span>)&gt;</p>    <p style="margin: 0px"><span style="color: blue">Public</span> <span style="color: blue">Function</span> test _</p>    <p style="margin: 0px">&#160; (<span style="color: blue">ByVal</span> myLispArgs <span style="color: blue">As</span> <span style="color: #2b91af">ResultBuffer</span>) <span style="color: blue">As</span> <span style="color: #2b91af">ResultBuffer</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' This example asks the user to select </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' an(entity) The object id of the entity is </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' returned to the calling lisp function</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> rbfResult <span style="color: blue">As</span> <span style="color: #2b91af">ResultBuffer</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> ed <span style="color: blue">As</span> Autodesk.AutoCAD.EditorInput.<span style="color: #2b91af">Editor</span></p>    <p style="margin: 0px">&#160;&#160;&#160; ed = Autodesk.AutoCAD.ApplicationServices. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Application</span>.DocumentManager. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MdiActiveDocument.Editor</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> prmptEntOpts <span style="color: blue">As</span> <span style="color: blue">New</span> <span style="color: #2b91af">PromptEntityOptions</span> _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;Select Entity&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> prmptEntRes <span style="color: blue">As</span> <span style="color: #2b91af">PromptEntityResult</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' Get the entity from the users selection</span></p>    <p style="margin: 0px">&#160;&#160;&#160; prmptEntRes = ed.GetEntity(prmptEntOpts)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' Make sure the entity was selected ok</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">If</span> prmptEntRes.Status &lt;&gt; <span style="color: #2b91af">PromptStatus</span>.OK <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; rbfResult = <span style="color: blue">New</span> <span style="color: #2b91af">ResultBuffer</span> _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: blue">New</span> <span style="color: #2b91af">TypedValue</span>(<span style="color: #2b91af">LispDataType</span>.Nil))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Return</span> rbfResult</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' Return the ObjectId to the Lisp function</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> objId <span style="color: blue">As</span> <span style="color: #2b91af">ObjectId</span></p>    <p style="margin: 0px">&#160;&#160;&#160; objId = prmptEntRes.ObjectId</p>    <p style="margin: 0px">&#160;&#160;&#160; rbfResult = <span style="color: blue">New</span> <span style="color: #2b91af">ResultBuffer</span> _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; (<span style="color: blue">New</span> <span style="color: #2b91af">TypedValue</span>(<span style="color: #2b91af">LispDataType</span>.ObjectId, objId))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Return</span> rbfResult</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Function</span></p> </div>  <p>Here is a LISP function that uses the .NET function:</p>  <p>&#160;&#160;&#160; (defun c:testID ( / objId nilTest ent)    <br />&#160;&#160;&#160; (setq objId (getId))     <br />&#160;&#160;&#160; (setq nilTest (nth 0 objId))     <br />&#160;&#160;&#160; (if (= nilTest nil)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; (princ &quot;Entity not selected&quot;)     <br />&#160;&#160;&#160;&#160;&#160; )     <br />&#160; <br />&#160;&#160;&#160;&#160; (if (/= nilTest nil)     <br />&#160;&#160;&#160;&#160; (progn     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (vl-load-com);ensure COM API is available     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; (setq ent (vlax-ename-&gt;vla-object (nth 0 objId)));the 0 element is an ename     <br />&#160;&#160;&#160;&#160;&#160; (vla-highlight ent :vlax-true); highlight the entity using COM call     <br />&#160;&#160;&#160;&#160; );progn     <br />&#160;&#160;&#160; );if     <br />&#160;&#160;&#160; (princ)     <br />&#160;&#160;&#160; )</p>
