---
layout: "post"
title: "Use an Open LW Polyline as the Boundary for a Hatch in VBA"
date: "2012-12-10 15:05:18"
author: "Fenton Webb"
categories:
  - "2010"
  - "2011"
  - "2012"
  - "2013"
  - "ActiveX"
  - "AutoCAD"
  - "Fenton Webb"
original_url: "https://adndevblog.typepad.com/autocad/2012/12/use-an-open-lw-polyline-as-the-boundary-for-a-hatch-in-vba.html "
typepad_basename: "use-an-open-lw-polyline-as-the-boundary-for-a-hatch-in-vba"
typepad_status: "Publish"
---

<p>by <a href="http://adndevblog.typepad.com/autocad/fenton-webb.html">Fenton Webb</a></p>  <p><b>Issue</b></p>  <p>How can I use a lightweight polyline that is open to define the boundary for a   <br />new hatch entity? Can I also use the AddVertex method for adding vertexes to the    <br />lightweight polyline?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>The following code contains a function that creates a lightweight polyline   <br />(using AddVertex) that is left &quot;open&quot; (although its start and end points    <br />coincide). This polyline is then used in the outerloop of the hatch entity    <br />created below.</p> <font style="background-color: #a5a5a5"><font face="Courier New"><font style="font-size: 8pt" color="#000000">Option Base 0</font></font> </font>  <p style="white-space: pre; margin: 0px 0px 15px; line-height: 16px"></p> <font style="font-size: 8pt"></font>  <p style="white-space: pre; margin: 0px 0px 15px; line-height: 16px"><font face="Courier New"><font style="font-size: 9pt; background-color: #cccccc" color="#000000">Sub TestLWPline ()       <br />&#160;&#160; 'build the initial array for two points        <br />&#160;&#160; Dim Pt(0 To 3) As Double        <br />&#160;&#160; Pt(0) = 0#: Pt(1) = 0#: Pt(2) = 0#: Pt(3) = 10#        <br />&#160;&#160; 'create a lwpline based on the two points        <br />&#160;&#160; Dim LWpline As Object        <br />&#160;&#160; Set LWpline = ThisDrawing.ModelSpace.AddLightWeightPolyline(Pt)        <br />&#160;&#160; 'add further points        <br />&#160;&#160; Pt(0) = 10#: Pt(1) = 10#        <br />&#160;&#160; LWpline.AddVertex 2, Pt        <br />&#160;&#160; 'add a the start point to lwpline again so        <br />&#160;&#160; 'that the start and end points coincide but its Closed        <br />&#160;&#160; 'property is false        <br />&#160;&#160; Pt(0) = 0#: Pt(1) = 0#        <br />&#160;&#160; LWpline.AddVertex 3, Pt        <br />&#160;&#160; 'you can check here if it is really false        <br />&#160;&#160; Dim bClosed As Boolean        <br />&#160;&#160; bClosed = LWpline.closed        <br />&#160;&#160; 'add a hatch to modelspace        <br />&#160;&#160; Dim MyHatch As Object        <br />&#160;&#160; Set MyHatch = ThisDrawing.ModelSpace.AddHatch</font></font></p>  <p style="white-space: pre; margin: 0px 0px 15px; line-height: 16px"><font face="Courier New"><font style="font-size: 9pt; background-color: #cccccc" color="#000000">(acHatchPatternTypePreDefined,&quot;ANSI31&quot;, True)       <br />&#160;&#160; 'create and append outer loop        <br />&#160;&#160; Dim outerLoop As Variant</font></font></p> <font style="font-size: 8pt"></font>  <p style="white-space: pre; margin: 0px 0px 15px; line-height: 16px"><font face="Courier New"><font style="font-size: 9pt; background-color: #cccccc" color="#000000">&#160;&#160; Dim outerLoopArray(0) As Object       <br />&#160;&#160; Set outerLoopArray(0) = LWpline</font></font></p> <font style="font-size: 8pt"></font>  <p style="white-space: pre; margin: 0px 0px 15px; line-height: 16px"><font face="Courier New"><font style="font-size: 9pt; background-color: #cccccc" color="#000000">&#160;&#160; outerLoop = outerLoopArray       <br />&#160;&#160; MyHatch.AppendOuterLoop (outerLoop)</font></font></p> <font style="font-size: 8pt"></font>  <p style="white-space: pre; margin: 0px 0px 15px; line-height: 16px"><font face="Courier New"><font style="font-size: 9pt; background-color: #cccccc" color="#000000">End Sub</font></font></p>
