---
layout: "post"
title: "LISP: How do I convert a Polygon Mesh into polylines?"
date: "2012-09-05 01:50:25"
author: "Philippe Leefsma"
categories:
  - "AutoCAD"
  - "LISP"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/autocad/2012/09/lisp-how-do-i-convert-a-polygon-mesh-into-polylines.html "
typepad_basename: "lisp-how-do-i-convert-a-polygon-mesh-into-polylines"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p>  <div style="line-height: 16px; widows: 2; text-transform: none; text-indent: 0px; letter-spacing: normal; font-family: ; white-space: normal; orphans: 2; color: ; clear: both; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px" class="clear">   <div><strong><font color="#000000">Q:</font></strong>      <br /></div>    <p style="line-height: 16px; margin: 0px 0px 15px"><font color="#000000">Using Visual LISP, is there a way to reduce Polygon Meshs (3D Meshs) into regular polylines or lines?</font></p> </div>  <div style="line-height: 16px; widows: 2; text-transform: none; text-indent: 0px; letter-spacing: normal; font-family: ; white-space: normal; orphans: 2; color: ; clear: both; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px" class="clear"><a name="section2"></a>    <div><strong><font color="#000000">A:</font></strong>      <br /></div>    <p style="line-height: 16px; margin: 0px 0px 15px"><font color="#000000">While Visual LISP has no built-in method for converting a polygon mesh to polylines (or lines), you can explode it, and then draw polylines using the coordinates of the resulting 3dFaces.&#160; The sample code below demonstrates this.&#160; It searches modelspace for polygon mesh objects, explodes them into 3dFaces, draws polylines (adding vertices to the the 3dFace coordinates), and deletes the original mesh (and faces):</font></p>    <p style="line-height: normal; text-indent: 0pt; margin: 0in 0in 0pt; word-spacing: normal" class="MsoNormal"><span style="color: "><font face="Calibri"><font color="#000000" size="3"><em>(defun c:XplPgMesh </em></font></font></span></p>    <p style="line-height: normal; text-indent: 0pt; margin: 0in 0in 0pt; word-spacing: normal" class="MsoNormal"><span style="color: "><font face="Calibri"><font color="#000000" size="3"><em> (/ oApp oDoc oMSp oObj vXplObj aXplObj oObjLst oObj2 vCoords o3dPline)             <br /><span style="mso-spacerun: yes">&#160;&#160; </span>(VL-LOAD-COM)              <br /><span style="mso-spacerun: yes">&#160;&#160; </span>(setq oApp (vlax-get-acad-object)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>oDoc (vla-get-activedocument oApp)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>oMSp (vla-get-modelspace oDoc)              <br /><span style="mso-spacerun: yes">&#160;&#160; </span>) ;setq              <br /><span style="mso-spacerun: yes">&#160;&#160; </span>(vlax-for oObj oMsp              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160; </span>(if (= (vla-get-objectname oObj) &quot;AcDbPolygonMesh&quot;)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160; </span>(if (setq vXplObj (vla-explode oObj))              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160; </span>(progn              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(setq aXplObj (vlax-variant-value vXplObj))              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(if (not (minusp (vlax-safearray-get-u-bound aXplObj 1)))              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(progn              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(setq oObjLst (vlax-safearray-&gt;list aXplObj))              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(foreach oObj2 oObjLst              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(if (= (vla-get-objectname oObj2) &quot;AcDbFace&quot;)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(progn              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(setq vCoords (vla-get-coordinates oObj2)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>o3dPline (vla-Add3DPoly oMSp vCoords)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>) ;setq              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(vlax-put-property o3dPline 'Closed :vlax-true)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(vla-delete oObj2)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(vlax-release-object o3dPline)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>) ;progn              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>) ;if              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>) ;foreach              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(foreach itm oObjLst (vlax-release-object itm))              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>) ;progn              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="mso-spacerun: yes">&#160; </span>) ;if              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span>(vla-delete oObj)              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160;&#160; </span>) ;progn              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160; </span>) ;if              <br /><span style="mso-spacerun: yes">&#160;&#160;&#160;&#160;&#160; </span>) ;if              <br /><span style="mso-spacerun: yes">&#160;&#160; </span>) ;vlax-for              <br /><span style="mso-spacerun: yes">&#160;&#160; </span>(princ)              <br />)</em></font></font></span></p>    <p style="line-height: 16px; margin: 0px 0px 15px"></p> </div>
