---
layout: "post"
title: "Define holes with AcDdSubDMesh::setSubDMesh() the same way as with AcGiGeometry::shell()"
date: "2012-05-28 04:46:47"
author: "Adam Nagy"
categories:
  - "Adam Nagy"
  - "AutoCAD"
  - "ObjectARX"
original_url: "https://adndevblog.typepad.com/autocad/2012/05/define-holes-with-acddsubdmeshsetsubdmesh-the-same-way-as-with-acgigeometryshell.html "
typepad_basename: "define-holes-with-acddsubdmeshsetsubdmesh-the-same-way-as-with-acgigeometryshell"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/adam-nagy.html" target="_self">Adam Nagy</a></p>  <p>I know how to set AcGiFaceData for AcGiGeometry::shell() to define holes. I'm trying to do the same with AcDbSubDMesh::setSubDMesh(), but that does not seem to work. Is it not possible to do that?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>No it isn't. You need to divide your manifold into faces without holes and set up the face data for AcDbSubDMesh::setSubDMesh() accordingly.</p>  <p>Another thing that might be helpful is using AcDb3dSolid entities, create the holes in them using boolean operations and then create an AcDbSubDMesh from that:</p>  <div style="font-family: Courier New; font-size: 8pt; color: black; background: white;"> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">static</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">void</span><span style="line-height: 140%;"> AcDbSubDMeshfromAcDb3dSolid(</span><span style="color: blue; line-height: 140%;">void</span><span style="line-height: 140%;">)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">{</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; Acad::ErrorStatus err;</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; ads_name name;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; ads_point pt;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">if</span><span style="line-height: 140%;"> (acedEntSel(L</span><span style="color: #a31515; line-height: 140%;">&quot;Select a solid&quot;</span><span style="line-height: 140%;">, name, pt) != RTNORM)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">return</span><span style="line-height: 140%;">;</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcDbObjectId id;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; acdbGetObjectId(id, name);</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcDbObjectPointer&lt;AcDb3dSolid&gt; ptrSolid(id, AcDb::kForRead); </span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcDbFaceterSettings settings;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcGePoint3dArray pts;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcArray faces; </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcGiFaceData* faceData;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; err = acdbGetObjectMesh(ptrSolid, &amp;settings, pts, faces, faceData);</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">if</span><span style="line-height: 140%;"> (faceData) </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; {</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">delete</span><span style="line-height: 140%;"> [] faceData-&gt;trueColors(); </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">delete</span><span style="line-height: 140%;"> [] faceData-&gt;materials();</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; </span><span style="color: blue; line-height: 140%;">delete</span><span style="line-height: 140%;"> faceData;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; }</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcDbObjectPointer&lt;AcDbSubDMesh&gt; ptrMesh;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; ptrMesh.create();</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; ptrMesh-&gt;setSubDMesh(pts, faces, 0); </span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcDbDatabase* pDb = </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; acdbHostApplicationServices()-&gt;workingDatabase();</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; AcDbBlockTableRecordPointer </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; &nbsp; ptrMS(ACDB_MODEL_SPACE, pDb, AcDb::kForWrite);</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; ptrMS-&gt;appendAcDbEntity(ptrMesh); </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">}</span></p> <p style="margin: 0px;">&nbsp;</p> </div>
