---
layout: "post"
title: "Monitor events of mouse click, ESC or right mouse button of Utility.GetEntity by COM API"
date: "2012-12-19 00:01:24"
author: "Xiaodong Liang"
categories:
  - "ActiveX"
  - "AutoCAD"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/autocad/2012/12/monitor-events-of-mouse-click-esc-or-right-mouse-button-of-utilitygetentity-by-com-api.html "
typepad_basename: "monitor-events-of-mouse-click-esc-or-right-mouse-button-of-utilitygetentity-by-com-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>  <p><b>Issue      <br /></b>Is it possible to know what a user has clicked after the follow command :     <br />AppAcad.ActiveDocument.Utility.GetEntity ObjPall, pnt, &quot;Select Entity&quot;.     <br />I want to know the user has selected a point in the draft, and not an entity, or has canceled the command by &quot;ESC&quot; or right mouse button.</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>COM API&#160; has event AcadDocument.BeginRightClick to watch right mouse event. But no method to monitor ESC. The workaround is to have the error status and do what you want in the exception. The sample below demonstrates this.</p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt">Sub Example<span style="color: #ff0000">(</span><span style="color: #ff0000">)</span>      <br />      <br />&#160;&#160; Dim returnObj As AcadObject      <br />&#160;&#160; Dim basePnt As Variant      <br />      <br />&#160;&#160;&#160;&#160; On Error GoTo ERRHAND      <br />&#160;&#160;&#160;&#160; ThisDrawing.Utility.GetEntity returnObj, basePnt, <span style="color: #ff00ff">&quot;Select Entity&quot;</span>      <br />      <br />&#160;&#160;&#160; 'If returnObj.ObjectID &lt;&gt; <span style="color: #008000">0</span> Then&#160; ' on 32bits OS      <br />&#160;&#160;&#160; If returnObj.ObjectID32 &lt;&gt; <span style="color: #008000">0</span> Then ' on 64bits OS      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox <span style="color: #ff00ff">&quot;You selected an object!&quot;</span>      <br />End If      <br />Exit Sub      <br />      <br />&#160; <br />ERRHAND:      <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160; 'do what you want      <br />&#160;&#160;&#160;&#160; Call ThisDrawing.Utility.Prompt<span style="color: #ff0000">(</span>Err.Description &amp; vbCr<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160; Resume ' back to GetEntity      <br />End Sub      <br />      <br />      <br />Private Sub AcadDocument_BeginRightClick<span style="color: #ff0000">(</span>ByVal PickPoint As Variant<span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160; Call ThisDrawing.Utility.Prompt<span style="color: #ff0000">(</span><span style="color: #ff00ff">&quot;AcadDocument_BeginRightClick&quot;</span> &amp; vbCr<span style="color: #ff0000">)</span>      <br />End Sub      <br />      <br />Private Sub AcadDocument_BeginSave<span style="color: #ff0000">(</span>ByVal FileName As String<span style="color: #ff0000">)</span>      <br />      <br />End Sub      <br /></span></p>
