---
layout: "post"
title: "Finding the centroid of a region using LISP"
date: "2012-09-28 02:45:00"
author: "Xiaodong Liang"
categories:
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/autocad/2012/09/finding-the-centroid-of-a-region-using-lisp.html "
typepad_basename: "finding-the-centroid-of-a-region-using-lisp"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>
<p><strong>Issue      <br /></strong>When a polyline is changed to a REGION you can get the center of gravity using MASSPROP. Variables exist for PERIMETER and AREA but not for the Center of Gravity. How can an Auto LISP routine extract the Center of Gravity from a region ?</p>
<p><a name="section2"></a></p>
<p><strong>Solution      <br /></strong>Use the ActiveX interface to return the Cenroid property for a region. The following AutoLISP code does this:</p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;"><span style="color: #ff0000;">(</span><span style="color: #0000ff;">defun</span> GetCentroid <span style="color: #ff0000;">(</span><span style="color: #ff0000;">)</span>      <br />&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">vl-load-com</span><span style="color: #ff0000;">)</span>      <br />&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> anEnt <span style="color: #ff0000;">(</span><span style="color: #0000ff;">entsel</span>&#0160;<span style="color: #ff00ff;">&quot;\nSelect A Region: &quot;</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">if</span> anEnt      <br />&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">progn</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> anObj <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-ename-</span>&gt;vla-object <span style="color: #ff0000;">(</span><span style="color: #0000ff;">car</span> anEnt<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">strcat</span>&#0160;<span style="color: #ff00ff;">&quot;\nObject Name: &quot;</span>&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> objName <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-Get-ObjectName</span>      <br />anObj<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">if</span>&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">equal</span> objName <span style="color: #ff00ff;">&quot;AcDbRegion&quot;</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">progn</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> vCentroid <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-Get-Centroid</span> anObj<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> strCentroidProp <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vl-princ-to-string</span>&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> CentroidLst      <br /><span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-safearray-</span>&gt;list <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-variant-value</span> vCentroid<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">if</span>&#0160;<span style="color: #ff0000;">(</span>&lt; <span style="color: #ff0000;">(</span>length CentroidLst<span style="color: #ff0000;">)</span>&#0160;<span style="color: #008000;">3</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> CentroidLst <span style="color: #ff0000;">(</span>append CentroidLst <span style="color: #ff0000;">(</span>list 0.0<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">strcat</span>&#0160;<span style="color: #ff00ff;">&quot;\nRegion Centroid: &quot;</span> strCentroidProp<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setvar</span>&#0160;<span style="color: #ff00ff;">&quot;PDMODE&quot;</span>&#0160;<span style="color: #008000;">3</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> *MS* <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-Get-ModelSpace</span>&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> acadDoc      <br /><span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-Get-ActiveDocument</span>&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> acadApp <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-get-acad-object</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">setq</span> ptObj <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-AddPoint</span> *MS* <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vlax-</span>3d-Point CentroidLst<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">vla-Put-Color</span> ptObj acYellow<span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff00ff;">&quot;\nRegion was not selected !&quot;</span><span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">)</span>      <br />&#0160;&#0160;&#0160; <span style="color: #ff0000;">)</span>      <br />&#0160;<span style="color: #ff0000;">)</span>      <br />&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span><span style="color: #ff0000;">)</span>      <br /><span style="color: #ff0000;">)</span>      <br />      <br /><span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff00ff;">&quot;\nGetCentroid loaded, type <span style="color: #ff0000;">(</span>GetCentroid<span style="color: #ff0000;">)</span> to run.&quot;</span><span style="color: #ff0000;">)</span>      <br /><span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span><span style="color: #ff0000;">)</span></span></p>
