---
layout: "post"
title: "Entmake an mtext entity"
date: "2012-09-25 02:03:00"
author: "Xiaodong Liang"
categories:
  - "AutoCAD"
  - "LISP"
  - "Xiaodong Liang"
original_url: "https://adndevblog.typepad.com/autocad/2012/09/entmake-an-mtext-entity.html "
typepad_basename: "entmake-an-mtext-entity"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/xiaodong-liang.html" target="_self">Xiaodong Liang</a></p>
<p><strong>Issue      <br /></strong>How can I use entmake in the following AutoLISP code to create an MTEXT entity? I can create a TEXT entity using similar code as below, but it does not work.</p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;"><span style="color: #ff0000;">(</span><span style="color: #0000ff;">defun</span> CreateMText <span style="color: #ff0000;">(</span><span style="color: #ff0000;">)</span>       <br />      <br />&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">if</span>&#0160; <br />&#0160;&#0160; <span style="color: #ff0000;">(</span>entmake       <br />&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>list       <br />&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">0</span>&#0160;<span style="color: #ff00ff;">&quot;MTEXT&quot;</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Entity Type        <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">1</span>&#0160;<span style="color: #ff00ff;">&quot;Some Text Here&quot;</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Text String        <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">10</span> &#39;<span style="color: #ff0000;">(</span>0.0 0.0 0.0<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Insertion Point        <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">40</span> 0.25<span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Text Height        <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">)</span>       <br />      <br />&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff00ff;">&quot;\nText Entity Created.&quot;</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff00ff;">&quot;\nText Entity was NOT Created.&quot;</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span><span style="color: #ff0000;">)</span>       <br /><span style="color: #ff0000;">)</span></span></p>
<p>&#0160;</p>
<p><strong>Solution</strong>     <br />For entities such as MTEXT that were created after AutoCAD R12, you will need to add the Entity SubClass Markers, group code 100, for this to work:</p>
<p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt;">&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">defun</span> CreateMtext <span style="color: #ff0000;">(</span><span style="color: #ff0000;">)</span>       <br />      <br />&#0160;<span style="color: #ff0000;">(</span><span style="color: #0000ff;">if</span>&#0160; <br />&#0160;&#0160; <span style="color: #ff0000;">(</span>entmake       <br />&#0160;&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>list       <br />&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">0</span>&#0160;<span style="color: #ff00ff;">&quot;MTEXT&quot;</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Entity Type        <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">100</span>&#0160;<span style="color: #ff00ff;">&quot;AcDbEntity&quot;</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; <span style="color: #008000;">100</span> Entity Code         <br /></span>&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">;<span style="color: #ff0000;">(</span>cons <span style="color: #008000;">8</span>&#0160;<span style="color: #ff00ff;">&quot;DIM&quot;</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ; The Layer         <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">100</span>&#0160;<span style="color: #ff00ff;">&quot;AcDbMText&quot;</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; <span style="color: #008000;">100</span> Entity Code         <br /></span>&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; For Other Formatting Codes See the:        <br /></span>&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; ActiveX and VBA Developer&#39;s Guide -&gt;        <br /></span>&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Chapter <span style="color: #008000;">4</span> -- Creating and Editing AutoCAD Entities -&gt;         <br /></span>&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Adding Text to Drawings -&gt;        <br /></span>&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Using Multiline Text <span style="color: #ff0000;">(</span>Mtext<span style="color: #ff0000;">)</span> -&gt;         <br /></span>&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Formatting Multiline Text        <br /></span>&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">1</span>&#0160;<span style="color: #ff00ff;">&quot;\\S100^200&quot;</span><span style="color: #ff0000;">)</span>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Stacked Text        <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">(</span>cons <span style="color: #008000;">10</span> &#39;<span style="color: #ff0000;">(</span>0.0 0.0 0.0<span style="color: #ff0000;">)</span><span style="color: #ff0000;">)</span>&#0160;&#0160; <span style="background-color: #e6e6e6; color: #800080;">; Insertion Point        <br /></span>&#0160;&#0160;&#0160; <span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">)</span>       <br />      <br />      <br />&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff00ff;">&quot;\nMtext Entity Created.&quot;</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff00ff;">&quot;\nMtext Entity NOT Created.&quot;</span><span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">)</span>       <br />&#0160;&#0160; <span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span><span style="color: #ff0000;">)</span>       <br /><span style="color: #ff0000;">)</span>       <br /><span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span>&#0160;<span style="color: #ff00ff;">&quot;\nCreateMtext loaded, type <span style="color: #ff0000;">(</span>CreateMtext<span style="color: #ff0000;">)</span> to run.&quot;</span><span style="color: #ff0000;">)</span>       <br /><span style="color: #ff0000;">(</span><span style="color: #0000ff;">princ</span><span style="color: #ff0000;">)</span></span></p>
