---
layout: "post"
title: "Select all inserted Xrefs using VBA"
date: "2012-07-09 05:34:16"
author: "Philippe Leefsma"
categories:
  - "AutoCAD"
  - "Philippe Leefsma"
original_url: "https://adndevblog.typepad.com/autocad/2012/07/select-all-inserted-xrefs-using-vba.html "
typepad_basename: "select-all-inserted-xrefs-using-vba"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/philippe-leefsma.html" target="_self">Philippe Leefsma</a></p> <p><b>Q:</b></p> <p>What approach can be used to select all Xrefs that are inserted in a drawing using VBA?</p> <p><a name="section2"></a></p> <p><b>A:</b></p> <p>The best approach would be to: <br>1. Iterate through the block definitions to determine if a block is an Xref. <br>2. Make a list of all such Xref names. <br>3. Then use a selection set filter with these names to select all those INSERTs.</p> <p>NOTE: Please introduce necessary error handling. <br></p><pre>Sub GetXrefInserts()
<p>&nbsp;&nbsp;&nbsp; Dim ssBlocks As AcadSelectionSet<br>&nbsp;&nbsp;&nbsp; Dim ssTemp As AcadSelectionSet<br>&nbsp;&nbsp;&nbsp; Dim col As New Collection<br>&nbsp;&nbsp;&nbsp; Dim obj() As Object<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Dim GroupCodeArray(0 To 3) As Integer<br>&nbsp;&nbsp;&nbsp; Dim GroupValueArray(0 To 3) As Variant<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Dim blkdef As AcadBlock<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; For Each blkdef In ThisDrawing.Blocks<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If blkdef.IsXRef = True Then<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; col.Add blkdef.Name<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If<br>&nbsp;&nbsp;&nbsp; Next<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Set ssBlocks = ThisDrawing.SelectionSets.Add("ss")<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Dim i As Integer<br>&nbsp;&nbsp;&nbsp; For i = 1 To col.Count<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set ssTemp = ThisDrawing.SelectionSets.Add("temp")<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupCodeArray(0) = -4<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupValueArray(0) = "&lt;AND"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'Entity Type<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupCodeArray(1) = 0<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupValueArray(1) = "INSERT"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'Block name<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupCodeArray(2) = 2<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupValueArray(2) = col.Item(i)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupCodeArray(3) = -4<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GroupValueArray(3) = "AND&gt;"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Call ssTemp.Select(acSelectionSetAll, , , GroupCodeArray, GroupValueArray)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim cnt As Integer<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cnt = ssTemp.Count<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If cnt &gt; 0 Then<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ReDim obj(0 To cnt - 1) As Object<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim k As Integer<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; For k = 0 To cnt - 1<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Set obj(k) = ssTemp(k)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Next<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ssBlocks.AddItems obj<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ssTemp.Delete<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; Next<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; If ssBlocks.Count &lt;&gt; 0 Then<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MsgBox ssBlocks.Count<br>&nbsp;&nbsp;&nbsp; End If<br>&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; ssBlocks.Delete<br>End Sub</p></pre><pre></pre>
