---
layout: "post"
title: "Invoking the MEASURE command using SendCommand in VB.NET"
date: "2012-06-22 10:35:29"
author: "Madhukar Moogala"
categories:
  - ".NET"
  - "AutoCAD"
  - "Stephen Preston"
original_url: "https://adndevblog.typepad.com/autocad/2012/06/invoking-the-measure-command-using-sendcommand-in-vbnet.html "
typepad_basename: "invoking-the-measure-command-using-sendcommand-in-vbnet"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/stephen-preston.html">Stephen Preston</a></p>  <p>There are several ways to invoke an AutoCAD command from a .NET plugin:</p>  <ul>   <li>The native .NET <a href="http://docs.autodesk.com/ACD/2013/ENU/index.html?url=files/GUID-4E1AAFA9-740E-4097-800C-CAED09CDFF12.htm,topicNumber=d30e698475">SendStringToExecute</a> method is asynchronous, which makes it fiddly to use. </li>    <li><a href="http://adndevblog.typepad.com/autocad/2012/04/synchronously-send-and-wait-for-commands-in-autocad-using-c-net.html">P/Invoking the ObjectARX acedCommand/acedCmd</a> function can cause problems because AutoCAD makes use of Fibers than are not supported in .NET (although it usually works ok). </li>    <li>Invoking the ActiveX SendCommand API introduces a dependency on the COM Interop assemblies, which introduces a platform dependency into your code that you may otherwise not have had in your .NET plug-in. (And read <a href="http://adndevblog.typepad.com/autocad/2012/05/why-does-sendcommand-run-asynchronously.html">this blog post</a> on some synchronous/asynchronous issues). </li> </ul>  <p><a href="http://dictionary.cambridge.org/dictionary/british/you-pays-your-money-and-you-takes-your-chance-choice">You pays your money and you takes your chance</a>! <img style="border-bottom-style: none; border-right-style: none; border-top-style: none; border-left-style: none" class="wlEmoticon wlEmoticon-smile" alt="Smile" src="/assets/image_845250.jpg" /></p>  <p>The following code demonstrates the use of SendCommand to invoke the AutoCAD MEASURE command to insert an instance of a block along a lightweight polyline. You’ll need a drawing containing a polyline over 10 units long and a block called ‘myblock’ to test the code. Make sure you reference the Autodesk.AutoCAD.Interop and Autodesk.AutoCAD.Interop.Common assemblies from the inc-win32 or inc-x64 directories of your ObjectARX SDK (depending on whether you’re working on a 32- or 64- bit platform).</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; &lt;</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;MYMEASURE&quot;</span><span style="line-height: 140%">)&gt; _</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span><span style="line-height: 140%"> MYMEASURE()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> app </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AcadApplication</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.AcadApplication</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> obj1, obj2 </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Object</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Use ActiveX GetEntity function, as we only want to select a single entity</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; app.ActiveDocument.Utility.GetEntity(obj1, obj2,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;select a polyline which you want to measure&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Cast Object to AcadObject</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> tmpObj </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">AcadObject</span><span style="line-height: 140%"> = </span><span style="line-height: 140%; color: blue">CType</span><span style="line-height: 140%">(obj1, </span><span style="line-height: 140%; color: #2b91af">AcadObject</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> strObjName </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; strObjName = tmpObj.ObjectName</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'&#160;&#160; Check its a polyline</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">If</span><span style="line-height: 140%"> strObjName = </span><span style="line-height: 140%; color: #a31515">&quot;AcDbPolyline&quot;</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> str1 </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Handle of polyline is used to identify it to MEASURE command</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; str1 = </span><span style="line-height: 140%; color: #a31515">&quot;(handent &quot;&quot;&quot;</span><span style="line-height: 140%"> + tmpObj.Handle + </span><span style="line-height: 140%; color: #a31515">&quot;&quot;&quot;&quot;</span><span style="line-height: 140%"> + </span><span style="line-height: 140%; color: #a31515">&quot;)&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">Dim</span><span style="line-height: 140%"> str </span><span style="line-height: 140%; color: blue">As</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">String</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'Insert instances of 'myblock' at 10 unit spacing along polyline</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">'(replace myblock with name of your block)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' the polyline needs to be longer than 10</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; str = </span><span style="line-height: 140%; color: #a31515">&quot;_measure &quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; str = str &amp; str1 &amp; vbCr &amp; </span><span style="line-height: 140%; color: #a31515">&quot;_block&quot;</span><span style="line-height: 140%"> &amp; vbCr &amp; </span><span style="line-height: 140%; color: #a31515">&quot;myblock&quot;</span><span style="line-height: 140%"> &amp;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vbCr &amp; </span><span style="line-height: 140%; color: #a31515">&quot;_Y&quot;</span><span style="line-height: 140%"> &amp; vbCr &amp; </span><span style="line-height: 140%; color: #a31515">&quot;10&quot;</span><span style="line-height: 140%"> &amp; vbCr</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; app.ActiveDocument.SendCommand(str)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">If</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">End</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">Sub</span></p> </div>
