---
layout: "post"
title: "Creating a 3D AcDbArc within rotated UCS"
date: "2012-12-18 17:19:16"
author: "Gopinath Taget"
categories: []
original_url: "https://adndevblog.typepad.com/autocad/2012/12/creating-a-3d-acdbarc-within-rotated-ucs.html "
typepad_basename: "creating-a-3d-acdbarc-within-rotated-ucs"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/gopinath-taget.html">Gopinath Taget</a></p>  <p>Consider this: You would like to create an AcDbArc in ARX by having the user specify a center point and two endpoints, but the angles are all wrong when you have a custom rotated UCS. So what is going on?</p>  <p>The problem is that the coordinates of points returned from acedGetPoint are in UCS, while arguments to AcDbArc expect WCS coordinates and vectors. The solution is to use acdbUcs2Wcs() to convert the points from UCS to WCS, then obtain the correct reference angles and apply the startAngle and endAngle to the new AcDbArc entity. The best way to obtain the normal for your new arc is to get the cross product of v1 and v2(the vectors joining the center point and the two end points of the arc), which returns a vector which is perpendicular to the plane on which these two vectors lie. Note that this example uses the distance from 'center' to 'pt1' as the radius of the arc.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">void</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> CreateArc()</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">{</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGePoint3d center, pt1, pt2;</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(RTNORM != acedGetPoint( NULL, </font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;Center point: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, asDblArray(center) )</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; || RTNORM != acedGetPoint( </font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; asDblArray(center), L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;Begin Arc: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">,</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; asDblArray( pt1 ) )</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; || RTNORM != acedGetPoint( </font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; asDblArray(center), L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;End Arc: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; asDblArray( pt2) ))</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> {</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; ads_printf( L</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nFunction canceled\n&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> );</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> }</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Convert the points to WCS</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGePoint3d centerWcs,pt1Wcs,pt2Wcs;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acdbUcs2Wcs(asDblArray(center),</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; asDblArray(centerWcs),</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">false</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acdbUcs2Wcs(asDblArray(pt1),</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; asDblArray(pt1Wcs),</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">false</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> acdbUcs2Wcs(asDblArray(pt2),</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; asDblArray(pt2Wcs),</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">false</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeVector3d v1Wcs(pt1Wcs-centerWcs), </font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; v2Wcs(pt2Wcs-centerWcs);</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// create the WCS vectors</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Get the normal for the new arc.</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeVector3d arcNorm=v1Wcs.crossProduct(v2Wcs);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Create the new Arc</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Note radius is distance from centerWcs to pt1Wcs.</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"> AcDbArc * pArc=</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">new</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; AcDbArc(centerWcs,arcNorm,</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">&#160; centerWcs.distanceTo(pt1Wcs),0,6.28);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Get the reference Vector...</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> AcGeVector3d arcRef=arcNorm.perpVector();</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"> arcNorm.negate();</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// We want our arc between the two </font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// points, not everywhere but in-between. </font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">double</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> startAngle= v1Wcs.angleTo(arcRef,arcNorm);</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">double</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> endAngle = v2Wcs.angleTo(arcRef,arcNorm);</font></span></font></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Set the Angles</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> pArc-&gt;setStartAngle(startAngle);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000"> pArc-&gt;setEndAngle(endAngle);</font></font></span></p>    <p style="margin: 0px"><font face="Consolas"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"> postToModelSpace(pArc);</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Append To MODEL SPACE</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Consolas"><font style="font-size: 8pt" color="#000000">}</font></font></span></p> </div>  <p>To keep this example simple, the function postToModelSpace(), which just appends the new entity to the model space of the current drawing has been omitted.</p>
