---
layout: "post"
title: "Use getClosestPointTo() and onSegAt() to locate a polyline vertex near a point"
date: "2012-06-28 14:45:46"
author: "Wayne Brill"
categories:
  - "AutoCAD"
  - "ObjectARX"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/autocad/2012/06/use-getclosestpointto-and-onsegat-to-locate-a-polyline-vertex-near-a-point.html "
typepad_basename: "use-getclosestpointto-and-onsegat-to-locate-a-polyline-vertex-near-a-point"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p>You can use getClosestPointTo() and onSegAt() to find a vertex of a polyline closest to a selected point. Here is an ObjectARX example that shows this idea. To try this run a command that runs this function. If you select a polyline the command line will display the number of the segment of the polyline (where you selected the polyline).</p>  <div style="font-family: consolas; background: white; color: black; font-size: 10pt">   <p style="margin: 0px">&#160;<span style="color: blue">static</span> <span style="color: blue">void</span> TEST_PointOnPoly(<span style="color: blue">void</span>)</p>    <p style="margin: 0px"> {</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; ads_name ename;</p>    <p style="margin: 0px">&#160; ads_point pt, ptWcs;</p>    <p style="margin: 0px">&#160; AcDbObjectId Id;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">if</span>(acedEntSel(_T(<span style="color: #a31515">&quot;Select Pline: &quot;</span>),</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ename,pt)!=RTNORM)</p>    <p style="margin: 0px">&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: green">// Convert to WCS incase selection was made </span></p>    <p style="margin: 0px">&#160; <span style="color: green">// while in a UCS.</span></p>    <p style="margin: 0px">&#160; acdbUcs2Wcs(pt, ptWcs, Adesk::kFalse); </p>    <p style="margin: 0px">&#160; acdbGetObjectId(Id,ename);</p>    <p style="margin: 0px">&#160; AcDbEntity* pEnt;</p>    <p style="margin: 0px">&#160; acdbOpenObject(pEnt,Id,AcDb::kForRead,<span style="color: blue">false</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; AcDbPolyline* pLine=NULL;</p>    <p style="margin: 0px">&#160; pLine=AcDbPolyline::cast(pEnt);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">if</span>(!pLine)</p>    <p style="margin: 0px">&#160; {</p>    <p style="margin: 0px">&#160;&#160; acutPrintf(_T</p>    <p style="margin: 0px">&#160;&#160;&#160; (<span style="color: #a31515">&quot;Selected Entity not a Polyline&quot;</span>));</p>    <p style="margin: 0px">&#160;&#160; pEnt-&gt;close();</p>    <p style="margin: 0px">&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; AcGePoint3d clickpt;</p>    <p style="margin: 0px">&#160; <span style="color: green">// This will convert the pick point to a </span></p>    <p style="margin: 0px">&#160; <span style="color: green">// point on the polyline</span></p>    <p style="margin: 0px">&#160; pLine-&gt;getClosestPointTo(asPnt3d(ptWcs), clickpt);</p>    <p style="margin: 0px">&#160; <span style="color: green">// Convert to 2d point, needed below... </span></p>    <p style="margin: 0px">&#160; AcGePoint2d clickpt2d(clickpt.x, clickpt.y); </p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">for</span>(<span style="color: blue">unsigned</span> <span style="color: blue">int</span> c=0; pLine-&gt;numVerts() &gt; c ; c++)</p>    <p style="margin: 0px">&#160; {</p>    <p style="margin: 0px">&#160;&#160; <span style="color: blue">double</span> segParam;</p>    <p style="margin: 0px">&#160;&#160; <span style="color: green">// This is the test filter here...it uses the </span></p>    <p style="margin: 0px">&#160;&#160; <span style="color: green">// nifty API onSegAt</span></p>    <p style="margin: 0px">&#160;&#160; <span style="color: blue">if</span>(pLine-&gt;onSegAt(c, clickpt2d, segParam))&#160; </p>    <p style="margin: 0px">&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160; acutPrintf(_T(<span style="color: #a31515">&quot;Selected Segment: %d \n&quot;</span>),c+1);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">break</span>;</p>    <p style="margin: 0px">&#160;&#160; }</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">&#160; pLine-&gt;close();</p>    <p style="margin: 0px"> }</p> </div>
