---
layout: "post"
title: "Using WblockCloneObjects to copy a Layout from the active document to a new drawing"
date: "2012-07-13 17:03:30"
author: "Madhukar Moogala"
categories:
  - ".NET"
  - "AutoCAD"
  - "Stephen Preston"
original_url: "https://adndevblog.typepad.com/autocad/2012/07/using-wblockcloneobjects-to-copy-a-layout-from-the-active-document-to-a-new-drawing.html "
typepad_basename: "using-wblockcloneobjects-to-copy-a-layout-from-the-active-document-to-a-new-drawing"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/stephen-preston.html">Stephen Preston</a></p>  <p>Another Friday afternoon, another DevNote migrated. This VB.NET sample copies a Layout from one drawing to another using CopyFrom and WblockCloneObjects.</p>  <div style="font-family: consolas; background: white; color: black; font-size: 14pt">   <p style="margin: 0px">&#160;<font size="2">&#160;&#160; &lt;<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;copyLayout&quot;</span>)&gt; _</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: blue">Sub</span> copyLayoutToNewDwg()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> layout <span style="color: blue">As</span> <span style="color: blue">New</span> <span style="color: #2b91af">Layout</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> layoutNameInCurDwg <span style="color: blue">As</span> <span style="color: blue">String</span> = <span style="color: #a31515">&quot;Layout1&quot;</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> lytMgr <span style="color: blue">As</span> <span style="color: #2b91af">LayoutManager</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> ed <span style="color: blue">As</span> <span style="color: #2b91af">Editor</span> =</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Editor()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> layoutId <span style="color: blue">As</span> <span style="color: #2b91af">ObjectId</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Get orignal drawing</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> db <span style="color: blue">As</span> <span style="color: #2b91af">Database</span> =</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Database</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: green">'create a new drawing</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> newDb <span style="color: blue">As</span> <span style="color: #2b91af">Database</span> = <span style="color: blue">New</span> <span style="color: #2b91af">Database</span>(<span style="color: blue">True</span>, <span style="color: blue">False</span>)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Using</span> tr <span style="color: blue">As</span> <span style="color: #2b91af">Transaction</span> = newDb.TransactionManager.StartTransaction()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Make the working database the new database</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">HostApplicationServices</span>.WorkingDatabase = newDb</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Create a new Layout</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> newLytMgr <span style="color: blue">As</span> <span style="color: #2b91af">LayoutManager</span> = <span style="color: #2b91af">LayoutManager</span>.Current()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> newLayoutId <span style="color: blue">As</span> <span style="color: #2b91af">ObjectId</span> = newLytMgr.CreateLayout(<span style="color: #a31515">&quot;newLayout&quot;</span>)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> newLayout <span style="color: blue">As</span> <span style="color: #2b91af">Layout</span> = tr.GetObject(newLayoutId, <span style="color: #2b91af">OpenMode</span>.ForWrite)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Make the original database the working database</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">HostApplicationServices</span>.WorkingDatabase = db</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Using</span> tr2 <span style="color: blue">As</span> <span style="color: #2b91af">Transaction</span> = db.TransactionManager.StartTransaction()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Get the dictionary of the original database</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> lytDict <span style="color: blue">As</span> <span style="color: #2b91af">DBDictionary</span> =</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr2.GetObject(db.LayoutDictionaryId, <span style="color: #2b91af">OpenMode</span>.ForRead)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Make sure the layout existes in the original database</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> <span style="color: blue">Not</span> lytDict.Contains(layoutNameInCurDwg) <span style="color: blue">Then</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;Layout named &quot;&quot;Layout1&quot;&quot; does not exist in current dwg&quot;</span>)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Return</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Get the layout in the original database</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lytMgr = <span style="color: #2b91af">LayoutManager</span>.Current()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; layoutId = lytMgr.GetLayoutId(layoutNameInCurDwg)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; layout = tr2.GetObject(layoutId, <span style="color: #2b91af">OpenMode</span>.ForRead)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLayout.CopyFrom(layout)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Get the block table record of the existing layout</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> blkTableRec <span style="color: blue">As</span> <span style="color: #2b91af">BlockTableRecord</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; blkTableRec =</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr2.GetObject(layout.BlockTableRecordId, <span style="color: #2b91af">OpenMode</span>.ForRead)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">'Get the object ids of the objects in the existing block table record</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> objIdCol <span style="color: blue">As</span> <span style="color: blue">New</span> <span style="color: #2b91af">ObjectIdCollection</span>()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">For</span> <span style="color: blue">Each</span> objId <span style="color: blue">As</span> <span style="color: #2b91af">ObjectId</span> <span style="color: blue">In</span> blkTableRec</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; objIdCol.Add(objId)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Next</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Clone the objects to the new layout</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> idMap <span style="color: blue">As</span> <span style="color: #2b91af">IdMapping</span> = <span style="color: blue">New</span> <span style="color: #2b91af">IdMapping</span>()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newDb.WblockCloneObjects(objIdCol,</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLayout.BlockTableRecordId,</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; idMap,</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">DuplicateRecordCloning</span>.MangleName,</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">False</span>)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr2.Commit()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Using</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit()</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; newDb.SaveAs(<span style="color: #a31515">&quot;c:\newLayout.dwg&quot;</span>, <span style="color: #2b91af">DwgVersion</span>.Newest)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Using</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></font></p> </div>
