---
layout: "post"
title: "Selecting Viewport with clipping"
date: "2012-05-28 04:43:33"
author: "Adam Nagy"
categories:
  - "Adam Nagy"
  - "AutoCAD"
  - "ObjectARX"
original_url: "https://adndevblog.typepad.com/autocad/2012/05/selecting-viewport-with-clipping.html "
typepad_basename: "selecting-viewport-with-clipping"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/adam-nagy.html" target="_self">Adam Nagy</a></p>  <p>I prompt the user to select a Viewport. This works fine, unless the Viewport has a clipping polyline in which case I get back the polyline instead of the Viewport. How could I get back the Viewport from the polyline?</p>  <div style="font-family: Courier New; font-size: 8pt; color: black; background: white;"> <p style="margin: 0px;"><span style="line-height: 140%;">ads_name ss;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">ads_name eName;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">ads_point pt;</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">if</span><span style="line-height: 140%;">( RTNORM != acedEntSel(_T(</span><span style="color: #a31515; line-height: 140%;">&quot;\nPlease pick a viewport&quot;</span><span style="line-height: 140%;">), eName, pt ))</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">return</span><span style="line-height: 140%;">;</span></p> <p style="margin: 0px;"><span style="color: green; line-height: 140%;">// eName might be a polyline even though the user selected a Viewport</span></p> </div>  <p><b>Solution</b></p>  <p>You can get back the Viewport (if the selected entity is a clipping boundary of a viewport) using AcDbLayoutManager::getNonRectVPIdFromClipId():</p>  <div style="font-family: Courier New; font-size: 8pt; color: black; background: white;"> <p style="margin: 0px;"><span style="line-height: 140%;">AcDbObjectId polyId;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">acdbGetObjectId(polyId, eName);</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">AcDbLayoutManager *layoutMgr;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">layoutMgr = acdbHostApplicationServices()-&gt;layoutManager();</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">AcDbObjectId viewportId = </span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; layoutMgr-&gt;getNonRectVPIdFromClipId(polyId); </span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">if</span><span style="line-height: 140%;"> (viewportId.isNull())</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">{</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: green; line-height: 140%;">// not a viewport clipping polyline</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">}</span></p> </div>  <p>You could also restrict the user to selecting Viewports only:</p>  <div style="font-family: Courier New; font-size: 8pt; color: black; background: white;"> <p style="margin: 0px;"><span style="line-height: 140%;">ads_name ss;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">ads_name eName;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">ads_point pt;</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="color: green; line-height: 140%;">// instead of...</span></p> <p style="margin: 0px;"><span style="color: green; line-height: 140%;">// if( RTNORM != acedEntSel(</span></p> <p style="margin: 0px;"><span style="color: green; line-height: 140%;">//&nbsp;&nbsp; _T(&quot;\nPlease pick a viewport&quot;), eName, pt )) </span></p> <p style="margin: 0px;"><span style="color: green; line-height: 140%;">// return;</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">resbuf filter;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">filter.resval.rstring = _T(</span><span style="color: #a31515; line-height: 140%;">&quot;VIEWPORT&quot;</span><span style="line-height: 140%;">);</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">filter.rbnext = NULL;</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">filter.restype = 0;</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">ACHAR* texts[] = {_T(</span><span style="color: #a31515; line-height: 140%;">&quot;\nPlease pick a viewport&quot;</span><span style="line-height: 140%;">), _T(</span><span style="color: #a31515; line-height: 140%;">&quot;&quot;</span><span style="line-height: 140%;">)}; </span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">int</span><span style="line-height: 140%;"> ret = acedSSGet(_T(</span><span style="color: #a31515; line-height: 140%;">&quot;_-M:S:$&quot;</span><span style="line-height: 140%;">), texts, NULL, &amp;filter, ss);</span></p> <p style="margin: 0px;"><span style="color: blue; line-height: 140%;">if</span><span style="line-height: 140%;"> (RTNORM != ret)</span></p> <p style="margin: 0px;"><span style="line-height: 140%;">&nbsp; </span><span style="color: blue; line-height: 140%;">return</span><span style="line-height: 140%;">;</span></p> <p style="margin: 0px;">&nbsp;</p> <p style="margin: 0px;"><span style="line-height: 140%;">acedSSName(ss, 0, eName);</span></p> </div>
