---
layout: "post"
title: "ObjectId.GetObject()"
date: "2012-07-05 14:33:41"
author: "Madhukar Moogala"
categories:
  - ".NET"
  - "AutoCAD"
  - "Stephen Preston"
original_url: "https://adndevblog.typepad.com/autocad/2012/07/objectidgetobject.html "
typepad_basename: "objectidgetobject"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/stephen-preston.html">Stephen Preston</a></p>  <p>Much of the sample code for the AutoCAD .NET API makes use of the Transaction.GetObject() method to open database-resident objects. Code that uses this method will look something like this:</p>  <div style="font-family: consolas; background: white; color: black; font-size: 14pt">   <p style="margin: 0px"><font size="2">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;test1&quot;</span>)]</font></p>    <p style="margin: 0px"><font size="2"><span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">void</span>&#160; transtest1()</font></p>    <p style="margin: 0px"><font size="2">{</font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: #2b91af">Document</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: #2b91af">Database</span> db = doc.Database;</font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = db.TransactionManager.StartTransaction())</font></p>    <p style="margin: 0px"><font size="2">&#160; {</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: #2b91af">BlockTable</span> bt = </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.GetObject(db.BlockTableId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">BlockTable</span>;</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">ObjectId</span> btrId <span style="color: blue">in</span> bt)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; {</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> btr = </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.GetObject(btrId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">BlockTableRecord</span>;</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Do something</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; }</font></p>    <p style="margin: 0px"><font size="2">&#160; }</font></p>    <p style="margin: 0px"><font size="2">}</font></p> </div>  <p>However, there is a more succinct way to open an object in a transaction – using ObjectId.GetObject(). For some reason this function is often overlooked – perhaps because sample code writers prefer to emphasize that transactions are being used by showing the more explicit Transaction.GetObject(). The same code using ObjectId.GetObject() looks like this:</p>  <div style="font-family: consolas; background: white; color: black; font-size: 14pt">   <p style="margin: 0px"><font size="2">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;test2&quot;</span>)]</font></p>    <p style="margin: 0px"><font size="2"><span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">void</span>&#160; transtest2()</font></p>    <p style="margin: 0px"><font size="2">{</font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: #2b91af">Document</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: #2b91af">Database</span> db = doc.Database;</font></p>    <p style="margin: 0px"><font size="2">&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = db.TransactionManager.StartTransaction())</font></p>    <p style="margin: 0px"><font size="2">&#160; {</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: #2b91af">BlockTable</span> bt = </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.BlockTableId.GetObject(<span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">BlockTable</span>;</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">ObjectId</span> btrId <span style="color: blue">in</span> bt)</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; {</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> btr = </font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160;&#160;&#160; btrId.GetObject(<span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">BlockTableRecord</span>;</font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//Do something</span></font></p>    <p style="margin: 0px"><font size="2">&#160;&#160;&#160; }</font></p>    <p style="margin: 0px"><font size="2">&#160; }</font></p>    <p style="margin: 0px"><font size="2">}</font></p> </div>  <p>Under the hood (and as explained in the helpfiles) , the ObjectId.GetObject() method is calling the TransactionManager.GetObject() method on the topmost transaction. If there is no Transaction active, then an exception is thrown.</p>  <p>Of course, there are even more ways to open database-resident objects that we’ve discussed before on this blog. There is the <a href="http://adndevblog.typepad.com/autocad/2012/04/dynamicnet-api-for-autocad-2013.html">Dynamic .NET introduced in AutoCAD 2013</a>, and the (non-transaction)<a href="http://adndevblog.typepad.com/autocad/2012/06/creating-a-polyline3d-without-using-transactions.html">Open/Close</a> technique (which is conveniently wrapped by the OpenCloseTransaction object if you want to not use transactions in exactly the same way as you’d use transactions <img style="border-bottom-style: none; border-right-style: none; border-top-style: none; border-left-style: none" class="wlEmoticon wlEmoticon-smile" alt="Smile" src="/assets/image_14933.jpg" />).</p>
