---
layout: "post"
title: "Plant SDK: Get ObjectID by PnPID"
date: "2012-07-20 06:03:25"
author: "Marat Mirgaleev"
categories:
  - ".NET"
  - "2011"
  - "2012"
  - "2013"
  - "Marat Mirgaleev"
  - "Plant3D"
  - "PnID"
original_url: "https://adndevblog.typepad.com/autocad/2012/07/plant-sdk-get-objectid-by-pnpid.html "
typepad_basename: "plant-sdk-get-objectid-by-pnpid"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/marat-mirgaleev.html" target="_self">Marat Mirgaleev</a></p>  <p><b>Issue</b></p>  <p><em>Is it possible to get the objectID by its PnPID or RowID?</em></p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>Yes. It is a two steps process, because there is a one-to-many possibility.</p>  <p>PnPID and RowID are the same thing.    <br />&#160; 1. DataLinksManager.FindAcPpObjectIds(rowId) --&gt; collection of PpObjectId     <br />&#160; 2. DataLinksManager.MakeAcDbObjectId(ppObjId) --&gt; converts PpObjectId to ObjectId     <br />There are various flavors of those functions. The main point to get across is that multiple AcDbObjectIds may be linked to a single RowID.</p>  <p>Here is a sample:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: green">// Conversions of IDs back and forth.</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: green">//------------------------------------------------------------------</span></p>    <p style="margin: 0px"><span style="line-height: 140%">[CommandMethod(</span><span style="line-height: 140%; color: #a31515">&quot;TestIds&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> TestIds()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// Prepare to the work: Let's get some entity's ObjectId</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; Database db = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; Application.DocumentManager.MdiActiveDocument.Database;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; DataLinksManager dlm = DataLinksManager.GetManager(db);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; ObjectId entId = ed.GetEntity(</span><span style="line-height: 140%; color: #a31515">&quot;Pick a P&amp;ID item: &quot;</span><span style="line-height: 140%">).ObjectId;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// Now get the PnPID (i.e. PpObjectId)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160; from the selected entity's ObjectId</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; PpObjectId pnpId = dlm.MakeAcPpObjectId(entId);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// Now let's do an opposite action - find ObjectId(s) of the entity</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> rowId1 = dlm.FindAcPpRowId(entId); </span><span style="line-height: 140%; color: green">// You can use ObjectId</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> rowId2 = dlm.FindAcPpRowId(pnpId); </span><span style="line-height: 140%; color: green">//&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; or PpObjectId</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// rowId1 and rowId2 are always equal</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; PpObjectIdArray ids = dlm.FindAcPpObjectIds(rowId1);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// NOTE: It returns a COLLECTION of AcPpObjectId!</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160;&#160;&#160; I.e., multiple AcDbObjectIds may be linked to a single RowID</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green">// Now find the ObjectID for each PpObjectId</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (PpObjectId ppid </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ids)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; ObjectId oid = dlm.MakeAcDbObjectId(ppid);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; ed.WriteMessage(</span><span style="line-height: 140%; color: #a31515">&quot;\n oid=&quot;</span><span style="line-height: 140%"> + oid.ToString());</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">} </span><span style="line-height: 140%; color: green">// TestIds()</span></p>    <p style="margin: 0px"></p> </div>
