---
layout: "post"
title: "Use SelectCrossingPolygon to select entities in view other than plan"
date: "2012-05-25 11:46:19"
author: "Wayne Brill"
categories:
  - ".NET"
  - "AutoCAD"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/autocad/2012/05/use-selectcrossingpolygon-to-select-entities-in-view-other-than-plan.html "
typepad_basename: "use-selectcrossingpolygon-to-select-entities-in-view-other-than-plan"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p><b>Issue</b></p>  <p>I am using Editor SelectCrossingWindow to select Entities. If the view is not a plan view then some of the entities inside of the window defined by the points are not included in the selection.</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>The selection area using SelectCrossingWindow() is going to be a rectangular shape in WCS that is horizontal. To see the selection area for the crossing window, in WCS (plan view) draw a rectangle using the REC command using the points used for the crossing window. Then go to the non plan view, change the UCS to view and draw another rectangle by snapping to the points used for the first rectangle. Change the UCS back to world before you run the code and you will see the entities that are inside or cross the second rectangle are selected. </p>  <p>Instead of using SelectCrossingWindow use SelectCrossingPolygon(). Here is an example. If the entities are visible, then this will get the entities in the area defined by the points. (Regardless of the current view). This example uses a filter to only select lines.</p>  <div style="font-family: consolas; background: white; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;SEL&quot;</span>)]</p>    <p style="margin: 0px"><span style="color: blue">public</span> <span style="color: blue">void</span> MySelection()</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Document</span> doc = Autodesk.AutoCAD</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; .ApplicationServices.<span style="color: #2b91af">Application</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; .DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Editor</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point3d</span> p1 = <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>(10.0, 10.0, 0.0);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point3d</span> p2 = <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>(10.0, 11.0, 0.0);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point3d</span> p3 = <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>(11.0, 11.0, 0.0);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point3d</span> p4 = <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>(11.0, 10.0, 0.0);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Point3dCollection</span> pntCol = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Point3dCollection</span>();</p>    <p style="margin: 0px">&#160;&#160;&#160; pntCol.Add(p1);</p>    <p style="margin: 0px">&#160;&#160;&#160; pntCol.Add(p2);</p>    <p style="margin: 0px">&#160;&#160;&#160; pntCol.Add(p3);</p>    <p style="margin: 0px">&#160;&#160;&#160; pntCol.Add(p4);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">int</span> numOfEntsFound = 0;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">PromptSelectionResult</span> pmtSelRes = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">TypedValue</span>[] typedVal = <span style="color: blue">new</span> <span style="color: #2b91af">TypedValue</span>[1];</p>    <p style="margin: 0px">&#160;&#160;&#160; typedVal[0] = <span style="color: blue">new</span> <span style="color: #2b91af">TypedValue</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((<span style="color: blue">int</span>)<span style="color: #2b91af">DxfCode</span>.Start, <span style="color: #a31515">&quot;Line&quot;</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">SelectionFilter</span> selFilter = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">SelectionFilter</span>(typedVal);</p>    <p style="margin: 0px">&#160;&#160;&#160; pmtSelRes = ed.SelectCrossingPolygon</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (pntCol, selFilter);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// May not find entities in the UCS area</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// between p1 and p3 if not PLAN view</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// pmtSelRes = </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//&#160;&#160;&#160; ed.SelectCrossingWindow(p1, p3, selFilter);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">if</span> (pmtSelRes.Status == <span style="color: #2b91af">PromptStatus</span>.OK)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">ObjectId</span> objId <span style="color: blue">in</span> </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pmtSelRes.Value.GetObjectIds())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; numOfEntsFound++;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;Entities found &quot;</span> + </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; numOfEntsFound.ToString());</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;\nDid not find entities&quot;</span>);</p>    <p style="margin: 0px">}</p> </div>
