---
layout: "post"
title: "Create layers with (entmake) or ads_entmake()"
date: "2013-01-30 04:02:59"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "AutoCAD"
  - "LISP"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/create-layers-with-entmake-or-ads_entmake.html "
typepad_basename: "create-layers-with-entmake-or-ads_entmake"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>It is possible to create layers using ads_entmake() or (entmake). However, you need to specify all the100 subclass data markers on calling entmake. A subclass data marker specifies the derived class names of an object. Specifying these subclass data markers is necessary for all new Entity/Object types. For R12 compatibility reasons, you can omit these subclass data markers for the old R12 entities. </p>  <p>It wasn't possible to entmake layers in R12; this is why you need to specify the subclass data markers for layers as well:</p>  <p><span style="line-height: 120%; font-family: &#39;courier new&#39;, courier; font-size: 8pt"><span style="color: #ff0000">(</span>entmake <span style="color: #ff0000">(</span>list <span style="color: #ff0000">(</span>cons <span style="color: #008000">0</span>&#160;<span style="color: #ff00ff">&quot;LAYER&quot;</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span>cons <span style="color: #008000">100</span>&#160;<span style="color: #ff00ff">&quot;AcDbSymbolTableRecord&quot;</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span>cons <span style="color: #008000">100</span>&#160;<span style="color: #ff00ff">&quot;AcDbLayerTableRecord&quot;</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span>cons <span style="color: #008000">2</span>&#160;<span style="color: #ff00ff">&quot;My Layer Name&quot;</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span>cons <span style="color: #008000">70</span>&#160;<span style="color: #008000">0</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span>cons <span style="color: #008000">62</span>&#160;<span style="color: #008000">7</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #ff0000">(</span>cons <span style="color: #008000">6</span>&#160;<span style="color: #ff00ff">&quot;CONTINUOUS&quot;</span><span style="color: #ff0000">)</span>      <br />&#160;&#160;&#160;&#160; <span style="color: #ff0000">)</span>      <br /><span style="color: #ff0000">)</span></span></p> I wanted to create a layer using ads_entmake(), but ads_entmake() returns the error code RTREJ (AutoCAD rejected request -- invalid). Because the routine has to be used in drawings where that layer already could exist, the solution with ads_command() is not so nice, because of the warning &quot;Layer already exists&quot;. The entmake-solution raises no warning to the user if a layer already exists
