---
layout: "post"
title: "Purging anonymous blocks"
date: "2013-01-05 00:32:30"
author: "Daniel Du"
categories:
  - "AutoCAD"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/purging-anonymous-blocks-using-vba.html "
typepad_basename: "purging-anonymous-blocks-using-vba"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/daniel-du.html">Daniel Du</a></p> <p><b>Issue</b></p> <p>How do I purge all unnamed (and unreferenced) blocks from a drawing programmatically?</p> <p><a name="section2"></a></p> <p><b>Solution</b></p> <p>To purge all unreferenced objects from a drawing, you can use the PurgeAll command. </p> <p>Here is the VBA code: </p><pre style="line-height: normal; font-family: ; background: white; color: "><span style="color: "><font color="#0000ff" face="新宋体"><font style="font-size: 7.8pt">Sub</font></font></span><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000"> del_all()<br> <br>&nbsp;&nbsp;&nbsp; ThisDrawing.Application.ActiveDocument.PurgeAll()<br> </font><br><span style="color: "><font color="#0000ff">End</font></span><font color="#000000">&nbsp;</font></font><span style="color: "><font style="font-size: 7.8pt" color="#0000ff">Sub</font></span></font></pre>
<p><pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><span style="color: "><font style="font-size: 7.8pt" color="#0000ff"></font></span></font></pre>And here is a sample of .net(C#) code which deletes all unreferenced blocks:
<pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><font color="#000000"><font style="font-size: 7.8pt">[</font></font><font style="font-size: 7.8pt"><span style="color: "><font color="#2b91af">CommandMethod</font></span><font color="#000000">(</font><span style="color: "><font color="#a31515">"ClearUnrefedBlocks"</font></span><font color="#000000">)]</font><br><span style="color: "><font color="#0000ff">public</font></span><font color="#000000">&nbsp;</font><span style="color: "><font color="#0000ff">void</font></span></font></font><font style="font-size: 7.8pt"><font face="新宋体"><font color="#000000"> ClearUnrefedBlocks()<br>{<br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">Document</font></span><font color="#000000"> doc = </font><span style="color: "><font color="#2b91af">Application</font></span></font><font face="新宋体"><font color="#000000">.DocumentManager.MdiActiveDocument;<br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">Editor</font></span></font><font face="新宋体"><font color="#000000"> ed = doc.Editor;<br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">Database</font></span></font><font face="新宋体"><font color="#000000"> db = doc.Database;<br> <br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#0000ff">using</font></span><font color="#000000"> (</font><span style="color: "><font color="#2b91af">Transaction</font></span></font><font face="新宋体"><font color="#000000"> trans = db.TransactionManager.StartTransaction())<br>&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">BlockTable</font></span><font color="#000000"> bt = trans.GetObject(db.BlockTableId, </font><span style="color: "><font color="#2b91af">OpenMode</font></span></font><font face="新宋体"><font color="#000000">.ForWrite)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#0000ff">as</font></span><font color="#000000">&nbsp;</font><span style="color: "><font color="#2b91af">BlockTable</font></span></font><font face="新宋体"><font color="#000000">;<br> <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#0000ff">foreach</font></span><font color="#000000"> (ObjectId oid </font><span style="color: "><font color="#0000ff">in</font></span></font><font face="新宋体"><font color="#000000"> bt)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span><font color="#000000"> btr = trans.GetObject(oid, </font><span style="color: "><font color="#2b91af">OpenMode</font></span></font><font face="新宋体"><font color="#000000">.ForWrite)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#0000ff">as</font></span><font color="#000000">&nbsp;</font><span style="color: "><font color="#2b91af">BlockTableRecord</font></span></font></font><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000">;<br> <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#0000ff">if</font></span><font color="#000000"> (btr.GetBlockReferenceIds(</font><span style="color: "><font color="#0000ff">false</font></span><font color="#000000">, </font><span style="color: "><font color="#0000ff">false</font></span><font color="#000000">).Count == 0<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &amp;&amp; !btr.IsLayout)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br> <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; btr.Erase();<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br> <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br> <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; trans.Commit();<br>&nbsp;&nbsp;&nbsp; }<br> <br>}</font></font></font></pre><pre style="line-height: normal; font-family: ; background: white; color: "></pre>
<p>Another option is to use Wblock. Any unreferenced symbols in the input database are omitted in the new database (which makes the new database potentially cleaner and smaller than the original).</p><pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><font color="#000000"><font style="font-size: 7.8pt">[</font></font><font style="font-size: 7.8pt"><span style="color: "><font color="#2b91af">CommandMethod</font></span><font color="#000000">(</font><span style="color: "><font color="#a31515">"ClrDb"</font></span><font color="#000000">)]</font><br><span style="color: "><font color="#0000ff">public</font></span><font color="#000000">&nbsp;</font><span style="color: "><font color="#0000ff">void</font></span></font></font><font style="font-size: 7.8pt"><font face="新宋体"><font color="#000000"> ClearDatabase()<br>{<br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">Document</font></span><font color="#000000"> doc = </font><span style="color: "><font color="#2b91af">Application</font></span></font><font face="新宋体"><font color="#000000">.DocumentManager.MdiActiveDocument;<br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">Editor</font></span></font><font face="新宋体"><font color="#000000"> ed = doc.Editor;<br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">Database</font></span></font><font face="新宋体"><font color="#000000"> db = doc.Database;<br> <br>&nbsp;&nbsp;&nbsp; </font><span style="color: "><font color="#2b91af">Database</font></span></font></font><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000"> newDb = db.Wblock();<br>&nbsp;&nbsp;&nbsp; newDb.SaveAs(</font><span style="color: "><font color="#a31515">@"c:\temp\clrdb.dwg"</font></span><font color="#000000">, </font><span style="color: "><font color="#2b91af">DwgVersion</font></span><font color="#000000">.Current);<br> <br>}</font></font></font></pre>
