---
layout: "post"
title: "Accessing LDATA values from VBA"
date: "2013-01-04 23:33:19"
author: "Daniel Du"
categories:
  - "AutoCAD"
  - "Daniel Du"
  - "LISP"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/accessing-ldata-values-from-vba.html "
typepad_basename: "accessing-ldata-values-from-vba"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/daniel-du.html">Daniel Du</a></p>  <p><b>Issue</b></p>  <p>A VLISP function can be used to create a dictionary just like:</p>  <p>(vlax-ldata-put &quot;Test&quot; &quot;Helper&quot; &quot;Good&quot;)</p>  <p>And a dictionary named &quot;Test&quot; is created, and a (vlax-ldata-get &quot;Test&quot; &quot;Helper&quot;) retrieves the return value, &quot;Good&quot;. From VBA, how can I get the dictionary data value of &quot;Good&quot;?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>VLISP ldata is attached to a custom object with class name &quot;vlo_VL&quot; and then the object is added to the Named Object Dictionary. However, a custom object is not penetrable by means of the VBA object model alone. You cannot create custom entities/objects with VBA, but you can develop custom entities with ObjectARX and create an ActiveX interface to it so that it can be used within VBA. Unfortunately, there is no direct interface (or Automation server) to a vlo_VL object.</p>  <p>The AutoCAD Visual LISP Automation server (an unsupported interface) can be used to bridge the gap between VBA macro and the LISP environment, though.</p>  <p>If the following has already been entered successfully at the command line:</p>  <pre>(vl-load-com)<br />(vlax-ldata-put &quot;Test&quot; &quot;Helper&quot; &quot;Good&quot;)</pre>

<p>Then, with a little effort a VBA macro can use the LISP server's generalized object model:</p>

<pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><span style="color: "><font color="#0000ff"><font style="font-size: 7.8pt">Function</font></font></span><font style="font-size: 7.8pt"><font color="#000000"> readEvalHelper(app </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span></font></font><font style="font-size: 7.8pt"><font face="新宋体"><font color="#000000">)<br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' this is a helper function</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160; vld = app.ActiveDocument<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> vlf_read </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span><br /><font color="#000000">&#160;&#160;&#160; vlf_read = vld.Functions.Item(</font><span style="color: "><font color="#a31515">&quot;read&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> vl_obj1 </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span><br /><font color="#000000">&#160;&#160;&#160; vl_obj1 = vlf_read.funcall(</font><span style="color: "><font color="#a31515">&quot;(defun read-eval (arg)(eval (read arg)))&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> vlf_eval </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span><br /><font color="#000000">&#160;&#160;&#160; vlf_eval = vld.Functions.Item(</font><span style="color: "><font color="#a31515">&quot;eval&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> vl_obj2 </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160; vl_obj2 = vlf_eval.funcall(vl_obj1)<br /> </font><br /><span style="color: "><font color="#0000ff">End</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Function</font></span><br /></font><font face="新宋体"><font color="#000000"> <br /> </font><br /><span style="color: "><font color="#0000ff">Public</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Sub</font></span></font><font face="新宋体"><font color="#000000"> vlsGetLData()<br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> vlApp </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span><br /><font color="#000000">&#160;&#160;&#160; vlApp = CreateObject(</font><span style="color: "><font color="#a31515">&quot;VL.Application.16&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br /> <br />&#160;&#160;&#160; readEvalHelper(vlApp)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> invokeIt </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span><br /><font color="#000000">&#160;&#160;&#160; invokeIt = vlApp.ActiveDocument.Functions.Item(</font><span style="color: "><font color="#a31515">&quot;read-eval&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br />&#160;&#160;&#160; invokeIt.funcall(</font><span style="color: "><font color="#a31515">&quot;(setq lDatum (vlax-ldata-get &quot;&quot;Test&quot;&quot; &quot;&quot;Helper&quot;&quot;))&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br /> <br />&#160;&#160;&#160; sym = vlApp.ActiveDocument.Functions.Item(</font><span style="color: "><font color="#a31515">&quot;read&quot;</font></span><font color="#000000">).funcall(</font><span style="color: "><font color="#a31515">&quot;lDatum&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br />&#160;&#160;&#160; GetLispSym = vlApp.ActiveDocument.Functions.Item(</font><span style="color: "><font color="#a31515">&quot;eval&quot;</font></span></font><font face="新宋体"><font color="#000000">).funcall(sym)<br />&#160;&#160;&#160; MsgBox(</font><span style="color: "><font color="#a31515">&quot;Key's data is:&quot;</font></span></font></font><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000"> + Chr(13) + GetLispSym)<br /> </font><br /><span style="color: "><font color="#0000ff">End</font></span><font color="#000000">&#160;</font></font><span style="color: "><font style="font-size: 7.8pt" color="#0000ff">Sub</font></span></font></pre>
