---
layout: "post"
title: "How to create a new layout and paper space viewport?"
date: "2013-01-04 23:41:09"
author: "Daniel Du"
categories:
  - "AutoCAD"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/how-to-create-a-new-layout-and-paper-space-viewport.html "
typepad_basename: "how-to-create-a-new-layout-and-paper-space-viewport"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/daniel-du.html">Daniel Du</a></p>  <p><b>Issue</b></p>  <p>How do I use the AutoCAD VBA API to create a new layout and a new paper space viewport?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>To create a new layout, use the add method of the layouts property of the drawing:</p>  <pre style="line-height: normal; font-family: ; background: white"><font face="新宋体"><span style="color: "><font color="#0000ff"><font style="font-size: 7.8pt">Set</font></font></span><font style="font-size: 7.8pt" color="#000000"> lyt = ThisDrawing.Layouts.Add(&quot;Test1&quot;)</font></font></pre>

<p>To create a new paper space viewport, use the AddPViewport of the drawing's paper space property:</p>

<pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><span style="color: "><font color="#0000ff"><font style="font-size: 7.8pt">Set</font></font></span><font style="font-size: 7.8pt" color="#000000"> PSVport = ThisDrawing.PaperSpace.AddPViewport(pnt, 5, 4) </font></font><br /></pre>

<p>where pnt is the center of the viewport.</p>

<p>One item of which to be aware is that the paper space property of the drawing references the ActiveLayout. The following procedure creates a new layout and paper space viewport on the new layout.</p>

<pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><span style="color: "><font color="#0000ff"><font style="font-size: 7.8pt">Public</font></font></span><font style="font-size: 7.8pt"><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Sub</font></span></font></font><font style="font-size: 7.8pt"><font face="新宋体"><font color="#000000"> NewLayoutAndNewPVport()<br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> PSVport </font><span style="color: "><font color="#0000ff">As</font></span></font><font face="新宋体"><font color="#000000"> AcadPViewport<br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> lyt </font><span style="color: "><font color="#0000ff">As</font></span></font><font face="新宋体"><font color="#000000"> AcadLayout<br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> pnt(0 </font><span style="color: "><font color="#0000ff">To</font></span><font color="#000000"> 2) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Double</font></span><br /></font><font face="新宋体"><font color="#000000"> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' Create a point to be used for the new paperspace viewport</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160; pnt(0) = 5<br />&#160;&#160;&#160; pnt(1) = 5<br />&#160;&#160;&#160; pnt(2) = 0<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' Create a new layout</font></span><br /><font color="#000000">&#160;&#160;&#160; lyt = ThisDrawing.Layouts.Add(</font><span style="color: "><font color="#a31515">&quot;Test1&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' If a layout named &quot;Test1&quot; already exists comment out</font></span><br /><font color="#000000">&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' the line above and uncomment this line.</font></span><br /><font color="#000000">&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' Set lyt = ThisDrawing.Layouts(&quot;Test1&quot;)</font></span><br /></font><font face="新宋体"><font color="#000000"> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' Make lyt created above the active layout</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160; ThisDrawing.ActiveLayout = lyt<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' Create a new paper space viewport notice that you use</font></span><br /><font color="#000000">&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' the Paperspace property of this drawing. The Paperspace</font></span><br /><font color="#000000">&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' property references the active layout</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160; PSVport = ThisDrawing.PaperSpace.AddPViewport(pnt, 5, 4)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' Make sure the Viewport is displayed and on</font></span><br /><font color="#000000">&#160;&#160;&#160; PSVport.Display(</font><span style="color: "><font color="#0000ff">True</font></span></font><font face="新宋体"><font color="#000000">)<br />&#160;&#160;&#160; PSVport.ViewportOn = </font><span style="color: "><font color="#0000ff">True</font></span><br /></font><font face="新宋体"><font color="#000000"> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' Before making a pViewport active the mspace property needs</font></span><br /><font color="#000000">&#160;&#160;&#160; </font><span style="color: "><font color="#008000">' to be True for a floating viewport</font></span><br /><font color="#000000">&#160;&#160;&#160; ThisDrawing.MSpace = </font><span style="color: "><font color="#0000ff">True</font></span><br /></font></font><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000">&#160;&#160;&#160; ThisDrawing.ActivePViewport = PSVport<br />&#160;&#160;&#160; ThisDrawing.Regen(acActiveViewport)<br /> </font><br /><span style="color: "><font color="#0000ff">End</font></span><font color="#000000">&#160;</font></font><span style="color: "><font style="font-size: 7.8pt" color="#0000ff">Sub</font></span></font><br /></pre>

<pre><br /></pre>

<pre style="line-height: normal; font-family: ; background: white"><br /></pre>
