---
layout: "post"
title: "Rotate3d with ObjectARX"
date: "2013-01-15 11:08:24"
author: "Augusto Goncalves"
categories:
  - "Augusto Goncalves"
  - "AutoCAD"
  - "ObjectARX"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/rotate3d-with-objectarx.html "
typepad_basename: "rotate3d-with-objectarx"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>We suggest two possibilities to use ROTATE3D in an ARX program: call the build-in command or implement using transformBy.</p>  <p><strong><u>Method #1</u></strong></p>  <p>Call the AutoCAD ROTATE3D command using acedInvoke(). As ROTATE3D is located in geom3d.arx in AutoCAD, and is registered with acedDefun, we cannot use acedCommand, but must use acedInvoke. In addition, you have to make sure that the geom3d module is loaded and your function which calls acedInvoke() is registered with acedDefun() and not with acedRegCmds-&gt;addCommand().</p>  <p>The following is sample code:</p>  <p><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">int</font></font></span><font style="font-size: 8pt" color="#000000"> testfunc()</font></font></p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{ </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">// make sure that geom3d.arx is loaded</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; acedArxLoad(_T(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;geom3d.arx&quot;</font></span><font color="#000000">)); </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; ads_name pieces;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; ads_point Point1, Point2;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; Point1[X] =&#160; 1.0;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; Point1[Y] =&#160; 1.0;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; Point1[Z] =&#160; 0.0;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; Point1[X] = 10.0;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; Point1[Y] = 10.0;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; Point1[Z] = 10.0;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; ads_real&#160; Angle = 32;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><span><font style="font-size: 8pt" color="#008000">//Select the entities you want to rotate</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; acedSSGet( NULL,NULL, NULL, NULL, pieces );</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; resbuf* pBuf = acutBuildList(RTSTR,_T(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;c:rotate3d&quot;</font></span><font color="#000000">),</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; RTPICKS, pieces, RTSTR, _T(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;&quot;</font></span><font color="#000000">), RT3DPOINT, Point1, </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; RT3DPOINT, Point2, RTREAL, Angle, RTNONE);</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; resbuf* result=NULL;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; acedInvoke(pBuf,&amp;result); </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; acutRelRb(pBuf); </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">if</font></span><font color="#000000"> (result!=NULL)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; acutRelRb(result);</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">return</font></span><font color="#000000"> RTNORM;</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></p> </div>  <p><strong><u>Method #2</u></strong></p>  <p>With ObjectARX, it is recommended that AcDbEntity::transformBy() is used instead of invoking ROTATE3D. For example, for each entity (ename) with AcGePoint3d start (start) and end (end) points for the axis, and the rotation angle (angle), you can perform the following:</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">double</font></span><font color="#000000"> pi =&#160; 3.14159265359; </font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; AcDbObjectId objId; </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; acdbGetObjectId(objId, ename);&#160; </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; AcDbEntity* pEnt = NULL;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; acdbOpenAcDbEntity(pEnt, objId, AcDb::kForWrite);&#160; </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; AcGeMatrix3d mat;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; mat.setToRotation(angle * pi / 180, end - start, start); </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; pEnt-&gt;transformBy(mat); </font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; pEnt-&gt;close();</font></font></p> </div>
