---
layout: "post"
title: "Setting dimension override string in the required format?"
date: "2013-01-05 00:54:09"
author: "Daniel Du"
categories:
  - "AutoCAD"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/setting-dimension-override-string-in-the-required-format.html "
typepad_basename: "setting-dimension-override-string-in-the-required-format"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/daniel-du.html">Daniel Du</a></p>  <p><b>Issue</b></p>  <p>How can I set the overridden text in the required units and format for a given dimension object? For example, I am using the &quot;AddDimAligned&quot; method to create a dimension between two lines, that is 3'-0&quot;. I then use the &quot;TextOverride&quot; property to override the dimension of 3'-0&quot; to 1.667' but 1.667' is now a string. How can I convert the 1.667' value to display it in Architectural units as 1'-8&quot;?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>TextOverride is a string property and hence you can use data type conversion utilities to format the number to the style you want. In the following VBA example, RealToString method of Utility object is used to format the number to the required style. To control the suppression of zeros, set the DIMZIN system variable.</p>  <p>In this example the value of DIMZIN is set to 1. This will Include zero feet and precisely zero inches while performing the conversions using realToString. You can also use this string &quot;&lt;&gt;&quot; in the TextOverride to display the actual measurement.   <br />For example, you can specify dimobj.TextOverride = &quot;length = &lt;&gt; mm&quot;. This would set the override as &quot;length = 10 mm&quot; if the dimension's measurement is 10mm.</p>  <pre style="line-height: normal; font-family: ; background: white; color: "><span style="color: "><font color="#0000ff" face="新宋体"><font style="font-size: 7.8pt">Sub</font></font></span><font style="font-size: 7.8pt"><font face="新宋体"><font color="#000000"> f_test()<br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> po_dim </font><span style="color: "><font color="#0000ff">As</font></span></font><font face="新宋体"><font color="#000000"> AcadDimAligned<br />&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> p1(2) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Double</font></span><br /><font color="#000000">&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> p2(2) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Double</font></span><br /></font><font face="新宋体"><font color="#000000"> <br />&#160;&#160;&#160; p1(0) = 0 : p1(1) = 0<br />&#160;&#160;&#160; p2(0) = 10 : p2(1) = 10<br /> <br />&#160;&#160;&#160; po_dim = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, p2)<br />&#160;&#160;&#160; po_dim.TextOverride = ThisDrawing.Utility.RealToString(1.667 * 12,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; acArchitectural, 6)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'set the DIMZIN to required format</font></span><br /><font color="#000000">&#160;&#160;&#160; ThisDrawing.SetVariable(</font><span style="color: "><font color="#a31515">&quot;DIMZIN&quot;</font></span></font><font face="新宋体"><font color="#000000">, 1)<br /> <br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'to test the required format</font></span><br /></font></font><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000">&#160;&#160;&#160; MsgBox(ThisDrawing.Utility.RealToString(48, acArchitectural, 6))<br /> </font><br /><span style="color: "><font color="#0000ff">End</font></span><font color="#000000">&#160;</font></font><span style="color: "><font style="font-size: 7.8pt" color="#0000ff">Sub</font></span></font><br /></pre>
