---
layout: "post"
title: "Plant SDK: For an entity in the Ortho View, how can I find the same piece of equipment in the 3D Model?"
date: "2013-07-09 10:05:15"
author: "Marat Mirgaleev"
categories:
  - ".NET"
  - "Marat Mirgaleev"
  - "Plant3D"
original_url: "https://adndevblog.typepad.com/autocad/2013/07/plant-sdk-for-an-entity-in-the-ortho-view-how-can-i-find-the-same-piece-of-equipment-in-the-3d-model.html "
typepad_basename: "plant-sdk-for-an-entity-in-the-ortho-view-how-can-i-find-the-same-piece-of-equipment-in-the-3d-model"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/marat-mirgaleev.html" target="_self">Marat Mirgaleev</a></p>  <p><strong>Issue</strong></p>  <p><em>I would like to let my users to select an entity in the Ortho view in AutoCAD Plant 3D and find some properties of this selected equipment:</em></p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01901e30ca78970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_931189.jpg" width="455" height="227" /></a></p>  <p><em>But it seems that to do this I need to find the corresponding object in the 3D model first:</em></p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b0192abeffe18970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_453535.jpg" width="410" height="255" /></a></p>  <p><em>How can I do this?</em></p>  <p><strong>Solution</strong></p>  <p>Unfortunately, the current Plant SDK does not provide this functionality. But a good news is that there is an undocumented class that is safe to use for this purpose.</p>  <p>Before we start coding, we need to find some sample drawings which we can use for testing. Let it be the out-of-the-box SampleProject with its Area1_Plan drawing:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01910426ef8c970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_988870.jpg" width="310" height="274" /></a></p>  <p>and the 3D model in 1-PE-001 drawing:</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b0192abeffe42970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_206288.jpg" width="317" height="269" /></a></p>  <p>Screenshots from these files can be found at the top of this post.</p>  <p>Let’s start from selecting an entity in the Ortho view. When you test the code, do not forget to switch from PAPER space to MODEL using the button shown on the first screenshot (or you just can’t select anything).</p>  <p>As soon as we have the selected entity’s ObjectId, we can call the undocumented method </p>  <p>&#160;&#160;&#160;&#160; <span style="line-height: 140%">Autodesk.ProcessPower.Drawings2d.</span><span style="line-height: 140%; color: #2b91af">PnPDwg2dUtil</span><span style="line-height: 140%">.</span><span style="line-height: 140%">GetModelObjectId().</span></p>  <p><span style="line-height: 140%">It is located in an assembly called C:\Program Files\Autodesk\AutoCAD 2014\PLNT3D\PnPDwg2dUtil.dll and, obviously, we need to add a reference to it from our Visual Studio project.</span></p>  <p>This is a code snippet which demonstrates usage of the <span style="line-height: 140%">GetModelObjectId() method. It defines a new command called “FOTM” (From Ortho To Model)</span>:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt"></div>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// From an entity in Ortho, looking for this entity </span><span style="line-height: 140%; color: green">in the Model.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Using the out-of-the-box SampleProject for tests: </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160; Ortho: Area1_Plan</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160; Model: 1-PE-001</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// In Area1_Plan, you need to switch from Paper to Model,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160; otherwise you can't select anything in it.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//===============================================================</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;FOTM&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> FromOrthoToModel()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// To test, select an entity in an Ortho drawing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptEntityResult</span><span style="line-height: 140%"> selectedEntity = doc.Editor.GetEntity(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;\nSelect an entity to annotate:&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (selectedEntity.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// GetModelObjectId() is an undocumented method to find </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//&#160;&#160; the corresponding entity in the Piping Model</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//=============================================================</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Autodesk.ProcessPower.Drawings2d.</span><span style="line-height: 140%; color: #2b91af">MdObjectId</span><span style="line-height: 140%"> orthoId =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.ProcessPower.Drawings2d.</span><span style="line-height: 140%; color: #2b91af">PnPDwg2dUtil</span><span style="line-height: 140%">.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetModelObjectId(selectedEntity.ObjectId,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; selectedEntity.ObjectId.Database);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// In this orthoId we have a drawing GUID and PpObjectId:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Autodesk.ProcessPower.DataLinks.</span><span style="line-height: 140%; color: #2b91af">PpObjectId</span><span style="line-height: 140%"> ppId =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; orthoId.PrjObjectId;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> dwgGUID = orthoId.DwgGUID;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Find the entity's ObjectId in the Model drawing.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Note: To do this you have to have the Model drawing open.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Autodesk.ProcessPower.DataLinks.</span><span style="line-height: 140%; color: #2b91af">DataLinksManager</span><span style="line-height: 140%"> dlm = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PlantApplication</span><span style="line-height: 140%">.CurrentProject.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ProjectParts[</span><span style="line-height: 140%; color: #a31515">&quot;Piping&quot;</span><span style="line-height: 140%">].DataLinksManager;&#160; </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> oid = dlm.MakeAcDbObjectId(ppId);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// THAT'S IT:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; doc.Editor.WriteMessage(</span><span style="line-height: 140%; color: #a31515">&quot;\n oid=&quot;</span><span style="line-height: 140%"> + oid.ToString());</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; } </span><span style="line-height: 140%; color: green">// FromOrthoToModel()</span></p>    <p style="margin: 0px"></p> </div>
