---
layout: "post"
title: "Calculate and create Elliptical Arcs using LISP and ADS ObjectARX"
date: "2013-01-17 14:57:07"
author: "Fenton Webb"
categories:
  - "2010"
  - "2011"
  - "2012"
  - "2013"
  - "AutoCAD"
  - "Fenton Webb"
  - "LISP"
  - "ObjectARX"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/calculate-and-create-elliptical-arcs-using-lisp-and-ads-objectarx.html "
typepad_basename: "calculate-and-create-elliptical-arcs-using-lisp-and-ads-objectarx"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/fenton-webb.html">Fenton Webb</a></p>  <p><b>Issue</b></p>  <p>In the DXF Reference listing for an open ellipse (elliptical arc), group code 41 is described as the &quot;start parameter&quot;.&#160; However, its association with known values for the arc is difficult to determine. How is this value derived?&#160; What is the parametric angle, and how do I calculate it from the true start angle?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>An elliptical arc is a special version of an arc that follows the eccentricity of the ellipse.&#160; One way to generate this type of arc is to find the parametric normal of the starting point.&#160; To do so, you must specify a start angle that is different from the actual start angle of the drawn arc.&#160; Group code 41 contains this parametric angle expressed in radians.</p>  <p>The parametric angle is generated from two concentric circles whose center is the center of the ellipse and whose radii are the major and minor axes, respectively.&#160; Every point of the ellipse lies either between or on these two circles, and each elliptical point can be defined by a unique relation to them.&#160; To discover this relationship, draw a line perpendicular to the major axis from a point on the ellipse to the closest intersection with the circle described by the major axis.&#160; Then do the same with the minor axis, starting   <br />from the elliptical point and drawing perpendicular to the minor axis until the line intersects the circle described by the minor axis.&#160; The two points of intersection with the circles are colinear with the center of the ellipse.&#160; The angle between the line containing these three points and the major axis is the parametric angle specified by group code 41.</p>  <p>To calculate the parametric angle from the true start angle, you must first find the start point on the ellipse.&#160; This requires a simultaneous solution to the equations for the line and the ellipse.&#160; In this example we assume that the major axis of the ellipse lies on the x-axis with the origin at the center of the ellipse.&#160; When this point is found, you can use its y-value and the minor axis to solve the equation for the circle whose radius is the minor axis value and whose center is the center of the ellipse.&#160; This will provide the x,y point on the circle that dictates the parametric angle from the center of the ellipse.</p>  <p>Below is an AutoLisp example that demonstrates how to use trigonometric functions to determine the parametric angle:</p>  <pre><pre><br />(defun c:e_arc( / a b slope ang q1 q2 q3 q4 qmode x y a2) <br />&#160;&#160; ;;assuming 0,0 is at the center of the ellipse, major axis in x direction<br />&#160;&#160; (setq ang (getangle '(0.0 0.0) &quot;Choose start angle: &quot;))<br />&#160;&#160; (setq a 1<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; b 0.5<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; slope (/ (sin ang) (cos ang))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; q1 (/ pi 2.0)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; q2 pi<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; q3 (/ (* 3 pi) 2.0)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; q4 (* 2.0 pi)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; qmode 'q1&#160; <br />&#160;&#160; );setq<br />&#160;&#160; (entmake<br />&#160;&#160;&#160;&#160;&#160; (setq ent '((0 . &quot;ELLIPSE&quot;)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (100 . &quot;AcDbEntity&quot;)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (100 . &quot;AcDbEllipse&quot;)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (10 0.0 0.0 0.0)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (11 1.0 0.0 0.0)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (40 . 0.5)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (62 . 1)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; )<br />&#160;&#160;&#160;&#160;&#160; );setq<br />&#160;&#160; );entmake<br />&#160;&#160; ;;line equation is y = mx + 0, where m is the slope and 0 is the y-intercept<br />&#160;&#160; ;;ellipse equation is x^2/a^2 + y^2/b^2 = 1<br />&#160;&#160; ;;solve line and ellipse equations simultaneously to find x and y values<br />&#160;&#160; (setq y (/ (* a b slope) (sqrt (+ (* (* slope slope) (* a a)) (* b b)))))<br />&#160;&#160; ;;minor axis circle equation is x^2 + y^2 = b^2<br />&#160;&#160; ;;solve circle equation where y = value calculated above<br />&#160;&#160; (setq x (sqrt (- (* b b) (* y y))))<br />&#160;&#160; ;;calculate start angle trigonometrically<br />&#160;&#160; (setq cos_a2 (/ x b)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sin_a2 (/ y b)<br />&#160;&#160; );setq<br />&#160;&#160; (if (/= cos_a2 0)<br />&#160;&#160;&#160;&#160;&#160; (setq a2 (atan (/ sin_a2 cos_a2)))<br />&#160;&#160;&#160;&#160;&#160; (setq a2 q1<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; qmode 'q1<br />&#160;&#160;&#160;&#160;&#160; )<br />&#160;&#160; );if<br />&#160;&#160; ;;make a2 insensitive to quadrant<br />&#160;&#160; (cond<br />&#160;&#160;&#160;&#160;&#160; ((and (&gt; ang q1) (&lt; ang q2))<br />&#160;&#160;&#160;&#160;&#160;&#160; (setq a2 (- pi (abs a2))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; qmode 'q2<br />&#160;&#160;&#160;&#160;&#160;&#160; );setq<br />&#160;&#160;&#160;&#160;&#160; );statement 1<br />&#160;&#160;&#160;&#160;&#160; ((and (&gt; ang q2) (&lt; ang q3))<br />&#160;&#160;&#160;&#160;&#160;&#160; (setq a2 (+ (abs a2) pi)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; qmode 'q3<br />&#160;&#160;&#160;&#160;&#160;&#160; );setq<br />&#160;&#160;&#160;&#160;&#160; );statement 2<br />&#160;&#160;&#160;&#160;&#160; ((and (&gt; ang q3) (&lt; ang q4)) <br />&#160;&#160;&#160;&#160;&#160;&#160; (setq a2 (abs (- (* 2 pi) (abs a2)))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; qmode 'q4<br />&#160;&#160;&#160;&#160;&#160;&#160; );setq<br />&#160;&#160;&#160;&#160;&#160; );statement 3<br />&#160;&#160;&#160;&#160;&#160; ;;special cases: angle = 0, 90, 180, 270 or 360 deg<br />&#160;&#160;&#160;&#160;&#160; ((or (= ang 0) (= ang q1))<br />&#160;&#160;&#160;&#160;&#160;&#160; (setq qmode 'q1)<br />&#160;&#160;&#160;&#160;&#160; );statement 4<br />&#160;&#160;&#160;&#160;&#160; ((= ang q2)<br />&#160;&#160;&#160;&#160;&#160;&#160; (setq a2 pi<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; qmode 'q1<br />&#160;&#160;&#160;&#160;&#160;&#160; )<br />&#160;&#160;&#160;&#160;&#160; );statement 5<br />&#160;&#160;&#160;&#160;&#160; ((= ang q3)<br />&#160;&#160;&#160;&#160;&#160;&#160; (setq a2 (- (/ pi 2.0) pi)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; qmode 'q1<br />&#160;&#160;&#160;&#160;&#160;&#160; )<br />&#160;&#160;&#160;&#160;&#160; );statement 6<br />&#160;&#160;&#160;&#160;&#160; (t nil);default statement<br />&#160;&#160; );cond<br />&#160;&#160; (command &quot;zoom&quot; &quot;c&quot; &quot;0,0&quot; 3)<br />&#160;&#160; (setq ent (append ent (list (cons 41 a2) (cons 42 (+ a2 (/ pi 2.0))))))<br />&#160;&#160; (setq ent (subst '(62 . 5) (assoc 62 ent) ent))<br />&#160;&#160; (entmake ent)<br />&#160;&#160; (setq a2<br />&#160;&#160;&#160;&#160;&#160; (cond<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((= qmode 'q1) a2)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((= qmode 'q2) a2)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((= qmode 'q3) (- a2 q4))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ((= qmode 'q4) (- a2 q4))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (t nil)<br />&#160;&#160;&#160;&#160;&#160; );cond<br />&#160;&#160; );setq<br />&#160;&#160; (princ &quot;\nParametric angle in radians: &quot;)<br />&#160;&#160; (princ a2)<br />&#160;&#160; (princ &quot;\nParametric angle in degrees: &quot;)<br />&#160;&#160; (princ (/ (* 180 a2) pi))<br />&#160;&#160; (princ)<br />);e_arc</pre></pre>
