---
layout: "post"
title: "How to add dimension entities to a block object using VBA?"
date: "2013-01-04 23:16:15"
author: "Daniel Du"
categories:
  - ".NET"
  - "2010"
  - "2011"
  - "2012"
  - "2013"
  - "AutoCAD"
  - "Daniel Du"
original_url: "https://adndevblog.typepad.com/autocad/2013/01/how-to-add-dimension-entities-to-a-block-object-using-vba.html "
typepad_basename: "how-to-add-dimension-entities-to-a-block-object-using-vba"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/daniel-du.html">Daniel Du</a></p>  <p><b>Issue</b></p>  <p>The AddDimAligned method of Block object produces incorrect dimension objects. How can I add dimension entities to a Block object?</p>  <p><a name="section2"></a></p>  <p><b>Solution</b></p>  <p>The AddDimAligned method as well as other AddDimxxx methods of adding dimension entities to a Block object results in dimension objects that are incorrect.</p>  <p>This is a known problem. Use the following workaround to add dimension entities to a block object:</p>  <p>1. Create a Dimension entity in model space.    <br />2. Use the CopyObject method to copy the Dimension entity to a Block object.     <br />3. Delete the original Dimension entity from model space.</p>  <p>The following sample code creates a block &quot;test&quot;, adds a DimRotated entity to the block, and then inserts the block into model space.</p>  <pre style="line-height: normal; font-family: ; background: white; color: "><font face="新宋体"><font style="font-size: 7.8pt"><span style="color: "><font color="#0000ff">Sub</font></span></font></font><font style="font-size: 7.8pt"><font face="新宋体"><font color="#000000"> f_SolAddDiminBlocks()<br />&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'Workaround for Adding dimensions to block AutoCAD</font></span><br /><span style="color: "><font color="#0000ff">     Dim</font></span><font color="#000000"> po_rotDim </font><span style="color: "><font color="#0000ff">As</font></span></font><font face="新宋体"><font color="#000000"> AcadDimAligned<br />&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> po_block </font><span style="color: "><font color="#0000ff">As</font></span></font><font face="新宋体"><font color="#000000"> AcadBlock<br />&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#0000ff">Dim</font></span><font color="#000000"> pd_ext1(0 </font><span style="color: "><font color="#0000ff">To</font></span><font color="#000000"> 2) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Double</font></span><br /><span style="color: "><font color="#0000ff">     Dim</font></span><font color="#000000"> pd_ext2(0 </font><span style="color: "><font color="#0000ff">To</font></span><font color="#000000"> 2) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Double</font></span><br /><span style="color: "><font color="#0000ff">     Dim</font></span><font color="#000000"> pd_lineLoc(0 </font><span style="color: "><font color="#0000ff">To</font></span><font color="#000000"> 2) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Double</font></span><br /><span style="color: "><font color="#0000ff">     Dim</font></span><font color="#000000"> po_array(0) </font><span style="color: "><font color="#0000ff">As</font></span><font color="#000000">&#160;</font><span style="color: "><font color="#0000ff">Object</font></span><br /></font><font face="新宋体"><font color="#000000"> <br />&#160;&#160;&#160;&#160; pd_ext1(0) = 3 : pd_ext1(1) = 3 : pd_ext1(2) = 0<br />&#160;&#160;&#160;&#160; pd_ext2(0) = 10 : pd_ext2(1) = 3 : pd_ext2(2) = 0<br />&#160;&#160;&#160;&#160; pd_lineLoc(0) = 5 : pd_lineLoc(1) = 4 : pd_lineLoc(2) = 0<br />&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'create dimeionsion object</font></span><br /></font><font face="新宋体"><font color="#000000">&#160;&#160;&#160;&#160; po_rotDim = ThisDrawing.ModelSpace.AddDimAligned(pd_ext1, pd_ext2,<br />&#160;&#160;&#160;&#160; pd_lineLoc)<br /> <br />&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'create a new block by name test</font></span><br /><font color="#000000">&#160;&#160;&#160;&#160; po_block = ThisDrawing.Blocks.Add(pd_ext1, </font><span style="color: "><font color="#a31515">&quot;test&quot;</font></span></font><font face="新宋体"><font color="#000000">)<br />&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'insert a block reference</font></span><br /><font color="#000000">&#160;&#160;&#160;&#160; ThisDrawing.ModelSpace.InsertBlock(pd_ext1, </font><span style="color: "><font color="#a31515">&quot;test&quot;</font></span></font><font face="新宋体"><font color="#000000">, 1, 1, 1, 0)<br />&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'copy dimension object</font></span><br /></font></font><font face="新宋体"><font style="font-size: 7.8pt"><font color="#000000">&#160;&#160;&#160;&#160; po_array(0) = po_rotDim<br />&#160;&#160;&#160;&#160; ThisDrawing.CopyObjects(po_array, po_block)<br />&#160;&#160;&#160;&#160; po_rotDim.Delete()<br />&#160;&#160;&#160;&#160; </font><span style="color: "><font color="#008000">'release the references</font></span><br /><font color="#000000">&#160;&#160;&#160;&#160; po_block = </font><span style="color: "><font color="#0000ff">Nothing</font></span><br /><font color="#000000">&#160;&#160;&#160;&#160; po_rotDim = </font><span style="color: "><font color="#0000ff">Nothing</font></span><br /><span style="color: "><font color="#0000ff">End</font></span><font color="#000000">&#160;</font></font><span style="color: "><font style="font-size: 7.8pt" color="#0000ff">Sub</font></span></font></pre>
