---
layout: "post"
title: "Copy a leader using Visual LISP"
date: "2014-03-13 12:03:06"
author: "Wayne Brill"
categories:
  - "AutoCAD"
  - "LISP"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/autocad/2014/03/copy-a-leader-using-visual-lisp.html "
typepad_basename: "copy-a-leader-using-visual-lisp"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p>Recently I had a case where the question was how to create a new leader based on an existing leader using AutoLISP. Here is an example that I came up with. When you run this example you select a leader and the MText annotation for the leader. After you run the function you will need to move the Leader manually to see that there are are two leaders at the same location. </p>  <p>Another way to do this would be to use the Copy method and set the annotation property. This example is just getting the points from the existing leader, the MText, and then creating a new Leader at the same location.&#160;&#160;&#160; </p>  <p>&#160;</p>  <p>(defun C:copyLeaderTest (/ vla_ldr vla_mtx coords numberOfPoints    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arrayForPoints points attachPointFromExistingMText     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; textForMText widthForMText insertioinPointForMText     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; acadObj doc modelSpace newMText     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; drawingDirectionForMText newLeader verticalTextPosition)</p>  <p>&#160; (vl-load-com)    <br />&#160; (setvar &quot;osmode&quot; 0)     <br />&#160; (setvar &quot;orthomode&quot; 0)</p>  <p>&#160; ; Get Leader and MText    <br />&#160; (while (setq ss1 (ssget (list (cons -4 &quot;&lt;OR&quot;)     <br />&#160;&#160;&#160; (cons 0 &quot;LEADER&quot;) (cons 0 &quot;MTEXT&quot;)(cons -4 &quot;OR&gt;&quot;))))</p>  <p>&#160;&#160; ; Ensure selection set has two entities    <br />&#160; (if (/= (sslength ss1) 2)     <br />&#160;&#160;&#160; (alert &quot;Select 1 MText and 1 leader.&quot;)     <br />&#160;&#160;&#160; ; Have a Leader and MText get the ActiveX Object     <br />&#160;&#160;&#160; (progn     <br />&#160;&#160;&#160;&#160;&#160; (if (= (cdr (assoc 0 (entget (ssname ss1 0)))) &quot;LEADER&quot;)     <br />&#160;&#160;&#160; (setq vla_ldr (vlax-ename-&gt;vla-object (ssname ss1 0))     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vla_mtx (vlax-ename-&gt;vla-object (ssname ss1 1))     <br />&#160;&#160;&#160; )     <br />&#160;&#160;&#160; (setq vla_ldr (vlax-ename-&gt;vla-object (ssname ss1 1))     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vla_mtx (vlax-ename-&gt;vla-object (ssname ss1 0))     <br />&#160;&#160;&#160; )     <br />&#160;&#160;&#160;&#160;&#160; )</p>  <p>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160; ; Get the coordinates from the existing leader     <br />&#160;&#160;&#160;&#160;&#160; ; and make an array of doubles     <br />&#160;&#160;&#160;&#160;&#160; (setq coords (vlax-get vla_ldr 'Coordinates))     <br />&#160;&#160;&#160;&#160;&#160; (setq numberOfPoints (1- (length coords)))     <br />&#160;&#160;&#160;&#160;&#160; (setq arrayForPoints (cons 0 numberOfPoints))     <br />&#160;&#160;&#160;&#160;&#160; (setq points (vlax-make-safearray vlax-vbDouble     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arrayForPoints))     <br />&#160;&#160;&#160;&#160;&#160; (vlax-safearray-fill points coords)     <br />&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; ; Store the current attachmentpoint of the existing MText&#160; <br />&#160;&#160;&#160; (setq attachPointFromExistingMText (vla-get-attachmentpoint vla_mtx)) </p>  <p>&#160;&#160;&#160; ; change the attachmentPoint for existing leader to Top Left    <br />&#160;&#160;&#160; ; This is will make the insertion point correct for the new MText     <br />&#160;&#160;&#160; (vla-put-AttachmentPoint vla_mtx acAttachmentPointTopLeft)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; (setq textForMText (vla-get-TextString vla_mtx))     <br />&#160;&#160;&#160; (setq widthForMText (vla-get-width vla_mtx))     <br />&#160;&#160;&#160; (setq insertioinPointForMText (vla-get-insertionpoint vla_mtx))</p>  <p>&#160;&#160;&#160; ; Get modelspace and add the new MText    <br />&#160;&#160;&#160; (setq acadObj (vlax-get-acad-object))     <br />&#160;&#160;&#160; (setq doc (vla-get-ActiveDocument acadObj))     <br />&#160;&#160;&#160; (setq modelSpace (vla-get-ModelSpace doc))&#160; <br />&#160;&#160;&#160; (setq newMText (vla-AddMText modelSpace     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; insertioinPointForMText widthForMText textForMText))</p>  <p>&#160;&#160;&#160; (vla-put-AttachmentPoint newMText attachPointFromExistingMText)</p>  <p>&#160;&#160;&#160; ; make the attachmentPoint what it was    <br />&#160;&#160;&#160; (vla-put-AttachmentPoint vla_mtx attachPointFromExistingMText)</p>  <p>&#160;&#160;&#160; (setq drawingDirectionForMText (vla-get-drawingdirection vla_mtx))    <br />&#160;&#160;&#160; (vla-put-drawingdirection newMText drawingDirectionForMText)     <br />&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; ;; Create the leader object in model space     <br />&#160;&#160;&#160; (setq newLeader (vla-AddLeader modelSpace points newMText acLineWithArrow))</p>  <p>&#160;&#160;&#160; (setq verticalTextPosition(vla-get-VerticalTextPosition vla_ldr))    <br />&#160;&#160;&#160; (vla-put-VerticalTextPosition newLeader verticalTextPosition)     <br />&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160; (vla-put-ArrowheadBlock     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLeader     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; (vla-get-ArrowheadBlock vla_ldr)     <br />&#160;&#160;&#160; )</p>  <p>&#160;&#160;&#160; (vla-put-layer newLeader (vla-get-layer vla_ldr))    <br />&#160;&#160;&#160; (vla-put-layer newMText (vla-get-layer vla_mtx))</p>  <p>&#160;&#160; ; (vla-Erase vla_ldr)    <br />&#160;&#160; ; (vla-Erase vla_mtx)</p>  <p>&#160;&#160;&#160;&#160; )    <br />&#160; )     <br />)</p>  <p>&#160; (princ)    <br />)</p>
