---
layout: "post"
title: "Opening a P&amp;ID Drawing that was edited offline (avoiding the Update dialog)"
date: "2014-02-21 11:48:52"
author: "Wayne Brill"
categories:
  - "Plant3D"
  - "Wayne Brill"
original_url: "https://adndevblog.typepad.com/autocad/2014/02/opening-a-pid-drawing-that-was-edited-offline-avoiding-the-update-dialog.html "
typepad_basename: "opening-a-pid-drawing-that-was-edited-offline-avoiding-the-update-dialog"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/wayne-brill.html" target="_self">Wayne Brill</a></p>  <p>A drawing that was edited offline has to be re-inserted (merged) into the project. Plant drawings contain subset of project database (BLOB as SQL database). Plant also a knows whether the drawing was saved in the current project or not. If drawing was not saved in the current project, the BLOB has to be merged into the project. </p>  <p>There are several API to handle this situation: </p>  <p><em>Project.IsDrawingOutOfSync(string dwgname, Database db)</em> – tells whether AcDbDatabase is in sync with project database </p>  <p><em>Project.UpdatePnPDrawing(Database db, string dwgname, ref PnPSyncConflicts conflicts)</em> – merge blob into project database. </p>  <p><strong>C# example:</strong></p>  <div style="font-family: consolas; background: #eeeeee; color: black; font-size: 10pt">   <p style="margin: 0px">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;testOpen&quot;</span>, <span style="color: #2b91af">CommandFlags</span>.Session)]</p>    <p style="margin: 0px"><span style="color: blue">public</span> <span style="color: blue">void</span> testOpen() </p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">string</span> strDwgPath;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Database</span> db = <span style="color: blue">new</span> <span style="color: #2b91af">Database</span>(<span style="color: blue">false</span>, <span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Project</span> currentProject = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PlantApp</span>.CurrentProject.ProjectParts[<span style="color: #a31515">&quot;PnId&quot;</span>];</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">DataLinksManager</span> dlm = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; currentProject.DataLinksManager;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// get project drawing&#160; </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">PnPProjectDrawing</span> pnp_dwg = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; currentProject.GetDwgFileByName</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;C:\\MyProject\\PID DWG\\PumpAnlage.dwg&quot;</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// use resolved path</span></p>    <p style="margin: 0px">&#160;&#160;&#160; strDwgPath = pnp_dwg.ResolvedFilePath;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; db.ReadDwgFile(strDwgPath, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">FileShare</span>.ReadWrite, <span style="color: blue">false</span>, <span style="color: blue">null</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// tell DLM to manage drawing database. </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//(Documents are automatically enlisted </span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">//when they are opened in editor)</span></p>    <p style="margin: 0px">&#160;&#160;&#160; dlm.EnlistDrawing(db);</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// dispose will unelist it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">if</span> (currentProject.IsDrawingOutOfSync</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (strDwgPath, db))</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PnPSyncConflicts</span> conflicts = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; currentProject.UpdatePnPDrawing</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (db, strDwgPath, <span style="color: blue">ref</span> conflicts);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// tell DLM that drawing related data has to </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// be saved in the project database.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// otherwise, DLM will not save drawing sync </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// timestamp causing out-of-sync </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// situation on drawing open</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">DataLinksManager</span>.DatabaseToForceSaveComplete</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = db;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.SaveAs(strDwgPath, <span style="color: #2b91af">DwgVersion</span>.Current);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">catch</span> (System.<span style="color: #2b91af">Exception</span> ex)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">finally</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">DataLinksManager</span>.DatabaseToForceSaveComplete</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; db.CloseInput(<span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160; db.Dispose();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">DocumentCollection</span> acDocMgr = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Application</span>.DocumentManager;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">Document</span> acDoc = acDocMgr.Open(strDwgPath, <span style="color: blue">false</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #2b91af">AcadDocument</span> anAcadDoc = </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">AcadDocument</span>)acDoc.GetAcadDocument();</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// if(!anAcadDoc.Saved)</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; anAcadDoc.Save();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">}</p> </div>
