---
layout: "post"
title: "From Model Space to Paper Space"
date: "2014-11-12 08:14:31"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "AutoCAD"
original_url: "https://adndevblog.typepad.com/autocad/2014/11/from-model-space-to-paper-space.html "
typepad_basename: "from-model-space-to-paper-space"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>Convert a coordinate from a Paper Space Viewport to the respective Model Space is possible using acedTrans and it’s already described at <a href="http://adndevblog.typepad.com/autocad/2012/03/converting-paper-space-point-to-model-space-using-autocadnet.html">this blog post</a>. Note that a point on a Viewport will point to a single point on model space, meaning this is a 1 to 1 relationship.</p>  <p>The opposite way is not 1 to 1, but in fact 1 to many. A point on the model space can be on several paper space viewport. To make such a conversion, we need to have a viewport, then do some math to convert the coordinate. With that, the basic idea is calculate a scale factor using two points on both paper and model space. Then using those points again calculate how much the need to move.</p>  <p>With that in mind, the code below is the same from <a href="http://adndevblog.typepad.com/autocad/2012/03/converting-paper-space-point-to-model-space-using-autocadnet.html">this post</a> with a few new <strong>pieces in bold</strong>. To test the idea, the code is also adding DBPoints on Paper Space for each entity’s grip point (from model space).</p>  <p>Note this is assuming a 2D drawing on model space, showing as a 2D drawing on paper space, with a simple view (no perspective). To make it work on every possible scenario, we may need to adjust the math…</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb07aa923b970d-pi"><img title="ms_to_ps" style="border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px; display: inline" border="0" alt="ms_to_ps" src="/assets/image_978326.jpg" width="470" height="332" /></a> </p>  <pre style="font-size: 12px; font-family: consolas; background: white; color: black">[<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;testAcadMS2PS&quot;</span>)]<br /><span style="color: blue">public</span>&#160;<span style="color: blue">void</span> CmdTestAcadMS2PS()<br />{<br />&#160; <span style="color: #2b91af">Editor</span> ed = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Editor;<br />&#160; <span style="color: green">// pick a PS Viewport</span><br />&#160; <span style="color: #2b91af">PromptEntityOptions</span> opts = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">PromptEntityOptions</span>(<span style="color: #a31515">&quot;Pick PS Viewport&quot;</span>);<br />&#160; opts.SetRejectMessage(<span style="color: #a31515">&quot;Must select PS Viewport objects only&quot;</span>);<br />&#160; opts.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">Viewport</span>), <span style="color: blue">false</span>);<br />&#160; <span style="color: #2b91af">PromptEntityResult</span> res = ed.GetEntity(opts);<br />&#160; <span style="color: blue">if</span> (res.Status == <span style="color: #2b91af">PromptStatus</span>.OK)<br />&#160; {<br />&#160;&#160;&#160; <span style="color: blue">int</span> vpNumber = 0;<br />&#160;&#160;&#160; <span style="color: green">// extract the viewport points</span><br />&#160;&#160;&#160; <span style="color: #2b91af">Point3dCollection</span> psVpPnts = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Point3dCollection</span>();<br />&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Viewport</span> psVp =<br />&#160;&#160;&#160;&#160;&#160; res.ObjectId.Open(<span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Viewport</span>)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// get the vp number</span><br />&#160;&#160;&#160;&#160;&#160; vpNumber = psVp.Number;<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// now extract the viewport geometry</span><br />&#160;&#160;&#160;&#160;&#160; psVp.GetGripPoints(psVpPnts, <span style="color: blue">new</span>&#160;<span style="color: #2b91af">IntegerCollection</span>(),<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">IntegerCollection</span>());<br />&#160;&#160;&#160; }<br /> <br />&#160;&#160;&#160; <span style="color: green">// let's assume a rectangular vport for now,</span><br />&#160;&#160;&#160; <span style="color: green">// make the cross-direction grips square</span><br />&#160;&#160;&#160; Point3d tmp = psVpPnts[2];<br />&#160;&#160;&#160; psVpPnts[2] = psVpPnts[1];<br />&#160;&#160;&#160; psVpPnts[1] = tmp;<br /> <br />&#160;&#160;&#160; <span style="color: green">// Transform the PS points to MS points</span><br />&#160;&#160;&#160; <span style="color: #2b91af">ResultBuffer</span> rbFrom = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">ResultBuffer</span>(<span style="color: blue">new</span> TypedValue(5003, 3));<br />&#160;&#160;&#160; <span style="color: #2b91af">ResultBuffer</span> rbTo = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">ResultBuffer</span>(<span style="color: blue">new</span> TypedValue(5003, 2));<br />&#160;&#160;&#160; <span style="color: blue">double</span>[] retPointDouble = <span style="color: blue">new</span>&#160;<span style="color: blue">double</span>[] { 0, 0, 0 };<br />&#160;&#160;&#160; <span style="color: green">// loop the ps points </span><br />&#160;&#160;&#160; <span style="color: #2b91af">Point3dCollection</span> msVpPnts = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Point3dCollection</span>();<br />&#160;&#160;&#160; <span style="color: blue">foreach</span> (Point3d pnt <span style="color: blue">in</span> psVpPnts)<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// translate from from the DCS of Paper Space (PSDCS) RTSHORT=3 and </span><br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// the DCS of the current model space viewport RTSHORT=2</span><br />&#160;&#160;&#160;&#160;&#160; acedTrans(pnt.ToArray(), rbFrom.UnmanagedObject,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; rbTo.UnmanagedObject, 0, retPointDouble);<br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// add the resulting point to the ms pnt array</span><br />&#160;&#160;&#160;&#160;&#160; Point3d retPoint = <span style="color: blue">new</span> Point3d(retPointDouble);<br />&#160;&#160;&#160;&#160;&#160; msVpPnts.Add(retPoint);<br />&#160;&#160;&#160; }<br /> <br /><strong>&#160;&#160;&#160; <span style="color: green">// *******</span><br />&#160;&#160;&#160; <span style="color: green">// now we assume both list of points (on MS and PS) have</span><br />&#160;&#160;&#160; <span style="color: green">// at least 2 points, which is correct as a Viewport needs</span><br />&#160;&#160;&#160; <span style="color: green">// 3 points for create a closed area</span><br />&#160;&#160;&#160; <span style="color: green">// </span><br />&#160;&#160;&#160; <span style="color: green">// find the scale fator based on points from PS and MS</span><br />&#160;&#160;&#160; <span style="color: blue">double</span> transformScale =<br />&#160;&#160;&#160;&#160;&#160; psVpPnts[1].DistanceTo(psVpPnts[0]) /<br />&#160;&#160;&#160;&#160;&#160; msVpPnts[1].DistanceTo(msVpPnts[0]);<br />&#160;&#160;&#160; <span style="color: green">// and find the transformation vector (displacement)</span><br />&#160;&#160;&#160; Vector3d transformVector = msVpPnts[0].TransformBy(<br />&#160;&#160;&#160;&#160;&#160; Matrix3d.Scaling(transformScale, Point3d.Origin))<br />&#160;&#160;&#160;&#160;&#160; .GetVectorTo(psVpPnts[0]);<br />&#160;&#160;&#160; <span style="color: green">// *******</span></strong><br /> <br />&#160;&#160;&#160; <span style="color: green">// now switch to MS</span><br />&#160;&#160;&#160; ed.SwitchToModelSpace();<br />&#160;&#160;&#160; <span style="color: green">// set the CVPort</span><br />&#160;&#160;&#160; <span style="color: #2b91af">Application</span>.SetSystemVariable(<span style="color: #a31515">&quot;CVPORT&quot;</span>, vpNumber);<br />&#160;&#160;&#160; <span style="color: green">// once switched, we can use the normal selection mode to select</span><br />&#160;&#160;&#160; <span style="color: #2b91af">PromptSelectionResult</span> selectionresult =<br />&#160;&#160;&#160;&#160;&#160; ed.SelectCrossingPolygon(msVpPnts);<br />&#160;&#160;&#160; <span style="color: green">// now switch back to PS</span><br />&#160;&#160;&#160; ed.SwitchToPaperSpace();<br /> <br /><strong>&#160;&#160;&#160; <span style="color: green">// *******</span><br />&#160;&#160;&#160; <span style="color: #2b91af">Database</span> db = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument.Database;<br />&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> trans = db.TransactionManager.StartTransaction())<br />&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> paperSpace = trans.GetObject(db.CurrentSpaceId,<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForWrite) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">BlockTableRecord</span>;<br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">SelectedObject</span> obj <span style="color: blue">in</span> selectionresult.Value)<br />&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Entity</span> ent = trans.GetObject(obj.ObjectId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Entity</span>;<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Point3dCollection</span> grips = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Point3dCollection</span>();<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ent.GetGripPoints(grips, <span style="color: blue">new</span>&#160;<span style="color: #2b91af">IntegerCollection</span>(), <span style="color: blue">new</span>&#160;<span style="color: #2b91af">IntegerCollection</span>());<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (Point3d pt <span style="color: blue">in</span> grips)<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; {<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// for each grip point on MS, add a DBPoint</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// apply first the scaling fator</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// then the displacement vector</span><br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">DBPoint</span> point = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">DBPoint</span>(pt<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .TransformBy(Matrix3d.Scaling(transformScale, Point3d.Origin))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .TransformBy(Matrix3d.Displacement(transformVector))<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; paperSpace.AppendEntity(point);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.AddNewlyCreatedDBObject(point, <span style="color: blue">true</span>);<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160; }<br />&#160;&#160;&#160;&#160;&#160; trans.Commit();<br />&#160;&#160;&#160; }<br />&#160;&#160;&#160; <span style="color: green">// *******</span></strong><br />&#160; }<br />}<br /> <br />[<span style="color: #2b91af">DllImport</span>(<span style="color: #a31515">&quot;accore.dll&quot;</span>,<br />&#160; CallingConvention = <span style="color: #2b91af">CallingConvention</span>.Cdecl, EntryPoint = <span style="color: #a31515">&quot;acedTrans&quot;</span>)]<br /><span style="color: blue">private</span>&#160;<span style="color: blue">static</span>&#160;<span style="color: blue">extern</span>&#160;<span style="color: blue">int</span> acedTrans(<span style="color: blue">double</span>[] point, IntPtr fromRb,<br />&#160; IntPtr toRb, <span style="color: blue">int</span> disp, <span style="color: blue">double</span>[] result);</pre>
