---
layout: "post"
title: "Audit API - New in AutoCAD 2015"
date: "2014-03-26 01:44:04"
author: "Virupaksha Aithal"
categories:
  - ".NET"
  - "2015"
  - "AutoCAD"
  - "Virupaksha Aithal"
original_url: "https://adndevblog.typepad.com/autocad/2014/03/audit-api-new-in-autocad-2015.html "
typepad_basename: "audit-api-new-in-autocad-2015"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/autocad/Virupaksha-Aithal.html" target="_self">Virupaksha Aithal</a></p>
<p>From AutoCAD 2015, you can programmatically audit the drawing file using the new Database API “Audit” . You can also try fixing the issues in the drawing file using API’s argument. This API is present in ObjectARX and .NET.</p>
<p>In ObjectARX – use Acad::ErrorStatus acedAudit(AcDbDatabase* , bool , bool ) API.</p>
<div style="border: #000080 0px solid; color: #000; font-family: &#39;Courier New&#39;, Courier, Monospace; font-size: 8pt;">
<div style="background-color: #ffffff; overflow: auto; padding: 2px 5px; white-space: nowrap;"><span style="background: #ffffff; color: #000000;">[</span><span style="background: #ffffff; color: #2b91af;">CommandMethod</span><span style="background: #ffffff; color: #000000;">(</span><span style="background: #ffffff; color: #a31515;">&quot;AuditTest&quot;</span><span style="background: #ffffff; color: #000000;">)]</span><br /> <span style="background: #ffffff; color: #0000ff;">public</span><span style="background: #ffffff; color: #0000ff;">void</span><span style="background: #ffffff; color: #000000;"> AuditTest() </span><span style="background: #ffffff; color: #008000;">// This method can have any name</span><br /> <span style="background: #ffffff; color: #000000;">{</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #2b91af;">Document</span><span style="background: #ffffff; color: #000000;"> doc = </span><span style="background: #ffffff; color: #2b91af;">Application</span><span style="background: #ffffff; color: #000000;">.DocumentManager.MdiActiveDocument;</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #2b91af;">Editor</span><span style="background: #ffffff; color: #000000;"> ed = doc.Editor;</span><br /> <br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #0000ff;">try</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;{</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #008000;">//to fix the error or not</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #0000ff;">bool</span><span style="background: #ffffff; color: #000000;"> bFixErrors = </span><span style="background: #ffffff; color: #0000ff;">true</span><span style="background: #ffffff; color: #000000;">;</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #008000;">//to show the message in commandline or not</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #0000ff;">bool</span><span style="background: #ffffff; color: #000000;"> becho = </span><span style="background: #ffffff; color: #0000ff;">true</span><span style="background: #ffffff; color: #000000;">;</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #008000;">//call audit API</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;doc.Database.Audit(bFixErrors, becho);</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;}</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;</span><span style="background: #ffffff; color: #0000ff;">catch</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;{</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;ed.WriteMessage(</span><span style="background: #ffffff; color: #a31515;">&quot;Unable to audit the drawing\n&quot;</span><span style="background: #ffffff; color: #000000;">);</span><br /> <span style="background: #ffffff; color: #000000;">&#0160;&#0160;&#0160;&#0160;}</span><br /> <br /> <span style="background: #ffffff; color: #000000;">}</span></div>
</div>
