---
layout: "post"
title: "Traversing a 3D solid's brep using AutoCAD 2009's new .NET API"
date: "2008-09-01 11:18:08"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Solid modeling"
original_url: "https://www.keanw.com/2008/09/traversing-a-3d.html "
typepad_basename: "traversing-a-3d"
typepad_status: "Publish"
---

<p>In a recent <a href="http://through-the-interface.typepad.com/through_the_interface/2008/08/autodesk-api-te.html">webcast</a>, Gopinath Taget, from our DevTech Americas team, showed how to use the Brep API from a .NET application: something that was made possible in AutoCAD 2009. The Brep API in AutoCAD allows you to traverse the <a href="http://en.wikipedia.org/wiki/Boundary_representation">boundary representation</a> of a Solid3d object. Without going into specifics - as this isn&#39;t really an area of AutoCAD I&#39;ve had much reason to use, over the years - I went ahead and took the sample Gopi showed in his webcast and modified it for the purposes of this blog.</p>

<p>The following C# code traverses the Brep of a selected Solid3d, dumping the information to the command-line. It uses the technique shown in <a href="http://through-the-interface.typepad.com/through_the_interface/2007/05/getting_the_typ.html">this previous post</a> to retrieve the type of solid we&#39;re dealing with via COM.</p><p><div style="font-family: Courier New; font-size: 8pt; color: black; background: white;"><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> Autodesk.AutoCAD.ApplicationServices;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> Autodesk.AutoCAD.DatabaseServices;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> Autodesk.AutoCAD.EditorInput;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> Autodesk.AutoCAD.Runtime;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> Autodesk.AutoCAD.BoundaryRepresentation;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> Autodesk.AutoCAD.Interop.Common;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">BrFace</span><span style="line-height: 140%;"> =</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; Autodesk.AutoCAD.BoundaryRepresentation.</span><span style="color: #2b91af; line-height: 140%;">Face</span><span style="line-height: 140%;">;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="color: blue; line-height: 140%;">namespace</span><span style="line-height: 140%;"> BRepTraversal</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">{</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">public</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">class</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Commands</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; [</span><span style="color: #2b91af; line-height: 140%;">CommandMethod</span><span style="line-height: 140%;">(</span><span style="color: #a31515; line-height: 140%;">&quot;TBR&quot;</span><span style="line-height: 140%;">)]</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">static</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">public</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">void</span><span style="line-height: 140%;"> TraverseBRep()</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Document</span><span style="line-height: 140%;"> doc =</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Application</span><span style="line-height: 140%;">.DocumentManager.MdiActiveDocument;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Database</span><span style="line-height: 140%;"> db = doc.Database;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Editor</span><span style="line-height: 140%;"> ed = doc.Editor;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Transaction</span><span style="line-height: 140%;"> tr =</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; db.TransactionManager.StartTransaction();</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> (tr)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">try</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Prompt for selection of a solid to be traversed</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">PromptEntityOptions</span><span style="line-height: 140%;"> prEntOpt =</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">new</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">PromptEntityOptions</span><span style="line-height: 140%;">(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\nSelect a 3D solid:&quot;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; prEntOpt.SetRejectMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\nMust be a 3D solid.&quot;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; prEntOpt.AddAllowedClass(</span><span style="color: blue; line-height: 140%;">typeof</span><span style="line-height: 140%;">(</span><span style="color: #2b91af; line-height: 140%;">Solid3d</span><span style="line-height: 140%;">), </span><span style="color: blue; line-height: 140%;">true</span><span style="line-height: 140%;">);</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">PromptEntityResult</span><span style="line-height: 140%;"> prEntRes =</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ed.GetEntity(prEntOpt);</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">ObjectId</span><span style="line-height: 140%;">[] objIds = { prEntRes.ObjectId };</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Solid3d</span><span style="line-height: 140%;"> sol =</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; (</span><span style="color: #2b91af; line-height: 140%;">Solid3d</span><span style="line-height: 140%;">)tr.GetObject(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; prEntRes.ObjectId,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">OpenMode</span><span style="line-height: 140%;">.ForRead</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Use COM to get the solid&#39;s type</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Acad3DSolid</span><span style="line-height: 140%;"> oSol = (</span><span style="color: #2b91af; line-height: 140%;">Acad3DSolid</span><span style="line-height: 140%;">)sol.AcadObject;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\nSolid type: {0}&quot;</span><span style="line-height: 140%;">,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; oSol.SolidType</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; oSol = </span><span style="color: blue; line-height: 140%;">null</span><span style="line-height: 140%;">;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Build the BRep topology object to traverse</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">Brep</span><span style="line-height: 140%;"> brp = </span><span style="color: blue; line-height: 140%;">new</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Brep</span><span style="line-height: 140%;">(sol);</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">using</span><span style="line-height: 140%;"> (brp)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">int</span><span style="line-height: 140%;"> cmpCnt = 0;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Get all the Complexes which are primary BRep</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// elements and represent a conceptual topological</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// entity of connected shell boundaries.</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">foreach</span><span style="line-height: 140%;"> (</span><span style="color: #2b91af; line-height: 140%;">Complex</span><span style="line-height: 140%;"> cmp </span><span style="color: blue; line-height: 140%;">in</span><span style="line-height: 140%;"> brp.Complexes)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; Complex number {0}&quot;</span><span style="line-height: 140%;">,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ++cmpCnt</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Get all the shells within a complex. Shells</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// are secondary BRep entities that correspond</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// to a collection of neighboring surfaces on a</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// solid</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">int</span><span style="line-height: 140%;"> shlCnt = 0;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">foreach</span><span style="line-height: 140%;"> (</span><span style="color: #2b91af; line-height: 140%;">Shell</span><span style="line-height: 140%;"> shl </span><span style="color: blue; line-height: 140%;">in</span><span style="line-height: 140%;"> cmp.Shells)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; &#0160; Shell number {0} [{1}]&quot;</span><span style="line-height: 140%;">,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ++shlCnt,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; shl.ShellType</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Get all the faces in a shell. Faces are</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// primary BRep topological entities that</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// directly correspond to face subentities on</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// AutoCAD entities like solid, region and body</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">int</span><span style="line-height: 140%;"> fceCnt = 0;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">foreach</span><span style="line-height: 140%;"> (</span><span style="color: #2b91af; line-height: 140%;">BrFace</span><span style="line-height: 140%;"> fce </span><span style="color: blue; line-height: 140%;">in</span><span style="line-height: 140%;"> shl.Faces)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; &#0160; &#0160; Face number {0}&quot;</span><span style="line-height: 140%;">,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ++fceCnt</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Get all the boundary loops within a face</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// (Secondary BRep entities and no corresponding</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// AutoCAD entities/subentities)</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">try</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">int</span><span style="line-height: 140%;"> lpCnt = 0;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">foreach</span><span style="line-height: 140%;"> (</span><span style="color: #2b91af; line-height: 140%;">BoundaryLoop</span><span style="line-height: 140%;"> lp </span><span style="color: blue; line-height: 140%;">in</span><span style="line-height: 140%;"> fce.Loops)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; &#0160; &#0160; &#0160; Loop number {0} [{1}]&quot;</span><span style="line-height: 140%;">,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ++lpCnt,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; lp.LoopType</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Get all the Edges in a loop (Edges are</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// primary BRep entities and correspond to</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">// Geometric entities). Output the </span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">int</span><span style="line-height: 140%;"> edgCnt = 0;</span></p><p style="margin: 0px; font-size: 8pt;">&#0160;</p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">foreach</span><span style="line-height: 140%;"> (</span><span style="color: #2b91af; line-height: 140%;">Edge</span><span style="line-height: 140%;"> edg </span><span style="color: blue; line-height: 140%;">in</span><span style="line-height: 140%;"> lp.Edges)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; &#0160; &#0160; &#0160; &#0160; Edge number {0}: &quot;</span><span style="line-height: 140%;"> +</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; &#0160; &#0160; &#0160; &#0160; Vertex 1: {1}&quot;</span><span style="line-height: 140%;"> +</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; &#0160; &#0160; &#0160; &#0160; Vertex 2: {2}&quot;</span><span style="line-height: 140%;">,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ++edgCnt,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; edg.Vertex1.Point,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; edg.Vertex2.Point</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">catch</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\n&#0160; &#0160; &#0160; &#0160; Problem getting loops/edges:&quot;</span><span style="line-height: 140%;"> +</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot; object is probably unbounded &quot;</span><span style="line-height: 140%;"> +</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;(e.g. a sphere or a torus).&quot;</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; tr.Commit();</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">catch</span><span style="line-height: 140%;"> (System.</span><span style="color: #2b91af; line-height: 140%;">Exception</span><span style="line-height: 140%;"> ex)</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; {</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; ed.WriteMessage(</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;\nException during traversal: {0}&quot;</span><span style="line-height: 140%;">,</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; &#0160; ex.Message</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; &#0160; );</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; &#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">&#0160; }</span></p><p style="margin: 0px; font-size: 8pt;"><span style="line-height: 140%;">}</span></p></div></p><p>Here&#39;s what happens when we run the TBR command against a cylinder:</p>

<div style="FONT-SIZE: 8pt; BACKGROUND: white; COLOR: black; FONT-FAMILY: courier new"><p style="FONT-SIZE: 8pt; MARGIN: 0px">Command:&#0160; <span style="color: #ff0000;">TBR</span></p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">Select a 3D solid:</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">Solid type: Cylinder</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; Complex number 1</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160; Shell number 1 [ShellExterior]</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;Face number 1</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; Loop number 1 [LoopWinding]</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Edge number 1:</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 1: (15.0005647466013,4.38174252440491,0)</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 2: (15.0005647466013,4.38174252440491,0)</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; Loop number 2 [LoopWinding]</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Edge number 1:</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 1: (15.0005647466013,4.38174252440491,5.78051528967497)</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 2: (15.0005647466013,4.38174252440491,5.78051528967497)</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;Face number 2</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; Loop number 1 [LoopExterior]</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Edge number 1:</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 1: (15.0005647466013,4.38174252440491,0)</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 2: (15.0005647466013,4.38174252440491,0)</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;Face number 3</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; Loop number 1 [LoopExterior]</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Edge number 1:</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 1: (15.0005647466013,4.38174252440491,5.78051528967497)</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; &#0160; Vertex 2: (15.0005647466013,4.38174252440491,5.78051528967497)</p></div><p>One point to note: in the above code I&#39;ve used a try-catch block around the code to get the loops of a face and the edges of a loop. This is because the GetEnumerator() call on either a loop or an edge (which gets called implicitly by the foreach statement to loop through their respective enumerable objects) can throw an exception in the case where an object is unbounded. Here&#39;s an excerpt from the .NET reference material (currently residing in the ObjectARX Reference, which is part of the ObjectARX SDK):</p><blockquote><p><span style="DISPLAY: none"><a name="WSfacf1429558a55de8821c21057fbebc2b-53f9"></a></span><em>A topological object may be unbounded (that is, it may have no lower dimensional bounding topology) only in the following cases:</em></p><p><span style="DISPLAY: none"><a name="WS1a9193826455f5ff128052610e798412bc-4666"></a></span></p>

<ul>
<li><em>A closed surface, which is intrinsically bounded in both the <span class="code">u</span> and <span class="code">v</span> directions (such as a full torus or sphere), is represented by a face that has no loop boundaries. </em></li>
<li><em>A closed curve, which is intrinsically bounded (such as a full circle or ellipse), is represented by an edge that has coincident start and end vertices.</em></li>
</ul>
</blockquote><p>For example, here&#39;s what happens when we run the TBR command against a torus:</p>

<div style="FONT-SIZE: 8pt; BACKGROUND: white; COLOR: black; FONT-FAMILY: courier new"><p style="FONT-SIZE: 8pt; MARGIN: 0px">Command:&#0160; <span style="color: #ff0000;">TBR</span></p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">Select a 3D solid:</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">Solid type: Torus</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; Complex number 1</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160; Shell number 1 [ShellExterior]</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;Face number 1</p>

<p style="FONT-SIZE: 8pt; MARGIN: 0px">&#0160; &#0160;&#0160; &#0160;&#0160; Problem getting loops/edges: object is probably unbounded (e.g. a sphere or a torus).</p></div><p>So we have, at least, detected the case, even if we have to deal with the overhead of catching an exception rather than checking a property for the number of Loops (something I couldn&#39;t work out how to do).</p>
