---
layout: "post"
title: "Pointing at clouds: more random musings on AutoCAD and F#"
date: "2008-02-25 12:45:38"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "F#"
  - "Point clouds"
original_url: "https://www.keanw.com/2008/02/more-random-mus.html "
typepad_basename: "more-random-mus"
typepad_status: "Publish"
---

<p>On my way back from the US last week, I started thinking more about uses for random numbers inside AutoCAD: especially ones that allow me to try out some possible application areas for F#.</p>
<p>There&#39;s something deliciously perverse about using random numbers in Engineering systems, where it&#39;s really important for outcomes to be <a href="http://en.wikipedia.org/wiki/Deterministic_algorithm">deterministic</a> (i.e. predictable) &amp; precise. And that perversity appeals to me quite strongly, for some reason. Feel free to drop me a mail if you have an idea why that might be, any amateur psychologists out there... ;-)</p>
<p>So, I got to thinking... an interesting domain area for our development partners is that of <a href="http://en.wikipedia.org/wiki/Laser_scanning">laser scanning</a>. These systems often generate huge (and I mean <strong><em>huge</em></strong>) data-sets: millions upon millions of points are generated by laser scanners (often known as <a href="http://en.wikipedia.org/wiki/Point_cloud">point clouds</a>), and these need to be managed in some way by software - often by solutions that are integrated with Autodesk products.</p>
<p>So I thought, wouldn&#39;t it be fun to go through an AutoCAD model and generated huge arrays of points representing the shell of solid objects in the model - essentially generating random point clouds - to see how F# deals with such humungous data-sets.</p>
<p>The general approach I decided to use was to go through all of the entities in the model-space, open them up and - for those that are of type Solid3d - generate 100,000 points (say) that are found on the shell of the object. To find points on the shell, I adopted the following technique:</p>
<ol>
<li>Create a random 3D vector</li>
<li>Generate a random plane intersecting the solid (by using the centroid of the solid as the origin and the generated vector as the normal)</li>
<li>Create a region representing the section of the solid and the plane</li>
<li>Create another random vector, this time on the plane</li>
<li>Use this vector to fire a ray</li>
<li>Get the intersection of the ray and the region</li>
<li>Repeat until we have enough points</li>
</ol>
<p>To display each point we just draw a zero-length vector, which I decided to make red.</p>
<p>In my initial implementation, I used a classic functional programming technique, that of <a href="http://en.wikipedia.org/wiki/Tail_recursion">tail recursion</a>. As a bit of a purist, I try to use functional (as opposed to imperative) techniques whenever I can when writing F# code. The problem is that tail recursion can significantly drain your stack space, as it results in a new function call - and a new level in the call stack - for every item in your list (and after all we&#39;re talking about huge numbers of points). Some compilers/evaluation systems can optimise out the recursive function call, reducing it to a simple branch, but F# doesn&#39;t currently appear to do so with my code (it is supposed to, so there may be something about the way my recursive functions are structured that prevents them from being identified as tail-recursive).</p>
<p>Here are a couple of examples of tail-recursive functions - one to generate a list of points, the other to draw them:</p>
<div style="FONT-FAMILY: Courier New; BACKGROUND: white; COLOR: black; FONT-SIZE: 8pt">
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// A function that accepts an ObjectId and returns</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// a list of random points on its surface</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> <span style="COLOR: blue">rec</span> getNPoints n (sol:Solid3d) =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">if</span> n &lt;= 0 <span style="COLOR: blue">then</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;[]</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">else</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> mp = sol.MassProperties</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> pl = <span style="COLOR: blue">new</span> Plane()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;pl.Set(mp.Centroid,randomVector3d sol.ObjectId.OldId)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> reg = sol.GetSection(pl)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> ray = <span style="COLOR: blue">new</span> Ray()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ray.BasePoint &lt;- mp.Centroid</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ray.UnitDir &lt;- randomVectorOnPlane pl</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> pts = <span style="COLOR: blue">new</span> Point3dCollection()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;reg.IntersectWith</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; (ray,</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; Intersect.OnBothOperands,</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; pts,</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; 0, 0)</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;pl.Dispose()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;reg.Dispose()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ray.Dispose()</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> ptlist = Seq.untyped_to_list pts</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ptlist @ getNPoints (n - pts.Count) sol</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"> </p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// A recursive function to show the contents of a list</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> <span style="COLOR: blue">rec</span> drawPointList (x:Point3d list) =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">match</span> x <span style="COLOR: blue">with</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; | h :: t <span style="COLOR: blue">-&gt;</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ed.DrawVector(h,h,1,<span style="COLOR: blue">true</span>)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;drawPointList t</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; | [] <span style="COLOR: blue">-&gt;</span> ()</p></div>
<p>While more elegant from a functional perspective, this elegance results in sub-optimal execution. The way to &quot;fix&quot; this is to introduce iterative code - whether a for, foreach or while loop - to avoid the recursion. </p>
<p>Here&#39;s the complete F# code that makes use of iterative techniques rather than recursion:</p>
<div style="FONT-FAMILY: Courier New; BACKGROUND: white; COLOR: black; FONT-SIZE: 8pt">
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// Use lightweight F# syntax</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">#light</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// Declare a specific namespace and module name</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">module</span> MyNamespace.MyApplication</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// Import managed assemblies</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">#I <span style="COLOR: maroon">@&quot;C:\Program Files\Autodesk\AutoCAD 2008&quot;</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">#r <span style="COLOR: maroon">&quot;acdbmgd.dll&quot;</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">#r <span style="COLOR: maroon">&quot;acmgd.dll&quot;</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">open</span> System</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">open</span> Autodesk.AutoCAD.Runtime</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">open</span> Autodesk.AutoCAD.ApplicationServices</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">open</span> Autodesk.AutoCAD.DatabaseServices</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">open</span> Autodesk.AutoCAD.Geometry</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// Get a random vector on a plane</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">let</span> randomVectorOnPlane pl =</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Create our random number generator</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> ran = <span style="COLOR: blue">new</span> System.Random()</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// First we get the absolute value</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// of our x, y and z coordinates</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> absx = ran.NextDouble()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> absy = ran.NextDouble()</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Then we negate them, half of the time</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> x = <span style="COLOR: blue">if</span> (ran.NextDouble() &lt; 0.5) <span style="COLOR: blue">then</span> -absx <span style="COLOR: blue">else</span> absx</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> y = <span style="COLOR: blue">if</span> (ran.NextDouble() &lt; 0.5) <span style="COLOR: blue">then</span> -absy <span style="COLOR: blue">else</span> absy</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> v2 = <span style="COLOR: blue">new</span> Vector2d(x,y)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">new</span> Vector3d(pl,v2)</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// Get a random vector in 3D space</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// Note: _ is only used to make sure this function gets</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// executed when it is called... if we have no argument</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// it&#39;s a value that doesn&#39;t require repeated execution</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">let</span> randomVector3d _ =</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Create our random number generator</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> ran = <span style="COLOR: blue">new</span> System.Random()</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// First we get the absolute value</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// of our x, y and z coordinates</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> absx = ran.NextDouble()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> absy = ran.NextDouble()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> absz = ran.NextDouble()</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Then we negate them, half of the time</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> x = <span style="COLOR: blue">if</span> (ran.NextDouble() &lt; 0.5) <span style="COLOR: blue">then</span> -absx <span style="COLOR: blue">else</span> absx</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> y = <span style="COLOR: blue">if</span> (ran.NextDouble() &lt; 0.5) <span style="COLOR: blue">then</span> -absy <span style="COLOR: blue">else</span> absy</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> z = <span style="COLOR: blue">if</span> (ran.NextDouble() &lt; 0.5) <span style="COLOR: blue">then</span> -absz <span style="COLOR: blue">else</span> absz</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">new</span> Vector3d(x, y, z)</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: green">// Now we declare our command</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">[&lt;CommandMethod(<span style="COLOR: maroon">&quot;pts&quot;</span>)&gt;]</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt"><span style="COLOR: blue">let</span> createPoints () =</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Let&#39;s get the usual helpful AutoCAD objects</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> doc =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; Application.DocumentManager.MdiActiveDocument</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> ed = doc.Editor</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> db = doc.Database</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// &quot;use&quot; has the same effect as &quot;using&quot; in C#</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">use</span> tr =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; db.TransactionManager.StartTransaction();</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Get appropriately-typed BlockTable and BTRs</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> bt =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; tr.GetObject</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;(db.BlockTableId,OpenMode.ForRead)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; :?&gt; BlockTable</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> ms =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; tr.GetObject</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;(bt.[BlockTableRecord.ModelSpace],</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;OpenMode.ForRead)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; :?&gt; BlockTableRecord</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// A function that accepts an ObjectId and returns</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// a list of random points on its surface</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> getNPoints n (sol:Solid3d) =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">let</span> ptcol = <span style="COLOR: blue">new</span> Point3dCollection()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">while</span> ptcol.Count &lt; n <span style="COLOR: blue">do</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> mp = sol.MassProperties</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> pl = <span style="COLOR: blue">new</span> Plane()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;pl.Set</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; (mp.Centroid, randomVector3d n)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> reg = sol.GetSection(pl)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> ray = <span style="COLOR: blue">new</span> Ray()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ray.BasePoint &lt;- mp.Centroid</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ray.UnitDir &lt;- randomVectorOnPlane pl</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> pts = <span style="COLOR: blue">new</span> Point3dCollection()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;reg.IntersectWith</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; (ray,</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; Intersect.OnBothOperands,</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; pts,</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; 0, 0)</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;pl.Dispose()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;reg.Dispose()</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ray.Dispose()</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">for</span> pt <span style="COLOR: blue">in</span> pts <span style="COLOR: blue">do</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; ptcol.Add pt |&gt; ignore</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; Seq.untyped_to_list ptcol</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> generatePoints numPoints (x : ObjectId) =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">let</span> obj = tr.GetObject(x,OpenMode.ForRead)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">match</span> obj <span style="COLOR: blue">with</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; | :? Solid3d <span style="COLOR: blue">-&gt;</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;<span style="COLOR: blue">let</span> sol = (obj :?&gt; Solid3d)</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;getNPoints numPoints sol</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; | _ <span style="COLOR: blue">-&gt;</span> []</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// An iterative function to draw a point list</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> drawPointList (x:Point3d list) =</p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; <span style="COLOR: blue">for</span> pt <span style="COLOR: blue">in</span> x <span style="COLOR: blue">do</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;ed.DrawVector(pt,pt,1,<span style="COLOR: blue">true</span>)</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Let&#39;s generate 10K points per solid</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: blue">let</span> points = generatePoints 100000</p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// Here&#39;s where we plug everything together...</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; Seq.untyped_to_list ms |&gt; <span style="COLOR: green">// ObjectIds from modelspace</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160; List.map points |&gt;&#0160; &#0160;&#0160; &#0160;<span style="COLOR: green">// Get points for each object</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;List.concat |&gt;&#0160; &#0160;&#0160; &#0160;&#0160; <span style="COLOR: green">// No need for the outer list</span></p>
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; &#0160;&#0160; &#0160;&#0160; drawPointList&#0160; &#0160;&#0160; &#0160; <span style="COLOR: green">// Draw the resultant points</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; <span style="COLOR: green">// As usual, committing is cheaper than aborting</span></p><br />
<p style="MARGIN: 0px; FONT-SIZE: 8pt">&#0160; tr.Commit()</p></div>
<p>Here are the results of the PTS command called on a set of 6 Solid3d objects, essentially generating and drawing 600,000 points. The code doesn&#39;t currently result in any persistent graphics at all - if you change views the points all disappear. At some point I&#39;d like to extend this to store the generated points persistently, but for now the point of the exercise (no pun intended :-) is more to see how F# performs with large data-sets, rather than how we deal with the issue of persistence.</p>
<p><a href="http://through-the-interface.typepad.com/.shared/image.html?/photos/uncategorized/2008/02/25/f_point_clouds.png" onclick="window.open(this.href, &#39;_blank&#39;, &#39;width=800,height=624,scrollbars=no,resizable=no,toolbar=no,directories=no,location=no,menubar=no,status=no,left=0,top=0&#39;); return false"></a><a href="http://through-the-interface.typepad.com/.shared/image.html?/photos/uncategorized/2008/02/25/f_point_clouds_2.png" onclick="window.open(this.href, &#39;_blank&#39;, &#39;width=800,height=598,scrollbars=no,resizable=no,toolbar=no,directories=no,location=no,menubar=no,status=no,left=0,top=0&#39;); return false"><img alt="F_point_clouds_2" border="0" height="224" src="/assets/f_point_clouds_2.png" title="F_point_clouds_2" width="300" /></a> </p>
<p>A final note: I now realise the use of tail recursion was almost certainly the wall I hit with the F# implementation in <a href="http://through-the-interface.typepad.com/through_the_interface/2008/02/robotic-hatch-1.html">this previous post</a>.</p>
