---
layout: "post"
title: "Overruling AutoCAD 2010&rsquo;s entity display and explode using IronPython"
date: "2009-04-23 13:26:26"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Graphics system"
  - "IronPython"
  - "Overrules"
  - "Python"
  - "Solid modeling"
original_url: "https://www.keanw.com/2009/04/overruling-autocad-2010s-entity-display-and-explode-using-ironpython.html "
typepad_basename: "overruling-autocad-2010s-entity-display-and-explode-using-ironpython"
typepad_status: "Publish"
---

<p>To continue <a href="http://through-the-interface.typepad.com/through_the_interface/ironpython/">my investigations into IronPython</a> and <a href="http://through-the-interface.typepad.com/through_the_interface/overrules/">the fun I’m having with overrules</a>, I decided to to port <a href="http://through-the-interface.typepad.com/through_the_interface/2009/04/overruling-explode-in-autocad-2010-using-net.html">my most recent C# overrule implementation</a> across to IronPython. I’ve also been trying to do the same for IronRuby, but – so far – without luck.</p>  <p>Please refer back to one of the previous IronPython posts for the PYLOAD command implementation needed to load our Python script into AutoCAD.</p>  <p>Here are the contents of our .py file:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> clr</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">path = </span><span style="line-height: 140%; color: maroon">'C:\\Program Files\\Autodesk\\AutoCAD 2010\\'</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">clr.AddReferenceToFileAndPath(path + </span><span style="line-height: 140%; color: maroon">'acdbmgd.dll'</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">clr.AddReferenceToFileAndPath(path + </span><span style="line-height: 140%; color: maroon">'acmgd.dll'</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime as ar</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices as aas</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices as ads</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput as aei</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.GraphicsInterface as agi</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry as ag</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.Colors as ac</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Autodesk.AutoCAD.Internal as ai</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">from</span><span style="line-height: 140%"> Autodesk.AutoCAD.Internal </span><span style="line-height: 140%; color: blue">import</span><span style="line-height: 140%"> Utils</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> autocad_command(function):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; Function to register AutoCAD commands</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; To be used via a function decorator</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># First query the function name</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; n = function.__name__</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># Create the callback and add the command</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; cc = ai.CommandCallback(function)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; Utils.AddCommand(</span><span style="line-height: 140%; color: maroon">'pycmds'</span><span style="line-height: 140%">, n, n, ar.CommandFlags.Modal, cc)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># Let's now write a message to the command-line</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; doc = aas.Application.DocumentManager.MdiActiveDocument</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; ed = doc.Editor</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; ed.WriteMessage(</span><span style="line-height: 140%; color: maroon">&quot;\nRegistered Python command: {0}&quot;</span><span style="line-height: 140%">, n)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">appName = </span><span style="line-height: 140%; color: maroon">&quot;TTIF_PIPE&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">appCode = 1001</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">radCode = 1040</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> PipeRadiusForObject(obj):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; Get the XData for a particular object</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; and return the &quot;pipe radius&quot; if it exists</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; res = 0.0</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">try</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; rb = obj.XData</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> rb </span><span style="line-height: 140%; color: blue">is</span><span style="line-height: 140%"> None:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> res</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; foundStart = False</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> tv </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> rb:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> tv.TypeCode == appCode </span><span style="line-height: 140%; color: blue">and</span><span style="line-height: 140%"> tv.Value == appName:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; foundStart = True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">else</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> foundStart:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> tv.TypeCode == radCode:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; res = tv.Value</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">break</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; rb.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">except</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> 0.0</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> res</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> SetPipeRadiusOnObject(tr, obj, radius):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; Set the pipe radius as XData on a particular object</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; db = obj.Database</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># Make sure the application is registered</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># (we could separate this out to be called</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># only once for a set of operations)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; rat = tr.GetObject(db.RegAppTableId, ads.OpenMode.ForRead)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">not</span><span style="line-height: 140%"> rat.Has(appName):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; rat.UpgradeOpen()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ratr = ads.RegAppTableRecord()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ratr.Name = appName</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; rat.Add(ratr)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(ratr, True)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># Create the XData and set it on the object</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; rb = ads.ResultBuffer(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.TypedValue(appCode, appName),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.TypedValue(radCode, radius)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; obj.XData = rb</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; rb.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> PipeDrawOverrule(agi.DrawableOverrule):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; The base class for our draw overrules specifying the</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; registered application name for the XData upon which</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; to filter</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> __init__(self):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Tell AutoCAD to filter on our application name</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># (this means our overrule will only be called</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># on objects possessing XData with this name)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; self.SetXDataFilter(appName)&#160; </span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> LinePipeDrawOverrule(PipeDrawOverrule):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; An overrule to make a pipe out of a line</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> __init__(self):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; self._sweepOpts = ads.SweepOptions()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> WorldDraw(self, d, wd):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; radius = PipeRadiusForObject(d)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> radius &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Draw the line as is, with overruled attributes</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; PipeDrawOverrule.WorldDraw(self, d, wd)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">not</span><span style="line-height: 140%"> d.Id.IsNull </span><span style="line-height: 140%; color: blue">and</span><span style="line-height: 140%"> d.Length &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Draw a pipe around the line</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; c = wd.SubEntityTraits.TrueColor</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.SubEntityTraits.TrueColor = ac.EntityColor(0x00AFAFFF)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.SubEntityTraits.LineWeight = ads.LineWeight.LineWeight000</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; start = d.StartPoint</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; end = d.EndPoint</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; norm = ag.Vector3d(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end.X - start.X,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end.Y - start.Y,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end.Z - start.Z</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr = ads.Circle(start, norm, radius)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe = ads.ExtrudedSurface()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.CreateExtrudedSurface(clr, norm, self._sweepOpts)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">except</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc = aas.Application.DocumentManager.MdiActiveDocument</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Editor.WriteMessage(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: maroon">&quot;\nFailed with CreateExtrudedSurface.&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.WorldDraw(wd)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.SubEntityTraits.TrueColor = c</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> PipeDrawOverrule.WorldDraw(self, d, wd)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> SetAttributes(self, d, t):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; b = PipeDrawOverrule.SetAttributes(self, d, t)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; radius = PipeRadiusForObject(d)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> radius &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Set color to magenta</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; t.Color = 6</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># and lineweight to .40 mm</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; t.LineWeight = ads.LineWeight.LineWeight040</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> b</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> CirclePipeDrawOverrule(PipeDrawOverrule):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; An overrule to make a pipe out of a circle</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> __init__(self):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; self._sweepOpts = ads.SweepOptions()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> WorldDraw(self, d, wd):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; radius = PipeRadiusForObject(d)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> radius &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Draw the circle as is, with overruled attributes</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; PipeDrawOverrule.WorldDraw(self, d, wd)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Needed to avoid ill-formed swept surface</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> d.Radius &gt; radius:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Draw a pipe around the circle</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; c = wd.SubEntityTraits.TrueColor</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.SubEntityTraits.TrueColor = ac.EntityColor(0x3FFFE0E0)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.SubEntityTraits.LineWeight = ads.LineWeight.LineWeight000</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; start = d.StartPoint</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen = d.Center</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; norm = ag.Vector3d(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.X - start.X,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.Y - start.Y,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.Z - start.Z</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr = ads.Circle(start, norm.CrossProduct(d.Normal), radius)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe = ads.SweptSurface()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.CreateSweptSurface(clr, d, self._sweepOpts)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.WorldDraw(wd)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.SubEntityTraits.TrueColor = c</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> PipeDrawOverrule.WorldDraw(self, d, wd)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> SetAttributes(self, d, t):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; b = PipeDrawOverrule.SetAttributes(self, d, t)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; radius = PipeRadiusForObject(d)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> radius &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Set color to yellow</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; t.Color = 2</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># and lineweight to .60 mm</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; t.LineWeight = ads.LineWeight.LineWeight060</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> b</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> LinePipeTransformOverrule(ads.TransformOverrule):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; An overrule to explode a linear pipe into Solid3d objects</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> __init__(self):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; self._sweepOpts = ads.SweepOptions()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> Explode(self, e, objs):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; radius = PipeRadiusForObject(e)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> radius &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">not</span><span style="line-height: 140%"> e.Id.IsNull </span><span style="line-height: 140%; color: blue">and</span><span style="line-height: 140%"> e.Length &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Draw a pipe around the line</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; start = e.StartPoint</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; end = e.EndPoint</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; norm = ag.Vector3d(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end.X - start.X,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end.Y - start.Y,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end.Z - start.Z</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr = ads.Circle(start, norm, radius)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe = ads.ExtrudedSurface()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.CreateExtrudedSurface(clr, norm, self._sweepOpts)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">except</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc = aas.Application.DocumentManager.MdiActiveDocument</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Editor.WriteMessage(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: maroon">&quot;\nFailed with CreateExtrudedSurface.&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; objs.Add(pipe)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; PipeDrawOverrule.Explode(self, e, objs)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> CirclePipeTransformOverrule(ads.TransformOverrule):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: maroon">&quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; An overrule to explode a circular pipe into Solid3d objects</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: maroon">&#160; &quot;&quot;&quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> __init__(self):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; self._sweepOpts = ads.SweepOptions()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> Explode(self, e, objs):</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; radius = PipeRadiusForObject(e)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> radius &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> e.Radius &gt; radius:</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; start = e.StartPoint</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen = e.Center</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; norm = ag.Vector3d(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.X - start.X,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.Y - start.Y,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.Z - start.Z</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr = ads.Circle(start, norm.CrossProduct(e.Normal), radius)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe = ads.SweptSurface()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pipe.CreateSweptSurface(clr, e, self._sweepOpts)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clr.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; objs.Add(pipe)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; PipeDrawOverrule.Explode(self, e, objs)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> Overrule(enable):</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># Regen to see the effect</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: green"># (turn on/off Overruling and LWDISPLAY)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; ar.Overrule.Overruling = enable</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> enable:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; aas.Application.SetSystemVariable(</span><span style="line-height: 140%; color: maroon">&quot;LWDISPLAY&quot;</span><span style="line-height: 140%">, 1)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">else</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; aas.Application.SetSystemVariable(</span><span style="line-height: 140%; color: maroon">&quot;LWDISPLAY&quot;</span><span style="line-height: 140%">, 0)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; doc = aas.Application.DocumentManager.MdiActiveDocument</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; doc.SendStringToExecute(</span><span style="line-height: 140%; color: maroon">&quot;REGEN3\n&quot;</span><span style="line-height: 140%">, True, False, False)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; doc.Editor.Regen()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: green"># Set some global variables</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">radius = 0.0</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">overruling = False</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">lpdo = LinePipeDrawOverrule()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">cpdo = CirclePipeDrawOverrule()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">lpto = LinePipeTransformOverrule()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">cpto = CirclePipeTransformOverrule()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> Commands:</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; @autocad_command</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> Overrule1():</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Only add the overrule if not currently attached</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">global</span><span style="line-height: 140%"> overruling</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">not</span><span style="line-height: 140%"> overruling:</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Create a temporary line to get its class</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># (this may not be the best way)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ln = ads.Line()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.AddOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(ln.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lpdo,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.AddOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(ln.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lpto,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ln.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Create a temporary circle to get its class</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># (this may not be the best way)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; c = ads.Circle()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.AddOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(c.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cpdo,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.AddOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(c.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cpto,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; c.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; overruling = True</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Overrule(True)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; @autocad_command</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> Overrule0():</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Only remove the overrule if previously added</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">global</span><span style="line-height: 140%"> overruling</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> overruling:</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Create a temporary line to get its class</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># (this may not be the best way)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ln = ads.Line()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.RemoveOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(ln.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lpdo</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.RemoveOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(ln.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lpto</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ln.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Create a temporary circle to get its class</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># (this may not be the best way)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; c = ads.Circle()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.RemoveOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(c.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cpdo</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ads.ObjectOverrule.RemoveOverrule(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ar.RXClass.GetClass(c.GetType()),</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cpto</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; c.Dispose()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; overruling = False</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Overrule(False)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; @autocad_command</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">def</span><span style="line-height: 140%"> MakePipe():</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; doc = aas.Application.DocumentManager.MdiActiveDocument</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; db = doc.Database</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ed = doc.Editor</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Pick up the radius from the global scope</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">global</span><span style="line-height: 140%"> radius</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Ask the user to select the entities to make into pipes</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; pso = aei.PromptSelectionOptions()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; pso.AllowDuplicates = False</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; pso.MessageForAdding = </span><span style="line-height: 140%; color: maroon">&quot;\nSelect objects to turn into pipes: &quot;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; selRes = ed.GetSelection(pso)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># If the user didn't make valid selection, we return</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> selRes.Status &lt;&gt; aei.PromptStatus.OK:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ss = selRes.Value</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Ask the user for the pipe radius to set</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; pdo = aei.PromptDoubleOptions(</span><span style="line-height: 140%; color: maroon">&quot;\nSpecify pipe radius:&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Use the previous value, if if already called</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> radius &gt; 0.0:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; pdo.DefaultValue = radius</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; pdo.UseDefaultValue = True</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; pdo.AllowNegative = False</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; pdo.AllowZero = False</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; pdr = ed.GetDouble(pdo)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Return if something went wrong</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> pdr.Status &lt;&gt; aei.PromptStatus.OK:</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Set the &quot;last radius&quot; value for when</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># the command is called next</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; radius = pdr.Value</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Use a transaction to edit our various objects</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; tr = db.TransactionManager.StartTransaction()</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># Loop through the selected objects</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> o </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ss:</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># We could choose only to add XData to the objects</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green"># we know will use it (Lines and Circles, for now)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; obj = tr.GetObject(o.ObjectId, ads.OpenMode.ForWrite)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; SetPipeRadiusOnObject(tr, obj, radius)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; tr.Commit()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; tr.Dispose()</span></p> </div> <!--EndFragment-->  <p>Once you have built your loader application and used PYLOAD to load your .py script, you should be able to use MAKEPIPE and OVERRULE1 to create pipes:</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201156f2ac23a970c-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="Overruled lines and circles" border="0" alt="Overruled lines and circles" src="/assets/image_912344.jpg" width="483" height="249" /></a></p>  <p>And EXPLODE to reduce them to Solid3d objects:</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201156f2ac25f970c-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="Exploded overruled lines and circles" border="0" alt="Exploded overruled lines and circles" src="/assets/image_74223.jpg" width="484" height="250" /></a></p>  <p>The logic in the code is basically same as that used in C#, although I have added some checks to make sure nothing bad happens if you call OVERRULE1 or OVERRULE0 repeatedly (previously I did not check for this, which could lead to an exception).</p>
