---
layout: "post"
title: "Creating an editable AutoCAD solid using .NET"
date: "2009-02-20 10:05:53"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Solid modeling"
original_url: "https://www.keanw.com/2009/02/creating-an-editable-autocad-solid-using-net.html "
typepad_basename: "creating-an-editable-autocad-solid-using-net"
typepad_status: "Publish"
---

<p>This question <a href="http://discussion.autodesk.com/forums/thread.jspa?threadID=715715&amp;tstart=0">came up recently on the AutoCAD .NET Discussion Group</a>: how to create a Solid3d object which provides the user with the full set of grips to manipulate it (which I've abbreviated to "editable" in the title of this post :-). This comes down to a enhancements that were made in AutoCAD 2007 to allow better manipulation of solids via the user-interface via extended grips and a push-pull mechanism. These capabilities need to be enabled solids as you create them - and unfortunately cannot be retro-fitted to existing solid objects - by telling the solid that you would like it to record its history. And it's really that simple, you simply have to set the RecordHistory flag to true.</p> <p>The below C# code demonstrates how this works, by exposing a command that prompts the user whether to set this flag to true, or not:</p> <div style="font-size: 8pt; background: white; color: black; font-family: courier new"> <p style="font-size: 8pt; margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p> <p style="font-size: 8pt; margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p> <p style="font-size: 8pt; margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p> <p style="font-size: 8pt; margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p> <p style="font-size: 8pt; margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="color: blue; line-height: 140%">namespace</span><span style="line-height: 140%"> SolidCreation</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">{</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">class</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Commands</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp; {</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp; [</span><span style="color: #2b91af; line-height: 140%">CommandMethod</span><span style="line-height: 140%">(</span><span style="color: #a31515; line-height: 140%">"CWH"</span><span style="line-height: 140%">)]</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">void</span><span style="line-height: 140%"> CylinderWithHistory()</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp; {</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Document</span><span style="line-height: 140%"> doc =</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Database</span><span style="line-height: 140%"> db = doc.Database;</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: green; line-height: 140%">// Ask the user whether to create history</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: green; line-height: 140%">// and where to place the cylinder</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">bool</span><span style="line-height: 140%"> createHistory = </span><span style="color: blue; line-height: 140%">false</span><span style="line-height: 140%">;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">PromptKeywordOptions</span><span style="line-height: 140%"> pko =</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">PromptKeywordOptions</span><span style="line-height: 140%">(</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #a31515; line-height: 140%">"\nRecord history for this cylinder?"</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; );</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; pko.AllowNone = </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">;</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; pko.Keywords.Add(</span><span style="color: #a31515; line-height: 140%">"Yes"</span><span style="line-height: 140%">);</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; pko.Keywords.Add(</span><span style="color: #a31515; line-height: 140%">"No"</span><span style="line-height: 140%">);</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; pko.Keywords.Default = </span><span style="color: #a31515; line-height: 140%">"Yes"</span><span style="line-height: 140%">;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">PromptResult</span><span style="line-height: 140%"> pkr =</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ed.GetKeywords(pko);</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (pkr.Status != </span><span style="color: #2b91af; line-height: 140%">PromptStatus</span><span style="line-height: 140%">.OK)</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%">;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (pkr.StringResult == </span><span style="color: #a31515; line-height: 140%">"Yes"</span><span style="line-height: 140%">)</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; createHistory = </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">PromptPointResult</span><span style="line-height: 140%"> ppr =</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ed.GetPoint(</span><span style="color: #a31515; line-height: 140%">"\nSelect point: "</span><span style="line-height: 140%">);</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (ppr.Status != </span><span style="color: #2b91af; line-height: 140%">PromptStatus</span><span style="line-height: 140%">.OK)</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%">;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%"> pt = ppr.Value;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Transaction</span><span style="line-height: 140%"> tr =</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; db.TransactionManager.StartTransaction();</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> (tr)</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: green; line-height: 140%">// Create the solid and set the history flag</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Solid3d</span><span style="line-height: 140%"> sol = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Solid3d</span><span style="line-height: 140%">();</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sol.RecordHistory = createHistory;</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: green; line-height: 140%">// Hardcode the dimensions of the cylinder</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: green; line-height: 140%">// for the purpose of this example</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sol.CreateFrustum(10, 3, 3, 3);</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: green; line-height: 140%">// Add the Solid3d to the modelspace</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">BlockTable</span><span style="line-height: 140%"> bt =</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (</span><span style="color: #2b91af; line-height: 140%">BlockTable</span><span style="line-height: 140%">)tr.GetObject(</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; db.BlockTableId,</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">OpenMode</span><span style="line-height: 140%">.ForRead</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; );</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">BlockTableRecord</span><span style="line-height: 140%"> ms =</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (</span><span style="color: #2b91af; line-height: 140%">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; bt[</span><span style="color: #2b91af; line-height: 140%">BlockTableRecord</span><span style="line-height: 140%">.ModelSpace],</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; );</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ms.AppendEntity(sol);</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tr.AddNewlyCreatedDBObject(sol, </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">);</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: green; line-height: 140%">// And transform it to the selected point</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sol.TransformBy(</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="color: #2b91af; line-height: 140%">Matrix3d</span><span style="line-height: 140%">.Displacement(pt - </span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%">.Origin)</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; );</span></p> <p style="font-size: 8pt; margin: 0px">&nbsp;</p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tr.Commit();</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp;&nbsp;&nbsp; }</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">&nbsp; }</span></p> <p style="font-size: 8pt; margin: 0px"><span style="line-height: 140%">}</span></p></div><!--EndFragment--> <p>Let's see the results of the CWH command - in this case we run it twice, selecting "No" to the question about history creation for the cylinder on the left and "Yes" to the same question for the cylinder on the right:</p> <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e20111688934bd970c-pi"><img style="border-top-width: 0px; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="374" alt="Cyrilnders with (right) and without (left) history recording enabled" src="/assets/image_944338.jpg" width="473" border="0"></a> </p> <p>As pointed out in the thread on the discussion group, there are some limitations to the API around the history recording for solids: you cannot, for instance, programmatically manipulate the solid's history: it's only possible to create new solids that will then allow users to make use of editing operations that effect the history.</p> <p>On a somewhat related note, back in <a href="http://through-the-interface.typepad.com/through_the_interface/2008/05/sweeping-an-aut.html">this post</a> I mentioned a hole in the .NET API around creating a swept solid. I've been informed by a friend in our Engineering team that we've now plugged it - and some other related holes - in the .NET API for AutoCAD 2010. You will now have the following methods available from the Solid3d class: CreateExtrudedSolid, CreateLoftedSolid, CreateRevolvedSolid and CreateSweptSolid (the equivalent .NET methods for Surfaces existed already, as well as the base C++ methods in ObjectARX). Thanks for the heads-up, Joel! :-)</p>
