---
layout: "post"
title: "Providing information on AutoCAD objects in a tooltip using .NET"
date: "2009-07-27 16:50:19"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Notification / Events"
  - "Selection"
  - "User interface"
original_url: "https://www.keanw.com/2009/07/providing-information-on-autocad-objects-in-a-tooltip-using-net.html "
typepad_basename: "providing-information-on-autocad-objects-in-a-tooltip-using-net"
typepad_status: "Publish"
---

<p>One of the responses to <a href="http://through-the-interface.typepad.com/through_the_interface/2009/07/coming-soon-to-autodesk-labs-plugin-of-the-month.html">my last post</a> on the “Plugin of the Month” asked about showing information on an AutoCAD drawing object via a tooltip. Other than using the standard rollover tooltip properties mechanism, as shown in <a href="http://through-the-interface.typepad.com/through_the_interface/2008/11/adding-custom-p.html">this previous post</a>, the best way to achieve this is via a PointMonitor.</p>  <p>In the below C# code we check which object ore objects are being hovered over, get information about those objects and add them to the tooltip.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PointMonitorTooltips</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;SM&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> StartMonitor()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument.Editor;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ed.PointMonitor +=</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventHandler</span><span style="line-height: 140%">(ed_PointMonitor);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;XM&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> StopMonitor()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument.Editor;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ed.PointMonitor -=</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventHandler</span><span style="line-height: 140%">(ed_PointMonitor);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> ed_PointMonitor(</span><span style="line-height: 140%; color: blue">object</span><span style="line-height: 140%"> sender, </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventArgs</span><span style="line-height: 140%"> e)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = (</span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%">)sender;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = ed.Document;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (!e.Context.PointComputed)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Determine the size of the selection aperture</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">short</span><span style="line-height: 140%"> pickbox =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: blue">short</span><span style="line-height: 140%">)</span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.GetSystemVariable(</span><span style="line-height: 140%; color: #a31515">&quot;PICKBOX&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point2d</span><span style="line-height: 140%"> extents =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.Context.DrawContext.Viewport.GetNumPixelsInUnitSquare(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.Context.ComputedPoint</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> boxWidth = pickbox / extents.X;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%"> vec =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%">(boxWidth / 2, boxWidth / 2, 0.0);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Do a crossing selection using a centred box the</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// size of the aperture</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptSelectionResult</span><span style="line-height: 140%"> pse =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.SelectCrossingWindow(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.Context.ComputedPoint - vec,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.Context.ComputedPoint + vec</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (pse.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK ||</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pse.Value.Count &lt;= 0)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Go through the results of the selection</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// and detect the curves</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> curveInfo = </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Open each object, one by one</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%">[] ids = pse.Value.GetObjectIds();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> id </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ids)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBObject</span><span style="line-height: 140%"> obj =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.GetObject(id, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (obj != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If it's a curve, get its length</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%"> cv = obj </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (cv != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> length =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cv.GetDistanceAtParameter(cv.EndParam);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Then add a message including the object</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// type and its length</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; curveInfo +=</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; obj.GetType().Name + </span><span style="line-height: 140%; color: #a31515">&quot;'s length: &quot;</span><span style="line-height: 140%"> +</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%">.Format(</span><span style="line-height: 140%; color: #a31515">&quot;{0:F}&quot;</span><span style="line-height: 140%">, length) + </span><span style="line-height: 140%; color: #a31515">&quot;\n&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Cheaper than aborting</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add the tooltip of the lengths of the curves detected</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (curveInfo != </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.AppendToolTipText(curveInfo);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">catch</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Not sure what we might get here, but not real action</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// needed (worth adding an Exception parameter and a</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// breakpoint, in case things need investigating).</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">}</span></p> </div> <!--EndFragment-->  <p>During the command we perform a selection, using Editor.SelectCrossingWindow() specifying a window based on the selected point, using a window that’s about the size of the selection aperture (at least that’s what I’m trying to do: let me know if you’ve got a better solution for this). Having some amount of “fuzz” in the selection allows us to not have to hover very precisely over the object, which may or may not be what you’re looking for.</p>  <p>We then iterate through the objects, gathering information about the objects we care about. In this case we’re looking for curves: when we find one, we add its length (along with its object type) to the string we eventually add to the tooltip via AppendToolTipText().</p>  <p>There are two commands: SM adds the monitor, and XM removes it. Bear in mind that the event fires for all sorts of input events - including keystrokes – so you can actually cause problems unless you’re careful. As an example, I wasn’t previously checking the PointComputed status of the PointManager’s context, which is false if we’re looking at keyboard input. The code would go ahead and try to select geometry, which – for some reason unknown to me – cause the character in the keystroke buffer to be lost. Which meant that entering any command would only result in the last command being executed (via the return being processed – that one got through, OK :-). All this to point out that care should be taken when relying on events that are so integrated so deeply into AutoCAD’s user input mechanism.</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e20115723bf2b2970b-pi"><img style="border-right-width: 0px; margin: 0px 20px 0px 30px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="PointMonitor tooltip over a single line" border="0" alt="PointMonitor tooltip over a single line" align="right" src="/assets/image_237925.jpg" width="181" height="125" /></a> So let’s see what we get after NETLOADing the module, running the SM command and hovering over a curve, in this case a line. We see a tooltip appear containing the line’s length.</p>  <p>And if we do the same with a lot more intersecting objects, we see that we also get the <a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e20115723bf2ba970b-pi"><img style="border-right-width: 0px; margin: 10px 30px 0px 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="PointMonitor tooltip over lots of different curves" border="0" alt="PointMonitor tooltip over lots of different curves" align="left" src="/assets/image_566507.jpg" width="240" height="197" /></a>opportunity to provide information on those. It’s ultimately our choice how we manage the selection process and what we do with the results (although please don’t assume you can attempt everything from this kind of very frequently fired event: there are a number of areas where you may find things failing, especially if there’s any interactive component).</p>  <p>&#160;</p>  <p><strong><em>Update:</em></strong></p>  <p>Thanks to Tony Tanzillo for keeping me honest (see his comments, below). The below code addresses a few issues with the version shown above, and should be used instead.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PointMonitorTooltips</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;SM&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> StartMonitor()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument.Editor;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ed.PointMonitor +=</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventHandler</span><span style="line-height: 140%">(ed_PointMonitor);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;XM&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> StopMonitor()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument.Editor;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ed.TurnForcedPickOn();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; ed.PointMonitor -=</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventHandler</span><span style="line-height: 140%">(ed_PointMonitor);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> ed_PointMonitor(</span><span style="line-height: 140%; color: blue">object</span><span style="line-height: 140%"> sender, </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventArgs</span><span style="line-height: 140%"> e)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = (</span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%">)sender;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = ed.Document;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%">[] paths =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.Context.GetPickedEntities();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Go through the results of the selection</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// and detect the curves</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> curveInfo = </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Open each object, one by one</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%"> path </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> paths)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%">[] ids = path.GetObjectIds();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (ids.Length &gt; 0)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> id = ids[ids.GetUpperBound(0)];</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBObject</span><span style="line-height: 140%"> obj =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.GetObject(id, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (obj != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If it's a curve, get its length</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%"> cv = obj </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (cv != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> length =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cv.GetDistanceAtParameter(cv.EndParam) -</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cv.GetDistanceAtParameter(cv.StartParam);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Then add a message including the object</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// type and its length</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; curveInfo +=</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; obj.GetType().Name + </span><span style="line-height: 140%; color: #a31515">&quot;'s length: &quot;</span><span style="line-height: 140%"> +</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%">.Format(</span><span style="line-height: 140%; color: #a31515">&quot;{0:F}&quot;</span><span style="line-height: 140%">, length) + </span><span style="line-height: 140%; color: #a31515">&quot;\n&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Cheaper than aborting</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add the tooltip of the lengths of the curves detected</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (curveInfo != </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.AppendToolTipText(curveInfo);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">catch</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Not sure what we might get here, but not real action</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// needed (worth adding an Exception parameter and a</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// breakpoint, in case things need investigating).</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">}</span></p> </div> <!--EndFragment-->
