---
layout: "post"
title: "Free-form modeling in AutoCAD 2010 using .NET"
date: "2009-03-25 23:43:35"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Solid modeling"
original_url: "https://www.keanw.com/2009/03/free-form-modeling-in-autocad-2010-using-net.html "
typepad_basename: "free-form-modeling-in-autocad-2010-using-net"
typepad_status: "Publish"
---

<p><em>A big thanks to Stephen Preston, who manages DevTech Americas and coordinates our worldwide AutoCAD workgroup as well as spending time working with the AutoCAD Engineering team (phew!), for providing this sample. Stephen originally put it together for our annual Developer Days tour late last year: I took the original sample, converted it from VB.NET to C# and made some minor changes to the code. The VB.NET version is available from the ADN website, in case.</em></p>  <p>The Free-Form Design feature in AutoCAD 2010 is one of the coolest enhancements to the product (I really like the Parametric Drawing feature, too, although as the API for that is currently C++-only it’s unfortunately going to get a little less air-time on this blog). This post looks at how to automate free-form design operations: starting with a traditional Solid3d object, converting it to a sub-division mesh (SubDMesh) which we then manipulate in a number of interesting ways before converting back to a Solid3d.</p>  <p>Here’s the C# code:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Colors;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Collections.Generic;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%; color: blue">namespace</span><span style="line-height: 140%"> FreeformModeling</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Commands</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add a new mesh to the current space,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// setting it to a sphere primitive -</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// no smoothing.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;SPHM&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> SphericalMesh()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db = doc.Database;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.CurrentSpaceId,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%"> mySubD = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; mySubD.SetSphere(20, 8, 8, 0);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; mySubD.SetDatabaseDefaults();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(mySubD);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(mySubD, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Make clone of solid, inflate it by a fraction of its</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// extents, create a mesh from the clone, erase the clone.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> cloneAndInflateSolid(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> solidId</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Now copy the solid</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db = doc.Database;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> newId;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Inflate solid by user specified fraction</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// (0.05 works well with sample drawing)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptDoubleOptions</span><span style="line-height: 140%"> pdo =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptDoubleOptions</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;\nSpecify inflation as fraction of bounds:&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptDoubleResult</span><span style="line-height: 140%"> pdr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.GetDouble(pdo);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Return if something went wrong.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (pdr.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%">.Null;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> frac = pdr.Value;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%"> ids = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ids.Add(solidId);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">IdMapping</span><span style="line-height: 140%"> im = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">IdMapping</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; db.DeepCloneObjects(ids, db.CurrentSpaceId, im, </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; newId = im.Lookup(solidId).Value;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// We now have the ObjectID of the newly cloned</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// solid in newId</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Inflate by length of diagonal vector across bounds</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// multiplied by inflation fraction</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Solid3d</span><span style="line-height: 140%"> sol =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">Solid3d</span><span style="line-height: 140%">)tr.GetObject(newId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Extents3d</span><span style="line-height: 140%"> ext = (</span><span style="line-height: 140%; color: #2b91af">Extents3d</span><span style="line-height: 140%">)sol.Bounds;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%"> vec = ext.MaxPoint - ext.MinPoint;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; sol.OffsetBody(vec.Length * frac);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Define params governing mesh generation algorithm</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// (See ObjectARX helpfiles for explanation of params)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">MeshFaceterData</span><span style="line-height: 140%"> fd =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">MeshFaceterData</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 0.01 * vec.Length,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 40 * </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.PI / 180,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 2, 2, 15, 5, 5, 0</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Get the mesh data from the solid</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// (with smoothing level 1).</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">MeshDataCollection</span><span style="line-height: 140%"> mdc =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%">.GetObjectMesh(sol, fd);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Create the mesh defined by this data.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%"> sd = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; sd.SetDatabaseDefaults();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; sd.SetSubDMesh(mdc.VertexArray, mdc.FaceArray, 1);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add the mesh to database.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.CurrentSpaceId,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; newId = btr.AppendEntity(sd);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(sd, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Erase the cloned solid</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; sol.Erase();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> newId;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add creases to user selected faces</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Returns true if successful</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">bool</span><span style="line-height: 140%"> addCreases(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> meshId</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptSelectionOptions</span><span style="line-height: 140%"> pso =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptSelectionOptions</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; pso.ForceSubSelections = </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; pso.AllowDuplicates = </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; pso.MessageForAdding = </span><span style="line-height: 140%; color: #a31515">&quot;\nSelect edges to crease: &quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptSelectionResult</span><span style="line-height: 140%"> selRes =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Editor.GetSelection(pso);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If the user didn't make valid selection, we return</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (selRes.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SelectionSet</span><span style="line-height: 140%"> ss = selRes.Value;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// They may have picked more than one object - we need</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// the subobjects of the object with the right ObjectId</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SelectedObject</span><span style="line-height: 140%"> so = </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">SelectedObject</span><span style="line-height: 140%"> o </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ss)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (o.ObjectId == meshId)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; so = o;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If they picked on the wrong object, then just don't</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// add any extrusions</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (so == </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// We got to here so selection was valid</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// This will store selected edges</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%">&gt; creasePaths =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%">&gt;();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBObject</span><span style="line-height: 140%"> obj =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.GetObject(so.ObjectId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%"> sd = obj </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (sd != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.UpgradeOpen();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add all selected subentities to the collection</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SelectedSubObject</span><span style="line-height: 140%">[] subEnts =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; so.GetSubentities();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">SelectedSubObject</span><span style="line-height: 140%"> subEnt </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> subEnts)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (subEnt.FullSubentityPath.SubentId.Type</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; == </span><span style="line-height: 140%; color: #2b91af">SubentityType</span><span style="line-height: 140%">.Edge)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; creasePaths.Add(subEnt.FullSubentityPath);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add infinite creases to all those edges</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// -1 means 'always' crease</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.SetCrease(creasePaths.ToArray(), -1);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Extrude each mesh face by a random amount, up to a</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// user specified maximum. Returns true if successful.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">bool</span><span style="line-height: 140%"> extrudeFaces(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> meshId</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Now we want to stretch a few faces to add a bit of</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// randomness. Better just stretch outwards.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Prompt for max random bump (0.02 works well for</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// sample drawing).</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptDoubleOptions</span><span style="line-height: 140%"> pdo =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptDoubleOptions</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;\nSpecify bump size as fraction of bounds: &quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptDoubleResult</span><span style="line-height: 140%"> pdr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Editor.GetDouble(pdo);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If user cancels value entry, then we return.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (pdr.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> extrudelen = pdr.Value;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptSelectionOptions</span><span style="line-height: 140%"> pso =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptSelectionOptions</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; pso.ForceSubSelections = </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; pso.MessageForAdding = </span><span style="line-height: 140%; color: #a31515">&quot;\nSelect faces to bump: &quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptSelectionResult</span><span style="line-height: 140%"> psr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Editor.GetSelection(pso);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If user cancels selection, then we assume they want</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// to continue, but that they don't want to extrude any</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// surfaces</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (psr.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SelectionSet</span><span style="line-height: 140%"> ss = psr.Value;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// They may have picked more than one object - we need</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// the subobjects of the object with the right ObjectId</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SelectedObject</span><span style="line-height: 140%"> so = </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">SelectedObject</span><span style="line-height: 140%"> o </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ss)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (o.ObjectId == meshId)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; so = o;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (so == </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If they picked on the wrong object, then just don't</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// add any extrusions</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// We got to here so selection was valid</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Stores faces we selected for random extrusion</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%">&gt; bumpPaths =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%">&gt;();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBObject</span><span style="line-height: 140%"> obj =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.GetObject(so.ObjectId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%"> sd = obj </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (sd != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.UpgradeOpen();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SelectedSubObject</span><span style="line-height: 140%">[] subEnts =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; so.GetSubentities();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// We'll be extruding faces by a random amount, so</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// instantiate random number generator here ready</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// to use inside loop</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Random</span><span style="line-height: 140%"> rnd = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Random</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Process each selected face in turn</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">SelectedSubObject</span><span style="line-height: 140%"> subEnt </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> subEnts)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Is it a face?</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (subEnt.FullSubentityPath.SubentId.Type</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; == </span><span style="line-height: 140%; color: #2b91af">SubentityType</span><span style="line-height: 140%">.Face)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%">[] faces =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">FullSubentityPath</span><span style="line-height: 140%">[1];</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; faces[0] = subEnt.FullSubentityPath;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Find normal for this face</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Plane</span><span style="line-height: 140%"> fPlane =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.GetFacePlane(faces[0].SubentId);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%"> norm = fPlane.Normal;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Get length of diagonal across bounds to use</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// in calculating bump scale</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Extents3d</span><span style="line-height: 140%"> ext = (</span><span style="line-height: 140%; color: #2b91af">Extents3d</span><span style="line-height: 140%">)sd.Bounds;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%"> vec = ext.MaxPoint - ext.MinPoint;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%"> mat =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%">.Displacement(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; norm * 0.5 * extrudelen *</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; rnd.NextDouble() * vec.Length</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.TransformSubentityPathsBy(faces, mat);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Set random color for each mesh face.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> colorFaces(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> meshId</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Random</span><span style="line-height: 140%"> rnd = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Random</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBObject</span><span style="line-height: 140%"> obj =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.GetObject(meshId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%"> sd = obj </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (sd != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.UpgradeOpen();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Iterate all faces and set to a random color</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> i = 0; i &lt;= sd.NumberOfFaces - 1; i++)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubentityId</span><span style="line-height: 140%"> sId =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SubentityId</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">SubentityType</span><span style="line-height: 140%">.Face, i);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">byte</span><span style="line-height: 140%">[] rgb = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">byte</span><span style="line-height: 140%">[3];</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; rnd.NextBytes(rgb);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Color</span><span style="line-height: 140%"> col =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Color</span><span style="line-height: 140%">.FromRgb(rgb[0], rgb[1], rgb[2]);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.SetSubentColor(sId, col);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> convertToSolid(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> meshId</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db = doc.Database;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> newId = </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%">.Null;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBObject</span><span style="line-height: 140%"> obj =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.GetObject(meshId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%"> sd = obj </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SubDMesh</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (sd != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; sd.UpgradeOpen();</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// ConvertToSolid will throw an exception if</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// it can't create a solid from the mesh.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Solid3d</span><span style="line-height: 140%"> sol = </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sol = sd.ConvertToSolid(</span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">catch</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;\nMesh was too complex to turn into a solid.&quot;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.CurrentSpaceId,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; newId = btr.AppendEntity(sol);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(sol, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> newId;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Translates entity along x-axis by factor multiplied by</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// the entity's extent along the x-axis.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> translateEntity(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> objId, </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> factor</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%"> ent =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; objId,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Extents3d</span><span style="line-height: 140%"> ext = (</span><span style="line-height: 140%; color: #2b91af">Extents3d</span><span style="line-height: 140%">)ent.Bounds;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt1 =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(ext.MaxPoint.X, ext.MinPoint.Y, ext.MinPoint.Z);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%"> transVec =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; factor * (pt1 - ext.MinPoint);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%"> mat = </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%">.Displacement(transVec);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ent.TransformBy(mat);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Creates a SubDMesh based on an 'inflated' clone of the</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// selected solid. The user then gets to add creases and</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// select which faces will be given a random extrusion.</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// It colors each face of the mesh and then converts it to</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// a smooth solid.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;CC&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> CreateCasing()</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> meshId;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// First select the solid (just one)</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptEntityOptions</span><span style="line-height: 140%"> peo =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptEntityOptions</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;\nSelect a solid: &quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; peo.SetRejectMessage(</span><span style="line-height: 140%; color: #a31515">&quot;\nObject must be a 3D solid.&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; peo.AddAllowedClass(</span><span style="line-height: 140%; color: blue">typeof</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">Solid3d</span><span style="line-height: 140%">), </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptEntityResult</span><span style="line-height: 140%"> per = ed.GetEntity(peo);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (per.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; meshId =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cloneAndInflateSolid(tr, per.ObjectId);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If the above call returned a null ObjectId,</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// then something went wrong - we need to stop now</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (meshId == </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%">.Null)</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Now we have our original solid and the mesh</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// created from the cloned solid</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add creases</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (!addCreases(tr, meshId))</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Randomly extrude faces</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (!extrudeFaces(tr, meshId))</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Give faces random colors</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; colorFaces(tr, meshId);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Convert the mesh to a solid.</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> solId =</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; convertToSolid(tr, meshId);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Move the entities so they don't sit on</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// top of one other</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; translateEntity(tr, meshId, 1.5);</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; translateEntity(tr, solId, 3);</span></p>    <p style="margin: 0px; font-size: 8pt">&#160;</p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.TransactionManager.QueueForGraphicsFlush();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px; font-size: 8pt"><span style="line-height: 140%">}</span></p> </div> <!--EndFragment-->  <p>Here’s a sample 3D model – consisting of a single, composite 3D solid:</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201156f5568a7970b-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="Composite 3D solid" border="0" alt="Composite 3D solid" src="/assets/image_151405.jpg" width="378" height="337" /></a> </p>  <p>Here’s what happens when we run the CC command, selecting this solid and applying the recommended values (0.2 – i.e. 20% – for the inflation percentage and 0.05 – i.e. 5% – for the maximum random bump). I selected a number of edges and faces at random after which the code assigned random colours to all the faces, so please don’t get frustrated trying to reproduce these exact results. :-)</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201156e5cc530970c-pi"><img style="border-right-width: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="Infated, creased and bumped versions of the original (both as a mesh and a solid)" border="0" alt="Infated, creased and bumped versions of the original (both as a mesh and a solid)" src="/assets/image_127604.jpg" width="484" height="283" /></a> </p>  <p>The objects are (going from right to left):</p>  <ol>   <li>The original solid. </li>    <li>A sub-division mesh created by inflating the original solid and applying creases to certain edges and extruding certain faces. </li>    <li>A traditional AutoCAD solid created from the sub-division mesh. </li> </ol>  <p>The best way to understand the overall functionality of the application is to scan the CC command – defined by the CreateCasing function found at the bottom of the listing – and then looking into individual functions it uses. The application also defines another command – SPHM – which shows how to create a simple, spherical sub-division mesh.</p>
