---
layout: "post"
title: "Solving a fun little geometry problem in C# and F#"
date: "2010-11-10 15:26:43"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "F#"
  - "Geometry"
original_url: "https://www.keanw.com/2010/11/solving-a-fun-little-geometry-problem-in-c-and-f.html "
typepad_basename: "solving-a-fun-little-geometry-problem-in-c-and-f"
typepad_status: "Publish"
---

<p>A colleague set me a fun little geometry-related challenge a couple of days ago: to write C# and F# applications to make AutoCAD draw lines between a number of points spaced evenly around the circumference of a circle.</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e2013488dc0467970c-pi"><img style="border-right-width: 0px; margin: 20px auto; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px" title="Lines between points" border="0" alt="Lines between points" src="/assets/image_41353.jpg" width="482" height="470" /></a> </p>  <p>Here’s the first C# version I wrote, which makes use of a function to collect the various points before indexing into the collection from a nested loop:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">namespace</span><span style="line-height: 140%"> CircleOfLines</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Commands</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3dCollection</span><span style="line-height: 140%"> pointsOnCircle(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> center, </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> radius, </span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> n</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> alpha = </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.PI * 2 / n;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3dCollection</span><span style="line-height: 140%"> pts = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3dCollection</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> i = 0; i &lt; n; i++)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> theta = alpha * i;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.X + </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Cos(theta) * radius,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.Y + </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Sin(theta) * radius,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.Z</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pts.Add(pt);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> pts;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;CSCIR&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> CreateLinesBetweenPoints()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">HostApplicationServices</span><span style="line-height: 140%">.WorkingDatabase;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%"> bt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.BlockTableId,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bt[</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">.ModelSpace],</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> n = 19;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3dCollection</span><span style="line-height: 140%"> pts =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pointsOnCircle(</span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(0, 0, 0), 5.0, n);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> i = 0; i &lt; n; i++)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> j = i + 1; j &lt; n; j++)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> ln = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%">(pts[i], pts[j]);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(ln);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(ln, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div> <!--EndFragment-->  <p>I also wrote a “flattened” version in C# using a more linear approach (avoiding the function definition/call), although ultimately I believe the prior version to be more realistic:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">namespace</span><span style="line-height: 140%"> CircleOfLines</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Commands2</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;CSCIR2&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> CreateLinesBetweenPoints2()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">HostApplicationServices</span><span style="line-height: 140%">.WorkingDatabase;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%"> bt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.BlockTableId,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bt[</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">.ModelSpace],</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> n = 19;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> center = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(0, 0, 0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> radius = 5.0;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> alpha = </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.PI * 2 / n;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> i = 0; i &lt; n; i++)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> theta = alpha * i;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt1 =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.X + </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Cos(theta) * radius,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.Y + </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Sin(theta) * radius,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.Z</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">for</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">int</span><span style="line-height: 140%"> j = i + 1; j &lt; n; j++)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> theta2 = alpha * j;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt2 =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.X + </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Cos(theta2) * radius,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.Y + </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Sin(theta2) * radius,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; center.Z</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> ln = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%">(pt1, pt2);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(ln);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(ln, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div> <!--EndFragment-->  <p>And finally I provided a really “functional” version (in the sense that it uses Functional Programming techniques – all three versions are functional, of course ;-) in F#. This avoids any use of direct iteration, preferring to use data pipelining and recursion, although the recursion gets changed to iteration in the generated IL by the F# compiler’s tail call optimization.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">module</span><span style="line-height: 140%"> CircleOfLines</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> System</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">rec</span><span style="line-height: 140%"> circPoints acc (cen : Point3d) rad alpha n =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> n &lt;= 0 </span><span style="line-height: 140%; color: blue">then</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; acc</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> theta = alpha * (float)n</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> pt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> Point3d</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (cen.X + Math.Cos(theta) * rad,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.Y + Math.Sin(theta) * rad,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; cen.Z)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; circPoints (pt :: acc) cen rad alpha (n-1)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> pointsOnCircle cen rad n =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> alpha = Math.PI * 2.0 / (float)n</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; circPoints [] cen rad alpha n</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">rec</span><span style="line-height: 140%"> fromAtoBs acc pt1 pts =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">match</span><span style="line-height: 140%"> pts </span><span style="line-height: 140%; color: blue">with</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; | [] </span><span style="line-height: 140%; color: blue">-&gt;</span><span style="line-height: 140%"> acc</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; | pt2::t </span><span style="line-height: 140%; color: blue">-&gt;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> ln = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> Line(pt1,pt2)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; fromAtoBs (ln :: acc) pt1 t</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> linesFromPoint start endpts = fromAtoBs [] start endpts</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">rec</span><span style="line-height: 140%"> fromAsToBs acc pts =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">match</span><span style="line-height: 140%"> pts </span><span style="line-height: 140%; color: blue">with</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; | [] </span><span style="line-height: 140%; color: blue">-&gt;</span><span style="line-height: 140%"> acc</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; | h :: t </span><span style="line-height: 140%; color: blue">-&gt;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; fromAsToBs (linesFromPoint h t @ acc) t</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> linesBetweenPoints pts = fromAsToBs [] pts</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">[&lt;CommandMethod(</span><span style="line-height: 140%; color: maroon">&quot;FSCIR&quot;</span><span style="line-height: 140%">)&gt;]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> createLinesBetweenPoints() =</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> db = HostApplicationServices.WorkingDatabase</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">use</span><span style="line-height: 140%"> tr = db.TransactionManager.StartTransaction()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> bt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.GetObject</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; (db.BlockTableId,OpenMode.ForRead)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; :?&gt; BlockTable</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> ms =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.GetObject</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; (bt.[BlockTableRecord.ModelSpace],</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; OpenMode.ForWrite)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; :?&gt; BlockTableRecord</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> addToDatabase ent =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; ms.AppendEntity(ent) |&gt; ignore</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(ent, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; pointsOnCircle (</span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> Point3d(0.0, 0.0, 0.0)) 5.0 19</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; |&gt; linesBetweenPoints</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; |&gt; List.map addToDatabase</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; |&gt; ignore</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; tr.Commit()</span></p> </div> <!--EndFragment-->  <p>All versions do the same thing and actually have similar numbers of lines of code (although that would probably be different if I were formatting to a broader page width than fits on my blog, of course).</p>  <p><strong><em>Update</em></strong></p>  <p>Thanks for MichaelGG for the comment helping refine the F# implementation. Here’s the updated code which is, indeed, a good few lines shorter:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">module</span><span style="line-height: 140%"> CircleOfLines</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">open</span><span style="line-height: 140%"> System</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> pointsOnCircle (cen: Point3d) rad n =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> alpha = Math.PI * 2.0 / (float)n</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> calcPoint n =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> theta = alpha * (float)(n + 1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; Point3d(cen.X + Math.Cos theta * rad,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; cen.Y + Math.Sin theta * rad,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; cen.Z)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; List.init n calcPoint </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> linesFromPoint start endpts = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; endpts |&gt; List.map(</span><span style="line-height: 140%; color: blue">fun</span><span style="line-height: 140%"> x </span><span style="line-height: 140%; color: blue">-&gt;</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> Line(start, x)) |&gt; List.rev</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">rec</span><span style="line-height: 140%"> fromAsToBs acc pts =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">match</span><span style="line-height: 140%"> pts </span><span style="line-height: 140%; color: blue">with</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; | [] </span><span style="line-height: 140%; color: blue">-&gt;</span><span style="line-height: 140%"> acc</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; | h :: t </span><span style="line-height: 140%; color: blue">-&gt;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; fromAsToBs (linesFromPoint h t @ acc) t</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> linesBetweenPoints pts = fromAsToBs [] pts</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">[&lt;CommandMethod(</span><span style="line-height: 140%; color: maroon">&quot;FSCIR&quot;</span><span style="line-height: 140%">)&gt;]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> createLinesBetweenPoints() =</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> db = HostApplicationServices.WorkingDatabase</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">use</span><span style="line-height: 140%"> tr = db.TransactionManager.StartTransaction()</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> bt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.GetObject</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; (db.BlockTableId,OpenMode.ForRead)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; :?&gt; BlockTable</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> ms =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.GetObject</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; (bt.[BlockTableRecord.ModelSpace],</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; OpenMode.ForWrite)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; :?&gt; BlockTableRecord</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">let</span><span style="line-height: 140%"> addToDatabase ent =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; ms.AppendEntity(ent) |&gt; ignore</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(ent, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; pointsOnCircle (</span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> Point3d(0.0, 0.0, 0.0)) 5.0 19</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; |&gt; linesBetweenPoints</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; |&gt; List.map addToDatabase</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; |&gt; ignore</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; tr.Commit()</span></p> </div> <!--EndFragment-->  <p>Oh, and thanks to Jason Davies I now know I’ve been plotting a <a href="http://en.wikipedia.org/wiki/Complete_graph" target="_blank">complete graph</a>. Which is even easier to <a href="http://www.wolframalpha.com/input/?i=19-complete+graph" target="_blank">plot using Wolfram Alpha</a> than it is using C# or F# inside AutoCAD. ;-)</p>
