---
layout: "post"
title: "Jigging an AutoCAD hatch using .NET"
date: "2011-04-07 18:27:32"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Graphics system"
  - "Hatches"
  - "Jigs"
original_url: "https://www.keanw.com/2011/04/jigging-an-autocad-hatch-using-net.html "
typepad_basename: "jigging-an-autocad-hatch-using-net"
typepad_status: "Publish"
---

<p><a href="http://through-the-interface.typepad.com/through_the_interface/2010/06/creating-transparent-hatches-in-autocad-using-net.html?cid=6a00d83452464869e2014e8724f857970d#comment-6a00d83452464869e2014e8724f857970d" target="_blank">This question</a> came in a few weeks ago, which I thought worth addressing:</p>  <blockquote>   <p><em>Hi, Kean! I have a question - how can we create hatch during jig?</em></p> </blockquote>  <p>The code in this post endeavours to do just that, but – be warned – isn’t fully successful. The problem I chose to interpret this as is “how do you jig the creation of a polyline, using it as the boundary for an associative hatch?”, and it’s not an easy one to solve.</p>  <p>I started by taking Philippe Leefsma’s code from <a href="http://through-the-interface.typepad.com/through_the_interface/2010/12/jigging-an-autocad-polyline-with-arc-segments-using-net.html" target="_blank">this previous post</a>, which jigs a polyline (including arc segments). I switched it to use a DrawJig – rather than an EntityJig – as we’re creating multiple entities (a polyline and a hatch). I created the objects we want to jig, adding them to the database and the transaction before passing them to the jig’s constructor – an approach that has proven successful for jigging objects in a certain way, whether <a href="http://through-the-interface.typepad.com/through_the_interface/2009/03/jigging-an-autocad-solid-using-ironpython-and-net.html" target="_blank">a Solid3d with a visual style</a>, or <a href="http://through-the-interface.typepad.com/through_the_interface/2009/03/jigging-an-autocad-block-with-attributes-using-net.html" target="_blank">a BlockReference with attributes</a>.</p>  <p>Here’s the C# code:</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black">   <p style="margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p>    <p style="margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Colors;</span></p>    <p style="margin: 0px"><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue; line-height: 140%">namespace</span><span style="line-height: 140%"> HatchJig</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="color: blue; line-height: 140%">class</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">JigUtils</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Custom ArcTangent method, as the Math.Atan</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// doesn't handle specific cases</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">static</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> Atan(</span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> y, </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> x)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (x &gt; 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Math</span><span style="line-height: 140%">.Atan(y / x);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (x &lt; 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Math</span><span style="line-height: 140%">.Atan(y / x) - </span><span style="color: #2b91af; line-height: 140%">Math</span><span style="line-height: 140%">.PI;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%">&#160; </span><span style="color: green; line-height: 140%">// x == 0</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (y &gt; 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Math</span><span style="line-height: 140%">.PI;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (y &lt; 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> -</span><span style="color: #2b91af; line-height: 140%">Math</span><span style="line-height: 140%">.PI;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%"> </span><span style="color: green; line-height: 140%">// if (y == 0) theta is undefined</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> 0.0;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Computes Angle between current direction</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// (vector from last vertex to current vertex)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// and the last pline segment</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">static</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> ComputeAngle(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%"> startPoint, </span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%"> endPoint,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%"> xdir, </span><span style="color: #2b91af; line-height: 140%">Matrix3d</span><span style="line-height: 140%"> ucs</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%"> v =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (endPoint.X - startPoint.X) / 2,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (endPoint.Y - startPoint.Y) / 2,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (endPoint.Z - startPoint.Z) / 2</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> cos = v.DotProduct(xdir);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> sin =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; v.DotProduct(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%">.ZAxis.TransformBy(ucs).CrossProduct(xdir)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> Atan(sin, cos);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">class</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">HatchJig</span><span style="line-height: 140%"> : </span><span style="color: #2b91af; line-height: 140%">DrawJig</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%"> _tempPoint;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">bool</span><span style="line-height: 140%"> _isArcSeg = </span><span style="color: blue; line-height: 140%">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">bool</span><span style="line-height: 140%"> _isUndoing = </span><span style="color: blue; line-height: 140%">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Matrix3d</span><span style="line-height: 140%"> _ucs;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Plane</span><span style="line-height: 140%"> _plane;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Polyline</span><span style="line-height: 140%"> _pline = </span><span style="color: blue; line-height: 140%">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Hatch</span><span style="line-height: 140%"> _hat = </span><span style="color: blue; line-height: 140%">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> HatchJig(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Matrix3d</span><span style="line-height: 140%"> ucs, </span><span style="color: #2b91af; line-height: 140%">Plane</span><span style="line-height: 140%"> plane, </span><span style="color: #2b91af; line-height: 140%">Polyline</span><span style="line-height: 140%"> pl, </span><span style="color: #2b91af; line-height: 140%">Hatch</span><span style="line-height: 140%"> hat</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; _ucs = ucs;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; _plane = plane;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; _pline = pl;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; _hat = hat;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; AddDummyVertex();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">protected</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">override</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">bool</span><span style="line-height: 140%"> WorldDraw(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.GraphicsInterface.</span><span style="color: #2b91af; line-height: 140%">WorldDraw</span><span style="line-height: 140%"> wd</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Update the dummy vertex to be our 3D point</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// projected onto our plane</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_isArcSeg)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%"> lastVertex =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.GetPoint3dAt(_pline.NumberOfVertices - 2);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%"> refDir;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices &lt; 3)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; refDir = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%">(1.0, 1.0, 0.0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Check bulge to see if last segment was an arc or a line</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.GetBulgeAt(_pline.NumberOfVertices - 3) != 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">CircularArc3d</span><span style="line-height: 140%"> arcSegment =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.GetArcSegmentAt(_pline.NumberOfVertices - 3);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Line3d</span><span style="line-height: 140%"> tangent = arcSegment.GetTangent(lastVertex);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Reference direction is the invert of the arc tangent</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// at last vertex </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; refDir = tangent.Direction.MultiplyBy(-1.0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%"> pt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.GetPoint3dAt(_pline.NumberOfVertices - 3);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; refDir =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lastVertex.X - pt.X,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lastVertex.Y - pt.Y,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lastVertex.Z - pt.Z</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> angle =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">JigUtils</span><span style="line-height: 140%">.ComputeAngle(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lastVertex, _tempPoint, refDir, _ucs</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Bulge is defined as tan of one fourth of included angle</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Need to double the angle since it represents the included</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// angle of the arc</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// So formula is: bulge = Tan(angle * 2 * 0.25) </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> bulge = </span><span style="color: #2b91af; line-height: 140%">Math</span><span style="line-height: 140%">.Tan(angle * 0.5);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.SetBulgeAt(_pline.NumberOfVertices - 2, bulge);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Line mode. Need to remove last bulge if there was one</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices &gt; 1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.SetBulgeAt(_pline.NumberOfVertices - 2, 0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; _pline.SetPointAt(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.NumberOfVertices - 1, _tempPoint.Convert2d(_plane)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices == 3)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.Closed = </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">ObjectIdCollection</span><span style="line-height: 140%"> ids = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">ObjectIdCollection</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ids.Add(_pline.ObjectId);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Add the hatch loops and complete the hatch</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _hat.Associative = </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _hat.AppendLoop(</span><span style="color: #2b91af; line-height: 140%">HatchLoopTypes</span><span style="line-height: 140%">.Default, ids);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (!wd.RegenAbort)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.Geometry.Draw(_pline);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices &gt; 2)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _hat.EvaluateHatch(</span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (!wd.RegenAbort)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; wd.Geometry.Draw(_hat);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">protected</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">override</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">SamplerStatus</span><span style="line-height: 140%"> Sampler(</span><span style="color: #2b91af; line-height: 140%">JigPrompts</span><span style="line-height: 140%"> prompts)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">JigPromptPointOptions</span><span style="line-height: 140%"> jigOpts = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">JigPromptPointOptions</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; jigOpts.UserInputControls =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="color: #2b91af; line-height: 140%">UserInputControls</span><span style="line-height: 140%">.Accept3dCoordinates |</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">UserInputControls</span><span style="line-height: 140%">.NullResponseAccepted |</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">UserInputControls</span><span style="line-height: 140%">.NoNegativeResponseAccepted |</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">UserInputControls</span><span style="line-height: 140%">.GovernedByOrthoMode);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; _isUndoing = </span><span style="color: blue; line-height: 140%">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices == 1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// For the first vertex, just ask for the point</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; jigOpts.Message = </span><span style="color: #a31515; line-height: 140%">&quot;\nSpecify start point: &quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices &gt; 1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">string</span><span style="line-height: 140%"> msgAndKwds =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (_isArcSeg ?</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #a31515; line-height: 140%">&quot;\nSpecify endpoint of arc or [Line/Undo]: &quot;</span><span style="line-height: 140%"> :</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #a31515; line-height: 140%">&quot;\nSpecify next point or [Arc/Undo]: &quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">string</span><span style="line-height: 140%"> kwds = (_isArcSeg ? </span><span style="color: #a31515; line-height: 140%">&quot;Line Undo&quot;</span><span style="line-height: 140%"> : </span><span style="color: #a31515; line-height: 140%">&quot;Arc Undo&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; jigOpts.SetMessageAndKeywords(msgAndKwds, kwds);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">SamplerStatus</span><span style="line-height: 140%">.Cancel; </span><span style="color: green; line-height: 140%">// Should never happen</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Get the point itself</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">PromptPointResult</span><span style="line-height: 140%"> res = prompts.AcquirePoint(jigOpts);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (res.Status == </span><span style="color: #2b91af; line-height: 140%">PromptStatus</span><span style="line-height: 140%">.Keyword)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (res.StringResult.ToUpper() == </span><span style="color: #a31515; line-height: 140%">&quot;ARC&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _isArcSeg = </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (res.StringResult.ToUpper() == </span><span style="color: #a31515; line-height: 140%">&quot;LINE&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _isArcSeg = </span><span style="color: blue; line-height: 140%">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (res.StringResult.ToUpper() == </span><span style="color: #a31515; line-height: 140%">&quot;UNDO&quot;</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _isUndoing = </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">SamplerStatus</span><span style="line-height: 140%">.OK;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (res.Status == </span><span style="color: #2b91af; line-height: 140%">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Check if it has changed or not (reduces flicker)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_tempPoint == res.Value)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">SamplerStatus</span><span style="line-height: 140%">.NoChange;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _tempPoint = res.Value;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">SamplerStatus</span><span style="line-height: 140%">.OK;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">SamplerStatus</span><span style="line-height: 140%">.Cancel;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">bool</span><span style="line-height: 140%"> IsUndoing</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">get</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%"> _isUndoing;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">void</span><span style="line-height: 140%"> AddDummyVertex()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Create a new dummy vertex... can have any initial value</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; _pline.AddVertexAt(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.NumberOfVertices, </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Point2d</span><span style="line-height: 140%">(0, 0), 0, 0, 0</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">void</span><span style="line-height: 140%"> RemoveLastVertex()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Let's first remove our dummy vertex&#160;&#160;&#160; </span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices &gt; 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pline.RemoveVertexAt(_pline.NumberOfVertices - 1);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// And then check the type of the last segment</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (_pline.NumberOfVertices &gt;= 2)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">double</span><span style="line-height: 140%"> blg = _pline.GetBulgeAt(_pline.NumberOfVertices - 2);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _isArcSeg = (blg != 0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; [</span><span style="color: #2b91af; line-height: 140%">CommandMethod</span><span style="line-height: 140%">(</span><span style="color: #a31515; line-height: 140%">&quot;HATJIG&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">public</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">static</span><span style="line-height: 140%"> </span><span style="color: blue; line-height: 140%">void</span><span style="line-height: 140%"> RunHatchJig()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Database</span><span style="line-height: 140%"> db = doc.Database;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Create a transaction, as we're jigging</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// db-resident objects</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">BlockTableRecord</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</span><span style="color: #2b91af; line-height: 140%">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.CurrentSpaceId, </span><span style="color: #2b91af; line-height: 140%">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%"> normal =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Vector3d</span><span style="line-height: 140%">.ZAxis.TransformBy(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.CurrentUserCoordinateSystem</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// We will pass a plane to our jig, to help</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// with UCS transformations</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Plane</span><span style="line-height: 140%"> plane = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Plane</span><span style="line-height: 140%">(</span><span style="color: #2b91af; line-height: 140%">Point3d</span><span style="line-height: 140%">.Origin, normal);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// We also pass a db-resident polyline</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Polyline</span><span style="line-height: 140%"> pl = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Polyline</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pl.Normal = normal;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(pl);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(pl, </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// And a db-resident hatch</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">Hatch</span><span style="line-height: 140%"> hat = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Hatch</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Use a non-solid hatch pattern, to aid jigging</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; hat.SetHatchPattern(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">HatchPatternType</span><span style="line-height: 140%">.PreDefined,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #a31515; line-height: 140%">&quot;ANGLE&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// But let's make it transparent, for fun</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Alpha value is Truncate(255 * (100-n)/100)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; hat.ColorIndex = 1;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; hat.Transparency = </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">Transparency</span><span style="line-height: 140%">(127);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Add the hatch to the modelspace &amp; transaction</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">ObjectId</span><span style="line-height: 140%"> hatId = btr.AppendEntity(hat);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(hat, </span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// And finally pass everything to the jig</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">HatchJig</span><span style="line-height: 140%"> jig =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">HatchJig</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.CurrentUserCoordinateSystem, plane, pl, hat</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">while</span><span style="line-height: 140%"> (</span><span style="color: blue; line-height: 140%">true</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: #2b91af; line-height: 140%">PromptResult</span><span style="line-height: 140%"> res = ed.Drag(jig);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">switch</span><span style="line-height: 140%"> (res.Status)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// New point was added, keep going</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">case</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">PromptStatus</span><span style="line-height: 140%">.OK:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; jig.AddDummyVertex();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">break</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// Keyword was entered</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">case</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">PromptStatus</span><span style="line-height: 140%">.Keyword:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">if</span><span style="line-height: 140%"> (jig.IsUndoing)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; jig.RemoveLastVertex();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">break</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// The jig completed successfully</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">case</span><span style="line-height: 140%"> </span><span style="color: #2b91af; line-height: 140%">PromptStatus</span><span style="line-height: 140%">.None:</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// You can remove this next line if you want</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// the vertex being jigged to be included</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; jig.RemoveLastVertex();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// User cancelled the command</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">default</span><span style="line-height: 140%">:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// No need to erase the polyline &amp; hatch, as</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: green; line-height: 140%">// the transaction will simply be aborted</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="color: blue; line-height: 140%">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span>&#160;</p> </div> <!--EndFragment-->  <p>Overall the code works, but the graphics refresh has some issues. The HATJIG command starts well enough:</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e20147e3ceae79970b-pi"><img title="Jigging our hatch - starts well" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" border="0" alt="Jigging our hatch - starts well" src="/assets/image_748991.jpg" width="475" height="271" /></a></p>  <p>But as we move the cursor around, there is unfortunate ghosting of the hatch graphics:</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e2014e60738ba0970c-pi"><img title="Jigging our hatch - ugly in the middle" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" border="0" alt="Jigging our hatch - ugly in the middle" src="/assets/image_458869.jpg" width="457" height="315" /></a></p>  <p>Even as we pick new boundary points the hatch gets shown but doesn’t stop being displayed as the boundary changes. It seems as though the transient graphics sub-system – which is being fed the graphics from the DrawJig’s WorldDraw() method – seems to think more needs to be displayed than is actually the case.</p>  <p>At least when the jig is completed the polyline and hatch are displayed properly:</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e2014e874f0e3f970d-pi"><img title="Jigging our hatch - but ends well" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" border="0" alt="Jigging our hatch - but ends well" src="/assets/image_297884.jpg" width="475" height="314" /></a></p>  <p>There may be other approaches to solve this – such as using the transient graphics API directly – but I suspect that the nature of the hatch implementation will make it hard to rely on its evaluation and display work effectively when called transiently, whether via a jig or directly.</p>  <p>I decided to post this anyway, in case any readers have bright ideas on how either to fix this implementation or to solve it differently. Someone may even have implemented a solution they don’t mind sharing. Anyone?</p>  <p><strong><em>Update:</em></strong></p>  <p>Thanks to input from Holger Rasch, <a href="http://through-the-interface.typepad.com/through_the_interface/2014/04/jigging-an-autocad-hatch-using-net-redux.html" target="_blank">this post</a> shows how to make this work properly.</p>
