---
layout: "post"
title: "Displaying transient AutoCAD points that respect PDMODE using .NET"
date: "2011-03-28 14:29:29"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Geometry"
  - "Graphics system"
original_url: "https://www.keanw.com/2011/03/displaying-transient-autocad-points-that-respect-pdmode-using-net.html "
typepad_basename: "displaying-transient-autocad-points-that-respect-pdmode-using-net"
typepad_status: "Publish"
---

<p>Since starting to use the transient graphics API in AutoCAD 2009, I’ve believed that any DBPoints you display would not respect PDMODE (the AutoCAD system variable allowing the user to control how points are displayed). A recent internal discussion was on this very subject, and one of our engineering team, Longchao Jiang, interjected with a comment explaining that only points on the DEFPOINTS layer get displayed without PDMODE being applied.</p>  <p>This was quite a revelation for me: DBPoints apparently get created on DEFPOINTS by default and simply changing them to layer 0 (say) would cause them to respect PDMODE when displayed transiently? I had to try that out.</p>  <p>To do so, I took the code from a couple of recent posts, one <a href="http://through-the-interface.typepad.com/through_the_interface/2011/02/gathering-points-defining-3d-autocad-geometry-using-net.html" target="_blank">gathering points on a 3D object</a> and another <a href="http://through-the-interface.typepad.com/through_the_interface/2011/03/adding-ortho-support-to-the-transient-graphics-autocad-move-using-net.html" target="_blank">using transient graphics to implement a custom MOVE command</a>, and plugged them together. For each of the objects selected to move, the code now gathers points from them and creates and displays these transiently along with the base geometry.</p>  <p>The updates to the point-gathering code were really minor – just about changing the signatures of the functions we want to use to be static and/or public – so we can simply call them from the other source file without much effort. Because the changes were minor, I’ve placed the code <a href="http://through-the-interface.typepad.com/files/gather-points-3d.cs" target="_blank">here for you to download</a>.</p>  <p>The other source file has changed slightly more, but not very much: we now call into the other file to gather points on each object and pass them through to the modified CreateTransGraphics() function. This function now creates a DBPoint for each point, making sure it is on layer 0 before adding it to our list of transient objects to display.</p>  <p>Here’s the C# code from that file:</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.GraphicsInterface;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Collections.Generic;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">namespace</span><span style="line-height: 140%"> CustomMove</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Commands</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;MYMOVE&quot;</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: #2b91af">CommandFlags</span><span style="line-height: 140%">.UsePickSet)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> CustomMoveCmd()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.ApplicationServices.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%"> ucs = ed.CurrentUserCoordinateSystem;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Start by getting the objects to move</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// (will use the pickfirst set, if defined)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptSelectionResult</span><span style="line-height: 140%"> psr = ed.GetSelection();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (psr.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK || psr.Value.Count == 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Create a collection of the selected objects' IDs</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%"> ids =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%">(psr.Value.GetObjectIds());</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Ask the user to select a base point for the move</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptPointResult</span><span style="line-height: 140%"> ppr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.GetPoint(</span><span style="line-height: 140%; color: #a31515">&quot;\nSpecify base point: &quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (ppr.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> baseUcs = ppr.Value;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">CoordinateSystem3d</span><span style="line-height: 140%"> cs = ucs.CoordinateSystem3d;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Transform from UCS to WCS</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%"> mat =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%">.AlignCoordinateSystem(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">.Origin,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%">.XAxis,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%">.YAxis,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%">.ZAxis,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cs.Origin,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cs.Xaxis,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cs.Yaxis,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cs.Zaxis</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> baseWcs = baseUcs.TransformBy(mat);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> curPt = baseWcs;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// A local delegate for our event handler so</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// we can remove it at the end</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventHandler</span><span style="line-height: 140%"> handler = </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Our transaction</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Database.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Gather our points</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3dCollection</span><span style="line-height: 140%"> pts = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3dCollection</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> id </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ids)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%"> ent = (</span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%">)tr.GetObject(id, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; PointGathering.</span><span style="line-height: 140%; color: #2b91af">Commands</span><span style="line-height: 140%">.CollectPoints(tr, ent, pts);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Create our transient drawables, with associated</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// graphics, from the selected objects</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%">&gt; drawables =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; CreateTransGraphics(tr, ids, pts);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Add our point monitor</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// (as a delegate we have access to basePt and curPt,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//&#160; which avoids having to access global/member state)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; handler =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">delegate</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: blue">object</span><span style="line-height: 140%"> sender, </span><span style="line-height: 140%; color: #2b91af">PointMonitorEventArgs</span><span style="line-height: 140%"> e)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Get the point, with &quot;ortho&quot; applied, if needed</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt = e.Context.ComputedPoint;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (IsOrthModeOn())</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Point is in WCS, we need UCS for ortho calcs</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> destUcs = pt.TransformBy(mat.Inverse());</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pt = GetOrthoPoint(baseUcs, destUcs);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Then we transform back to WCS</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pt = pt.TransformBy(mat);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Update our graphics and the current point</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; UpdateTransGraphics(drawables, curPt, pt);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; curPt = pt;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; };</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.PointMonitor += handler;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Ask for the destination, during which the point</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// monitor will be updating the transient graphics</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">PromptPointOptions</span><span style="line-height: 140%"> opt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptPointOptions</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;\nSpecify second point: &quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; opt.UseBasePoint = </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; opt.BasePoint = baseUcs;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ppr = ed.GetPoint(opt);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// If the point was selected successfully...</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (ppr.Status == </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// ... move the entities to their destination</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> destUcs = ppr.Value;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> dest =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (IsOrthModeOn() ?</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetOrthoPoint(baseUcs, destUcs) :</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; destUcs);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MoveEntities(tr, baseWcs, dest.TransformBy(mat), ids);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// And inform the user</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;\n{0} object{1} moved.&quot;</span><span style="line-height: 140%">, ids.Count,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ids.Count == 1 ? </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span><span style="line-height: 140%"> : </span><span style="line-height: 140%; color: #a31515">&quot;s&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">catch</span><span style="line-height: 140%"> (Autodesk.AutoCAD.Runtime.</span><span style="line-height: 140%; color: #2b91af">Exception</span><span style="line-height: 140%"> ex)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(</span><span style="line-height: 140%; color: #a31515">&quot;\nException: {0}&quot;</span><span style="line-height: 140%">, ex.Message);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">finally</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Clear any transient graphics</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClearTransGraphics(drawables);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Remove the event handler</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (handler != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.PointMonitor -= handler;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Dispose();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">bool</span><span style="line-height: 140%"> IsOrthModeOn()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Check the value of the ORTHOMODE sysvar</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">object</span><span style="line-height: 140%"> orth =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.ApplicationServices.</span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetSystemVariable(</span><span style="line-height: 140%; color: #a31515">&quot;ORTHOMODE&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Convert</span><span style="line-height: 140%">.ToInt32(orth) &gt; 0;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> GetOrthoPoint(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> basePt, </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Apply an orthographic mode</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> x = pt.X,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; y = pt.Y,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; z = pt.Z;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Vector3d</span><span style="line-height: 140%"> vec = basePt.GetVectorTo(pt);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">double</span><span style="line-height: 140%"> absX = </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Abs(vec.X),</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; absY = </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Abs(vec.Y),</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; absZ = </span><span style="line-height: 140%; color: #2b91af">Math</span><span style="line-height: 140%">.Abs(vec.Z);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (absX &lt; absY &amp;&amp; absX &lt; absZ)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; x = basePt.X;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">else</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (absY &lt; absX &amp;&amp; absY &lt; absZ)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; y = basePt.Y;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; z = pt.Z;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%">(x, y, z);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> MoveEntities(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> basePt, </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> moveTo,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%"> ids</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Transform a set of entities to a new location</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%"> mat =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%">.Displacement(basePt.GetVectorTo(moveTo));</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> id </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ids)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%"> ent = (</span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%">)tr.GetObject(id, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ent.TransformBy(mat);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%">&gt; CreateTransGraphics(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%"> ids, </span><span style="line-height: 140%; color: #2b91af">Point3dCollection</span><span style="line-height: 140%"> pts</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Create our list of drawables to return</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%">&gt; drawables = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%">&gt;();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> id </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ids)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Read each entity</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%"> ent = (</span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%">)tr.GetObject(id, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Clone it, make it red &amp; add the clone to the list</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%"> drawable = ent.Clone() </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; drawable.ColorIndex = 1;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; drawables.Add(drawable);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Create a transient point for each member of the collection</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> pts)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Make sure each point is on layer 0 (i.e. not DEFPOINTS)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// and make it red, too</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">DBPoint</span><span style="line-height: 140%"> dbp = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">DBPoint</span><span style="line-height: 140%">(pt);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; dbp.Layer = </span><span style="line-height: 140%; color: #a31515">&quot;0&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; dbp.ColorIndex = 1;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; drawables.Add(dbp);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Draw each one initially</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%"> d </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> drawables)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">TransientManager</span><span style="line-height: 140%">.CurrentTransientManager.AddTransient(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; d, </span><span style="line-height: 140%; color: #2b91af">TransientDrawingMode</span><span style="line-height: 140%">.DirectShortTerm,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 128, </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">IntegerCollection</span><span style="line-height: 140%">()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> drawables;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> UpdateTransGraphics(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%">&gt; drawables, </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> curPt, </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> moveToPt</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Displace each of our drawables</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%"> mat =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Matrix3d</span><span style="line-height: 140%">.Displacement(curPt.GetVectorTo(moveToPt));</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Update their graphics</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%"> d </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> drawables)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%"> e = d </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; e.TransformBy(mat);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">TransientManager</span><span style="line-height: 140%">.CurrentTransientManager.UpdateTransient(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; d, </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">IntegerCollection</span><span style="line-height: 140%">()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> ClearTransGraphics(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%">&gt; drawables</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Clear the transient graphics for our drawables</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">TransientManager</span><span style="line-height: 140%">.CurrentTransientManager.EraseTransients(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">TransientDrawingMode</span><span style="line-height: 140%">.DirectShortTerm,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; 128, </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">IntegerCollection</span><span style="line-height: 140%">()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; );</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">// Dispose of them and clear the list</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Drawable</span><span style="line-height: 140%"> d </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> drawables)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; d.Dispose();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; drawables.Clear();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div> <!--EndFragment-->  <p>Here’s what happens when we execute the code and move a sphere, with PDMODE set to 0 (you should just be able to make out the points displayed as dots):</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e20147e38a1221970b-pi" target="_blank"><img style="background-image: none; border-bottom: 0px; border-left: 0px; margin: 0px auto; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top: 0px; border-right: 0px; padding-top: 0px" title="Transient graphics showing points as dots" border="0" alt="Transient graphics showing points as dots" src="/assets/image_543009.jpg" width="475" height="309" /></a></p>  <p>And here’s what happens with PDMODE set to 2 (which looks a bit like something out of an old-school Star Wars video game):</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e20147e38a1239970b-pi" target="_blank"><img style="background-image: none; border-bottom: 0px; border-left: 0px; margin: 0px auto; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top: 0px; border-right: 0px; padding-top: 0px" title="Transient point graphics respecting PDMODE" border="0" alt="Transient point graphics respecting PDMODE" src="/assets/image_46195.jpg" width="475" height="299" /></a></p>  <p>Very cool – thanks for the tip, Longchao! :-)</p>  <p>I’m now at the airport, heading for Bangalore via Heathrow. I’ll be working from our office there for the coming week, spending time with our team there. Aside from catching up with everyone, I’m looking forward to watching India vs. Pakistan during the 2011 Cricket World Cup semi-final on Wednesday: I’m not really a cricket fan, but watching a match like this in India is a real experience (even if you’re only watching it on TV, as I’ll be doing).</p>
