---
layout: "post"
title: "Testing whether a point is on any AutoCAD curve using .NET"
date: "2012-01-09 05:58:00"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Geometry"
original_url: "https://www.keanw.com/2012/01/testing-whether-a-point-is-on-any-autocad-curve-using-net.html "
typepad_basename: "testing-whether-a-point-is-on-any-autocad-curve-using-net"
typepad_status: "Publish"
---

<p>One great thing about having an engaged blog readership is that people catch issues quickly (which helps keep me honest :-). When I posted late on a Friday night (under self-imposed pressure to get a third post up in a four-day first week back after the holidays), I suspected I’d missed something. I even checked the protocol I expected to contain the function I knew had to be there, but obviously not thoroughly enough.</p>  <p>Anyway, all this to say that there’s a better, more general approach to finding whether a point is on a polyline, the subject of <a href="http://through-the-interface.typepad.com/through_the_interface/2012/01/testing-whether-a-point-is-on-an-autocad-polyline-using-net.html" target="_blank">the last post</a>. I knew it was there – as part of the abstract Curve protocol that is implemented by all linear geometry stored in the AutoCAD drawing database – but I needed a reminder from <a href="http://twitter.com/owenwengerd" target="_blank">Owen Wengard</a>, who sent me a direct Twitter message when a TypePad quirk stopped him from humiliating me publicly ;-) – to realise what I’d missed. Thanks for the prod, Owen!</p>  <p>While there is no “IsOn()” method at the Curve level, there are GetParamAtPoint() (the method Owen suggested) and GetDistAtPoint() (the one I ended up using) methods, which throw exceptions if the provided point is not on the provided curve.</p>  <p>Catching an exception does have performance implications – in pure ObjectARX, from C++, the equivalent AcDbCurve::getDistAtPoint() method returns an error code indicating success or failure, which is less expensive – so Owen also suggested using GetClosestPointTo(), instead.</p>  <p>The below implementation shows two implementations of an “IsPointOnCurve” function: IsPointOnCurveGDAP() (for GetDistAtPoint()) and IsPointOnCurveGCP() (for GetClosestPoint()). The updated POC command makes use of the latter implementation – as I expect that to be more efficient in the case of the point not being on the curve – but we’ll compare performance of the two implementations in a post later on in the week.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Geometry;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">namespace</span><span style="line-height: 140%"> CurveTesting</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Commands</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;POC&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> PointOnCurve()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Database</span><span style="line-height: 140%"> db = doc.Database;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Editor</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">PromptEntityOptions</span><span style="line-height: 140%"> peo =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptEntityOptions</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;\nSelect a curve&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; peo.SetRejectMessage(</span><span style="line-height: 140%; color: #a31515">&quot;Please select a curve&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; peo.AddAllowedClass(</span><span style="line-height: 140%; color: blue">typeof</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%">), </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">PromptEntityResult</span><span style="line-height: 140%"> per = ed.GetEntity(peo);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (per.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">PromptPointResult</span><span style="line-height: 140%"> ppr = ed.GetPoint(</span><span style="line-height: 140%; color: #a31515">&quot;\nSelect a point&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (ppr.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr = db.TransactionManager.StartTransaction();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (tr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%"> curve =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tr.GetObject(per.ObjectId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (curve != </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">bool</span><span style="line-height: 140%"> isOn = IsPointOnCurveGCP(curve, ppr.Value);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ed.WriteMessage(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #a31515">&quot;\nSelected point is {0}on the curve.&quot;</span><span style="line-height: 140%">,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; isOn ? </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span><span style="line-height: 140%"> : </span><span style="line-height: 140%; color: #a31515">&quot;not &quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tr.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// A generalised IsPointOnCurve function that works on all</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// types of Curve (including Polylines), but catches an</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Exception on failure</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">bool</span><span style="line-height: 140%"> IsPointOnCurveGDAP(</span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%"> cv, </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Return true if operation succeeds</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; cv.GetDistAtPoint(pt);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">catch</span><span style="line-height: 140%"> { }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Otherwise we return false</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// A generalised IsPointOnCurve function that works on all</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// types of Curve (including Polylines), and checks the position</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// of the returned point rather than relying on catching an</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// exception</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">bool</span><span style="line-height: 140%"> IsPointOnCurveGCP(</span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%"> cv, </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> pt)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Return true if operation succeeds</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Point3d</span><span style="line-height: 140%"> p = cv.GetClosestPointTo(pt, </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> (p - pt).Length &lt;= </span><span style="line-height: 140%; color: #2b91af">Tolerance</span><span style="line-height: 140%">.Global.EqualPoint;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">catch</span><span style="line-height: 140%"> { }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Otherwise we return false</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div>    <p>You should see exactly the same behaviour as in the last post, but now the code works for all curve classes, such as Polyline, Polyline2d, Polyline3d, Line, Arc, Circle and Spline.</p>
