---
layout: "post"
title: "Fixing block draw-order in AutoCAD drawings exported by SmartSketch using .NET"
date: "2013-05-27 16:49:55"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Draw order"
  - "Drawing structure"
original_url: "https://www.keanw.com/2013/05/fixing-autocad-drawings-exported-by-smartsketch-using-net.html "
typepad_basename: "fixing-autocad-drawings-exported-by-smartsketch-using-net"
typepad_status: "Publish"
---

<p>Here’s a question I received recently from Dustin Vest, who works as a PDMS administrator at <a href="http://www.fluor.com" target="_blank">Fluor</a>:</p>  <blockquote>   <p><em>I am having a problem with Intergraph’s SmartSketch dwg files it exports... I found some code on your site that got me into the blocks, but I can’t seem to change the draworder of entities within the block. SmartPlant 3D exports all the symbols as blocks but with wipeouts on top of the rest of the block.</em></p> </blockquote>  <p>Dustin provided some code that was very nearly working – it really didn’t need much work to get it in shape – and has kindly allowed me to share it, here.</p>  <p>The below C# code defines a WTB command (for “WipeoutsToBottom” – it’s not a new Internet swearcronym ;-) that moves any wipeouts to the bottom of the selected block (or of all blocks in the drawing if the user hits Enter).</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.DatabaseServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.EditorInput;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.AutoCAD.Runtime;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">namespace</span><span style="line-height: 140%"> BlockFixer</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Commands</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; [</span><span style="line-height: 140%; color: #2b91af">CommandMethod</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;WTB&quot;</span><span style="line-height: 140%">)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">void</span><span style="line-height: 140%"> WipeoutsToBottom()</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> doc = </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%">.DocumentManager.MdiActiveDocument;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> ed = doc.Editor;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> db = doc.Database;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Ask the user to select a block or None for &quot;all&quot;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> peo =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">PromptEntityOptions</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #a31515">&quot;\nSelect block to fix &lt;all&gt;&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; peo.SetRejectMessage(</span><span style="line-height: 140%; color: #a31515">&quot;Must be a block.&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; peo.AddAllowedClass(</span><span style="line-height: 140%; color: blue">typeof</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">BlockReference</span><span style="line-height: 140%">), </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; peo.AllowNone = </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> per = ed.GetEntity(peo);</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; per.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.OK &amp;&amp;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; per.Status != </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.None</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// If the user hit enter, run on all blocks in the drawing</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">bool</span><span style="line-height: 140%"> allBlocks = per.Status == </span><span style="line-height: 140%; color: #2b91af">PromptStatus</span><span style="line-height: 140%">.None;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> tr = db.TransactionManager.StartTransaction())</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> toProcess = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (allBlocks)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> bt =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (</span><span style="line-height: 140%; color: #2b91af">BlockTable</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; db.BlockTableId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Collect all the non-layout blocks in the drawing</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> btrId </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> bt)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; btrId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (!btr.IsLayout)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; toProcess.Add(btrId);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// A specific block was selected, let&#39;s open it</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> brId = per.ObjectId;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> br =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (</span><span style="line-height: 140%; color: #2b91af">BlockReference</span><span style="line-height: 140%">)tr.GetObject(brId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Collect the ID of its underlying block definition</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; toProcess.Add(br.BlockTableRecord);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> brIds = MoveWipeoutsToBottom(tr, toProcess);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> count = toProcess.Count;</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Open each of the returned block references and</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// request that they be redrawn</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> brId </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> brIds)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> br =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (</span><span style="line-height: 140%; color: #2b91af">BlockReference</span><span style="line-height: 140%">)tr.GetObject(brId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite);</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// We want to redraw a specific block, so let&#39;s modify a</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// property on the selected block reference</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// We might also have called this method:</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// br.RecordGraphicsModified(true);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// but setting a property works better with undo</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; br.Visible = br.Visible;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Report the number of blocks modified (after</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// being filtered by MoveWipeoutsToBottom())</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ed.WriteMessage(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #a31515">&quot;\nModified {0} block definition{1}.&quot;</span><span style="line-height: 140%">,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; count, count == 1 ? </span><span style="line-height: 140%; color: #a31515">&quot;&quot;</span><span style="line-height: 140%"> : </span><span style="line-height: 140%; color: #a31515">&quot;s&quot;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Commit the transaction</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tr.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">catch</span><span style="line-height: 140%"> (Autodesk.AutoCAD.Runtime.</span><span style="line-height: 140%; color: #2b91af">Exception</span><span style="line-height: 140%"> e)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; doc.Editor.WriteMessage(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #a31515">&quot;\nException: {0}&quot;</span><span style="line-height: 140%">, e.Message</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Move the wipeouts to the bottom of the specified</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// block definitions</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">private</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">static</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%"> MoveWipeoutsToBottom(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> tr, </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%"> ids</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; )</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// The IDs of any block references we find</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// to return to the call for updating</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> brIds = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// We only need to get this once</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> wc = </span><span style="line-height: 140%; color: #2b91af">RXClass</span><span style="line-height: 140%">.GetClass(</span><span style="line-height: 140%; color: blue">typeof</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">Wipeout</span><span style="line-height: 140%">));</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Take a copy of the IDs passed in, as we&#39;ll modify the</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// original list for the caller to use</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> btrIds = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%">[ids.Count];</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; ids.CopyTo(btrIds, 0);</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Loop through the blocks passed in, opening each one</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> btrId </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> btrIds)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> btr =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (</span><span style="line-height: 140%; color: #2b91af">BlockTableRecord</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; btrId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Collect the wipeouts in the block</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> wipeouts = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ObjectIdCollection</span><span style="line-height: 140%">();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> id </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> btr)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> ent = (</span><span style="line-height: 140%; color: #2b91af">Entity</span><span style="line-height: 140%">)tr.GetObject(id, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForRead);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (ent.GetRXClass().IsDerivedFrom(wc))</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; wipeouts.Add(id);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Move the collected wipeouts to the bottom</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (wipeouts.Count &gt; 0)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Modify the draw order table, if we have wipepouts</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> dot =</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (</span><span style="line-height: 140%; color: #2b91af">DrawOrderTable</span><span style="line-height: 140%">)tr.GetObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; btr.DrawOrderTableId, </span><span style="line-height: 140%; color: #2b91af">OpenMode</span><span style="line-height: 140%">.ForWrite</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; dot.MoveToBottom(wipeouts);</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// Collect the block references to this block, to pass</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: green">// back to the calling function for updating</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">var</span><span style="line-height: 140%"> btrBrIds = btr.GetBlockReferenceIds(</span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ObjectId</span><span style="line-height: 140%"> btrBrId </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> btrBrIds)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; brIds.Add(btrBrId);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">else</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ids.Remove(btrId);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160;&#0160;&#0160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> brIds;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160;&#0160;&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#0160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div>  <p>The code is a bit longer than I had originally expected as I decided that, rather than relying on Editor.Regen() to reflect the changes to the drawing, it would be cleaner to modify each block reference in turn in order to force their graphics to be refreshed.</p>  <p>We’re not actually making a change to each block reference, but it’s not enough to just open them for write. The classic approach, here, would be to call RecordGraphicsModified(true) on each object, but I’ve actually found that making a property modification (even if to the same value) leads to undo working better – it forces a redraw even on undo. So I’ve chosen to set the Visible property of each block reference to the current value of the Visible property – I’m sure you’ll agree that’s as innocuous a modification as you can get. :-)</p>  <p>The function that checks each block for wipeouts and then modifies the draw order now collects the block references to these blocks and returns them to the caller. It’s clear that calling Regen() would have been simpler (i.e. taking fewer lines of code), but it would have exhibited similar behaviour to calling RecordGraphicsModified() with respect to undo. So while it takes more code, this approach is ultimately cleaner and works better, too.</p>  <p>Dustin has tried the application and tells me it works well for him – and it works well on the drawings Dustin provided for me to test with – but, beyond that, as I don’t personally use SmartSketch I have to take his word for it. If any other SmartSketch users who’ve hit this particular problem are able to give this a test, it’d be great to get some feedback in the comments.</p>
