---
layout: "post"
title: "JavaScript in AutoCAD: Revision clouds using Paper.js"
date: "2014-05-21 11:41:58"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "HTML"
  - "JavaScript"
  - "JSON"
  - "User interface"
  - "Web/Tech"
original_url: "https://www.keanw.com/2014/05/javascript-in-autocad-revision-clouds-using-paperjs.html "
typepad_basename: "javascript-in-autocad-revision-clouds-using-paperjs"
typepad_status: "Publish"
---

<p>Having <a href="http://through-the-interface.typepad.com/through_the_interface/2014/05/javascript-in-autocad-introducing-the-series.html" target="_blank">introduced this series</a>, it’s time to look at some code. This first sample shows how to create and host a web-page that uses an external graphics library – in our case <a href="http://paperjs.org" target="_blank">Paper.js</a> – within an AutoCAD application. The main “trick” to this is going to be getting the data from the HTML page into AutoCAD, which we’ll do <a href="http://through-the-interface.typepad.com/through_the_interface/2013/05/returning-data-from-net-to-javascript-inside-autocad.html" target="_blank">by</a> <a href="http://through-the-interface.typepad.com/through_the_interface/2013/05/complementing-autocads-javascript-api-using-net.html" target="_blank">extending</a> <a href="http://through-the-interface.typepad.com/through_the_interface/2013/04/under-the-hood-autocads-javascript-api.html" target="_blank">AutoCAD’s shaping layer</a>. Bear in mind that this code will work with AutoCAD 2015, but I can’t guarantee it will do so with 2014 (the JavaScript API was very much a “preview” in that release).</p>  <p>Something I should say, right off the bat, is that the samples you’ll see in the coming posts each have different origins, whether being based on different SDK samples or just from me coding them at different times. So – despite some effort from my side – there will be inconsistencies: some use jQuery, some do not, some have JavaScript embedded in the HTML page while others only use external files.</p>  <p>The samples all use some common approaches – especially with the AutoCAD-resident code – but you shouldn’t take my samples as “best practice” for working with HTML/JavaScript as much as demonstrations of possibilities.</p>  <p>As the main HTML/CSS/JavaScript code is all hosted on my blog – and can be accessed there by the application – let’s start with the piece that you’ll need to build into a local, AutoCAD-resident .NET DLL. You can also download the various files and place them in your DLL folder and load them locally by uncommenting a few lines of code. In fact, this is the main way I’ve been developing/testing this code, which is why I permitted myself to omit the code we saw in <a href="http://through-the-interface.typepad.com/through_the_interface/2014/04/adding-a-web-page-as-a-document-tab-in-autocad-2015-using-net.html" target="_blank">this previous post</a> to check whether a URL is valid and loadable before trying to load the HTML page it points to.</p>  <p>Our C# code has ended up doing a lot more that I initially expected it to – please don’t be put off by its length. (If the details don’t interest you, please do scroll down to check out the embedded <a href="http://youtu.be/cH7iReGX1BM" target="_blank">YouTube video with the code in action</a>.)</p>  <p>It implements a couple of commands to load the web-page into an HTML-hosting <a href="http://through-the-interface.typepad.com/through_the_interface/2013/03/implementing-an-autocad-palette-using-html5-and-javascript.html" target="_blank">palette</a> or <a href="http://through-the-interface.typepad.com/through_the_interface/2014/04/adding-a-web-page-as-a-document-tab-in-autocad-2015-using-net.html" target="_blank">document</a> (called PAPER and PAPDOC, respectively) and also defines a function that will be called from our JavaScript code – via an extension to the Shaping Layer, more on that later – with the Paper.js project encoded as a JSON string passed in as an argument.</p>  <p>This function – which is tagged with the JavaScriptCallback attribute making it callable from JavaScript – extracts the “path” data from the JSON file and generates corresponding Polyline entities that get added to a new block which gets inserted into the active document (or drawing document that launched the initial command it in the case where the HTML page is loaded into its own document window). A lot of the work was to make sure we create the block at the right size – both based on the extents of the paths we get from Paper.js but also the current zoom factor in AutoCAD – and that it’s centered on the cursor. The INSERT command will let you scale and rotate, but I wanted the initial size and position to make some sense.</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.ApplicationServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Runtime;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Windows;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Newtonsoft.Json.Linq;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System.IO;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System.Reflection;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">namespace</span> JavaScriptExtender</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160; <span style="color: blue">public</span> <span style="color: blue">class</span> <span style="color: #2b91af">Commands</span></p>    <p style="margin: 0px">&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: #2b91af">PaletteSet</span> _pps = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">static</span> <span style="color: #2b91af">Document</span> _launchDoc = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">static</span> <span style="color: blue">double</span> _fac;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">JavaScriptCallback</span>(<span style="color: #a31515">&quot;CreatePath&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">string</span> CreatePath(<span style="color: blue">string</span> jsonArgs)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> dm = <span style="color: #2b91af">Application</span>.DocumentManager;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doc = GetActiveDocument(dm);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we didn't find a document, return</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (doc == <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: #a31515">&quot;&quot;</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Lock the document, as we will be modifying it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> dl = doc.LockDocument())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> db = doc.Database;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Unescape the string and remove surrounding quotes</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (could use a less manual approach for this, but hey)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> str = jsonArgs.Replace(<span style="color: #a31515">&quot;\\\&quot;&quot;</span>, <span style="color: #a31515">&quot;\&quot;&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (str.StartsWith(<span style="color: #a31515">&quot;\&quot;&quot;</span>))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; str = str.Substring(1);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (str.EndsWith(<span style="color: #a31515">&quot;\&quot;\n&quot;</span>))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; str = str.Remove(str.Length - 2);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Parse the JSON to extract the info we want</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> a = <span style="color: #2b91af">JArray</span>.Parse(str);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> kids = a[0][1][<span style="color: #a31515">&quot;children&quot;</span>];</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (kids == <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: #a31515">&quot;&quot;</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We'll collect Polylines in a collection</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> paths = <span style="color: blue">new</span> <span style="color: #2b91af">DBObjectCollection</span>();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Aggregate the various vertices in a single point</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// that we divide by the number of points to get the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// mean (the centroid of the shape)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> totalPoints = 0;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> total = <span style="color: #2b91af">Point3d</span>.Origin;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Also collect the bounding box of the polyline</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ext = <span style="color: blue">new</span> <span style="color: #2b91af">Extents3d</span>();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create our Polylines relative to WCS</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (we'll transform them later, once we've</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// collected the centroid)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> plane = <span style="color: blue">new</span> <span style="color: #2b91af">Plane</span>(<span style="color: #2b91af">Point3d</span>.Origin, <span style="color: #2b91af">Vector3d</span>.ZAxis);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pathNum = 0;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: blue">var</span> path <span style="color: blue">in</span> kids)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the next path</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> p = path[1];</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We currently only care about the segments, but</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// could also use the other information</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (linewidth, etc.)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> segments = p[<span style="color: #a31515">&quot;segments&quot;</span>];</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> width = p[<span style="color: #a31515">&quot;strokeWidth&quot;</span>];</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> cap = p[<span style="color: #a31515">&quot;strokeCap&quot;</span>];</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> join = p[<span style="color: #a31515">&quot;strokeJoin&quot;</span>];</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pl = <span style="color: blue">new</span> <span style="color: #2b91af">Polyline</span>();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> last = <span style="color: #2b91af">Point3d</span>.Origin;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> segNum = 0;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: blue">var</span> seg <span style="color: blue">in</span> segments)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Points are grouped in sets of 3 (although the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// first 3 are together and then the next 2 plus</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// one previous point make up the groups)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (segNum &gt; 0 &amp;&amp; segNum % 2 == 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get our 3 points - we don't care about the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// tangent information as we'll just construct</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// GeArcs instead</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pt1 = seg.Previous.Previous[0];</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pt2 = seg.Previous[0];</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pt3 = seg[0];</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create corresponding Point3d objects</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> start =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>((<span style="color: blue">double</span>)pt1[0], -(<span style="color: blue">double</span>)pt1[1], 0);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> mid =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>((<span style="color: blue">double</span>)pt2[0], -(<span style="color: blue">double</span>)pt2[1], 0);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> end =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>((<span style="color: blue">double</span>)pt3[0], -(<span style="color: blue">double</span>)pt3[1], 0);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; last = end;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Include our vertices in the extents</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (the end point is the start of the next -</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// we'll use the last variable to get the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// last end point)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ext.AddPoint(start);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ext.AddPoint(mid);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Aggregate all the start points so we can get</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// the average at the end</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; total = start + total.GetAsVector();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; totalPoints++;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create a CircularArc3d</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ca = <span style="color: blue">new</span> <span style="color: #2b91af">CircularArc3d</span>(start, mid, end);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Calculate the bulge factor using it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> b =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Math</span>.Tan(0.25 * (ca.EndAngle - ca.StartAngle)) *</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ca.Normal.Z;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Add our vertex</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pl.AddVertexAt(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pl.NumberOfVertices,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ca.StartPoint.Convert2d(plane),</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; b, 0, 0</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; segNum++;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Add the final vertex</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pl.AddVertexAt(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pl.NumberOfVertices, last.Convert2d(plane), 0, 0, 0</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Add the last vertex for completeness</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; total = last + total.GetAsVector();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; totalPoints++;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Also to our extents object</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ext.AddPoint(last);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Add our Polyline to the path collection</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; paths.Add(pl);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pathNum++;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Now we can get the average vertex to make that</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// the insertion point (i.e. the centroid)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; total = total / totalPoints;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We want the geometry to be created based on the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// current zoom factor. So let's try to get that</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// from the Editor (which will fail in HTML document</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// mode, hence the try-catch block)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> fac =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _launchDoc == <span style="color: blue">null</span> ? GetCurrentZoomFactor(doc) : _fac;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create a transformation to both displace the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// geometry - to use our centroid as the insertion</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// point - and to scale the geometry to be nice and</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// small (the INSERT command allows scaling upwards)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> totVec = total.GetAsVector();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> diag = ext.MaxPoint - ext.MinPoint;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> mat =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Matrix3d</span>.Scaling(fac / diag.Length, <span style="color: #2b91af">Point3d</span>.Origin).</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; PostMultiplyBy(<span style="color: #2b91af">Matrix3d</span>.Displacement(-totVec));</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we have some Polylines, add them to our block</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// or the current space</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (paths.Count &gt; 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> blockRoot = <span style="color: #a31515">&quot;CLOUD&quot;</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">bool</span> createAndInsert = !<span style="color: #2b91af">String</span>.IsNullOrEmpty(blockRoot);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">string</span> blockName = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> tr = doc.TransactionManager.StartTransaction())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">BlockTableRecord</span> btr;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we're creating and inserting, starting by</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// creating the blank block definition</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (createAndInsert)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the block table, initially for read</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> bt =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">BlockTable</span>)tr.GetObject(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.BlockTableId, <span style="color: #2b91af">OpenMode</span>.ForRead</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Loop until we have a valid (unused) block name</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> num = 0;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">do</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; blockName = <span style="color: #2b91af">String</span>.Format(blockRoot + <span style="color: #a31515">&quot;{0}&quot;</span>, num);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; num++;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">while</span> (bt.Has(blockName));</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create our block definition, opening the block</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// table for write in order to add it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr = <span style="color: blue">new</span> <span style="color: #2b91af">BlockTableRecord</span>();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.Name = blockName;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bt.UpgradeOpen();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bt.Add(btr);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bt.DowngradeOpen();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(btr, <span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we're adding to the current space (rather than</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// a new block), just open it for write</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">BlockTableRecord</span>)tr.GetObject(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db.CurrentSpaceId, <span style="color: #2b91af">OpenMode</span>.ForWrite</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Loop through our collection, adding all the entities</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (after transforming them for displacement and scale)</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// and disposing of anything else (should be nothing)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">DBObject</span> o <span style="color: blue">in</span> paths)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ent = o <span style="color: blue">as</span> <span style="color: #2b91af">Entity</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ent != <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ent.TransformBy(mat);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(ent);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(ent, <span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; o.Dispose();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// At this stage we're done with the drawing changes,</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// so commit the transaction</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Our Editor-based code is wrapped in a try-catch</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// block as accessing the Editor will cause</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// an exception to be thrown in HTML document mode</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Let's try to insert our block, if we created one</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (createAndInsert &amp;&amp; !<span style="color: #2b91af">String</span>.IsNullOrEmpty(blockName))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If running in our own document window,</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// activate the associated drawing first</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (dm.MdiActiveDocument != doc)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; dm.MdiActiveDocument = doc;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We'll use SendStringToExecute() as it works</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// well for these purposes</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.SendStringToExecute(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;_.-INSERT &quot;</span> + blockName + <span style="color: #a31515">&quot;\n&quot;</span>, <span style="color: blue">true</span>, <span style="color: blue">true</span>, <span style="color: blue">false</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we're adding to the current space, just</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// have the screen redraw to show the results</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.UpdateScreen();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">catch</span> { }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: #a31515">&quot;{\&quot;retCode\&quot;:0}&quot;</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">static</span> <span style="color: #2b91af">Matrix3d</span> Dcs2Wcs(<span style="color: #2b91af">AbstractViewTableRecord</span> v)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Matrix3d</span>.Rotation(-v.ViewTwist, v.ViewDirection, v.Target) *</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Matrix3d</span>.Displacement(v.Target - <span style="color: #2b91af">Point3d</span>.Origin) * </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Matrix3d</span>.PlaneToWorld(v.ViewDirection);</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Get the current amount of zoom - I probably shouldn't use</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// the term &quot;zoom factor&quot; as it tends to mean something else.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// But it's a factor - in drawing units - that shows how</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// zoomed into a model we are</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">static</span> <span style="color: blue">double</span> GetCurrentZoomFactor(<span style="color: #2b91af">Document</span> doc)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> fac = 0.0;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Let's try to get the Editor - will fail if called from</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// an HTML document</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the view and a diagonal vector across the extents</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> vtr = ed.GetCurrentView();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> vec = <span style="color: blue">new</span> <span style="color: #2b91af">Vector3d</span>(vtr.Width, vtr.Height, 0);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Capture the visible extents in an object</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> screenExt = <span style="color: blue">new</span> <span style="color: #2b91af">Extents3d</span>();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the centre of the screen in WCS and use it</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// with the diagonal vector to add the corners to the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// extents object</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ctr =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>(vtr.CenterPoint.X, vtr.CenterPoint.Y, 0);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> dcs = Dcs2Wcs(vtr);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; screenExt.AddPoint((ctr + 0.5 * vec).TransformBy(dcs));</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; screenExt.AddPoint((ctr - 0.5 * vec).TransformBy(dcs));</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Calculate the length of the diagonal in WCS</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// then return a tenth of that as our factor</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> diag2 =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (screenExt.MaxPoint - screenExt.MinPoint).Length;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; fac = diag2 / 10;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">catch</span> { }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> fac;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: #2b91af">Document</span> GetActiveDocument(<span style="color: #2b91af">DocumentCollection</span> dm)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we're called from an HTML document, the active</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// document may be null</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doc = dm.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (doc == <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc = _launchDoc;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> doc;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;PAPDOC&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">void</span> PaperDocument()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; _launchDoc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; _fac = GetCurrentZoomFactor(_launchDoc);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; _launchDoc.BeginDocumentClose +=</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (s, e) =&gt; { _launchDoc = <span style="color: blue">null</span>; };</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Application</span>.DocumentWindowCollection.AddDocumentWindow(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Paper.js Document&quot;</span>, GetHtmlPathPaper()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;PAPER&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">void</span> PaperPalette()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; _launchDoc = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; _pps =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ShowPalette(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; _pps,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Guid</span>(<span style="color: #a31515">&quot;B0B176D0-6402-4D1A-8D44-4CB2EA8F29C0&quot;</span>),</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;PAPER&quot;</span>,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Paper.js Example&quot;</span>,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; GetHtmlPathPaper()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Helper function to show a palette</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: #2b91af">PaletteSet</span> ShowPalette(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PaletteSet</span> ps, <span style="color: #2b91af">Guid</span> guid, <span style="color: blue">string</span> cmd, <span style="color: blue">string</span> title, <span style="color: #2b91af">Uri</span> uri</p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ps == <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ps = <span style="color: blue">new</span> <span style="color: #2b91af">PaletteSet</span>(cmd, guid);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ps.Visible)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> ps;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ps.Count != 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ps[0].PaletteSet.Remove(0);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ps.Add(title, uri);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ps.Visible = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> ps;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Helper function to get the path to our HTML files</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">static</span> <span style="color: blue">string</span> GetHtmlPath()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Use this approach if loading the HTML from the same</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// location as your .NET module</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//var asm = Assembly.GetExecutingAssembly();</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//return Path.GetDirectoryName(asm.Location) + &quot;\\&quot;;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: #a31515">&quot;http://through-the-interface.typepad.com/files/&quot;</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">static</span> <span style="color: #2b91af">Uri</span> GetHtmlPathPaper()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: blue">new</span> <span style="color: #2b91af">Uri</span>(GetHtmlPath() + <span style="color: #a31515">&quot;paperclouds.html&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">}</p> </div>  <p>Again, none of this is better than what we already have with the REVCLOUD command inside AutoCAD, but it does show the interoperability potential of an HTML/JavaScript app that generates geometry inside AutoCAD.</p>  <p>Here’s the code in action, generating a few revision clouds both from an AutoCAD-based palette and a separate document window (using a sample drawing borrowed from <a href="http://www.iammea.org/ggingras/cad115/gjdg_samples.htm" target="_blank">here</a>):</p>  <br /><iframe height="264" src="//www.youtube.com/embed/cH7iReGX1BM?rel=0" frameborder="0" width="470" allowfullscreen="allowfullscreen"></iframe>  <br />  <br />  <p>If you’re interested in the code that’s hosted on my blog and accessed from there, read on!</p>  <p>Here’s <a href="http://through-the-interface.typepad.com/files/paperclouds.html" target="_blank">the HTML page</a> that uses Paper.js to draw our clouds: the “Paperscript” code that does this is incredibly compact. The function at the bottom is one you’ll see in each of the samples in this series (and is a technique I borrowed from <a href="https://github.com/jdan/isomer/blob/master/test/test.js" target="_blank">the Isomer samples</a>) – it just goes through and generates a set of buttons dynamically based on the JavaScript “commands” that are in the code.</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">&lt;</span><span style="color: maroon">!doctype</span> <span style="color: red">html</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px"><span style="color: blue">&lt;</span><span style="color: maroon">html</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160; <span style="color: blue">&lt;</span><span style="color: maroon">head</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">meta</span> <span style="color: red">charset</span><span style="color: blue">=&quot;UTF-8&quot;&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">title</span><span style="color: blue">&gt;</span>Clouds<span style="color: blue">&lt;/</span><span style="color: maroon">title</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">link</span> <span style="color: red">rel</span><span style="color: blue">=&quot;stylesheet&quot;</span> <span style="color: red">href</span><span style="color: blue">=&quot;style.css&quot;&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">script</span> <span style="color: red">type</span><span style="color: blue">=&quot;text/javascript&quot;</span> <span style="color: red">src</span><span style="color: blue">=&quot;js/paper-full.min.js&quot;&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;/</span><span style="color: maroon">script</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">script</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: red">src</span><span style="color: blue">=&quot;http://app.autocad360.com/jsapi/v2/Autodesk.AutoCAD.js&quot;&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;/</span><span style="color: maroon">script</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">script</span> <span style="color: red">src</span><span style="color: blue">=&quot;js/acadext.js&quot;&gt;&lt;/</span><span style="color: maroon">script</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">script</span> <span style="color: red">type</span><span style="color: blue">=&quot;text/paperscript&quot;</span> <span style="color: red">canvas</span><span style="color: blue">=&quot;canvas&quot;&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; function init() {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; project.currentStyle = {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; strokeColor: 'black',</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; strokeWidth: 5,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; strokeJoin: 'round',</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; strokeCap: 'round'</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; };</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; // The user has to drag the mouse at least 30pt before the</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; // mouse drag event is fired:</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; tool.minDistance = 30;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; var path;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; function onMouseDown(event) {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; path = new Path();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; path.add(event.point);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; function onMouseDrag(event) {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; path.arcTo(event.point, true);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; function Commands() {}</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; Commands.clear = function () {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; project.activeLayer.removeChildren();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; var c = document.getElementById(&quot;canvas&quot;);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; var ctx = c.getContext(&quot;2d&quot;);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ctx.clearRect(0, 0, c.width, c.height);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; };</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; Commands.insert = function () {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; sendPathToAutoCAD(project.exportJSON());</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; };</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; (function () {</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; init();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; var canvas = document.getElementById('canvas');</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; canvas.width = window.innerWidth - 25,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; canvas.height = window.innerHeight - 65;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; var panel = document.getElementById('control');</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; for (var fn in Commands) {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; var button = document.createElement('div');</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; button.classList.add('cmd-btn');</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; button.innerHTML = fn;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; button.onclick = (function (fn) {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; return function () { fn(); };</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; })(Commands[fn]);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; panel.appendChild(button);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; panel.appendChild(document.createTextNode('\u00a0'));</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; })();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;/</span><span style="color: maroon">script</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160; <span style="color: blue">&lt;/</span><span style="color: maroon">head</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160; <span style="color: blue">&lt;</span><span style="color: maroon">body</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">canvas</span> <span style="color: red">id</span><span style="color: blue">=&quot;canvas&quot;&gt;&lt;/</span><span style="color: maroon">canvas</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">&lt;</span><span style="color: maroon">div</span> <span style="color: red">id</span><span style="color: blue">=&quot;control&quot;&gt;&lt;/</span><span style="color: maroon">div</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px">&#160; <span style="color: blue">&lt;/</span><span style="color: maroon">body</span><span style="color: blue">&gt;</span></p>    <p style="margin: 0px"><span style="color: blue">&lt;/</span><span style="color: maroon">html</span><span style="color: blue">&gt;</span></p> </div>  <p>Here’s <a href="http://through-the-interface.typepad.com/files/js/acadext.js" target="_blank">the extension to the Shaping Layer</a> that is called from this code, which just passes through the provided JSON directly as an argument (and in reality won’t care very much about the result).</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">function</span> sendPathToAutoCAD(jsonArgs) {</p>    <p style="margin: 0px">&#160; <span style="color: blue">var</span> jsonResponse =</p>    <p style="margin: 0px">&#160;&#160;&#160; exec(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; JSON.stringify({</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; functionName: <span style="color: #a31515">'CreatePath'</span>,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; invokeAsCommand: <span style="color: blue">false</span>,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; functionParams: jsonArgs</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; })</p>    <p style="margin: 0px">&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160; <span style="color: blue">var</span> jsonObj = JSON.parse(jsonResponse);</p>    <p style="margin: 0px">&#160; <span style="color: blue">if</span> (jsonObj.retCode !== Acad.ErrorStatus.eJsOk) {</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">throw</span> Error(jsonObj.retErrorString);</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">&#160; <span style="color: blue">return</span> jsonObj.result;</p>    <p style="margin: 0px">}</p> </div>  <p>And for completeness, here’s <a href="http://through-the-interface.typepad.com/files/style.css" target="_blank">the CSS</a> that (mainly) shows the nice buttons at the bottom:</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: maroon">#canvas</span> {</p>    <p style="margin: 0px">&#160; <span style="color: red">display</span>: <span style="color: blue">block</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">margin</span>: <span style="color: blue">0</span> <span style="color: blue">auto</span>;</p>    <p style="margin: 0px">}</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: maroon">#control</span> {</p>    <p style="margin: 0px">&#160; <span style="color: red">position</span>: <span style="color: blue">absolute</span>;</p>    <p style="margin: 0px">}</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: maroon">.cmd-btn</span> {</p>    <p style="margin: 0px">&#160; <span style="color: red">font-family</span>: <span style="color: blue">'Helvetica Neue'</span>, <span style="color: blue">Helvetica</span>, <span style="color: blue">Arial</span>, <span style="color: blue">sans-serif</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">font-size</span>: <span style="color: blue">24px</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">border</span>: <span style="color: blue">3px</span> <span style="color: blue">solid</span> <span style="color: blue">#555</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">border-radius</span>: <span style="color: blue">5px</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">color</span>: <span style="color: blue">#555</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">background</span>: <span style="color: blue">transparent</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">text-transform</span>: <span style="color: blue">uppercase</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">padding</span>: <span style="color: blue">15px</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">width</span>: <span style="color: blue">120px</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">text-align</span>: <span style="color: blue">center</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">display</span>: <span style="color: blue">inline</span></p>    <p style="margin: 0px">}</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: maroon">.cmd-btn:hover</span> {</p>    <p style="margin: 0px">&#160; <span style="color: red">cursor</span>: <span style="color: blue">pointer</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">color</span>: <span style="color: blue">#fff</span>;</p>    <p style="margin: 0px">&#160; <span style="color: red">background-color</span>: <span style="color: blue">#555</span>;</p>    <p style="margin: 0px">}</p> </div>  <p>That’s it for the initial Paper.js and AutoCAD integration. At some point I’d quite like to see investigate taking 2D geometry from AutoCAD and manipulating it using Paper.js (it has some nice path simplification capabilities for hand-drawn curves, for instance).</p>  <p>But next up is a look at integrating Isomer to display 2D isometric views of 3D AutoCAD geometry.</p>
