---
layout: "post"
title: "Attaching geo-location data to an AutoCAD drawing using .NET"
date: "2014-06-26 11:02:59"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Geo-location"
  - "Geometry"
  - "Graphics system"
original_url: "https://www.keanw.com/2014/06/attaching-geo-location-data-to-an-autocad-drawing-using-net.html "
typepad_basename: "attaching-geo-location-data-to-an-autocad-drawing-using-net"
typepad_status: "Publish"
---

<p>AutoCAD’s geo-location API is a topic I’ve been meaning (and even promising) to cover for some time now. So here we are. :-)</p>  <p>The below code sample is based on one shown at ADN’s DevDays tour at the end of 2013 – for the AutoCAD 2014 release – but the API ended up not being fully usable (at least as far as I recall: someone should jump in and correct me if I have this wrong) until the 2015 release.</p>  <p>I’ve taken the opportunity to use Editor.Command() to call a couple of commands synchronously – to turn on the GEOMAP information and to zoom to a circle that we create around our location – now that this particular API is available.</p>  <p>Here’s the C# code implementing the IGR command:</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.ApplicationServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Runtime;</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px"><span style="color: blue">namespace</span> GeoLocationAPI</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#0160; <span style="color: blue">public</span> <span style="color: blue">class</span> <span style="color: #2b91af">Commands</span></p>    <p style="margin: 0px">&#0160; {</p>    <p style="margin: 0px">&#0160;&#0160;&#0160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;IGR&quot;</span>)]</p>    <p style="margin: 0px">&#0160;&#0160;&#0160; <span style="color: blue">public</span> <span style="color: blue">void</span> InsertGeoRef()</p>    <p style="margin: 0px">&#0160;&#0160;&#0160; {</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">if</span> (doc == <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> db = doc.Database;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> msId = <span style="color: #2b91af">SymbolUtilityServices</span>.GetBlockModelSpaceId(db);</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Check whether the drawing already has geolocation data</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">bool</span> hasGeoData = <span style="color: blue">false</span>;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">try</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; {</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> gdId = db.GeoDataObject;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; hasGeoData = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; }</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">catch</span> { }</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">if</span> (hasGeoData)</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; {</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Report and return: could also open the object for</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// write and modify its properties, of course</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ed.WriteMessage(<span style="color: #a31515">&quot;\nDrawing already has geo-location data!&quot;</span>);</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; }</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Let&#39;s create some geolocation data for this drawing,</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// using a handy method to add it to the modelspace</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// (it gets added to the extension dictionary)</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> data = <span style="color: blue">new</span> <span style="color: #2b91af">GeoLocationData</span>();</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; data.BlockTableRecordId = msId;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; data.PostToDb();</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// We&#39;re going to define our geolocation in terms of</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// latitude/longitude using the Mercator projection</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// http://en.wikipedia.org/wiki/Mercator_projection</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; data.CoordinateSystem = <span style="color: #a31515">&quot;WORLD-MERCATOR&quot;</span>;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; data.TypeOfCoordinates = <span style="color: #2b91af">TypeOfCoordinates</span>.CoordinateTypeGrid;</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Use the lat-long for La Tene, my local &quot;beach&quot;</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// (it&#39;s on a lake, after all :-)&#0160;&#0160;&#0160;&#0160;&#0160; </span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> geoPt = <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>(7.019438, 47.005247, 0);</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Transform from a geographic to a modelspace point</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// and add the information to our geolocation data</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> wcsPt = data.TransformFromLonLatAlt(geoPt);</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; data.DesignPoint = wcsPt;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; data.ReferencePoint = geoPt;</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Let&#39;s launch the GEOMAP command to show our geographic</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// overlay</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; ed.Command(<span style="color: #a31515">&quot;_.GEOMAP&quot;</span>, <span style="color: #a31515">&quot;_AERIAL&quot;</span>);</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Now we&#39;ll add a circle around our location</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// and that will provide the extents for our zoom</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">using</span> (<span style="color: blue">var</span> tr = db.TransactionManager.StartTransaction())</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; {</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> ms =</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tr.GetObject(msId, <span style="color: #2b91af">OpenMode</span>.ForWrite) <span style="color: blue">as</span> <span style="color: #2b91af">BlockTableRecord</span>;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">if</span> (ms != <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// Add a red circle of 7K units radius</span></p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// centred on our point</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: blue">var</span> circle = <span style="color: blue">new</span> <span style="color: #2b91af">Circle</span>(wcsPt, <span style="color: #2b91af">Vector3d</span>.ZAxis, 7000);</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; circle.ColorIndex = 1;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ms.AppendEntity(circle);</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tr.AddNewlyCreatedDBObject(circle, <span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tr.Commit();</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; }</p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: green">// And we&#39;ll zoom to the circle&#39;s extents</span></p>    <p style="margin: 0px">&#0160;</p>    <p style="margin: 0px">&#0160;&#0160;&#0160;&#0160;&#0160; ed.Command(<span style="color: #a31515">&quot;_.ZOOM&quot;</span>, <span style="color: #a31515">&quot;_OBJECT&quot;</span>, <span style="color: #a31515">&quot;_L&quot;</span>, <span style="color: #a31515">&quot;&quot;</span>);</p>    <p style="margin: 0px">&#0160;&#0160;&#0160; }</p>    <p style="margin: 0px">&#0160; }</p>    <p style="margin: 0px">}</p> </div>  <p>When we run the code, we will see our geographic location gets set to that of La Tene (a place close to my home that I’ve <a href="http://through-the-interface.typepad.com/through_the_interface/2010/08/capturing-a-point-cloud-of-a-monument-using-photosynth.html" target="_blank">mentioned</a> <a href="http://through-the-interface.typepad.com/through_the_interface/2010/10/capturing-a-point-cloud-of-a-monument-using-a-laser-scanner.html" target="_blank">before</a>) and a circle is created with a radius of 7,000 units (maybe that’s 7km? it looks about right) around our location:</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201a73de0a3ca970d-pi" target="_blank"><img alt="GeoLocation in action" border="0" height="294" src="/assets/image_574424.jpg" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 20px auto; display: block; padding-right: 0px; border-top-width: 0px" title="GeoLocation in action" width="468" /></a></p>  <p>In case you’re wondering, the choice of 7000 was arbitrary: it made the map look good with the fields of <a href="http://en.wikipedia.org/wiki/Rapeseed" target="_blank">oilseed rape</a> at the upper left (setting a larger radius caused a different, less colourful set of imagery to be loaded).</p>  <p>A quick word of warning about the TransformFromLonLatAlt() method: it assumes the Point3d passed in has <em>longitude, latitude, altitude</em> in the x, y, z fields <strong>in that order</strong>. I made the mistake of copying the lat-long values directly across from Google Maps (not realising I needed long-lat), and found that AutoCAD zoomed into <a href="https://www.google.com/maps/place/7%C2%B001&#39;13.8%22N+47%C2%B000&#39;18.5%22E/@7.0376222,46.9998708,14z/data=!4m2!3m1!1s0x0:0x0" target="_blank">a location about 1km inside Ethiopia’s border with Somalia</a>. Seems like the kind of thing someone could make a fun activity out of: send a letter to the address on the “opposite” side of the planet of your own (except it isn’t opposite, of course, but I honestly don’t know the best way to describe what happens when you swap latitude with longitude).</p>  <p>There’s more I want to do with the geo-location API inside AutoCAD: I want to be able to clip an image and access/modify its properties programmatically, for instance. We’ll take a look at that in an upcoming post. Also, do let me know if you have additional geo-location tasks you’d like to see performed, and I’ll see what’s possible.</p>
