---
layout: "post"
title: "Creating an AutoCAD layout with custom plot and viewport settings using .NET"
date: "2015-11-03 17:39:26"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Drawing structure"
  - "Plotting"
original_url: "https://www.keanw.com/2015/11/creating-an-autocad-layout-with-custom-plot-and-viewport-settings-using-net.html "
typepad_basename: "creating-an-autocad-layout-with-custom-plot-and-viewport-settings-using-net"
typepad_status: "Publish"
---

<p>This request from Thomas Longnecker languished in my inbox for several weeks before I finally found the time to work on it.</p>  <blockquote>   <p>It would be tremendously helpful to me if you could give an explanatory example of how to: Create a new layout, add a page-setup with plot-settings and then either delete the default viewport and create a new one or possible change the default viewport. </p>    <p>[…]</p>    <p>Within the newly created layouts I needed to set some of the general Plot setting, mainly Paper size and Plot style table.</p>    <p>Some of the main things for the viewport was to set the viewing area and plot scale and then lock it.</p> </blockquote>  <p>It’s clearly an area that’s of general interest – many people need to automate the creation and configuration of layout tabs – but it’s not an area I’ve spend much time looking at, myself. In the end I managed to put something together that works well – once again with a fair amount of help from the <a href="http://help.autodesk.com/view/ACD/2016/ENU/?guid=GUID-5FA86EF3-DEFD-4256-BB1C-56DAC32BD868" target="_blank">online</a> <a href="http://help.autodesk.com/view/ACD/2016/ENU/?guid=GUID-56BD3247-471C-4471-A238-FFDFDC3BD2E4" target="_blank">documentation</a> – and is hopefully fairly easy to understand: I’ve done my best to implement extension methods that should be useful for people in other contexts, which has helped keep the command implementation nice and succinct.</p>  <p>Here’s the C# code:</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.ApplicationServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Runtime;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">namespace</span> LayoutCreation</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">class</span> <span style="color: #2b91af">Extensions</span></p>    <p style="margin: 0px">&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Reverses the order of the X and Y properties of a Point2d.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;flip&quot;&gt;</span><span style="color: green">Boolean indicating whether to reverse or not.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;returns&gt;</span><span style="color: green">The original Point2d or the reversed version.</span><span style="color: gray">&lt;/returns&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: #2b91af">Point2d</span> Swap(<span style="color: blue">this</span> <span style="color: #2b91af">Point2d</span> pt, <span style="color: blue">bool</span> flip = <span style="color: blue">true</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> flip ? <span style="color: blue">new</span> <span style="color: #2b91af">Point2d</span>(pt.Y, pt.X) : pt;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Pads a Point2d with a zero Z value, returning a Point3d.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;pt&quot;&gt;</span><span style="color: green">The Point2d to pad.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;returns&gt;</span><span style="color: green">The padded Point3d.</span><span style="color: gray">&lt;/returns&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: #2b91af">Point3d</span> Pad(<span style="color: blue">this</span> <span style="color: #2b91af">Point2d</span> pt)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>(pt.X, pt.Y, 0);</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Strips a Point3d down to a Point2d by simply ignoring the Z ordinate.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;pt&quot;&gt;</span><span style="color: green">The Point3d to strip.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;returns&gt;</span><span style="color: green">The stripped Point2d.</span><span style="color: gray">&lt;/returns&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: #2b91af">Point2d</span> Strip(<span style="color: blue">this</span> <span style="color: #2b91af">Point3d</span> pt)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: blue">new</span> <span style="color: #2b91af">Point2d</span>(pt.X, pt.Y);</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Creates a layout with the specified name and optionally makes it current.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;name&quot;&gt;</span><span style="color: green">The name of the viewport.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;select&quot;&gt;</span><span style="color: green">Whether to select it.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;returns&gt;</span><span style="color: green">The ObjectId of the newly created viewport.</span><span style="color: gray">&lt;/returns&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: #2b91af">ObjectId</span> CreateAndMakeLayoutCurrent(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">this</span> <span style="color: #2b91af">LayoutManager</span> lm, <span style="color: blue">string</span> name, <span style="color: blue">bool</span> select = <span style="color: blue">true</span></p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// First try to get the layout</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> id = lm.GetLayoutId(name);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If it doesn't exist, we create it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (!id.IsValid)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; id = lm.CreateLayout(name);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// And finally we select it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (select)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lm.CurrentLayout = name;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> id;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Applies an action to the specified viewport from this layout.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Creates a new viewport if none is found withthat number.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;tr&quot;&gt;</span><span style="color: green">The transaction to use to open the viewports.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;vpNum&quot;&gt;</span><span style="color: green">The number of the target viewport.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;f&quot;&gt;</span><span style="color: green">The action to apply to each of the viewports.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">void</span> ApplyToViewport(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">this</span> <span style="color: #2b91af">Layout</span> lay, <span style="color: #2b91af">Transaction</span> tr, <span style="color: blue">int</span> vpNum, <span style="color: #2b91af">Action</span>&lt;<span style="color: #2b91af">Viewport</span>&gt; f</p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> vpIds = lay.GetViewports();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Viewport</span> vp = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">ObjectId</span> vpId <span style="color: blue">in</span> vpIds)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> vp2 = tr.GetObject(vpId, <span style="color: #2b91af">OpenMode</span>.ForWrite) <span style="color: blue">as</span> <span style="color: #2b91af">Viewport</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (vp2 != <span style="color: blue">null</span> &amp;&amp; vp2.Number == vpNum)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We have found our viewport, so call the action</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp = vp2;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">break</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (vp == <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We have not found our viewport, so create one</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> btr =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">BlockTableRecord</span>)tr.GetObject(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.BlockTableRecordId, <span style="color: #2b91af">OpenMode</span>.ForWrite</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp = <span style="color: blue">new</span> <span style="color: #2b91af">Viewport</span>();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Add it to the database</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(vp);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(vp, <span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Turn it - and its grid - on</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp.On = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp.GridOn = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Finally we call our function on it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; f(vp);&#160;&#160;&#160;&#160;&#160; </p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Apply plot settings to the provided layout.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;pageSize&quot;&gt;</span><span style="color: green">The canonical media name for our page size.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;styleSheet&quot;&gt;</span><span style="color: green">The pen settings file (ctb or stb).</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;devices&quot;&gt;</span><span style="color: green">The name of the output device.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">void</span> SetPlotSettings(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">this</span> <span style="color: #2b91af">Layout</span> lay, <span style="color: blue">string</span> pageSize, <span style="color: blue">string</span> styleSheet, <span style="color: blue">string</span> device</p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> ps = <span style="color: blue">new</span> <span style="color: #2b91af">PlotSettings</span>(lay.ModelType))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ps.CopyFrom(lay);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> psv = <span style="color: #2b91af">PlotSettingsValidator</span>.Current;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Set the device</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> devs = psv.GetPlotDeviceList();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (devs.Contains(device))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; psv.SetPlotConfigurationName(ps, device, <span style="color: blue">null</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; psv.RefreshLists(ps);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Set the media name/size</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> mns = psv.GetCanonicalMediaNameList(ps);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (mns.Contains(pageSize))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; psv.SetCanonicalMediaName(ps, pageSize);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Set the pen settings</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ssl = psv.GetPlotStyleSheetList();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ssl.Contains(styleSheet))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; psv.SetCurrentStyleSheet(ps, styleSheet);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Copy the PlotSettings data back to the Layout</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> upgraded = <span style="color: blue">false</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (!lay.IsWriteEnabled)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.UpgradeOpen();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; upgraded = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.CopyFrom(ps);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (upgraded)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.DowngradeOpen();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Determine the maximum possible size for this layout.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;returns&gt;</span><span style="color: green">The maximum extents of the viewport on this layout.</span><span style="color: gray">&lt;/returns&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: #2b91af">Extents2d</span> GetMaximumExtents(<span style="color: blue">this</span> <span style="color: #2b91af">Layout</span> lay)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If the drawing template is imperial, we need to divide by</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// 1&quot; in mm (25.4)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> div = lay.PlotPaperUnits == <span style="color: #2b91af">PlotPaperUnit</span>.Inches ? 25.4 : 1.0;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We need to flip the axes if the plot is rotated by 90 or 270 deg</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doIt =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.PlotRotation == <span style="color: #2b91af">PlotRotation</span>.Degrees090 ||</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.PlotRotation == <span style="color: #2b91af">PlotRotation</span>.Degrees270;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the extents in the correct units and orientation</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> min = lay.PlotPaperMargins.MinPoint.Swap(doIt) / div;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> max =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (lay.PlotPaperSize.Swap(doIt) -</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.PlotPaperMargins.MaxPoint.Swap(doIt).GetAsVector()) / div;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: blue">new</span> <span style="color: #2b91af">Extents2d</span>(min, max);</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Sets the size of the viewport according to the provided extents.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;ext&quot;&gt;</span><span style="color: green">The extents of the viewport on the page.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;fac&quot;&gt;</span><span style="color: green">Optional factor to provide padding.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">void</span> ResizeViewport(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">this</span> <span style="color: #2b91af">Viewport</span> vp, <span style="color: #2b91af">Extents2d</span> ext, <span style="color: blue">double</span> fac = 1.0</p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vp.Width = (ext.MaxPoint.X - ext.MinPoint.X) * fac;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vp.Height = (ext.MaxPoint.Y - ext.MinPoint.Y) * fac;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vp.CenterPoint =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">Point2d</span>.Origin + (ext.MaxPoint - ext.MinPoint) * 0.5).Pad();</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> Sets the view in a viewport to contain the specified model extents.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;/summary&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;ext&quot;&gt;</span><span style="color: green">The extents of the content to fit the viewport.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: gray">///</span><span style="color: green"> </span><span style="color: gray">&lt;param name=&quot;fac&quot;&gt;</span><span style="color: green">Optional factor to provide padding.</span><span style="color: gray">&lt;/param&gt;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">static</span> <span style="color: blue">void</span> FitContentToViewport(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">this</span> <span style="color: #2b91af">Viewport</span> vp, <span style="color: #2b91af">Extents3d</span> ext, <span style="color: blue">double</span> fac = 1.0</p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Let's zoom to just larger than the extents</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vp.ViewCenter =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (ext.MinPoint + ((ext.MaxPoint - ext.MinPoint) * 0.5)).Strip();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the dimensions of our view from the database extents</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> hgt = ext.MaxPoint.Y - ext.MinPoint.Y;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> wid = ext.MaxPoint.X - ext.MinPoint.X;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We'll compare with the aspect ratio of the viewport itself</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (which is derived from the page size)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> aspect = vp.Width / vp.Height;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If our content is wider than the aspect ratio, make sure we</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// set the proposed height to be larger to accommodate the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// content</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (wid / hgt &gt; aspect)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; hgt = wid / aspect;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Set the height so we're exactly at the extents</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vp.ViewHeight = hgt;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Set a custom scale to zoom out slightly (could also</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// vp.ViewHeight *= 1.1, for instance)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vp.CustomScale *= fac;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">public</span> <span style="color: blue">class</span> <span style="color: #2b91af">Commands</span></p>    <p style="margin: 0px">&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;CL&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">void</span> CreateLayout()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (doc == <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> db = doc.Database;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ext = <span style="color: blue">new</span> <span style="color: #2b91af">Extents2d</span>();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> tr = db.TransactionManager.StartTransaction())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create and select a new layout tab</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> id = <span style="color: #2b91af">LayoutManager</span>.Current.CreateAndMakeLayoutCurrent(<span style="color: #a31515">&quot;NewLayout&quot;</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Open the created layout</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> lay = (<span style="color: #2b91af">Layout</span>)tr.GetObject(id, <span style="color: #2b91af">OpenMode</span>.ForWrite);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Make some settings on the layout and get its extents</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.SetPlotSettings(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//&quot;ISO_full_bleed_2A0_(1189.00_x_1682.00_MM)&quot;, // Try this big boy!</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;ANSI_B_(11.00_x_17.00_Inches)&quot;</span>,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;monochrome.ctb&quot;</span>,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;DWF6 ePlot.pc3&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ext = lay.GetMaximumExtents();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; lay.ApplyToViewport(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr, 2,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp =&gt;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Size the viewport according to the extents calculated when</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// we set the PlotSettings (device, page size, etc.)</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Use the standard 10% margin around the viewport</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (found by measuring pixels on screenshots of Layout1, etc.)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp.ResizeViewport(ext, 0.8);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Adjust the view so that the model contents fit</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ValidDbExtents(db.Extmin, db.Extmax))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp.FitContentToViewport(<span style="color: blue">new</span> <span style="color: #2b91af">Extents3d</span>(db.Extmin, db.Extmax), 0.9);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Finally we lock the view to prevent meddling</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vp.Locked = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Commit the transaction</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Zoom so that we can see our new layout, again with a little padding</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ed.Command(<span style="color: #a31515">&quot;_.ZOOM&quot;</span>, <span style="color: #a31515">&quot;_E&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ed.Command(<span style="color: #a31515">&quot;_.ZOOM&quot;</span>, <span style="color: #a31515">&quot;.7X&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ed.Regen();</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Returns whether the provided DB extents - retrieved from</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Database.Extmin/max - are &quot;valid&quot; or whether they are the default</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// invalid values (where the min's coordinates are positive and the</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// max coordinates are negative)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">bool</span> ValidDbExtents(<span style="color: #2b91af">Point3d</span> min, <span style="color: #2b91af">Point3d</span> max)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; !(min.X &gt; 0 &amp;&amp; min.Y &gt; 0 &amp;&amp; min.Z &gt; 0 &amp;&amp;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; max.X &lt; 0 &amp;&amp; max.Y &lt; 0 &amp;&amp; max.Z &lt; 0);</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">}</p>    <p style="margin: 0px">&#160;</p> </div>  <p>And here’s the CL command – for CreateLayout – in action.</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201b8d170dde1970c-pi"><img title="Create Layout" style="float: none; margin: 50px auto; display: block" alt="Create Layout" src="/assets/image_865035.jpg" width="508" height="516" /></a></p>  <p>From looking through the code you can see it does pretty much what Thomas was asking for: after creating the layout and setting the page size, plot settings table and a device, we then modify the viewport (after creating it, if viewport creation on layout creation isn’t specified in AutoCAD’s OPTIONS) to contain the extents of our database – with a little padding so that it’s not too tight. After all is done we then zoom to the extents and then with an additional .7X – again, to leave some padding.</p>  <p>All in all it seems to work pretty much as the manual creation process does, the advantage being you can tweak the code for your own purposes, of course. One area I know needs a little work is the extents for 3D viewports: ideally I’d project the model (or just the bounding box, if lazy) along the view direction to the XY plane… right now I’m just lopping off the Z coordinate, which is a bit lazy. I’ll try to add that capability in a future update.</p>  <p>Hopefully I haven’t missed anything else that’s significant: please do post a comment if you spot something.</p>  <p><strong><em>Update:</em></strong></p>  <p>Thanks to Parrish Husband for <a href="http://through-the-interface.typepad.com/through_the_interface/2015/11/creating-an-autocad-layout-with-custom-plot-and-viewport-settings-using-net.html#comment-2344499392" target="_blank">pointing out</a> an opportunity to streamline the code slightly. I went ahead and made the change, and took the opportunity to fix a bug I stumbled across where I tried to fit the viewport to the extents of an empty drawing. I’ve updated the code above.</p>
