---
layout: "post"
title: "Recreating the Star Wars opening crawl in AutoCAD using F# &ndash; Part 2"
date: "2015-01-07 10:42:39"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Drawing structure"
  - "F#"
  - "Graphics system"
  - "HTML"
  - "JavaScript"
original_url: "https://www.keanw.com/2015/01/recreating-the-star-wars-opening-crawl-in-autocad-using-f-part-2.html "
typepad_basename: "recreating-the-star-wars-opening-crawl-in-autocad-using-f-part-2"
typepad_status: "Publish"
---

<p>After introducing this series in the last post, today we’re going to address the first 3 items on our TODO list:</p>  <ol>   <li><strong>The initial blue text </strong></li>    <li><strong>The theme music </strong></li>    <li><strong>The star field </strong></li>    <li>The disappearing Star Wars logo </li>    <li>The crawling text </li> </ol>  <p>The following two items are fairly significant, in their own right, so they’ll each take a post of their own to complete. Oh, and I’ve thrown in a surprise item 6, which I’ll unveil when we implement the crawling text.</p>  <p>Before we dive in, it’s important to make some points about the code: because this is mainly just a bit of fun, this code hasn’t been generalised to work with any drawing and any view, etc. I’ve hardcoded a lot of values that just work on a specific drawing and on my system. The timing works well for me, but may be off when working on systems with different performance profiles. Mileage may vary, as they say.</p>  <p>That’s one reason I’m providing <a href="http://through-the-interface.typepad.com/files/StarWarsCrawl.dwg" target="_blank">a drawing with the appropriate views set up</a>. I originally planned on putting the layers in there, too, but then decided to create those at runtime (as it was simple to do so). I could have done that with the views, too, but it didn’t seem worth the extra effort.</p>  <p>Another thing I should mention: in my first run at this I used transient graphics to display the intro and crawl text. I then decided to switch to db-resident objects, as I thought I could place them on layers that I turn off when they’re no longer needed. I ended up finding that didn’t work – as I have a single transaction making all the drawing modifications in the command, and couldn’t find a way to have the graphics system reflect the pending database changes – so I went ahead and erased them instead. I decided to stick with db-resident rather than transient graphics, nonetheless, but using transient graphics remains a viable approach for this: the reason I’m not doing so isn’t especially significant.</p>  <p>With that, here’s a look at the code in this post running inside AutoCAD:</p>  <br /><iframe height="264" src="//www.youtube.com/embed/YqePBHPRjWs?rel=0&amp;showinfo=0" frameborder="0" width="470" allowfullscreen="allowfullscreen"></iframe>  <br />  <br />  <p>A few task-specific comments:</p>  <p><strong>1. The initial blue text </strong></p>  <p>This was straightforward to implement. I ended up creating MText with the font information embedded in the contents, rather than a separate style. This is mainly because it’s the approach I used for the crawl text, later on, which uses multiple fonts. Overkill for this text, of course, but it saves me creating the style.</p>  <p>We’re using the intro text to do a bunch of things, behind the scenes. It’s essentially our splash screen for doing things like downloading the MP3 file for the theme music, etc.</p>  <p><strong>2. The theme music </strong></p>  <p>I came across an online version of the crawl music accessed in <a href="http://timpietrusky.com/star-wars-opening-crawl-from-1977" target="_blank">this great HTML implementation of the opening crawl</a>. Seems like an ideal candidate for SWAPI integration, extending it beyond the single episode. :-) Here’s <a href="http://codepen.io/TimPietrusky/pen/eHGfj" target="_blank">the code associated with it</a>, if you want to take a look.</p>  <p>I found out that the System.Windows.Media namespace contains a MediaPlayer object that allows you to access/play an MP3 file via a URL. All that remained was to work out some of the timings related to the music – it starts at 8.5 second in, for instance – and apply these to the code. In this version of the code, the player stops either when the music finishes or when AutoCAD is closed, whichever happens first.</p>  <p><strong>3</strong><strong>. The star field </strong></p>  <ol><!--EndFragment--></ol>  <p>This was a fairly simple matter of generating a bunch of random numbers and using them to define stars. I didn’t want to pass around large numbers of AutoCAD objects, though – whether DBPoints or even Point3ds – so I used a list of F# tuples (with x and y values, each of which holds a float between 0 and 1) that later gets transformed into DBPoints somewhere in the screen space. Although for the surprise item 6 I extended that space to be twice as high as currently needed.</p>  <p>Here’s the F# code implementing our first pass at the EPISODE command:</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">module</span> StarWars.Crawler</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">open</span> Autodesk.AutoCAD.ApplicationServices</p>    <p style="margin: 0px"><span style="color: blue">open</span> Autodesk.AutoCAD.ApplicationServices.Core</p>    <p style="margin: 0px"><span style="color: blue">open</span> Autodesk.AutoCAD.DatabaseServices</p>    <p style="margin: 0px"><span style="color: blue">open</span> Autodesk.AutoCAD.Geometry</p>    <p style="margin: 0px"><span style="color: blue">open</span> Autodesk.AutoCAD.Runtime</p>    <p style="margin: 0px"><span style="color: blue">open</span> System</p>    <p style="margin: 0px"><span style="color: blue">open</span> System.Windows.Media</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// The intro music MP3 file</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> mp3 =</p>    <p style="margin: 0px">&#160; <span style="color: #a31515">&quot;http://s.cdpn.io/1202/Star_Wars_original_opening_crawl_1977.mp3&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// The layers we want to create as a list of (name, (r, g, b))</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> layers =</p>    <p style="margin: 0px">&#160; [</p>    <p style="margin: 0px">&#160;&#160;&#160; (<span style="color: #a31515">&quot;Stars&quot;</span>, (255, 255, 255));</p>    <p style="margin: 0px">&#160;&#160;&#160; (<span style="color: #a31515">&quot;Intro&quot;</span>, (75, 213, 238))</p>    <p style="margin: 0px">&#160; ]</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Create layers based on the provided names and colour values</span></p>    <p style="margin: 0px"><span style="color: green">// (only creates layers if they don't already exist... could be</span></p>    <p style="margin: 0px"><span style="color: green">// updated to make sure the layers are on/thawed and have the</span></p>    <p style="margin: 0px"><span style="color: green">// right colour values)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> createLayers (tr:Transaction) (db:Database) =</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> lt =</p>    <p style="margin: 0px">&#160;&#160;&#160; tr.GetObject(db.LayerTableId, OpenMode.ForWrite) :?&gt; LayerTable</p>    <p style="margin: 0px">&#160; layers |&gt;</p>    <p style="margin: 0px">&#160; List.iter (<span style="color: blue">fun</span> (name, (r, g, b)) <span style="color: blue">-&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">if</span> not(lt.Has(name)) <span style="color: blue">then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">let</span> lay = <span style="color: blue">new</span> LayerTableRecord()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; lay.Color &lt;-</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.Colors.Color.FromRgb(byte r, byte g, byte b)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; lay.Name &lt;- name</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; lt.Add(lay) |&gt; ignore</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(lay, <span style="color: blue">true</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Get a view by name</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> getView (tr:Transaction) (db:Database) (name:string) =</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> vt =</p>    <p style="margin: 0px">&#160;&#160;&#160; tr.GetObject(db.ViewTableId, OpenMode.ForRead) :?&gt; ViewTable</p>    <p style="margin: 0px">&#160; <span style="color: blue">if</span> vt.Has(name) <span style="color: blue">then</span></p>    <p style="margin: 0px">&#160;&#160;&#160; tr.GetObject(vt.[name], OpenMode.ForRead) :?&gt; ViewTableRecord</p>    <p style="margin: 0px">&#160; <span style="color: blue">else</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">null</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Add an entity to a block and a transaction</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> addToDatabase (tr:Transaction) (btr:BlockTableRecord) o =</p>    <p style="margin: 0px">&#160; btr.AppendEntity(o) |&gt; ignore</p>    <p style="margin: 0px">&#160; tr.AddNewlyCreatedDBObject(o, <span style="color: blue">true</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Flush the graphics for a particular document</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> refresh (doc:Document) =</p>    <p style="margin: 0px">&#160; doc.TransactionManager.QueueForGraphicsFlush()</p>    <p style="margin: 0px">&#160; doc.TransactionManager.FlushGraphics()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Transform between the Display and World Coordinate Systems</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> dcs2wcs (vtr:AbstractViewTableRecord) =</p>    <p style="margin: 0px">&#160; Matrix3d.Rotation(-vtr.ViewTwist, vtr.ViewDirection, vtr.Target) *</p>    <p style="margin: 0px">&#160; Matrix3d.Displacement(vtr.Target - Point3d.Origin) * </p>    <p style="margin: 0px">&#160; Matrix3d.PlaneToWorld(vtr.ViewDirection)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Poll until a music file has downloaded fully</span></p>    <p style="margin: 0px"><span style="color: green">// (could sleep or use a callback to avoid this being too</span></p>    <p style="margin: 0px"><span style="color: green">// CPU-intensive, but hey)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> <span style="color: blue">rec</span> waitForComplete (mp:MediaPlayer) =</p>    <p style="margin: 0px">&#160; <span style="color: blue">if</span> mp.DownloadProgress &lt; 1. <span style="color: blue">then</span></p>    <p style="margin: 0px">&#160;&#160;&#160; System.Windows.Forms.Application.DoEvents()</p>    <p style="margin: 0px">&#160;&#160;&#160; waitForComplete mp</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Poll until a specified delay has elapsed since start</span></p>    <p style="margin: 0px"><span style="color: green">// (could sleep or use a callback to avoid this being too</span></p>    <p style="margin: 0px"><span style="color: green">// CPU-intensive, but hey)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> <span style="color: blue">rec</span> waitForElapsed (start:DateTime) delay =</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> elapsed = DateTime.Now - start</p>    <p style="margin: 0px">&#160; <span style="color: blue">if</span> elapsed.Seconds &lt; delay <span style="color: blue">then</span></p>    <p style="margin: 0px">&#160;&#160;&#160; System.Windows.Forms.Application.DoEvents()</p>    <p style="margin: 0px">&#160;&#160;&#160; waitForElapsed start delay</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Create the intro text as an MText object relative to the view</span></p>    <p style="margin: 0px"><span style="color: green">// (has a parameter to the function doesn't execute when loaded...</span></p>    <p style="margin: 0px"><span style="color: green">// also has hardcoded values that make it view-specific)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> createIntro _ =</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> mt = <span style="color: blue">new</span> MText()</p>    <p style="margin: 0px">&#160; mt.Contents &lt;-</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #a31515">&quot;{\\fFranklin Gothic Book|b0|i0|c0|p34;&quot;</span> +</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: #a31515">&quot;A long time ago, in a galaxy far,\\Pfar away...}&quot;</span></p>    <p style="margin: 0px">&#160; mt.Layer &lt;- <span style="color: #a31515">&quot;Intro&quot;</span></p>    <p style="margin: 0px">&#160; mt.TextHeight &lt;- 0.5</p>    <p style="margin: 0px">&#160; mt.Width &lt;- 10.</p>    <p style="margin: 0px">&#160; mt.Normal &lt;- Vector3d.ZAxis</p>    <p style="margin: 0px">&#160; mt.TransformBy(Matrix3d.Displacement(<span style="color: blue">new</span> Vector3d(1., 6., 0.)))</p>    <p style="margin: 0px">&#160; mt</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Generate a quantity of randomly located stars... a list of (x,y)</span></p>    <p style="margin: 0px"><span style="color: green">// tuples where x and y are between 0 and 1. These will later</span></p>    <p style="margin: 0px"><span style="color: green">// get transformed into the relevant space (on the screen, etc.)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> locateStars quantity =</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: green">// Create our random number generator</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> ran = <span style="color: blue">new</span> System.Random()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: green">// Note: _ is only used to make sure this function gets</span></p>    <p style="margin: 0px">&#160; <span style="color: green">// executed when it is called... if we have no argument</span></p>    <p style="margin: 0px">&#160; <span style="color: green">// it's a value that doesn't require repeated execution</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> randomPoint _ =</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Get random values between 0 and 1 for our x and y coordinates</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; (ran.NextDouble(), ran.NextDouble())</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: green">// Local recursive function to create n stars at random</span></p>    <p style="margin: 0px">&#160; <span style="color: green">// locations (in the plane of the screen)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> <span style="color: blue">rec</span> randomStars n =</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">match</span> n <span style="color: blue">with</span></p>    <p style="margin: 0px">&#160;&#160;&#160; | 0 <span style="color: blue">-&gt;</span> []</p>    <p style="margin: 0px">&#160;&#160;&#160; | _ <span style="color: blue">-&gt;</span> (randomPoint 0.) :: randomStars (n-1)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: green">// Create the specified number of stars at random locations</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; randomStars quantity</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Take locations from 0-1 in X and Y and place them</span></p>    <p style="margin: 0px"><span style="color: green">// relative to the screen</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">let</span> putOnScreen wid hgt dcs (x, y) =</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: green">// We want to populate a space that's 2 screens high (so we</span></p>    <p style="margin: 0px">&#160; <span style="color: green">// can pan/rotate downwards at the end of the crawl), hence</span></p>    <p style="margin: 0px">&#160; <span style="color: green">// the additional multiplier on y</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> pt = <span style="color: blue">new</span> Point3d(wid * (x - 0.5), hgt * ((y * -1.5) + 0.5), 0.)</p>    <p style="margin: 0px">&#160; pt.TransformBy(dcs)&#160;&#160;&#160; </p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: green">// Commands to recreate the open crawl experience for a selected</span></p>    <p style="margin: 0px"><span style="color: green">// Star Wars episode</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">[&lt;CommandMethod(<span style="color: #a31515">&quot;EPISODE&quot;</span>)&gt;]</p>    <p style="margin: 0px"><span style="color: blue">let</span> episode() =</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: green">// Make sure the active document is valid before continuing</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160; <span style="color: blue">let</span> doc = Application.DocumentManager.MdiActiveDocument</p>    <p style="margin: 0px">&#160; <span style="color: blue">if</span> doc &lt;&gt; <span style="color: blue">null</span> <span style="color: blue">then</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> db = doc.Database</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> ed = doc.Editor</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Start our transaction and create the required layers</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">use</span> tr = doc.TransactionManager.StartTransaction()</p>    <p style="margin: 0px">&#160;&#160;&#160; createLayers tr db</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Get our special Initial and Crawl views</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> ivtr = getView tr db <span style="color: #a31515">&quot;Initial&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> cvtr = getView tr db <span style="color: #a31515">&quot;Crawl&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">if</span> ivtr = <span style="color: blue">null</span> || cvtr = <span style="color: blue">null</span> <span style="color: blue">then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\nPlease load StarWarsCrawl.dwg before running command.&quot;</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; doc.TransactionManager.EnableGraphicsFlush(<span style="color: blue">true</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> btr =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; tr.GetObject(doc.Database.CurrentSpaceId, OpenMode.ForWrite)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; :?&gt; BlockTableRecord</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Set the initial view: this gives us higher quality text</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; ed.SetCurrentView(ivtr)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// First we create the intro text</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> intro = createIntro ()</p>    <p style="margin: 0px">&#160;&#160;&#160; intro |&gt; addToDatabase tr btr</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Make sure the intro text is visible</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; doc |&gt; refresh</p>    <p style="margin: 0px">&#160;&#160;&#160; ed.UpdateScreen()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// We'll now perform a number of start-up tasks, while our</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// initial intro text is visible... we'll start vy recording</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// our start time, so we can synchronise our delay</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> start = DateTime.Now</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Get our view's DCS matrix</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> dcs = dcs2wcs(cvtr)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Create a host of stars at random screen positions</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; locateStars 1000 |&gt;</p>    <p style="margin: 0px">&#160;&#160;&#160; List.iter</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; (<span style="color: blue">fun</span> xy <span style="color: blue">-&gt;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">let</span> p = putOnScreen cvtr.Width cvtr.Height dcs xy</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">let</span> dbp = <span style="color: blue">new</span> DBPoint(p)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; dbp.Layer &lt;- <span style="color: #a31515">&quot;Stars&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; dbp |&gt; addToDatabase tr btr)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Open the intro music over the web</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">let</span> mp = <span style="color: blue">new</span> MediaPlayer()</p>    <p style="margin: 0px">&#160;&#160;&#160; mp.Open(<span style="color: blue">new</span> Uri(mp3))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Wait for the download to complete before playing it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; waitForComplete mp</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Have a minimum delay of 5 seconds showing the intro text</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; waitForElapsed start 5</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Start the audio at 8.5 seconds in</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; mp.Position &lt;- <span style="color: blue">new</span> TimeSpan(0, 0, 0, 8, 500)</p>    <p style="margin: 0px">&#160;&#160;&#160; mp.Play()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Switch to the crawl view: this will also change the</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// visual style from 2D Wireframe to Realistic</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; ed.SetCurrentView(cvtr)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Remove the intro text</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; intro.Erase()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; tr.Commit() <span style="color: green">// Commit the transaction</span></p> </div>  <p>That’s it for this part in the series. In the next part we’ll take a look at the code to show the disappearing Star Wars logo inside AutoCAD.</p>
