---
layout: "post"
title: "Testing whether a point is inside or above an AutoCAD solid using .NET"
date: "2015-07-20 14:42:07"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Selection"
  - "Solid modeling"
original_url: "https://www.keanw.com/2015/07/testing-whether-a-point-is-inside-or-above-an-autocad-solid-using-net.html "
typepad_basename: "testing-whether-a-point-is-inside-or-above-an-autocad-solid-using-net"
typepad_status: "Publish"
---

<p>Today’s post resulted from an internal discussion: Miroslav Schonauer – with the help of Jan Liska – put together some code for a recent consulting engagement that they felt was important to share with the community. They wanted to test point containment for a particular 3D solid, but also to test whether the selected point – if outside the solid – was above it.</p>  <p><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201b8d13aac38970c-pi" target="_blank"><img title="Selecting a point in a solid" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 20px auto; border-left: 0px; display: block; padding-right: 0px" border="0" alt="Selecting a point in a solid" src="/assets/image_889310.jpg" width="256" height="264" /></a></p>  <p>They achieved this using AutoCAD’s Brep API. Here is the C# they put together (with some minor, cosmetic edits from my side):</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.ApplicationServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.BoundaryRepresentation;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.EditorInput;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Runtime;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">namespace</span> BrepTest</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160; <span style="color: blue">public</span> <span style="color: blue">class</span> <span style="color: #2b91af">Commands</span></p>    <p style="margin: 0px">&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;PISO&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">void</span> PointInSolid()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> db = doc.Database;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Select Solid3d</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> peo = <span style="color: blue">new</span> <span style="color: #2b91af">PromptEntityOptions</span>(<span style="color: #a31515">&quot;\nSelect a 3D solid&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; peo.SetRejectMessage(<span style="color: #a31515">&quot;\nMust be a 3D solid.&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; peo.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">Solid3d</span>), <span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> per = ed.GetEntity(peo);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (per.Status != <span style="color: #2b91af">PromptStatus</span>.OK)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> tr = db.TransactionManager.StartTransaction())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Open the selected Solid3d</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> sol = tr.GetObject(per.ObjectId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">Solid3d</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (sol != <span style="color: blue">null</span>) <span style="color: green">// Should always be true</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; { </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create the sub-entity path to it</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ids = <span style="color: blue">new</span> <span style="color: #2b91af">ObjectId</span>[] { per.ObjectId };</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> path =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">FullSubentityPath</span>(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ids, <span style="color: blue">new</span> <span style="color: #2b91af">SubentityId</span>(<span style="color: #2b91af">SubentityType</span>.Null, <span style="color: #2b91af">IntPtr</span>.Zero)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Create a Brep from the path</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> brep = <span style="color: blue">new</span> <span style="color: #2b91af">Brep</span>(path))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">while</span> (<span style="color: blue">true</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Select point</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ppr = ed.GetPoint(<span style="color: #a31515">&quot;\nSelect a point&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ppr.Status != <span style="color: #2b91af">PromptStatus</span>.OK)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">break</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pt = ppr.Value;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// 1) Check point containment w.r.t selected solid</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pc = <span style="color: blue">new</span> <span style="color: #2b91af">PointContainment</span>();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> brepEnt = brep.GetPointContainment(pt, <span style="color: blue">out</span> pc))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;\nPt {0}: {1}&quot;</span>, pt, pc);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// 2) If Outside, check whether the solid is &quot;below&quot;:</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (pc == <span style="color: #2b91af">PointContainment</span>.Outside)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Fire a -Z Ray from the point to find if it hits the Brep</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ray = <span style="color: blue">new</span> <span style="color: #2b91af">Ray3d</span>(pt, -<span style="color: #2b91af">Vector3d</span>.ZAxis);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> hits = brep.GetLineContainment(ray, 1);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (hits == <span style="color: blue">null</span> || hits.Length == 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;\nSolid is NOT below point.&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">else</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\nSolid IS below point, distance = {0}&quot;</span>,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pt.DistanceTo(hits[0].Point)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">catch</span> (System.<span style="color: #2b91af">Exception</span> ex)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(<span style="color: #a31515">&quot;Error: {0}\r\n at {1}&quot;</span>, ex.Message, ex.StackTrace);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">}</p> </div>  <p>&#160;</p>  <p>To give it a try, just run the PISO command (for PointInSolid), then select a Solid3d and start picking points. You’ll see on the application report via the command-line whether the selected point is contained within the solids and, if not, whether the point is above it (i.e. that the solid is below the point).</p>  <p>A big thanks to Miro &amp; Jan for sharing this useful code! :-)</p>
