---
layout: "post"
title: "Adding wiggle to jigsaw puzzles in AutoCAD using .NET"
date: "2015-04-30 11:27:52"
author: "Kean Walmsley"
categories:
  - "AutoCAD"
  - "AutoCAD .NET"
  - "Geometry"
original_url: "https://www.keanw.com/2015/04/adding-wiggle-to-jigsaw-puzzles-in-autocad-using-net.html "
typepad_basename: "adding-wiggle-to-jigsaw-puzzles-in-autocad-using-net"
typepad_status: "Publish"
---

<p>After <a href="http://through-the-interface.typepad.com/through_the_interface/2015/04/creating-jigsaw-puzzles-inside-autocad-using-net.html" target="_blank">seeing some code to create basic jigsaws in AutoCAD</a> – and then <a href="http://through-the-interface.typepad.com/through_the_interface/2015/04/puzzling-over-laser-cutters.html" target="_blank">a quick look at fabricating them using a laser cutter</a> – in today’s post we’re adding a “wiggle” factor, making the shape of the tabs more unique than in the prior version of the application.</p>  <p>This has been integrated into the existing JIG and JIGL commands, but we’ve also added a new command called WIGL, which applies a wiggle to the tabs of existing jigsaws (it basically checks the selection for splines with 6 fit points and runs our algorithm against those).</p>  <p>The amount of wiggle is calculated randomly for each tab but can also be influenced by a wiggle factor: this is hardcoded to 0.8 for the JIG and JIGL creation commands but can be specified by the user during the WIGL command.</p>  <p>Here’s a before and after look at the results of running WIGL against our previous puzzle:</p>  <br/><a href="http://through-the-interface.typepad.com/.a/6a00d83452464869e201b7c7824910970b-pi"><img title="Adding some wiggle" style="float: none; margin-left: auto; display: block; margin-right: auto" alt="Adding some wiggle" src="/assets/image_172513.jpg" width="438" height="440" /></a><br/><br/>  <p>Here’s the C# code implementing this version of the application:</p>  <div style="font-size: 8pt; font-family: courier new; background: white; color: black; line-height: 140%">   <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.ApplicationServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.DatabaseServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.EditorInput;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Geometry;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.AutoCAD.Runtime;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">namespace</span> JigsawGenerator</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160; <span style="color: blue">public</span> <span style="color: blue">class</span> <span style="color: #2b91af">Commands</span></p>    <p style="margin: 0px">&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// The WIGL command asks the user to enter this value (which</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// influences the extent of the &quot;wiggle&quot;). For the JIG</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// and JIGL commands we just use this hardcoded value.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// We could certainly ask the user to enter it or get it</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// from a system variable, of course</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">const</span> <span style="color: blue">double</span> wigFac = 0.8;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// We'll store a central random number generator,</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// which means we'll get more random results</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: #2b91af">Random</span> _rnd = <span style="color: blue">null</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">// Constructor</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> Commands()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; _rnd = <span style="color: blue">new</span> <span style="color: #2b91af">Random</span>();</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;JIG&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">void</span> JigEntity()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (<span style="color: blue">null</span> == doc)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> db = doc.Database;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Select our entity to create a tab for</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> peo = <span style="color: blue">new</span> <span style="color: #2b91af">PromptEntityOptions</span>(<span style="color: #a31515">&quot;\nSelect entity to jig&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; peo.SetRejectMessage(<span style="color: #a31515">&quot;\nEntity must be a curve.&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; peo.AddAllowedClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">Curve</span>), <span style="color: blue">false</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> per = ed.GetEntity(peo);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (per.Status != <span style="color: #2b91af">PromptStatus</span>.OK)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We'll ask the user to select intersecting/delimiting</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// entities: if they choose none we use the whole length</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\nSelect intersecting entities. &quot;</span> +</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Hit enter to use whole entity.&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pso = <span style="color: blue">new</span> <span style="color: #2b91af">PromptSelectionOptions</span>();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> psr = ed.GetSelection();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; psr.Status != <span style="color: #2b91af">PromptStatus</span>.OK &amp;&amp;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; psr.Status != <span style="color: #2b91af">PromptStatus</span>.Error <span style="color: green">// No selection</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> tr = doc.TransactionManager.StartTransaction())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Open our main curve</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> cur =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.GetObject(per.ObjectId, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">Curve</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> start = 0, end = 0;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">bool</span> bounded = <span style="color: blue">false</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (cur != <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We'll collect the intersections, if we have</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// delimiting entities selected</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pts = <span style="color: blue">new</span> <span style="color: #2b91af">Point3dCollection</span>();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (psr.Value != <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Loop through and collect the intersections</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: blue">var</span> id <span style="color: blue">in</span> psr.Value.GetObjectIds())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ent = (<span style="color: #2b91af">Entity</span>)tr.GetObject(id, <span style="color: #2b91af">OpenMode</span>.ForRead);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cur.IntersectWith(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ent,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Intersect</span>.OnBothOperands,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pts,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">IntPtr</span>.Zero,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">IntPtr</span>.Zero</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ed.WriteMessage(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;\nFound {0} intersection points.&quot;</span>, pts.Count</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we have no intersections, use the start and end</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// points</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (pts.Count == 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; start = cur.StartParam;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end = cur.EndParam;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pts.Add(cur.StartPoint);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pts.Add(cur.EndPoint);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bounded = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">else</span> <span style="color: blue">if</span> (pts.Count == 2)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; start = cur.GetParameterAtPoint(pts[0]);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; end = cur.GetParameterAtPoint(pts[1]);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; bounded = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// If we have a bounded length, create our tab in a random</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// direction</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (bounded)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> left = _rnd.NextDouble() &gt;= 0.5;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; CreateTab(db, tr, cur, start, end, pts, left);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;JIGL&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">void</span> JigLines()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (<span style="color: blue">null</span> == doc)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> db = doc.Database;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Here we're going to get a selection set, but only care</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// about lines</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pso = <span style="color: blue">new</span> <span style="color: #2b91af">PromptSelectionOptions</span>();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> psr = ed.GetSelection();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (psr.Status != <span style="color: #2b91af">PromptStatus</span>.OK)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> tr = doc.TransactionManager.StartTransaction())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We'll be generating random numbers to decide direction</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// for each tab</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: blue">var</span> id <span style="color: blue">in</span> psr.Value.GetObjectIds())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We only care about lines</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ln = tr.GetObject(id, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">Line</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (ln != <span style="color: blue">null</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the start and end points in a collection</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pts =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Point3dCollection</span>(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span> <span style="color: #2b91af">Point3d</span>[] {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ln.StartPoint,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ln.EndPoint</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Decide the direction (randomly) then create the tab</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> left = _rnd.NextDouble() &gt;= 0.5;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; CreateTab(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; db, tr, ln, ln.StartParam, ln.EndParam, pts, left</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; [<span style="color: #2b91af">CommandMethod</span>(<span style="color: #a31515">&quot;WIGL&quot;</span>)]</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> <span style="color: blue">void</span> AdjustTabs()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> doc = <span style="color: #2b91af">Application</span>.DocumentManager.MdiActiveDocument;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (<span style="color: blue">null</span> == doc)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> db = doc.Database;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> ed = doc.Editor;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Here we're going to get a selection set, but only care</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// about splines</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pso = <span style="color: blue">new</span> <span style="color: #2b91af">PromptSelectionOptions</span>();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> psr = ed.GetSelection();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (psr.Status != <span style="color: #2b91af">PromptStatus</span>.OK)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pdo = <span style="color: blue">new</span> <span style="color: #2b91af">PromptDoubleOptions</span>(<span style="color: #a31515">&quot;\nEnter wiggle factor&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pdo.DefaultValue = 0.8;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pdo.UseDefaultValue = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pdo.AllowNegative = <span style="color: blue">false</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pdo.AllowZero = <span style="color: blue">false</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pdr = ed.GetDouble(pdo);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (pdr.Status != <span style="color: #2b91af">PromptStatus</span>.OK)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">using</span> (<span style="color: blue">var</span> tr = doc.TransactionManager.StartTransaction())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (<span style="color: blue">var</span> id <span style="color: blue">in</span> psr.Value.GetObjectIds())</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We only care about splines</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> sp = tr.GetObject(id, <span style="color: #2b91af">OpenMode</span>.ForRead) <span style="color: blue">as</span> <span style="color: #2b91af">Spline</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (sp != <span style="color: blue">null</span> &amp;&amp; sp.NumFitPoints == 6)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Collect the fit points</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> pts = sp.FitData.GetFitPoints();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Adjust them</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AddWiggle(pts, pdr.Value);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Set back the top points to the spline</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (we know these are the ones that have changed)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sp.UpgradeOpen();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sp.SetFitPointAt(2, pts[2]);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sp.SetFitPointAt(3, pts[3]);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; tr.Commit();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">void</span> CreateTab(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Database</span> db, <span style="color: #2b91af">Transaction</span> tr,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Curve</span> cur, <span style="color: blue">double</span> start, <span style="color: blue">double</span> end, <span style="color: #2b91af">Point3dCollection</span> pts,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">bool</span> left = <span style="color: blue">true</span></p>    <p style="margin: 0px">&#160;&#160;&#160; )</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We're calculating a random delta to adjust the location</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// of the tab along the length</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> delta = 0.1 * (_rnd.NextDouble() - 0.5);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Calculate the length of this curve (or section)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> len =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">Math</span>.Abs(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cur.GetDistanceAtParameter(end) -</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; cur.GetDistanceAtParameter(start)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// We're going to offset to the side of the core curve for</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// the tab points. This is currently a fixed tab size</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// (could also make this proportional to the curve)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> off = 0.5;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> fac = 0.5 * (len - 0.5 * off) / len;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (left) off = -off;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the next parameter along the length of the curve</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// and add the point associated with it into our fit points</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> nxtParam = start + (end - start) * (fac + delta);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> nxt = cur.GetPointAtParameter(nxtParam);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pts.Insert(1, nxt);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Get the direction vector of the curve</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> vec = pts[1] - pts[0];</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Rotate it by 90 degrees in the direction we chose,</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// then normalise it and use it to calculate the location</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// of the next point</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vec = vec.RotateBy(<span style="color: #2b91af">Math</span>.PI * 0.5, <span style="color: #2b91af">Vector3d</span>.ZAxis);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; vec = off * vec / vec.Length;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pts.Insert(2, nxt + vec);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Now we calculate the mirror points to complete the</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// splines definition</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; nxtParam = end - (end - start) * (fac - delta);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; nxt = cur.GetPointAtParameter(nxtParam);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pts.Insert(3, nxt + vec);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pts.Insert(4, nxt);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; AddWiggle(pts, wigFac);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Finally we create our spline and add it to the modelspace</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> sp = <span style="color: blue">new</span> <span style="color: #2b91af">Spline</span>(pts, 1, 0);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> btr =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">BlockTableRecord</span>)tr.GetObject(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SymbolUtilityServices</span>.GetBlockModelSpaceId(db),</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">OpenMode</span>.ForWrite</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; );</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; btr.AppendEntity(sp);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; tr.AddNewlyCreatedDBObject(sp, <span style="color: blue">true</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">private</span> <span style="color: blue">void</span> AddWiggle(<span style="color: #2b91af">Point3dCollection</span> pts, <span style="color: blue">double</span> fac)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">const</span> <span style="color: blue">double</span> rebase = 0.3;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Works on sets of six points only</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 2--------3</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; |&#160;&#160;&#160;&#160;&#160;&#160;&#160; |</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">//&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; |&#160;&#160;&#160;&#160;&#160;&#160;&#160; |</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// 0-----------1&#160;&#160;&#160;&#160;&#160;&#160;&#160; 4-----------5</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (pts.Count != 6)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Our spline's direction, tab width and perpendicular vector</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> dir = pts[5] - pts[0];</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; dir = dir / dir.Length;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> tab = (pts[4] - pts[1]).Length;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">var</span> cross = dir.RotateBy(<span style="color: #2b91af">Math</span>.PI * 0.5, <span style="color: #2b91af">Vector3d</span>.ZAxis);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; cross = cross / cross.Length;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// Adjust the &quot;top left&quot; and &quot;top right&quot; points outwards,</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// multiplying by fac1 and the random factor (0-1) brought</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: green">// back towards -0.5 to 0.5 by fac2</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pts[2] =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pts[2]</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; - (dir * tab * fac * (_rnd.NextDouble() - rebase))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; + (cross * tab * fac * (_rnd.NextDouble() - rebase));</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; pts[3] =</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; pts[3]</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; + (dir * tab * fac * (_rnd.NextDouble() - rebase))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; + (cross * tab * fac * (_rnd.NextDouble() - rebase));</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160; }</p>    <p style="margin: 0px">}</p> </div>  <p>Right now the code isn’t considering issues such as edges colliding as wiggle gets applied or the fragility of individual pieces. But it’s certainly possible to adjust individual splines manually after running the command, of course.</p>
