comments:
- author: Berria
  email: eiderunzu@hotmail.com
  ip: 213.96.145.3
  url: ''
  date: '2009-02-10 03:57:52'
  body: "Hi Jeremy, \nI inserted a new railing in the document and now, I want draw\
    \ with this type but no find, how can I  iterator the railing type?\nThis is the\
    \ code:\n\nstring Balaustres1 = @\"C:\\Documents and Settings\\All Users\\Datos\
    \ de programa\\Autodesk\\RST 2009\\Metric Library\\Balaustres\\Panel de cristalera\
    \ con fijaciones.rfa\";\nList BaranSymbols = LabUtils.GetAllFamilySymbols(app,\
    \ BuiltInCategory.OST_Railings);\n\nThanks,\n\nBerria"
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/1218580759s22477
  date: '2009-02-10 04:37:04'
  body: 'Hi Berria,


    I am really quite surprised by your question. Surely you have seen some of the
    examples of iterating over collections in the labs? Simply search for the string
    GetAllFamilySymbols throughout the labs and see how the results are iterated there.
    One prime example is in Lab3_3_DetermineInstanceTypeAndFamily.


    Cheers, Jeremy.'
- author: Berria
  email: eiderunzu@hotmail.com
  ip: 213.96.145.3
  url: ''
  date: '2009-02-10 05:57:08'
  body: 'Hi Jeremy,

    I try this example and floors, walls,windows and doors familys work well, but
    railing and stairs familys no detected anything.


    Thanks,Berria.'
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/1218580759s22477
  date: '2009-02-10 07:46:25'
  body: 'Hi Berria,


    I see. I may explore this in a future post.


    Cheers, Jeremy.'
- author: HR Dissertation
  email: marryjohn4@gmail.com
  ip: 221.132.118.230
  url: http://www.ukdissertation.co.uk/HR_Dissertation.htm
  date: '2009-11-04 10:15:35'
  body: Blogs are so informative where we get lots of information on any topic. Nice
    job keep it up!!
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/1218580759s22477
  date: '2009-11-05 05:13:18'
  body: :-)
- author: Dizz
  email: kirzaa@mail.ru
  ip: 195.206.47.127
  url: ''
  date: '2010-07-07 22:56:31'
  body: "neighbours = c.get_ElementsAtJoin(i);\n\n Error 1 An implicit type conversion\
    \ \"Autodesk.Revit.ElementArray\" Ð² \"System.Collections.Generic.List  \"\n\n\
    ??????????"
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/1218580759s22477
  date: '2010-07-15 16:57:20'
  body: "Dear Dizz,\n\nThank you for your very succinct non-question.\n\nPlease look\
    \ at an updated version of the CmdWallNeighbours external command, e.g. in version\
    \ 2011.0.74.0 of The Building Coder samples in \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/place-family-instance.html\"\
    >http://thebuildingcoder.typepad.com/blog/2010/06/place-family-instance.html</a>\n\
    \nMy code looks like this right now:\n\n//List neighbours;\nElementArray neighbours;\n\
    \nSo I apparently ran into the same issue as you and fixed it.\n\nCheers, Jeremy."
- author: zhu xiaomeng
  email: zhuxiaomengjj@gmail.com
  ip: 123.116.156.140
  url: ''
  date: '2010-07-22 23:49:25'
  body: "Hi, Jeremy,\n How can i do Interference Check Programly? More precisely how\
    \ can i do Intersect With a Solid and another Geometry."
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/1218580759s22477
  date: '2010-07-26 03:27:21'
  body: "Dear Zhu Xiaomeng, \n\nUnfortunately, there is no direct programmatic access\
    \ to the built-in Revit Interference Check command.\n\nThe Revit API does provide\
    \ some interference checking methods, which are described in the following post\
    \ and the previous ones that it points to:\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/06/intersection-between-elements.html\"\
    >http://thebuildingcoder.typepad.com/blog/2010/06/intersection-between-elements.html</a>\n\
    \nIt would be possible to build a full interference checking tool using those\
    \ methods. For an example of two such tools for specialised cases, please have\
    \ a look at the Revit SDK samples AvoidObstruction and FindColumns.\n\nCheers,\
    \ Jeremy."
- author: guming
  email: guming_yu@yahoo.cn
  ip: 115.236.88.90
  url: ''
  date: '2011-08-25 08:39:59'
  body: "Hi,Jeremy:\n   I have three parameters(column top point,bottom point and\
    \ radius),How can I insert a round column(cylinder) dynamically as the same effect\
    \ as NewDuct(...) ? the important function is that it can insert column repeatly.\n\
    \   It will be great if you can give me some help on this.\n\n   Thanks.\n\n \
    \  guming"
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.199
  url: http://profile.typepad.com/jeremytammik
  date: '2011-08-29 07:36:00'
  body: 'Dear Guming,


    Have you had a look at the PromptForFamilyInstancePlacement method?


    Cheers, Jeremy.'
- author: Rafael
  email: rafael.arbg@gmail.com
  ip: 189.45.8.17
  url: ''
  date: '2012-10-15 13:42:57'
  body: 'Hi Jeremy,


    First, thanks for the amazing work here on your blog. It''s a valuable information
    source for people working with Revit API. It already saved me some good hours
    of work!


    I have a fairly simple question:


    I want to get start and end XYZ points for beams and columns. Beams and slanted
    columns are easy, as they have a LocationCurve where I can use get_EndPoint(1).
    But for regular columns, I''m subtracting base from top offset to get its length
    and then add it to start''s Y value.


    Is that the most reliable way to do it, or there is a easier way to get endpoint
    from a vertical column?


    Thanks,

    Rafael'
- author: Jeremy Tammik
  email: ''
  ip: 87.146.172.2
  url: http://profile.typepad.com/jeremytammik
  date: '2012-10-18 07:16:55'
  body: 'Dear Rafael,


    Thank you for your appreciation!


    I have a fairly complex answer  :-)


    If it is a structural column, you could access its analytical model. That would
    give you the analytical start and end point.


    You could also query the column geometry and analyse that. You should be able
    to determine the long edges, and you could calculate the average of their start
    and end points, respectively, to obtain your own beam start and end point.


    It depends a bit on how you define start and end point, of course  :-)


    Apart from that, your approach sounds perfectly valid as well.


    Yet another way might be to determine the start point from the location point,
    possibly find the direction vector either from that as well, or from the geometry,
    e.g. the normal vector of the face containing the start point, and then use that
    together with the Length parameter, if it has one, to determine the end point.
    I like that better than what you describe, but I don''t know whether it would
    work. Please test and let me know.


    As you know, there is often more than one way to achieve something:


    <a href="http://thebuildingcoder.typepad.com/blog/2012/10/beam-bottom-endpoint.html">http://thebuildingcoder.typepad.com/blog/2012/10/beam-bottom-endpoint.html</a>


    Cheers, Jeremy.

    -----'
