comments:
- author: Fernando Malard
  email: fpmalard@yahoo.com.br
  ip: 189.26.202.244
  url: http://arxdummies.blogspot.com
  date: '2010-01-14 06:34:22'
  body: 'Hi Jeremy,


    Is it possible to change also the Material category of a single GraphicStyle as
    you did with the LineColor category?


    You did for DetailCurve derived elements. What about ModelCurve derived elements?
    Will this procedure work same way it did for DetailCurve?


    Regards,

    Fernando.'
- author: Joe Ye
  email: yexiongjin@hotmail.com
  ip: 58.32.239.82
  url: ''
  date: '2010-01-14 22:03:16'
  body: "Hi Fernando,\n\nIt is possible to change the Material property of category,\
    \ which is retrieved by GraphicsStyleCategory.\n\nThe way to change detail line\
    \ color is applicable to model curve. \nPlease see below code that I tested.\n\
    public class ChangeModelLine : IExternalCommand\n    {\n        public IExternalCommand.Result\
    \ Execute(ExternalCommandData commandData,\n        ref string message, ElementSet\
    \ elements)\n        {\n\n            Autodesk.Revit.Application app = commandData.Application;\n\
    \            Document doc = app.ActiveDocument;\n\n            XYZ end0 = new\
    \ XYZ(-1, 0, 0);\n            XYZ end1 = new XYZ(1, 0, 0);\n            XYZ pointOnCurve\
    \ = new XYZ(0, 1, 0);\n            Arc geomArc = commandData.Application.Create.NewArc(end0,\
    \ end1, pointOnCurve);\n            ModelArc arc = doc.Create.NewModelCurve(geomArc,\
    \ doc.ActiveView.SketchPlane) as ModelArc;\n            GraphicsStyle gs = arc.LineStyle\
    \ as GraphicsStyle;\n            gs.GraphicsStyleCategory.LineColor = new Color(100,\
    \ 100, 200);\n            //change to a new material\n            //get a material\n\
    \            ElementIterator ei = doc.get_Elements(typeof(MaterialSteel));\n \
    \           Material mat = null;\n            while (ei.MoveNext())\n        \
    \    {\n                mat = ei.Current as Material;\n                if (null\
    \ != mat)\n                {\n                    if (mat.Name.Equals(\"Metal\
    \ - Steel\"))\n                        break;\n                }\n\n         \
    \   }\n\n            gs.GraphicsStyleCategory.Material = mat;\n\n            return\
    \ IExternalCommand.Result.Succeeded;\n        }\n\n    }\n\n\nRegards,\n\nJoe"
- author: Jeremy Tammik
  email: ''
  ip: 87.176.152.38
  url: http://profile.typepad.com/1218580759s22477
  date: '2010-01-15 01:31:15'
  body: Mille grazie, Joe! Cheers, Jeremy.
- author: Stanley Audrey
  email: stanley_1287@yahoo.com
  ip: 202.77.98.130
  url: ''
  date: '2010-01-20 04:16:01'
  body: 'Is it possible to add new line style to the category? I see the function
    CanAddSubCategory (boolean) but I don''t know how to create new line style/subcategory.


    Thanks

    Stanley Audrey'
- author: Jeremy Tammik
  email: ''
  ip: 87.176.154.179
  url: http://profile.typepad.com/1218580759s22477
  date: '2010-01-20 07:07:57'
  body: 'Dear Stanley Audrey,


    Sure it is. Have a look at the Categories.NewSubcategory method in the Revit API
    help file. It adds a new subcategory to the Revit document. Samples on using it
    in C# and VB are provided. As far as I can tell from them, they execute in the
    family document context. I don''t know whether you can also add a category in
    the project document context.


    Cheers, Jeremy.'
- author: Christian Degen
  email: christian.degen@mumz.ch
  ip: 80.218.76.185
  url: ''
  date: '2010-12-10 13:33:10'
  body: 'Hello Jeremy


    Why is the normal in this example 1,1,0 and not 0,0,1 ?

    Did I miss something?


    Thanks

    Christian Degen'
- author: Jeremy Tammik
  email: ''
  ip: 81.253.17.152
  url: http://profile.typepad.com/jeremytammik
  date: '2010-12-10 15:22:41'
  body: "Dear Christian,\n\nThank you very much for this way overdue question!\n\n\
    Hey guys, why did nobody else ask this before?\n\nThis is an error, pure and simple,\
    \ which came from copying someone else's code.\n\nI discovered it when new error\
    \ checks and messages were added in Revit 2011, and updated the sample command\
    \ accordingly:\n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/05/detail-curve-must-indeed-lie-in-plane.html\"\
    >http://thebuildingcoder.typepad.com/blog/2010/05/detail-curve-must-indeed-lie-in-plane.html</a>\n\
    \nThe best thing to do, obviously, is to download the very most recent version\
    \ of The Building Coder sample code, which is currently version 2011.0.81.0 provided\
    \ in \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/11/access-to-sketch-and-sketch-plane.html\"\
    >http://thebuildingcoder.typepad.com/blog/2010/11/access-to-sketch-and-sketch-plane.html</a>\n\
    \nThank you again for noticing and pointing this out!\n\nCheers, Jeremy."
- author: LeeJaeYoung
  email: isinegajok@naver.com
  ip: 14.46.39.230
  url: ''
  date: '2012-12-11 01:33:17'
  body: "HI, I am LeeJaeYOung. Korean.\nI study api in Revit 2013.\nI study according\
    \ to your source code.\nerror occurs.\n\nI'm sorry to incorrect English.\n\nusing\
    \ System;\nusing System.Collections;\nusing System.Windows.Forms;\n\nusing Autodesk;\n\
    using Autodesk.Revit.UI;\nusing Autodesk.Revit.DB;\nusing Autodesk.Revit.DB.Structure;\n\
    using System.IO;\nusing Autodesk.Revit.Creation;\n\nnamespace DetailArc\n{\n \
    \   [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Automatic)]\n\
    \    [Autodesk.Revit.Attributes.Regeneration(Autodesk.Revit.Attributes.RegenerationOption.Manual)]\n\
    \    [Autodesk.Revit.Attributes.Journaling(Autodesk.Revit.Attributes.JournalingMode.NoCommandData)]\n\
    \n    public class Class1\n    {\n\n        public class DetailArc : IExternalCommand\n\
    \        {\n            public Autodesk.Revit.UI.Result Execute(ExternalCommandData\
    \ commandData, ref string message, Autodesk.Revit.DB.ElementSet elements)\n  \
    \          {\n\n                // Application app = commandData.Application;\n\
    \                // Document doc = app.ActiveDocument;\n                // View\
    \ view = doc.ActiveView;\n\n                Autodesk.Revit.UI.UIApplication app\
    \ = commandData.Application;\n                UIDocument document = app.ActiveUIDocument;\n\
    \                Autodesk.Revit.DB.Document doc = document.Document;\n       \
    \         Autodesk.Revit.DB.View view = document.Document.ActiveView;\n\n    \
    \            // Create a geometry line\n\n                XYZ startPoint = new\
    \ XYZ(0, 0, 0);\n                XYZ endPoint = new XYZ(10, 10, 0);\n        \
    \        \n                Line geomLine = app.Application.Create.NewLine(startPoint,\
    \ endPoint, true);                \n                \n                // Create\
    \ a geometry arc\n\n                XYZ end0 = new XYZ(1, 0, 0);\n           \
    \     XYZ end1 = new XYZ(10, 10, 10);\n                XYZ pointOnCurve = new\
    \ XYZ(10, 0, 0);\n\n                Arc geomArc = app.Application.Create.NewArc(end0,\
    \ end1, pointOnCurve);\n\n                // Create a geometry plane\n\n     \
    \           XYZ origin = new XYZ(0, 0, 0);\n                XYZ normal = new XYZ(1,\
    \ 1, 0);\n\n                Plane geomPlane = app.Application.Create.NewPlane(\n\
    \                  normal, origin);\n\n                // Create a sketch plane\
    \ in current document\n\n                SketchPlane sketch = doc.Create.NewSketchPlane(geomPlane);\n\
    \                \n                // Create a DetailLine element using the \n\
    \                // newly created geometry line and sketch plane\n\n         \
    \       DetailLine line = doc.Create.NewDetailCurve(view, geomLine) as DetailLine;\n\
    \n                // Create a DetailArc element using the \n                //\
    \ newly created geometry arc and sketch plane\n                // DetailArc arc\
    \ = doc.Create.NewDetailCurve(view, geomArc) as DetailArc;\n                DetailArc\
    \ arc = doc.Create.NewDetailCurve(view, geomArc) as DetailArc;\n             \
    \   \n                // Change detail curve colour.\n                // Initially,\
    \ this only affects the newly \n                // created curves. However, when\
    \ the view \n                // is refreshed, all detail curves will \n      \
    \          // be updated.\n\n                GraphicsStyle gs = arc.LineStyle\
    \ as GraphicsStyle;\n\n                gs.GraphicsStyleCategory.LineColor\n  \
    \                = new Color(250, 10, 10);\n\n                return CmdResult.Succeeded;\n\
    \            }\n\n        }\n\n    }\n}\n\n\n\nerror\nError\t1\tCannot convert\
    \ type 'Autodesk.Revit.DB.DetailCurve' to 'DetailArc.Class1.DetailArc' via a reference\
    \ conversion, boxing conversion, unboxing conversion, wrapping conversion, or\
    \ null type conversion\tc:\\users\\team\\documents\\visual studio 2010\\Projects\\\
    DetailArc\\DetailArc\\Class1.cs\t70\t33\tDetailArc\n\nError\t2\t'DetailArc.Class1.DetailArc'\
    \ does not contain a definition for 'LineStyle' and no extension method 'LineStyle'\
    \ accepting a first argument of type 'DetailArc.Class1.DetailArc' could be found\
    \ (are you missing a using directive or an assembly reference?)\tc:\\users\\team\\\
    documents\\visual studio 2010\\Projects\\DetailArc\\DetailArc\\Class1.cs\t78\t\
    40\tDetailArc\nError\t3\tThe name 'CmdResult' does not exist in the current context\t\
    c:\\users\\team\\documents\\visual studio 2010\\Projects\\DetailArc\\DetailArc\\\
    Class1.cs\t83\t24\tDetailArc"
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.22
  url: http://profile.typepad.com/jeremytammik
  date: '2012-12-14 01:03:51'
  body: 'Dear LeeJaeYoung,


    I would suggest you simply grab the most up-to-date version of The Building Coder
    sample code, instead of trying to work with this possibly obsolete version.


    The latest update was version 2013.0.99.4 and is provided here:


    <a href="http://thebuildingcoder.typepad.com/blog/2012/10/slab-boundary-revisited.html">http://thebuildingcoder.typepad.com/blog/2012/10/slab-boundary-revisited.html</a>


    Cheers, Jeremy.'
- author: LeeJaeYoung
  email: isinegajok@naver.com
  ip: 118.223.75.155
  url: ''
  date: '2013-01-01 07:34:55'
  body: 'thank you

    as your teaching i knew detailline


    happy new year'
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.22
  url: http://profile.typepad.com/jeremytammik
  date: '2013-01-02 16:42:02'
  body: 'Dear LeeJaeYoung,


    Thank you for your appreciation.


    Happy New Year to you too!


    Cheers, Jeremy.'
- author: Mina Maher
  email: minamaher20@gmail.com
  ip: 41.40.131.213
  url: ''
  date: '2014-08-09 22:21:53'
  body: 'hi, first thank you for these great tutorials.

    i wanted to ask, when i try to get the Graphics Style Category of imported AutoCAD
    Geometry Line it returns null for the category but on revit they still has visible
    colors and in visibility options they have categories with layer names from AutoCAD
    so how to filter them by color or change their color'
- author: Jeremy Tammik
  email: ''
  ip: 132.188.32.206
  url: http://profile.typepad.com/jeremytammik
  date: '2014-08-11 10:29:15'
  body: 'Dear Mina,


    Thank you for your query and appreciation.


    I am very glad you like it  :-)


    There are a large number of different methods and levels at which you can set
    graphics attributes in Revit:


    <a href="http://thebuildingcoder.typepad.com/blog/2013/08/attributes-relationships-and-other-stuff.html#6">http://thebuildingcoder.typepad.com/blog/2013/08/attributes-relationships-and-other-stuff.html#6</a>


    I would suggest exploring your model using RevitLookup or other more in-depth
    methods to determine where the required attributes are defined:


    <a href="http://thebuildingcoder.typepad.com/blog/2013/11/intimate-revit-database-exploration-with-the-python-shell.html">http://thebuildingcoder.typepad.com/blog/2013/11/intimate-revit-database-exploration-with-the-python-shell.html</a>


    Cheers, Jeremy.

    -----'
