comments:
- author: Arnaud
  email: zak.villa@hotmail.fr
  ip: 83.206.220.177
  url: ''
  date: '2011-07-19 10:25:07'
  body: 'Hi Jeremy,

    I have a question please,

    I created an ExternalCommand, Is it possible to call the command from an external
    application?'
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.196
  url: http://profile.typepad.com/jeremytammik
  date: '2011-07-19 15:14:10'
  body: 'Dear Arnaud,


    Exactly that is actually the main purpose of many external applications. For a
    pretty minimal example of doing so, please refer to the zero document state sample,
    for instance:


    <a href="http://thebuildingcoder.typepad.com/blog/2011/02/enable-ribbon-items-in-zero-document-state.html">http://thebuildingcoder.typepad.com/blog/2011/02/enable-ribbon-items-in-zero-document-state.html</a>


    Cheers, Jeremy.'
- author: Arnaud
  email: zak.villa@hotmail.fr
  ip: 83.206.220.177
  url: ''
  date: '2011-07-20 02:32:00'
  body: 'Hi Jeremy,


    Thank you very much for your reponse, but my question is false.


    T would like to know if it''s possible to call a EXTERNALCOMMAND or an EXTERNALPPLICATION
    from another application(not from revit)


    (Example: I Have a button in Add-ins that displays an TaskDIalog(HelloWorld),
    and I have another programme PROG.EXE that he must call REVIT and then Call the
    Button HelloWorld)


    How Can i do that?



    (Excuse me, my english is bad)'
- author: Arnaud
  email: zak.villa@hotmail.fr
  ip: 83.206.220.177
  url: ''
  date: '2011-07-20 02:33:42'
  body: 'Hi Jeremy,


    Thank you very much for your reponse, but my question is false.


    T would like to know if it''s possible to call a EXTERNALCOMMAND or an EXTERNALPPLICATION
    from another application(not from revit)


    (Example: I Have a button in Add-ins that displays an TaskDIalog(HelloWorld),
    and I have another programme PROG.EXE that he must call REVIT and then Call the
    Button HelloWorld)


    How Can i do that?



    (Excuse me, my english is bad)'
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.196
  url: http://profile.typepad.com/jeremytammik
  date: '2011-07-20 02:39:07'
  body: "Dear Arnaud,\n\nI always thought that only answers could be false, not questions.\
    \ Congratulations on proving me wrong  :-)\n\nNope, what you are asking for is\
    \ not possible. There are workarounds to get around this, and they are convoluted.\
    \ There are lots of posts discussing this issue. For instance, look at all the\
    \ posts involving 'driving Revit from outside', 'launching a command', the Idling\
    \ event, and \n\n<a href=\"http://thebuildingcoder.typepad.com/blog/2010/04/asynchronous-api-calls-and-idling.html\"\
    >http://thebuildingcoder.typepad.com/blog/2010/04/asynchronous-api-calls-and-idling.html</a>\n\
    \nCheers, Jeremy."
- author: Jeremy Tammik
  email: ''
  ip: 82.220.1.196
  url: http://profile.typepad.com/jeremytammik
  date: '2011-07-20 02:40:34'
  body: 'Dear Arnaud,


    I always thought that only answers could be false, not questions. Congratulations
    on proving me wrong :-)


    Nope, what you are asking for is not possible. There are workarounds to get around
    this, and they are convoluted. There are lots of posts discussing this issue.
    For instance, look at all the posts involving ''driving Revit from outside'',
    ''launching a command'', the Idling event, and


    <a href="http://thebuildingcoder.typepad.com/blog/2010/04/asynchronous-api-calls-and-idling.html">http://thebuildingcoder.typepad.com/blog/2010/04/asynchronous-api-calls-and-idling.html</a>


    Cheers, Jeremy.'
- author: Arnaud
  email: zak.villa@hotmail.fr
  ip: 80.11.87.250
  url: ''
  date: '2011-07-20 08:50:28'
  body: Thank you very much Jeremy.
- author: Ahmed
  email: ahmad4343@live.com
  ip: 2.89.12.53
  url: ''
  date: '2013-05-17 11:13:23'
  body: "How you are able to create using newwall !!, i am suffering when i am trying\
    \ this using revit macro ,\nlook for example i am trying to create walls from\
    \ reference planes.\nimagine the errors comes from newwall\nalso i need to compute\
    \ where the planes intersect to find the start and end points of the walls which\
    \ i do not know how to perform any help Jeremy ?\n\n\nusing System;\nusing Autodesk.Revit.UI;\n\
    using Autodesk.Revit.DB;\nusing Autodesk.Revit.UI.Selection;\nusing System.Collections.Generic;\n\
    using System.Linq;\n\nnamespace refplanes2walls\n{\n    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]\n\
    \    [Autodesk.Revit.DB.Macros.AddInId(\"B4947BF5-8424-46D1-92EC-D300EFDC6699\"\
    )]\n\tpublic partial class ThisApplication\n\t{\n\t\tprivate void Module_Startup(object\
    \ sender, EventArgs e)\n\t\t{\n\n\t\t}\n\n\t\tprivate void Module_Shutdown(object\
    \ sender, EventArgs e)\n\t\t{\n\n\t\t}\n\n\t\t#region Revit Macros generated code\n\
    \t\tprivate void InternalStartup()\n\t\t{\n\t\t\tthis.Startup += new System.EventHandler(Module_Startup);\n\
    \t\t\tthis.Shutdown += new System.EventHandler(Module_Shutdown);\n\t\t}\n\t\t\
    #endregion\n\t\tpublic void Replanes2walls()\n\t\t{\n\t\t\t Document doc = this.ActiveUIDocument.Document;\n\
    \    UIDocument uidoc = new UIDocument(doc);\n\n    // Get \"Level 1\"\n    Level\
    \ level = (from l in new FilteredElementCollector(doc).OfClass(typeof(Level))\
    \ where l.Name == \"Level 1\" select l).First() as Level;\n\n    // Selection\
    \ will be restricted to lines only. Attempts to click on other objects will be\
    \ ignored\n    ISelectionFilter referenceplanefilter = new refplaneSelectionFilter();\n\
    \n    IList<Reference> refr = uidoc.Selection.PickObjects(ObjectType.Element,\
    \ referenceplanefilter, \"Pick lines\");\n\n    using (Transaction t = new Transaction(doc,\"\
    Create Walls From Lines\"))\n    {\n    // Get application creation object \n\
    \    \n    \tAutodesk.Revit.Creation.Application appCreation\n      = this.Application.Create;\n\
    \        t.Start(); \n        foreach (Reference reference in refr)\n        {\n\
    \            ReferencePlane refplane = doc.GetElement(reference) as ReferencePlane;\n\
    \           Wall wall=  doc.Create.newwall(refplane.Direction, level, false);\
    \ // false indicates that the wall's Structural property is false\n        }\n\
    \        t.Commit();\n    }\n}\npublic class refplaneSelectionFilter : ISelectionFilter\n\
    {\n    // determine if the element should be accepted by the filter\n    public\
    \ bool AllowElement(Element element)\n    {\n        // Convert the element to\
    \ a ModelLine\n        ReferencePlane refplane = element as ReferencePlane;\n\
    \        // line is null if the element is not a model line\n        if (refplane\
    \ == null)\n        {\n            return false;\n        }\n        // return\
    \ true if the line is a model line\n        return true;\n    }\n\n    // references\
    \ will never be accepeted by this filter, so always return false\n    public bool\
    \ AllowReference(Reference refer, XYZ point)\n    {return false;}\n}\n\t\t}\n\t\
    }\n\n-----"
