comments:
- author: Matt Taylor
  email: matthew.taylor@wspgroup.com
  ip: 61.14.99.173
  url: ''
  date: '2013-07-31 19:42:19'
  body: What about using the copy-paste API?
- author: Brett
  email: brett.burling@bgeeng.com
  ip: 203.118.243.245
  url: ''
  date: '2013-07-31 23:49:59'
  body: 'You can create a exact copy of a floor and its holes using the transform
    utilities:


    <i>

    dim translationVector as newXYZ(0,10,0)

    Dim duplicates As ICollection(Of ElementId) = ElementTransformUtils.CopyElement(document,

    floorInstance.Id, translationVector)

    </i>'
- author: Victor Chekalin
  email: ''
  ip: 5.79.221.122
  url: http://profile.typepad.com/6p017ee5f8b354970d
  date: '2013-08-05 11:36:28'
  body: 'Hi Brett,


    To copy floor was not the objective in my project. I needed created a new floor
    with several boundaries. To copy floor is just a sample how to create it programatically.

    But thanks for the ElementTransformUtils though..'
- author: Brett
  email: brett.burling@gmail.com
  ip: 124.170.219.250
  url: ''
  date: '2013-08-09 07:17:27'
  body: 'ok yeah, i see that now...

    -----'
