---
layout: "post"
title: "Program Prototyping"
date: "2008-10-10 22:48:10"
author: "Adam Nagy"
categories:
  - "Beginning API"
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2008/10/program-prototyping.html "
typepad_basename: "program-prototyping"
typepad_status: "Publish"
---

<p>In some of the previous postings I&#39;ve talked about some of the advantages and disadvantages of the various languages. One thing I mentioned was the use of VBA to prototype programs.&#0160; A colleague stopped by my office earlier today asking for some help with a program he&#39;s writing for a customer. Apparently the customer, and now him, have been struggling with getting the program to work.&#0160; </p>
<p>Here&#39;s a simplified description of what they were trying to do.&#0160; While working in a drawing that contains retrieved dimensions they want to be able to get to the associated tolerance information from the part.&#0160; I didn&#39;t immediately know the answer to this either but was able to figure it out in a couple of minutes.&#0160; The reason I was able to do this is because I know how to use VBA as a prototyping tool.&#0160; The good part is that you can learn how too. It&#39;s an extremely powerful tool when programming Inventor that you can take advantage of regardless of what language you&#39;re writing your program in.&#0160; </p>
<p>I&#39;ll go through the procedure step-by-step that I used to figure out the solution to this specific problem.&#0160; Although this looks at a specific case, the principles demonstrated here are generally applicable to any case.&#0160; Below is the example for this case for this case which consists of a drawing view with three retrieved dimensions.&#0160; Given a dimension we want to get the tolerance information from the associated parameter in the model.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105357a6b75970c-pi"><img alt="DiameterDim" border="0" height="162" src="/assets/image_797458.jpg" style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" width="244" /></a> </p>
<ol>
<li>Have Inventor running with the document open that contains the type of data you want to query.&#0160; 
<li>Select the object you&#39;re interested in.&#0160; In this case it&#39;s one of the dimensions. 
<li>Open the VBA environment and write the following code.&#0160; (I would write it in a module in your application project then you can use it again later.) 
<blockquote>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub DebugObject() <br />&#0160;&#0160;&#0160; Dim oDoc As Document <br />&#0160;&#0160;&#0160; Set oDoc = ThisApplication.ActiveDocument <br />&#0160;&#0160;&#0160; Dim oObj As Object <br />&#0160;&#0160;&#0160; Set oObj = oDoc.SelectSet.Item(1) <br />&#0160;&#0160;&#0160; Stop <br />End Sub</div></blockquote>
<li>Run the VBA macro. You&#39;ll get an error like the one shown below if there isn&#39;t an entity selected.&#0160; Just stop the program, select the desired entity and run it again. <br /><br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105357a6b7a970c-pi"><img alt="GeneralError" border="0" height="139" src="/assets/image_417423.jpg" style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" width="244" /></a> <br />
<li>The macro will stop execution at the <strong>Stop</strong> statement.&#0160; (You could have also put a break in the code but the Stop statement is convenient.) 
<li>Right-click the mouse anywhere within the variable oObj and select the &quot;Add Watch...&quot; command. <br /><br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105357155d7970b-pi"><img alt="AddWatch" border="0" height="233" src="/assets/image_474311.jpg" style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" width="244" /></a>&#0160; <br />
<li>Click <strong>OK</strong> and accept the defaults in the &quot;Add Watch&quot; dialog. <br /><br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105357a6b80970c-pi"><img alt="AddWatch2" border="0" height="182" src="/assets/image_1029.jpg" style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" width="244" /></a>&#0160; <br /><br />
<li>The Watch window should appear, if it wasn&#39;t already shown, and the variable &quot;oObj&quot; will be displayed. The watch window shows three interesting things; Expression, Value, and Type. The expression is the variable or property we&#39;re watching, the value is the value of that expression, and the type is the type of the variable or object the expression results in. In this example we can see the type of oObj is a DiameterGeneralDimension.&#0160; You&#39;ll often see object types prefixed with &quot;IRx&quot; and you can just ignore the prefix. The Value is empty because a DiameterGeneralDimension doesn&#39;t have an explicit value. <br /><br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105357a6b85970c-pi"><img alt="Debug1" border="0" height="209" src="/assets/image_417658.jpg" style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" width="431" /></a> <br /><br />
<li>Click on the &quot;+&quot; next to oObj to expand the object. Now all of the properties of the DiameterGeneralDimension are displayed. Each property also shows it&#39;s value and type.&#0160; Some of the properties return objects and have a &quot;+&quot; next to them so you can expand them and see the properties associated with that object.&#0160; In this case there are two properties that are interesting for the problem we&#39;re trying to solve; Retrieved and RetrievedFrom.&#0160; The Retrieved property indicates if this drawing dimension was created by retrieving a dimension from the model.&#0160; You can see in the debug window that the value is True for the currently selected dimension.&#0160; The RetrievedFrom property returns the model dimension this was retrieved from.&#0160; In this case the type of object returned is a FeatureDimension. <br /><br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105357155f3970b-pi"><img alt="Debug2" border="0" height="351" src="/assets/image_422334.jpg" style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" width="431" /></a> <br /><br />
<li>Expanding the RetrievedFrom property you see the properties of the FeatureDimension object.&#0160; One of these is the Parameter property which returns a ModelParameter object.&#0160; Expanding this we can see the Tolerance property. Finally, expanding on this we can see the upper and lower tolerance values.&#0160; All of this is shown below. <br /><br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105357155f6970b-pi"><img alt="Debug4" border="0" height="465" src="/assets/image_437614.jpg" style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" width="404" /></a> <br /><br />
<li>Here&#39;s the corresponding code that was written based on what was learned from the debugger window.&#0160;&#0160; <br /><br />
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub GetDimTolerance() <br />&#0160;&#0160;&#0160; &#39; Get the active document.&#0160; Assumes it&#39;s a drawing.&#0160; <br />&#0160;&#0160;&#0160; Dim oDrawDoc As DrawingDocument <br />&#0160;&#0160;&#0160; Set oDrawDoc = ThisApplication.ActiveDocument <br /><br />&#0160;&#0160;&#0160; &#39; Get the selected dimension, with error handling to <br />&#0160;&#0160;&#0160; &#39; gracefully error out if a dimension isn&#39;t selected. <br />&#0160;&#0160;&#0160; On Error Resume Next <br />&#0160;&#0160;&#0160; Dim oDim As GeneralDimension <br />&#0160;&#0160;&#0160; Set oDim = oDrawDoc.SelectSet.Item(1) <br />&#0160;&#0160;&#0160; If Err Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox &quot;A drawing dimension must be selected.&quot; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160; End If&#0160; <br /><br />&#0160;&#0160;&#0160; &#39; Check to see if the selected dimension was retrieved. <br />&#0160;&#0160;&#0160; If oDim.Retrieved Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Get the associated model dimension. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oFeatureDim As FeatureDimension <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oFeatureDim = oDim.RetrievedFrom <br /><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Get the associated model tolerance. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oTol As Tolerance <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oTol = oDim.RetrievedFrom.Parameter.Tolerance <br /><br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Display the tolerance value. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Debug.Print &quot;Tol: &quot; &amp; oTol.Upper &amp; &quot;/&quot; &amp; oTol.Lower <br />&#0160;&#0160;&#0160; End If <br />End Sub</div></li>
</li></li></li></li></li></li></li></li></li></li></ol>
<br />
<p>The specifics of what the code is doing in this case isn&#39;t important but the method we used to arrived at this code is.&#0160; The debug window provides a &quot;live&quot; view of the object model that you can traverse through to see how objects are connected through their various properties. Anytime you want to investigate how to use the API to access a certain object or to get to particular information. </p>
