---
layout: "post"
title: "Introduction to Attributes"
date: "2009-07-02 06:31:03"
author: "Adam Nagy"
categories:
  - "Attributes"
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/07/introduction-to-attributes.html "
typepad_basename: "introduction-to-attributes"
typepad_status: "Publish"
---

<p>This is the first of at least two posts on attributes.&#160; This first one will cover the basics and subsequent postings will go into some more advanced aspects.&#160; Most programs your write will likely only need the information covered in this post.</p>  <p>The attribute functionality of Inventor is something that’s only available through the API; it doesn’t have a user-interface.&#160; The basic concept of attributes is very simple; it’s the ability to associate information with Inventor entities.&#160; Where it get’s a little more complicated is in understanding when this functionality might apply to your programs and how you can take advantage of it.</p>  <p>First, let’s look at the API for attributes.&#160; Every object that supports attributes has the AttributeSets property from which you can access the attributes associated with that particular object.&#160; Below is the object model for attributes.    <br />&#160;<a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834011570a96141970c-pi"><img title="AttributesModel" style="border-top-width: 0px; display: block; border-left-width: 0px; float: none; border-bottom-width: 0px; margin-left: auto; margin-right: auto; border-right-width: 0px" height="141" alt="AttributesModel" src="/assets/image_861332.jpg" width="179" border="0" /></a></p>  <p></p>  <p>The “Inventor Entity” is any object that supports the AttributeSets property.&#160; The AttributesSets object returned by this property is an object collection that lets you access all of the AttributeSet objects associated with the object, and it also lets you create new AttributeSet objects.&#160; An AttributeSet is exactly what the name implies; a set of attributes.&#160; They provide a way of grouping the attributes associated with an object.&#160; Typically, each application that adds an attribute to an object will create their own attribute set so that their attributes aren’t mixed with another application’s attributes. </p>  <p><font size="3"><strong>Creating an Attribute </strong></font>    <br />An AttributeSet object is also a collection object and provides access to the Attribute objects it contains and provides the ability to create new attributes.&#160; Below is an example VBA macro that demonstrates this by creating a new attribute set on a selected entity and then adds an attribute to that set.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">   <p>Public Sub CreateAttribute()      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the active document.&#160; It can be any type of document.          <br /></strong></font>&#160;&#160;&#160; Dim doc As Document       <br />&#160;&#160;&#160; Set doc = ThisApplication.ActiveDocument&#160; <br />      <br /></p>    <p><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the selected entity.          <br /></strong></font>&#160;&#160;&#160; Dim entity As Object       <br />&#160;&#160;&#160; On Error Resume Next       <br />&#160;&#160;&#160; Set entity = doc.SelectSet.Item(1)       <br />&#160;&#160;&#160; If Err Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;You must select an entity.&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If </p>    <p><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the AttributeSets object from the selected entity.          <br /></strong></font>&#160;&#160;&#160; Dim attribSets As AttributeSets       <br />&#160;&#160;&#160; Set attribSets = entity.AttributeSets       <br />&#160;&#160;&#160; If Err Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;You must select an entity that supports attributes.&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; On Error GoTo 0&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Create an attribute set.          <br /></strong></font>&#160;&#160;&#160; Dim attribSet As AttributeSet       <br />&#160;&#160;&#160; Set attribSet = attribSets.Add(&quot;SampleSet&quot;)       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Create an attribute on the set.          <br /></strong></font>&#160;&#160;&#160; Dim attrib As Inventor.Attribute       <br />&#160;&#160;&#160; Set attrib = attribSet.Add(&quot;SampleAttribute&quot;, _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kStringType, &quot;A Test&quot;)       <br />End Sub</p> </div>  <p></p>  <p>The first portion of the program gets the entity that is currently selected within the active document.&#160; Notice that the variable “entity” is declared as Object, indicating that any type of object can be handled.&#160; The error handling is used to catch the case where no entity has been selected.</p>  <p>The next section of the program gets the AttributeSets object from the selected entity.&#160; Since the program allows you to select anything, the error handling is used to catch the case where the selected object doesn’t support the AttributeSets property.</p>  <p>Finally, we have an AttributeSets object that was obtained from the selected entity.&#160; The next section creates an AttributeSet object using the Add method of the AttributeSets object.&#160; It supplies the name to use for the AttributeSet.&#160; The name must be unique with respect to the other AttributeSet objects associated with that particular AttributeSets object.&#160; Typically you would append the set name with your company or application name to make it unique, i.e. “modmachineSampleTest”.</p>  <p>The final section of the program creates an attribute within the attribute set.&#160; The creation of the attribute takes three arguments; name, type, and value.&#160; The name must be unique with respect to the other attributes within this attribute set.&#160; Since it’s likely you’re the only one adding attributes to your set this is easily managed by you.&#160; Attributes can be one of four different types; Double, Integer, String, or array of Bytes.&#160; In the example above it creates a String attribute with the value of “A Test”.</p>  <p><font size="3"><strong>Getting an Existing Attribute From an Entity</strong></font>     <br />Now that you’ve seen how to create an attribute on an entity, how do you get that attribute back at a later time?&#160; There are two ways of accessing attributes.&#160; The first uses the objects we’ve already looked at; AttributeSets and AttributeSet.&#160; The sample code below illustrates getting the attribute that was just created.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">   <p>Public Sub GetAttribute()      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the active document.&#160; It can be any type of document.          <br /></strong></font>&#160;&#160;&#160; Dim doc As Document       <br />&#160;&#160;&#160; Set doc = ThisApplication.ActiveDocument       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the selected entity.          <br /></strong></font>&#160;&#160;&#160; Dim entity As Object       <br />&#160;&#160;&#160; On Error Resume Next       <br />&#160;&#160;&#160; Set entity = doc.SelectSet.Item(1)       <br />&#160;&#160;&#160; If Err Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;You must select an entity.&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the AttributeSets object from the selected entity.          <br /></strong></font>&#160;&#160;&#160; Dim attribSets As AttributeSets       <br />&#160;&#160;&#160; Set attribSets = entity.AttributeSets       <br />&#160;&#160;&#160; If Err Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;You must select an entity that supports attributes.&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; On Error GoTo 0       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Check to see if it has the &quot;SampleSet&quot; attribute set.          <br /></strong></font>&#160;&#160;&#160; If attribSets.NameIsUsed(&quot;SampleSet&quot;) Then       <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the attribute set.          <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim attribSet As AttributeSet       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set attribSet = attribSets.Item(&quot;SampleSet&quot;) </p>    <p><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the attribute on the set.          <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim attrib As Inventor.Attribute       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set attrib = attribSet.Item(&quot;SampleAttribute&quot;)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;Attribute &quot; &amp; attrib.name &amp; &quot; = &quot; &amp; attrib.Value       <br />&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;The entity does not have the expected attribute set.&quot;       <br />&#160;&#160;&#160; End If       <br />End Sub</p> </div>  <p></p>  <p>Most of the code in the sample above is the same as the previous sample.&#160; However, once it has the AttributeSets object from the selected entity it uses the NameIsUsed property of the AttributeSets object to see if there is an attribute set named “SampleSet”.&#160; If there is then it gets the attribute named “SampleAttribute”.&#160; Finally it displays the name and value of that attribute.</p>  <p>The approach demonstrated above illustrates how you can get an attribute from an known entity.&#160; The problem with this approach is that in many cases you don’t have a reference to the entity the attribute is attached to.&#160; For example, you might have attached an attribute to a face so you can use the attribute at a later time to find that face again.&#160; Using the technique shown above you would need to iterate over every face in the model until you found the one that had the “SampleSet” attribute set.&#160; Not a very efficient way to find the attribute.&#160; Another approach of getting attributes is discussed below.</p>  <p><font size="3"><strong>Getting an Existing Attribute Using the Attribute Manager        <br /></strong></font>The other way to find existing attributes is to use the AttributeManager object.&#160; This is an object you obtain using the AttributeManager property of the Document object.&#160; The most common use of the attribute manager is to query for attributes that exist in the document.&#160; For example, the code below will find all entities that have an attribute set called “SampleSet”.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">   <p>Public Sub GetAttributeUsingManager()      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the active document.&#160; It can be any type of document.          <br /></strong></font>&#160;&#160;&#160; Dim doc As Document       <br />&#160;&#160;&#160; Set doc = ThisApplication.ActiveDocument&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the attribute manager.          <br /></strong></font>&#160;&#160;&#160; Dim attribMgr As AttributeManager       <br />&#160;&#160;&#160; Set attribMgr = doc.AttributeManager       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Find all attribute sets named &quot;SampleSet&quot;.          <br /></strong></font>&#160;&#160;&#160; Dim foundEntities As ObjectCollection       <br />&#160;&#160;&#160; Set foundEntities = attribMgr.FindObjects(&quot;SampleSet&quot;)       <br />      <br />&#160;&#160;&#160; MsgBox &quot;Found &quot; &amp; foundEntities.Count &amp; &quot; entities.&quot;       <br />End Sub</p> </div>  <p></p>  <p>You can see this is much easier, and faster, than looking through all of the entities to see if they have a particular attribute set.</p>  <p>There are three different Find methods to choose from and you’ll choose one over the other depending on which type of object will be the most convenient for you to use in your program.&#160; The three find methods are FindAttributes, FindAttributeSets, and FindObjects.&#160; All three of them take the same input arguments and do the same type of search with the only difference being what they return.&#160; The FindAttributes method returns a list of Attribute objects as an AttributesEnumerator object.&#160; The FindAttributeSets method returns a list of AttributeSet objects as an AttributeSetsEnumerator object.&#160; The FindObjects returns a list of entities as an ObjectCollection object.</p>  <p>The three Find methods have three arguments.&#160; The first is the name of the attribute set, the second is the name of the attribute, and the third is the value of the attribute.&#160; You can use wild cards when searching.&#160; For example if I had added the following attribute sets to several different entities, SampleSet1, SampleSet2, SampleSet3, and SampleSet4, the following query would find and return all four attribute sets.&#160; Notice the asterisk wild card at the end of “SampleSet”</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new"><font color="#0000ff"><strong>&#160;&#160;&#160; ' Find all attribute sets named &quot;SampleSet&quot;.        <br /></strong></font>&#160;&#160;&#160; Dim foundSets As AttributeSetsEnumerator&#160; <br />&#160;&#160;&#160; Set foundSets = attribMgr.FindAttributeSets(&quot;SampleSet*&quot;)     <br /></div>  <p>The following query will find all attribute sets named “SampleSet” that contain an attribute named “TableType”.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new"><font color="#0000ff"><strong>&#160;&#160;&#160; ' Find all attribute sets named &quot;SampleSet&quot;.        <br /></strong></font>&#160;&#160;&#160; Dim foundSets As AttributeSetsEnumerator&#160; <br />&#160;&#160;&#160; Set foundSets = attribMgr.FindAttributeSets(&quot;SampleSet&quot;, _</div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;TableType&quot;)    <br /></div>  <p>This last one find all attribute sets that have an attribute whose value is “ACME Fastener”.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new"><font color="#0000ff"><strong>&#160;&#160;&#160; ' Find all attribute sets named &quot;SampleSet&quot;.        <br /></strong></font>&#160;&#160;&#160; Dim foundSets As AttributeSetsEnumerator&#160; <br />&#160;&#160;&#160; Set foundSets = attribMgr.FindAttributeSets(&quot;*&quot;, &quot;*&quot;, _</div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;ACME Fastener&quot;)    <br /></div>  <p>As discussed above, the various find methods return different types of objects.&#160; Frequently you may have a reference to one type of object but also need the associated objects.&#160; We’ve already seen how how you can walk down the object model from an entity to get an associated AttributeSet object and from the AttributeSet object to get the Attribute objects.&#160; You can also walk up the object model.&#160; If you start with an Attribute object you can use its Parent property to get the AttributeSet object it is associated with.&#160; You can use the Parent property of the AttributeSet object to get the parent AttributeSets object.&#160; And finally, you can use the AttributeSets object’s Parent property to get the entity the attribute set is associated with.&#160; <br /><font size="3"><strong>       <br />Why Use Attributes? </strong>      <br /></font>A common question when first learning about attributes is “why/how would you use them?”.&#160; Attributes don’t do anything by themselves but only serve as a tool to enable other things.&#160; Because of this they are used in many different ways for many unique applications.&#160; Here are a some examples that illustrate how attributes can be used.&#160; They also demonstrate why you would choose one of the find methods of the AttributeManager object over another.&#160; </p>  <p>Probably the most common use of attributes is for naming an entity so you can find it later.&#160; For example, you might be automating the creation of an assembly and need to find the entities that will be used as input when creating constraints to position the parts in the assembly.&#160; One approach is to add an attribute set to the entity so you can use one of the AttributeManager find method find it later.&#160; In this case it’s the entity that’s of interest and the attribute is just serving as the mechanism to find the entity and using the FindObjects method makes sense because it directly returns the object so you can easily use it to create the constraint.</p>  <p>Another common example of the use of attributes is adding additional information to an entity that’s important for your application. For example you might write a program to create a custom table in a drawing.&#160; In this case each row of the table represents something unique to your application is not something that Inventor is aware of.&#160; You can use the API to create a custom table with the data you want to display but you can also add an attribute set to the custom table that contains additional information that will be useful to you to understand where the data in the table came from so you can easily update it.&#160; In this case it’s probably the AttributeSets object that’s the most interesting since it gives you easy access to the attributes to allow you to query them to determine the table information.&#160; Using the FindAttributeSets method makes more sense in this case.</p>  <p>Here’s an example where Inventor takes advantage of attributes.&#160; I talked this in a previous post, <a title="http://modthemachine.typepad.com/my_weblog/2009/04/controlling-layers-in-your-flat-pattern-export.html" href="http://modthemachine.typepad.com/my_weblog/2009/04/controlling-layers-in-your-flat-pattern-export.html">http://modthemachine.typepad.com/my_weblog/2009/04/controlling-layers-in-your-flat-pattern-export.html</a>.&#160; In this example, you add attributes to the edges of a flat pattern and the translator will use the attributes to determine which layer to create the corresponding geometry on.</p>  <p>Another example is face colors.&#160; You can right-click on a face in a part and select the Properties command to change the color of that face.&#160; Internally, Inventor remembers the color you selected by adding an attribute to that face that has the name of the color.</p>
