---
layout: "post"
title: "Positioning Assembly Occurrences"
date: "2009-04-10 01:03:20"
author: "Adam Nagy"
categories:
  - "Assemblies"
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/04/positioning-assembly-occurrences.html "
typepad_basename: "positioning-assembly-occurrences"
typepad_status: "Publish"
---

<p>Rob Cohee recently posted a <a href="http://www.youtube.com/watch?v=GsE7r9iU5Rw">video</a> demonstrating some skeletal modeling techniques in Inventor related to .&#0160; To simplify the process he used a VBA macro that I wrote for him.&#0160; It’s a simple macro and is useful by itself but also helps to demonstrate some API capabilities.&#0160; Here’s the macro that I provided Rob.</p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">
<p>Public Sub AlignOccurrencesWithConstraints() <br />&#0160;&#0160;&#0160; Dim assemblydoc As AssemblyDocument <br />&#0160;&#0160;&#0160; Set assemblydoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the occurrences in the select set. <br /></strong></font>&#0160;&#0160;&#0160; Dim occurrenceList As New Collection <br />&#0160;&#0160;&#0160; Dim entity As Object <br />&#0160;&#0160;&#0160; For Each entity In assemblydoc.SelectSet <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If TypeOf entity Is ComponentOccurrence Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; occurrenceList.Add entity <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; Next <br /><br />&#0160;&#0160;&#0160; If occurrenceList.Count &lt; 2 Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox &quot;At least two occurrences must be selected.&quot; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160; End If <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; This assumes the first selected occurrence is the &quot;base&quot; <br />&#0160;&#0160;&#0160; &#39; and will constrain the base workplanes of all the other parts <br />&#0160;&#0160;&#0160; &#39; to the base workplanes of the first part. If there are <br />&#0160;&#0160;&#0160; &#39; constraints on the other they end up being over constrained.</strong></font></p>
<p><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the planes from the base part and create proxies for them. <br /></strong></font>&#0160;&#0160;&#0160; Dim baseOccurrence As ComponentOccurrence <br />&#0160;&#0160;&#0160; Set baseOccurrence = occurrenceList.Item(1) <br /><br />&#0160;&#0160;&#0160; Dim BaseXY As WorkPlane <br />&#0160;&#0160;&#0160; Dim BaseYZ As WorkPlane <br />&#0160;&#0160;&#0160; Dim BaseXZ As WorkPlane <br />&#0160;&#0160;&#0160; Call GetPlanes(baseOccurrence, BaseXY, BaseYZ, BaseXZ) <br /><br />&#0160;&#0160;&#0160; Dim constraints As AssemblyConstraints <br />&#0160;&#0160;&#0160; Set constraints = assemblydoc.ComponentDefinition.constraints <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Iterate through the other occurrences <br /></strong></font>&#0160;&#0160;&#0160; Dim i As Integer <br />&#0160;&#0160;&#0160; For i = 2 To occurrenceList.Count <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim thisOcc As ComponentOccurrence <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set thisOcc = occurrenceList.Item(i) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Move it to the base occurrence so that if the base is <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; not fully constrained it shouldn&#39;t move when the flush <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; constraints are added. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; thisOcc.Transformation = baseOccurrence.Transformation <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Get the planes from the occurrence <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim occPlaneXY As WorkPlane <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim occPlaneYZ As WorkPlane <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim occPlaneXZ As WorkPlane <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call GetPlanes(thisOcc, occPlaneXY, occPlaneYZ, occPlaneXZ) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Add the flush constraints. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call constraints.AddFlushConstraint(BaseXY, occPlaneXY, 0) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call constraints.AddFlushConstraint(BaseYZ, occPlaneYZ, 0) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call constraints.AddFlushConstraint(BaseXZ, occPlaneXZ, 0) <br />&#0160;&#0160;&#0160; Next <br />End Sub <br /><br /><font color="#0000ff"><strong>&#39; Utility function used by the AlignOccurrencesWithConstraints macro. <br />&#39; Given an occurrence it returns the base work planes that are in <br />&#39; the part or assembly the occurrence references.&#0160; It gets the <br />&#39; proxies for the planes since it needs the work planes in the <br />&#39; context of the assembly and not in the part or assembly document <br />&#39; where they actually exist.</strong></font> <br />Private Sub GetPlanes(ByVal Occurrence As ComponentOccurrence, _&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ByRef BaseXY As WorkPlane, _&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ByRef BaseYZ As WorkPlane, _&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ByRef BaseXZ As WorkPlane) <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the work planes from the definition of the occurrence. <br />&#0160;&#0160;&#0160; &#39; These will be in the context of the part or subassembly, not&#0160; <br />&#0160;&#0160;&#0160; &#39; the top-level assembly, which is what we need to return. <br /></strong></font>&#0160;&#0160;&#0160; Set BaseXY = Occurrence.Definition.WorkPlanes.Item(3) <br />&#0160;&#0160;&#0160; Set BaseYZ = Occurrence.Definition.WorkPlanes.Item(1) <br />&#0160;&#0160;&#0160; Set BaseXZ = Occurrence.Definition.WorkPlanes.Item(2) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Create proxies for these planes.&#0160; This will act as the work <br />&#0160;&#0160;&#0160; &#39; plane in the context of the top-level assembly. <br /></strong></font>&#0160;&#0160;&#0160; Call Occurrence.CreateGeometryProxy(BaseXY, BaseXY) <br />&#0160;&#0160;&#0160; Call Occurrence.CreateGeometryProxy(BaseYZ, BaseYZ) <br />&#0160;&#0160;&#0160; Call Occurrence.CreateGeometryProxy(BaseXZ, BaseXZ) <br />End Sub</p></div>
<br />
<p>The program above constrains the base work planes of the set of selected occurrences to the base work planes of one other selected occurrence (the base part).&#0160; It places three flush constraints between each part and the base part.&#0160; The advantage to this is that the occurrences are all constrained to the base part so that if the base part is repositioned all of the other parts will automatically move to maintain the relationship defined by the constraints.&#0160; The disadvantage is that it’s doing quite a bit of work and each constraint placement causes the assembly to recompute, which is what gave Rob time to go get coffee.</p>
<p>There’s another approach that is much faster if you just need to position parts but don’t need to associate their position to another part.&#0160; The macro below does this.&#0160; It’s simpler and runs much faster.&#0160; This macro positions the parts exactly as the previous macro but instead of creating constraints it just repositions them and then grounds them so they can’t be accidentally moved.</p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">
<p>Public Sub AlignOccurrencesWithGround() <br />&#0160;&#0160;&#0160; Dim assemblydoc As AssemblyDocument <br />&#0160;&#0160;&#0160; Set assemblydoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the occurrences in the select set.&#0160; The first occurrence <br />&#0160;&#0160;&#0160; &#39; selected will be the &quot;base&quot; where all of the other occurrences <br />&#0160;&#0160;&#0160; &#39; will be positioned relative to it. <br /></strong></font>&#0160;&#0160;&#0160; Dim baseOccurrence As ComponentOccurrence <br />&#0160;&#0160;&#0160; Dim baseTransform As Matrix <br />&#0160;&#0160;&#0160; Dim transObjects As TransientObjects <br />&#0160;&#0160;&#0160; Set transObjects = ThisApplication.TransientObjects <br />&#0160;&#0160;&#0160; Dim occList As ObjectCollection <br />&#0160;&#0160;&#0160; Set occList = transObjects.CreateObjectCollection <br />&#0160;&#0160;&#0160; Dim transformList As ObjectCollection <br />&#0160;&#0160;&#0160; Set transformList = transObjects.CreateObjectCollection <br />&#0160;&#0160;&#0160; Dim entity As Object <br />&#0160;&#0160;&#0160; For Each entity In assemblydoc.SelectSet <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Check that the selected entity is an occurrence. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If TypeOf entity Is ComponentOccurrence Then <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Check if the base occurrence has been assigned. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; If not then this is the first occurrence found and <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; use it as the base occurrence. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If baseOccurrence Is Nothing Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set baseOccurrence = entity <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set baseTransform = baseOccurrence.Transformation <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Else <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; This is another selected occurrence so just <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; add it to the list. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; occList.Add entity <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transformList.Add baseTransform <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; Next&#0160; <br /><br />&#0160;<font color="#0000ff"><strong>&#0160;&#0160; &#39; Check that at least a base occurrence and one other occurrence <br />&#0160;&#0160;&#0160; &#39; was selected. <br /></strong></font>&#0160;&#0160;&#0160; If occList.Count &lt; 1 Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox &quot;At least two occurrences must be selected.&quot; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160; End If <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Reposition all of the occurrences.&#0160; The TransformOccurrences <br />&#0160;&#0160;&#0160; &#39; method was new in Inventor 2009. <br /></strong></font>&#0160;&#0160;&#0160; Dim assemblyDef As AssemblyComponentDefinition <br />&#0160;&#0160;&#0160; Set assemblyDef = assemblydoc.ComponentDefinition <br />&#0160;&#0160;&#0160; Call assemblyDef.TransformOccurrences( occList, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transformList) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Iterate through the occurrences and ground them. <br /></strong></font>&#0160;&#0160;&#0160; Dim i As Integer <br />&#0160;&#0160;&#0160; For i = 1 To occList.Count <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim thisOccurrence As ComponentOccurrence <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set thisOccurrence = occList.Item(i) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; thisOccurrence.Grounded = True <br />&#0160;&#0160;&#0160; Next <br />End Sub</p></div>
<br />
<p>Here’s one final version of this macro that is still even simpler.&#0160; In the two previous macros the selected occurrences were moved relative to the location of the first selected occurrence.&#0160; The macro below moves every occurrence to be positioned relative to the base assembly coordinate system.&#0160; It doesn’t rely on selection but repositions every occurrence and grounds it.</p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">
<p>Public Sub AlignOccurrencesWithOrigin() <br />&#0160;&#0160;&#0160; Dim assemblyDoc As AssemblyDocument <br />&#0160;&#0160;&#0160; Set assemblyDoc = ThisApplication.ActiveDocument <br />&#0160;&#0160;&#0160; Dim assemblyDef As AssemblyComponentDefinition <br />&#0160;&#0160;&#0160; Set assemblyDef = assemblyDoc.ComponentDefinition <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Create a matrix.&#0160; It is initialized as an identity matrix <br />&#0160;&#0160;&#0160; &#39; which means it defines a position as the origin and aligned <br />&#0160;&#0160;&#0160; &#39; with the global x, y, and z axes. <br /></strong></font>&#0160;&#0160;&#0160; Dim transGeom As TransientGeometry <br />&#0160;&#0160;&#0160; Set transGeom = ThisApplication.TransientGeometry <br />&#0160;&#0160;&#0160; Dim baseTransform As Matrix <br />&#0160;&#0160;&#0160; Set baseTransform = transGeom.CreateMatrix <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Create collections to load the occurrences into. <br /></strong></font>&#0160;&#0160;&#0160; Dim transObjects As TransientObjects <br />&#0160;&#0160;&#0160; Set transObjects = ThisApplication.TransientObjects <br />&#0160;&#0160;&#0160; Dim occList As ObjectCollection <br />&#0160;&#0160;&#0160; Set occList = transObjects.CreateObjectCollection <br />&#0160;&#0160;&#0160; Dim transformList As ObjectCollection <br />&#0160;&#0160;&#0160; Set transformList = transObjects.CreateObjectCollection <br /><br />&#0160;<font color="#0000ff"><strong>&#0160;&#0160; &#39; Iterate through all of the occurrences. <br /></strong></font>&#0160;&#0160;&#0160; Dim occurrence As ComponentOccurrence <br />&#0160;&#0160;&#0160; For Each occurrence In assemblyDef.Occurrences <br />&#0160;<font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Add each occurrence to the list. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; occList.Add occurrence <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Add the transform to the list. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transformList.Add baseTransform <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Ground each occurrence.&#0160; This is ok to do here <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; because the move will ignore the ground condition. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; occurrence.Grounded = True <br />&#0160;&#0160;&#0160; Next <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Reposition all of the occurrences.&#0160; The TransformOccurrences <br />&#0160;&#0160;&#0160; &#39; method was new in Inventor 2009.&#0160; <br /></strong></font>&#0160;&#0160;&#0160; Set assemblyDef = assemblydoc.ComponentDefinition <br />&#0160;&#0160;&#0160; Call assemblyDef.TransformOccurrences(occList, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transformList) <br />End Sub</p></div>
<br />
<p>Of course these macros just the demonstrate one solution using the API to a specific problem.&#0160; The same functionality demonstrated above and combined with other API functions can be used in many other ways to solve other problems.&#0160; All I’m trying to say is that if the macros above don’t quite do what you need them to do it’s time to start investigating Inventor’s API so that you can modify them to solve your specific problems.</p>
