---
layout: "post"
title: "Setting the Weight for iPart Members"
date: "2009-02-10 21:32:27"
author: "Adam Nagy"
categories:
  - "Brian"
  - "Parts"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/02/setting-the-weight-for-ipart-members.html "
typepad_basename: "setting-the-weight-for-ipart-members"
typepad_status: "Publish"
---

<p>There was a question posted on the customization newsgroup that I spent a little time investigating and think the answer might be of general interest.&#0160; The objective is to have a column in the iPart table that has the weight for that member.&#0160; I wasn’t able to figure out a way to do this with built-in functionality in Inventor but it turned out it isn’t too difficult to write a program to accomplish the task.&#0160; Although the program and description below is specific to the weight of a part, it could be modified to handle other part information that you want to associate with an iPart member.</p>
<p>First, let’s look at the iPart factory to see what needs to exist for the program to function correctly.&#0160; The only thing special is that I created a custom iProperty called “Weight” and added that as one of the iProperties that I want to set from the table.&#0160; It didn’t have to be an iProperty and could have been an “Other” value but using an iProperty provides the most flexibility for using the value elsewhere in Inventor.&#0160; For example, in the the drawing.&#0160; The picture below shows the iPart table after setting it up with this iProperty.&#0160; The values for this new column are empty.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401116858fd95970c-pi"><img alt="iPartTable" border="0" height="275" src="/assets/image_236547.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="iPartTable" width="454" /></a> </p>
<br />
<p>Now we need to assign the correct weight for each row to the weight column.&#0160; If you had to this manually you would:</p>
<ol>
<li>Activate a member. 
<li>Run the iProperties command 
<li>Go to the “Physical” tab of the iProperties dialog. 
<li>Click the “Update” button on the “Physical” tab. 
<li>Select and Copy the “Mass” field. 
<li>Open the iPart table and paste the mass value into the table for the correct row. 
<li>Close the iPart table. 
<li>Repeat steps 1 to 7 for every row in the table. </li>
</li></li></li></li></li></li></li></ol>
<p>As you can see this is very tedious and prone to errors.&#0160; Instead of manually going through these steps they can be automated using Inventor’s programming interface.&#0160; Below is a VBA macro that will do the work. </p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub UpdateWeightOfiParts() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; ‘ Get the active document.&#0160; This assumes it is a part. <br /></strong></font>&#0160;&#0160;&#0160; Dim oPartDoc As PartDocument <br />&#0160;&#0160;&#0160; Set oPartDoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Check that this part is an iPart factory. <br /></strong></font>&#0160;&#0160;&#0160; If Not oPartDoc.ComponentDefinition.IsiPartFactory Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox &quot;This part must be an iPart factory.&quot; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160; End If <br /><br />&#0160;&#0160;&#0160; Dim oFactory As iPartFactory <br />&#0160;&#0160;&#0160; Set oFactory = oPartDoc.ComponentDefinition.iPartFactory <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Check that there&#39;s a &quot;Weight&quot; column in the iPart table,</strong></font></div>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new"><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; and get its index in the table. <br /></strong></font>&#0160;&#0160;&#0160; Dim iWeightColumnIndex As Long <br />&#0160;&#0160;&#0160; iWeightColumnIndex = GetColumnIndex(oFactory, &quot;Weight&quot;) <br />&#0160;&#0160;&#0160; If iWeightColumnIndex = -1 Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox &quot;The column &quot;&quot;weight&quot;&quot; does not exist in the table.&quot; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160; End If <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Iterate through the rows <br /></strong></font>&#0160;&#0160;&#0160; Dim oRow As iPartTableRow <br />&#0160;&#0160;&#0160; For Each oRow In oFactory.TableRows <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Make this the active row so the model will recompute. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oFactory.DefaultRow = oRow <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Get the weight. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim dWeight As Double <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; dWeight = oPartDoc.ComponentDefinition.MassProperties.Mass <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Convert it to current mass units defined by the document. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim strWeight As String <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; strWeight = oPartDoc.UnitsOfMeasure.GetStringFromValue( _&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; dWeight, kDefaultDisplayMassUnits) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Set the row value for the weight column. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oRow.Item(iWeightColumnIndex).Value = strWeight <br />&#0160;&#0160;&#0160; Next <br />End Sub <br /><br /><br /><font color="#0000ff"><strong>’ Function that given a factory and the name or a column will return <br />’ the index number of the column, if it’s found in the factory’s <br />’ table.&#0160; If the column is not found it returns –1.&#0160; The comparison <br />’ of the name is done in a case insensitive way. <br /></strong></font>Private Function GetColumnIndex(ByVal Factory As iPartFactory, _&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ByVal ColumnName As String) As Long <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; ‘ Iterate through all of the columns looking for a <br />&#0160;&#0160;&#0160; ‘ match to the input name. <br /></strong></font>&#0160;&#0160;&#0160; Dim i As Long <br />&#0160;&#0160;&#0160; For i = 1 To Factory.TableColumns.Count <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oColumn As iPartTableColumn <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oColumn = Factory.TableColumns.Item(i) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ‘ Compare this column with the input name. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If LCase(oColumn.DisplayHeading) = LCase(ColumnName) Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; A matching column was found so exit. <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GetColumnIndex = i <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Function <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; Next <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; The column wasn&#39;t found so return -1. <br /></strong></font>&#0160;&#0160;&#0160; GetColumnIndex = -1 <br />End Function</div>
<p></p>
<br />
<p>The program is essentially performing the same steps that would be required to do this manually.&#0160; It’s just able to do it much faster and without any mistakes.&#0160; After running the macro on my factory the table now looks like this.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105371e60a3970b-pi"><img alt="iPartTableAfter" border="0" height="276" src="/assets/image_677255.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="iPartTableAfter" width="454" /></a></p>
<br />
<p>It’s also important to recognize that the weight is a snapshot of the weight at the time the macro was run.&#0160; If the part is modified (for example, a new feature is added) or table values are edited that affect the part geometry, the weight will no longer be correct and the macro will need to be run again to update the weight column.</p>
