---
layout: "post"
title: "Controlling Part Colors"
date: "2009-02-05 00:18:39"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/02/controlling-part-colors.html "
typepad_basename: "controlling-part-colors"
typepad_status: "Publish"
---

<p>There was a recent discussion on the newsgroup regarding setting the color of a part.&#160; It’s not particularly easy to figure out the API to do this so I thought I would put together a little primer on the concepts and some sample code that demonstrates it.</p>  <p><strong><font size="3">Overall Color of a Part        <br /></font></strong>First, a part has a defined overall color.&#160; By default this is defined as “As Material” which means it will use whatever color is assigned to the current material.&#160; Using the material combo box in the part you can override this and change the part color to any other available color.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401116848128c970c-pi"><img title="PartColorList" style="border-top-width: 0px; display: inline; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="151" alt="PartColorList" src="/assets/image_700416.jpg" width="220" border="0" /></a>     <br /></p>  <p>The available colors are defined in the style library, which you can see using the Style and Standard Editor, as shown below.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401116848129a970c-pi"><img title="ColorStyleEditor" style="border-right: 0px; border-top: 0px; display: inline; border-left: 0px; border-bottom: 0px" height="326" alt="ColorStyleEditor" src="/assets/image_377179.jpg" width="434" border="0" /></a>     <br /></p>  <p>In the API, these colors are referred to as <em>RenderStyles</em>.&#160; Here’s a small program that sets the color of the active part to “Red”.&#160; When getting a render style you specify the style using its name.&#160; In the example below, if there isn’t a color named “Red” the line where it tries to get the color will fail.&#160; When using the Item property to get a specific RenderStyle the name specified is case insensitive so “Red”, “red” or “RED” will all work.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub SetPartColor()    <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument     <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get a reference to the RenderStyle named &quot;Red&quot;.        <br /></strong></font>&#160;&#160;&#160; Dim oRenderStyle As RenderStyle     <br />&#160;&#160;&#160; Set oRenderStyle = oPartDoc.RenderStyles.Item(&quot;Red&quot;)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Assign the render style to the part.        <br /></strong></font>&#160;&#160;&#160; oPartDoc.ActiveRenderStyle = oRenderStyle     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Force the view to update to see the change.        <br /></strong></font>&#160;&#160;&#160; ThisApplication.ActiveView.Update     <br />End Sub</div>  <p>   <br />If you want to set the part color back to “As Material” then you need to set the color currently assigned to part to be the render style associated with the active material.&#160; Inventor recognizes that the assigned render style is the same as that associated with the active material and will change the setting to “As Material”.&#160; This is demonstrated below.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub SetPartToMaterialColor()    <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument     <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument</div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160; Dim oPartDef As PartComponentDefinition</div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160; Set oPartDef = oPartDoc.ComponentDefinition    <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get a reference to the material render style.        <br /></strong></font>&#160;&#160;&#160; Dim oRenderStyle As RenderStyle     <br />&#160;&#160;&#160; Set oRenderStyle = oPartDef.Material.RenderStyle     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Assign the render style to the part.        <br /></strong></font>&#160;&#160;&#160; oPartDoc.ActiveRenderStyle = oRenderStyle     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Force the view to update to see the change.        <br /></strong></font>&#160;&#160;&#160; ThisApplication.ActiveView.Update     <br />End Sub</div>  <p>&#160;</p>  <p><strong><font size="3">Override Colors for Features and Faces        <br /></font></strong>What I’ve talked about so far is the overall color for the part.&#160; It’s also possible to assign override colors to faces and features.&#160; In the user-interface this is done by right-clicking on the feature or the face and running the <strong>Properties</strong> command from the context menu.&#160; As you can see in the pictures below, the Properties dialogs for a feature and face allow you to select a color style for the feature or face.&#160; These override the color defined by the part for that specific feature or face.&#160; There’s a level of priority when assigning colors.&#160; The part color colors the entire part.&#160; A feature color overrides the part color and colors the feature.&#160; A face color override the part or feature color and will color the face.&#160; To remove the override of a face you set it’s color style to “As Feature” or “As Part” and to remove the override from a feature you set it to “As Part”.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105370dc355970b-pi"><img title="FeatureColor" style="border-top-width: 0px; display: inline; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="319" alt="FeatureColor" src="/assets/image_484883.jpg" width="224" border="0" /></a>&#160; <a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340105370dc35c970b-pi"><img title="FaceColor" style="border-top-width: 0px; display: inline; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="109" alt="FaceColor" src="/assets/image_767543.jpg" width="224" border="0" /></a>     <br /></p>  <p>Below is an example program that sets the color of a feature and a face.&#160; It uses the second feature created in the active part and an arbitrary face of that feature.</p>  <p></p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub SetFeatureAndFaceColor()    <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument     <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the second feature.        <br /></strong></font>&#160;&#160;&#160; Dim oFeature As PartFeature     <br />&#160;&#160;&#160; Set oFeature = oPartDoc.ComponentDefinition.Features.Item(2)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Set the color of the feature to &quot;Yellow&quot;        <br /></strong></font>&#160;&#160;&#160; Call oFeature.SetRenderStyle(kOverrideRenderStyle, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPartDoc.RenderStyles.Item(&quot;Yellow&quot;))     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get one of the faces of the feature.&#160;&#160; <br />&#160;&#160;&#160; ' This could be any face in the part.         <br /></strong></font>&#160;&#160;&#160; Dim oFace As Face     <br />&#160;&#160;&#160; Set oFace = oFeature.Faces.Item(1)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Set the color of the face to &quot;Green&quot;        <br /></strong></font>&#160;&#160;&#160; Call oFace.SetRenderStyle(kOverrideRenderStyle, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPartDoc.RenderStyles.Item(&quot;Green&quot;))     <br />End Sub</div>  <p>   <br />The example below removes these color overrides and resets all features to use the part color and all faces to use the feature color.&#160; </p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub RemoveFeatureAndFaceColorOverrides()    <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument     <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument </div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160; Dim oPartDef As PartComponentDefinition</div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160; Set oPartDef = oPartDoc.ComponentDefinition    <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Iterate through all features.        <br /></strong></font>&#160;&#160;&#160; Dim oFeature As PartFeature     <br />&#160;&#160;&#160; For Each oFeature In oPartDoc.ComponentDefinition.Features     <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Set the render style to be &quot;As Part&quot;.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oFeature.SetRenderStyle(kPartRenderStyle)     <br />&#160;&#160;&#160; Next     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Iterate through all faces.        <br /></strong></font>&#160;&#160;&#160; Dim oFace As Face     <br />&#160;&#160;&#160; For Each oFace In oPartDef.SurfaceBodies.Item(1).Faces     <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Set the render style to be &quot;As Feature&quot;.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oFace.SetRenderStyle(kFeatureRenderStyle)     <br />&#160;&#160;&#160; Next     <br />End Sub</div>  <p>&#160;</p>  <p>Part models can have very many faces and typically only a few of those will have color overrides.&#160; Iterating and setting every face can be expensive.&#160; To improve performance there is a trick to quickly find only those faces that have overrides.&#160; The trick takes advantage of the fact that face color overrides are implemented internally using standard API attributes.&#160; The program below does the same thing as the previous program but uses this trick so it will be more efficient on large models. </p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub RemoveFeatureAndFaceColorOverrides2()    <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument     <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Iterate through all features.        <br /></strong></font>&#160;&#160;&#160; Dim oFeature As PartFeature     <br />&#160;&#160;&#160; For Each oFeature In oPartDoc.ComponentDefinition.Features     <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Set the render style to be &quot;As Part&quot;.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oFeature.SetRenderStyle(kPartRenderStyle)     <br />&#160;&#160;&#160; Next     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get all of the faces that have the &quot;FaceColor&quot; attribute.        <br /></strong></font>&#160;&#160;&#160; Dim oFaces As ObjectCollection     <br />&#160;&#160;&#160; Set oFaces = oPartDoc.AttributeManager.FindObjects( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;com.autodesk.inventor.FaceAttributes&quot;, &quot;FaceColor&quot;)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Iterate through all faces that have colors.        <br /></strong></font>&#160;&#160;&#160; Dim oFace As Face     <br />&#160;&#160;&#160; For Each oFace In oFaces     <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Set the render style to be &quot;As Feature&quot;.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oFace.SetRenderStyle(kFeatureRenderStyle)     <br />&#160;&#160;&#160; Next     <br />End Sub</div>  <p>&#160;</p>  <p>If you want to find out what the current color of a feature or face is you can use the GetRenderStyle method.&#160; This returns the current color of the feature or face and also indicates why it is that color.&#160; For example, if you get the color of a face it can be that color because of the part color, feature color, or the face color.&#160; In most cases you probably don’t care why it’s the color it is and can just use the color returned and ignore why it’s that color.&#160; The sample below displays the name of the color of the selected feature or face and why it’s that color.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub ShowPartColors()    <br />&#160;&#160;&#160; Dim oPartDoc As PartDocument     <br />&#160;&#160;&#160; Set oPartDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Check that an entity is selected.        <br /></strong></font>&#160;&#160;&#160; If oPartDoc.SelectSet.Count &lt;&gt; 1 Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A feature or face must be selected.&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160; End If     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Check to see if it is a face or feature that's selected.        <br /></strong></font>&#160;&#160;&#160; Dim ColorSource As StyleSourceTypeEnum     <br />&#160;&#160;&#160; Dim oRenderStyle As RenderStyle     <br />&#160;&#160;&#160; If TypeOf oPartDoc.SelectSet.Item(1) Is PartFeature Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oFeature As PartFeature     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oFeature = oPartDoc.SelectSet.Item(1)     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oRenderStyle = oFeature.GetRenderStyle(ColorSource)     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;Feature color: &quot; &amp; oRenderStyle.Name &amp; vbCr &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Reason: &quot; &amp; StyleSourceTypeEnumName(ColorSource)     <br />&#160;&#160;&#160; ElseIf TypeOf oPartDoc.SelectSet.Item(1) Is Face Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim oFace As Face     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oFace = oPartDoc.SelectSet.Item(1)     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set oRenderStyle = oFace.GetRenderStyle(ColorSource)     <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;Face color: &quot; &amp; oRenderStyle.Name &amp; vbCr &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Reason: &quot; &amp; StyleSourceTypeEnumName(ColorSource)     <br />&#160;&#160;&#160; Else     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A feature or face must be selected.&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160; End If     <br />End Sub     <br />    <br />    <br /><font color="#0000ff"><strong>' Utility function used to get a readable name for an enum value.        <br /></strong></font>Private Function StyleSourceTypeEnumName( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; EnumValue As StyleSourceTypeEnum) As String     <br />&#160;&#160;&#160; Select Case EnumValue     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kFeatureRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Feature color&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kOverrideRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Override color&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kPartRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Part color&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kWeldBeadRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Weld bead color&quot;     <br />&#160;&#160;&#160; End Select     <br />End Function</div>  <p>&#160;</p>  <p><font size="3"><strong>Override Colors for Occurrences in an Assembly</strong></font>     <br />The concepts of applying an override color also apply when coloring objects in an assembly.&#160; The default color of any part in an assembly is the color defined in the part.&#160; You can choose to override the part color and assign any other color.&#160; In an assembly, the override applies to the entire occurrence.&#160; You override the color of a part in the user-interface by selecting a part and then choosing a color from the color combo box, as shown below. You can’t override the color of feature or faces in an assembly, only the entire part.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401116848128c970c-pi"><img title="PartColorList" style="border-top-width: 0px; display: inline; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="151" alt="PartColorList" src="/assets/image_700416.jpg" width="220" border="0" /></a>    <br /></p>  <p>The ComponentOccurrence object supports both the SetRenderStyle and GetRenderStyle methods.&#160; A ComponentOccurrence object can represent an individual part or a subassembly.&#160; If you set the render style of a component occurrence that represents a part it will override the color for that single instance of the part.&#160; If you set it for a component occurrence that represents a subassembly it will override the color for all of the parts within the subassembly.&#160; The sample below illustrates this by randomly setting the color of all of the top-level occurrences in an assembly.&#160; The occurrences can be parts or subassemblies.&#160;&#160; Remember, this is overriding the color as defined by the part.&#160; </p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub SetOccurrenceOverrideColors()    <br />&#160;&#160;&#160; Dim oAsmDoc As AssemblyDocument     <br />&#160;&#160;&#160; Set oAsmDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Initialize the random number generator and get        <br />&#160;&#160;&#160; ' the number of render styles defined.         <br /></strong></font>&#160;&#160;&#160; Randomize     <br />&#160;&#160;&#160; Dim iColorCount As Long     <br />&#160;&#160;&#160; iColorCount = oAsmDoc.RenderStyles.Count     <br />    <br />&#160;&#160;&#160; <font color="#0000ff"><strong>' Iterate through the top-level occurrences in the assembly.</strong></font>     <br />&#160;&#160;&#160; Dim oOcc As ComponentOccurrence     <br />&#160;&#160;&#160; For Each oOcc In oAsmDoc.ComponentDefinition.Occurrences     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff"><strong>' Set the color to a random color.</strong></font>     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oOcc.SetRenderStyle(kOverrideRenderStyle, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oAsmDoc.RenderStyles.Item(Int((iColorCount * Rnd) + 1)))     <br />&#160;&#160;&#160; Next     <br />End Sub</div>  <p>&#160;</p>  <p>This next sample goes through the top-level occurrences in an assembly and removes any color overrides so they all revert back to the original part color.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub RemoveOccurrenceOverrideColors()    <br />&#160;&#160;&#160; Dim oAsmDoc As AssemblyDocument     <br />&#160;&#160;&#160; Set oAsmDoc = ThisApplication.ActiveDocument     <br />    <br />&#160;&#160;&#160; <font color="#0000ff"><strong>' Iterate through the top-level occurrences in the assembly.</strong></font>     <br />&#160;&#160;&#160; Dim oOcc As ComponentOccurrence     <br />&#160;&#160;&#160; For Each oOcc In oAsmDoc.ComponentDefinition.Occurrences     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff"><strong>' Set each occurrence to use the part defined color.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call oOcc.SetRenderStyle(kPartRenderStyle)     <br />&#160;&#160;&#160; Next     <br />End Sub</div>  <p>&#160;</p>  <p>This final sample is similar to the previous part sample that reports the color of the selected feature or face except this reports the color of the selected occurrence.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub ShowOccurrenceColor()    <br />&#160;&#160;&#160; Dim oAsmDoc As AssemblyDocument     <br />&#160;&#160;&#160; Set oAsmDoc = ThisApplication.ActiveDocument     <br />    <br />&#160;&#160;&#160; <font color="#0000ff"><strong>' Check that an occurence is selected.        <br /></strong></font>&#160;&#160;&#160; Dim oOcc As ComponentOccurrence     <br />&#160;&#160;&#160; On Error Resume Next     <br />&#160;&#160;&#160; Set oOcc = oAsmDoc.SelectSet.Item(1)     <br />&#160;&#160;&#160; If Err Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;An occurrence must be selected.&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; On Error GoTo 0     <br />    <br />&#160;&#160;&#160; <font color="#0000ff"><strong>' Check to see if it is a face or feature that's selected.        <br /></strong></font>&#160;&#160;&#160; Dim ColorSource As StyleSourceTypeEnum     <br />&#160;&#160;&#160; Dim oRenderStyle As RenderStyle     <br />&#160;&#160;&#160; Set oRenderStyle = oOcc.GetRenderStyle(ColorSource)     <br />&#160;&#160;&#160; MsgBox &quot;Occurence color: &quot; &amp; oRenderStyle.Name &amp; vbCr &amp; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Reason: &quot; &amp; StyleSourceTypeEnumName(ColorSource)     <br />End Sub     <br />    <br />    <br /><font color="#0000ff"><strong>' Utility function used to get a readable name for an enum value.        <br /></strong></font>Private Function StyleSourceTypeEnumName( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; EnumValue As StyleSourceTypeEnum) As String     <br />&#160;&#160;&#160; Select Case EnumValue     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kFeatureRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Feature color&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kOverrideRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Override color&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kPartRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Part color&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Case kWeldBeadRenderStyle     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; StyleSourceTypeEnumName = &quot;Weld bead color&quot;     <br />&#160;&#160;&#160; End Select     <br />End Function</div>
