---
layout: "post"
title: "Accessing Assembly Components"
date: "2009-03-05 00:45:45"
author: "Adam Nagy"
categories:
  - "Assemblies"
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/03/accessing-assembly-components.html "
typepad_basename: "accessing-assembly-components"
typepad_status: "Publish"
---

<p>A common need when working with an assembly is accessing the components that make up the assembly.&#0160; This reason to do this can be for a lot of reasons from creating your own custom BOM to editing parameter values within certain parts.&#0160; Here’s a quick overview of how to access its components.&#0160; (For this discussion I’m going to focus only on the parts and subassemblies within an assembly and not anything else that can be in an assembly; constraints, assembly features, level of detail, etc.)</p>
<p><strong><font size="3">What is an Assembly?</font></strong> <br />For the topic at hand, an assembly can be thought of as a container that contains instances of parts and other assembles.&#0160; Each instance (or occurrence) defines a position within the assembly and other properties that define the appearance and behavior (color, visibility, adaptive, etc.) of the instance.&#0160; An instance doesn’t contain any geometry but displays the geometry that it gets from the referenced part.&#0160; A part can be referenced once and then instanced many times by displaying that single part in different locations in the assembly.&#0160; Below is the example assembly I’ll use to illustrate.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834011168baac16970c-pi"><img alt="AssemblyStructureAssembly" border="0" height="294" src="/assets/image_673869.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="AssemblyStructureAssembly" width="454" /></a> </p>
<br />
<p>Below is the browser for this assembly.&#0160; You can see that the assembly consists of 14 occurrences where two of these are subassemblies and 12 of them are parts.&#0160; There is one unique subassembly and 5 unique parts, which is illustrated in the view of Windows Explorer shown below.&#0160; The geometry for the parts only exists within the five .ipt files.&#0160; The assembly references these parts and displays their graphics at positions defined by the location of the occurrence that represents the part.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340112792f5be328a4-pi"><img alt="AssemblyStructureBrowser" border="0" height="383" src="/assets/image_512111.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="AssemblyStructureBrowser" width="465" /></a> </p>
<p>Here are some API terms you should be familiar with for the rest of the discussion:</p>
<blockquote>
<p><em><strong>ComponentOccurrence</strong></em> – This is the API object that represents an occurrence within an assembly.&#0160; A ComponentOccurrence can represent a subassembly or part and can be at any level of the assembly.&#0160; The example assembly above is represented by 14 ComponentOccurrence API objects.</p>
<p><em><strong>File Reference</strong> – </em>This is the reference between the assembly to the subassemblies and parts it contains.&#0160; In the example above there are six file references within the assembly to the various subassemblies and parts that are referenced.&#0160; There is only ever one file reference for a particular file.&#0160; For example, even though there are four Pillar parts, there is only one file reference between the assembly and the Pillar.ipt file.&#0160; For more information about file references see the previous post <a href="http://modthemachine.typepad.com/my_weblog/2008/11/understanding-file-references.html" title="Understanding File References">Understanding File References</a>.</p>
<p><em><strong>Leaf Occurrences</strong></em> – These are occurrences that define the end of each branch as you traverse an assembly.&#0160; In Inventor all parts are considered leaf occurrences.</p></blockquote>
<p>There are a few ways to access the occurrences of an assembly.&#0160; Which one to use depends on what you’ll be doing with the results.&#0160; Below are descriptions and samples illustrating each one.</p>
<p><strong><font size="3">Assembly Structure</font> <br /></strong>The first method is to access the full assembly structure.&#0160; This provides all of the occurrences and the full assembly tree, just as you see it in the browser.&#0160; This provides the complete view of the assembly and should be a sufficient amount of information for any task that needs the complete structure.&#0160; </p>
<p>Writing a program to access the full assembly tree is the most difficult of the approaches discussed here.&#0160; This is because an assembly tree is not a pre-defined size.&#0160; An assembly can have any number of levels with each level having any number of occurrences.&#0160; It’s a tree with any number of branches.&#0160; To get the full assembly structure you need to walk down every branch until you reach every leaf.&#0160; To handle a problem like this you need to use a recursive function, which is demonstrated in the code below. </p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub TraverseAssemblySample() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the active assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oAsmDoc As AssemblyDocument <br />&#0160;&#0160;&#0160; Set oAsmDoc = ThisApplication.ActiveDocument <br />&#0160;&#0160;&#0160; Debug.Print oAsmDoc.DisplayName <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Call the function that does the recursion. <br /></strong></font>&#0160;&#0160;&#0160; Call TraverseAssembly(oAsmDoc.ComponentDefinition.Occurrences, 1) <br />End Sub <br /><br />Private Sub TraverseAssembly(Occurrences As ComponentOccurrences, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Level As Integer) <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Iterate through all of the occurrence in this collection.&#0160; This <br />&#0160;&#0160;&#0160; &#39; represents the occurrences at the top level of an assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oOcc As ComponentOccurrence <br />&#0160;&#0160;&#0160; For Each oOcc In Occurrences <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Print the name of the current occurrence. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Debug.Print Space(Level * 3) &amp; oOcc.Name <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Check to see if this occurrence represents a subassembly <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; and recursively call this function to traverse through it. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If oOcc.DefinitionDocumentType = kAssemblyDocumentObject Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call TraverseAssembly(oOcc.SubOccurrences, Level + 1) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; Next <br />End Sub</div>
<p></p>
<br />
<p>The TraverseAssemblySample sub gets the active assembly document and calls the TraverseAssembly sub, passing in the collection of occurrences from the top-level assembly.&#0160; The Occurrences property of the AssemblyComponentDefinition object and the SubOccurrences property of the ComponentOccurrence object only return the occurrences directly within that assembly, not in any of its subassemblies.&#0160; The TraverseAssembly Sub then does all the work to walk the tree.&#0160; It iterates through each occurrences in the collection and for this sample,&#0160; prints out the name of each occurrence, but anything could be done with the occurrence at that point.&#0160; The next thing it does is what’s the most interesting; it checks to see if the occurrence is a subassembly or a part and if it is a subassembly it calls the TraverseAssembly sub again, passing the collection of occurrences in that subassembly.&#0160; The fact that the sub is calling itself is recursion.&#0160; It continues this process until it’s completely walked the assembly tree. <br /><br />When running the program using the previous sample assembly, the following is written into the VBA Immediate window.&#0160; You can compare this with the browser view of the assembly and see that they match.</p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Sample.iam <br />&#0160;&#0160; Floor:1 <br />&#0160;&#0160; Arch:1 <br />&#0160;&#0160;&#0160;&#0160;&#0160; CurvedSupport:1 <br />&#0160;&#0160;&#0160;&#0160;&#0160; CurvedSupport:2 <br />&#0160;&#0160;&#0160;&#0160;&#0160; ArchTop:1 <br />&#0160;&#0160; Arch:2 <br />&#0160;&#0160;&#0160;&#0160;&#0160; CurvedSupport:1 <br />&#0160;&#0160;&#0160;&#0160;&#0160; CurvedSupport:2 <br />&#0160;&#0160;&#0160;&#0160;&#0160; ArchTop:1 <br />&#0160;&#0160; Pillar:1 <br />&#0160;&#0160; Pillar:2 <br />&#0160;&#0160; Pillar:3 <br />&#0160;&#0160; Pillar:4 <br />&#0160;&#0160; Inventor:1</div>
<br />
<p>There are a couple of things to point out in the program.&#0160; One is the “Level” argument of the TraverseAssembly sub.&#0160; This is used to keep track of what level of the assembly the program is currently at so it can correctly indent the output of the tree and is not required to walk an assembly tree.&#0160; The area of the code that you would replace to do the work you want to perform with each occurrence is the line where it prints out the occurrence name.&#0160; This line is executed for every occurrence in the assembly.&#0160; You can replace this with code that performs whatever functionality you need to accomplish.&#0160; For example, if you need to create a custom BOM your code might access the document that’s referenced by this occurrence and extract some iProperty values and then print this out as part of a structured BOM. <br /></p>
<p><strong><font size="3">Occurrence Lists</font>&#0160; <br /></strong>For several releases of Inventor the only way to access the assembly through the API was to traverse the entire tree, as shown above.&#0160; Often you don’t need the tree structure but just want a simple list of the contents of the assembly.&#0160; There are a couple of properties that provide this simpler access to the assembly contents.</p>
<p><strong>All Leaf Occurrences <br /></strong>This first example uses the AllLeafOccurrences property of the ComponentOccurrences object which returns a collection that contains all of the leaf occurrences of an entire assembly.&#0160; the leaf occurrences at every level of the assembly are returned in this single collection.&#0160; Remember that the leaf occurrences are the parts, so this won’t contain any subassembly occurrences.&#0160; The AllLeafOccurrences property also has one optional argument, (that isn’t used in the sample below), that provides some additional flexibility by allowing you to get only the leaf occurrences for a specified subassembly.</p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub GetPartOccurrences() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the active assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oAsmDoc As AssemblyDocument <br />&#0160;&#0160;&#0160; Set oAsmDoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the assembly component definition. <br /></strong></font>&#0160;&#0160;&#0160; Dim oAsmDef As AssemblyComponentDefinition <br />&#0160;&#0160;&#0160; Set oAsmDef = oAsmDoc.ComponentDefinition <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get all of the leaf occurrences of the assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oLeafOccs As ComponentOccurrencesEnumerator <br />&#0160;&#0160;&#0160; Set oLeafOccs = oAsmDef.Occurrences.AllLeafOccurrences <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Iterate through the occurrences and print the name. <br /></strong></font>&#0160;&#0160;&#0160; Dim oOcc As ComponentOccurrence <br />&#0160;&#0160;&#0160; For Each oOcc In oLeafOccs <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Debug.Print oOcc.Name <br />&#0160;&#0160;&#0160; Next <br />End Sub</div>
<p></p>
<br />
<p>When the above program is run on the sample assembly the following is written to the VBA Immediate window.&#0160; Making the single call is much simpler than traversing the entire assembly looking for part occurrences.</p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Floor:1 <br />CurvedSupport:1 <br />CurvedSupport:2 <br />ArchTop:1 <br />CurvedSupport:1 <br />CurvedSupport:2 <br />ArchTop:1 <br />Pillar:1 <br />Pillar:2 <br />Pillar:3 <br />Pillar:4 <br />Inventor:1 </div>
<p><br /><strong>All Occurrences of a Specified Component <br /></strong>You can also get all of the occurrences that reference a specific document.&#0160; For example, you might need to access every instance of a specific fastener in an assembly to replace it with another.&#0160; To find every occurrence that references a specified document you can use the AllReferencedOccurrences property of the ComponentOccurrences object.&#0160; This property has a single required argument that specifies which part or assembly you want the referencing occurrences for.&#0160; It will return all of the occurrences at all levels of the assembly that reference the specified document.&#0160; The sample below illustrates this. </p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub FindOccurrences() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the active assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oAsmDoc As AssemblyDocument <br />&#0160;&#0160;&#0160; Set oAsmDoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the definition of the assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oAsmDef As AssemblyComponentDefinition <br />&#0160;&#0160;&#0160; Set oAsmDef = oAsmDoc.ComponentDefinition <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the document to find occurrences for. Since it’s assumed <br />&#0160;&#0160;&#0160; &#39; there is at least one occurrence in the assembly that&#0160; <br />&#0160;&#0160;&#0160; &#39; references this document, it will already be open since it <br />&#0160;&#0160;&#0160; &#39; was opened when the assembly was opened. <br /></strong></font>&#0160;&#0160;&#0160; Dim oDoc As Document <br />&#0160;&#0160;&#0160; Set oDoc = ThisApplication.Documents.ItemByName( _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &quot;C:\AssemblySample\Pillar.ipt&quot;) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the occurrences that represent this document. <br /></strong></font>&#0160;&#0160;&#0160; Dim oOccs As ComponentOccurrencesEnumerator <br />&#0160;&#0160;&#0160; Set oOccs = oAsmDef.Occurrences.AllReferencedOccurrences(oDoc) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Print the occurrences to the Immediate window. <br /></strong></font>&#0160;&#0160;&#0160; Dim oOcc As ComponentOccurrence <br />&#0160;&#0160;&#0160; For Each oOcc In oOccs <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Debug.Print oOcc.Name <br />&#0160;&#0160;&#0160; Next <br />End Sub</div>
<p></p>
<p><br />The output for this program is shown below.</p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Pillar:1 <br />Pillar:2 <br />Pillar:3 <br />Pillar:4</div>
<p></p>
<p><br />Getting a single list of specific occurrences is easier than traversing through the assembly but you also lose the assembly context that you get when traversing.&#0160; However, there are a few properties supported by the occurrence that provide this information in various ways.&#0160; If you ever need this kind of information look at the ContainingOccurrence, OccurrencePath, and ParentOccurrence properties of the ComponentOccurrence object. <br /></p>
<p><strong><font size="3">All Referenced Documents</font> <br /></strong>Another common need when working with an assembly is to access the unique documents referenced by the assembly, because in many cases you don’t need individual access to each occurrence.&#0160; For example, let’s say you want to change the material of all parts to a certain material.&#0160; You can do that with either one of the two previous programs by adding code that takes a given occurrence, gets the associated document, and changes its material.&#0160; The problem is that you’ll end up doing a lot more work than is necessary.&#0160; For example, in the sample assembly you’ll end up setting the material for the pillar part four times since it’s used that many times in the assembly, where you really only need to set it once for Pillar.ipt.</p>
<p>You can do this using the list of references instead of the occurrences since there is only one reference to each document regardless of how many times it’s used in the assembly.&#0160; The AllReferencedDocuments property of the AssemblyDocument object provides this.&#0160; It returns the complete set of referenced documents for the entire assembly regardless of the level in the assembly the reference actually occurs.</p>
<p>Here’s a simple example that illustrates this.</p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub ShowReferences() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the active assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oAsmDoc As AssemblyDocument <br />&#0160;&#0160;&#0160; Set oAsmDoc = ThisApplication.ActiveDocument 
<p></p>
<p><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get all of the referenced documents.</strong></font> <br />&#0160;&#0160;&#0160; Dim oRefDocs As DocumentsEnumerator <br />&#0160;&#0160;&#0160; Set oRefDocs = oAsmDoc.AllReferencedDocuments <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Iterate through the list of documents. <br /></strong></font>&#0160;&#0160;&#0160; Dim oRefDoc As Document <br />&#0160;&#0160;&#0160; For Each oRefDoc In oRefDocs <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Debug.Print oRefDoc.DisplayName <br />&#0160;&#0160;&#0160; Next <br />End Sub</p></div>
<p></p>
<p><br />And here are the results when this sample is run.</p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Pillar.ipt <br />Inventor.ipt <br />ArchTop.ipt <br />CurvedSupport.ipt <br />Arch.iam <br />Floor.ipt 
<p></p></div>
<br />
<p>Here’s a more complex sample that uses this to demonstrate setting the material of every referenced part to Gold.</p>
<p></p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">Public Sub ChangeAllPartMaterial() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the active assembly document. <br /></strong></font>&#0160;&#0160;&#0160; Dim oAsmDoc As AssemblyDocument&#0160; <br />&#0160;&#0160;&#0160; Set oAsmDoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the material to assign to all of the parts. <br /></strong></font>&#0160;&#0160;&#0160; Dim strMaterialName As String <br />&#0160;&#0160;&#0160; strMaterialName = &quot;Gold&quot; <br /><br />&#0160;&#0160;&#0160; Dim oMaterial As Material <br />&#0160;&#0160;&#0160; On Error Resume Next <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Try to get the material of the specified name. <br /></strong></font>&#0160;&#0160;&#0160; Set oMaterial = oAsmDoc.Materials.Item(strMaterialName) <br />&#0160;&#0160;&#0160; If Err Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; MsgBox &quot;The material &quot;&quot;&quot; &amp; strMaterialName &amp; _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &quot;&quot;&quot; was not found in the library.&quot; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; On Error GoTo 0 <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Iterate through all of the documents refrenced by the assembly. <br /></strong></font>&#0160;&#0160;&#0160; Dim oDoc As Document <br />&#0160;&#0160;&#0160; For Each oDoc In oAsmDoc.AllReferencedDocuments <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Check to see if this is a part. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If oDoc.DocumentType = kPartDocumentObject Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim oPartDoc As PartDocument <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set oPartDoc = oDoc <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &#39; Set the material. <br /></strong></font>&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oPartDoc.ComponentDefinition.Material = oMaterial <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; Next <br />End Sub </div>
