---
layout: "post"
title: "Running Commands Using the API"
date: "2009-03-30 23:46:45"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/03/running-commands-using-the-api.html "
typepad_basename: "running-commands-using-the-api"
typepad_status: "Publish"
---

<p>Occasionally there is a need to run an Inventor command from a program.&#160; There are a couple of reasons why you might want to do this.&#160; One is when the API doesn’t support some functionality but Inventor does.&#160; By running the command you can sometimes work around the API deficiency.&#160; Another reason is when you want to take advantage of the interactive behavior of a command by starting a command and then turning it over to the user finish it.</p>  <p><font size="3"><strong>Running a Command in Inventor        <br /></strong></font>It turns out that it’s fairly simple to run any command in Inventor.&#160; This includes Inventor’s standard commands and also Add-In commands.&#160; In the API, every command is represented as a ControlDefinition object.&#160; The ControlDefinition object supports the Execute method which is the equivalent of clicking on a button and running a command in the user-interface.&#160; Below is an example that executes the Line command in a sketch.</p>  <p></p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub RunLineCommand()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the CommandManager object.        <br /></strong></font>&#160;&#160;&#160; Dim oCommandMgr As CommandManager     <br />&#160;&#160;&#160; Set oCommandMgr = ThisApplication.CommandManager     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get control definition for the line command.        <br /></strong></font>&#160;&#160;&#160; Dim oControlDef As ControlDefinition     <br />&#160;&#160;&#160; Set oControlDef = oCommandMgr.ControlDefinitions.Item( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;SketchLineCmd&quot;)&#160; <br />&#160;&#160;&#160; ' Execute the command.     <br />&#160;&#160;&#160; Call oControlDef.Execute     <br />End Sub</div>  <p></p>  <p>&#160;</p>  <p><font size="3"><strong>Getting Command Names</strong></font>     <br />The tricky part in using the code above is knowing what the name of the command is that you want to run.&#160; In the example above it uses “SketchLineCmd” to specify the Line command.&#160; Every control definition has a name that uniquely identifies it.&#160; There are a couple of techniques you can use to find out the name of the desired command.&#160; The first is to use a program to create a list of all of the available commands.&#160; The program below, (which is straight from Inventor’s programming help), does this.&#160; It will create a file named “C:\Temp\CommandNames.txt” that contains a list showing the name and description of every command.&#160; You can open this file using Notepad or another text editor and search for the command you’re interested in.&#160; Command names are typically very similar to the command name you see in the user-interface.</p>  <p></p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Sub PrintCommandNames()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the CommandManager object.        <br /></strong></font>&#160;&#160;&#160; Dim oCommandMgr As CommandManager     <br />&#160;&#160;&#160; Set oCommandMgr = ThisApplication.CommandManager     <br />&#160;&#160;&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the collection of control definitions.        <br /></strong></font>&#160;&#160;&#160; Dim oControlDefs As ControlDefinitions     <br />&#160;&#160;&#160; Set oControlDefs = oCommandMgr.ControlDefinitions     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Open the file and print out a header line.        <br /></strong></font>&#160;&#160;&#160; Dim oControlDef As ControlDefinition     <br />&#160;&#160;&#160; Open &quot;C:\temp\CommandNames.txt&quot; For Output As #1     <br />&#160;&#160;&#160; Print #1, Tab(10); &quot;Command Name&quot;; Tab(75); _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Description&quot;; vbNewLine     <br />    <br /><font color="#0000ff">&#160;&#160;&#160; ' Iterate through the controls and write out the name.      <br /></font>&#160;&#160;&#160; For Each oControlDef In oControlDefs     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Print #1, oControlDef.InternalName; Tab(55); _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oControlDef.DescriptionText     <br />&#160;&#160;&#160; Next     <br />    <br /><font color="#0000ff">&#160;&#160;&#160; ' Close the file.      <br /></font>&#160;&#160;&#160; Close #1     <br />End Sub</div>  <p></p>  <p>   <br />Another technique to find a command name is to use the Event Watcher utility that’s delivered as part of Inventor’s SDK.&#160; This utility lets you listen to the various events that Inventor supports through the API.&#160; One of these events is sent whenever a command is executed within Inventor and as part of that event it provides the name of the command that was executed.&#160; To use this follow the steps below.</p>  <ol>   <li>Have Inventor running and in a state where the command you want to use is available.&#160; For example, if you want to know the name of the Circle command you will need to have a sketch active.      <br /></li>    <li>Run EventWatcher.exe.&#160; On a Windows Vista install this is typically at:      <br /><font face="Arial Narrow" size="1">       <br />C:\Users\Public\Documents\Autodesk\Inventor 2009\SDK\DeveloperTools\Tools\EventWatcher\bin\Release         <br /></font>      <br />On a Windows XP install it is typically at:       <br /><font face="Arial Narrow" size="1">       <br />C:\Program Files\Autodesk\Inventor 2009\SDK\DeveloperTools\Tools\EventWatcher\bin\Release         <br /></font>      <br />If you can’t find it, it’s likely you haven’t installed the developer tools portion of the SDK.&#160; To do that install DeveloperTools.msi, which is in the SDK directory.&#160; If you’re running Vista you’ll need to disable UAC to successfully install the developer tools.       <br /></li>    <li>In EventWatcher, find the event UserInputEvents.OnActivateCommand and make sure the event has a check mark beside it.      <br /></li>    <li>Run the whatever command in Inventor that you want to find the name for.      <br /></li>    <li>Get the command name from EventWatcher.&#160; The picture below shows the EventWatcher interface with the OnActivateCommand selected and the results after running the New Sketch and Sketch Line commands. </li> </ol>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401156f985477970b-pi"><img title="EventWatcher" style="border-top-width: 0px; display: inline; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="302" alt="EventWatcher" src="/assets/image_969720.jpg" width="454" border="0" /></a> </p>  <p>&#160;</p>  <p><font size="3"><strong>Limitations</strong></font>     <br />Being able to run any command using the API may seem like the answer to the problem where the API doesn’t cover all of Inventor’s functionality.&#160; Unfortunately this isn’t a solution to that problem.&#160; When you execute a command using the functionality discussed above it is exactly the same as if you had clicked on the command in the user-interface; the command is started.&#160; The problem is that most commands need additional input from the user.&#160; For example, the Extrude command displays a dialog to get the required input from the user or the Arrange Dimensions command doesn’t have a dialog but does require the user to select the set of dimensions to arrange.</p>  <p>In general, when running a command using the API you can’t provide the input the command is expecting so you can’t fully control and use the command via the API.&#160; There are a couple of exceptions to this discussed below but for most commands you can only start them through the API.&#160; This is still useful because there are cases where you only want to start a command and then let the user take over.</p>  <p><font size="3"><strong>Providing Input to Commands</strong></font>     <br />As mentioned above, there are some exceptions about providing input to commands that will allow you to better utilize them from the API.&#160; There are two techniques of providing input to a command.&#160; The first is pre-selecting the entities that the command should process.&#160; This will only work for a small set of commands but is a workaround in a few cases where the API doesn’t directly support the equivalent of the command functionality.</p>  <p>An example of the use of pre-selecting entities is the new Arrange Dimensions command in Inventor 2010.&#160; The API doesn’t support this functionality yet but by using this pre-selection technique you can use the command directly.&#160; You select entities by adding them to the SelectSet object.&#160; This is the equivalent of the user selecting them.&#160; Many commands will check to see if valid entities are selected and operate on them if they are.&#160; The program below takes advantage of this.&#160; </p>  <p></p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub ArrangeDimensions()    <br /><font color="#0000ff">&#160;&#160;&#160; <strong>' Get the active document, assuming it is a drawing.        <br /></strong></font>&#160;&#160;&#160; Dim oDrawDoc As DrawingDocument     <br />&#160;&#160;&#160; Set oDrawDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the collection of dimensions on the active sheet.        <br /></strong></font>&#160;&#160;&#160; Dim oDimensions As DrawingDimensions     <br />&#160;&#160;&#160; Set oDimensions = oDrawDoc.ActiveSheet.DrawingDimensions     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get a reference to the select set and clear it.        <br /></strong></font>&#160;&#160;&#160; Dim oSelectSet As SelectSet     <br />&#160;&#160;&#160; Set oSelectSet = oDrawDoc.SelectSet     <br />&#160;&#160;&#160; oSelectSet.Clear     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Add each dimension to the select set to select them.        <br /></strong></font>&#160;&#160;&#160; Dim oDrawDim As DrawingDimension     <br />&#160;&#160;&#160; For Each oDrawDim In oDimensions     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSelectSet.Select oDrawDim     <br />&#160;&#160;&#160; Next     <br />    <br /><font color="#0000ff"><strong>&#160;&#160; ' Get the CommandManager object.        <br /></strong></font>&#160;&#160;&#160; Dim oCommandMgr As CommandManager     <br />&#160;&#160;&#160; Set oCommandMgr = ThisApplication.CommandManager     <p></p>    <p>&#160;<font color="#0000ff"><strong>&#160;&#160; ' Get control definition for the arrange dimensions command.          <br /></strong></font>&#160;&#160;&#160; Dim oControlDef As ControlDefinition       <br />&#160;&#160;&#160; Set oControlDef = oCommandMgr.ControlDefinitions.Item( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;DrawingArrangeDimensionsCmd&quot;) </p>    <p>&#160;<font color="#0000ff"><strong>&#160;&#160; ' Execute the command.          <br /></strong></font>&#160;&#160;&#160; Call oControlDef.Execute       <br />End Sub</p> </div>  <p></p>  <p>&#160;</p>  <p>In the case of the Arrange Dimensions sample above, it fully completes the command.&#160; That is when you run the macro, all of the dimensions on the active sheet will be re-arranged.&#160; That’s because if the command sees some dimensions in the select set it operates on them without asking for any more input.&#160; Most commands, even if they support pre-selection of entities, will still allow additional selection so they will still require user input.&#160; For example the Fillet command will take any pre-selected edges as input but still displays the dialog to allow the user to select more edges and specify any other options.</p>  <p>There is another way of providing input for most commands expect a filename as input.&#160; Through the API you can predefine a filename and then run the command.&#160; If a filename is defined, the command will use it.&#160; For some commands, where only a filename is needed, it will skip the dialog portion of the command, for example the Place Component command.&#160; Where more information is required it will use the predefined filename as the default filename and the command will run as normal by displaying its dialog so the user can change the filename and/or set other options.&#160; The Base View command that’s used to create a drawing view is a good example of this.</p>  <p>You predefine a filename using the PostPrivateEvent method of the CommandManager object.&#160; The example below demonstrates its use with the Place Component command.&#160; When the macro executes the Place Component command checks to see if a filename has already been defined.&#160; If it has it uses that filename and skips the dialog step and continues to the step where the user can specify the placement point of the component.&#160; This is a good example of defining the inputs and then allowing the command to take over so you can take advantage of the interactivity the command provides.</p>  <p></p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub PlacePart()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the command manager.        <br /></strong></font>&#160;&#160;&#160; Dim oCommandMgr As CommandManager     <br />&#160;&#160;&#160; Set oCommandMgr = ThisApplication.CommandManager     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Post the filename.        <br /></strong></font>&#160;&#160;&#160; Call oCommandMgr.PostPrivateEvent(kFileNameEvent, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;C:\Users\ekinsb\Documents\Inventor 2010\Showcasetest.ipt&quot;)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get control definition for the place component command.        <br /></strong></font>&#160;&#160;&#160; Dim oControlDef As ControlDefinition     <br />&#160;&#160;&#160; Set oControlDef = oCommandMgr.ControlDefinitions.Item( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;AssemblyPlaceComponentCmd&quot;)&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Execute the command.        <br /></strong></font>&#160;&#160;&#160; Call oControlDef.Execute     <br />End Sub</div>  <p></p>  <p>&#160;</p>  <p><font size="3"><strong>Command Execution Behavior</strong></font></p>  <p>In all of the examples above the Execute method has been used to run the desired command.&#160; The behavior of this method is to tell Inventor to run the command but immediately return control back to your program.&#160; In the example of placing a component in the assembly, control returns back to the macro right after calling Execute, event though the user is still in the middle of placing components.&#160; In many cases this is ok because it’s likely this is the last step in your program, but sometimes you may want to wait until the command has been completed and then finish some additional steps in your program.&#160; You can do this using the Execute2 method.&#160; This method has a single argument indicating if you want to run the command synchronously or asynchronously.&#160; Asynchronous is the same as the Execute method and will immediately return control back to your program.&#160; Synchronous won’t return control back to your program until the command has finished processing.&#160; </p>  <p></p>  <p>Here’s a variation of the previous program that reports on which components were just placed.</p>  <p></p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub PlacePart2()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the assembly component definition.        <br /></strong></font>&#160;&#160;&#160; Dim oAsmDef As AssemblyComponentDefinition     <br />&#160;&#160;&#160; Set oAsmDef = ThisApplication.ActiveDocument.ComponentDefinition     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the command manager.        <br /></strong></font>&#160;&#160;&#160; Dim oCommandMgr As CommandManager     <br />&#160;&#160;&#160; Set oCommandMgr = ThisApplication.CommandManager     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Post the filename.        <br /></strong></font>&#160;&#160;&#160; Call oCommandMgr.PostPrivateEvent(kFileNameEvent, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;C:\Users\ekinsb\Documents\Inventor 2010\Showcasetest.ipt&quot;)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get control definition for the place component command.        <br /></strong></font>&#160;&#160;&#160; Dim oControlDef As ControlDefinition     <br />&#160;&#160;&#160; Set oControlDef = oCommandMgr.ControlDefinitions.Item( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;AssemblyPlaceComponentCmd&quot;)     <p></p>    <p><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the current number of occurrences.          <br /></strong></font>&#160;&#160;&#160; Dim iOccurrenceCount As Long       <br />&#160;&#160;&#160; iOccurrenceCount = oAsmDef.Occurrences.Count&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Execute the command synchronously.&#160; <br /></strong></font>&#160;&#160;&#160; Call oControlDef.Execute2(True)       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Display information about the placed components.          <br /></strong></font>&#160;&#160;&#160; Dim strPrompt As String       <br />&#160;&#160;&#160; strPrompt = oAsmDef.Occurrences.Count - iOccurrenceCount &amp; _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot; occurrences were placed:&quot; &amp; vbCr       <br />&#160;&#160;&#160; Dim i As Integer       <br />&#160;&#160;&#160; For i = iOccurrenceCount + 1 To oAsmDef.Occurrences.Count       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; strPrompt = strPrompt &amp; &quot;&#160;&#160;&#160; &quot; &amp; _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oAsmDef.Occurrences.Item(i).Name &amp; vbCr       <br />&#160;&#160;&#160; Next       <br />&#160;&#160;&#160; MsgBox strPrompt       <br />End Sub</p> </div>
