---
layout: "post"
title: "Controlling Layers in Your Flat Pattern Export"
date: "2009-04-14 17:24:10"
author: "Adam Nagy"
categories:
  - "Brian"
  - "Sheet Metal"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/04/controlling-layers-in-your-flat-pattern-export.html "
typepad_basename: "controlling-layers-in-your-flat-pattern-export"
typepad_status: "Publish"
---

<p>When writing out a flat pattern as DXF or DWG you have control over which layers various bits of the flat pattern are written to.&#0160; You can see these options in the <strong>Save Copy As</strong> dialog when you right-click on the flat pattern in the browser, as shown below.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401156f2545df970c-pi"><img alt="SaveCopyAsFlatPattern" border="0" height="394" src="/assets/image_833760.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="SaveCopyAsFlatPattern" width="454" /></a> </p>
<br />
<p>The dialog allows you to specify the layer name for various categories of items that can exist in a flat pattern.&#0160; You can change the layer names and control which groups are written to the DXF or DWG file.&#0160; This is all good functionality but you’re limited to the predefined sets of groups.&#0160; There is a solution to this that allows you to have very detailed control over which layer specific entities are written to.</p>
<p>Using the API you can assign an attribute to an edge in the flat pattern and this will control which layer that edge will be written to in the DXF or DWG file.&#0160; The name of the layer is specified by the attribute.&#0160; Below is a very simple example that will add an attribute to a selected edge.</p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">
<p><font color="#0000ff"><strong>&#39; This program assumes that a sheet metal document is open, the <br />&#39; flat pattern is active, and that an edge of the flat pattern is <br />&#39; selected.&#0160; For simplicity, no error checking is done to <br />&#39; validate this. <br /></strong></font>Sub AddLayerName() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the active document. <br /></strong></font>&#0160;&#0160;&#0160; Dim oDoc As PartDocument <br />&#0160;&#0160;&#0160; Set oDoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the selected edge. <br /></strong></font>&#0160;&#0160;&#0160; Dim oEdge As Edge <br />&#0160;&#0160;&#0160; Set oEdge = oDoc.SelectSet(1) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Add an attribute set named “FlatPatternAttributes” <br />&#0160;&#0160;&#0160; &#39; to the selected edge. <br /></strong></font>&#0160;&#0160;&#0160; Dim attSet As AttributeSet <br />&#0160;&#0160;&#0160; Set attSet = oEdge.AttributeSets.Add(&quot;FlatPatternAttributes&quot;)&#0160; <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Add an attribute specifying the name of the layer. <br /></strong></font>&#0160;&#0160;&#0160; Dim myLayerName As String <br />&#0160;&#0160;&#0160; myLayerName = &quot;CustomLayer&quot; <br />&#0160;&#0160;&#0160; Call attSet.Add(&quot;LayerName&quot;, kStringType, myLayerName) <br />End Sub</p></div>
<p><br />Any edge on the flat pattern model is valid to name.&#0160; The bend and tangent lines are also Edge objects and can be assigned a layer name too.&#0160; Defining layers for sketches and sketch entities is not currently supported so attributes added to these will be ignored.&#0160; When you specify the layer of an entity using this technique it overrides the dialog settings.&#0160; For example, if an edge will normally be written to the IV_OUTER_PROFILE it will instead be written to the layer you specify using the attribute.</p>
<p>One other thing to be aware of is that only the edges that are visible are written to the DXF or DWG file.&#0160; The picture below shows a flat pattern as viewed with the Z axis pointed towards you.&#0160; This is the geometry you would expect in the output DXF or DWG file.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401156f2545ea970c-pi"><img alt="FlatPattern" border="0" height="386" src="/assets/image_348848.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="FlatPattern" width="450" /></a> </p>
<br />
<p>Here’s a close-up of an area of the model where it’s slightly rotated.&#0160; The red selected edge is on the “back” of the part and will not be written out to the DXF or DWG file.&#0160; Adding an attribute to this edge won’t have any effect since the edge is not written out.&#0160; The same is true for the bend and tangent lines too.&#0160; Only those on the “front” of the part will be written out.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401156f2545f1970c-pi"><img alt="FlatPatternEdge" border="0" height="172" src="/assets/image_434959.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="FlatPatternEdge" width="244" /></a> </p>
<p></p>
<br />
<p>When edges have been attributed in this way the <strong>Save Copy As</strong> command honors this by displaying this as a layer in the dialog to allow you to choose whether to write it out or not.&#0160; Notice in the picture below that the last layer in the list is “CustomLayer” which is the name that was assigned using the macro above.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401156f2545f6970c-pi"><img alt="SaveCopyAsFlatPatternAfter" border="0" height="394" src="/assets/image_886959.jpg" style="BORDER-TOP-WIDTH: 0px; DISPLAY: inline; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" title="SaveCopyAsFlatPatternAfter" width="454" /></a>&#0160; </p>
<br />
<p>These layer overrides are also honored when using the API to write out a DXF or DWG file of the flat pattern.&#0160; The program below is directly from Inventor’s online help and illustrates using the API to write out a DXF file of the flat pattern.&#0160; See the topic on the DataIO object in the online help for additional information about this.</p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">
<p>Public Sub WriteSheetMetalDXF() <br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the active document.&#0160; This assumes it is a part document. <br /></strong></font>&#0160;&#0160;&#0160; Dim oDoc As PartDocument <br />&#0160;&#0160;&#0160; Set oDoc = ThisApplication.ActiveDocument <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Get the DataIO object. <br /></strong></font>&#0160;&#0160;&#0160; Dim oDataIO As DataIO <br />&#0160;&#0160;&#0160; Set oDataIO = oDoc.ComponentDefinition.DataIO <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Build the string that defines the format of the DXF file. <br /></strong></font>&#0160;&#0160;&#0160; Dim sOut As String <br />&#0160;&#0160;&#0160; sOut = &quot;FLAT PATTERN DXF?AcadVersion=R12&quot; <br /><br /><font color="#0000ff"><strong>&#0160;&#0160;&#0160; &#39; Create the DXF file. <br /></strong></font>&#0160;&#0160;&#0160; oDataIO.WriteDataToFile sOut, &quot;C:\temp\flat.dxf&quot; <br />End Sub</p></div>
<br />
<p>If attributes are something new to you watch this blog over the next couple of weeks for additional postings explaining attributes in more detail.</p>
