---
layout: "post"
title: "Combining Multiple Actions into a Single Undo"
date: "2009-03-12 23:53:46"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2009/03/combining-multiple-actions-into-a-single-undo.html "
typepad_basename: "combining-multiple-actions-into-a-single-undo"
typepad_status: "Publish"
---

<p>A question was recently asked in the customization newsgroup about how to combine several actions into one undo.&#160; I think this topic is of general interest and a good one to discuss here.&#160; I think this is a capability that's typically overlooked but is something that's easy to add to your existing macros.&#160; Below is an example of a simple macro that draws a triangle on the active sketch.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub DrawTriangle()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Check to see that a sketch is active.        <br /></strong></font>&#160;&#160;&#160; If Not TypeOf ThisApplication.ActiveEditObject Is sketch Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A sketch must be active.&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160; End If     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get a reference to the sketch.        <br /></strong></font>&#160;&#160;&#160; Dim oSketch As sketch     <br />&#160;&#160;&#160; Set oSketch = ThisApplication.ActiveEditObject     <br />    <br />&#160;&#160;&#160; Dim oTG As TransientGeometry     <br />&#160;&#160;&#160; Set oTG = ThisApplication.TransientGeometry     <br />    <br /><strong><font color="#0000ff">&#160;&#160;&#160; ' Draw the three lines of the triangle.        <br /></font></strong>&#160;&#160;&#160; Dim aoLines(2) As SketchLine     <br />&#160;&#160;&#160; Set aoLines(0) = oSketch.SketchLines.AddByTwoPoints( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(0, 0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(5, 0))     <br />&#160;&#160;&#160; Set aoLines(1) = oSketch.SketchLines.AddByTwoPoints( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(0).EndSketchPoint, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(2.5, 4))     <br />&#160;&#160;&#160; Set aoLines(2) = oSketch.SketchLines.AddByTwoPoints( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(1).EndSketchPoint, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(0).StartSketchPoint)     <br />    <br /><strong><font color="#0000ff">&#160;&#160;&#160; ' Add a horizontal constraint to the bottom line.        <br /></font></strong>&#160;&#160;&#160; Call oSketch.GeometricConstraints.AddHorizontal(aoLines(0))     <br />End Sub </div>  <p></p>  <p>   <br />If you run this program it will create a triangle.&#160; If you want to get rid of the triangle you'll need to do 4 undo steps, one for the horizontal constraint and three for the lines.&#160; Since from the users perspective this was all created as a single step it would be nice if it would undo using a single undo.     <br /></p>  <p></p>  <p><strong><font size="3">Transaction Basics        <br /></font></strong>You can combine multiple actions into a single undo using <em>transactions</em>.&#160; A transaction is any action that can be undone.&#160; Many, if not most, API calls are not transacted.&#160; In the example above, checking that a sketch is active, getting the sketch, and getting the TransientGeometry are not transacted since they don't cause any change to the current document.&#160; Creating the lines and the horizontal constraint are automatically transacted.&#160; If you don't do anything special, each API call that causes a transaction will show up in the undo list as an individual item and can be undone.</p>  <p>To combine a set of actions into a single undo the API allows you to create your own transaction which wraps the other transactions.&#160; Since the other transactions are nested within your transaction they aren't visible in the undo command and are undone and redone as a group whenever your transaction is undone or redone.&#160; The functionality to use transactions through the API is supported through the TransactionManager object.&#160; The modified version of the previous program shown below demonstrates this. </p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub DrawTriangle()    <br /><font color="#0000ff">&#160;<strong>&#160;&#160; ' Check to see that a sketch is active.        <br /></strong></font>&#160;&#160;&#160; If Not TypeOf ThisApplication.ActiveEditObject Is sketch Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A sketch must be active.&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160; End If     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get a reference to the sketch.        <br /></strong></font>&#160;&#160;&#160; Dim oSketch As sketch     <br />&#160;&#160;&#160; Set oSketch = ThisApplication.ActiveEditObject     <br />    <br />&#160;&#160;&#160; Dim oTG As TransientGeometry     <br />&#160;&#160;&#160; Set oTG = ThisApplication.TransientGeometry     <br />    <br /><font color="#0000ff">&#160;&#160;&#160; ' Create a transaction. </font></div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new"><font color="#ff0000">&#160;&#160;&#160; Dim oTransMgr As TransactionManager</font></div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new"><font color="#ff0000">&#160;&#160;&#160; Set oTransMgr = ThisApplication.TransactionManager      <br />&#160;&#160;&#160; Dim oTrans As Transaction       <br />&#160;&#160;&#160; Set oTrans = oTransMgr.StartTransaction( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveDocument, &quot;Create Triangle&quot;)       <br /></font>    <br /><font color="#0000ff">&#160;&#160;&#160; ' Draw the three lines of the triangle.      <br /></font>&#160;&#160;&#160; Dim aoLines(2) As SketchLine     <br />&#160;&#160;&#160; Set aoLines(0) = oSketch.SketchLines.AddByTwoPoints( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d0,0),     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(5, 0))     <br />&#160;&#160;&#160; Set aoLines(1) = oSketch.SketchLines.AddByTwoPoints( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(0).EndSketchPoint,     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(2.5, 4))     <br />&#160;&#160;&#160; Set aoLines(2) = oSketch.SketchLines.AddByTwoPoints( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(1).EndSketchPoint,     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(0).StartSketchPoint)&#160; <br />    <br /><font color="#0000ff">&#160;&#160;&#160; ' Add a horizontal constraint to the bottom line.      <br /></font>&#160;&#160;&#160; Call oSketch.GeometricConstraints.AddHorizontal(aoLines(0))     <br />    <br />&#160;<font color="#0000ff">&#160;&#160; ' End the transaction.      <br /></font><font color="#ff0000">&#160;&#160;&#160; oTrans.End      <br /></font>End Sub </div>  <p>   <br />There are four extra lines from the previous program that are highlighted in red.&#160; After running this program and looking in the Edit menu you'll see that you can undo &quot;Create Triangle&quot;, as shown in the picture below.&#160; </p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401127964e52328a4-pi"><img style="border-top-width: 0px; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="116" alt="UndoInEditMenu" src="/assets/image_487582.jpg" width="244" border="0" /></a></p>  <p>&#160;</p>  <p>For many programs these four extra lines are all that you'll need to implement undo behavior.&#160; The StartTransaction method creates and starts your transaction.&#160; The first argument is a document and can be any document, it doesn't matter which one.&#160; The second argument is the text that will appear in the Edit menu and can be whatever string you want to describe the group of steps being wrapped by this transaction.&#160; The API calls after the StartTransaction and before the call of the End method will be nested within your transaction.</p>  <p><font size="3"><strong></strong></font></p>  <p><font size="3"><strong>Handling Errors</strong></font>     <br />The code above does demonstrate the minimum to wrap multiple actions into a single undo.&#160; The only problem with it is if something happens in the program so that the Transaction.End method is never called.&#160; For example, if an error is encountered when creating the lines.&#160; In this case your transaction is started, some other transactions are created as a result of the API calls and are nested within your transaction but then it terminates if an error occurs, which leaves Inventor in a bit of a weird state.&#160; To make sure this doesn't happen it's best to correctly handle any errors that might occur.&#160; The modified example code below illustrates this.&#160; <br /></p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub DrawTriangle()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Enable error handling.        <br /></strong></font><font color="#ff0000">&#160;&#160;&#160; On Error GoTo ErrorFound      <br /></font>    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Check to see that a sketch is active.        <br /></strong></font>&#160;&#160;&#160; If Not TypeOf ThisApplication.ActiveEditObject Is sketch Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A sketch must be active.&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160; End If     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get a reference to the sketch.        <br /></strong></font>&#160;&#160;&#160; Dim oSketch As sketch     <br />&#160;&#160;&#160; Set oSketch = ThisApplication.ActiveEditObject     <br />    <br />&#160;&#160;&#160; Dim oTG As TransientGeometry     <br />&#160;&#160;&#160; Set oTG = ThisApplication.TransientGeometry     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Create a transaction.        <br /></strong></font></div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160; Dim oTransMgr As TransactionManager</div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">&#160;&#160;&#160; Set oTransMgr = ThisApplication.TransactionManager    <br />&#160;&#160;&#160; Dim oTrans As Transaction     <br />&#160;&#160;&#160; Set oTrans = oTransMgr.StartTransaction( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveDocument, &quot;Create Triangle&quot;)     <br /></div>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">   <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Draw the three lines of the triangle.        <br /></strong></font>&#160;&#160;&#160; Dim aoLines(2) As SketchLine     <br />&#160;&#160;&#160; Set aoLines(0) = oSketch.SketchLines.AddByTwoPoints( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(0, 0),     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(5, 0))     <br />&#160;&#160;&#160; Set aoLines(1) = oSketch.SketchLines.AddByTwoPoints( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(0).EndSketchPoint,     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG.CreatePoint2d(2.5, 4))     <br />&#160;&#160;&#160; Set aoLines(2) = oSketch.SketchLines.AddByTwoPoints( _&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(1).EndSketchPoint,     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aoLines(0).StartSketchPoint)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Add a horizontal constraint to the bottom line.        <br /></strong></font>&#160;&#160;&#160; Call oSketch.GeometricConstraints.AddHorizontal(aoLines(0))     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' End the transaction.        <br /></strong></font>&#160;&#160;&#160; oTrans.End     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' No errors were found so exit before the error handling code.        <br /></strong></font><font color="#ff0000">&#160;&#160;&#160; Exit Sub      <br /></font>    <br /><font color="#0000ff"><strong>' Handle any errors        <br /></strong></font><font color="#ff0000">ErrorFound:      <br />&#160;&#160;&#160; MsgBox &quot;Unexpected error encountered.&quot;       <br /></font>    <br /><strong>&#160;</strong><font color="#0000ff"><strong>&#160;&#160; ' Check to see if a transaction was started.        <br /></strong></font><font color="#ff0000">&#160;&#160;&#160; If Not oTrans Is Nothing Then      <br /></font><strong><font color="#0000ff">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Abort the transaction.        <br /></font></strong><font color="#ff0000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTrans.Abort      <br />&#160;&#160;&#160; End If       <br /></font>End Sub </div>  <p>   <br />The new code is highlighted.&#160; At the beginning of the macro the On Error statement is used to turn on error handling.&#160; In this case it's set up to jump to the ErrorFound: line if any error should occur.&#160; In the ErrorFound: section it checks to see if a transaction object was created and if it was it calls the Transaction.Abort method.&#160; This results in undoing every action since your transaction was created.&#160; Instead of the Abort method the End method could have been called which will result in creating everything that was created up to the point of the error occurring.&#160; The choice is yours whether to use Abort or End.&#160; The reason this section checks to see if a transaction was created before call Abort is because an error could have occurred before the transaction was created and calling Abort or End would fail since your transaction object won't exist.</p>  <p>&#160;</p>  <p><font size="3"><strong>Transaction Issues to be Aware Of</strong></font>&#160; <br />There are a couple of things to be aware of when using transactions through the API.&#160; First, let's look at the behavior of Inventor relative to transactions and undo.&#160; Try this:</p>  <ol>   <li>Create a new part document. </li>    <li>Create another new part document. </li>    <li>In one of the part documents (part 1), draw some lines in a sketch. </li>    <li>Activate the other part document (part 2) and draw two lines. </li>    <li>Activate part 1 and draw one line. </li>    <li>Do an undo and the line will go away. </li>    <li>Do another undo.&#160; One of the lines in part 2 will go away. </li>    <li>Close part 1. </li>    <li>Do another undo. </li> </ol>  <p>There are two things to notice from the above steps.&#160; First is that there is a single undo list for all of Inventor, not for each document.&#160; The fact that you performed operations in different documents doesn't matter, all actions go onto a single undo list and are undone in the order they were performed.&#160; The second issue is that in step 9 you are unable to do an undo because the undo command is unavailable.&#160; This is because when a document is closed the undo stack is cleared.&#160; This seems like a fairly big limitation but doesn't seem to matter in the real world since I've never found anyone that knew of this behavior before I showed it to them.</p>  <p>Because the undo stack is cleared when a document is closed you can't wrap the opening and closing of documents in a transaction.&#160; That's probably the single biggest problem people have when using transactions.&#160; There is one exception to this rule.&#160; If the opening and closing of a document is done within your transaction, then it's ok.&#160; For example, you could perform the following steps:</p>  <ol>   <li>Start a transaction. </li>    <li>Open a part. </li>    <li>Change a parameter. </li>    <li>Update the part. </li>    <li>Save a copy to a new file. </li>    <li>Close the part. </li>    <li>Insert the new part into the assembly. </li>    <li>End the transaction. </li> </ol>  <p>Even though a document was closed, it didn't clear the undo stack since the opening and closing of the document was within your transaction.&#160; If you perform an undo after the previous steps, the part will be removed from the assembly.&#160; However, the file on disk will remain.</p>  <p>&#160;</p>  <p><font size="3"><strong>Other Functionality</strong></font>&#160; <br />The TransactionManager supports a lot more functionality than I’ve described here.&#160; However, I think the samples above demonstrate all that’s needed by 99.9% of the programs written.&#160; There are descriptions of the additional functionality in the online help, if you’re interested.</p>  <p>You might also see references to something called a <em>change processor</em>.&#160; This is a different mechanism for grouping multiple operations within a single undo but it’s much more complicated to use and cannot be used from within VBA.&#160; I wouldn’t recommend it for most programs.&#160; In fact I would only recommend it for larger application type of add-ins (like Tube &amp; Pipe) that want to automate testing their custom commands.&#160; The change processor provides important functionality to support that.</p>
