---
layout: "post"
title: "Totaling the Length of Parts in an Assembly"
date: "2010-09-09 22:56:04"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2010/09/totaling-the-length-of-parts-in-an-assembly.html "
typepad_basename: "totaling-the-length-of-parts-in-an-assembly"
typepad_status: "Publish"
---

<p>There’s a <a href="http://forums.autodesk.com/t5/Autodesk-Inventor-Customization/Adding-values-from-within-a-BOM/td-p/2758449">question on the Inventor Customization newsgroup</a> that I thought might be of general interest so I’m posting my response here.&#160; The specific question is that they have a cabinet assembly and some of the parts in the assembly represent pieces of molding.&#160; They want to get a total length of all of the molding used in the assembly.&#160; I’ve written a small sample below that illustrates one approach to this.</p>  <p>The first thing before writing any program is to fully understand the conditions the program can expect.&#160; You might need to impose certain requirements on the model in order for the program to function correctly.&#160; A computer program isn’t very smart and only does exactly what you’ve programmed it to do.&#160; Each variation in the conditions of the model requires more code to check for and handle each case.&#160; Here are the assumptions that this program makes about the assembly.&#160; </p>  <ol>   <li>The program is executed when the cabinet assembly is active. </li>    <li>Any parts that represent molding will have the word “molding” in the category iProperty.&#160; This is how the program determines which parts are molding parts. </li>    <li>Each molding part has a parameter called “Length” that is the actual length of the molding part. </li> </ol>  <p>The program demonstrates several basic things that should be interesting for many of you.&#160; First, it traverses the entire assembly looking for molding parts.&#160; It uses the iProperty portion of the API and rule number 2 above to determine which parts in the assembly are molding parts.&#160; Once it finds a molding part it uses the parameters portion of the API to get the length of the molding.&#160; It again uses iProperties to create or update a custom iProperty in the assembly with the total length of the molding (plus 30% for waste).</p>  <p>Not everyone needs a program that totals the length of molding parts but hopefully you can see how this sample could be easily edited to perform other similar tasks.</p>  <p>Something to be aware of is that this is not automatic.&#160; It’s essentially a “snapshot” of the length of molding at the time you run the program.&#160; If you edit, add, or remove parts the iProperty will not automatically update but you’ll need to manually run the program again.   <br />    <br />If you’re new to Inventor’s VBA, here’s a <a href="http://modthemachine.typepad.com/my_weblog/2010/05/using-vba-sample-code-for-the-non-programmer.html">post that lists the steps of how to use a VBA macro within Inventor</a>.</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">   <p><font color="#0000ff"><strong>' Main program that computes the total length of all molding         <br />' parts in the active assembly.</strong></font>      <br />Public Sub ComputeMoldingLength()&#160; <br />&#160;&#160; Dim asmDoc As AssemblyDocument&#160; <br />&#160;&#160; Set asmDoc = ThisApplication.ActiveDocument&#160; <br />&#160;&#160; Dim asmDef As AssemblyComponentDefinition&#160; <br />&#160;&#160; Set asmDef = asmDoc.ComponentDefinition      <br />&#160; <br /><font color="#0000ff"><strong>&#160;&#160; ' Call the recursive function to traverse the assembly.&#160; <br /></strong></font>&#160;&#160; Dim MoldingLength As Double&#160; <br />&#160;&#160; MoldingLength = 0&#160; <br />&#160;&#160; Call GetMoldingLength(asmDef.Occurrences, MoldingLength)&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160; ' Get the iProperties for this document.&#160; <br /></strong></font>&#160;&#160; Dim propSets As PropertySets&#160; <br />&#160;&#160; Set propSets = asmDoc.PropertySets&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160; ' Get the user defined property set.&#160; <br /></strong></font>&#160;&#160; Dim userProps As PropertySet&#160; <br />&#160;&#160; Set userProps = propSets.Item(&quot;Inventor User Defined Properties&quot;)&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160; ' Create a string that represents the length value,&#160; <br />&#160;&#160; ' including an extra 30% for waste.&#160; <br /></strong></font>&#160;&#160; Dim totalLength As String&#160; <br />&#160;&#160; totalLength = asmDoc.UnitsOfMeasure.GetStringFromValue( _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MoldingLength * 1.3, kDefaultDisplayLengthUnits)&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160; ' Update or create the iProperty containing the length.&#160; <br /></strong></font>&#160;&#160; On Error Resume Next&#160; <br />&#160;&#160; Dim lengthProp As Inventor.Property&#160; <br />&#160;&#160; Set lengthProp = userProps.Item(&quot;MoldingLength&quot;)&#160; <br />&#160;&#160; If Err.Number &lt;&gt; 0 Then&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160; ' The property doesn't exist so create it.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160; Set lengthProp = userProps.Add(totalLength, &quot;MoldingLength&quot;)&#160; <br />&#160;&#160; Else&#160; <br />&#160;&#160;&#160;&#160;&#160; lengthProp.value = totalLength&#160; <br />&#160;&#160; End If&#160; <br />      <br />&#160;&#160; MsgBox &quot;Total molding length (including 30% waste): &quot; _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &amp; totalLength       <br />End Sub       <br />      <br />      <br /></p>   <font color="#0000ff"><strong>' Sub that is called recursively to iterate through the entire       <br />' assembly structure to find and total the lengths of all         <br />' molding parts.        <br /></strong></font>Private Sub GetMoldingLength( _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal Occurrences As ComponentOccurrences, _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByRef MoldingLength As Double)&#160; <br /><font color="#0000ff"><strong>&#160;&#160; ' Iterate through the occurrences in the current assembly.&#160; <br /></strong></font>&#160;&#160; Dim occ As ComponentOccurrence&#160; <br />&#160;&#160; For Each occ In Occurrences&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160; ' Check if this is a part or assembly.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160; If occ.DefinitionDocumentType = kPartDocumentObject Then&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the iProperties for this document.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim propSets As PropertySets&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set propSets = occ.Definition.Document.PropertySets&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the Document Summary Info property set.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim docSummaryInfo As PropertySet&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set docSummaryInfo = propSets.Item( _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Inventor Document Summary Information&quot;)&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Check to see if the term &quot;molding&quot; is part of&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' the category property.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If InStr(&quot;MOLDING&quot;, _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; UCase(docSummaryInfo.Item(&quot;Category&quot;).value)) &gt; 0 Then&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the user defined property set.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim userDefinedProps As PropertySet&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set userDefinedProps = propSets.Item( _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;Inventor User Defined Properties&quot;)    <br />&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the component definition of the part.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim partCompDef As PartComponentDefinition&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set partCompDef = occ.Definition&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the parameter for the length.&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' It will be in centimeters.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error Resume Next&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim length As Double&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; length = partCompDef.Parameters.Item(&quot;Length&quot;).value&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Err.Number = 0 Then&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MoldingLength = MoldingLength + length&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;Error getting the Length property from &quot; &amp; _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; occ.Definition.Document.DisplayName&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If&#160; <br />&#160;&#160;&#160;&#160;&#160; Else&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' It's an assembly so call this sub again.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call GetMoldingLength(occ.SubOccurrences, MoldingLength)&#160; <br />&#160;&#160;&#160;&#160;&#160; End If&#160; <br />&#160;&#160; Next     <br />End Sub</div>
