---
layout: "post"
title: "Exporting Assembly Structure to Excel"
date: "2010-01-28 19:59:03"
author: "Adam Nagy"
categories:
  - "Assemblies"
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2010/01/exporting-assembly-structure-to-excel.html "
typepad_basename: "exporting-assembly-structure-to-excel"
typepad_status: "Publish"
---

<p>There was a recent question in the newsgroup about exporting the structure of an assembly to an Excel spreadsheet.&#160; I’ve written a small VBA program that does this.&#160; When executed it will prompt for a filename and then write the structure of the currently open assembly to the file.&#160; The file created is a CSV file, which can be opened directly by Excel.&#160; For each occurrence in the assembly it writes one row, with the first column containing the name of the occurrence as seen in the browser, and the second column containing the full filename of the part or assembly represented by that occurrence.&#160; The data is written such that the structure of the assembly is preserved, which can be seen below.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340128772191fb970c-pi"><img title="AssemblyStructureExcel" style="border-right: 0px; border-top: 0px; display: inline; border-left: 0px; border-bottom: 0px" height="298" alt="AssemblyStructureExcel" src="/assets/image_586725.jpg" width="454" border="0" /></a> </p>  <p>It’s likely everyone using this will want different information or a different format for the output.&#160; This is a good time to get your feet wet and learn a little bit about programming Inventor so you can make the small changes to have it write out the information you want.</p>  <p>For those of you unfamiliar with VBA here are the steps to using this program:</p>  <ol>   <li>Open the VBA editor within Inventor (Alt-F11 or Tools –&gt; VBA Editor).&#160; </li>    <li>In the project tree, find the project named <strong>ApplicationProject</strong> </li>    <li>Expand the <strong>Modules</strong> folder. </li>    <li>Double click on the module named <strong>Module1</strong>.&#160; This should open up the code window. </li>    <li>Copy and paste the code below into the code window.&#160; If there’s some code already there, paste it at the bottom of any existing code.&#160; The result is shown below. </li> </ol>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401287721920c970c-pi"><img title="Paste code into VBA" style="border-top-width: 0px; display: inline; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="278" alt="Paste code into VBA" src="/assets/image_249344.jpg" width="454" border="0" /></a> </p>  <p>Once pasted, you can run the program.&#160; This <a href="http://modthemachine.typepad.com/my_weblog/visual-basic-for-applications-vba/">posting</a> describes a few ways to do that.</p>  <p>Here’s the code to copy and paste:</p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">   <p>Public Sub WriteAssemblyStructure()     <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Check that an assembly is open.         <br /></strong></font>&#160;&#160;&#160; Dim asmDoc As AssemblyDocument      <br />&#160;&#160;&#160; Dim docType As DocumentTypeEnum      <br />&#160;&#160;&#160; docType = ThisApplication.ActiveDocumentType      <br />&#160;&#160;&#160; If docType &lt;&gt; kAssemblyDocumentObject Then      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;An assembly must be active.&quot;      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub      <br />&#160;&#160;&#160; Else      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set asmDoc = ThisApplication.ActiveDocument      <br />&#160;&#160;&#160; End If      <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the name of the file to create.          <br /></strong></font>&#160;&#160;&#160; Dim csvFilename As String       <br />&#160;&#160;&#160; Dim saveDialog As FileDialog       <br />&#160;&#160;&#160; Call ThisApplication.CreateFileDialog(saveDialog)       <br />&#160;&#160;&#160; With saveDialog       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Filter = &quot;CSV (Command delimited)(*.csv)|*.csv&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .DialogTitle = &quot;Specify output filename&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .OptionsEnabled = False       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .SuppressResolutionWarnings = True       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .ShowSave      <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If .FileName = &quot;&quot; Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; csvFilename = .FileName       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; End With      <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Open the file.          <br /></strong></font>&#160;&#160;&#160; Dim FilePointer As Integer       <br />&#160;&#160;&#160; FilePointer = FreeFile       <br />&#160;&#160;&#160; Open csvFilename For Output As #FilePointer       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Write the top-level assembly name.          <br /></strong></font>&#160;&#160;&#160; Print #FilePointer, asmDoc.DisplayName &amp; &quot;,&quot; &amp; _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; asmDoc.FullFileName      <br />       <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Read through the assembly and write the structure out.          <br /></strong></font>&#160;&#160;&#160; Call WriteStructure(asmDoc.ComponentDefinition.occurrences, _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 1, FilePointer)      <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Close the file.&#160; <br /></strong></font>&#160;&#160;&#160; Close #FilePointer      <br />       <br />&#160;&#160;&#160; MsgBox &quot;Completed writing assembly structure to: &quot; &amp; csvFilename       <br />End Sub      <br />      <br />      <br />      <br />Private Sub WriteStructure( _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal occurrences As ComponentOccurrences, _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal Level As Integer, _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ByVal FilePointer As Integer)      <br />       <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Iterate through the occurrences in the current level.          <br /></strong></font>&#160;&#160;&#160; Dim occ As ComponentOccurrence       <br />&#160;&#160;&#160; For Each occ In occurrences       <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Write information for this occurrence to the file.          <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Print #FilePointer, String$(Level, &quot;,&quot;) &amp; _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; occ.Name &amp; &quot;,&quot; &amp; occ.Definition.Document.FullFileName      <br />       <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' If this occurrence is a subassembly iterate          <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' over its occurrences.           <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; If occ.DefinitionDocumentType = kAssemblyDocumentObject Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call WriteStructure(occ.SubOccurrences, Level + 1, _      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; FilePointer)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; Next       <br />End Sub</p> </div>
