---
layout: "post"
title: "Flattening an Assembly"
date: "2010-03-17 14:53:08"
author: "Adam Nagy"
categories:
  - "Assemblies"
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2010/03/flattening-an-assembly.html "
typepad_basename: "flattening-an-assembly"
typepad_status: "Publish"
---

<p>I had an internal request recently for a utility to take any assembly and create an equivalent single-level assembly.&#0160; In this particular case they had a large assembly whose structure didn’t make sense for their current use and the structure made it difficult to delete individual components.&#0160; By flattening the assembly they’re now able to quickly remove portions of the assembly and get something they can begin working with.&#0160; In this specific case, to begin building fixtures around it.</p>
<p>Here’s the VBA macro code that does the flattening.&#0160; (I had to add some line continuations that I wouldn’t normally use to get the code to fit within the narrow space I have here.)</p>
<div style="FONT-SIZE: 8pt; BACKGROUND: #eeeeee; COLOR: black; LINE-HEIGHT: 140%; FONT-FAMILY: courier new">
<p><font color="#0000ff"><strong>&#39; Macro that creates a new assembly that represents a flattened <br />&#39; version of the current active assembly.&#0160; The result is a single <br />&#39; level assembly of occurrences.&#0160; There are not constraints and <br />&#39; each occurrence is grounded. <br /></strong></font>Public Sub FlattenAssembly()&#0160; <br /><font color="#0000ff"><strong>&#0160;&#0160; &#39; Get the active assembly.&#0160; <br /></strong></font>&#0160;&#0160; Dim sourceAsmDoc As AssemblyDocument&#0160; <br />&#0160;&#0160; On Error Resume Next&#0160; <br />&#0160;&#0160; Set sourceAsmDoc = ThisApplication.ActiveDocument&#0160; <br />&#0160;&#0160; If Err Then&#0160; <br />	&#0160; MsgBox &quot;An assembly must active.&quot;&#0160; <br />	&#0160; Exit Sub&#0160; <br />&#0160;&#0160; End If&#0160; <br />&#0160;&#0160; On Error GoTo 0 <br /><br /><font color="#0000ff"><strong>&#0160;&#0160; &#39; Create the new, empty assembly.&#0160; <br /></strong></font>&#0160;&#0160; Dim targetAsmDoc As AssemblyDocument&#0160; <br />&#0160;&#0160; Set targetAsmDoc = ThisApplication.Documents.Add( _ <br />					&#0160; kAssemblyDocumentObject, _ <br />					&#0160; ThisApplication.FileManager.GetTemplateFile( _ <br />					&#0160; kAssemblyDocumentObject)) <br /><br /><font color="#0000ff"><strong>&#0160;&#0160; &#39; Traverse through the existing assembly getting&#0160; <br />&#0160;&#0160; &#39; each leaf component and creating an occurrence&#0160; <br />&#0160;&#0160; &#39; in the new assembly that represents it.&#0160; <br /></strong></font>&#0160;&#0160; Call CopyAssemblyAsFlat(targetAsmDoc.ComponentDefinition, _&#0160; <br />					&#0160;&#0160; sourceAsmDoc.ComponentDefinition.Occurrences) <br />End Sub <br /><br /><br /><br /><font color="#0000ff"><strong>&#39; Utility sub used by FlattenAssembly macro.&#0160; This sub is call <br />&#39; recursively to traverse an entire assembly.&#0160; It creates new <br />&#39; top-level occurrences in the target assembly to represent each <br />&#39; of the occurrences found in the source assembly. <br />&#39; <br />&#39; TargetAsm - The component definition of the target assembly. <br />&#39; Occurrences - The occurrences collection of the assembly <br />&#39; to traverse. <br /></strong></font>Private Sub CopyAssemblyAsFlat( _<br />					&#0160;&#0160; TargetAsm As AssemblyComponentDefinition, _&#0160; <br />					&#0160;&#0160; Occurrences As ComponentOccurrences)&#0160; <br /><font color="#0000ff"><strong>&#0160;&#0160; &#39; Iterate through the occurrences in the current level&#0160; <br />&#0160;&#0160; &#39; of the assembly.&#0160; <br /></strong></font>&#0160;&#0160; Dim occ As ComponentOccurrence&#0160; <br />&#0160;&#0160; For Each occ In Occurrences&#0160; <br /><font color="#0000ff"><strong>	&#0160; &#39; Skip any invisible, suppressed, or excluded components.&#0160; <br /></strong></font>	&#0160; If occ.Visible And Not occ.Suppressed And _ <br />											&#0160; Not occ.Excluded Then&#0160; <br /><font color="#0000ff"><strong>		 &#39; Check to see if this occurrence is a part or assembly.&#0160; <br /></strong></font>		 If occ.DefinitionDocumentType = kPartDocumentObject Then&#0160; <br /><font color="#0000ff"><strong>		&#0160;&#0160;&#0160; &#39; Create an occurrence in the target assembly&#0160; <br />		&#0160;&#0160;&#0160; &#39; for this part.&#0160; <br /></strong></font>		&#0160;&#0160;&#0160; Dim newOcc As ComponentOccurrence&#0160; <br />		&#0160;&#0160;&#0160; Set newOcc = _ <br />				&#0160;&#0160; TargetAsm.Occurrences.AddByComponentDefinition( _&#0160; <br />								 occ.Definition, occ.Transformation)&#0160; <br />		&#0160;&#0160;&#0160; newOcc.Grounded = True&#0160; <br />		 Else&#0160; <br /><font color="#0000ff"><strong>		&#0160;&#0160;&#0160; &#39; Recursively call this sub to continue&#0160; <br />		&#0160;&#0160;&#0160; &#39; traversing the assembly.&#0160; <br /></strong></font>		&#0160;&#0160;&#0160; Call CopyAssemblyAsFlat(TargetAsm, occ.SubOccurrences)&#0160; <br />	&#0160;&#0160;&#0160; End If&#0160; <br />	 End If&#0160; <br />&#0160;&#0160; Next <br />End Sub</p></div>
<p>The macro uses somewhat of a brute force method.&#0160; It creates a new, empty assembly, traverses the existing assembly to determine what parts are used and where they’re located and then reconstructs the original assembly by placing parts in the new assembly.&#0160; The parts are positioned correctly in the new assembly but there aren’t any constraints and they’re all grounded.</p>
<p>You can see that there’s really not much code needed to do this.&#0160; It’s actually just a variation of the assembly traversal code from a <a href="http://modthemachine.typepad.com/my_weblog/2009/03/accessing-assembly-components.html">previous post</a>.</p>
<p><strong>Update (March 29, 2010)</strong> <br />A couple of limitations with the program have been pointed out to me and are worth noting.</p>
<ol>
<li>All assembly features are lost. 
<li>All weldment data is lost (preparations, welds, finishing). </li>
</li></ol>
<p>Luckily I don’t believe these are an issue in most cases where the program would be used, but in case you do have assembly features or weldments you should be aware of these limitations.</p>
