---
layout: "post"
title: "Changing Drawing Curves to Match Assembly Color"
date: "2010-10-18 18:21:05"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2010/10/changing-drawing-curves-to-match-assembly-color.html "
typepad_basename: "changing-drawing-curves-to-match-assembly-color"
typepad_status: "Publish"
---

<p>I had a couple of requests lately asking about the possibility of using the API to change the colors of the curves in a drawing view to match the color of the parts in the assembly.&#160; Below is a program that does this.&#160; It starts with a selected drawing view and gets the associated assembly.&#160; It then iterates over every occurrence in the assembly and for each part occurrence gets the color of that part as it exists in the assembly.&#160; If the color has been overridden in the assembly then it will use the override color.&#160; It then checks to see if there is a layer in the drawing that has the same name as the color.&#160; If there isn’t it creates a new layer with the same color.&#160; It then gets all of the curves in the drawing that are associated with that occurrence and assigns the layer to those curves.&#160; The picture below shows the result after running it on the engine sample that’s delivered with Inventor.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340133f52a0299970b-pi"><img title="DrawingCurveColorExample" style="border-top-width: 0px; display: inline; border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px" height="242" alt="DrawingCurveColorExample" src="/assets/image_865121.jpg" width="450" border="0" /></a> </p>  <p>Here’s the VBA code that does the work.&#160; A key API functions that the program uses is the DrawingView.DrawingCurves property, which given an occurrence returns all of the curves in the view that are associated with that occurrence.&#160; It also uses the Sheet.ChangeLayer method which is a new method in Inventor 2011 that changes the layer of a group of objects.&#160; The program could be written without this, but would be much slower since it will need to change the layer of each curve one at a time.</p>  <p style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Public Sub ChangeLayerOfOccurrenceCurves()   <br /><font color="#0000ff"><strong>&#160;&#160; ' Get the active drawing document.       <br /></strong></font>&#160;&#160; Dim drawDoc As DrawingDocument    <br />&#160;&#160; Set drawDoc = ThisApplication.ActiveDocument    <br />    <br /><font color="#0000ff"><strong>&#160;&#160; ' Have the user select a drawing view.       <br /></strong></font>&#160;&#160; Dim drawView As DrawingView    <br />&#160;&#160; Set drawView = ThisApplication.CommandManager.Pick( _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kDrawingViewFilter, &quot;Select a drawing view.&quot;)&#160; <br />    <br />&#160;&#160; Dim docDesc As DocumentDescriptor    <br />&#160;&#160; Set docDesc = drawView.ReferencedDocumentDescriptor&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160; ' Verify that the selected drawing view is of an assembly.       <br /></strong></font>&#160;&#160; If docDesc.ReferencedDocumentType &lt;&gt; kAssemblyDocumentObject Then    <br />&#160;&#160;&#160;&#160;&#160; MsgBox &quot;The selected view must be of an assembly.&quot;    <br />&#160;&#160;&#160;&#160;&#160; Exit Sub    <br />&#160;&#160; End If&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160; ' Get the component definition for the assembly.       <br /></strong></font>&#160;&#160; Dim asmDef As AssemblyComponentDefinition    <br />&#160;&#160; Set asmDef = docDesc.ReferencedDocument.ComponentDefinition&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160; ' Process the occurrences, wrapping it in a transaction so the       <br />&#160;&#160; ' entire process can be undone with a single undo operation.        <br /></strong></font>&#160;&#160; Dim trans As Transaction    <br />&#160;&#160; Set trans = ThisApplication.TransactionManager.StartTransaction( _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; drawDoc, &quot;Change drawing view color&quot;)&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160; ' Call the recursive function that does all the work.       <br /></strong></font>&#160;&#160; Call ProcessAssemblyColor(drawView, asmDef.Occurrences)    <br />&#160;&#160; trans.End    <br />End Sub     <br />    <br />    <br />    <br />Private Sub ProcessAssemblyColor(drawView As DrawingView, _    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Occurrences As ComponentOccurrences)    <br /><font color="#0000ff"><strong>&#160;&#160; ' Iterate through the current collection of occurrences.       <br /></strong></font>&#160;&#160; Dim occ As ComponentOccurrence    <br />&#160;&#160; For Each occ In Occurrences    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160; ' Check to see if this occurrence is a part or assembly.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160; If occ.DefinitionDocumentType = kPartDocumentObject Then    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' ** It's a part so process the color.&#160; <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the render style of the occurrence.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim color As RenderStyle    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim sourceType As StyleSourceTypeEnum    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set color = occ.GetRenderStyle(sourceType)&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the TransientsObjects object to use later.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim transObjs As TransientObjects    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set transObjs = ThisApplication.TransientObjects&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Verify that a layer exists for this color.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim layers As LayersEnumerator    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set layers = drawView.Parent.Parent.StylesManager.layers&#160; <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim drawDoc As DrawingDocument    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set drawDoc = drawView.Parent.Parent&#160; <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error Resume Next    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim colorLayer As Layer    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set colorLayer = layers.Item(color.Name)&#160; <br />    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Err.Number &lt;&gt; 0 Then    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get the diffuse color for the render style.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim red As Byte    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim green As Byte    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim blue As Byte&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Create a color object that is the diffuse color.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call color.GetDiffuseColor(red, green, blue)    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim newColor As color    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set newColor = transObjs.CreateColor(red, green, blue)&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Copy an arbitrary layer giving it the name       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' of the render style.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set colorLayer = layers.Item(1).Copy(color.Name)    <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Set the attributes of the layer to use the color,       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' have a solid line type, and a specific width.        <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; colorLayer.color = newColor    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; colorLayer.LineType = kContinuousLineType    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; colorLayer.LineWeight = 0.02    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Get all of the curves associated with this occurrence.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error Resume Next    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim drawcurves As DrawingCurvesEnumerator    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set drawcurves = drawView.DrawingCurves(occ)    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Err.Number = 0 Then    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Create an empty collection.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim objColl As ObjectCollection    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set objColl = transObjs.CreateObjectCollection()&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Add the curve segments to the collection.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim drawCurve As DrawingCurve    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For Each drawCurve In drawcurves    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim segment As DrawingCurveSegment    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For Each segment In drawCurve.Segments    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; objColl.Add segment    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next&#160; <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Change the layer of all of the segments.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call drawView.Parent.ChangeLayer(objColl, colorLayer)    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; On Error GoTo 0    <br />&#160;&#160;&#160;&#160;&#160; Else    <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' It's an assembly so process its contents.       <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call ProcessAssemblyColor(drawView, occ.SubOccurrences)    <br />&#160;&#160;&#160;&#160;&#160; End If    <br />&#160;&#160; Next    <br />End Sub</p>  <p>This sample program sets the color of each occurrence based on its color in the assembly. You could choose to set the color based on any other criteria instead. It can be anything associated with the part. you just have to choose what attribute of the part to use and what the associated set of colors are that cam be assigned to each part. For example, you might have a custom iProperty that controls what color is assigned to each part in the drawing.</p>
