---
layout: "post"
title: "Approximating a Sketch Curve with Line Segments"
date: "2010-07-15 19:23:52"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2010/07/approximating-a-sketch-curve-with-line-segments.html "
typepad_basename: "approximating-a-sketch-curve-with-line-segments"
typepad_status: "Publish"
---

<p>Here’s another little VBA macro that I wrote that might be interesting to some of you.&#160; This one takes any sketch curve (circle, arc, spline, ellipse, or elliptical arc) as input, along with the number of segments to break the curve into.&#160; It then creates sketch lines along the curve.&#160; It also sets the original curve to be construction geometry.</p>  <p>This mostly uses the curve geometry query functionality in the API and also demonstrates creating a sketch.&#160; I’ve tried to add comments to the code to help in understanding what it’s doing.&#160; </p>  <div style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">   <p>Public Sub CreateSegmentedCurve()      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Check to see that a curved sketch entity is selected.          <br /></strong></font>&#160;&#160;&#160; Dim entity As SketchEntity       <br />&#160;&#160;&#160; On Error Resume Next       <br />&#160;&#160;&#160; Set entity = ThisApplication.ActiveDocument.SelectSet.Item(1)       <br />&#160;&#160;&#160; If Err.Number &lt;&gt; 0 Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A curved sketch entity must be selected.&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; On Error GoTo 0&#160; <br />      <br />&#160;&#160;&#160; If TypeOf entity Is SketchPoint Or _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TypeOf entity Is SketchLine Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A curved sketch entity must be selected.&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Ask for the number of segments to break the curve into.          <br /></strong></font>&#160;&#160;&#160; Dim prompt As String       <br />&#160;&#160;&#160; prompt = &quot;Enter the number of segments for the curve.&quot;       <br />&#160;&#160;&#160; Dim segmentCount As Integer       <br />&#160;&#160;&#160; segmentCount = Val(InputBox(prompt, &quot;Number of Segments&quot;, &quot;10&quot;))       <br />&#160;&#160;&#160; If segmentCount = 0 Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;Invalid segment count.&quot;       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub       <br />&#160;&#160;&#160; End If&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the parent sketch.          <br /></strong></font>&#160;&#160;&#160; Dim sk As sketch       <br />&#160;&#160;&#160; Set sk = entity.Parent&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the evaluator from the associate geometry.          <br /></strong></font>&#160;&#160;&#160; Dim curveEval As Curve2dEvaluator       <br />&#160;&#160;&#160; Set curveEval = entity.Geometry.Evaluator       <br />&#160;&#160;&#160; Dim minU As Double       <br />&#160;&#160;&#160; Dim maxU As Double       <br />&#160;&#160;&#160; Call curveEval.GetParamExtents(minU, maxU)&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Determine if the entity is open or closed (circle,          <br />&#160;&#160;&#160; ' ellipse, or closed spline)           <br /></strong></font>&#160;&#160;&#160; Dim curveIsClosed As Boolean       <br />&#160;&#160;&#160; curveIsClosed = False       <br />&#160;&#160;&#160; If TypeOf entity Is SketchCircle Or _       <br />&#160;&#160;&#160;&#160;&#160;&#160; TypeOf entity Is SketchEllipse Or _       <br />&#160;&#160;&#160;&#160;&#160;&#160; TypeOf entity Is SketchSpline Or _       <br />&#160;&#160;&#160;&#160;&#160;&#160; TypeOf entity Is SketchOffsetSpline Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If TypeOf entity Is SketchSpline Or _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TypeOf entity Is SketchOffsetSpline Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If entity.Closed Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; curveIsClosed = True       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; curveIsClosed = True       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; Dim tg As TransientGeometry       <br />&#160;&#160;&#160; Set tg = ThisApplication.TransientGeometry&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Determine if start point is at the min or max parameter.          <br /></strong></font>&#160;&#160;&#160; Dim startPoint As SketchPoint       <br />&#160;&#160;&#160; Dim endPoint As SketchPoint       <br />&#160;&#160;&#160; If Not curveIsClosed Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim startCoord() As Double       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim endCoord() As Double       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call curveEval.GetEndPoints(startCoord, endCoord)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If entity.StartSketchPoint.Geometry.IsEqualTo( _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(startCoord(0), startCoord(1))) Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set startPoint = entity.StartSketchPoint       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set endPoint = entity.EndSketchPoint       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set endPoint = entity.StartSketchPoint       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set startPoint = entity.EndSketchPoint       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; End If&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the curve length.          <br /></strong></font>&#160;&#160;&#160; Dim length As Double       <br />&#160;&#160;&#160; Call curveEval.GetLengthAtParam(minU, maxU, length)&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Determine the length between segments.          <br /></strong></font>&#160;&#160;&#160; Dim offset As Double       <br />&#160;&#160;&#160; offset = length / segmentCount&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Start a transaction to wrap the sketch creation as a          <br />&#160;&#160;&#160; ' single undo operation.           <br /></strong></font>&#160;&#160;&#160; On Error GoTo ErrorFound       <br />&#160;&#160;&#160; Dim transMgr As TransactionManager       <br />&#160;&#160;&#160; Set transMgr = ThisApplication.TransactionManager       <br />&#160;&#160;&#160; Dim trans As Transaction       <br />&#160;&#160;&#160; Set trans = transMgr.StartTransaction( _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ThisApplication.ActiveDocument, &quot;Segment Curve&quot;)&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Defer updates on the sketch while the sketch entities          <br />&#160;&#160;&#160; ' are being created.&#160; This will significantly improve           <br />&#160;&#160;&#160; ' performance.           <br /></strong></font>&#160;&#160;&#160; sk.DeferUpdates = True&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Calculate the points and create a sketch          <br />&#160;&#160;&#160; ' point at each position.           <br /></strong></font>&#160;&#160;&#160; Dim points() As SketchPoint       <br />&#160;&#160;&#160; ReDim points(segmentCount)       <br />&#160;&#160;&#160; Dim i As Integer       <br />&#160;&#160;&#160; Dim currentLength As Double       <br />&#160;&#160;&#160; currentLength = 0       <br />&#160;&#160;&#160; For i = 0 To segmentCount       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim currentParam As Double       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call curveEval.GetParamAtLength(minU, currentLength, _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; currentParam)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; currentLength = currentLength + offset&#160; <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim params(0) As Double       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; params(0) = currentParam       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim coords() As Double       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call curveEval.GetPointAtParam(params, coords)&#160; <br />      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If i = 0 Then       <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Special case for first point.          <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If Not curveIsClosed Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set points(i) = startPoint       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set points(i) = sk.SketchPoints.Add( _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(coords(0), coords(1)), False)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set endPoint = points(i)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ElseIf i = segmentCount Then       <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Special case for last point          <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set points(i) = endPoint       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set points(i) = sk.SketchPoints.Add( _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(coords(0), coords(1)), False)       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If       <br />&#160;&#160;&#160; Next&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Connect the points with lines.          <br /></strong></font>&#160;&#160;&#160; For i = 0 To segmentCount - 1       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Call sk.SketchLines.AddByTwoPoints(points(i), points(i + 1))       <br />&#160;&#160;&#160; Next&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Make the selected entity construction geometry.          <br /></strong></font>&#160;&#160;&#160; entity.Construction = True       <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' There's a current problem that when setting the construction          <br />&#160;&#160;&#160; ' property, the display isn't updated to reflect this change           <br />&#160;&#160;&#160; ' until something causes the sketch to recompute.&#160; This performs           <br />&#160;&#160;&#160; ' a change on the sketch to kick a recompute.           <br /></strong></font>&#160;&#160;&#160; Dim originalPoint As Point2d       <br />&#160;&#160;&#160; Set originalPoint = points(0).Geometry       <br />&#160;&#160;&#160; Call points(0).MoveTo(tg.CreatePoint2d( _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; points(0).Geometry.X + 0.001, _       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; points(0).Geometry.Y))       <br />&#160;&#160;&#160; Call points(0).MoveTo(originalPoint)&#160; <br />      <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Turn off the defer to the sketch will recompute normally.          <br /></strong></font>&#160;&#160;&#160; sk.DeferUpdates = False&#160; <br />      <br />&#160;&#160;&#160; trans.End       <br />&#160;&#160;&#160; Exit Sub       <br />      <br />ErrorFound:       <br />&#160;&#160;&#160; sk.DeferUpdates = False&#160; <br />      <br />&#160;&#160;&#160; If Not trans Is Nothing Then       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Abort       <br />&#160;&#160;&#160; End If&#160; <br />      <br />&#160;&#160;&#160; MsgBox &quot;Unexpected error segmenting curve.&quot;       <br />End Sub</p> </div>
