---
layout: "post"
title: "Saving 3D DWG Using the DWG Translator"
date: "2011-05-18 20:19:27"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2011/05/saving-3d-dwg-using-the-dwg-translator.html "
typepad_basename: "saving-3d-dwg-using-the-dwg-translator"
typepad_status: "Publish"
---

<p>Some new functionality in Inventor 2012 is the ability to save 3D part and assembly models to a DWG file.&#160; Ok, this isn’t exactly new but the previous way to do it was a bit of a workaround by using the AEC Exchange application (now known as BIM Exchange) to create the DWG file.&#160; In Inventor 2012 the DWG translator has been expanded to support 3D so you can use the Save Copy As command and select “AutoCAD DWG Files” as the file type.&#160; In the options dialog you can choose which of the following types to write out; Solid, Surface, or Sketch.&#160; You can also specify which version of DWG you want to create; 2000, 2004, 2007, or 2010.</p>  <p>It’s also possible to do the same thing through the API by controlling the DWG translator add-in as shown below.&#160; The result of running the VBA macro below is that it will save the solids in the active part or assembly as an AutoCAD 2010 DWG file called “C:\Temp\DWGOutTest.dwg”.&#160; The options are documented in the comments.</p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt">Public Sub SaveCopyAsDWG3D()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the DWG translator Add-In.&#160; <br /></strong></font>&#160;&#160;&#160; Dim DWGAddIn As TranslatorAddIn     <br />&#160;&#160;&#160; Set DWGAddIn = ThisApplication.ApplicationAddIns.ItemById( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;{C24E3AC2-122E-11D5-8E91-0010B541CD80}&quot;)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the active document.&#160; Can be either a part or assembly.        <br /></strong></font>&#160;&#160;&#160; Dim doc As Document&#160; <br />&#160;&#160;&#160; Set doc = ThisApplication.ActiveDocument&#160; <br />    <br />&#160;&#160;&#160; Dim transObjs As TransientObjects     <br />&#160;&#160;&#160; Set transObjs = ThisApplication.TransientObjects     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Set up the context to define an output file.        <br /></strong></font>&#160;&#160;&#160; Dim context As TranslationContext     <br />&#160;&#160;&#160; Set context = transObjs.CreateTranslationContext     <br />&#160;&#160;&#160; context.Type = kFileBrowseIOMechanism     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Get the available options from the translator.        <br /></strong></font>&#160;&#160;&#160; Dim options As NameValueMap     <br />&#160;&#160;&#160; Set options = transObjs.CreateNameValueMap     <br />&#160;&#160;&#160; If DWGAddIn.HasSaveCopyAsOptions(doc, context, options) Then     <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Set the options for what types of data to write out.&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; options.Value(&quot;Solid&quot;) = True&#160;&#160;&#160;&#160;&#160; ' Output solids.&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; options.Value(&quot;Surface&quot;) = False&#160;&#160; ' Output surfaces.&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; options.Value(&quot;Sketch&quot;) = False&#160;&#160;&#160; ' Output sketches.     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br /><font color="#0000ff"><strong>&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' Set the DWG version.        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' 23 = ACAD 2000         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' 25 = ACAD 2004         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' 27 = ACAD 2007         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' 29 = ACAD 2010&#160; <br /></strong></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; options.Value(&quot;DwgVersion&quot;) = 29     <br />&#160;&#160;&#160; End If     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Set the output filename, using a DataMedium object.        <br /></strong></font>&#160;&#160;&#160; Dim oDataMedium As DataMedium     <br />&#160;&#160;&#160; Set oDataMedium = transObjs.CreateDataMedium     <br />&#160;&#160;&#160; oDataMedium.filename = &quot;c:\temp\DWGOutTest.dwg&quot;     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Call the SaveCopyAs method of the translator add-in.        <br /></strong></font>&#160;&#160;&#160; Call DWGAddIn.SaveCopyAs(doc, context, options, oDataMedium)     <br />End Sub</p>
