---
layout: "post"
title: "Importing Non-Native Models into Inventor"
date: "2011-02-03 22:48:08"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2011/02/importing-non-native-models-into-inventor.html "
typepad_basename: "importing-non-native-models-into-inventor"
typepad_status: "Publish"
---

<p>My friends from the DevTech group, which support the members of the <a href="http://www.autodesk.com/adn">Autodesk Developer Network (ADN)</a>, are helping me out while I’m buried with project work and are providing some content for blog posts.&#160; This one is from Xiaodong Liang who works in the Beijing China office.    <br />    <br />There are two basic mechanisms for importing non-native surface or solid bodies into Inventor. The first involves using the TransientBrep.ReadFromFile method to read a surface body in directly. The second mechanism involves using a suitable translator add-in to read the data in. In both cases the surface/solid data can then be added as a Part feature via the NonParametricFeatures.Add method.</p>  <p>This first code sample illustrates how to use the TransientBrep.ReadFromFile mechanism to read the model data from a SAT file:-</p>  <p style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Sub importByBrep()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get the active part document        <br /></font>&#160;&#160;&#160; </strong>Dim oDoc As PartDocument     <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get transient Brep        <br /></font>&#160;&#160;&#160; </strong>Dim oBrep As TransientBRep     <br />&#160;&#160;&#160; Set oBrep = ThisApplication.TransientBRep     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get the surfacebodies        <br /></font>&#160;&#160;&#160; </strong>Dim oSBs As SurfaceBodies     <br />&#160;&#160;&#160; Set oSBs = oBrep.ReadFromFile(&quot;c:\temp\test.sat&quot;)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get definition of current document        <br /></font>&#160;&#160;&#160; </strong>Dim oActiveDocDef As PartComponentDefinition     <br />&#160;&#160;&#160; Set oActiveDocDef = oDoc.ComponentDefinition     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Add each surfacebody of imported file to        <br />&#160;&#160;&#160; ' NonParametricBaseFeatures         <br /></font>&#160;&#160;&#160; </strong>Dim oSB As SurfaceBody     <br />&#160;&#160;&#160; For Each oSB In oSBs     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oActiveDocDef.Features.NonParametricBaseFeatures.Add oSB     <br />&#160;&#160;&#160; Next     <br />    <br />&#160;&#160;&#160; oDoc.Update     <br />End Sub</p>  <p>This next code sample illustrates how to use one of the translator add-ins to read the relevant data in, again from a SAT file.</p>  <p style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Sub ImportByTanstorAddin()    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get the active part document        <br /></font>&#160;&#160;&#160; </strong>Dim oActiveDoc As PartDocument     <br />&#160;&#160;&#160; Set oActiveDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get definition of active part document        <br /></font>&#160;&#160;&#160; </strong>Dim oActiveDocDef As PartComponentDefinition     <br />&#160;&#160;&#160; Set oActiveDocDef = oActiveDoc.ComponentDefinition     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get SAT TranslatorAddIn        <br /></font>&#160;&#160;&#160; </strong>Dim oAddin As TranslatorAddIn     <br />&#160;&#160;&#160; Set oAddin = ThisApplication.ApplicationAddIns.ItemById( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &quot;{89162634-02B6-11D5-8E80-0010B541CD80}&quot;)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Create context for open&#160; <br /></font>&#160;&#160;&#160; Dim oTransObjs As TransientObjects       <br />&#160;&#160;&#160; Set oTransObjs = ThisApplication.TransientObjects       <br />&#160;&#160;&#160; </strong>Dim oContext As TranslationContext     <br />&#160;&#160;&#160; Set oContext = oTransObjs.CreateTranslationContext     <br />&#160;&#160;&#160; oContext.Type = kDataDropIOMechanism     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Create option for open        <br /></font>&#160;&#160;&#160; </strong>Dim oOptions As NameValueMap     <br />&#160;&#160;&#160; Set oOptions = oTransObjs.CreateNameValueMap     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Create DataMedium for open        <br /></font>&#160;&#160;&#160; </strong>Dim oDataMedium As DataMedium     <br />&#160;&#160;&#160; Set oDataMedium = oTransObjs.CreateDataMedium     <br />&#160;&#160;&#160; Call oOptions.Add(&quot;ImportSolid&quot;, True)     <br />&#160;&#160;&#160; oDataMedium.fileName = &quot;c:\temp\test.sat&quot;     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Open the SAT file        <br /></font>&#160;&#160;&#160; </strong>Dim oNewDoc As PartDocument     <br />&#160;&#160;&#160; Call oAddin.Open(oDataMedium, oContext, oOptions, oNewDoc)     <br />&#160;&#160;&#160; Dim oNewDocDef As PartComponentDefinition     <br />&#160;&#160;&#160; Set oNewDocDef = oNewDoc.ComponentDefinition     <br />    <br />&#160;<font color="#0000ff"><strong>&#160;&#160; </strong></font><strong><font color="#0000ff">' Read the surfacebodies to the current document        <br /></font>&#160;&#160;&#160; </strong>Dim oSB As SurfaceBody     <br />&#160;&#160;&#160; For Each oSB In oNewDocDef.SurfaceBodies     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oActiveDocDef.Features.NonParametricBaseFeatures.Add oSB     <br />&#160;&#160;&#160; Next     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Close the temp doc without saving        <br /></font>&#160;&#160;&#160; </strong>oNewDoc.Close True     <br />End Sub</p>  <p>What can be confusing about this is that reading multiple bodies from different files this way yields a solid for the first import, but surfaces for any further imports to the same Part document.&#160; A solid is created if there are no other solids in the Part and a surface is created if there is at least one solid in the Part already. This was the behavior in Inventor when importing bodies interactively until the recent addition of support for multiple solid bodies in a single part.&#160; The behavior of the method&#160; <b>NonParametricBaseFeatures.Add</b> mimics the old behavior.&#160; </p>  <p>There is a way to get the new behavior though. We can use a definition object to stipulate exactly what kind of model is imported (Solid or Surface). The <b>CreateDefinition</b> and <b>AddByDefinition</b> methods of the <b>NonParametricBaseFeatures</b> object were added in Inventor 2011 and support additional flexibility that the <b>Add</b> method doesn’t. <b>CreateDefinition</b> is used to create the relevant definition object, which then specifies the output type of the NonParametricBaseFeature (surface, solid, multiple solids or composite type). The code below illustrates how this can be used to import solids:-</p>  <p style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Sub BatchImport()    <br />&#160;&#160;&#160; ImportEachFile &quot;C:\temp\test.sat&quot;, 1     <br />&#160;&#160;&#160; ImportEachFile &quot;C:\temp\test2.sat&quot;, 2     <br />End Sub</p>  <p style="font-size: 8pt; background: #eeeeee; color: black; line-height: 140%; font-family: courier new">Sub ImportEachFile(fileName As String, index As Integer)    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get the active part document        <br /></font>&#160;&#160;&#160; </strong>Dim oDoc As PartDocument     <br />&#160;&#160;&#160; Set oDoc = ThisApplication.ActiveDocument     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get transient Brep        <br /></font>&#160;&#160;&#160; </strong>Dim oBrep As TransientBRep     <br />&#160;&#160;&#160; Set oBrep = ThisApplication.TransientBRep     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get the surfacebodies        <br /></font>&#160;&#160;&#160; </strong>Dim oSBs As SurfaceBodies     <br />&#160;&#160;&#160; Set oSBs = oBrep.ReadFromFile(fileName)     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' To transform the body        <br /></font>&#160;&#160;&#160; Dim oTG As TransientGeometry       <br />&#160;&#160;&#160; Set oTG = ThisApplication.TransientGeometry       <br />&#160;&#160;&#160; </strong>Dim oMatrix As Matrix     <br />&#160;&#160;&#160; Set oMatrix = oTG.CreateMatrix()     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Move the body arbitrarily        <br /></font>&#160;&#160;&#160; </strong>oMatrix.SetTranslation oTG.CreateVector( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; index * 10, index * 10, 0)&#160; <br />&#160;&#160;&#160; Dim oTransObjs As TransientObjects     <br />&#160;&#160;&#160; Set oTransObjs = ThisApplication.TransientObjects     <br />&#160;&#160;&#160; Dim oObjColl As ObjectCollection     <br />&#160;&#160;&#160; Set oObjColl = oTransObjs.CreateObjectCollection()     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Add each surfacebody of imported file to ObjectCollection        <br /></font>&#160;&#160;&#160; </strong>Dim oSB As SurfaceBody     <br />&#160;&#160;&#160; For Each oSB In oSBs     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oBrep.Transform oSB, oMatrix     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; oObjColl.Add oSB     <br />&#160;&#160;&#160; Next     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Get definition of current document        <br /></font>&#160;&#160;&#160; </strong>Dim oPartDef As PartComponentDefinition     <br />&#160;&#160;&#160; Set oPartDef = oDoc.ComponentDefinition     <br />&#160;&#160;&#160; Dim oFeatures As PartFeatures     <br />&#160;&#160;&#160; Set oFeatures = oPartDef.Features     <br />&#160;&#160;&#160; Dim oNPFD As NonParametricBaseFeatureDefinition     <br />&#160;&#160;&#160; Set oNPFD = oFeatures.NonParametricBaseFeatures.CreateDefinition     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; ' Assign the ObjectCollection to the definition.</strong></font><strong><font color="#0000ff">        <br /></font>&#160;&#160;&#160; </strong>oNPFD.BRepEntities = oObjColl     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Set the output type        <br /></font>&#160;&#160;&#160; </strong>oNPFD.OutputType = kSolidOutputType     <br />    <br /><font color="#0000ff"><strong>&#160;&#160;&#160; </strong></font><strong><font color="#0000ff">' Create the NonParametricBaseFeature using the definition.        <br /></font>&#160;&#160;&#160; </strong>oPartDef.Features.NonParametricBaseFeatures.AddByDefinition oNPFD     <br />End Sub</p>  <p>   <br />And there we have it! I hope this answers a few questions about importing solids into Inventor.</p>
