---
layout: "post"
title: "Create an iPart"
date: "2012-03-14 00:45:35"
author: "Wayne Brill"
categories:
  - "Beginning API"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/03/create-an-ipart.html "
typepad_basename: "create-an-ipart"
typepad_status: "Publish"
---

<p>To make a part into an iPart, you use the CreateFactory method of the PartComponentDefinition. The iPartFactory returned by the call to CreateFactory does have a TableRows collection but it does not have an Add method and the way to add the rows that you need for your iPart, may not be obvious. </p>  <p>My colleague Philippe Leefsma has this example that shows what needs to be done. It uses the Excel Spreadsheet returned from the ExcelWorkSheet property of the iPartFactory to create the table used to define the functionality of the iPart. In this <a href="http://modthemachine.typepad.com/iPart_VS_Example.zip">visual studio project</a> you will find the CreateiPart Sub Procedure and a couple of other procedures. One adds a new row to the iPart and the other prints the contents of the table to the immediate window. </p>  <div style="font-family: consolas; background: #eeeeee; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Public</span> <span style="color: blue">Sub</span> CreateiPart()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oPartDoc <span style="color: blue">As</span> <span style="color: #2b91af">PartDocument</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPartDoc = _InvApplication.Documents.Add _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">DocumentTypeEnum</span>.kPartDocumentObject, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160; _InvApplication.FileManager.GetTemplateFile _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #2b91af">DocumentTypeEnum</span>.kPartDocumentObject), _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">True</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPartDoc.SaveAs _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (<span style="color: #a31515">&quot;c:\Temp\iPart_By_API.ipt&quot;</span>, <span style="color: blue">False</span>)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oTG <span style="color: blue">As</span> <span style="color: #2b91af">TransientGeometry</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oTG = _InvApplication.TransientGeometry</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oCompDef <span style="color: blue">As</span> <span style="color: #2b91af">PartComponentDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oCompDef = oPartDoc.ComponentDefinition</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oPoints(3) <span style="color: blue">As</span> <span style="color: #2b91af">Point2d</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPoints(0) = oTG.CreatePoint2d(0, 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPoints(1) = oTG.CreatePoint2d(5, 0)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPoints(2) = oTG.CreatePoint2d(5, 5)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPoints(3) = oTG.CreatePoint2d(0, 5)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oSketch <span style="color: blue">As</span> <span style="color: #2b91af">PlanarSketch</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch = oCompDef.Sketches.Add _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oCompDef.WorkPlanes(1))</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oLines(3) <span style="color: blue">As</span> <span style="color: #2b91af">SketchLine</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLines(0) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchLines.AddByTwoPoints _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oPoints(0), oPoints(1))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLines(1) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchLines.AddByTwoPoints _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oLines(0).EndSketchPoint, oPoints(2))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLines(2) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchLines.AddByTwoPoints _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oLines(1).EndSketchPoint, oPoints(3))</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLines(3) = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oSketch.SketchLines.AddByTwoPoints _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oLines(2).EndSketchPoint, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oLines(0).StartSketchPoint)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oProfile <span style="color: blue">As</span> <span style="color: #2b91af">Profile</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oProfile = oSketch.Profiles.AddForSolid</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oExtrude <span style="color: blue">As</span> <span style="color: #2b91af">ExtrudeFeature</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oExtrude = oCompDef.Features. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ExtrudeFeatures.AddByDistanceExtent _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (oProfile, 15, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PartFeatureExtentDirectionEnum</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kPositiveExtentDirection, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">PartFeatureOperationEnum</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kNewBodyOperation, 0)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oExtrude.FeatureDimensions(1). _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Parameter.Name = <span style="color: #a31515">&quot;Length&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oExtrude.FeatureDimensions(2). _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Parameter.Name = <span style="color: #a31515">&quot;TaperAngle&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oFactory <span style="color: blue">As</span> <span style="color: #2b91af">iPartFactory</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oFactory = oCompDef.CreateFactory</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oWS <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Microsoft.Office.Interop.Excel.<span style="color: #2b91af">Worksheet</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS = oFactory.ExcelWorkSheet</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(1, 1) = _</p>    <p style="margin: 0px">&#160;<span style="color: #a31515">&quot;Member&lt;defaultRow&gt;1&lt;/defaultRow&gt;&lt;filename&gt;&lt;/filename&gt;&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(1, 2) = <span style="color: #a31515">&quot;Part Number [Project]&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(1, 3) = <span style="color: #a31515">&quot;Length&lt;free&gt;150 mm&lt;/free&gt;&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(1, 4) = <span style="color: #a31515">&quot;TaperAngle&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(2, 1) = <span style="color: #a31515">&quot;iPart_By_API-01&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(2, 2) = <span style="color: #a31515">&quot;iPart_By_API-01&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(2, 3) = <span style="color: #a31515">&quot;150 mm&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(2, 4) = <span style="color: #a31515">&quot;0 deg&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(3, 1) = <span style="color: #a31515">&quot;iPart_By_API-02&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(3, 2) = <span style="color: #a31515">&quot;iPart_By_API-02&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(3, 3) = <span style="color: #a31515">&quot;100 mm&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(3, 4) = <span style="color: #a31515">&quot;5 deg&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(4, 1) = <span style="color: #a31515">&quot;iPart_By_API-03&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(4, 2) = <span style="color: #a31515">&quot;iPart_By_API-03&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(4, 3) = <span style="color: #a31515">&quot;50 mm&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWS.Cells(4, 4) = <span style="color: #a31515">&quot;10 deg&quot;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oWB <span style="color: blue">As</span>&#160; _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Microsoft.Office.Interop.Excel.<span style="color: #2b91af">Workbook</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWB = oWS.Parent</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWB.Save()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oWB.Close()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPartDoc.Update()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oPartDoc.Save()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Sub</span></p> </div>  <p>Wayne Brill</p>
