---
layout: "post"
title: "Creating and Setting up Your Project"
date: "2012-04-09 05:02:55"
author: "Adam Nagy"
categories:
  - "Brian"
  - "Getting Started Tutorial"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/04/creating-and-setting-up-your-project.html "
typepad_basename: "creating-and-setting-up-your-project"
typepad_status: "Publish"
---

<p>If you’ve gone through the lessons in the <a href="http://modthemachine.typepad.com/my_weblog/2012/03/getting-started-programming-inventor.html">book I suggested earlier</a>, or any of the <a href="http://msdn.microsoft.com/en-us/vstudio/bb466226.aspx">online Microsoft tutorials</a> that are available you should be familiar with what projects are and how to create them.&#160; I won’t go into a lot of detail but will go through the steps below.</p>  <p>Here are the steps to creating an exe program that will access and control Inventor using the API.</p>  <ol>   <li>After running Visual Basic 2010 Express, select the “New Project…” option, which is outlined in red below.      <br />      <br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168e9d48668970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="VBStartPage" border="0" alt="VBStartPage" src="/assets/image_103636.jpg" width="454" height="371" /></a>&#160; </li>    <li>In the <strong>New Project</strong> dialog select “Windows Forms Application” as the type of project and enter “DrawShape” for the project name.&#160; <br />      <br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016303def149970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="VBNewProject" border="0" alt="VBNewProject" src="/assets/image_969914.jpg" width="454" height="257" /></a> </li>    <li>The project you’ve just created is a standard Windows application and doesn’t have any knowledge about Inventor’s API.&#160; In order to access Inventor’s API you need to make your project aware of the API and what it supports.&#160; You do this by referencing Inventor’s Interop library.&#160; The interop completely describes the API in a .Net friendly way.      <br />      <br />To add the reference choose the “Add Reference…” command from the Project menu, as shown below.       <br />      <br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016764d38b6a970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="VBAddReferenceMenu" border="0" alt="VBAddReferenceMenu" src="/assets/image_728350.jpg" width="254" height="210" /></a>       <br />In the <strong>Add Reference</strong> dialog choose the Browse tab and browse to the directory below (for whatever version of Inventor you’re using).&#160; <br />      <br />&#160;&#160; <font face="MS Reference Sans Serif">C:\Program Files\Autodesk\Inventor 2013\bin\Public Assemblies</font>       <br />      <br />Select “Autodesk.Inventor.Interop.dll”, as shown below and click OK.       <br />      <br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016303def169970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="VBAddReference" border="0" alt="VBAddReference" src="/assets/image_468762.jpg" width="454" height="237" /></a>&#160; <br />You can view the references a project has by using the Project window and selecting the “Show All Files” button highlighted in red below.&#160; All of the references will be displayed in the “References” folder.       <br />      <br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168e9d4869c970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="VBShowReferences" border="0" alt="VBShowReferences" src="/assets/image_315091.jpg" width="221" height="244" /></a> </li>    <li>I’ll talk more about this in my next post, but just so we end this post with your program doing something somewhat useful, add a button to your form, (I called mine btnRun), and add the code below into the Click event of the button.&#160; (Sorry about the weird line continuations but the width of a line in this blog interface is very limited.) </li> </ol>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt"><font color="#0000ff"><strong>' Connect to a running instance of Inventor.&#160; <br /></strong></font>Dim invApp As Inventor.Application&#160; <br />Try&#160; <br />&#160;&#160;&#160; invApp = _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; System.Runtime.InteropServices.Marshal.GetActiveObject _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (&quot;Inventor.Application&quot;)&#160; <br />Catch ex As Exception&#160; <br />&#160;&#160;&#160; MessageBox.Show(&quot;Inventor must be running.&quot;)&#160; <br />&#160;&#160;&#160; Exit Sub&#160; <br />End Try     <br />    <br /><font color="#0000ff"><strong>' Create a new part document.&#160; <br /></strong></font>Dim partDoc As Inventor.PartDocument&#160; <br />partDoc = invApp.Documents.Add( _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Inventor.DocumentTypeEnum.kPartDocumentObject)     <br /></font></p>  <blockquote>   <p>Now when you run your application and click the button the program will connect to Inventor if it’s running or display a warning message if it’s not.&#160; If it is running it will create a new part document.&#160; Each time you click the button a new part will be created.&#160; In the next post we’ll look at this code in more detail and discuss the basics of working with documents.</p> </blockquote>  <p>-Brian</p>
