---
layout: "post"
title: "Working with Sketches"
date: "2012-04-20 20:30:05"
author: "Adam Nagy"
categories:
  - "Brian"
  - "Getting Started Tutorial"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/04/working-with-sketches.html "
typepad_basename: "working-with-sketches"
typepad_status: "Publish"
---

<p>In this post, on our slow journey towards creating a command that creates a slot shape in a sketch, I’m going to discuss the main principles when working with sketches.</p>  <p>You can create a sketch in a part or assembly but I’m only going to address parts for now.&#160; A sketch is basically a 2D coordinate system positioned in 3D space.&#160; The API has a special type of object for this type of sketch called a <em>PlanarSketch</em> since it’s defining a plane in 3D space.&#160; There is also a <em>DrawingSketch</em> which is slightly different since a drawing is already 2D.&#160; Typically, sketches are created by referencing an existing planar entity, either a planar face or a work plane.&#160; The sketch is associatively related to the entity so that if the entity moves the sketch moves with it.</p>  <p>When you pick a face or work plane, Inventor has some logic that it uses to determine the orientation and origin of the 2D coordinate system that’s defined during the creation of the sketch.&#160; You typically don’t care about this orientation because the default is usually what you expect and the main thing it affects is the horizontal and vertical directions.&#160; The origin doesn’t matter since you dimension the sketch geometry relative to other geometry in the model so the actual x-y coordinates of the sketch geometry is immaterial.&#160; The picture below shows a selected face on a part where I want to create a sketch.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168ea77864b970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="SketchPlaneEntity" border="0" alt="SketchPlaneEntity" src="/assets/image_969781.jpg" width="300" height="333" /></a></p>  <p>&#160;</p>  <p>After creating the sketch it is possible to see and even edit the coordinate system that was defined for this sketch.&#160; You can do this using the “Edit Coordinate System” command that’s accessed through the context menu for the sketch.&#160; A 2D triad is displayed indicating the origin and the direction of the x and y axes.&#160; While in this command you can edit these to reorient the sketch on the plane.</p>  <p align="center"><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340163048218eb970d-pi"><img title="EditCoordSysCommand" border="0" alt="EditCoordSysCommand" src="/assets/image_824584.jpg" width="150" height="161" /></a>&#160;&#160;&#160;&#160; <a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401676575ccf4970b-pi"><img title="SketchCoordSystem" border="0" alt="SketchCoordSystem" src="/assets/image_511729.jpg" width="275" height="312" /></a></p>  <p align="center">The yellow lines you see in the picture above are sketch lines that were automatically created by projecting the edges of the selected face onto the sketch.&#160; This is the default behavior of Inventor but is controlled using the setting in the Application Options dialog as shown below.</p>  <p align="center"><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401630482193c970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="AutoProjectEdges" border="0" alt="AutoProjectEdges" src="/assets/image_764002.jpg" width="415" height="279" /></a></p>  <p align="center">&#160;</p>  <p align="center">To create a sketch using the API you need to use the collection object for sketches.&#160; Remember from the discussion in the previous post that collection objects provide access to existing objects of a certain type and also support methods to create new objects of that type.&#160; Below is a simplified view of the object hierarchy to get to the PlanarSketches object.&#160; We’ve already discussed how to create a PartDocument object but most of the data that we think of as part specific data, (features, work features, parameters, imates, etc.) are part of the <em>PartComponentDefinition</em> object.&#160; There is always a one-to-one relationship between a PartDocument and a PartComponentDefinition object.&#160; Don’t get too caught up in why there is a PartComponentDefinition object but instead just remember that for part information you’ll need to take that one extra step to get the PartComponentDefinition from the PartDocument.&#160; </p>  <p align="center"><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401630482194d970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="SketchModel" border="0" alt="SketchModel" src="/assets/image_479151.jpg" width="264" height="219" /></a></p>  <p align="center">Below is some code that creates a new part document and creates a new sketch on the X-Y work plane of the part.&#160; </p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt"><font color="#0000ff"><strong>' Connect to a running instance of Inventor.</strong></font>     <br />Dim invApp As Inventor.Application     <br />invApp = System.Runtime.InteropServices.Marshal.GetActiveObject _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (&quot;Inventor.Application&quot;)     <br />    <br /><font color="#0000ff"><strong>' Get the Documents collection.</strong></font>     <br />Dim docs As Inventor.Documents docs = invApp.Documents     <br />    <br /><font color="#0000ff"><strong>' Create a new part document.</strong></font>     <br />Dim partDoc As Inventor.PartDocument     <br />partDoc = docs.Add(Inventor.DocumentTypeEnum.kPartDocumentObject)     <br />    <br /><font color="#0000ff"><strong>' Get the component definition.</strong></font>     <br />Dim partDef As Inventor.PartComponentDefinition     <br />partDef = partDoc.ComponentDefinition     <br />    <br /><font color="#0000ff"><strong>' Get the X-Y work plane.        <br /></strong></font>Dim xyPlane As Inventor.WorkPlane = partDef.WorkPlanes.Item(3)     <br />    <br /><font color="#0000ff"><strong>' Create a new sketch.</strong></font>     <br />Dim sketch As Inventor.PlanarSketch     <br />sketch = partDef.Sketches.Add(xyPlane, False) </p>  <p>&#160;</p>  <p>The code above uses the ComponentDefinition property of the PartDocument object to get the PartComponentDefinition object associated with the part.&#160; In most cases the name of the property matches the name of the object is returns but that’s not always the case as in this example.&#160; </p>  <p>Next it gets the X-Y work plane from the part.&#160; It does this by getting the WorkPlanes collection object from the PartComponentDefinition and gets a work plane from it using the Item property.&#160; The WorkPlanes collection object contains all of the work planes in a part and also supports several Add methods to create new work planes.&#160; All parts will always have at least three work planes, three work axes, and one work point.&#160; Below is a picture of the browser for a new, empty part.&#160; You can see the base work features that exist in every part.&#160; When accessing these through the API they are returned by the API collection objects in the same order they’re shown in the browser.&#160; For example, getting WorkPlanes.Item(1) will return the YZ Plane.&#160; Getting WorkAxes.item(2) will return the Y axis. and getting WorkPoints.Item(1) will always return the origin work point.&#160; The user cannot delete or reorder these base work features so this is guaranteed to always be true.&#160; In this case I’m getting item 3 from the WorkPlanes collection, which is the XY Plane.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016304821966970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="BrowserNewPart" border="0" alt="BrowserNewPart" src="/assets/image_254590.jpg" width="187" height="293" /></a></p>  <p>The last section of code, shown below, creates a new sketch.&#160; There are a couple of things that I want to point out here.&#160; There are several things happening on the line where the sketch gets created.&#160; First, the Sketches property of the PartComponentDefinition is called.&#160; This returns a PlanarSketches object.&#160; Next, the Add method of the PlanarSketches object is called.&#160; This line could have been broken up into multiple lines by first getting the PlanarSketches object and then calling the Add method.&#160; Most languages support the ability to combine these calls into a single line to allow for less code.&#160; Just be aware that there are several calls being made on that single line, which can sometimes make problems a little more difficult to debug because if that line fails it’s difficult to know which call failed.</p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt"><font color="#0000ff"><strong>' Create a new sketch.</strong></font>     <br />Dim sketch As Inventor.PlanarSketch     <br />sketch = partDef.Sketches.Add(xyPlane, False) </p>  <p>The Add method to create a new sketch is fairly simple.&#160; It has two arguments.&#160; The first is the planar object you want to create the sketch on.&#160; This can be a work plane, like in this example, or it can be a planar face.&#160; The second argument indicates if the edges of the face should be copied into the sketch.&#160; This is the equivalent of the “Auto Project” option discussed above.&#160; The API ignores the application setting for the auto project and allows you to control it explicitly when you create a sketch.&#160; This setting is only used when you’re creating a sketch on a face and is ignored when a work plane is used.&#160; In fact the second argument is defined to be an optional argument so I could have left it out.&#160; It defaults to False if you don’t specify it.</p>  <p>The work plane created is the same as if you had interactively created it in Inventor, in that the origin and orientation of the plane is automatically inferred by Inventor.&#160; The PlanarSketches collection also supports an AddWithOrientation method that lets you specify the origin and orientation when you create it.&#160; In practice this is rarely used.</p>  <p>If you run the code above it will create a new part and you’ll see a new empty sketch in the part.&#160; Each time you run the program you get a new part with a sketch.&#160; Not too exciting yet, but in the next post we’ll look at drawing geometry on the sketch.&#160; Then it gets a lot more fun <img style="border-bottom-style: none; border-left-style: none; border-top-style: none; border-right-style: none" class="wlEmoticon wlEmoticon-smile" alt="Smile" src="/assets/image_194504.jpg" />.</p>  <p>-Brian</p>
