---
layout: "post"
title: "SurfaceGraphics &ndash; Select Primitives"
date: "2012-03-28 21:10:51"
author: "Wayne Brill"
categories: []
original_url: "https://modthemachine.typepad.com/my_weblog/2012/03/surfacegraphics-select-primitives.html "
typepad_basename: "surfacegraphics-select-primitives"
typepad_status: "Publish"
---

<p>The Inventor 2013 API has enhancements for ClientGraphics including the ability to control which parts of SurfaceGraphics will be selectable. (These are B-Rep entities within the graphics).</p>  <p>In previous releases you could create SurfaceGraphics, but the entire graphic would have been considered a primitive and just selectable as one entity. </p>  <p><strong>New 2013 properties for SurfaceGraphics: </strong></p>  <ul>   <li>SurfaceGraphics.ChildrenAreSelectable </li>    <li>SurfaceGraphicsEdge.Selectable </li>    <li>SurfaceGraphicsFace.Selectable </li>    <li>SurfaceGraphicsVertex.Selectable </li>    <li>SurfaceGraphics.DisplayedVertices </li> </ul>  <p>To make different parts of the SurfaceGraphics selectable, make that <strong>Selectable</strong> boolean property equal to true.&#160; </p>  <p>Also in this release there are a couple of new objects related to SurfaceGraphics. </p>  <p><strong>New 2013 Objects related to SurfaceGraphics:</strong></p>  <ul>   <li>SurfaceGraphicsVertex </li>    <li>SurfaceGraphicsVertexList </li> </ul>  <p><strong></strong></p>  <p><strong>VBA Example. </strong>(Please keep in mind that we only recommend using VBA for prototyping and learning the API but do not recommend using VBA in production).</p>  <p>This example demonstrates this new functionality. When you run the code it will display the open dialog that allows you to select an ipt or sat file that will be used to create the SurfaceGraphics. (The active document needs to be a part or assembly). A message box is then displayed with three options that control the user’s ability to select parts of the SurfaceGraphic. </p>  <ul>   <li>Yes - Make just the node selectable. (The entire body will be one selectable thing) </li>    <li>No - Everything is selectable. (Each edge, face and vertex) </li>    <li>Cancel - Disable selection for all the edges and vertices and make every other face selectable. (shows that you can control what is selectable in the SurfaceGraphics) </li> </ul>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401676459d5c6970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_966186.jpg" width="465" height="217" /></a></p>  <p>Here is a screenshot that shows the result of selecting “<strong>Yes</strong>”. The entire SurfaceGraphics is only selectable. </p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401676459d5db970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_520832.jpg" width="457" height="246" /></a></p>  <p>Also just to be clear, notice that this isn’t real inventor geometry. If you look at the model browser there are not any solid bodies or features. This is just client graphics.</p>  <p>Here you can see the result of selecting “<strong>Cancel</strong>” It will only allow you to select every other face which is kind of arbitrary. (Whatever order they came up in the faces collection). Also you can’t pick edges or vertices. </p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168e95af440970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_158486.jpg" width="407" height="310" /></a></p>  <p>You can run the procedure again with the “<strong>No</strong>” option to create a SurfaceGraphics that will allow you to select everything.&#160; (Each time the procedure runs it deletes the ClientGraphics named “test” and then recreates it).&#160; </p>  <p><strong>VBA Code</strong></p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 9pt">Public Sub SelectablePrimitives()    <br />&#160;&#160;&#160; <font color="#0000ff">' Make sure a part or assembly is active.</font>     <br />&#160;&#160;&#160; If ThisApplication.ActiveDocumentType &lt;&gt; _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kAssemblyDocumentObject _     <br />&#160;&#160;&#160;&#160;&#160; And ThisApplication.ActiveDocumentType _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; &lt;&gt; kPartDocumentObject Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox &quot;A part or assembly must be active.&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">' Get the document and it's      <br />&#160;&#160;&#160; ' associated definition.       <br /></font>&#160;&#160;&#160; Dim doc As Document     <br />&#160;&#160;&#160; Set doc = ThisApplication.ActiveDocument     <br />&#160;&#160;&#160; Dim def As ComponentDefinition     <br />&#160;&#160;&#160; Set def = doc.ComponentDefinition     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">' Get an .ipt or SAT filename from the user.      <br /></font>&#160;&#160;&#160; Dim dialog As FileDialog     <br />&#160;&#160;&#160; Dim filename As String     <br />&#160;&#160;&#160; Call ThisApplication.CreateFileDialog(dialog)     <br />&#160;&#160;&#160; With dialog     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Filter = _     <br />&quot;Inventor Part File (*.ipt)|*.ipt|ACIS SAT File (*.sat)|*.sat&quot;     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .FilterIndex = 0     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; .ShowOpen     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If .filename = &quot;&quot; Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Exit Sub     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Else     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; filename = .filename     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; End With     <br />&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">' Get the transient B-Rep object.      <br /></font>&#160;&#160;&#160; Dim tb As TransientBRep     <br />&#160;&#160;&#160; Set tb = ThisApplication.TransientBRep     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; <font color="#0000ff">' If a part was selected, open it invisibly      <br />&#160;&#160;&#160; ' and get the body.       <br /></font>&#160;&#160;&#160; Dim body As SurfaceBody     <br />&#160;&#160;&#160; If UCase(Right$(filename, 4)) = &quot;.IPT&quot; Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim newPart As PartDocument     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set newPart = ThisApplication.Documents. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Open(filename, False)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Copy out the first body of the part.      <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set body = tb.Copy _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (newPart.ComponentDefinition. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; SurfaceBodies.Item(1))     <br />&#160;&#160;&#160; Else     <br />&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Read in the sat file.</font>     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim bodies As SurfaceBodies     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set bodies = tb.ReadFromFile(filename)     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Set body = bodies.Item(1)     <br />&#160;&#160;&#160; End If     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160; <font color="#0000ff">' Create the client graphics object.      <br /></font>&#160;&#160;&#160; Dim graphics As ClientGraphics     <br />&#160;&#160;&#160; On Error Resume Next     <br />&#160;&#160;&#160; Set graphics = def.ClientGraphicsCollection _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Item(&quot;Test&quot;)     <br />&#160;&#160;&#160; If Err.Number = 0 Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; graphics.Delete     <br />&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; On Error GoTo 0     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Set graphics = def.ClientGraphicsCollection _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Add(&quot;Test&quot;)     <br />&#160;&#160;&#160; Dim node As GraphicsNode     <br />&#160;&#160;&#160; Set node = graphics.AddNode(1)     <br />&#160;&#160;&#160; node.Selectable = True     <br />&#160;&#160;&#160; node.DisplayName = &quot;My Solid&quot;     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim answer As VbMsgBoxResult     <br />&#160;&#160;&#160; answer = MsgBox _     <br />(&quot;Yes=Node Selectable, No=All Selectable, Cancel=Every other face selectable&quot;, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; vbYesNoCancel + vbQuestion)     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; Dim solidGraphics As SurfaceGraphics     <br />&#160;&#160;&#160; Set solidGraphics = node.AddSurfaceGraphics(body)     <br />&#160;&#160;&#160; ThisApplication.ActiveView.Update     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160; If answer = vbYes Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; solidGraphics.ChildrenAreSelectable = False     <br />&#160;&#160;&#160; Else     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; solidGraphics.ChildrenAreSelectable = True     <br />&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; If answer = vbCancel Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dim i As Integer     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Make Selectable False for all the      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' SurfaceGraphicsVertex       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 1 To solidGraphics. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; DisplayedVertices.Count     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; solidGraphics.DisplayedVertices _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Item(i).Selectable = False     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Make Selectable False for all the      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' SurfaceGraphicsEdge       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 1 To solidGraphics. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; DisplayedEdges.Count     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; solidGraphics.DisplayedEdges _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Item(i).Selectable = False     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <font color="#0000ff">' Make Selectable every other      <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ' SurfaceGraphicsFace False       <br /></font>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; For i = 1 To solidGraphics. _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; DisplayedFaces.Count     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; If i Mod 2 = 0 Then     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; solidGraphics.DisplayedFaces _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; .Item(i).Selectable = False     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Next     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; End If     <br />&#160;&#160;&#160; End If     <br />End Sub</p>  <p>Wayne Brill</p>
