---
layout: "post"
title: "ClientGraphics - text on each planar face"
date: "2012-03-20 22:31:30"
author: "Wayne Brill"
categories: []
original_url: "https://modthemachine.typepad.com/my_weblog/2012/03/clientgraphics-text-on-each-planar-face.html "
typepad_basename: "clientgraphics-text-on-each-planar-face"
typepad_status: "Publish"
---

<p>ClientGraphics allow you to provide visual cues to the user and there are many examples in the API help that show how to create ClientGraphics. This VB.NET example is interesting because it shows you how to put text on each planar face in a part. </p>  <p>To create ClientGraphics text, you use TextGraphics and you can control the orientation of the TextGraphics in 3D space. The TextGraphics itself is placed on the x-y plane and along the x-axis but you can reposition it by transforming the graphics node that the TextGraphics is owned by. </p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401676409a086970b-pi"><img style="background-image: none; border-right-width: 0px; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_510414.jpg" width="244" height="226" /></a></p>  <p>Below is code from <a href="http://modthemachine.typepad.com/ClientGraphics_Text_Example.zip">this example</a> that creates the ClientGraphics. In the VB.NET project you will also find the functions named FaceNormal and FaceXDir that are called from this Sub. See the comments in the code for more detail on how this example does the work. Notice that the second time you run the code it removes the ClientGraphics. </p>  <div style="font-family: consolas; background: #eeeeee; color: black; font-size: 10pt">   <p style="margin: 0px"><span style="color: blue">Public</span> <span style="color: blue">Sub</span> CreateTextOnEveryPlanarFace()</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> partDoc <span style="color: blue">As</span> <span style="color: #2b91af">PartDocument</span></p>    <p style="margin: 0px">&#160;&#160;&#160; partDoc = _InvApplication.ActiveDocument</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> compDef <span style="color: blue">As</span> <span style="color: #2b91af">PartComponentDefinition</span></p>    <p style="margin: 0px">&#160;&#160;&#160; compDef = partDoc.ComponentDefinition</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' Check to see if client graphics already exist.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> clientGraphics <span style="color: blue">As</span> <span style="color: #2b91af">ClientGraphics</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clientGraphics = compDef. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClientGraphicsCollection.Item(<span style="color: #a31515">&quot;FaceLabel&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' They do exist so just delete them and exit.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">clientGraphics</span>.Delete()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; _InvApplication.ActiveView.Update()</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Exit Sub</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Catch</span> ex <span style="color: blue">As</span> <span style="color: #2b91af">Exception</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' They don't exist so create them</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; clientGraphics = compDef. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ClientGraphicsCollection.Add(<span style="color: #a31515">&quot;FaceLabel&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">Try</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' Iterate over all of the faces in the part.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> count <span style="color: blue">As</span> <span style="color: blue">Integer</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Dim</span> oFace <span style="color: blue">As</span> <span style="color: #2b91af">Face</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">For</span> <span style="color: blue">Each</span> oFace <span style="color: blue">In</span> _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; compDef.SurfaceBodies.Item(1).Faces</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Check if the current face is a plane.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">If</span> oFace.SurfaceType = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">SurfaceTypeEnum</span>.kPlaneSurface <span style="color: blue">Then</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Get a point on the face. This </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' function is good because you're </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' guaranteed to get a(Point) on the </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' face, where-as if you got the </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' center of the face there could be </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' a hole there so the point would </span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' be in space.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> facePoint <span style="color: blue">As</span> <span style="color: #2b91af">Point</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; facePoint = oFace.PointOnFace</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Get the normal of the face.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> normal <span style="color: blue">As</span> <span style="color: #2b91af">UnitVector</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; normal = FaceNormal(oFace, facePoint)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Get the X direction of the face</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' (normal along the u).</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> xDir <span style="color: blue">As</span> <span style="color: #2b91af">UnitVector</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; xDir = FaceXDir(oFace, facePoint)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Calculate the Y direction by crossing</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' the normal with the x.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> yDir <span style="color: blue">As</span> <span style="color: #2b91af">UnitVector</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; yDir = normal.CrossProduct(xDir)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Create a transform to position the text</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' on the face.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> transform <span style="color: blue">As</span> <span style="color: #2b91af">Matrix</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; transform = _InvApplication. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TransientGeometry.CreateMatrix</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> transform. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; SetCoordinateSystem(facePoint, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; xDir.AsVector, yDir.AsVector, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; normal.AsVector)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Create a graphics node.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> oNode <span style="color: blue">As</span> <span style="color: #2b91af">GraphicsNode</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; count = count + 1</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNode = <span style="color: #2b91af">clientGraphics</span>.AddNode(count)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Create text at the model origin.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> text <span style="color: blue">As</span> <span style="color: #2b91af">TextGraphics</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text = oNode.AddScalableTextGraphics</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Dim</span> origin <span style="color: blue">As</span> <span style="color: #2b91af">Point</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; origin = _InvApplication. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; TransientGeometry.CreatePoint(0, 0, 0)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> text.SetTransformBehavior(origin, _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">DisplayTransformBehaviorEnum</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kNoTransformBehaviors, 1)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.Text = <span style="color: #a31515">&quot;Face &quot;</span> &amp; count</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.DepthPriority = 1</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.FontSize = 0.1</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.Font = <span style="color: #a31515">&quot;Arial&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.HorizontalAlignment = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">HorizontalTextAlignmentEnum</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kAlignTextCenter</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.VerticalAlignment = _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">VerticalTextAlignmentEnum</span>. _</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; kAlignTextMiddle</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; text.Anchor = origin</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">Call</span> text.PutTextColor(255, 255, 0)</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' Transform the graphics node so the text</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">' will lie on the face.</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; oNode.Transformation = transform</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">End</span> <span style="color: blue">If</span></p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">Next</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: green">' Update the view to see the results.</span></p>    <p style="margin: 0px">&#160;&#160;&#160; _InvApplication.ActiveView.Update()</p>    <p style="margin: 0px"><span style="color: blue">End</span> <span style="color: blue">Sub</span></p> </div>  <p>Wayne Brill</p>
