---
layout: "post"
title: "Get strokes for 2d and 3d transient wireframe geometry"
date: "2012-05-31 19:02:27"
author: "Wayne Brill"
categories:
  - "Parts"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/05/get-strokes-for-2d-and-3d-transient-wireframe-geometry.html "
typepad_basename: "get-strokes-for-2d-and-3d-transient-wireframe-geometry"
typepad_status: "Publish"
---

<p>An enhancement in the Inventor 2013 API allows you to get strokes for 2d and 3d transient geometry. One reason why you may want to do this is to approximate sketch geometry. The new method is GetStrokes of the CurveEvaluator and Curve2dEvaluator objects. To get the transient geometry (CurveEvaluator) from the sketch entity, use the Geometry.Evaluator property.</p>
<p><strong>New 2013 method used to get strokes</strong></p>
<ul>
<li>CurveEvaluator.GetStrokes </li>
<li>Curve2dEvaluator.GetStrokes </li>
</ul>
<p><strong>VBA Example: </strong></p>
<p>Please keep in mind that we only recommend using VBA for prototyping and learning the API but do not recommend using VBA in production.</p>
<p>To try out this example create a 3D Sketch. I used a helical curve as you can see in the screenshot. When you run the Approximate3DSketchGeometry procedure it prompts you to select a 3d entity and then displays an InputBox asking for the chord height tolerance. This value will be used as the maximum of deviation. (How far off can these line segments be to the curve). I used .25. This will be centimeters in database units.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016766f66780970b-pi"><img alt="image" border="0" height="356" src="/assets/image_404856.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="456" /></a></p>
<p>A MsgBox is used to ask if you want to use existing client graphics, create new client graphics or just cancel. The lines that you see that approximate the curve, are drawn using client graphics. Here is the result after running the procedure:</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168ebf7e6a4970c-pi"><img alt="image" border="0" height="277" src="/assets/image_680266.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="466" /></a></p>
<p><strong>VBA Code:</strong></p>
<p><span style="background-color: #ffffff;">&#39;<span style="color: #0000ff;"> Draws client graphics that is an approximation <br />&#39; of the selected curve. <br />&#39; To use this have a part open that contains <br />&#39; a 3D skech that contains curves. <br /></span></span>Public Sub Approximate3DSketchGeometry() <br />&#0160;&#0160;&#0160; Dim partDoc As PartDocument <br />&#0160;&#0160;&#0160; Set partDoc = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveDocument <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160; <span style="color: #0000ff;">&#39; Have the user select a sketch entity. <br /></span>&#0160;&#0160;&#0160; Dim selectObj As SketchEntity3D <br />&#0160;&#0160;&#0160; Set selectObj = ThisApplication. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; CommandManager.Pick _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (kSketch3DCurveFilter, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &quot;Select 3D sketch entity&quot;) <br />&#0160;&#0160;&#0160; If selectObj Is Nothing Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; On Error Resume Next <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call partDoc.ComponentDefinition _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; .ClientGraphicsCollection.Item _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (&quot;Test&quot;).Delete <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Call partDoc.GraphicsDataSetsCollection _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; .Item(&quot;Test&quot;).Delete <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveView.Update <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160; <span style="color: #0000ff;">&#39; Get the tolerance to approximate with. <br /></span>&#0160;&#0160;&#0160; Dim tolerance As Double <br />&#0160;&#0160;&#0160; tolerance = Val(InputBox _ <br />&#0160;&#0160;&#0160;&#0160; (&quot;Enter the chord height tolerance:&quot;, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; &quot;Tolerance&quot;, &quot;0.25&quot;)) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160; <span style="color: #0000ff;">&#39; Get the evaluator from the curve. <br /></span>&#0160;&#0160;&#0160; Dim eval As CurveEvaluator <br />&#0160;&#0160;&#0160; Set eval = selectObj.Geometry.Evaluator <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160; <span style="color: #0000ff;">&#39; Get the parameter extents. <br /></span>&#0160;&#0160;&#0160; Dim startParam As Double <br />&#0160;&#0160;&#0160; Dim endParam As Double <br />&#0160;&#0160;&#0160; Call eval.GetParamExtents _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (startParam, endParam) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim vertexCount As Long <br />&#0160;&#0160;&#0160; Dim vertexCoords() As Double <br />&#0160;&#0160;&#0160; Call eval.GetStrokes(startParam, endParam, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; tolerance, vertexCount, vertexCoords) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; &#39; <span style="color: #0000ff;">Create a client graphics object. <br />&#0160;&#0160;&#0160; &#39; If one already exists, give the user <br />&#0160;&#0160;&#0160; &#39; the option of re-using it, or creating <br />&#0160;&#0160;&#0160; &#39; a new one. <br /></span>&#0160;&#0160;&#0160; Dim graphics As ClientGraphics <br />&#0160;&#0160;&#0160; Dim graphicsData As GraphicsDataSets <br />&#0160;&#0160;&#0160; On Error Resume Next <br />&#0160;&#0160;&#0160; Set graphics = partDoc.ComponentDefinition. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ClientGraphicsCollection.Item(&quot;Test&quot;) <br />&#0160;&#0160;&#0160; On Error GoTo 0 <br />&#0160;&#0160;&#0160; If graphics Is Nothing Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set graphics = partDoc. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160; ComponentDefinition.ClientGraphicsCollection _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; .Add(&quot;Test&quot;) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set graphicsData = partDoc. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GraphicsDataSetsCollection.Add(&quot;Test&quot;) <br />&#0160;&#0160;&#0160; Else <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Dim answer As VbMsgBoxResult <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; answer = MsgBox _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (&quot;Yes = existing. No = new Cancel. = quit.&quot;, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; vbYesNoCancel + vbQuestion) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If answer = vbNo Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; On Error Resume Next <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; graphics.Delete <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; partDoc.GraphicsDataSetsCollection _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; .Item(&quot;Test&quot;).Delete <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; On Error GoTo 0 <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set graphics = partDoc.ComponentDefinition _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; .ClientGraphicsCollection.Add(&quot;Test&quot;) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set graphicsData = partDoc. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GraphicsDataSetsCollection.Add(&quot;Test&quot;) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ElseIf answer = vbYes Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Set graphicsData = partDoc. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; GraphicsDataSetsCollection.Item(&quot;Test&quot;) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ElseIf answer = vbCancel Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; If Not graphics Is Nothing Then <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; graphics.Delete <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; partDoc.GraphicsDataSetsCollection _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; .Item(&quot;Test&quot;).Delete <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ThisApplication.ActiveView.Update <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Exit Sub <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; End If <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; Dim coordSet As GraphicsCoordinateSet <br />&#0160;&#0160;&#0160; Set coordSet = graphicsData.CreateCoordinateSet(1) <br />&#0160;&#0160;&#0160; Call coordSet.PutCoordinates(vertexCoords)</p>
<p>&#0160;&#0160; <span style="color: #0000ff;">&#39; Create a graphics node. <br /></span>&#0160;&#0160;&#0160; Dim node As GraphicsNode <br />&#0160;&#0160;&#0160; Set node = graphics.AddNode(1) <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; <span style="color: #0000ff;">&#39; Create a line strip using the calculated coordinates.</span> <br />&#0160;&#0160;&#0160; Dim lineStrip As LineStripGraphics <br />&#0160;&#0160;&#0160; Set lineStrip = node.AddLineStripGraphics <br />&#0160;&#0160;&#0160; lineStrip.CoordinateSet = coordSet <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; ThisApplication.ActiveView.Update <br />End Sub</p>
<p>-Wayne</p>
