---
layout: "post"
title: "Discussion on Client Graphics &ndash; Segment 3"
date: "2012-08-14 21:34:12"
author: "Wayne Brill"
categories:
  - "Assemblies"
  - "Inventor"
  - "Parts"
  - "Wayne"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/08/discussion-on-client-graphics-segment-3.html "
typepad_basename: "discussion-on-client-graphics-segment-3"
typepad_status: "Publish"
---

<p>Here is the third of four articles on Client Graphics. This was originally in a technical paper written by Autodesk Developer Network engineer Xiaodong Liang.</p>
<p>Note: Segment 2 is <a href="http://modthemachine.typepad.com/my_weblog/2012/08/discussion-on-client-graphics-segment-2.html" target="_blank">here</a>.</p>
<p>This zip file has a VB.NET project with the examples discussed in this section.</p>
<p><strong><span class="asset  asset-generic at-xid-6a00e553fcbfc68834016769555aff970b"><a href="http://modthemachine.typepad.com/files/clientgraphics_segment_3.zip">Download ClientGraphics_Segment_3</a></span></strong></p>
<p><strong>Start of segment 3 </strong></p>
<p><strong>Using Index Sets <br /></strong>The Index Set provides a flexible way to arrange the coordinate set, color set and normal set (for triangles). For example, with the same coordinate data, the figure below, on the left, creates the line graphics from 1-2-3-4 where all lines have the same color, while the figure on the right creates the line from 1-3-2-4 and each line has a different color defined using an index set. <br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401774421914b970d-pi"><img alt="image" border="0" height="209" src="/assets/image_442586.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="481" /></a></p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Line, With Coordinate Index Set and Color Set&gt; <br /></span>&#0160;&#0160;&#0160;&#0160; Dim oPointCoords(11) As Double &#39;create 4 points <br />&#0160;&#0160;&#0160; oPointCoords(0) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(1) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(2) = 0 <br />&#0160;&#0160;&#0160; oPointCoords(3) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(4) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(5) = 0 <br />&#0160;&#0160;&#0160; oPointCoords(6) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(7) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(8) = 0 <br />&#0160;&#0160;&#0160; oPointCoords(9) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(10) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(11) = 0 <br />&#0160;&#0160;&#0160; Call oCoordSet.PutCoordinates(oPointCoords) <br />&#0160; <br />&#0160; <span style="color: #0000ff;">&#0160; &#39;Line strip: totally, 3 lines <br /></span>&#0160;&#0160;&#0160; Dim oGraphic As LineGraphics <br />&#0160;&#0160;&#0160; Set oGraphic = oGraphicsNode.AddLineGraphics&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; oGraphic.LineWeight = 5 <br /><br />&#0160; <span style="color: #0000ff;">&#0160; ‘Create Coordinate Index Set <br /></span>&#0160;&#0160;&#0160; Dim oCoordinateIndex As GraphicsIndexSet <br />&#0160;&#0160;&#0160; Set oCoordinateIndex = oDataSets.CreateIndexSet(oDataSets.count + 1) <br />&#0160;&#0160;&#0160; oCoordinateIndex.Add 1, 1&#0160; &#39;from point 1 <br />&#0160;&#0160;&#0160; oCoordinateIndex.Add 2, 3&#0160; &#39;connect to point 3 <br />&#0160;&#0160;&#0160; oCoordinateIndex.Add 3, 3&#0160; &#39;from point 3 <br />&#0160;&#0160;&#0160; oCoordinateIndex.Add 4, 2&#0160; &#39;connect to point 2 <br />&#0160;&#0160;&#0160; oCoordinateIndex.Add 5, 2&#0160; &#39;from point 2 <br />&#0160;&#0160;&#0160; oCoordinateIndex.Add 6, 4&#0160; &#39;connect to point 4&#0160;&#0160; <br />&#0160;&#0160;&#0160; <br />&#0160; <span style="color: #0000ff;">&#0160; &#39;Create the color set: two colors. <br /></span>&#0160;&#0160;&#0160; Dim oColorSet As GraphicsColorSet <br />&#0160;&#0160;&#0160; Set oColorSet = oDataSets.CreateColorSet(oDataSets.count + 1) <br />&#0160;&#0160;&#0160; Call oColorSet.Add(1, 255, 0, 0) <br />&#0160;&#0160;&#0160; Call oColorSet.Add(2, 0, 255, 0) <br />&#0160;&#0160;&#0160; <br /><span style="color: #0000ff;">&#0160; &#39; Create the index set for color <br /></span>&#0160;&#0160;&#0160; Dim oColorIndex As GraphicsIndexSet <br />&#0160;&#0160;&#0160; Set oColorIndex = oDataSets.CreateIndexSet(oDataSets.count + 1) <br />&#0160;&#0160;&#0160; oColorIndex.Add 1, 2&#0160; &#39;line 1 uses color 2 <br />&#0160;&#0160;&#0160; oColorIndex.Add 2, 1&#0160; &#39;line 2 uses color 1 <br />&#0160;&#0160;&#0160; oColorIndex.Add 3, 2&#0160; &#39;line 3 uses color 2&#0160; <br />&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; oGraphic.CoordinateSet = oCoordSet <br />&#0160;&#0160;&#0160; oGraphic.CoordinateIndexSet = oCoordinateIndex</p>
<p><strong>Using ‘Strip’ graphics <br /></strong>Strip Graphics are used to group the coordinates associated with a series of connected graphics objects and are only available with LineStrip, TriangleStrip or TriangleFan. You can specify the strip length. e.g. in the code below, points 1,2,3 are defined as one triangle strip, while points 4,5,6,7 are defined as another strip. Each strip is independent of the other strips. You can also specify the color for each.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc6883401676946853a970b-pi"><img alt="image" border="0" height="181" src="/assets/image_60773.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="491" /></a></p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Triangle Strip, Set Strip&gt; <br /></span>Dim oPointCoords(20) As Double&#0160;&#0160;&#0160; ‘create 7 points, <br />oPointCoords(0) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(1) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(2) = 0 <br />oPointCoords(3) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(4) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(5) = 0 <br />oPointCoords(6) = 2:&#0160;&#0160;&#0160;&#0160; oPointCoords(7) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(8) = 0 <br />oPointCoords(9) = 3:&#0160;&#0160;&#0160;&#0160; oPointCoords(10) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(11) = 0 <br />oPointCoords(12) = 4:&#0160;&#0160;&#0160;&#0160; oPointCoords(13) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(14) = 0 <br />oPointCoords(15) = 5:&#0160;&#0160;&#0160;&#0160; oPointCoords(16) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(17) = 0 <br />oPointCoords(15) = 5:&#0160;&#0160;&#0160;&#0160; oPointCoords(16) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(17) = 0 <br />oPointCoords(18) = 6:&#0160;&#0160;&#0160;&#0160; oPointCoords(19) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(20) = 0 <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />Call oCoordSet.PutCoordinates(oPointCoords) <br />&#0160; <br /><span style="color: #0000ff;">‘or Triangle Strip: totally 5 triangles <br /></span>Dim oGraphic As TriangleStripGraphics <br />Set oGraphic = oGraphicsNode.AddTriangleStripGraphics <br />&#0160; <br />Dim oStrip(1) As Long <br />oStrip(0) = 3&#0160; ‘ point 1,2,3&#0160;&#0160; for strip 1 <br />oStrip(1) = 4&#0160; ‘ point 4,5,6,7 for strip 2 <br />oGraphic.PutStripLengths oStrip <br /><br /><span style="color: #0000ff;">&#39;Create the color set: two colors. <br /></span>Dim oColorIndex As GraphicsIndexSet <br />Set oColorIndex = oDataSets.CreateIndexSet(oDataSets.count + 1) <br />oColorIndex.Add 1, 1 <br />oColorIndex.Add 2, 2 <br />oColorIndex.Add 3, 1 <br />oColorIndex.Add 4, 2 <br />oColorIndex.Add 5, 1&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160; <br /><span style="color: #0000ff;">&#0160; &#39; Create the index set for color <br /></span>Dim oColorSet As GraphicsColorSet <br />Set oColorSet = oDataSets.CreateColorSet(oDataSets.count + 1) <br />Call oColorSet.Add(1, 255, 0, 0) <br />Call oColorSet.Add(2, 0, 255, 0) <br /><br />oGraphic.CoordinateSet = oCoordSet <br />oGraphic.ColorIndexSet = oColorIndex <br />oGraphic.ColorSet = oColorSet <br />oGraphic.ColorBinding = kPerStripColors</p>
<p><strong>Using Model Native Data <br /></strong>Most scenarios where Client Graphics are required are based on the models native geometry. It is quite easy to get the data using Inventor API objects. e.g. SurfaceBody, Face, Edge, Vertex in Part or Assembly Documents, and DrawingCurve in drawing documents. The code below creates and transforms a surface using an existing SurfaceBody from the model.</p>
<p>It is also possible to obtain a coordinate data set from the existing SurfaceBody, Edge or Face objects using the CalculateStrokes method. You determine the tolerance (the number of points you need) by first calling GetExistingStrokeTolerances. You may need to do this multiple times in order to assess the average tolerance for the model. Similarly, obtain triangular facets from a SurfaceBody or Face using CalculateFacets. <br /><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340176173b244b970c-pi"><img alt="image" border="0" height="302" src="/assets/image_377761.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="475" /></a></p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Using model native data&gt; <br /></span>Dim oPartDef As PartComponentDefinition <br />Set oPartDef = ThisApplication.ActiveDocument.ComponentDefinition&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />Dim oTransientBRep As TransientBRep <br />Set oTransientBRep = ThisApplication.TransientBRep <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;<span style="color: #0000ff;">‘by Transient Brep class to copy the surface body <br /></span>&#0160; Dim oBody As SurfaceBody <br />&#0160; Set oBody = oTransientBRep.Copy(oCompDef.SurfaceBodies.Item(1)) <br />&#0160;&#0160;&#0160;&#0160; <br />&#0160; <span style="color: #0000ff;">&#39; Create client graphics based on the transient body <br /></span>&#0160; Dim oSurfaceGraphics As SurfaceGraphics <br />&#0160; Set oSurfaceGraphics = oSurfacesNode.AddSurfaceGraphics(oBody) <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br /><span style="color: #0000ff;">‘move the graphics to a new location <br /></span>&#0160; Dim oMatrix As Matrix <br />&#0160; Set oMatrix = ThisApplication.TransientGeometry.CreateMatrix <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160; oMatrix.SetTranslation ThisApplication.TransientGeometry.CreateVector(0, 0, 100)</p>
<p><strong>Basic Properties <br /></strong>Graphics has some properties to control the basic behavior. <br /><strong><em>Render Style <br /></em></strong>By default, the linetype, lineweight and color will use the settings on RenderStyle until they are overridden by LineType, LineWeight, Color (for Curve and Surface objects), and ColorSet (for Line, Triangle and TriangleFan objects). <br /><strong><em>Point Style <br /></em></strong>Specific to Point objects only, and controls the point style. <br /><strong><em>Visibility <br /></em></strong>Controls whether or not the graphics are visible. <br /><strong><em>Selectable <br /></em></strong>Specifies whether client graphics can be selected when the Select command is running. <br /><strong><em>Burn Through <br /></em></strong>This specifies whether or not graphics are always visible even if they are blocked by other objects. <br /><strong><em>Transformation <br /></em></strong>This property is used to transform a graphics node. <br /><strong><em>Transform Behavior <br /></em></strong>Two special transform behaviors: front facing and pixel scaling. <br />•&#0160;&#0160;&#0160; Front Facing <br />Client graphics with this property do not rotate as the view is rotated but maintain the same orientation on the screen. They are positioned at a specified location within model space and their position on the screen will change as the view is zoomed in and out and scrolled, but their orientation will not change. <br />•&#0160;&#0160;&#0160; Pixel Scaling <br />Here client graphics maintain the same size and position relative to the screen. As the user zooms in and out in the graphic window, these objects remain static. <br />Any graphics object can also have no transform behavior (which means it&#39;s size, position, and orientation are maintained relative to model space), front facing, pixel scaling, or front facing &amp; pixel scaling. By default an object has no transform behavior, with the exception of text. Text always has front facing behavior regardless of the behavior type set through this method. <br /><strong><em>Anchor Behavior <br /></em></strong>This will anchor the primitive in view space so that the graphics will display in one fixed position, no matter how the view changes.</p>
<p>End of Segment 3</p>
<p>- Wayne</p>
