---
layout: "post"
title: "Transient wire body &ndash; Create ruled surface"
date: "2012-05-23 22:24:22"
author: "Wayne Brill"
categories: []
original_url: "https://modthemachine.typepad.com/my_weblog/2012/05/transient-wire-body-create-ruled-surface.html "
typepad_basename: "transient-wire-body-create-ruled-surface"
typepad_status: "Publish"
---

<p>Transient B-Rep allows you to define B-Rep data from scratch and one of the enhancements to the Inventor 2013 API allows you to define a new wire body. In the previous release you could only build surfaces and solids. One reason to create a wire body is for input to other modeling operations.</p>
<p><span style="color: #232323;"><strong>New 2013 object, properties and method used to create a wire body ruled surface:</strong></span></p>
<ul>
<li>WireDefinition Object </li>
<li>FaceShellDefinition.WireDefinitions Property </li>
<li>WireDefinition.WireEdgeDefinitions Property </li>
<li>TransientBRep.CreateRuledSurface Method </li>
</ul>
<p><strong>VBA Example: </strong></p>
<p>Please keep in mind that we only recommend using VBA for prototyping and learning the API but do not recommend using VBA in production).</p>
<p>This example shows how to use this new functionality to create a ruled surface. After running this procedure a NonParametricBaseFeature will be added to the part file.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016766ba11ef970b-pi"><img alt="image" border="0" height="298" src="/assets/image_79932.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="578" /></a></p>
<p><strong>VBA Code:</strong></p>
<p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">&#39; Demonstrate creating a transient ruled surface.      <br />&#39; This sample uses all straight line segments       <br />&#39; for each of the sections.       <br />&#39; A part document must be open.       <br /></span>Public Sub RuledSurf()     <br /> <span style="color: #0000ff;">&#39; Get the transient B-Rep and Geometry objects.</span> <br /> Dim tBRep As TransientBRep     <br /> Set tBRep = ThisApplication.TransientBRep     <br /> <br /> Dim tg As TransientGeometry     <br /> Set tg = ThisApplication.TransientGeometry     <br /> <br /> <span style="color: #0000ff;">&#39; Create a new surface body definition.</span> <br /> Dim bodyDef As SurfaceBodyDefinition     <br /> Set bodyDef = tBRep.CreateSurfaceBodyDefinition     <br /> <br /> &#39;<span style="color: #0000ff;"> Add a lump, shell, and wire.</span> <br /> Dim lumpDef As LumpDefinition     <br /> Set lumpDef = bodyDef.LumpDefinitions.Add     <br /> <br /> Dim shellDef As FaceShellDefinition     <br /> Set shellDef = lumpDef.FaceShellDefinitions.Add     <br /> <br /> Dim wireDef As WireDefinition     <br /> Set wireDef = shellDef.WireDefinitions.Add     <br /> <br /> <span style="color: #0000ff;">&#39; Create coordinate points and use those      <br /> &#39; to create vertex definitions.       <br /></span> Dim pnts(2) As Point     <br /> Set pnts(0) = tg.CreatePoint(0, 0, 0)     <br /> Set pnts(1) = tg.CreatePoint(10, 3, 0)     <br /> Set pnts(2) = tg.CreatePoint(20, 0, 0)     <br /> Dim vertexDefs(2) As VertexDefinition     <br /> Set vertexDefs(0) = _     <br /> bodyDef.VertexDefinitions.Add(pnts(0))     <br /> Set vertexDefs(1) = _     <br /> bodyDef.VertexDefinitions.Add(pnts(1))     <br /> Set vertexDefs(2) = _     <br /> bodyDef.VertexDefinitions.Add(pnts(2))     <br /> <br /> <span style="color: #0000ff;">&#39; Create two wire edges, passing through the      <br /> &#39; three vertices.       <br /></span> Call wireDef.WireEdgeDefinitions.Add _     <br /> (vertexDefs(0), vertexDefs(1), _     <br /> tg.CreateLineSegment(pnts(0), pnts(1)))     <br /> Call wireDef.WireEdgeDefinitions.Add _     <br /> (vertexDefs(1), vertexDefs(2), _     <br /> tg.CreateLineSegment(pnts(1), pnts(2)))     <br /> <br /> <span style="color: #0000ff;">&#39; Create a second wire definition.      <br /></span> Dim wireDef2 As WireDefinition     <br /> Set wireDef2 = shellDef.WireDefinitions.Add     <br /> <br /> <span style="color: #0000ff;">&#39; Create coordinate points and use those to      <br /> &#39; create vertex definitions.       <br /></span> Set pnts(0) = tg.CreatePoint(-5, 0, 10)     <br /> Set pnts(1) = tg.CreatePoint(10, 6, 10)     <br /> Set pnts(2) = tg.CreatePoint(25, 0, 10)     <br /> <br /> Set vertexDefs(0) = _     <br /> bodyDef.VertexDefinitions.Add(pnts(0))     <br /> Set vertexDefs(1) = _     <br /> bodyDef.VertexDefinitions.Add(pnts(1))     <br /> Set vertexDefs(2) = _     <br /> bodyDef.VertexDefinitions.Add(pnts(2))     <br /> <br /> <span style="color: #0000ff;">&#39; Create two edges, passing through the      <br /> &#39; three vertices.       <br /></span> Call wireDef2.WireEdgeDefinitions.Add _     <br /> (vertexDefs(0), vertexDefs(1), _     <br /> tg.CreateLineSegment(pnts(0), pnts(1)))     <br /> Call wireDef2.WireEdgeDefinitions.Add _     <br /> (vertexDefs(1), vertexDefs(2), _     <br /> tg.CreateLineSegment(pnts(1), pnts(2)))     <br /> <br /> <span style="color: #0000ff;">&#39; Create a body using the defined wires.      <br /></span> Dim errors As NameValueMap     <br /> Set errors = ThisApplication.TransientObjects. _     <br /> CreateNameValueMap     <br /> Dim body1 As SurfaceBody     <br /> Set body1 = bodyDef. _     <br /> CreateTransientSurfaceBody(errors)     <br /> <br /> <span style="color: #0000ff;">&#39; Create a ruled surface between the two      <br /> &#39; wire bodies.</span> <br /> Dim ruled As SurfaceBody     <br /> Set ruled = tBRep.CreateRuledSurface _     <br /> (body1.Wires.Item(1), body1.Wires.Item(2))     <br /> <br /> <span style="color: #0000ff;">&#39; Get the part component definition of the      <br /> &#39; active document.       <br /></span> Dim partDoc As PartDocument     <br /> Set partDoc = ThisApplication.ActiveDocument     <br /> Dim partDef As PartComponentDefinition     <br /> Set partDef = partDoc.ComponentDefinition     <br /> <br /> <span style="color: #0000ff;">&#39; Create a base body feature of the      <br /> &#39; transient body.</span> <br /> Dim baseBody As NonParametricBaseFeature     <br /> Set baseBody = _     <br /> partDef.Features. _     <br /> NonParametricBaseFeatures.Add(ruled)     <br /> <br /> <span style="color: #0000ff;">&#39; Change the result work surface so      <br /> &#39; it&#39;s not translucent.       <br /></span> baseBody.SurfaceBodies.Item(1). _     <br /> Parent.Translucent = False     <br /> <br /> ThisApplication.ActiveView.Fit     <br />End Sub</p>
<p>-Wayne</p>
