---
layout: "post"
title: "Drawing in a Sketch"
date: "2012-04-27 20:57:08"
author: "Adam Nagy"
categories:
  - "Brian"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/04/drawing-in-a-sketch.html "
typepad_basename: "drawing-in-a-sketch"
typepad_status: "Publish"
---

<p>This is a continuation of the <a href="http://modthemachine.typepad.com/my_weblog/getting-started-tutorial/">getting started tutorial</a> that’s discussing the creation of a new command to draw a slot.&#160; In this installment I discuss drawing geometry in a sketch.</p>  <p>When creating sketch geometry using the API, there are a couple of concepts that are important to understand that aren’t very obvious when you create sketches interactively.&#160; Let’s look at what you really have when you draw two lines in a sketch.&#160; You can see from the picture below it just looks like two lines and nothing else.</p>  <p>&#160;<a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168ead0b8e7970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="Lines" border="0" alt="Lines" src="/assets/image_204866.jpg" width="339" height="248" /></a></p>  <p>If you know what to look for, you’ll also notice something else.&#160; If you move the mouse over the end of the lines, a point is displayed, as shown below.&#160; At first you might think this is just a handle being displayed to indicate that you can drag the end of the line.&#160; It’s not a handle, it’s a real sketch point that’s being displayed.&#160; </p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016304db28eb970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="LinesWithPoint" border="0" alt="LinesWithPoint" src="/assets/image_124079.jpg" width="347" height="272" /></a></p>  <p>In fact, to better see these are real points you can select a point and using the context menu, change the display style of the point to a center point.&#160; With this display style it remains visible all the time and not just when the cursor is over it.&#160; The picture below shows all three of the points being displayed with a center point style.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016765ce49e8970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="LineWithCenterPoint" border="0" alt="LineWithCenterPoint" src="/assets/image_110921.jpg" width="346" height="273" /></a></p>  <p>The thing to learn from this is that all sketch geometry is <u>always</u> associated to&#160; sketch points.&#160; Sketch geometry doesn’t exist on its own.&#160; The position of sketch geometry is controlled by the position of the points.&#160; It’s like the geometry is fastened to the points and if the points move the geometry attached to them also moves.&#160; </p>  <p>Another very important concept is that the two lines are connected by the fact that they share the same point.&#160; Both lines are attached to the same point.&#160; That’s how Inventor determines connected curves in a profile.&#160; We’ll see an example of this later in this post.</p>  <p>Below is a picture of the two lines after placing a fillet.&#160; The geometry consists of two lines and an arc.&#160; The position of each of the lines is still defined by two sketch points and the arc shares the sketch points where it connects to the lines.&#160; In addition, the arc has an additional sketch point that defines its center.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168ead0b90b970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; border-top-width: 0px; border-bottom-width: 0px; margin-left: auto; border-left-width: 0px; margin-right: auto; padding-top: 0px" title="LinesWithFillet" border="0" alt="LinesWithFillet" src="/assets/image_385098.jpg" width="324" height="230" /></a></p>  <p>When you interactively draw a sketch, Inventor automatically creates these points behind the scenes.&#160; It also automatically deletes them when the associated geometry is deleted.&#160; When using the API it’s possible to have it automatically create these points too, but without understanding these concepts of how geometry is connected to points and each other by sharing points it’s easy to get results you weren’t expecting.&#160; When interactively drawing a sketch, it’s natural to get the correct result because Inventor infers connections based on where you click the mouse.&#160; When using the API, none of this inference can take place because you’re not moving the mouse over the geometry.</p>  <p>The code below creates a sketch line on an existing sketch.&#160; You can paste this into the bottom of the sub from the previous post in this series.&#160; </p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt"><font color="#0000ff"><strong><font color="#0000ff">' Get a reference to the TransientGeometry object</font></strong>. </font>    <br />Dim tg As Inventor.TransientGeometry = invApp.TransientGeometry     <br />    <br /><strong><font color="#0000ff">' Get a reference to the SketchLines collection.        <br /></font></strong>Dim lines As Inventor.SketchLines = sketch.SketchLines     <br />    <br /><font color="#0000ff"><strong>' Draw a line between (0,0) and (4,0).</strong></font>     <br />Dim line1 As Inventor.SketchLine     <br />line1 = lines.AddByTwoPoints(tg.CreatePoint2d(0, 0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(4, 0))</p>  <p>The first thing this does is get a reference to the <em>TransientGeometry</em> object. This is a utility object in the API that lets you create various types of geometry.&#160; However, the geometry created is not ever displayed or saved by Inventor, which is why they are called <em>transient</em>.&#160; These objects are simply the mathematical definition of the geometry and are not visible entities.&#160; I’m using it in this case to create two coordinate points to define the end points of the line.&#160; The CreatePoint2d method creates a transient 2d point.&#160; The Point2d object is a simple API object that wraps the x-y coordinates of a point in 2d space.&#160; In Inventor’s API, instead of passing two values to define x-y coordinates a Point2d object is used instead.&#160; There’s also a Point object which wraps x-y-z coordinates for a 3d point.&#160; When working with a sketch you want to make sure you’re using the CreatePoint<u>2d</u> method and not the CreatePoint method.&#160; It’s a common mistake.</p>  <p>The next thing the program above does is get the SketchLines collection.&#160; In a <a href="http://modthemachine.typepad.com/my_weblog/2012/04/objects-in-the-api.html">previous post</a> I briefly discussed collection objects.&#160; The SketchLines object lets you access all of the lines on the sketch and it supports add methods to let you create new lines.&#160; This examples uses the AddByTwoPoints method to create a new sketch line.</p>  <p>The final section of the code above creates the new line.&#160; A variable is declared with the type of SketchLine and the newly created line is assigned to the variable.&#160; The AddByTwoPoints method takes to points as input.&#160; These can either be coordinate points (defined by a Point2d object as in the example above) or they can be existing SketchPoint objects, which you’ll see demonstrated below.</p>  <p>Another thing that’s important to understand are the units that Inventor uses. Internally, Inventor is consistent in the units it uses.&#160; Lengths are <u>always</u> defined in centimeters and angles are <u>always</u> defined in radians.&#160; It doesn’t matter what units the user has specified as their document units.&#160; The API is consistent with the Inventor internal units.&#160; When you create or query geometry, any length or coordinate values will always be in centimeters and any angles will always be in radians.&#160; The example above creates a 4 centimeter long line starting from the origin and going in the sketch X direction.&#160; We’ll see in a later post how to deal with user defined units.</p>  <p>Below is some code that creates a second and third line to create a triangle.</p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt"><font color="#0000ff"><strong>' Draw a line between (4,0) and (4,3).</strong></font>     <br />Dim line2 As Inventor.SketchLine     <br />line2 = lines.AddByTwoPoints(tg.CreatePoint2d(4, 0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(4, 3))     <br />    <br /><font color="#0000ff"><strong>' Draw a line between (4,3) and (0,0).</strong></font>     <br />Dim line3 As Inventor.SketchLine     <br />line3 = lines.AddByTwoPoints(tg.CreatePoint2d(4, 3), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(0, 0)) </p>  <p>The resulting geometry is shown below on the left.&#160; If I try to create an extrusion using this sketch I can’t select the triangle, but only the individual lines.&#160; That’s because each line has it’s own unique pair of sketch points for its end points, instead of sharing a single point between two lines.&#160; This becomes obvious if I drag any of the end points, the triangle pulls apart, as shown in the picture on the right.</p>  <p align="left"><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168ead0b919970c-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; float: left; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="LinesTriangle" border="0" alt="LinesTriangle" align="left" src="/assets/image_167674.jpg" width="231" height="182" /></a></p>  <p align="left"><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016304db290c970d-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="LinesBrokenTriangle" border="0" alt="LinesBrokenTriangle" src="/assets/image_694962.jpg" width="240" height="204" /></a></p>  <p>The code below is a variation of the previous code but creates a set of connected lines.&#160; The difference is that instead of defining new coordinates for the end of each line it uses the EndSketchPoint and StartSketchPoint properties of the SketchLine object to get the sketch points from the existing lines.</p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt"><font color="#0000ff"><strong>' Draw a line between (0,0) and (4,0).</strong></font>     <br />Dim line1 As Inventor.SketchLine     <br />line1 = lines.AddByTwoPoints(tg.CreatePoint2d(0, 0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(4, 0))     <br />    <br /><font color="#0000ff"><strong>' Draw a second line from the end of the previous line to (4,3).</strong></font>     <br />Dim line2 As Inventor.SketchLine     <br />line2 = lines.AddByTwoPoints(line1.EndSketchPoint, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tg.CreatePoint2d(4, 3))     <br />    <br /><font color="#0000ff"><strong>' Draw a line connecting the last point to the first point.        <br /></strong></font>Dim line3 As Inventor.SketchLine     <br />line3 = lines.AddByTwoPoints(line2.EndSketchPoint, _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; line1.StartSketchPoint)</p>  <p>&#160;</p>  <p>The approach to creating sketch geometry that I’ve had the best personal success with is to create the sketch points first and then use those as input when creating the various sketch entities.&#160; It’s easier for me to visualize the points I need if I map it out before hand and having the map helps to eliminate mistakes in my code.&#160; For example, below is an example of what I sketched up to help me visualize the points that will be needed to create the slot.&#160; Remember that arcs and circles require a sketch point at their center.&#160; I’ve numbered the points starting with zero.&#160; Those numbers will correspond to indices in an array in my program.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168ead0b93c970c-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; margin-left: auto; border-top: 0px; margin-right: auto; border-right: 0px; padding-top: 0px" title="SlotSketch" border="0" alt="SlotSketch" src="/assets/image_481426.jpg" width="347" height="200" /></a></p>  <p>Below is the code that demonstrates this approach.&#160; It begins by creating the sketch points and then it uses those points to create the sketch geometry.&#160; It becomes a dot-to-dot exercise to draw the geometry.&#160; This examples illustrates lines and arcs, but all of sketch geometry uses the same concepts.&#160; You’ll just be using different collection objects and different add methods within those collections.</p>  <p style="line-height: 140%; font-family: courier new; background: #eeeeee; color: black; font-size: 8pt"><strong><font color="#0000ff">' Get a reference to the SketchPoints collection.</font></strong>     <br />Dim points As Inventor.SketchPoints = sketch.SketchPoints     <br />    <br /><font color="#0000ff"><strong>' Get a reference to the SketchLines collection.        <br /></strong></font>Dim lines As Inventor.SketchLines = sketch.SketchLines     <br />    <br /><font color="#0000ff"><strong>' Get a reference to the SketchArcs collection.</strong></font>     <br />Dim arcs As Inventor.SketchArcs = sketch.SketchArcs     <br />    <br /><font color="#0000ff"><strong>' Create the sketch points.</strong></font>     <br />Dim pointArray(5) As Inventor.SketchPoint     <br />pointArray(0) = points.Add(tg.CreatePoint2d(0, 1), False)     <br />pointArray(1) = points.Add(tg.CreatePoint2d(0, 0), False)     <br />pointArray(2) = points.Add(tg.CreatePoint2d(0, -1), False)     <br />pointArray(3) = points.Add(tg.CreatePoint2d(4, -1), False)     <br />pointArray(4) = points.Add(tg.CreatePoint2d(4, 0), False)     <br />pointArray(5) = points.Add(tg.CreatePoint2d(4, 1), False)     <br />    <br /><font color="#0000ff"><strong>' Draw the geometry.</strong></font>     <br />Dim arc1 As Inventor.SketchArc     <br />arc1 = arcs.AddByCenterStartEndPoint(pointArray(1), pointArray(0), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pointArray(2))     <br />    <br />Dim line1 As Inventor.SketchLine     <br />line1 = lines.AddByTwoPoints(pointArray(2), pointArray(3))     <br />    <br />Dim arc2 As Inventor.SketchArc     <br />arc2 = arcs.AddByCenterStartEndPoint(pointArray(4), pointArray(3), _     <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; pointArray(5))     <br />    <br />Dim line2 As Inventor.SketchLine     <br />line2 = lines.AddByTwoPoints(pointArray(5), pointArray(0))     <br /></p>  <p>The result after running the program is shown below, which is what’s expected.&#160; Because the entities share sketch points at the connections, Inventor sees this as being closed so it can be used as input to create an extrusion.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340168ead0b94b970c-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; margin-left: auto; border-top: 0px; margin-right: auto; border-right: 0px; padding-top: 0px" title="SlotResult" border="0" alt="SlotResult" src="/assets/image_898572.jpg" width="274" height="117" /></a></p>  <p>However, if you try and edit the sketch by dragging the points it may not behave as you expect, as shown in the picture below.&#160; This is because there aren’t any constraints to define the behavior.&#160; Interactively, constraints are inferred during the sketching process by how you move your mouse, which can’t happen when using the API.&#160; I’ll discuss adding constraints in an upcoming post.</p>  <p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016765ce4a2b970b-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; margin-left: auto; border-top: 0px; margin-right: auto; border-right: 0px; padding-top: 0px" title="ModifiedSlotResult" border="0" alt="ModifiedSlotResult" src="/assets/image_71754.jpg" width="273" height="132" /></a></p>  <p><strong>Note</strong>: One issue that I just discovered while writing this post is that the AddByCenterStartEndPoint method is not associating the input center sketch point with the new arc, but is instead creating a new point at that position.&#160; This is not expected behavior and I’ll discuss how you can work around this issue in a later post.&#160; Just know that when you see the extra center points that you didn’t do anything wrong.</p>  <p>-Brian</p>
