---
layout: "post"
title: "Discussion on Client Graphics &ndash; segment 2"
date: "2012-08-10 21:19:20"
author: "Wayne Brill"
categories:
  - "Assemblies"
  - "Drawings"
  - "Inventor"
  - "Parts"
  - "Wayne"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/08/discussion-on-client-graphics-segment-2.html "
typepad_basename: "discussion-on-client-graphics-segment-2"
typepad_status: "Publish"
---

<p>Here is the second of four articles on Client Graphics. This was originally in a technical paper written by Autodesk Developer Network engineer Xiaodong Liang.</p>
<p>Note: Segment 1 is <a href="http://modthemachine.typepad.com/my_weblog/2012/08/discussion-on-client-graphics.html" target="_blank">here</a></p>
<p><strong>This zip file has a VB.NET project with the examples discussed in this section.</strong></p>
<p><strong><span class="asset  asset-generic at-xid-6a00e553fcbfc688340176173b0196970c"><a href="http://modthemachine.typepad.com/files/clientgraphics_segment_2.zip">Download ClientGraphics_Segment_2</a></span></strong></p>
<p><strong>Start of segment 2</strong></p>
<p><strong>Graphic Primitives</strong></p>
<p><strong><em>Point</em></strong></p>
<p>Point is the simplest graphics object available. You could change the point style such as circular dot, a cross etc, and from Inventor 2011, a Point can be displayed with an image. (This section uses VBA code snippets. In 64 bit using iPictureDisp from&#0160;out of process is a known limitation. In 64 bit VBA is out of process)</p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">&#39; &lt;code snippet : Point&gt; <br /></span>Dim oPointCoords(8) As Double <br />oPointCoords(0) = 0:&#0160;&#0160; oPointCoords(1) = 0: oPointCoords(2) = 0 <br />oPointCoords(3) = 0:&#0160;&#0160; oPointCoords(4) = 1: oPointCoords(5) = 0 <br />oPointCoords(6) = 1:&#0160;&#0160; oPointCoords(7) = 1: oPointCoords(8) = 1 <br /><br /><span style="color: #0000ff;">&#39; Create an image set <br /></span>Dim oImageSet As GraphicsImageSet <br />Set oImageSet = oDataSets.CreateImageSet(oDataSets.count + 1) <br />Dim oImage As IPictureDisp <br />Set oImage = LoadPicture(&quot;C:\Temp\MyImage.bmp&quot;) <br />Call oImageSet.Add(1,oImage) <br /><br /><span style="color: #0000ff;">‘add point graphics and assign the data <br /></span>Call oCoordSet.PutCoordinates(oPointCoords)&#0160; <br />Dim oPointGraphics As PointGraphics <br />Set oPointGraphics = oPointNode.AddPointGraphics oPointGraphics.PointRenderStyle = kFilledCrossPointStyle <br />oPointGraphics.CoordinateSet = oCoordSet <br />oPointGraphics.BurnThrough = True</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834017617261271970c-pi"><img alt="image" border="0" height="342" src="/assets/image_478732.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="297" /></a></p>
<p><strong><em>&#0160;</em></strong></p>
<p><strong><em>Line <br /></em></strong>These are individual line segments. Line graphics use two coordinates to define a line, and then the next two coordinates to define the next line, and so on through the defined coordinates.</p>
<p><strong><em>Line Strip <br /></em></strong>These are a connected set of lines. Line strips use the first two coordinates to define the first line and then the last point of the first line becomes the first point of the second line and the next coordinate is used as the end point of the second line. This results in the set of points being connected by a continuous set of lines, drawing a continuous curve. So to define 2 connected lines, just 3 coordinates would be required.</p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Line or LineStrip&gt;</span> Dim oPointCoords(11) As Double ‘create 4 points&#0160;&#0160;&#0160; <br />oPointCoords(0) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(1) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(2) = 0 <br />oPointCoords(3) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(4) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(5) = 0 <br />oPointCoords(6) = 2:&#0160;&#0160;&#0160;&#0160; oPointCoords(7) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(8) = 0 <br />oPointCoords(9) = 3:&#0160;&#0160;&#0160;&#0160; oPointCoords(10) = 1:&#0160; oPointCoords(11) = 0&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />Call oCoordSet.PutCoordinates(oPointCoords) <span style="color: #0000ff;"><br /><br />‘Line: every 2 points for 1 Line <br /></span>Dim oGraphic As LineGraphics <br />Set oGraphic = oGraphicsNode.AddLineGraphics <br /><br /><span style="color: #0000ff;">‘Line strip: totally, 3 lines <br />‘Dim oGraphic As LineStripGraphics <br />‘Set oGraphic = oGraphicsNode.AddLineStripGraphics&#0160; </span></p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340177440c2442970d-pi"><img alt="image" border="0" height="157" src="/assets/image_565387.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="493" /></a></p>
<p>&#0160;</p>
<p><strong><em>Triangle <br /></em></strong>These are used to define individual triangles. Each set of three coordinates defines a triangle. The next three coordinates then define the next triangle, and so on through all of the coordinates that are provided.</p>
<p><strong><em>Triangle Strip <br /></em></strong>These provide a connected set of triangles. The first three coordinates define a triangle and the next coordinate defines another triangle using the previous two coordinates. You could also specify the strip length. This is provided for performance reasons.&#0160;&#0160;&#0160;</p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Triangle or Triangle Strip&gt; <br /></span>Dim oPointCoords(20) As Double&#0160;&#0160;&#0160; ‘create 7 points, <br />oPointCoords(0) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(1) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(2) = 0 <br />oPointCoords(3) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(4) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(5) = 0 <br />oPointCoords(6) = 2:&#0160;&#0160;&#0160;&#0160; oPointCoords(7) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(8) = 0 <br />oPointCoords(9) = 3:&#0160;&#0160;&#0160;&#0160; oPointCoords(10) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(11) = 0 <br />oPointCoords(12) = 4:&#0160;&#0160;&#0160;&#0160; oPointCoords(13) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(14) = 0 <br />oPointCoords(15) = 5:&#0160;&#0160;&#0160;&#0160; oPointCoords(16) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(17) = 0 <br />oPointCoords(15) = 5:&#0160;&#0160;&#0160;&#0160; oPointCoords(16) = 1:&#0160;&#0160;&#0160;&#0160; oPointCoords(17) = 0 <br />oPointCoords(18) = 6:&#0160;&#0160;&#0160;&#0160; oPointCoords(19) = 0:&#0160;&#0160;&#0160;&#0160; oPointCoords(20) = 0 <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />Call oCoordSet.PutCoordinates(oPointCoords) <span style="color: #0000ff;"><br /><br />‘Triangle: every 3 points for 1 triangle <br /></span>Dim oGraphic As TriangleGraphics <br />Set oGraphic = oGraphicsNode.AddTriangleGraphics <br /><br /><span style="color: #0000ff;">‘or Triangle Strip: totally 5 triangles <br />‘Dim oGraphic As TriangleStripGraphics <br />‘Set oGraphic = oGraphicsNode.AddTriangleStripGraphics </span><br /><br />oGraphic.CoordinateSet = oCoordSet</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340176172612c5970c-pi"><img alt="image" border="0" height="141" src="/assets/image_63722.jpg" style="background-image: none; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="481" /></a></p>
<p><strong>Graphics</strong></p>
<p><strong><em>Triangle Fan <br /></em></strong>This defines a set of connected triangles. The first coordinate is shared in all triangles. The first three coordinates define a triangle. And the next coordinate defines another triangle using the previous coordinates: one of which is the first coordinate. If all the coordinates surround the first point, then the resulting graphics looks like a fan. Again this facility is provided primarily for performance reasons.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016769311710970b-pi"><img alt="image" border="0" height="244" src="/assets/image_550898.jpg" style="background-image: none; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="211" /></a></p>
<p><strong><em>&#0160;</em></strong></p>
<p><strong><em>TextGraphics</em></strong></p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Text&gt; <br /></span>Dim oTG As TransientGeometry <br />Set oTG = ThisApplication.TransientGeometry <br /><br />Dim oTextGraphics As TextGraphics <br />Set oTextGraphics = oNode.AddTextGraphics <br /><br />oTextGraphics.Text = Text <br />oTextGraphics.Anchor = oPosition <br />oTextGraphics.Bold = True <br />oTextGraphics.Font = &quot;Arial&quot; <br />oTextGraphics.FontSize = 40 <br />oTextGraphics.HorizontalAlignment = kAlignTextLeft <br />oTextGraphics.Italic = True <br />Call oTextGraphics.PutTextColor(0, 255, 0)</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340177440c2465970d-pi"><img alt="image" border="0" height="244" src="/assets/image_299339.jpg" style="background-image: none; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="237" /></a></p>
<p>&#0160;</p>
<p><strong><em>Curve <br /></em></strong>Curves include the following objects: LineSegment, Circle, Arc3d, EllipseFull, EllipticalArc and BSplineCurve. The object TransientGeometry is used to create the geometry and client graphics then uses this geometry as input. You can also use the geometry from a model’s native data too.</p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Curve&gt; <br /></span>Dim oTG As TransientGeometry <br />Set oTG = ThisApplication.TransientGeometry <br /><br />Dim oCircle As Inventor.Circle <br />Set oCircle = oTG.CreateCircle(oTG.CreatePoint(0, 0, 0), <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTG.CreateUnitVector(0, 0, 1), 5#) <br />&#0160;&#0160;&#0160; <br />Dim oGraphic As CurveGraphics <br />Set oGraphic = oGraphicsNode.AddCurveGraphics(oCircle)</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc688340177440c2478970d-pi"><img alt="image" border="0" height="235" src="/assets/image_403913.jpg" style="background-image: none; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="244" /></a></p>
<p>&#0160;</p>
<p><strong><em>Surface <br /></em></strong>TransientBrep is used to create the underlying geometry data, and client graphics objects then use this geometry. Again you can use the model’s native data: face, faces or face collection too.</p>
<p style="line-height: 140%; font-family: arial; background: #eeeeee; color: black; font-size: 9pt;"><span style="color: #0000ff;">‘&lt;code snippet: Surface&gt; <br /></span>Dim oTransientBRep As TransientBRep <br />Set oTransientBRep = ThisApplication.TransientBRep <br />&#0160;&#0160;&#0160; <br />Dim oTG As TransientGeometry <br />Set oTG = ThisApplication.TransientGeometry <br /><br /><br />Dim oBody As SurfaceBody <br />Set oBody = oTransientBRep.CreateSolidCylinderCone _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; (oTG.CreatePoint(0, 0, 0), _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oTG.CreatePoint(0, 10, 0), _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; 5, 5, 0) Dim oSurfaceGraphics As SurfaceGraphics <br />Set oSurfaceGraphics = oSurfacesNode. _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; AddSurfaceGraphics(oBody)</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834016769311738970b-pi"><img alt="image" border="0" height="244" src="/assets/image_724260.jpg" style="background-image: none; margin: 0px; padding-left: 0px; padding-right: 0px; display: inline; padding-top: 0px; border-width: 0px;" title="image" width="240" /></a></p>
<p>&#0160;</p>
<p>End of Segment 2</p>
<p>-Wayne</p>
