---
layout: "post"
title: "Inventor API Labs step by step"
date: "2012-02-25 00:57:30"
author: "Wayne Brill"
categories:
  - "Beginning API"
original_url: "https://modthemachine.typepad.com/my_weblog/2012/02/inventor-api-labs-step-by-step.html "
typepad_basename: "inventor-api-labs-step-by-step"
typepad_status: "Publish"
---

<p>If you are just learning the Inventor API, these <a href="http://www.adskconsulting.com/adn/cs/api_course_webcast_archive.php">webcasts</a> delivered in the spring of 2010 are a great resource. There are labs for each section. (A slide in the presentation). The finished labs that are downloaded with the webcast recordings are very useful however the lab instructions do not have much detail. </p>  <p>When I do labs I usually want to have step by step instructions. If you are like me then the steps in these <a href="http://modthemachine.typepad.com/Inventor_API_Labs_StepByStep.zip">VB.NET projects</a> will be better. There are four VB .NET projects in the zip file. </p>  <ul>   <li>Labs </li>    <li>Labs_Compete </li>    <li>Lab_10_AddIn_Add_To_Ribbon </li>    <li>Lab_10_Complete_AddIn_Add_To_Ribbon </li> </ul>  <p>The Labs project creates a standalone executable that connects to Inventor from out of process. Lab_10_AddIn_Add_To_Ribbon project is an Add-In created by the SDK Add-In wizard.</p>  <p>Here is an example of the Instructions in the Labs project:</p>  <div style="font-family: courier new; background: #eeeeee; color: black; font-size: 9pt">   <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' ***** Start of LAB 2 ***********************</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' 2.1 Add a procedure called iProps. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Note: put the End Sub below step 2.19</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' 2.2 Declare a variable as a PartDocument </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Name it m_PartDoc</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' 2.3. Make a new PartDocument by using the Add</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' method of the documents collection of the </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Application(variable created in step 3 of LAB1)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' (Instantiate the variable created in 2.2)</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' 2.4. Use a For Each loop and iterate through</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' all the PropertySets in the PartDocument </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' created in step 2.3.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Note: put the Next statement below Step 2.10</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' 2.5. Use Debug.print and print the DisplayName </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' of the PropertySet</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' 2.6. Use Debug.print and print the InternalName</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' of the PropertySet</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' 2.7. Use a For Each loop and iterate through </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' all the Property in the PropertySet created in </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' step 2.4.(in the For Each statement)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">' Note: put the Next statement below Step 2.10 </span></p> </div>  <p>You can use Labs_Complete if you have trouble getting the lab to work right.&#160; </p>  <p>Here is a synopsis of the labs. </p>  <p><strong>Lab1</strong>: Access the Application Object – Connect to an Inventor session change the ActiveView and the caption of the Inventor Window.</p>  <p><strong>Lab2</strong>: iProperties - In this lab you create a procedure that creates a new part document and sets a few iProperties for the part.</p>  <p><strong>Lab3</strong>: UnitsOfMeasure and parameters - Use UnitsOfMeasure to test to see if a string you get from the user is valid. If the value is valid you convert it to a different unit and use the value to update a parameter.</p>  <p><strong>Lab4</strong>: WorkFeatures Sketch &amp; Fetures - Access workaxes and workplanes. You create a new workaxis and workplane. You also create a new part, add a sketch and then extrude it. You also create a SweepFeature. (It needs a SketchLine3d)</p>  <p><strong>Lab5</strong>: B-Rep: In this lab you get information about a selected edge using the curveEvaluator of the edge. You also use the B-Rep API to traverse the solid. You also use LocateUsingPoint and FindUsingRay to get geometry of the model. </p>  <p><strong>Lab6</strong>: – (not finished) It would have done more with the B-Rep API</p>  <p><strong>Lab7</strong>: Sheet Metal – Demonstrates the creation of sheet metal face and cut features. It creates a new sheet metal document, creates a face feature, a cut feature and another face feature. You also create a R12 DXF file. </p>  <p><strong>Lab8</strong>: Assembly Occurrences - Create an assembly and place components. You will also see how to move occurrences by transforming them. This lab also has instructions for exploring proxies and how to add constraints.</p>  <p><strong>Lab9</strong>: Drawings - Create an idw file and see how to add a dimension</p>  <p><strong>Lab10</strong>: Add-In – Create an AddIn that adds buttons to the part and assembly ribbon. The project you complete was created by the Add-In wizard. To get your Add-In to load make sure to edit the .addin file and put the file in a location where Inventor will find it.</p>  <p>The instructions in these labs require some experience with VB.NET programming. If you are just getting started with programming then be sure to go through the “<a href="http://usa.autodesk.com/adsk/servlet/index?siteID=123112&amp;id=17324828">My First Plug-In</a>” training first. </p>  <p>Wayne Brill</p>
