---
layout: "post"
title: "Working with Cameras (Part 2)"
date: "2013-09-09 19:22:53"
author: "Adam Nagy"
categories:
  - "Brian"
  - "Inventor"
original_url: "https://modthemachine.typepad.com/my_weblog/2013/09/working-with-cameras-part-2.html "
typepad_basename: "working-with-cameras-part-2"
typepad_status: "Publish"
---

<p>This is a continuation of a <a href="http://modthemachine.typepad.com/my_weblog/2013/09/working-with-cameras-part-1.html">previous post</a> introducing cameras.</p>
<p><strong>A Camera Gotcha</strong> <br />When working with cameras associated with a graphics view you use the Camera property of the View object. Typically you’ll get the View object using the Application.ActiveView property. The behavior of the View.Camera property is that every time you call it, it returns a new camera. This behavior makes it easy to run into a very common problem when working with cameras. The code below illustrates the problem. It calls the Camera property of the View object and then calls the ViewOrientationType property of the Camera object, setting the camera position to be a standard isometric view. Once it does this it calls the camera’s Apply method. The result is that nothing happens.</p>
<div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black;">
<p><span style="color: #0000ff;"><strong>&#39; Set the camera orientation to an iso view.</strong></span> <br />invApp.ActiveView.Camera.ViewOrientationType = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; IsoTopLeftViewOrientation <br /><span style="color: #0000ff;"><strong>&#39; Apply the camera changes to the view.</strong></span> <br />invApp.ActiveView.Camera.Apply</p>
</div>
<p>The reason that nothing happens is that in the first line the Camera property is called and a camera is created and returned. On this camera the isometric view is specified. On the next line the Camera property is called again and another camera is created and returned. On this camera the Apply method is called, but this camera hasn’t had the view orientation set but is the same as the current view so you don’t see any visible change. The code below illustrates the correct procedure and does create the desired result. In this case the Camera property is called and the camera is returned. The orientation for that camera is defined as an isometric view and the Apply method on the same camera is called. The view then updates to reflect the new camera position.</p>
<div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black;">
<p><span style="color: #0000ff;"><strong>&#39; Get the camera from the view. <br /></strong></span>Dim cam As Camera <br />Set cam = invApp.ActiveView.Camera <br /> </p>
<span style="color: #0000ff;"><strong>&#39; Set the camera orientation to an iso view. <br /></strong></span>cam.ViewOrientationType = kIsoTopLeftViewOrientation <br /> <br /><span style="color: #0000ff;"><strong>&#39; Apply the camera changes to the view. <br /></strong></span>cam.Apply</div>
<p><strong>Applying Camera Changes</strong> <br />Setting a property on a camera doesn’t have an immediate effect. This is because typically you’ll want to make several changes to the camera before you force the view to update. For example you might want to change both the eye and target points and then update the camera. There are two methods that cause changes to the camera take effect. They are Apply and ApplyWithoutTransition. The Apply method uses the same transition technique that inventor uses when you change to a new view orientation; it smoothly transitions from one position to another. The ApplyWithoutTransition immediately shows the new camera position without any transition. The ApplyWithoutTransition is used when you’re doing your own camera animation because you’ll be computing all of the camera positions yourself and don’t want the delay as Inventor transitions from one camera position to another.</p>
<p><strong>Modifying the Camera <br /></strong>There are three properties on the camera that control the position and orientation of the camera; the Eye, Target, and UpVector properties. There are other properties that let you control the camera’s field of view. the Perspective property lets you toggle the camera from perspective to parallel. When the camera is a perspective camera you can use the PerspectiveAngle property to control the field of view. When it’s a parallel camera you can use the GetExtents and SetExtents methods to get and set the field of view. In addition to these functions that let you directly get and set the underlying properties of a camera there are also some convenience functions that make it easier to manipulate the camera. For example, the ViewOrientationType lets you specify standard view positions, (i.e. top, front, top-left iso, etc.) and Inventor will modify the eye, target, and up vector as-needed. The Fit method takes into account the size of the model and modifies the camera so the entire model is visible. There is also a function that takes mouse input and modifies the camera to reflect the mouse movement or scrolling.</p>
<p>Below is some VBA code that will fly the camera around the model. To simplify the code, the target is hard coded at the origin and the up vector is the positive Z.</p>
<div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black;">
<p>Public Sub RotateCamera() <br /><strong>&#0160;&#0160; <span style="color: #0000ff;">&#39; Get the active camera.</span></strong> <br />&#0160;&#0160; Dim cam As Camera <br />&#0160;&#0160; Set cam = ThisApplication.ActiveView.Camera <br />&#0160;&#0160; Dim tg As TransientGeometry <br />&#0160;&#0160; Set tg = ThisApplication.TransientGeometry <br /> <br /><strong>&#0160;&#0160; <span style="color: #0000ff;">&#39; Define the number of steps in the animation.</span></strong> <br />&#0160;&#0160; Dim steps As Integer <br />&#0160;&#0160; steps = 360 <br /> <br /><strong>&#0160;&#0160; <span style="color: #0000ff;">&#39; Define the distance between the eye and target.</span></strong> <br />&#0160;&#0160; Dim eyeDistance As Double <br />&#0160;&#0160; eyeDistance = 15 <br /> <br /><strong>&#0160;&#0160; <span style="color: #0000ff;">&#39; Calculate pi.</span></strong> <br />&#0160;&#0160; Dim pi As Double <br />&#0160;&#0160; pi = Atn(1) * 4 <br /> <br /><strong>&#0160;&#0160; <span style="color: #0000ff;">&#39; Iterate the specified number of steps.</span></strong> <br />&#0160;&#0160; Dim i As Integer&#0160; <br />&#0160;&#0160; For i = 1 To steps&#0160; <br /><strong>&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #0000ff;">&#39; Calculate the x and y coordinates of the eye.</span></strong> <br />&#0160;&#0160;&#0160;&#0160;&#0160; Dim x As Double <br />&#0160;&#0160;&#0160;&#0160;&#0160; Dim y As Double <br />&#0160;&#0160;&#0160;&#0160;&#0160; x = eyeDistance * Cos(i / steps * (2 * pi)) <br />&#0160;&#0160;&#0160;&#0160;&#0160; y = eyeDistance * Sin(i / steps * (2 * pi)) <br /> <br /><strong>&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #0000ff;">&#39; Set the eye using calculated x, y and a hard coded z value.</span></strong> <br />&#0160;&#0160;&#0160;&#0160;&#0160; cam.Eye = tg.CreatePoint(x, y, 3) <br /><strong> <br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #0000ff;">&#39; Define the up vector as positive z.</span></strong> <br />&#0160;&#0160;&#0160;&#0160;&#0160; cam.UpVector = tg.CreateUnitVector(0, 0, 1) <br /> <br /><strong>&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #0000ff;">&#39; Apply the current camera definition to the view.</span></strong> <br />&#0160;&#0160;&#0160;&#0160;&#0160; cam.ApplyWithoutTransition <br />&#0160;&#0160; Next <br />End Sub</p>
</div>
<p><strong>Why Use the Camera?</strong> <br />There are several reasons you might want to use the Camera object. The first is that you have a need to control the view within Inventor. For example, you can create a custom fly-trough of an assembly or write some utilities that allow you to quickly go to certain views. The sample code above demonstrates the procedure to set the camera properties and apply it to a view. Watch for another post about how to make the camera follow a curve like what was demonstrated in the video in this earlier <a href="http://modthemachine.typepad.com/my_weblog/2013/08/high-school-interns-at-autodesk.html">post</a>.</p>
<p>A camera is also used to create non-standard drawing views. Using a camera you can create any view orientation you want. The following code illustrates using a camera to create a custom drawing view that is a perspective isometric view.</p>
<div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black;">
<p><strong><span style="color: #0000ff;">&#39; Create a camera to be used to define the view orientation.</span></strong> <br />Dim cam As Camera <br />Set cam = ThisApplication.TransientObjects.CreateCamera <br /><strong> <br /><span style="color: #0000ff;">&#39; Set up the camera.</span></strong> <br />cam.Perspective = True <br />cam.ViewOrientationType = kIsoTopRightViewOrientation <br /><strong> <br /><span style="color: #0000ff;">&#39; Create a drawing view using the camera.</span></strong> <br />Dim viewPnt As Point2d <br />Set viewPnt = ThisApplication.TransientGeometry.CreatePoint2d(12, 12) <br />Dim drawView As DrawingView <br />Set drawView = drawSheet.DrawingViews.AddBaseView(doc, viewPnt, 1, _&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; kArbitraryViewOrientation, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; kHiddenLineRemovedDrawingViewStyle, , _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; oCamera) </p>
</div>
<p>The Camera object can also be used to save an image as a file. You essentially capture whatever the camera is currently seeing and save that as an image file. The format of the file can be any of several popular image types, (i.e. jpg, bmp, png, gif, and tiff). This can be useful within Inventor but is particularly useful with Apprentice because Apprentice doesn’t have a visible graphics window. You can use a camera to create images for parts, assemblies, and drawings. The VB.Net code below demonstrates creating an image of a part or assembly using Apprentice. It assumes you’ve already created an instance of Apprentice and have opened the part or assembly, which are both passed into this sub, along with the filename to use for the image. The type of image created is dependent on the extension of the filename.</p>
<div style="font-size: 10pt; font-family: consolas; background: #eeeeee; color: black;">
<p>Private Sub CreateImage( _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Apprentice As Inventor.ApprenticeServerComponent, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; PartOrAssembly As Inventor.ApprenticeServerDocument, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Filename As String) <br /><strong>&#0160;&#0160; &#39; Create a new camera.</strong> <br />&#0160;&#0160; Dim cam As Inventor.Camera <br />&#0160;&#0160; cam = Apprentice.TransientObjects.CreateCamera <br /><strong> <br />&#0160;&#0160; &#39; Associate the document with the camera.</strong> <br />&#0160;&#0160; cam.SceneObject = PartOrAssembly.ComponentDefinition <br /><strong> <br />&#0160;&#0160; &#39; Define the camera and apply the changes.</strong> <br />&#0160;&#0160; cam.ViewOrientationType = _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Inventor.ViewOrientationTypeEnum.kIsoTopRightViewOrientation <br />&#0160;&#0160; cam.Fit() <br />&#0160;&#0160; cam.ApplyWithoutTransition() <br /><strong> <br />&#0160;&#0160; &#39; Save the result, defining the background color of the image.</strong> <br />&#0160;&#0160; cam.SaveAsBitmap(Filename, 800, 600, _ <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Apprentice.TransientObjects.CreateColor(255, 255, 0), _&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Apprentice.TransientObjects.CreateColor(15, 15, 15)) <br />End Sub</p>
</div>
<p>The resulting image is shown below.</p>
<p><a href="http://modthemachine.typepad.com/.a/6a00e553fcbfc68834019aff492167970c-pi"><img alt="Camera07" border="0" height="237" src="/assets/image_495984.jpg" style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; margin-right: auto; border-width: 0px;" title="Camera07" width="315" /></a></p>
<p>That’s the basics of using cameras. Watch for an upcoming post where we’ll look at a tool to better visualize the camera and how to use geometry in the model to control the camera.</p>
<p>-Brian</p>
