---
layout: "post"
title: "Inventor 2014 API 新機能 更新情報"
date: "2013-04-29 03:33:14"
author: "Shigelazu Saitou"
categories:
  - "API カスタマイズ"
  - "その他カスタマイズ"
  - "デスクトップ製品"
original_url: "https://adndevblog.typepad.com/technology_perspective/2013/04/inventor-2014-api-%E6%96%B0%E6%A9%9F%E8%83%BD-%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1.html "
typepad_basename: "inventor-2014-api-新機能-更新情報"
typepad_status: "Publish"
---

<p><a href="http://adndevblog.typepad.com/technology_perspective/2013/04/inventor-2014-api%E6%A9%9F%E8%83%BD-%E3%81%9D%E3%81%AE%EF%BC%91.html">前回</a>、<a href="http://adndevblog.typepad.com/technology_perspective/2013/04/inventor-2014-%E6%A9%9F%E8%83%BD-%E3%81%9D%E3%81%AE%EF%BC%92.html">前々回</a>の「Inventor 2014 機能紹介 」に続き、Inventor 2014のAPIについてご紹介させていただきます。<br />
今回は、アセンブリ内における「新しいジョイント機能」用のAPIにおいて、Autodesk Inventor 2014 API Help( admapi_18_0.chm) ファイルに掲載されております「サンプルコード」の<strong>更新情報</strong>を掲載させていただきます。</p>

<p><strong>"Create rotational assembly connection. API Sample"</strong><br />
<a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b019101a3529d970c-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b019101a3529d970c" alt="Fig-1" title="Fig-1" src="/assets/image_778177.jpg" /></a><br /><br />
<strong>Public Sub AssemblyJoint()</strong><br />
    ' アセンブリドキュメントを新規作成<br />
    Dim asmDoc As AssemblyDocument<br />
    Set asmDoc = ThisApplication.Documents.Add(kAssemblyDocumentObject, _<br />
                  ThisApplication.FileManager.GetTemplateFile(kAssemblyDocumentObject))<br />
    Dim asmDef As AssemblyComponentDefinition<br />
    Set asmDef = asmDoc.ComponentDefinition<br />
    <br />
    ' アセンブリ内にオカレンスを配置<br />
    Dim occ1 As ComponentOccurrence<br />
    Dim occ2 As ComponentOccurrence<br />
    Dim trans As Matrix<br />
    Set trans = ThisApplication.TransientGeometry.CreateMatrix<br />
    Set occ1 = asmDef.Occurrences.Add("C:\Temp\SamplePart.ipt", trans)<br />
    <br />
    ' 最初に配置されたオカレンス位置を基に２つ目のオカレンスのマトリクスを調整し配置<br />
    trans.Cell(1, 4) = 6 * 2.54<br />
    Set occ2 = asmDef.Occurrences.Add("C:\Temp\SamplePart.ipt", trans)<br />
    <br />
    ' 最初のオカレンスのFace1を得て、FaceProxyを作成<br />
    Dim face1 As Face<br />
    Set face1 = GetNamedEntity(occ1, "Face1")<br />
    <br />
    ' ２つ目のオカレンスのFace2を得て、FaceProxy を作成<br />
    Dim face2 As Face<br />
    Set face2 = GetNamedEntity(occ2, "Face2")<br />
    <br />
    ' ２つ目のオカレンスから Edge1 を得てEdgeProxyの作成.<br />
    Dim Edge1 As Edge<br />
    Set Edge1 = GetNamedEntity(occ2, "Edge1")<br />
    <br />
    ' 最初のオカレンスからEdge 3 を得てEdgeProxyの作成.<br />
    Dim Edge3 As Edge<br />
    Set Edge3 = GetNamedEntity(occ1, "Edge3")<br />
    <br />
    ' Edge1の中心データでGeometryIntentの作成<br />
    Dim edge1Intent As GeometryIntent<br />
    Set edge1Intent = asmDef.CreateGeometryIntent(Edge1, PointIntentEnum.kMidPointIntent)<br />
    <br />
    ' Edge3の中心データでGeometryIntentの作成<br />
    Dim edge3Intent As GeometryIntent<br />
    Set edge3Intent = asmDef.CreateGeometryIntent(Edge3, PointIntentEnum.kMidPointIntent)<br />
    <br />
    ' 「ジョイント」定義用に２つのGeometryIntentの作成<br />
    Dim intentOne As GeometryIntent<br />
    Set intentOne = asmDef.CreateGeometryIntent(face2, edge1Intent)<br />
    Dim intentTwo As GeometryIntent<br />
    Set intentTwo = asmDef.CreateGeometryIntent(face1, edge3Intent)</p>

<p>    ' ２つのパーツ間に「リジッド」ジョイントを作成<br />
    Dim jointDef As AssemblyJointDefinition<br />
    Set jointDef = asmDef.Joints.CreateAssemblyJointDefinition(kRotationalJointType, intentOne, intentTwo)<br />
    jointDef.FlipAlignmentDirection = False<br />
    jointDef.FlipOriginDirection = True<br />
    Dim joint As AssemblyJoint<br />
    Set joint = asmDef.Joints.Add(jointDef)</p>

<p>    ' ジョイントを表示<br />
    joint.Visible = True<br />
    <br />
    ' ジョイントをアニメーション駆動<br />
    joint.DriveSettings.StartValue = "0 deg"<br />
    joint.DriveSettings.EndValue = "180 deg"<br />
    joint.DriveSettings.GoToStart<br />
    joint.DriveSettings.PlayForward<br />
    joint.DriveSettings.PlayReverse<br />
<strong>End Sub</strong></p>

<p><br />
' 指定された名前のiMateと関連付けられているエンティティを検索します。<br />
‘ iMatesを汎用ネーミングメカニズムとして使用する<br />
<strong>Private Function GetNamedEntity(Occurrence As ComponentOccurrence, Name As String) As Object</strong><br />
    ' 参照されたファイル内で指定した名前のiMateを探す<br />
    Dim iMate As iMateDefinition<br />
    Dim partDef As PartComponentDefinition<br />
    Set partDef = Occurrence.Definition<br />
    For Each iMate In partDef.iMateDefinitions<br />
        ' iMateが正しい名前を持っているかどうかを確認<br />
        If UCase(iMate.Name) = UCase(Name) Then<br />
            '  iMateに関連付けられているジオメトリを取得<br />
            Dim entity As Object<br />
            Set entity = iMate.entity<br />
            <br />
            ' プロキシの作成<br />
            Dim resultEntity As Object<br />
            Set resultEntity = Nothing<br />
            Call Occurrence.CreateGeometryProxy(entity, resultEntity)<br />
            <br />
            Exit For<br />
        End If<br />
    Next<br />
    <br />
    ' 見つかったエンティティを返す。見つからない場合はNothing<br />
    Set GetNamedEntity = resultEntity<br />
<strong>End Function</strong></p>

<p>サンプルは<span class="asset  asset-generic at-xid-6a0167607c2431970b01901bad8858970b"><a href="http://adndevblog.typepad.com/files/assemblyjoint.zip">ここ</a></span> よりダウンロードする事ができます。<br />
（解凍後、"C:\Temp\SamplePart.ipt"として配置して動作確認ができます）</p>

<p><strong>次回も、引き続きInventor2014製品の API ついてご案内する予定です。</strong><br />
By Shigekazu Saito.<br />
</p>
