---
layout: "post"
title: "Inventor 2014 API 新機能 その２"
date: "2013-05-06 02:30:00"
author: "Shigelazu Saitou"
categories:
  - "API カスタマイズ"
  - "その他カスタマイズ"
  - "デスクトップ製品"
original_url: "https://adndevblog.typepad.com/technology_perspective/2013/05/inventor-2014-api-%E6%96%B0%E6%A9%9F%E8%83%BD-%E3%81%9D%E3%81%AE%EF%BC%92.html "
typepad_basename: "inventor-2014-api-新機能-その２"
typepad_status: "Publish"
---

<p><a href="http://adndevblog.typepad.com/technology_perspective/2013/04/inventor-2014-api-%E6%96%B0%E6%A9%9F%E8%83%BD-%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1.html">前回</a>、の「Inventor 2014 API 新機能 更新情報」に続き、<strong>Inventor 2014の新しいAPI</strong>についてご紹介させていただきます。</p>

<p><strong>１．	２Ｄ／３Ｄスプライン及び２Ｄ／３Ｄ計算式曲線の作成 並びに３Ｄ交差曲線がAPIにより作成可能となります</strong>。<br />
<a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b019101d3c43d970c-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b019101d3c43d970c" alt="Fig1" title="Fig1" src="/assets/image_786731.jpg" /></a><a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b019101d3c56b970c-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b019101d3c56b970c" alt="Fig2" title="Fig2" src="/assets/image_93486.jpg" /></a><a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017eeadb5b0f970d-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b017eeadb5b0f970d" alt="Fig3" title="Fig3" src="/assets/image_822720.jpg" /></a><a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b019101d3c843970c-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b019101d3c843970c" alt="Fig4" title="Fig4" src="/assets/image_969186.jpg" /></a><a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017eeadb5c8b970d-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b017eeadb5c8b970d" alt="Fig5" title="Fig5" src="/assets/image_754297.jpg" /></a><a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017eeadb5d04970d-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b017eeadb5d04970d" alt="Fig6" title="Fig6" src="/assets/image_783472.jpg" /></a></p>

<p><strong>' ２Ｄ／３Ｄスプライン及び２Ｄ／３Ｄ計算式曲線の作成 並びに３Ｄ交差曲線の作成。<br />
Public Sub SketchCurves()</strong><br />
    ' 新規パーツファイルの作成<br />
    Dim partDoc As PartDocument<br />
    Set partDoc = ThisApplication.Documents.Add(kPartDocumentObject, _<br />
                  ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))<br />
    Dim partDef As PartComponentDefinition<br />
    Set partDef = partDoc.ComponentDefinition<br />
                  <br />
    ' X-Y平面を使って ２Ｄスケッチの作成<br />
    Dim sketch1 As PlanarSketch<br />
    Set sketch1 = partDef.Sketches.Add(partDef.WorkPlanes.Item(3))<br />
    <br />
    Dim tg As TransientGeometry<br />
    Set tg = ThisApplication.TransientGeometry<br />
    <br />
    ' スプライン構成点群の作成<br />
    Dim pnts As ObjectCollection<br />
    Set pnts = ThisApplication.TransientObjects.CreateObjectCollection<br />
    Call pnts.Add(tg.CreatePoint2d(2, 0))<br />
    Call pnts.Add(tg.CreatePoint2d(4, 1))<br />
    Call pnts.Add(tg.CreatePoint2d(4, 2))<br />
    Call pnts.Add(tg.CreatePoint2d(6, 3))<br />
    Call pnts.Add(tg.CreatePoint2d(8, 1))<br />
    <br />
    ' スプラインの作成<br />
    Dim controlPointSpline As SketchControlPointSpline<br />
    Set controlPointSpline = sketch1.SketchControlPointSplines.Add(pnts)<br />
    <br />
    ' Y-Z平面を使って ２Ｄスケッチの作成<br />
    Dim sketch2 As PlanarSketch<br />
    Set sketch2 = partDef.Sketches.Add(partDef.WorkPlanes.Item(1))<br />
    <br />
    ' ２Ｄ計算式曲線の作成<br />
    Dim equationCurve As SketchEquationCurve<br />
    Set equationCurve = sketch2.SketchEquationCurves.Add(kParametric, kCartesian, _<br />
                                "0.1 * cos(t) * t  * 0.1", "0.1 *  sin(t) * t * 0.1", 0, 360 * 3)<br />
                                <br />
    ' ３Ｄスケッチの作成<br />
    Dim sketch3 As sketch3D<br />
    Set sketch3 = partDef.Sketches3D.Add<br />
    <br />
    ' ３Ｄスプライン構成点群の作成<br />
    Set pnts = ThisApplication.TransientObjects.CreateObjectCollection<br />
    Call pnts.Add(tg.CreatePoint(10, 0, 0))<br />
    Call pnts.Add(tg.CreatePoint(12, 1, 3))<br />
    Call pnts.Add(tg.CreatePoint(12, 2, -5))<br />
    Call pnts.Add(tg.CreatePoint(14, 3, 2))<br />
    Call pnts.Add(tg.CreatePoint(16, 1, -3))<br />
    <br />
    ' ３Ｄスプラインの作成<br />
    Dim controlPointSpline2 As SketchControlPointSpline3D<br />
    Set controlPointSpline2 = sketch3.SketchControlPointSplines3D.Add(pnts)<br />
    <br />
    ' ３Ｄ計算式曲線の作成<br />
    Dim equationCurve2 As SketchEquationCurve3D<br />
     Set equationCurve2 = sketch3.SketchEquationCurves3D.Add(kCartesian, _<br />
                            "0.01 * cos(t) * t + 8", "0,01 * sin(t) * t", "0.02 * t", 0, 360 * 3)<br />
                           <br />
    ThisApplication.ActiveView.Fit<br />
    <br />
    ' X-Y平面として作成した２Ｄスケッチ上の曲線を使い、押し出しフィーチャーの作成<br />
    Dim prof As Profile<br />
    Set prof = sketch1.Profiles.AddForSurface(controlPointSpline)<br />
    Dim extrudeDef As ExtrudeDefinition<br />
    Set extrudeDef = partDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(prof, kSurfaceOperation)<br />
    Call extrudeDef.SetDistanceExtent(6, kSymmetricExtentDirection)<br />
    Dim extrude1 As ExtrudeFeature<br />
    Set extrude1 = partDef.Features.ExtrudeFeatures.Add(extrudeDef)<br />
    <br />
    ' 押し出しフィーチャーの「親」のサーフェスを獲得し「半透明」表現を解除<br />
    Dim surf As WorkSurface<br />
    Set surf = extrude1.SurfaceBodies.Item(1).Parent<br />
    surf.Translucent = False<br />
    <br />
    ' Y-Z平面として作成した２Ｄスケッチ上の曲線を使い、押し出しフィーチャーの作成<br />
    Set prof = sketch2.Profiles.AddForSurface(equationCurve)<br />
    Set extrudeDef = partDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(prof, kSurfaceOperation)<br />
    Call extrudeDef.SetDistanceExtent(9, kPositiveExtentDirection)<br />
    Dim extrude2 As ExtrudeFeature<br />
    Set extrude2 = partDef.Features.ExtrudeFeatures.Add(extrudeDef)<br />
    <br />
    ' ３Ｄスケッチを作成<br />
    Dim interSketch As sketch3D<br />
    Set interSketch = partDef.Sketches3D.Add<br />
    <br />
    ' 押し出し１と押し出し２を使い、３Ｄスケッチ上に「交点曲線」を作成<br />
    Call interSketch.IntersectionCurves.Add(extrude1.SurfaceBodies.Item(1), extrude2.SurfaceBodies.Item(1))<br />
<strong>End Sub</strong></p>

<p><br />
<strong>２．	２Ｄスケッチ上にスロットの作成</strong></p>

<p><a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017eeadb61ae970d-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b017eeadb61ae970d" alt="Fig7" title="Fig7" src="/assets/image_919082.jpg" /></a><br />
<strong>' ２Ｄスケッチ上にスロットの作成<br />
Public Sub CreateSlots()</strong><br />
   ' パーツファイルの新規作成<br />
    Dim partDoc As PartDocument<br />
    Set partDoc = ThisApplication.Documents.Add(kPartDocumentObject, _<br />
                  ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))<br />
    Dim partDef As PartComponentDefinition<br />
    Set partDef = partDoc.ComponentDefinition<br />
                  <br />
    ' X-Y平面を使って ２Ｄスケッチの作成<br />
    Dim sketch As PlanarSketch<br />
    Set sketch = partDef.Sketches.Add(partDef.WorkPlanes.Item(3))<br />
    <br />
    Dim tg As TransientGeometry<br />
    Set tg = ThisApplication.TransientGeometry<br />
    <br />
    Dim pi As Double<br />
    pi = Atn(1) * 4<br />
    <br />
    ' ２Ｄスケッチ上に 各スロットの作成<br />
    Dim results As SketchEntitiesEnumerator<br />
    Set results = sketch.AddArcSlotByCenterPointArc(tg.CreatePoint2d(0, 0), tg.CreatePoint2d(6, 0), pi / 2, 2)<br />
    <br />
    Set results = sketch.AddArcSlotByThreePointArc(tg.CreatePoint2d(15, 0), tg.CreatePoint2d(12.5, 2), tg.CreatePoint2d(10, 0), 2)<br />
    <br />
    Set results = sketch.AddStraightSlotByCenterToCenter(tg.CreatePoint2d(0, 10), tg.CreatePoint2d(6, 10), 2)<br />
    <br />
    Set results = sketch.AddStraightSlotByOverall(tg.CreatePoint2d(10, 10), tg.CreatePoint2d(16, 10), 2)<br />
                                <br />
    ThisApplication.ActiveView.Fit<br />
    <br />
<strong>End Sub</strong></p>

<p><br />
<strong>３．	アセンブリファイル内の２つのボディを使用し、フェースの重なったエッジで分割された新しいサーフェスボディを持つ「パーツファイル」の作成。</strong><br />
<a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017eeadb6375970d-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b017eeadb6375970d" alt="Fig8" title="Fig8" src="/assets/image_916562.jpg" /></a</p>

<p><a class="asset-img-link"  style="display: inline;" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01901bddd536970b-pi"><img class="asset  asset-image at-xid-6a0167607c2431970b01901bddd536970b" alt="Fig9" title="Fig9" src="/assets/image_859283.jpg" /></a><br />
<strong>Fig9. 新しいサーフェスを持つパーツファイル</strong></p>

<p><strong>Public Sub CreateImprintFromAssembly()</strong><br />
    ' アクティブなアセンブリドキュメントの確保<br />
    Dim asmDoc As AssemblyDocument<br />
    Set asmDoc = ThisApplication.ActiveDocument<br />
    <br />
    ' アセンブリ内のオカレンスを選択<br />
    Dim part1 As ComponentOccurrence<br />
    Dim part2 As ComponentOccurrence<br />
    Set part1 = ThisApplication.CommandManager.Pick(kAssemblyLeafOccurrenceFilter, "Select part 1")<br />
    Set part2 = ThisApplication.CommandManager.Pick(kAssemblyLeafOccurrenceFilter, "Select part 2")<br />
    <br />
    ' 関連するオカレンスを得る。<br />
    ' 尚、このサンプルはImprintBodiesメソッドを使用しているために<br />
    ' SurfaceBodyProxyオブジェクトで使用する場合は、動作しません。<br />
    ' これらを回避するために、新たな変換されたボディを作成する事により<br />
    ' 同等の結果が提供されます。<br />
    <br />
    ' 一時的なボディとしてパーツ空間でボディを取得<br />
    Dim transBrep As TransientBRep<br />
    Set transBrep = ThisApplication.TransientBRep<br />
    Dim body1 As SurfaceBody<br />
    Dim body2 As SurfaceBody<br />
    Set body1 = transBrep.Copy(part1.Definition.SurfaceBodies.Item(1))<br />
    Set body2 = transBrep.Copy(part2.Definition.SurfaceBodies.Item(1))<br />
    <br />
    ' アセンブリ内で表現できるように、ボディを変換<br />
    Call transBrep.Transform(body1, part1.Transformation)<br />
    Call transBrep.Transform(body2, part2.Transformation)<br />
    <br />
    ' ２つのボディを使って、フェースの領域を見つける。<br />
    ' フェースが重なったエッジで分割された新しいボディを作成。<br />
    Dim newBody1 As SurfaceBody<br />
    Dim newBody2 As SurfaceBody<br />
    Dim body1OverlapFaces As Faces<br />
    Dim body2OverlapFaces As Faces<br />
    Dim body1OverlapEdges As Edges<br />
    Dim body2OverlapEdges As Edges<br />
    Call ThisApplication.TransientBRep.ImprintBodies _<br />
       (body1, body2, True, newBody1, newBody2, _<br />
        body1OverlapFaces, body2OverlapFaces, _<br />
        body1OverlapEdges, body2OverlapEdges)</p>

<p>    ' 結果を表現する為の新しいパーツファイルを作成<br />
    Dim partDoc As PartDocument<br />
    Set partDoc = ThisApplication.Documents.Add(kPartDocumentObject, _<br />
                  ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))<br />
    Dim partDef As PartComponentDefinition<br />
    Set partDef = partDoc.ComponentDefinition</p>

<p>    ' 新しく作成された１つ目のサーフェスボディを使い、<br />
    ' 新規にNonParametricBaseFeatureオブジェクトの作成<br />
    Dim non1 As NonParametricBaseFeature<br />
    Set non1 = partDef.Features.NonParametricBaseFeatures.Add(newBody1)<br />
    Set newBody1 = non1.SurfaceBodies.Item(1)</p>

<p>    ' 新しく作成された２つ目のサーフェスボディを使い、<br />
    ' 新規にNonParametricBaseFeatureオブジェクトの作成<br />
    Dim non2 As NonParametricBaseFeature<br />
    Set non2 = partDef.Features.NonParametricBaseFeatures.Add(newBody2)<br />
    Set newBody2 = non2.SurfaceBodies.Item(1)<br />
<strong>End Sub</strong></p>

<p>サンプルは <span class="asset  asset-generic at-xid-6a0167607c2431970b017eeadb74ac970d"><a href="http://adndevblog.typepad.com/files/sample1-2.zip">ここ</a></span> よりダウンロードする事ができます。<br />
（解凍後、C:\TempホルダーにInventor2014_J_Ver1.ivbとSamplePart.ipt"を配置し、「ツール」->「アプリケーションオプション」の「ファイル」タブ内「既存のVBAプロジェクト」に「C:\Temp\Inventor2014_J_Ver1.ivb」と設定する事で動作確認ができます）</p>

<p>次回も、引き続きInventor2014製品の API ついてご案内する予定です。<br />
　By Shigekazu Saito.</p>

<p><br />
</p>
