comments:
- author: Anton
  email: anton.van.buiten@betagraphics.nl
  ip: 212.178.65.74
  url: ''
  date: '2012-05-16 07:48:20'
  body: "Although very clear described one question remains:\nHow is the 2Dpoint \"\
    linked\" to the active sketch in the following code fragment.\n\nDim tg As Inventor.TransientGeometry\
    \ = invApp.TransientGeometry\n\n' Draw a line between (0,0) and (4,0).\nDim line1\
    \ As Inventor.SketchLine\nline1 = lines.AddByTwoPoints(tg.CreatePoint2d(0, 0),\
    \ _\n                             tg.CreatePoint2d(4, 0))\n\nI'll assume the active\
    \ sketch supplies the Z-coordinate but how is the tg object linked to the active\
    \ sketch?\n\n\n-----"
