comments:
- author: slachance
  email: SergeLachance@gdpro.qc.ca
  ip: 206.41.84.107
  url: ''
  date: '2017-06-13 01:40:17'
  body: 'hi!


    I''m looking for a ifeatures insert but with x direction and y direction with
    a edge seclection!


    It''s possible???


    ex.: oPatternX = ThisApplication.CommandManager.Pick(SelectionFilterEnum.kPartEdgeFilter,
    "select a X EDGE DIRECTION.")

    oVectorInput.LineInput = oPatternX'
- author: slachance
  email: SergeLachance@gdpro.qc.ca
  ip: 206.41.84.107
  url: ''
  date: '2017-09-12 10:26:54'
  body: 'Hi!


    i try to change the position angle but when i put 1 in oTG.CreateVector my angle
    value is 253 degre??? anf i want 180 degre.


    my code


    Dim oInput As iFeatureInput

    For Each oInput In oiFeatureDef.iFeatureInputs

    Dim oParamInput As iFeatureParameterInput

    Select Case oInput.Name

    Case "Sketch Plane1"

    Dim oPlaneInput As iFeatureSketchPlaneInput

    oPlaneInput = oInput

    oPlaneInput.PlaneInput = oFace

    ''Dim oTG As TransientGeometry

    ''oTG = ThisApplication.TransientGeometry

    ''oPlaneInput.SetPosition(oTG.CreatePoint(0, 0, 0),oTG.CreateVector(1, 0, 0),
    1)

    -----'
