comments:
- author: slachance
  email: SergeLachance@gdpro.qc.ca
  ip: 206.41.84.107
  url: ''
  date: '2017-06-01 09:20:31'
  body: 'Hi!


    I try your vbnet code in ilogic but dont work for me?


    error with sub''s or function!'
- author: slachance
  email: SergeLachance@gdpro.qc.ca
  ip: 206.41.84.107
  url: ''
  date: '2017-06-12 02:10:56'
  body: "it's possible to have a iFeatures edge direction input same to that?\n\n\
    Dim oFace As Face\noFace = ThisApplication.CommandManager.Pick(SelectionFilterEnum.kPartFaceFilter,\
    \ \"SELECTIONNE TON PART\")\nDim oEdgeX As Edge \noEdgeX = ThisApplication.CommandManager.Pick(SelectionFilterEnum.kPartEdgeFilter,\
    \ \"SELECTIONNE TA DIRECTION EN X.\")\nDim oEdgeY As Edge \noEdgeY = ThisApplication.CommandManager.Pick(SelectionFilterEnum.kPartEdgeFilter,\
    \ \"SELECTIONNE TA DIRECTION EN Y.\")\n\nCase \"FACE\"\nDim oPlaneInput As iFeatureSketchPlaneInput\n\
    oPlaneInput = oInput\noPlaneInput.PlaneInput = oFace\nCase \"DIRECTION X\"\nDim\
    \ oEdgeInput As iFeatureSketchEdgeInput\noEdgeInput = oInput\noEdgeInput.EdgeInput\
    \ = oEdgeX\n\n-----"
