comments:
- author: Linh 7cad
  email: linh@7cad-programming.com
  ip: 42.114.221.53
  url: ''
  date: '2017-11-28 18:01:10'
  body: 'Thanks for your code.

    How can I get PointCloudEx API? I downloaded, open it and VS says "the name ''PointCloudEx''
    doesn''t exist in current context"'
- author: Madhukar Moogala
  email: ''
  ip: ''
  url: http://profile.typepad.com/madhukarmoogala
  date: '2017-11-28 19:08:32'
  body: 'Typepad HTML Email





    Thanks for stopping by.

    &nbsp;

    Have your referenced AcDbMgd.dll in your project apart from AcCoreMgd.dll &amp;
    AcMgd.dll.

    Can you put the screenshot of the error, for me to understand.

    &nbsp;

    &nbsp;

    &nbsp;'
- author: Linh 7cad
  email: linh@7cad-programming.com
  ip: 42.114.221.53
  url: ''
  date: '2017-11-28 20:22:05'
  body: OK, I find it out. Got to use AutoCAD 2018 dll. I used to add reference of
    AutoCAD 2013. Thanks.
- author: Thomas Bailey
  email: thomas.bailey@cgiconnect.com
  ip: 208.91.185.36
  url: https://cgiconnect.com/
  date: '2020-01-13 15:08:32'
  body: 'Previewing your Comment


    Thomas Bailey

    Madhukar,


    Thank you for your sample! I know this is an old post, but I have a question hopefully
    you may answer?


    I''m attempting to run your code on a point cloud of my own. I have modified your
    code so that the point cloud in question is selected by the user. This is working.
    What I am confused about is the plane in which the crop is performed. I have tried
    entering different coordinates for these values:


    Point3d crop1_pt1 = new Point3d(-7.0, 12.0, 0);

    Point3d crop1_pt2 = new Point3d(-4.0, 9.0, 0);



    But it appears to be cropping somewhere far outside the bounds of my point cloud.
    I know this because if I invert the cropping, my entire cloud disappears. The
    center of my point cloud is around the coordinates of (0,0,1200). What values
    should I give for the above variables given that my point cloud is up high? Note:
    I tried lowering it down to Z=0 but still could not get it to visibly crop anything.
    I would be more than happy to provide a trimmed down version of the point cloud
    for you to look at. Thank you!'
- author: Amir Ash
  email: a.ashrafi2895@yahoo.com
  ip: 75.102.136.4
  url: ''
  date: '2020-03-30 21:25:52'
  body: 'Hi Madhukar,


    Thank you for your code. I have tested it on my point cloud and the Circular cropping
    works perfectly and I created more than 1000 cropped PCs, however the rectangular
    type which I am looking for doesn''t work at all. I tired to change the code in
    so much ways even updated the Autocad .net core but nothing happens in my point
    cloud. For example when I show/hide or invert the cropped section in the toolbar,
    nothing changed(I mean the whole point cloud doesn''t appear/disappear which means
    nothing was cropped at the first place). I would appreciate it if you could help
    me with this.


    Thank you.'
- author: Madhukar Moogala
  email: ''
  ip: 203.202.234.31
  url: https://profile.typepad.com/madhukarmoogala
  date: '2020-03-30 22:07:07'
  body: "Hi, \n\nIt is important ensure the cropping points fit in cropping boundary,\
    \ were you able to crop to rectangular for the sample in the blog ?"
- author: Madhukar Moogala
  email: ''
  ip: 203.202.234.31
  url: https://profile.typepad.com/madhukarmoogala
  date: '2020-03-30 22:09:07'
  body: "Hi, \n\nFor some reason I did get notification for your post. \n<b>I would\
    \ be more than happy to provide a trimmed down version of the point cloud for\
    \ you to look at.\n</b>\ncan you please do that I will spend sometime this weekend."
- author: Amir Ash
  email: a.ashrafi2895@yahoo.com
  ip: 75.102.136.4
  url: ''
  date: '2020-03-31 09:01:15'
  body: 'Madhukar,


    Thank you for you answer. I am not sure what you mean by fitting in cropping boundary,
    but for your information I passed two points(first upper-left corner point and
    third bottom-right corner point) from the cropping rectangular to the "addcropping"
    function. Also in the function I changed the norm vector to use the top view (0,0,1)
    and it works well for the circular crop but nothing for rectangular.


    I tested the code on my own point cloud not the blog sample.


    Please let me know what you think.


    Thank you,'
- author: Hossam Moussa
  email: hossammoussa2333@gmail.com
  ip: 80.100.70.17
  url: ''
  date: '2021-06-28 05:30:21'
  body: "Hi,\n\nRectangle - first corner point, 2nd, 3rd, 4th and first corner point\
    \ again. \n\nbut you use just two point for the rectangle\nand the normal of the\
    \ crop plan is Y-axis, it has to be Z-axis\n\nI dont understand this ??\ncan you\
    \ help me to beter understanding.\n\nRegards Hossam"
- author: Anh-Tuan NGUYEN
  email: anh-tuan.nguyen@vinci-construction.fr
  ip: 90.3.94.3
  url: ''
  date: '2022-06-18 02:45:23'
  body: 'Hi Madhukar

    Thanks alot for your code, it''s very intersting for me to make un plugin to control
    point cloud for my team. I tried with your code but it made only Circular cropping
    and not Rectangle cropping. Can you tell me what is the error that i made please.

    Best regards

    Anh-Tuan

    -----'
