comments:
- author: Tony Tanzillo
  email: tony.tanzillo@caddzone.com
  ip: 69.115.6.167
  url: http://www.caddzone.com
  date: '2009-01-23 06:06:31'
  body: 'Hi Kean. Kudos on an interesting solution.


    "My ideal would be to have a smooth transition between the 3D views, showing the
    rotation of the model "


    I think the GsView''s Orbit(), Dolly(), Pan(), and ZoomExtents() methods might
    get you there.'
- author: Tony Tanzillo
  email: tony.tanzillo@caddzone.com
  ip: 69.115.6.167
  url: http://www.caddzone.com
  date: '2009-01-23 07:01:36'
  body: BTW, in native ObjectARX there is a class called AcEdSolidSubentitySelector,
    that pretty much takes care of everything related to selecting solid faces.  Unfortunately,
    because it returns an AcArray<AcDbSubentId>, it cannot be easily P/Invoked :(
- author: Kean Walmsley
  email: ''
  ip: 88.85.2.123
  url: http://profile.typekey.com/walmsleyk/
  date: '2009-01-23 10:22:05'
  body: 'On GsView - possibly, although I''m hoping desperately for something simpler...
    :-)


    On AcEdSolidSubentitySelector - yep, I spent a some hours in December trying to
    P/Invoke it but eventually gave up. I suspect the file you linked to from your
    site is probably the cleanest approach we can use from managed code.


    Kean

    -----'
