comments:
- author: Limin
  email: lhe@fmsystems.com
  ip: 96.10.15.122
  url: http://www.fmsystems.com
  date: '2009-12-15 21:00:18'
  body: 'Hi,Kean,


    I''m looking for some sample code in .NET to do something like command "Boundary"
    can do in Autocad command line but having no luck. Is there a way to create a
    boundary using an internal point in .NET?


    Thanks!'
- author: Kean Walmsley
  email: ''
  ip: 88.85.0.178
  url: http://profile.typepad.com/kean
  date: '2009-12-16 09:22:45'
  body: 'Hi Limin,


    Not without calling either the BHATCH or BOUNDARY commands (but we''re very aware
    this is a longstanding requirement).


    Cheers,


    Kean'
- author: Limin
  email: lhe@fmsystems.com
  ip: 96.10.15.122
  url: http://www.fmsystems.com
  date: '2009-12-16 16:22:04'
  body: 'Hi Kean,


    Thanks for the answer to save me time trying to do this in .NET.  But I still
    have some questions if using "Boundary" command.


    1)How to get the object(polyline) created by boundary command?  In VBA, it can
    be found in ThisDrawing.ModelSpace collection, but in .NET, I did not find it
    in Application.DocumentManager.MdiActiveDocument, or there is other approach?


    2)Is there a timing issue? I mean how to prevent .Net code run when "Boundary"
    is still running in command line?'
- author: Kean Walmsley
  email: ''
  ip: 88.85.0.178
  url: http://profile.typepad.com/kean
  date: '2009-12-16 17:13:10'
  body: 'Hi Limin,


    I actually did you a disservice by attempting to answer your question. This really
    isn''t a forum for getting support, and I usually don''t answer handle questions
    this way.


    As an ADN member you should really be contacting <a href="http://adn.autodesk.com">ADN</a>
    support with your question: they''ll be able to share more specific information
    regarding this issue with you.


    Regards,


    Kean'
- author: Limin
  email: lhe@fmsystems.com
  ip: 96.10.15.122
  url: http://www.fmsystems.com
  date: '2009-12-16 18:30:34'
  body: 'Hi,Kean,


    I tried other AutoDesk resource like ADN, .Net discussion forum and find your
    blog is the most helpful and efficient resource. Sorry to use too much of your
    time. I really appreciate your time and help.'
- author: sami
  email: algorythm001@yahoo.com
  ip: 71.249.255.140
  url: ''
  date: '2011-03-10 19:57:55'
  body: 'Hello Kean,

    I am new to Autocad API, so pardon me for this silly question,but i am looking
    for a way to convert splines into polylines. I am working with .NET and objectARX.
    Could you suggest any example which does that?

    Thanks,'
- author: Kean Walmsley
  email: ''
  ip: 80.83.34.178
  url: http://profile.typepad.com/kean
  date: '2011-03-10 21:41:35'
  body: 'Hello Sami,


    Sorry - this isn''t a forum for support, and I really don''t have time to answer
    questions not directly related to my posts.


    Please submit your question to <a href="http://adn.autodesk.com">the ADN team</a>,
    if you''re a member, or otherwise <a href="http://discussion.autodesk.com/forums/forum.jspa?forumID=152">the
    AutoCAD .NET Discussion Group</a>.


    Kean'
- author: sami
  email: algorythm001@yahoo.com
  ip: 71.249.255.140
  url: ''
  date: '2011-03-11 15:57:34'
  body: 'Kean,

    I apologize for any inconvenience this question might have caused you. I am not
    aware of the purpose of this forum as could not find anything specifying that
    it is not meant for support and assumed by looking at other comments that you
    might have some time to guide someone in appropriate direction.

    Thanks.

    Sami'
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/kean
  date: '2011-03-11 16:10:45'
  body: 'Sami,


    Not a problem.


    I get a *lot* of email asking for help, but my "day job" is to manage a worldwide
    team - I barely get enough time to write posts.


    Thanks for understanding,


    Kean'
- author: David
  email: vnsharifi@gmail.com
  ip: 198.91.196.131
  url: ''
  date: '2012-12-12 05:19:49'
  body: "Hello Kean.\nHave a quesiton .\nWhy Can't we add custom scale to none rectangular\
    \ view port ? \nRegards,\nDavid"
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.22
  url: http://profile.typepad.com/kean
  date: '2012-12-12 08:42:10'
  body: 'Hello David,


    This sounds more like a product usage question (which is not really my specialty).
    Please head on over to the online discussion groups and post your question there.


    Regards,


    Kean

    -----'
