comments:
- author: Hasan
  email: hasancad@gmail.com
  ip: 217.54.112.74
  url: ''
  date: '2010-03-22 09:14:08'
  body: "It is not my first to be here but fist time to write a comment.\n\nIts great\
    \ site to learn and to get sources\n\nI have 2 question\n- How can I use those\
    \ codes?\n  is it same as LISP (copy and paset in a new file and change the extention\
    \ to DLL, Or what?\n\nAs I see its some kind of codes using C+, C#, F, etc\nHow\
    \ Do I start learnign this kind or programing?\n\nRegards"
- author: Kean Walmsley
  email: ''
  ip: 219.101.215.2
  url: http://profile.typepad.com/kean
  date: '2010-03-22 10:00:11'
  body: 'Hasan,


    You need to use a tool such as Visual Studio or Visual Basic Express to build
    a DLL or Class Library from the source (copy and pasting the code from this blog
    into the project before building).


    I suggest getting started with these two old posts:


    <a href="http://through-the-interface.typepad.com/through_the_interface/2006/06/getting_started.html">Getting
    started with Autodesk''s APIs</a>

    <a href="http://through-the-interface.typepad.com/through_the_interface/2006/07/getting_started.html">Getting
    started with AutoCAD and .NET</a>


    Regards,


    Kean'
- author: Nithesh
  email: nvrde@rediffmail.com
  ip: 124.124.54.130
  url: ''
  date: '2010-09-14 13:52:42'
  body: 'Hi

    I have to do a project that involves detemining whether the given set lines forms
    a polygon or not .,I tried several times its not working.,can yu pls explain me
    with a code?'
- author: Kean Walmsley
  email: ''
  ip: 132.188.32.100
  url: http://profile.typepad.com/kean
  date: '2010-09-14 13:54:04'
  body: 'No, I cannot. Please post your question to the appropriate Autodesk discussion
    forum.


    Kean'
- author: Abhay Joshi
  email: abhay.y.joshi@gmail.com
  ip: 115.113.144.130
  url: ''
  date: '2010-11-24 16:40:01'
  body: "Hi,\n\nI am working on Custom Entity in ARX. I created Custom entity by deriving\
    \ from AcDbPolyLine. Inheritance hierarchy is as follows.\n\nAcDbPolyLine\n\t\
    CWSPolyLine\n\t\tCWSRoom\n\nI am able to create object of CWSRoom and it is working\
    \ fine.\n\nNow I created class WSPolylineGripOverrule deriving from AcDbGripOverrule\
    \ and implemented getGripPoints() and moveGripPointsAt() . \n\nIn On_kInitAppMsg()\
    \ I added following line of code.\n\nWSPolylineGripOverrule m_pWSPLineOsnapOverrule;\n\
    ASSERT(AcDbGripOverrule::addOverrule(CWSRoom::desc(), &m_pWSPLineOsnapOverrule)\
    \ != RTNORM);\n\nAcDbGripOverrule::setIsOverruling(true);\nbool bRet = AcDbGripOverrule::isOverruling();\n\
    \nSo, it will set overrule at application starup and permanently.\n\nBut after\
    \ creating the CWSRoom object in command, I am not able to see the special behavior\
    \ (additional grips and custom movement). Also it not hitting the break points\
    \ in getGripPoints() and moveGripPointsAt().\n\nCan you tell me what I did incorrect?\
    \ \nIs inheritance is problem? Or I need to add overrule after creating entities.\n\
    \nI need to create this overrule object so in future when I create new custom\
    \ entities that will use same overrule. I donâ€™t need to repeat code in each custom\
    \ entities class."
- author: Kean Walmsley
  email: ''
  ip: 80.83.60.121
  url: http://profile.typepad.com/kean
  date: '2010-11-24 16:50:59'
  body: 'Hi Abhay,


    This isn''t a forum for support.


    Your comment doesn''t appear to relate to this post, so please submit your question
    to <a href="http://adn.autodesk.com">the ADN team</a>, if you''re a member, or
    otherwise <a href="http://discussion.autodesk.com/forums/forum.jspa?forumID=152">the
    AutoCAD .NET Discussion Group</a>.


    Kean'
- author: Jin
  email: ZKP03942011@163.com
  ip: 123.15.57.236
  url: ''
  date: '2012-05-23 07:29:49'
  body: 'Hi Kean,

    I am a fresh man study CAD secondary development using.Now I want to know how
    to chang dimension Style? I check many blog of you,but I can not find it. How
    can I do?

    Regards,


    Looking forward to your reply.Thanks.'
- author: Kean Walmsley
  email: ''
  ip: 95.172.88.5
  url: http://profile.typepad.com/kean
  date: '2012-05-23 11:59:07'
  body: 'Hi Jin,


    I suggest posting your question to the ADN team, if you''re a member, or to the
    AutoCAD .NET Discussion Group.


    Regards,


    Kean'
- author: dharma
  email: mrdharmarajan@gmail.com
  ip: 182.72.175.254
  url: ''
  date: '2014-02-27 05:14:20'
  body: 'Hi Kean,


    Similar to ''DimensionHighlightOverrule'' function, I want to get the bounding
    box detail for dimension text alone. Is there any such option available?'
- author: Kean Walmsley
  email: ''
  ip: 178.197.236.124
  url: http://profile.typepad.com/kean
  date: '2014-02-27 06:33:24'
  body: 'Hi dharma,


    Should be possible. You may need to explode the dimension to collect its text''s
    extents.


    These posts may be of some help:


    <a href="http://through-the-interface.typepad.com/through_the_interface/2012/11/creating-the-smallest-possible-rectangle-around-2d-autocad-geometry-using-net.html">http://through-the-interface.typepad.com/through_the_interface/2012/11/creating-the-smallest-possible-rectangle-around-2d-autocad-geometry-using-net.html</a>

    <a href="http://through-the-interface.typepad.com/through_the_interface/2011/02/creating-the-smallest-possible-circle-around-2d-autocad-geometry-using-net.html">http://through-the-interface.typepad.com/through_the_interface/2011/02/creating-the-smallest-possible-circle-around-2d-autocad-geometry-using-net.html</a>


    Kean'
- author: dharma
  email: mrdharmarajan@gmail.com
  ip: 182.72.175.254
  url: ''
  date: '2014-03-03 08:00:43'
  body: 'Thanks Kean. It works fine :)

    -----'
