---
layout: "post"
title: "Creating a Curved Beam using Revit API"
date: "2012-07-06 15:56:53"
author: "Saikat Bhattacharya"
categories:
  - ".NET"
  - "Revit Architecture"
  - "Revit Structure"
  - "Saikat Bhattacharya"
original_url: "https://adndevblog.typepad.com/aec/2012/07/creating-a-curved-beam-using-revit-api.html "
typepad_basename: "creating-a-curved-beam-using-revit-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/saikat-bhattacharya.html" target="_self">Saikat Bhattacharya</a></p>  <p>Creating a curved beam using the Revit API is quite straightforward – as long as the specific overload of the NewFamilyInstance() method that can create the curved beam is known. For example, it has been commonly seen that using the following overload of the NewFamilyInstance() method:</p>  <p><em>NewFamilyInstance(XYZ, FamilySymbol, StructuralType)</em></p>  <p>does create a beam but attempting to set the LocationCurve.Curve of this beam to be a curve (arc) does not work. The beam created using the specific overload shown above only expects the LocationCurve to be a Line (and not an Arc). </p>  <p>The following code snippet shows one of the simplest ways of creating a curved beam.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Collections.Generic;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Text;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Linq;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.Attributes;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.DB;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.UI;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.UI.Selection;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.ApplicationServices;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">namespace</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Revit.SDK.Samples.HelloRevit.CS</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; [</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000">(</font></span><span style="line-height: 11pt"><font color="#2b91af">TransactionMode</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Manual)]</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">class</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Command</font></span><span style="line-height: 11pt"><font color="#000000"> : </font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#2b91af">IExternalCommand</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Result</font></span><span style="line-height: 11pt"><font color="#000000"> Execute(</font></span><span style="line-height: 11pt"><font color="#2b91af">ExternalCommandData</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> commandData, </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">ref</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">string</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> message, </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">ElementSet</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> elements)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">UIApplication</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> app = commandData.Application;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Document</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> doc = app.ActiveUIDocument.Document;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span><span style="line-height: 11pt"><font color="#000000"> end0 = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(0, 0, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span><span style="line-height: 11pt"><font color="#000000"> end1 = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(10, 10, 10);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span><span style="line-height: 11pt"><font color="#000000"> pointOnCurve = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(10, 0, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Arc</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> arc = app.Application.Create.NewArc(</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; end0, end1, pointOnCurve);</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">FilteredElementCollector</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> coll = </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">FilteredElementCollector</font></span><span style="line-height: 11pt"><font color="#000000">(doc).OfClass(</font></span><span style="line-height: 11pt"><font color="#0000ff">typeof</font></span><span style="line-height: 11pt"><font color="#000000">(</font></span><span style="line-height: 11pt"><font color="#2b91af">Level</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">));</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Level</font></span><span style="line-height: 11pt"><font color="#000000"> lvl = coll.ToElements()[0] </font></span><span style="line-height: 11pt"><font color="#0000ff">as</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Level</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">FilteredElementCollector</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> symbolCollector = </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">FilteredElementCollector</font></span><span style="line-height: 11pt"><font color="#000000">(doc).OfClass(</font></span><span style="line-height: 11pt"><font color="#0000ff">typeof</font></span><span style="line-height: 11pt"><font color="#000000">(</font></span><span style="line-height: 11pt"><font color="#2b91af">FamilySymbol</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">));</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">var</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> targetElems = </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">from</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">FamilySymbol</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> newFamilySymbol </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">in</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> symbolCollector </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">where</font></span><span style="line-height: 11pt"><font color="#000000"> newFamilySymbol.Name.Equals(</font></span><span style="line-height: 11pt"><font color="#a31515">&quot;C15X50&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">) </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">select</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> newFamilySymbol;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">using</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000"> trans = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000">(doc, </font></span><span style="line-height: 11pt"><font color="#a31515">&quot;beam&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">))</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Start();</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">FamilyInstance</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> curvedBeam = </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.FamilyCreate.NewFamilyInstance(</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(0,0,0), </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; targetElems.ElementAt(0), </font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lvl, </font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.DB.Structure.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">StructuralType</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Beam);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">LocationCurve</font></span><span style="line-height: 11pt"><font color="#000000"> locationCurve = curvedBeam.Location </font></span><span style="line-height: 11pt"><font color="#0000ff">as</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">LocationCurve</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; locationCurve.Curve = arc; </font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit();</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; }</font></font></span><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Result</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Succeeded;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></span></p> </div>  <p>The output generated using this simple code is included below – a curved beam, as desired: </p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017616339622970c-pi"><img style="background-image: none; border-bottom: 0px; border-left: 0px; padding-left: 0px; padding-right: 0px; display: block; float: none; margin-left: auto; border-top: 0px; margin-right: auto; border-right: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_394589.jpg" width="325" height="273" /></a></p>
