---
layout: "post"
title: "Accessing MultiViewBlockReference Definition using .NET API"
date: "2012-09-24 14:36:00"
author: "Saikat Bhattacharya"
categories:
  - ".NET"
  - "AutoCAD Architecture"
  - "AutoCAD MEP"
  - "Saikat Bhattacharya"
original_url: "https://adndevblog.typepad.com/aec/2012/09/accessing-multiviewblockreference-definition-using-net-api.html "
typepad_basename: "accessing-multiviewblockreference-definition-using-net-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/saikat-bhattacharya.html">Saikat Bhattacharya</a></p>
<p>This post is to capture a question that was once asked by a partner who wanted to use the AutoCAD MEP .NET API to access the definition of a MultiViewBlockReference. </p>
<p>The definition of a MultiViewBlockReference is infact stored in the Style of the MultiViewBlockReference. Thus, using the StyleId property on a MultiViewBlockReference object, we can access its MultiViewBlockDefinition. The following code snippet shows the approach by accessing the name of the MultiViewBlockDefinition.</p>
<div style="background: white;">
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160; [Autodesk.AutoCAD.Runtime.</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">CommandMethod</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">(</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #a31515;">&quot;TagTest&quot;</span></span><span style="line-height: 11pt;"><span style="color: #000000;">, </span></span><span style="line-height: 11pt;"><span style="color: #2b91af;">CommandFlags</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">.Modal)]</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">public</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">void</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;"> TagTestCmd()</span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;&#0160;&#0160; {</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">Database</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> db = </span></span><span style="line-height: 11pt;"><span style="color: #2b91af;">HostApplicationServices</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">.WorkingDatabase;</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">using</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> (</span></span><span style="line-height: 11pt;"><span style="color: #2b91af;">Transaction</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;"> trans = </span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; db.TransactionManager.StartTransaction())</span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160; {</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">PromptEntityOptions</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;"> peo = </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">new</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span><span style="line-height: 11pt;"><span style="color: #2b91af;">PromptEntityOptions</span></span><span style="line-height: 11pt;"><span style="color: #000000;">(</span></span><span style="line-height: 11pt;"><span style="color: #a31515;">&quot;pick tag&quot;</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">);</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; peo.SetRejectMessage(</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #a31515;">&quot;\nObject must be of type mvblock.&quot;</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">);</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; peo.AddAllowedClass(</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">typeof</span></span><span style="line-height: 11pt;"><span style="color: #000000;">(</span></span><span style="line-height: 11pt;"><span style="color: #2b91af;">MultiViewBlockReference</span></span><span style="line-height: 11pt;"><span style="color: #000000;">), </span></span><span style="line-height: 11pt;"><span style="color: #0000ff;">true</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">);</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Autodesk.AutoCAD.EditorInput.</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">Editor</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;"> ed = </span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; Autodesk.AutoCAD.ApplicationServices</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; .</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">Application</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">.DocumentManager.MdiActiveDocument.Editor;</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">PromptEntityResult</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;"> per = ed.GetEntity(peo);</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">MultiViewBlockReference</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;"> mvbr = </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; trans.GetObject(per.ObjectId, </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">OpenMode</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">.ForRead) </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">as</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span><span style="line-height: 11pt;"><span style="color: #2b91af;">MultiViewBlockReference</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">;</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">MultiViewBlockDefinition</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;"> def = </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; trans.GetObject(mvbr.StyleId, </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">OpenMode</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">.ForRead) </span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #0000ff;">as</span></span><span style="line-height: 11pt;"><span style="color: #000000;"> </span></span><span style="line-height: 11pt;"><span style="color: #2b91af;">MultiViewBlockDefinition</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">;</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="line-height: 11pt;"><span style="color: #000000;"><span style="font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; System.Windows.Forms.</span></span></span><span style="font-size: 8pt;"><span style="line-height: 11pt;"><span style="color: #2b91af;">MessageBox</span></span></span><span style="line-height: 11pt;"><span style="color: #000000; font-size: 8pt;">.Show(def.Name);</span></span></span></p>
<p style="margin: 0px;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;</span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; trans.Commit();</span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;&#0160;&#0160;&#0160;&#0160; }</span></span></span></p>
<p style="margin: 0px;"><span style="line-height: 11pt;"><span style="font-family: Courier New;"><span style="color: #000000; font-size: 8pt;">&#0160;&#0160;&#0160; }</span></span></span></p>
</div>
