---
layout: "post"
title: "Revit model viewer for iOS - part 1"
date: "2012-06-20 10:17:03"
author: "Adam Nagy"
categories:
  - ".NET"
  - "Adam Nagy"
  - "Cloud"
  - "Mobile"
  - "Revit"
original_url: "https://adndevblog.typepad.com/aec/2012/06/revit-model-viewer-for-ios-part-1.html "
typepad_basename: "revit-model-viewer-for-ios-part-1"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/adam-nagy.html" target="_self">Adam Nagy</a></p>
<p>In preparation for our DevCamp&#39;s we looked into what sort of demo applications we could prepare that would show examples of how to take advantage of Cloud and Mobile technologies in context of Autodesk products.</p>
<p>My colleague, <a href="http://adndevblog.typepad.com/autocad/philippe-leefsma.html" target="_self">Philippe</a>, already created an Inventor file viewer for Android, so I had a look at that thinking about writing a similar solution for Revit with a viewer on iOS. His solution includes an Inventor AddIn that can upload Inventor files to a custom web service, which on request from a mobile client can generate the geometrical information from an Inventor file using Inventor Apprentice, and then pass it back to the mobile device that renders the geometry using OpenGL ES.</p>
<p>There will be some differences in our case though:</p>
<ol>
<li>There is no publicly available technology like Inventor Apprentice for Revit, so we&#39;ll have to retrieve the geometry from the model inside the Revit Add-In</li>
<li>The geometry data we get back from Revit is organized differently from Inventor</li>
<li>iOS 5 introduced GLKit, so I was interested in using that instead of solely relying on OpenGL function calls</li>
</ol>
<p>My solution includes the following:</p>
<ol>
<li>A Revit AddIn that gets all the geometrical information (facets) from the model and uploads that to the Cloud - in this case to my Amazon Simple Storage Service (S3) account. Just to keep things simple the format of the data will be proprietary - it will simply contain a list of the coordinates of all the facet triangles. I chose Amazon S3 because this seemed to have really good toolkits for both iOS and .NET, the two platforms I will be using.</li>
<li>An iOS application that accesses the data from the cloud storage and displays it using OpenGL ES</li>
</ol>
<p><strong>The Revit AddIn part</strong></p>
<p>For easy access to the Amazon service I installed the AWS .NET SDK: <a href="http://aws.amazon.com/sdkfornet/" target="_self" title="AWS .NET SDK">http://aws.amazon.com/sdkfornet/</a> <br />Inside my project I just needed to add a reference to <strong>C:\Program&#0160;Files\AWS&#0160;SDK&#0160;for&#0160;.NET\bin\AWSSDK.dll</strong> and then I could start accessing the cloud storage. Here is the function that uploads the data that we gather from the Revit model&#0160;to the storage service&#0160;- you just need to replace <strong>kAccessKey</strong> and <strong>kSecretAccessKey</strong> with your own keys:</p>
<div style="font-family: Courier New; font-size: 8pt; color: black; background: white;">
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Const</span><span style="line-height: 140%;"> kAccessKey </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">String</span><span style="line-height: 140%;"> = </span><span style="color: #a31515; line-height: 140%;">&quot;&quot;</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Const</span><span style="line-height: 140%;"> kSecretAccessKey </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">String</span><span style="line-height: 140%;"> = </span><span style="color: #a31515; line-height: 15px;">&quot;&quot;</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Const</span><span style="line-height: 140%;"> kBucketName </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">String</span><span style="line-height: 140%;"> = </span><span style="color: #a31515; line-height: 140%;">&quot;RevitModelViewer&quot;</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span><span style="line-height: 140%;"> UploadToAmazon(</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> memoryStream </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">MemoryStream</span><span style="line-height: 140%;">) </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Boolean</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Using</span><span style="line-height: 140%;"> client </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">AmazonS3</span><span style="line-height: 140%;"> =</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; Amazon.</span><span style="color: #2b91af; line-height: 140%;">AWSClientFactory</span><span style="line-height: 140%;">.CreateAmazonS3Client(</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; kAccessKey, kSecretAccessKey)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Try</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> bucketRequest </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">PutBucketRequest</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; bucketRequest.WithBucketName(kBucketName)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Using</span><span style="line-height: 140%;"> response </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">S3Response</span><span style="line-height: 140%;"> = client.PutBucket(bucketRequest)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Using</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> objectRequest </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">PutObjectRequest</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; objectRequest.WithBucketName(kBucketName)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; objectRequest.WithInputStream(memoryStream)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; objectRequest.WithKey(mDoc.Title)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Using</span><span style="line-height: 140%;"> response </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">S3Response</span><span style="line-height: 140%;"> = client.PutObject(objectRequest)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Using</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Catch</span><span style="line-height: 140%;"> ex </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">AmazonS3Exception</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">MessageBox</span><span style="line-height: 140%;">.Show(ex.Message, </span><span style="color: #a31515; line-height: 140%;">&quot;Model Uploader&quot;</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Return</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">False</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Try</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Using</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Return</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">True</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span></p>
</div>
<p>Revit SDK already contains a sample that gathers geometrical information from the model and displays it in a custom dialog: <strong>&lt;Revit&#0160;SDK&gt;\Samples\Viewers\ElementViewer</strong>. I modified it to only collect solid geometry and then instead of showing it in our dialog it uploads the data to the cloud storage.</p>
<p>In this case we do not even need the transformation functions since we can simply use the model space coordinates.&#0160;</p>
<p>The geometrical information will be stored on a per face basis as the color can change at that level. Inside each Face section we will list all facets of the face with their coordinates - 3 coordinates and the corresponding normal vector which will be needed by OpenGL. We will calculate the normal vector from the coordinates of the 3 vertices.<br />&gt;&gt;&gt;&gt;&gt;<br />Face;&lt;red&gt;, &lt;green&gt;, &lt;blue&gt;<br />&lt;x1&gt;, &lt;y1&gt;, &lt;z1&gt;;&lt;x2&gt;, &lt;y2&gt;, &lt;z2&gt;;&lt;x3&gt;, &lt;y3&gt;, &lt;z3&gt;;&lt;xn&gt;, &lt;yn&gt;, &lt;zn&gt;<br />etc.<br />&lt;&lt;&lt;&lt;&lt;&#0160;</p>
<div style="font-family: Courier New; font-size: 8pt; color: black; background: white;">
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> mOptions </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Options</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> mApplication _</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> Autodesk.Revit.ApplicationServices.</span><span style="color: #2b91af; line-height: 140%;">Application</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> mSolidCounter </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Long</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> mFaceCounter </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Long</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> mDoc </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Document</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> mFile </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">TextWriter</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Public</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span><span style="line-height: 140%;"> Execute( _</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> commandData </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">ExternalCommandData</span><span style="line-height: 140%;">, </span><span style="color: blue; line-height: 140%;">ByRef</span><span style="line-height: 140%;"> message </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">String</span><span style="line-height: 140%;">, _</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> elements </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">ElementSet</span><span style="line-height: 140%;">) _</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Result</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Implements</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">IExternalCommand</span><span style="line-height: 140%;">.Execute</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: green; line-height: 140%;">&#39; Initialize global variables</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mApplication = commandData.Application.Application</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mDoc = commandData.Application.ActiveUIDocument.Document</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mOptions = _</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; commandData.Application.Application.Create.NewGeometryOptions</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mOptions.DetailLevel = </span><span style="color: #2b91af; line-height: 140%;">ViewDetailLevel</span><span style="line-height: 140%;">.Fine</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mSolidCounter = 0</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mFaceCounter = 0</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: green; line-height: 140%;">&#39; Collect all the solids in the model</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Using</span><span style="line-height: 140%;"> ms </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">MemoryStream</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Using</span><span style="line-height: 140%;"> textFile </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">TextWriter</span><span style="line-height: 140%;"> = </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">StreamWriter</span><span style="line-height: 140%;">(ms)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; mFile = textFile</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">For</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Each</span><span style="line-height: 140%;"> elem </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Element</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">In</span><span style="line-height: 140%;"> GetAllModelElements(mDoc)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; DrawElement(elem)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Next</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; textFile.Flush()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Not</span><span style="line-height: 140%;"> UploadToAmazon(ms) </span><span style="color: blue; line-height: 140%;">Then</span><span style="line-height: 140%;"> mSolidCounter = -1</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Using</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Using</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mApplication = </span><span style="color: blue; line-height: 140%;">Nothing</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: green; line-height: 140%;">&#39; Show result</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> mSolidCounter &gt;= 0 </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: #2b91af; line-height: 140%;">MessageBox</span><span style="line-height: 140%;">.Show(</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;File &quot;&quot;&quot;</span><span style="line-height: 140%;"> + mDoc.Title + </span><span style="color: #a31515; line-height: 140%;">&quot;&quot;&quot; with &quot;</span><span style="line-height: 140%;"> +</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; mSolidCounter.ToString() + </span><span style="color: #a31515; line-height: 140%;">&quot; solids having &quot;</span><span style="line-height: 140%;"> +</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; mFaceCounter.ToString() + </span><span style="color: #a31515; line-height: 140%;">&quot; faces has been uploaded &quot;</span><span style="line-height: 140%;"> +</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;to the Cloud&quot;</span><span style="line-height: 140%;">,</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;Model Uploader&quot;</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Return</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Result</span><span style="line-height: 140%;">.Succeeded</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span><span style="line-height: 140%;"> GetAllModelElements(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> doc </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Document</span><span style="line-height: 140%;">) _</span></p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">IList</span><span style="line-height: 140%;">(</span><span style="color: blue; line-height: 140%;">Of</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Element</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> elements </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">List</span><span style="line-height: 140%;">(</span><span style="color: blue; line-height: 140%;">Of</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Element</span><span style="line-height: 140%;">)()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> collector </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">FilteredElementCollector</span><span style="line-height: 140%;"> = _</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">FilteredElementCollector</span><span style="line-height: 140%;">(doc).WhereElementIsNotElementType()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">For</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Each</span><span style="line-height: 140%;"> e </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Element</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">In</span><span style="line-height: 140%;"> collector</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> e.Category </span><span style="color: blue; line-height: 140%;">IsNot</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Nothing</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; elements.Add(e)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Next</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Return</span><span style="line-height: 140%;"> elements</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> DrawElement(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> elem </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Element</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">TypeOf</span><span style="line-height: 140%;"> elem </span><span style="color: blue; line-height: 140%;">Is</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Group</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> group </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Group</span><span style="line-height: 140%;"> = elem</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> memberIds </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">IList</span><span style="line-height: 140%;">(</span><span style="color: blue; line-height: 140%;">Of</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">ElementId</span><span style="line-height: 140%;">) = group.GetMemberIds()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">For</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Each</span><span style="line-height: 140%;"> id </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">ElementId</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">In</span><span style="line-height: 140%;"> memberIds</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> elm </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Element</span><span style="line-height: 140%;"> = mDoc.GetElement(id)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; DrawElement(elem)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Next</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Else</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> geom </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">GeometryElement</span><span style="line-height: 140%;"> = elem.Geometry(mOptions)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Not</span><span style="line-height: 140%;"> (geom </span><span style="color: blue; line-height: 140%;">Is</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Nothing</span><span style="line-height: 140%;">) </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">&#39; If a family instance then we need the version </span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: green; line-height: 140%;">&#39; that is transformed into the model space</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">TypeOf</span><span style="line-height: 140%;"> elem </span><span style="color: blue; line-height: 140%;">Is</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">FamilyInstance</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Then</span><span style="line-height: 140%;"> geom = _</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; &#0160; geom.GetTransformed(</span><span style="color: #2b91af; line-height: 140%;">Transform</span><span style="line-height: 140%;">.Identity)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; DrawElement(geom)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> DrawElement(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> elementGeom </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">GeometryElement</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> elementGeom </span><span style="color: blue; line-height: 140%;">Is</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Nothing</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Exit Sub</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> geomObject </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">GeometryObject</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">For</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Each</span><span style="line-height: 140%;"> geomObject </span><span style="color: blue; line-height: 140%;">In</span><span style="line-height: 140%;"> elementGeom</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> (</span><span style="color: blue; line-height: 140%;">TypeOf</span><span style="line-height: 140%;"> geomObject </span><span style="color: blue; line-height: 140%;">Is</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">GeometryInstance</span><span style="line-height: 140%;">) </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; DrawInstance(geomObject)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">ElseIf</span><span style="line-height: 140%;"> (</span><span style="color: blue; line-height: 140%;">TypeOf</span><span style="line-height: 140%;"> geomObject </span><span style="color: blue; line-height: 140%;">Is</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Solid</span><span style="line-height: 140%;">) </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; DrawSolid(geomObject)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Next</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> DrawInstance(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> geomInstance </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">GeometryInstance</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> geomSymbol </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">GeometryElement</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; geomSymbol = geomInstance.SymbolGeometry</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Not</span><span style="line-height: 140%;"> (geomSymbol </span><span style="color: blue; line-height: 140%;">Is</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Nothing</span><span style="line-height: 140%;">) </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; DrawElement(geomSymbol)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span><span style="line-height: 140%;"> XyzToString(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> pt </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">XYZ</span><span style="line-height: 140%;">) </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">String</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Return</span><span style="line-height: 140%;"> (</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; pt.X.ToString(</span><span style="color: #2b91af; line-height: 140%;">CultureInfo</span><span style="line-height: 140%;">.InvariantCulture) + </span><span style="color: #a31515; line-height: 140%;">&quot;, &quot;</span><span style="line-height: 140%;"> +</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; pt.Y.ToString(</span><span style="color: #2b91af; line-height: 140%;">CultureInfo</span><span style="line-height: 140%;">.InvariantCulture) + </span><span style="color: #a31515; line-height: 140%;">&quot;, &quot;</span><span style="line-height: 140%;"> +</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; pt.Z.ToString(</span><span style="color: #2b91af; line-height: 140%;">CultureInfo</span><span style="line-height: 140%;">.InvariantCulture))</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Function</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> DrawMesh(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> geomMesh </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Mesh</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> i </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Integer</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">For</span><span style="line-height: 140%;"> i = 0 </span><span style="color: blue; line-height: 140%;">To</span><span style="line-height: 140%;"> geomMesh.NumTriangles - 1</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> triangle </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">MeshTriangle</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; triangle = geomMesh.Triangle(i)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: green; line-height: 140%;">&#39; Calculate normal</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> u </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">XYZ</span><span style="line-height: 140%;"> = triangle.Vertex(1).Subtract(triangle.Vertex(0))</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> v </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">XYZ</span><span style="line-height: 140%;"> = triangle.Vertex(2).Subtract(triangle.Vertex(0))</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> n </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">XYZ</span><span style="line-height: 140%;"> = u.CrossProduct(v).Normalize()</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; mFile.WriteLine(</span><span style="color: #a31515; line-height: 140%;">&quot;{0};{1};{2};{3}&quot;</span><span style="line-height: 140%;">,</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; XyzToString(triangle.Vertex(0)),</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; XyzToString(triangle.Vertex(1)),</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; XyzToString(triangle.Vertex(2)),</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; XyzToString(n))</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Next</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> DrawSolid(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> geomSolid </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Solid</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> geomSolid.Faces.Size &gt; 0 </span><span style="color: blue; line-height: 140%;">Then</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> face </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Face</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">For</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Each</span><span style="line-height: 140%;"> face </span><span style="color: blue; line-height: 140%;">In</span><span style="line-height: 140%;"> geomSolid.Faces</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; &#0160; DrawFace(face)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: blue; line-height: 140%;">Next</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; mSolidCounter += 1</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">If</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">Private</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span><span style="line-height: 140%;"> DrawFace(</span><span style="color: blue; line-height: 140%;">ByVal</span><span style="line-height: 140%;"> geomFace </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Face</span><span style="line-height: 140%;">)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> mat </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Material</span><span style="line-height: 140%;"> = mDoc.GetElement(geomFace.MaterialElementId)</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">Dim</span><span style="line-height: 140%;"> col </span><span style="color: blue; line-height: 140%;">As</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Color</span><span style="line-height: 140%;"> = </span><span style="color: blue; line-height: 140%;">New</span><span style="line-height: 140%;"> </span><span style="color: #2b91af; line-height: 140%;">Color</span><span style="line-height: 140%;">(128, 128, 128)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; </span><span style="color: blue; line-height: 140%;">If</span><span style="line-height: 140%;"> mat </span><span style="color: blue; line-height: 140%;">IsNot</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Nothing</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Then</span><span style="line-height: 140%;"> col = mat.Color</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mFile.WriteLine( _</span></p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; &#0160; </span><span style="color: #a31515; line-height: 140%;">&quot;Face;{0}, {1}, {2}&quot;</span><span style="line-height: 140%;">, col.Red, col.Green, col.Blue)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; DrawMesh(geomFace.Triangulate)</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="line-height: 140%;">&#0160; mFaceCounter += 1</span></p>
<p style="margin: 0px;">&#0160;</p>
<p style="margin: 0px;"><span style="color: blue; line-height: 140%;">End</span><span style="line-height: 140%;"> </span><span style="color: blue; line-height: 140%;">Sub</span></p>
</div>
<p>The Revit AddIn part is done - you can download it from here:&#0160;<span class="asset  asset-generic at-xid-6a0167607c2431970b016767aefd95970b"><a href="http://adndevblog.typepad.com/files/revitmodelviewer---revit-addin---2012-06-19.zip">Download RevitModelViewer - Revit AddIn - 2012-06-19</a></span></p>
<p>Once you compiled the project and set it up according to the readme.txt file so that it gets automatically loaded into Revit, then you can just open up any project and run the command from the Ribbon, Add-Ins tab &gt;&gt; External Tools &gt;&gt; Model Uploader. If the upload succeeds then you&#39;ll see a message like this:</p>
<p><a class="asset-img-link" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017615a617ef970c-pi" style="display: inline;"> </a><a class="asset-img-link" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b016306bd32fa970d-pi" style="display: inline;"><img alt="Modeluploader" class="asset  asset-image at-xid-6a0167607c2431970b016306bd32fa970d" src="/assets/image_271629.jpg" title="Modeluploader" /></a></p>
<p>The AWS .NET SDK also includes a Visual Studio Add-In that makes it quite easy to check the uploaded content:</p>
<p><a class="asset-img-link" href="http://adndevblog.typepad.com/.a/6a0167607c2431970b016767b61541970b-pi" style="display: inline;"><img alt="AWS Explorer" class="asset  asset-image at-xid-6a0167607c2431970b016767b61541970b" src="/assets/image_887131.jpg" title="AWS Explorer" /></a></p>
<p>In the next post we will look at implementing the iOS model viewer application.</p>
