---
layout: "post"
title: "Adding TrimPlanes to Structural Members using ACA .NET API"
date: "2012-12-11 16:01:02"
author: "Saikat Bhattacharya"
categories:
  - ".NET"
  - "AutoCAD Architecture"
  - "Saikat Bhattacharya"
original_url: "https://adndevblog.typepad.com/aec/2012/12/adding-trimplanes-to-structural-members-using-aca-net-api.html "
typepad_basename: "adding-trimplanes-to-structural-members-using-aca-net-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/saikat-bhattacharya.html">Saikat Bhattacharya</a></p>  <p>How can we add TrimPlanes to Structural members using ACA .NET API?</p>  <p>The workflow for creating TrimPlanes and adding them to a Structural member is quite straightforward. The first step is to create an instance of TrimPlane object and assigning the End and Plane property. The code snippet included below creates a TrimPlane for the Start and End point of a column and eventually, sets the newly created TrimPlanes using the member.TrimPlanes property by passing in the collection of the TrimPlanes. </p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> System</font></font><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.AutoCAD.ApplicationServices</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.AutoCAD.DatabaseServices</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.AutoCAD.EditorInput</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.AutoCAD.Runtime</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.AutoCAD.Geometry</font></font><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.Aec.DatabaseServices</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.Aec.PropertyData.DatabaseServices</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Imports</font></font></span><font style="font-size: 8pt" color="#000000"> Autodesk.Aec.Structural.DatabaseServices</font></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">Public</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font><span><font color="#0000ff">Class</font></span><font color="#000000"> Class1</font></font></font><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; &lt;CommandMethod(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;testmemberTrim&quot;</font></span><font color="#000000">)&gt; _</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Public</font></span><font color="#000000"> </font><span><font color="#0000ff">Function</font></span><font color="#000000"> testmemberTrim()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> db </font><span><font color="#0000ff">As</font></span><font color="#000000"> Database = HostApplicationServices.WorkingDatabase</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> tm </font><span><font color="#0000ff">As</font></span><font color="#000000"> Autodesk.AutoCAD.DatabaseServices.TransactionManager = db.TransactionManager</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> trans </font><span><font color="#0000ff">As</font></span><font color="#000000"> Transaction = tm.StartTransaction()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> ed </font><span><font color="#0000ff">As</font></span><font color="#000000"> Editor = Application.DocumentManager.MdiActiveDocument.Editor</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#0000ff">Try</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> member </font><span><font color="#0000ff">As</font></span><font color="#000000"> Member = </font><span><font color="#0000ff">New</font></span><font color="#000000"> Member()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; member.MemberType = MemberType.Column</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; member.SetDatabaseDefaults(db)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; member.SetToStandard(db)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' Set the start and end point of Member in WCS</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; member.Set(</font></font><font style="font-size: 8pt"><span><font color="#0000ff">New</font></span><font color="#000000"> Point3d(0.0, 0.0, 0.0), </font><span><font color="#0000ff">New</font></span><font color="#000000"> Point3d(5000.0, 0.0, 0.0))</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'either get the existing trim planes,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'Autodesk.Aec.DatabaseServices.ImpObjectCollection trimPlanes = member.TrimPlanes;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">'or create a new collection</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> trimPlanes </font><span><font color="#0000ff">As</font></span><font color="#000000"> Autodesk.Aec.DatabaseServices.ImpObjectCollection = </font><span><font color="#0000ff">New</font></span><font color="#000000"> Autodesk.Aec.DatabaseServices.ImpObjectCollection()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' create a trim plane at the start</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> ptOrigin </font><span><font color="#0000ff">As</font></span><font color="#000000"> Point3d = </font><span><font color="#0000ff">New</font></span><font color="#000000"> Point3d(1.0, 1.0, 1.0)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> vec </font><span><font color="#0000ff">As</font></span><font color="#000000"> Vector3d = </font><span><font color="#0000ff">New</font></span><font color="#000000"> Vector3d(1, 0, 0)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> tp1 </font><span><font color="#0000ff">As</font></span><font color="#000000"> TrimPlane = </font><span><font color="#0000ff">New</font></span><font color="#000000"> TrimPlane()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tp1.End = TrimPlaneFrom.Start</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tp1.Plane = </font></font><font style="font-size: 8pt"><span><font color="#0000ff">New</font></span><font color="#000000"> Plane(ptOrigin, vec.GetNormal())</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trimPlanes.Add(tp1)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' create another trim plane at the end</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> tp2 </font><span><font color="#0000ff">As</font></span><font color="#000000"> TrimPlane = </font><span><font color="#0000ff">New</font></span><font color="#000000"> TrimPlane()</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tp2.End = TrimPlaneFrom.End</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; tp2.Plane = </font></font><font style="font-size: 8pt"><span><font color="#0000ff">New</font></span><font color="#000000"> Plane(ptOrigin, vec.GetNormal())</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trimPlanes.Add(tp2)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#008000">' replaces the collection of trim planes on the member</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; member.TrimPlanes = trimPlanes</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> blkTbl </font><span><font color="#0000ff">As</font></span><font color="#000000"> BlockTable = trans.GetObject(db.BlockTableId, OpenMode.ForRead)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">Dim</font></span><font color="#000000"> ms </font><span><font color="#0000ff">As</font></span><font color="#000000"> BlockTableRecord = trans.GetObject(blkTbl(ms.ModelSpace), OpenMode.ForWrite)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; ms.AppendEntity(member)</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.AddNewlyCreatedDBObject(member, </font></font><font style="font-size: 8pt"><span><font color="#0000ff">True</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#0000ff">Catch</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;\nMember creation failed&quot;</font></span><font color="#000000">)</font></font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Abort()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><span><font style="font-size: 8pt" color="#0000ff">Finally</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; MsgBox(</font></font><font style="font-size: 8pt"><span><font color="#a31515">&quot;\nMember created!&quot;</font></span><font color="#000000">)</font></font></font><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Dispose()</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Try</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font><font style="font-size: 8pt"><span><font color="#0000ff">End</font></span><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Function</font></span></font><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span><font color="#0000ff"><font style="font-size: 8pt">End</font></font></span><font style="font-size: 8pt"><font color="#000000"> </font></font><span><font style="font-size: 8pt" color="#0000ff">Class</font></span></font></p> </div>
