---
layout: "post"
title: "Prerequisites for input profiles in NewSweptBlend form creation with Revit API"
date: "2012-05-25 12:34:15"
author: "Saikat Bhattacharya"
categories:
  - ".NET"
  - "Revit"
  - "Saikat Bhattacharya"
original_url: "https://adndevblog.typepad.com/aec/2012/05/prerequisites-for-input-profiles-in-newsweptblend-form-creation-with-revit-api.html "
typepad_basename: "prerequisites-for-input-profiles-in-newsweptblend-form-creation-with-revit-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/saikat-bhattacharya.html" target="_self">Saikat Bhattacharya</a></p>  <p>As the post title explains, in this short post we shall take a look at a not-so-obvious rule for input profiles in the NewSweptBlend method. This is based on one of the queries that we have received from a partner in the recent past. </p>  <p>The following method CreateNewSweptBlend based on the GenericModelCreation SDK sample CreateGenericModel method creates a valid swept blend form: </p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">public</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">void</font></span><span style="line-height: 11pt"><font color="#000000"> CreateNewSweptBlend(</font></span><span style="line-height: 11pt"><font color="#2b91af">Document</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> doc)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> (!doc.IsFamilyDocument)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">TaskDialog</font></span><span style="line-height: 11pt"><font color="#000000">.Show(</font></span><span style="line-height: 11pt"><font color="#a31515">&quot;Error&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;Please run this command in a family document.&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; Autodesk.Revit.ApplicationServices.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Application</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> app = doc.Application;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; Autodesk.Revit.Creation.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Application</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> creapp</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; = app.Create;</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">CurveArrArray</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> curvess0</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; = creapp.NewCurveArrArray();</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">CurveArray</font></span><span style="line-height: 11pt"><font color="#000000"> curves0 = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">CurveArray</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">();</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> p00 = creapp.NewXYZ(0, 7.5, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> p01 = creapp.NewXYZ(0, 15, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// changing Z to 1 in the following line fails:</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> p02 = creapp.NewXYZ(-1, 10, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curves0.Append(creapp.NewLineBound(p00, p01));</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curves0.Append(creapp.NewLineBound(p01, p02));</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curves0.Append(creapp.NewLineBound(p02, p00));</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curvess0.Append(curves0);</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">CurveArrArray</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> curvess1 = creapp.NewCurveArrArray();</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">CurveArray</font></span><span style="line-height: 11pt"><font color="#000000"> curves1 = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">CurveArray</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">();</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> p10 = creapp.NewXYZ(7.5, 0, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> p11 = creapp.NewXYZ(15, 0, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// changing the Z value in the following line fails:</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> p12 = creapp.NewXYZ(10, -1, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curves1.Append(creapp.NewLineBound(p10, p11));</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curves1.Append(creapp.NewLineBound(p11, p12));</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curves1.Append(creapp.NewLineBound(p12, p10));</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; curvess1.Append(curves1);</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">SweepProfile</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> sweepProfile0</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; = creapp.NewCurveLoopsProfile(curvess0);</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">SweepProfile</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> sweepProfile1</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; = creapp.NewCurveLoopsProfile(curvess1);</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span><span style="line-height: 11pt"><font color="#000000"> pnt10 = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(5, 0, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span><span style="line-height: 11pt"><font color="#000000"> pnt11 = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(0, 20, 0);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Curve</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> curve = creapp.NewLineBound(pnt10, pnt11);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span><span style="line-height: 11pt"><font color="#000000"> normal = </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.BasisZ;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">SketchPlane</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> splane = CreateSketchPlane(</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; doc, normal, </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Zero);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">try</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">SweptBlend</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> sweptBlend = doc.FamilyCreate.NewSweptBlend(</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">true</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">, curve, splane, sweepProfile0, sweepProfile1);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">catch</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#2b91af">Exception</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ex)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; Util.ErrorMsg(</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;NewSweptBlend exception: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> + ex.Message);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></span></p> </div>  <div style="font-family: ; background: white">   <p>But if we change the Z coordinate value of points p02 and p12 to 1 instead of 0, it throws an invalid operation exception. Which rule is being broken when I change the Z value of both p02 and p12, please? Does the curve have to be perpendicular to the sweep profiles? </p>    <p>The problem is neither in the user interface nor the API, but simply in the definition of the input curves and the NewSweptBlend method documentation. The Revit API help file RevitAPI.chm states the following requirements for the two input profiles bottomProfile and topProfile: </p>    <ul>     <li>Type: Autodesk.Revit.DB.SweepProfile. </li>      <li>It should consist of only one curve loop. </li>      <li>The input profile must be in one plane. </li>   </ul>    <p>After some research and discussion, we determined that the input profile curve loop must be in the XY plane, implying that the Z coordinates must all be zero. Revit will calculate the profile planes with the input path curve and then transforms the XY plane curve loop to the right profile plane internally. In other words, you need to define the curve profiles to be 2D and located in the XY plane, i.e. set the XYZ input points' Z coordinates to zero. Unfortunately, the documentation does not mention the XY plane, it just states that the curves should be in one plane. Once we set all the Z coordinates to zero, it works fine. </p> </div>
