---
layout: "post"
title: "Moving end points of the slanted column"
date: "2012-06-11 01:37:57"
author: "Katsuaki Takamizawa"
categories:
  - "Katsuaki Takamizawa"
original_url: "https://adndevblog.typepad.com/aec/2012/06/moving-end-points-of-the-slanted-column.html "
typepad_basename: "moving-end-points-of-the-slanted-column"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/katsuaki-takamizawa.html" target="_self">Katsuaki Takamizawa</a></p>  <p>If a column’s “Column Style” parameter is “Slanted”, Location property is a curve defined by LocationCurve class. (it is defined by LocationPoint class if “Vertical”) You can then move the column and/or change the slope by modifying the end points of the curve.</p>  <p>Here is the code extracted from Command.cs in MoveLinear SDK sample.You can do the same thing to change end points of the slanted column.</p>  <p><font face="ＭＳ ゴシック"><span><font color="#0000ff"><font style="font-size: 7.8pt">if</font></font></span><font style="font-size: 7.8pt"><font color="#000000">( element != </font><span><font color="#0000ff">null</font></span></font></font><font style="font-size: 7.8pt"><font face="ＭＳ ゴシック"><font color="#000000"> )          <br />{           <br />&#160; Autodesk.Revit.DB.</font><span><font color="#2b91af">LocationCurve</font></span></font><font face="ＭＳ ゴシック"><font color="#000000"> lineLoc;          <br />&#160; lineLoc = element.Location </font><span><font color="#0000ff">as</font></span><font color="#000000">&#160;</font><span><font color="#2b91af">LocationCurve</font></span></font><font face="ＭＳ ゴシック"><font color="#000000">;          <br />&#160; </font><span><font color="#0000ff">if</font></span><font color="#000000"> (</font><span><font color="#0000ff">null</font></span></font><font face="ＭＳ ゴシック"><font color="#000000"> == lineLoc)          <br />&#160; {           <br />&#160;&#160;&#160; MessageBox.Show(           <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#a31515">&quot;Please select an element which based on a Line&quot;</font></span></font><font face="ＭＳ ゴシック"><font color="#000000">,&#160; <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#a31515">&quot;MoveLinear&quot;</font></span></font><font face="ＭＳ ゴシック"><font color="#000000">);          <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="ＭＳ ゴシック"><font color="#000000"> res;          <br />&#160; }           <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160; Autodesk.Revit.DB.</font><span><font color="#2b91af">Line</font></span></font><font face="ＭＳ ゴシック"><font color="#000000"> line;          <br />&#160; </font><span><font color="#008000">//get start point via &quot;get_EndPoint(0)&quot;</font></span>         <br /><font color="#000000">&#160; Autodesk.Revit.DB.</font><span><font color="#2b91af">XYZ</font></span><font color="#000000"> newStart = </font><span><font color="#0000ff">new</font></span><font color="#000000">&#160;</font><span><font color="#2b91af">XYZ</font></span></font><font face="ＭＳ ゴシック"><font color="#000000">(          <br />&#160;&#160;&#160; lineLoc.Curve.get_EndPoint(0).X + 100,           <br />&#160;&#160;&#160; lineLoc.Curve.get_EndPoint(0).Y,           <br />&#160;&#160;&#160; lineLoc.Curve.get_EndPoint(0).Z);           <br />&#160; </font><span><font color="#008000">//get end point via &quot;get_EndPoint(1)&quot;</font></span>         <br /><font color="#000000">&#160; Autodesk.Revit.DB.</font><span><font color="#2b91af">XYZ</font></span><font color="#000000"> newEnd = </font><span><font color="#0000ff">new</font></span><font color="#000000">&#160;</font><span><font color="#2b91af">XYZ</font></span></font></font><font face="ＭＳ ゴシック"><font style="font-size: 7.8pt"><font color="#000000">(          <br />&#160;&#160;&#160; lineLoc.Curve.get_EndPoint(1).X,           <br />&#160;&#160;&#160; lineLoc.Curve.get_EndPoint(1).Y + 100,           <br />&#160;&#160;&#160; lineLoc.Curve.get_EndPoint(1).Z);           <br />          <br />          <br />&#160; </font><span><font color="#008000">//get a new line and use it to move current element </font></span>        <br /><font color="#000000">&#160; </font><span><font color="#008000">//with property &quot;Autodesk.Revit.DB.LocationCurve.Curve&quot;</font></span>         <br /><font color="#000000">&#160; line = cmdData.Application.Application.          <br />&#160;&#160;&#160; Create.NewLineBound(newStart, newEnd);           <br />&#160; lineLoc.Curve = line;           <br />}</font></font></font></p>
