---
layout: "post"
title: "Adding Radial Dimension to a Circular Column in Edit Extrusion mode using Revit API"
date: "2012-11-09 17:07:41"
author: "Saikat Bhattacharya"
categories:
  - ".NET"
  - "Revit"
  - "Saikat Bhattacharya"
original_url: "https://adndevblog.typepad.com/aec/2012/11/adding-radial-dimension-to-a-circular-column-in-edit-extrusion-mode-using-revit-api.html "
typepad_basename: "adding-radial-dimension-to-a-circular-column-in-edit-extrusion-mode-using-revit-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/saikat-bhattacharya.html">Saikat Bhattacharya</a></p>  <p>This short blog-post shows the use of NewRadialDimension() to create a radial dimension for a circular column in <em>Edit Extrusion</em> mode. This is similar to selecting a circular column in a Revit family in the <em>Edit Extrusion</em> mode using the Revit User Interface (UI). </p>  <p>The code is pretty self-explanatory and simple. To test this, you can create a circular extrusion (say a circular column in the Column.rft template) using the UI and then execute following code:</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Collections.Generic;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Text;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.Attributes;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.DB;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.UI;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">namespace</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Revit.SDK.Samples.HelloRevit.CS</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; [</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000">(</font></span><span style="line-height: 11pt"><font color="#2b91af">TransactionMode</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Manual)]</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">class</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Command</font></span><span style="line-height: 11pt"><font color="#000000"> : </font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#2b91af">IExternalCommand</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Result</font></span><span style="line-height: 11pt"><font color="#000000"> Execute(</font></span><span style="line-height: 11pt"><font color="#2b91af">ExternalCommandData</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> commandData,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">ref</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">string</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> message,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">ElementSet</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> elements)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">UIApplication</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> app = commandData.Application;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Document</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> doc = app.ActiveUIDocument.Document;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Reference</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> extrusionRef = app.ActiveUIDocument.Selection.PickObject(</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.UI.Selection.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">ObjectType</font></span><span style="line-height: 11pt"><font color="#000000">.Element, </font></span><span style="line-height: 11pt"><font color="#a31515">&quot;Select a circular extrusion: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Extrusion</font></span><span style="line-height: 11pt"><font color="#000000"> extr = doc.GetElement(extrusionRef.ElementId) </font></span><span style="line-height: 11pt"><font color="#0000ff">as</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Extrusion</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Sketch</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> skt = extr.Sketch;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Arc</font></span><span style="line-height: 11pt"><font color="#000000"> arc = </font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">foreach</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#2b91af">CurveArray</font></span><span style="line-height: 11pt"><font color="#000000"> curArr </font></span><span style="line-height: 11pt"><font color="#0000ff">in</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> skt.Profile)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">foreach</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#2b91af">Curve</font></span><span style="line-height: 11pt"><font color="#000000"> curve </font></span><span style="line-height: 11pt"><font color="#0000ff">in</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> curArr)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arc = curve </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">as</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Arc</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">break</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"></font></font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">using</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000"> trans = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000">(doc, </font></span><span style="line-height: 11pt"><font color="#a31515">&quot;Radial Dimension&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">))</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Start();</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Dimension</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> radDim =</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.FamilyCreate.NewRadialDimension(</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.ActiveView,</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arc.Reference,</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; arc.Center);</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit();</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Result</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Succeeded;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000"></font></font></p>    <p style="margin: 0px"><font color="#000000">The dimension created can be verified when we click on the Column in the UI and click on the <em>Edit Extrusion</em> button to enter the Edit Extrusion mode. </font></p> </div>
