---
layout: "post"
title: "Inserting a multiple view block instance with associated attributes using OMF"
date: "2012-08-08 19:23:51"
author: "Katsuaki Takamizawa"
categories:
  - "AutoCAD Architecture"
  - "Katsuaki Takamizawa"
  - "OMF"
original_url: "https://adndevblog.typepad.com/aec/2012/08/inserting-a-multiple-view-block-instance-with-associated-attributes.html "
typepad_basename: "inserting-a-multiple-view-block-instance-with-associated-attributes"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/katsuaki-takamizawa.html" target="_self">Katsuaki Takamizawa</a></p>  <p>Issue:</p>  <p>How can I insert a multiple view block instance (AecDbMvBlockRef) with associated attributes using OMF? For example, I'd like to insert a column grid tag and provide a tag number to it.</p>  <p>Solution:</p>  <p>A multiple view block instance (AecDbMvBlockRef) is a display reference to one of the multiple view block definitions (AecDbMvBlockDef) which are stored in the dictionary AecDictMvBlockDef. AecDbMvBlockDef contains many view blocks (AecMvBlockView) which are used by individual display representations for different view directions. Each view block instance (AecMvBlockViewInstance) can contain many multiple view attributes (AecMvBlockAttribute) which are just wrappers of AutoCAD attribute objects (AcDbAttribute). </p>  <p>The appended code demonstrates how to achieve the desired task. This can be easily applied to other multiple block definitions. When you do so, please make sure that the name of multiple view block definition is provided correctly, the number of attributes is checked, proper attribute tags are retrieved from the view block definition, and the attributes and multiple view block reference are updated.</p>  <p>&#160;</p>  <p><font face="Calibri"><font color="#000000">&#160; </font><span><font color="#008000">//&#160; get a multi view block definition. </font></span>      <br /><font color="#000000">&#160; </font><span><font color="#008000">//&#160; for example, &quot;StandardGridBubble&quot;. (We assume we have it defined.)</font></span>       <br /><font color="#000000">&#160; </font><span><font color="#008000">// </font></span>      <br /><font color="#000000">&#160; AecRmCString mvName = </font><span><font color="#a31515">&quot;StandardGridBubble&quot;</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; AcDbObjectId mvBlkDefId;         <br />&#160; AcDbDatabase *pDb = acdbHostApplicationServices()-&gt;workingDatabase();         <br />        <br />&#160; AecDictMvBlockDef mvDict(pDb);         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">( mvDict.isValid() != Adesk::kTrue )        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />        <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">( mvDict.has(mvName) )&#160; <br />&#160;&#160;&#160; mvDict.getAt(mvName, mvBlkDefId);&#160; <br />&#160; </font><span><font color="#0000ff">else</font></span>       <br /><font color="#000000">&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />        <br />&#160; </font><span><font color="#008000">//&#160; create a multi view block reference. </font></span>      <br /><font color="#000000">&#160; </font><span><font color="#008000">// </font></span>      <br /><font color="#000000">&#160; AecDbMvBlockRef* mvBlkRef = </font><span><font color="#0000ff">new</font></span></font><font face="Calibri"><font color="#000000"> AecDbMvBlockRef;&#160; <br />&#160; assert(mvBlkRef != NULL);         <br />&#160; mvBlkRef-&gt;subSetDatabaseDefaults( pDb );         <br />&#160; mvBlkRef-&gt;setToStandard( pDb );         <br />&#160; mvBlkRef-&gt;setBlockDefId(mvBlkDefId);&#160; <br />&#160; mvBlkRef-&gt;setLocation(AcGePoint3d(0,0,0));         <br />&#160; mvBlkRef-&gt;setRotation(0);         <br />&#160; AcGeScale3d scale3d(350);         <br />&#160; mvBlkRef-&gt;setScale(scale3d);         <br />        <br />&#160; </font><span><font color="#008000">//&#160; set the attributes.</font></span>       <br /><font color="#000000">&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">( mvBlkRef-&gt;hasAttributes() )        <br />&#160; {         <br />&#160;&#160;&#160; </font><span><font color="#008000">//&#160; Here we choose the first view instance for the simplicity. </font></span>      <br /><font color="#000000">&#160;&#160;&#160; </font><span><font color="#008000">//&#160; </font></span>      <br /></font><font face="Calibri"><font color="#000000">&#160;&#160;&#160; AecMvBlockViewInstance* blkViewIns = mvBlkRef-&gt;getViewBlockAt(0);&#160; <br />&#160;&#160;&#160; assert(blkViewIns != NULL);         <br />        <br />&#160;&#160;&#160; </font><span><font color="#008000">//&#160; set the &quot;Label&quot; attribute to &quot;A0&quot;. </font></span>      <br /><font color="#000000">&#160;&#160;&#160; </font><span><font color="#0000ff">int</font></span></font><font face="Calibri"><font color="#000000"> indexFoundAt;        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">if</font></span><font color="#000000">( blkViewIns-&gt;findAttribute(_DNT(</font><span><font color="#a31515">&quot;LABEL&quot;</font></span></font><font face="Calibri"><font color="#000000">), indexFoundAt)==Adesk::kTrue )        <br />&#160;&#160;&#160; {         <br />&#160;&#160;&#160;&#160;&#160; AecMvBlockAttribute *mvBlkAtt;         <br />&#160;&#160;&#160;&#160;&#160; AcDbAttribute *acadAtt;         <br />&#160;&#160;&#160;&#160;&#160; mvBlkAtt = blkViewIns-&gt;getAttributeAt(indexFoundAt);         <br />&#160;&#160;&#160;&#160;&#160; assert(mvBlkAtt != NULL);         <br />&#160;&#160;&#160;&#160;&#160; acadAtt = mvBlkAtt-&gt;attributeForWrite( );         <br />&#160;&#160;&#160;&#160;&#160; assert(acadAtt != NULL);         <br />&#160;&#160;&#160;&#160;&#160; acadAtt-&gt;setTextString(_DNT(</font><span><font color="#a31515">&quot;A0&quot;</font></span><font color="#000000">));        <br />&#160;&#160;&#160;&#160;&#160; acadAtt-&gt;close();         <br />&#160;&#160;&#160;&#160;&#160; mvBlkAtt-&gt;setNeedsUpdate(Adesk::kTrue);         <br />&#160;&#160;&#160; }         <br />&#160; }         <br />        <br />&#160; mvBlkRef-&gt;updateViewBlocks();&#160; <br />        <br />&#160; Aec::transformToWcs(mvBlkRef, pDb);&#160; <br />&#160; Aec::addToCurrentSpaceAndClose(mvBlkRef); </font></font></p>  <pre style="line-height: normal; font-family: ; background: white"><font color="#000000" face="Calibri"></font></pre>
