---
layout: "post"
title: "Adding a property definition to a property set definition using OMF"
date: "2012-08-08 02:18:52"
author: "Katsuaki Takamizawa"
categories:
  - "AutoCAD Architecture"
  - "Katsuaki Takamizawa"
  - "OMF"
original_url: "https://adndevblog.typepad.com/aec/2012/08/adding-a-property-definition-to-a-property-set-definition-using-omf.html "
typepad_basename: "adding-a-property-definition-to-a-property-set-definition-using-omf"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/katsuaki-takamizawa.html" target="_self">Katsuaki Takamizawa</a></p>  <p>Issue:</p>  <p>How to add a property definition to a property set definition using OMF?</p>  <p>Solution:</p>  <p>You can access to a property set definition stored in the dictionary &quot;AEC_PROPERTY_SET_DEFS&quot; under AutoCAD Named Object Dictionary) and add a property definition. The following code shows how to do it. This code finds property sets attached to a door and finds definitions. Please set a least one door property set to the door before testing the code. The code adds a property definition “Area” and then sets the value of 15.98.</p>  <p>&#160;</p>  <p><font face="Calibri"><font color="#000000">&#160; </font><span><font color="#008000">// get working database </font></span>      <br /></font><font face="Calibri"><font color="#000000">&#160; AcDbDatabase *pCurDb = acdbHostApplicationServices()-&gt;workingDatabase();        <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(pCurDb == NULL)        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />        <br />&#160; </font><span><font color="#008000">// select a door </font></span>      <br /><font color="#000000">&#160; AecUiPrEntity promptEnt(_T(</font><span><font color="#a31515">&quot;Select a door&quot;</font></span></font><font face="Calibri"><font color="#000000">), NULL);        <br />&#160; promptEnt.addAllowedClass(AecDbDoor::desc());         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(promptEnt.go() != AecUiPr::kOk)        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nAborting command...&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; }         <br />        <br />&#160; </font><span><font color="#008000">// open the door for read </font></span>      <br /></font><font face="Calibri"><font color="#000000">&#160; Acad::ErrorStatus es;        <br />&#160; AecDbDoor *pEnt;         <br />&#160; es = AecDbDoor::open(pEnt, promptEnt.objectId(), AcDb::kForRead);         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(es != Acad::eOk)        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nCan not open the Door entity.&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; }         <br />        <br />&#160; AcDbObjectId propSetDefId, propSetId;         <br />&#160; AecDbPropertySet* propSet;         <br />&#160; Adesk::UInt32 propId;         <br />        <br />&#160; </font><span><font color="#008000">// get property sets from extension dictionary of the selected door </font></span>      <br /></font><font face="Calibri"><font color="#000000">&#160; AcDbObjectIdArray propSetIds;        <br />&#160; es = AecDbPropertySet::getPropertySets( (AcDbObject*) pEnt, propSetIds);         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(es != Acad::eOk)        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nThere are no property sets in this AEC entity.&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; pEnt-&gt;close();         <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; }         <br />&#160; pEnt-&gt;close();         <br />        <br />&#160; </font><span><font color="#008000">// iterate through all the property sets </font></span>      <br /><font color="#000000">&#160; </font><span><font color="#0000ff">for</font></span><font color="#000000">(</font><span><font color="#0000ff">int</font></span></font><font face="Calibri"><font color="#000000"> iPropSet=0; iPropSet &lt; propSetIds.length(); iPropSet++) {        <br />&#160;&#160;&#160; </font><span><font color="#008000">// get property set object </font></span>      <br /></font><font face="Calibri"><font color="#000000">&#160;&#160;&#160; AecDbPropertySet *propSet = NULL;        <br />&#160;&#160;&#160; AecDbPropertySet::open( propSet, propSetIds[iPropSet], AcDb::kForRead);         <br />        <br />&#160;&#160;&#160; AcDbObjectId propSetDefId = propSet-&gt;propertySetDef();         <br />&#160;&#160;&#160; propSet-&gt;close();         <br />        <br />&#160;&#160;&#160; AecDbPropertySetDef* propSetDef;         <br />&#160;&#160;&#160; es = AecDbPropertySetDef::open(propSetDef, propSetDefId, AcDb::kForWrite);         <br />        <br />&#160;&#160;&#160; </font><span><font color="#008000">// Add a propertydef to propertyset def </font></span>      <br /><font color="#000000">&#160;&#160;&#160; </font><span><font color="#008000">// Create property </font></span>      <br /><font color="#000000">&#160;&#160;&#160; AecPropertyDef* pdefArea = </font><span><font color="#0000ff">new</font></span></font><font face="Calibri"><font color="#000000"> AecPropertyDef;        <br />&#160;&#160;&#160; pdefArea-&gt;subSetDatabaseDefaults ( pCurDb) ;         <br />        <br />&#160;&#160;&#160; es = pdefArea-&gt;setName(_T(</font><span><font color="#a31515">&quot;Area&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; es = pdefArea-&gt;setAutomatic (</font><span><font color="#0000ff">false</font></span></font><font face="Calibri"><font color="#000000">);        <br />&#160;&#160;&#160; es = pdefArea-&gt;setDataType (AecPropertyDef::kReal );         <br />        <br />&#160;&#160;&#160; </font><span><font color="#008000">// Add to Property Set </font></span>      <br /></font><font face="Calibri"><font color="#000000">&#160;&#160;&#160; es = propSetDef-&gt;addPropertyDef(pdefArea);        <br />        <br />&#160;&#160;&#160; propSetDef-&gt;close();         <br />        <br />&#160;&#160;&#160; </font><span><font color="#008000">// Open again to make modifications </font></span>      <br /></font><font face="Calibri"><font color="#000000">&#160;&#160;&#160; es = AecDbPropertySet::open(propSet, propSetIds[iPropSet], AcDb::kForWrite);        <br />&#160;&#160;&#160; es = propSet-&gt;propertyNameToId(_T(</font><span><font color="#a31515">&quot;Area&quot;</font></span><font color="#000000">), propId);        <br />&#160;&#160;&#160; es = propSet-&gt;setAt(propId, 15.98);         <br />        <br />&#160;&#160;&#160; propSet-&gt;close();         <br />&#160; } </font></font></p>  <pre style="line-height: normal; font-family: ; background: white">&#160;</pre>

<pre style="line-height: normal; font-family: ; background: white"><font color="#000000" face="Calibri"></font></pre>

<pre style="line-height: normal; font-family: ; background: white"><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b017743fdf56c970d-pi"><img style="border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="DoorObjectProperty" border="0" alt="DoorObjectProperty" src="/assets/image_138379.jpg" width="244" height="211" /></a></pre>
