---
layout: "post"
title: "Why does AecGeRing.isValidRing return False?"
date: "2012-11-07 22:14:00"
author: "Saikat Bhattacharya"
categories:
  - ".NET"
  - "AutoCAD Architecture"
  - "Saikat Bhattacharya"
original_url: "https://adndevblog.typepad.com/aec/2012/11/why-does-aecgeringisvalidring-return-false.html "
typepad_basename: "why-does-aecgeringisvalidring-return-false"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/saikat-bhattacharya.html">Saikat Bhattacharya</a></p>  <p>A simple DWG containing a simple closed pline when converted to an AecGeRing, reports that the ring is not Valid. Why? The pline looks perfectly fine!</p>  <p>Even though to a polyline might look fine, there might be some disjoin somewhere which might be causing this. To avoid this unwanted behavior, we can use the JoinColinearSegments() method to fix any such disjoin problems. After using this method, the same polyline now returns <em>IsValidRing</em> value to be True. Here is the complete code which shows how use this API (which includes code to convert a polyline to a Ring):</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Editor</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> mEditor;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Database</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> mDb;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; Autodesk.AutoCAD.DatabaseServices.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">TransactionManager</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> mTransMgr;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> mTrans;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; [</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">CommandMethod</font></span><span style="line-height: 11pt"><font color="#000000">(</font></span><span style="line-height: 11pt"><font color="#a31515">&quot;Ring&quot;</font></span><span style="line-height: 11pt"><font color="#000000">, Autodesk.AutoCAD.Runtime.</font></span><span style="line-height: 11pt"><font color="#2b91af">CommandFlags</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Modal)]</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">void</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Ring()</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; mEditor = </font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">AcadApp</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.DocumentManager.MdiActiveDocument.Editor;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; mDb = </font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">AcadApp</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.DocumentManager.MdiActiveDocument.Database;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; mTransMgr = </font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">AcadApp</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.DocumentManager.MdiActiveDocument.TransactionManager;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// start the transaction</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; mTrans = mTransMgr.StartTransaction();</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">try</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">PromptEntityOptions</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> prOptions = </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">PromptEntityOptions</font></span><span style="line-height: 11pt"><font color="#000000">(</font></span><span style="line-height: 11pt"><font color="#a31515">&quot;\nSelect polyline to modify: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; prOptions.SetRejectMessage(</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nObject must be of type Polyline.&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; prOptions.AddAllowedClass(</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">typeof</font></span><span style="line-height: 11pt"><font color="#000000">(Autodesk.AutoCAD.DatabaseServices.</font></span><span style="line-height: 11pt"><font color="#2b91af">Polyline</font></span><span style="line-height: 11pt"><font color="#000000">), </font></span><span style="line-height: 11pt"><font color="#0000ff">true</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// prompt the user to select a polyline</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">PromptEntityResult</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> prResult = mEditor.GetEntity(prOptions);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// get the ObjectId from the selected polyline </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.DatabaseServices.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">ObjectId</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> oidSelected = </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; prResult.ObjectId;</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// open the polyline for Write based on the objectId</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; Autodesk.AutoCAD.DatabaseServices.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Polyline</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> polyline = </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; (Autodesk.AutoCAD.DatabaseServices.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Polyline</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)mTransMgr.GetObject(</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; oidSelected, </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">OpenMode</font></span><span style="line-height: 11pt"><font color="#000000">.ForWrite, </font></span><span style="line-height: 11pt"><font color="#0000ff">false</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; Autodesk.Aec.Geometry.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Ring</font></span><span style="line-height: 11pt"><font color="#000000"> ring = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> Autodesk.Aec.Geometry.</font></span><span style="line-height: 11pt"><font color="#2b91af">Ring</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">();</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; ring.SubSetDatabaseDefaults(mDb);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; ring.SetToStandard(mDb);</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; ring.AddSegmentsFrom(polyline, </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">true</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; ring.JoinColinearSegments();</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; mEditor.WriteMessage(</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nIs a Valid Ring: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; + ring.IsValidRing.ToString());</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; mEditor.WriteMessage(</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;\nIs a Self Intersecting: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; + ring.IsSelfIntersecting.ToString());</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">catch</font></span><span style="line-height: 11pt"><font color="#000000"> (System.</font></span><span style="line-height: 11pt"><font color="#2b91af">Exception</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> ex)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; mEditor.WriteMessage(ex.Message);</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">finally</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000">// Commit the transaction</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; mTrans.Commit();</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font color="#000000" face="Courier New"></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font color="#000000" face="Courier New"></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font color="#000000">And here is the output:</font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"></span></p>    <p><font face="Courier New">Command: ring</font></p>    <p><font face="Courier New">Select polyline to modify:</font></p>    <p><font face="Courier New">Is a Valid Ring: True</font></p>    <p><font face="Courier New">Is a Self Intersecting: False</font></p> </div>
