---
layout: "post"
title: "Creating dimensions"
date: "2012-06-17 23:37:37"
author: "Katsuaki Takamizawa"
categories:
  - "Katsuaki Takamizawa"
original_url: "https://adndevblog.typepad.com/aec/2012/06/creating-dimensions.html "
typepad_basename: "creating-dimensions"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/katsuaki-takamizawa.html" target="_self">Katsuaki Takamizawa</a></p>  <p>We have CreateDimensions SDK sample. This sample shows you how to create dimensions by simplifying the part of finding geometry references from the analytical line of a wall. However, the sample does not work in Revit 2013 (and 2012) since it has not incorporated the change. The geometries of the analytical model have to be accessed from the analytical model of each element.</p>  <p>If you replace the part of Command.cs in the sample with the following code, the sample will find the geometries from the analytical mode and creates the dimension.    <br /></p>  <p><font size="1"><font color="#000000">&#160; </font><span><font color="#008000">//get out all the walls in this array, and create a dimension from its start to its end</font></span>       <br /><font color="#000000">&#160; </font><span><font color="#0000ff">for</font></span><font color="#000000"> (</font><span><font color="#0000ff">int</font></span></font><font size="1"><font color="#000000"> i = 0; i &lt; m_walls.Count; i++)        <br />&#160; {         <br />&#160;&#160;&#160;&#160;&#160; Wall wallTemp = m_walls[i] </font><span><font color="#0000ff">as</font></span></font><font size="1"><font color="#000000"> Wall;        <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">if</font></span><font color="#000000"> (</font><span><font color="#0000ff">null</font></span></font><font size="1"><font color="#000000"> == wallTemp)        <br />&#160;&#160;&#160;&#160;&#160; {         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">continue</font></span></font><font size="1"><font color="#000000">;        <br />&#160;&#160;&#160;&#160;&#160; }         <br />        <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#008000">//get location curve</font></span>       <br /></font><font size="1"><font color="#000000">&#160;&#160;&#160;&#160;&#160; Location location = wallTemp.Location;        <br />&#160;&#160;&#160;&#160;&#160; LocationCurve locationline = location </font><span><font color="#0000ff">as</font></span></font><font size="1"><font color="#000000"> LocationCurve;        <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">if</font></span><font color="#000000"> (</font><span><font color="#0000ff">null</font></span></font><font size="1"><font color="#000000"> == locationline)        <br />&#160;&#160;&#160;&#160;&#160; {         <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">continue</font></span></font><font size="1"><font color="#000000">;        <br />&#160;&#160;&#160;&#160;&#160; }         <br />        <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#008000">//New Line</font></span>       <br /></font><font size="1"><font color="#000000">       <br />&#160;&#160;&#160;&#160;&#160; Line newLine = </font><span><font color="#0000ff">null</font></span></font><font size="1"><font color="#000000">;        <br />        <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#008000">//get reference</font></span>       <br /><font color="#000000">&#160;&#160;&#160;&#160;&#160; ReferenceArray referenceArray = </font><span><font color="#0000ff">new</font></span></font><font size="1"><font color="#000000"> ReferenceArray();        <br />        <br />&#160;&#160;&#160;&#160;&#160; AnalyticalModel analyticalModel = wallTemp.GetAnalyticalModel();         <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#2b91af">IList</font></span></font><font size="1"><font color="#000000">&lt;Curve&gt; activeCurveList =&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; analyticalModel.GetCurves(         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; AnalyticalCurveType.ActiveCurves);         <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">foreach</font></span><font color="#000000"> (Curve aCurve </font><span><font color="#0000ff">in</font></span></font><font size="1"><font color="#000000"> activeCurveList)        <br />&#160;&#160;&#160;&#160;&#160; {         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#008000">// find non-vertical curve from analytical model</font></span>       <br /><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">if</font></span></font><font size="1"><font color="#000000"> (aCurve.GetEndPoint(0).Z ==&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aCurve.GetEndPoint(1).Z)         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLine = aCurve </font><span><font color="#0000ff">as</font></span></font><font size="1"><font color="#000000"> Line;        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">if</font></span></font><font size="1"><font color="#000000"> (aCurve.GetEndPoint(0).Z !=&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; aCurve.GetEndPoint(1).Z)         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; {         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AnalyticalModelSelector amSelector =&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">new</font></span></font><font size="1"><font color="#000000"> AnalyticalModelSelector(aCurve);        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; amSelector.CurveSelector =&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; AnalyticalCurveSelector.StartPoint;         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; referenceArray.Append(         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; analyticalModel.GetReference(amSelector));         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; }         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">if</font></span></font><font size="1"><font color="#000000"> (2 == referenceArray.Size)        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">break</font></span></font><font size="1"><font color="#000000">;        <br />&#160;&#160;&#160;&#160;&#160; }         <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">if</font></span></font><font size="1"><font color="#000000"> (referenceArray.Size != 2)        <br />&#160;&#160;&#160;&#160;&#160; {         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_errorMessage += </font><span><font color="#a31515">&quot;Did not find two references&quot;</font></span></font><font size="1"><font color="#000000">;        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span><font color="#000000">&#160;</font><span><font color="#0000ff">false</font></span></font><font size="1"><font color="#000000">;        <br />&#160;&#160;&#160;&#160;&#160; }         <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">try</font></span>       <br /></font><font size="1"><font color="#000000">&#160;&#160;&#160;&#160;&#160; {        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#008000">//try to add new a dimension</font></span>       <br /></font><font size="1"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.UI.UIApplication app =&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_revit.Application;         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Document doc = app.ActiveUIDocument.Document;         <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.DB.XYZ p1 = </font><span><font color="#0000ff">new</font></span></font><font size="1"><font color="#000000"> XYZ(        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLine.get_EndPoint(0).X + 5,         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLine.get_EndPoint(0).Y + 5,         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLine.get_EndPoint(0).Z);         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.DB.XYZ p2 = </font><span><font color="#0000ff">new</font></span></font><font size="1"><font color="#000000"> XYZ(        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLine.get_EndPoint(1).X + 5,         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLine.get_EndPoint(1).Y + 5,         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; newLine.get_EndPoint(1).Z);         <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Line newLine2 = app.Application.Create.         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; NewLine(p1, p2, </font><span><font color="#0000ff">true</font></span></font><font size="1"><font color="#000000">);        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; Dimension newDimension = doc.Create.NewDimension(         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.ActiveView, newLine2, referenceArray);         <br />&#160;&#160;&#160; }         <br />&#160;&#160;&#160;&#160;&#160; </font><span><font color="#008000">// catch the exceptions</font></span>       <br /><font color="#000000">&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">catch</font></span><font color="#000000"> (</font><span><font color="#2b91af">Exception</font></span></font><font size="1"><font color="#000000"> ex)        <br />&#160;&#160;&#160;&#160;&#160; {         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; m_errorMessage += ex.ToString();         <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span><font color="#000000">&#160;</font><span><font color="#0000ff">false</font></span></font><font color="#000000" size="1">;      <br />&#160;&#160;&#160;&#160;&#160; }       <br />&#160; }       <br /></font></p>  <p>Please do not confused with this sample. You can create dimension for elements not in the analytical model, of course. The most difficult part is to find geometry references which you want to attach the dimension. Thanks to Jeremy that his API blogs introduce how to find geometry references with some typical use cases.</p>  <p><a href="http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-by-iterating-faces.html">http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-by-iterating-faces.html</a>     <br /><a href="http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-using-findreferencesbydirection.html">http://thebuildingcoder.typepad.com/blog/2011/02/dimension-walls-using-findreferencesbydirection.html</a></p>  <p>Please note that currently geometry references can not be found in symbolic lines using API while they can be dimensioned using UI.</p>  <p><font color="#000000" size="1"></font></p>
