---
layout: "post"
title: "Picking 3D points using Revit API"
date: "2012-05-30 15:39:16"
author: "Saikat Bhattacharya"
categories:
  - ".NET"
  - "Revit"
  - "Saikat Bhattacharya"
original_url: "https://adndevblog.typepad.com/aec/2012/05/picking-3d-points-using-revit-api.html "
typepad_basename: "picking-3d-points-using-revit-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/saikat-bhattacharya.html" target="_self">Saikat Bhattacharya</a></p>  <p>Many of our partners and API users have often wondering how we can possibly make use of the Revit API to prompt users to pick 3D points. As all who have worked with Revit API are aware, the Selection.PickPoint() is only limited to points on the active 2D workplane. </p>  <p>The solution to this is to set the work plane using the View.SketchPlane property and then use the Selection.PickPoint() method on that workplane. The code below shows how to set an active sketch plane for a view which allows us to select points in 3D.</p>  <div style="font-family: ; background: white">   <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Collections.Generic;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Text;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.DB;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.UI;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Autodesk.Revit.ApplicationServices;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">using</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> System.Linq;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#0000ff"><font style="font-size: 8pt">namespace</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> Select3DPoint</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">{</font></font></span><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; [Autodesk.Revit.Attributes.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000">(Autodesk.Revit.Attributes.</font></span><span style="line-height: 11pt"><font color="#2b91af">TransactionMode</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Manual)]</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">class</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Command</font></span><span style="line-height: 11pt"><font color="#000000"> : </font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#2b91af">IExternalCommand</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; {&#160;&#160;&#160;&#160;&#160; </font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> Autodesk.Revit.UI.</font></span><span style="line-height: 11pt"><font color="#2b91af">Result</font></span><span style="line-height: 11pt"><font color="#000000"> Execute(</font></span><span style="line-height: 11pt"><font color="#2b91af">ExternalCommandData</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> commandData,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">ref</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">string</font></span><span style="line-height: 11pt"><font color="#000000"> message, Autodesk.Revit.DB.</font></span><span style="line-height: 11pt"><font color="#2b91af">ElementSet</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> elements)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">UIApplication</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> uiapp = commandData.Application;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">UIDocument</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> uidoc = uiapp.ActiveUIDocument;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Application</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> app = uiapp.Application;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Document</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> doc = uidoc.Document;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> point_in_3d;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span><span style="line-height: 11pt"><font color="#000000"> (SetWorkPlaneAndPickObject(uidoc, </font></span><span style="line-height: 11pt"><font color="#0000ff">out</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> point_in_3d))</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">TaskDialog</font></span><span style="line-height: 11pt"><font color="#000000">.Show(</font></span><span style="line-height: 11pt"><font color="#a31515">&quot;3D Point Selected&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#a31515">&quot;3D point picked on the plane&quot;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#a31515">&quot; defined by the selected face: &quot;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;X: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> + point_in_3d.X.ToString() </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;, Y: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> + point_in_3d.Y.ToString() </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;, Z: &quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> + point_in_3d.Z.ToString());</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Result</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Succeeded;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">else</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; message = </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;3D point selection failed&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Result</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Failed;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#808080">///</font></span><span style="line-height: 11pt"><font color="#008000"> </font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#808080">&lt;summary&gt;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#808080">///</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000"> Return a 3D point. First, the user is prompted </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#808080">///</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000"> to pick a face on an element. This defines a </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#808080">///</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000"> work plane, on which a second point can be </font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#808080">///</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#008000"> picked.</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#808080">///</font></span><span style="line-height: 11pt"><font color="#008000"> </font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#808080">&lt;/summary&gt;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">public</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">bool</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> SetWorkPlaneAndPickObject(</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">UIDocument</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> uidoc,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">out</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">XYZ</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> point_in_3d)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; point_in_3d = </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"></font></font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Document</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> doc = uidoc.Document;</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Reference</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> r = uidoc.Selection.PickObject(</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.UI.Selection.</font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">ObjectType</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">.Face,</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot;Please select a planar face to define work plane&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt"></font></font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Element</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> e = doc.GetElement(r.ElementId);</font></span></font><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> != e)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">PlanarFace</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> face = e.GetGeometryObjectFromReference(r)</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">as</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">PlanarFace</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">GeometryElement</font></span><span style="line-height: 11pt"><font color="#000000"> geoEle = e.get_Geometry(</font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Options</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">());</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Transform</font></span><span style="line-height: 11pt"><font color="#000000"> transform = </font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">foreach</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#2b91af">GeometryObject</font></span><span style="line-height: 11pt"><font color="#000000"> gObj </font></span><span style="line-height: 11pt"><font color="#0000ff">in</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> geoEle.Objects)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">GeometryInstance</font></span><span style="line-height: 11pt"><font color="#000000"> gInst = gObj </font></span><span style="line-height: 11pt"><font color="#0000ff">as</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">GeometryInstance</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> != gInst)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; transform = gInst.Transform;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span><span style="line-height: 11pt"><font color="#000000"> (face != </font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Plane</font></span><span style="line-height: 11pt"><font color="#000000"> plane = </font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">if</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> != transform)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plane = </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Plane</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(transform.OfVector(face.Normal), </font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; transform.OfPoint(face.Origin));</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">else</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plane = </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Plane</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(face.Normal, face.Origin);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span><span style="line-height: 11pt"><font color="#000000"> t = </font></span><span style="line-height: 11pt"><font color="#0000ff">new</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#2b91af">Transaction</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">(doc);</font></span></font></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; t.Start(</font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#a31515">&quot;Temporarily set work plane&quot;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot; to pick point in 3D&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;</font></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#2b91af">SketchPlane</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> sp = doc.Create.NewSketchPlane(</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plane);</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; uidoc.ActiveView.SketchPlane = sp;</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; uidoc.ActiveView.ShowActiveWorkPlane();</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#0000ff">try</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; point_in_3d = uidoc.Selection.PickPoint(</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><span style="line-height: 11pt"><font style="font-size: 8pt" color="#a31515">&quot;Please pick a point on the plane&quot;</font></span></font></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#a31515">&quot; defined by the selected face&quot;</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">);</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">catch</font></span><span style="line-height: 11pt"><font color="#000000"> (</font></span><span style="line-height: 11pt"><font color="#2b91af">OperationCanceledException</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000">)</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; t.RollBack();</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><font face="Courier New"><span style="line-height: 11pt"><font color="#000000"><font style="font-size: 8pt">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font></font></span><font style="font-size: 8pt"><span style="line-height: 11pt"><font color="#0000ff">return</font></span><span style="line-height: 11pt"><font color="#000000"> </font></span><span style="line-height: 11pt"><font color="#0000ff">null</font></span></font><span style="line-height: 11pt"><font style="font-size: 8pt" color="#000000"> != point_in_3d;</font></span></font></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">&#160;&#160;&#160; }</font></font></span></p>    <p style="margin: 0px"><span style="line-height: 11pt"><font face="Courier New"><font style="font-size: 8pt" color="#000000">}</font></font></span></p> </div>
