---
layout: "post"
title: "Adding a property set programmatically using OMF"
date: "2012-08-08 01:30:17"
author: "Katsuaki Takamizawa"
categories:
  - "AutoCAD Architecture"
  - "Katsuaki Takamizawa"
  - "OMF"
original_url: "https://adndevblog.typepad.com/aec/2012/08/adding-a-property-set-programmatically-using-omf.html "
typepad_basename: "adding-a-property-set-programmatically-using-omf"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/katsuaki-takamizawa.html" target="_self">Katsuaki Takamizawa</a></p>  <p>Issue:</p>  <p>Using the command _AecPropertyDataEdit and Add button, we can add a property set to an AEC object. How can I do this programmatically in OMF?</p>  <p>Solution:</p>  <p>The property set object is added to AEC object's extension dictionary named &quot;AEC_PROPERTY_SETS&quot;. Its name will be anonymous (starting with &quot;*&quot;). In order to create it correctly, a property set definition must be referenced, as in the UI. The latter is stored in the dictionary &quot;AEC_PROPERTY_SET_DEFS&quot; under AutoCAD Named Object Dictionary). The following code shows exactly how to do it.</p>  <p><font face="Calibri"><font color="#000000"><font style="font-size: 7.8pt">&#160;<font size="2"> </font></font></font><span><font color="#008000">// get working database</font></span>       <br /></font><font face="Calibri"><font color="#000000">&#160; Acad::ErrorStatus es;        <br />&#160; AcDbDatabase *pCurDb = acdbHostApplicationServices()-&gt;workingDatabase();         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(pCurDb == NULL)        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />        <br />&#160; </font><span><font color="#008000">// get a property set definition name, e.g. Door, Frame, etc.</font></span>       <br /><font color="#000000">&#160; AecUiPrString promptStr(_T(</font><span><font color="#a31515">&quot;Input property set definition name&quot;</font></span></font><font face="Calibri"><font color="#000000">), Adesk::kFalse);        <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(promptStr.go() != AecUiPr::kOk)        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />        <br />&#160; </font><span><font color="#008000">// get dictionary of property set definition</font></span>       <br /></font><font face="Calibri"><font color="#000000">&#160; AecDictPropertySetDef dictPropSet(pCurDb);        <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">( !dictPropSet.isValid() )        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nCan not find any property set definitions.&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; }         <br />        <br />&#160; </font><span><font color="#008000">// get the specific PropSetDef Id</font></span>       <br /></font><font face="Calibri"><font color="#000000">&#160; AcDbObjectId objId;        <br />&#160; es = dictPropSet.getAt(promptStr.value(), objId);         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">( es != Acad::eOk )        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nThe %s property set does not exist.&quot;</font></span></font><font face="Calibri"><font color="#000000">),        <br />&#160;&#160;&#160;&#160;&#160; promptStr.value());         <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; }         <br />        <br />&#160; </font><span><font color="#008000">// select a door</font></span>       <br /><font color="#000000">&#160; AecUiPrEntity promptEnt(_T(</font><span><font color="#a31515">&quot;Select an Door&quot;</font></span></font><font face="Calibri"><font color="#000000">), NULL);        <br />&#160; promptEnt.addAllowedClass(AecDbDoor::desc());         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(promptEnt.go() != AecUiPr::kOk)        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nI am only able to work on AEC entities. :-(&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; }         <br />        <br />&#160; </font><span><font color="#008000">// open the door for write</font></span>       <br /></font><font face="Calibri"><font color="#000000">&#160; AecDbDoor *pEnt;        <br />&#160; es = AecDbDoor::open(pEnt, promptEnt.objectId(), AcDb::kForWrite);         <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(es != Acad::eOk)        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nCan not open this AEC entities to write.&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span></font><font face="Calibri"><font color="#000000">;        <br />&#160; }         <br />        <br />&#160; </font><span><font color="#008000">// add property set to door</font></span>       <br /></font><font face="Calibri"><font color="#000000">&#160; es = AecDbPropertySet::addPropertySet(pEnt, objId);        <br />&#160; </font><span><font color="#0000ff">if</font></span></font><font face="Calibri"><font color="#000000">(es != Acad::eOk)        <br />&#160; {         <br />&#160;&#160;&#160; acutPrintf(_T(</font><span><font color="#a31515">&quot;\nCan not add property set.&quot;</font></span></font><font face="Calibri"><font color="#000000">));        <br />&#160;&#160;&#160; </font><span><font color="#0000ff">return</font></span><font color="#000000">;        <br />&#160; }         <br />        <br />&#160; pEnt-&gt;close();</font></font></p>  <pre style="line-height: normal; font-family: ; background: white"><font color="#000000" face="Calibri"></font></pre>
