---
layout: "post"
title: "Get the sketch and sketch plane"
date: "2012-07-31 03:05:42"
author: "Joe Ye"
categories:
  - ".NET"
  - "Joe Ye"
  - "Revit"
original_url: "https://adndevblog.typepad.com/aec/2012/07/get-the-sketch-and-sketch-plane.html "
typepad_basename: "get-the-sketch-and-sketch-plane"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/joe-ye.html">Joe Ye</a></p>  <p>A sketch and a sketch plane are created when creating a floor, roof, and filled region et.al. I want to retrieve the sketch and sketch plane. However there is no API to do that . Would you please tell me how to find the two objects?</p>  <p><strong>Solution</strong></p>  <p>When creating a floor, slab and filled region et.al, users need to draw a profile to define the element's shape.&#160; Revit automatically creates a sketch and sketch plane for the profile. If the floor, slab or filled region is deleted, the corresponding sketch and sketch plane will be deleted accordingly. </p>  <p>Document.Delete() method returns all deleted elements' Id. Using this mechanism, we can figure out this solution. </p>  <p>Start a transaction, and delete the target element. The sketch and sketch plane Id should be in the returned element id list. Filter out the target elements by class name. Then rollback the transaction to keep the target element unchanged.</p>  <p>Here is the code showing the usage.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Collections.Generic;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Windows.Forms;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%">&#160; Autodesk.Revit .DB;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.UI;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit .ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.Attributes ;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.UI.Selection;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; [</span><span style="line-height: 140%; color: #2b91af">TransactionAttribute</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">TransactionMode</span><span style="line-height: 140%">.Manual)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; [</span><span style="line-height: 140%; color: #2b91af">RegenerationAttribute</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">RegenerationOption</span><span style="line-height: 140%">.Manual)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">RevitCommand</span><span style="line-height: 140%"> : </span><span style="line-height: 140%; color: #2b91af">IExternalCommand</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%"> Execute(</span><span style="line-height: 140%; color: #2b91af">ExternalCommandData</span><span style="line-height: 140%"> commandData, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">ref</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> messages, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ElementSet</span><span style="line-height: 140%"> elements)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">UIApplication</span><span style="line-height: 140%"> app = commandData.Application;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">UIDocument</span><span style="line-height: 140%"> uiDoc = app.ActiveUIDocument;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = uiDoc.Document;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Selection</span><span style="line-height: 140%"> sel = uiDoc.Selection;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Reference</span><span style="line-height: 140%"> ref1 = sel.PickObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ObjectType</span><span style="line-height: 140%">.Element, </span><span style="line-height: 140%; color: #a31515">&quot;Please pick an element&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Element</span><span style="line-height: 140%"> elem = ref1.Element;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> trans = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%">(doc);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; trans.Start(</span><span style="line-height: 140%; color: #a31515">&quot;test&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ICollection</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">ElementId</span><span style="line-height: 140%">&gt; ids = doc.Delete(elem);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; trans.RollBack();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> strName = </span><span style="line-height: 140%; color: #a31515">&quot;Host Id = &quot;</span><span style="line-height: 140%"> + </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; elem.Id.IntegerValue.ToString() + </span><span style="line-height: 140%; color: #a31515">&quot;\r\n&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ElementId</span><span style="line-height: 140%"> id </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> ids)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Element</span><span style="line-height: 140%"> elemIter = doc.get_Element(id);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (elemIter </span><span style="line-height: 140%; color: blue">is</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Sketch</span><span style="line-height: 140%"> || elemIter </span><span style="line-height: 140%; color: blue">is</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">SketchPlane</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; strName += </span><span style="line-height: 140%; color: #a31515">&quot;Id = &quot;</span><span style="line-height: 140%"> + id.IntegerValue.ToString() </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </span><span style="line-height: 140%; color: #a31515">&quot;;&quot;</span><span style="line-height: 140%"> + elemIter.Name</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; + </span><span style="line-height: 140%; color: #a31515">&quot; ;&quot;</span><span style="line-height: 140%"> + elemIter.GetType().ToString() + </span><span style="line-height: 140%; color: #a31515">&quot;\r\n&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">TaskDialog</span><span style="line-height: 140%">.Show(</span><span style="line-height: 140%; color: #a31515">&quot;test&quot;</span><span style="line-height: 140%">, strName);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%">.Succeeded ;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div>  <p>Using this approach, elements that are closing related with a specified element can be retrieved too. For example, the detailed lines that forms the profile can also be found. </p>
