---
layout: "post"
title: "Getting the room boundary based on &ldquo;Room Area Computation&rdquo; setting"
date: "2012-06-06 02:10:46"
author: "Katsuaki Takamizawa"
categories:
  - "Katsuaki Takamizawa"
original_url: "https://adndevblog.typepad.com/aec/2012/06/getting-the-room-boundary-based-on-room-area-computation-setting.html "
typepad_basename: "getting-the-room-boundary-based-on-room-area-computation-setting"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/katsuaki-takamizawa.html" target="_self">Katsuaki Takamizawa</a></p>  <p>Room.Boundary property was returning segments related to “Room Area Computation” setting (such as “At wall finish” and “At wall center”) in Revit 2012. However, Room.Boundary property is obsolete in Revit 2013 and Room.GetBoundarySegments() method is no longer related to “Room Are Computation” setting. Is there any way to get the room boundary relative to “Room Are Computation” setting in Revit 2013? The answer is Yes.</p>  <p>This is an regression issue. But Here is workaround.</p>  <p><font size="1"><span><font color="#008000">// This is the workaround to get room boundary based on </font></span>      <br /><span><font color="#008000">// &quot;Room Area Computation&quot;setting</font></span>       <br /><span><font color="#008000">//</font></span>       <br /><font color="#000000">Autodesk.Revit.DB.</font><span><font color="#2b91af">VolumeCalculationSetting</font></span></font><font size="1"><font color="#000000"> vsetting =        <br />&#0160; doc.Settings.VolumeCalculationSetting;         <br />Autodesk.Revit.DB.</font><span><font color="#2b91af">SpatialElementBoundaryOptions</font></span></font><font size="1"><font color="#000000"> options        <br />&#0160; = </font><span><font color="#0000ff">new</font></span><font color="#000000"> Autodesk.Revit.DB.</font><span><font color="#2b91af">SpatialElementBoundaryOptions</font></span></font><font size="1"><font color="#000000">();        <br />        <br />options.SpatialElementBoundaryLocation =         <br />&#0160; (Autodesk.Revit.DB.</font><span><font color="#2b91af">SpatialElementBoundaryLocation</font></span></font><font size="1"><font color="#000000">)vsetting.&#0160; <br />&#0160; VolumeCalculationOptions.RoomAreaBoundaryLocation;         <br />        <br /></font><span><font color="#008000">// Getting curves of the room boundary</font></span>       <br /><span><font color="#008000">//</font></span>       <br /><font color="#000000">System.Collections.Generic.</font><span><font color="#2b91af">IList</font></span><font color="#000000">&lt;Autodesk.Revit.DB.</font><span><font color="#2b91af">Curve</font></span></font><font size="1"><font color="#000000">&gt; curveAry =        <br />&#0160; </font><span><font color="#0000ff">new</font></span><font color="#000000"> System.Collections.Generic.</font><span><font color="#2b91af">List</font></span><font color="#000000">&lt;Autodesk.Revit.DB.</font><span><font color="#2b91af">Curve</font></span></font><font size="1"><font color="#000000">&gt;();        <br /></font><span><font color="#0000ff">foreach</font></span></font><font size="1"><font color="#000000"> (Collections.Generic.IList&lt;Revit.DB.BoundarySegment&gt;        <br />&#0160;&#0160;&#0160; bndSegAry </font><span><font color="#0000ff">in</font></span></font><font size="1"><font color="#000000"> room.GetBoundarySegments(options))        <br />{         <br />&#0160; </font><span><font color="#0000ff">foreach</font></span><font color="#000000"> (Revit.DB.BoundarySegment bndSeg </font><span><font color="#0000ff">in</font></span></font><font color="#000000" size="1"> bndSegAry)      <br />&#0160;&#0160;&#0160; curveAry.Add(bndSeg.Curve);       <br />}</font></p>
