---
layout: "post"
title: "Create line based generic model family instance"
date: "2012-05-21 02:53:12"
author: "Joe Ye"
categories:
  - ".NET"
  - "Joe Ye"
  - "Revit"
original_url: "https://adndevblog.typepad.com/aec/2012/05/create-line-based-generic-model-family-instance-1.html "
typepad_basename: "create-line-based-generic-model-family-instance-1"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/joe-ye.html">Joe Ye</a></p>  <p>When create a line based generic model family instance manually in the Revit project document or family document, Revit reminds you to select “Place on Face” or Plance on Work Plane” in the contextual Ribbon tab. After pick one of them, you can draw the instance by pick one point, and then next point to create the family instance.</p>  <p>As the base face or work plane is necessary when creating the family instance, we need to provide the base face or work plane, and also the base line when calling NewFamilyInstance(). This override of NewFamilyInstance can be used.</p>  <p>NewFamilyInstance(Line line, FamilySymbol symbol, View view);</p>  <p>Note: the base line passed in should be in the view that is passed in. Otherwise it fails to create the generic model family instance. The error message is that the line is not in the specified view.</p>  <p>&#160;</p>  <p>Here is the code snippet showing the usage. </p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Collections.Generic;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Text;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Windows.Forms;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.DB;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.UI;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.DB.Structure;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.Attributes;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">[</span><span style="line-height: 140%; color: #2b91af">TransactionAttribute</span><span style="line-height: 140%">(</span><span style="line-height: 140%; color: #2b91af">TransactionMode</span><span style="line-height: 140%">.Manual)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">RevitCommand</span><span style="line-height: 140%"> : </span><span style="line-height: 140%; color: #2b91af">IExternalCommand</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%"> Execute(</span><span style="line-height: 140%; color: #2b91af">ExternalCommandData</span><span style="line-height: 140%"> commandData,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">ref</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> messages, </span><span style="line-height: 140%; color: #2b91af">ElementSet</span><span style="line-height: 140%"> elements)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">UIApplication</span><span style="line-height: 140%"> app = commandData.Application;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = app.ActiveUIDocument.Document;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> trans = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%">(doc, </span><span style="line-height: 140%; color: #a31515">&quot;ExComm&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; trans.Start();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//For simplicity, and focusing on the important point,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Get the target family type via its Id. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Please replace this line with the code to get the lin</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//e based generic model FamilySymbol.</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">FamilySymbol</span><span style="line-height: 140%"> symbol = doc.get_Element(</span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ElementId</span><span style="line-height: 140%">(6732))</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">FamilySymbol</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> line = app.Application.Create.NewLineBound(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%">(0, 0, 0), </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%">(10, 10, 0));</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//For simplicity, use the active view. </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Note: before run this command, set the plan view which </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//elevation is 0 to be the active view.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//This can make sure the line is in this plan view.</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">FamilyInstance</span><span style="line-height: 140%"> inst = doc.FamilyCreate.NewFamilyInstance(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; line, symbol, doc.ActiveView);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; trans.Commit();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%">.Succeeded;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p>    <p style="margin: 0px"><span style="line-height: 140%"></span></p>    <p style="margin: 0px"><span style="line-height: 140%"><font size="2" face="Arial">After creating the family instance, we can change the base curve of the family instance. However you cannot assign the curve that is out of the host view. The new base curve required to be in this view. </font></span></p> </div>
