---
layout: "post"
title: "Assembly/Parts samples"
date: "2012-08-16 21:40:28"
author: "Katsuaki Takamizawa"
categories:
  - ".NET"
  - "Katsuaki Takamizawa"
  - "Revit"
original_url: "https://adndevblog.typepad.com/aec/2012/08/assemblyparts-samples.html "
typepad_basename: "assemblyparts-samples"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/katsuaki-takamizawa.html" target="_self">Katsuaki Takamizawa</a></p>  <p>Currently, we do not have Revit API samples for Assembly/Parts in Revit SDK.</p>  <p>So I searched for and I would like to share with you what I found.</p>  <p>Our Revit 2012 API webcast demonstrated the assembly creation. You can download the code sample posted with the webcast recording at <a href="http://www.adskconsulting.com/adn/cs/api_course_webcast_archive.php">Webcast Recording Archive web page</a>. I migrated the code sample tp Revit 2013 (it was an easy task) and attached <span class="asset  asset-generic at-xid-6a0167607c2431970b01676952d5df970b"><a href="http://adndevblog.typepad.com/files/constructionmodeling-3.zip">sample</a></span> in this blog post for your convenience. It implements two external commands. “CreateAssemblies” command let you pick elements and creates an assembly instance and a part list in a schedule view as following. “Compare Assemblies” command asks you to select two assembly instances and finds differences such as the number or types of elements. For example, you can create walls, windows, and columns as shown below to demonstrate the sample.</p>  <p><span style="font-family: calibri"><span style="color: #000000">&#0160; [</span><span><span style="color: #2b91af">Transaction</span></span><span style="color: #000000">(</span><span><span style="color: #2b91af">TransactionMode</span></span></span><span style="font-family: calibri"><span style="color: #000000">.Manual)]        <br />&#0160; </span><span><span style="color: #0000ff">public</span></span><span style="color: #000000">&#0160;</span><span><span style="color: #0000ff">class</span></span><span style="color: #000000">&#0160;</span><span><span style="color: #2b91af">CreateAssemblies</span></span><span style="color: #000000"> : </span><span><span style="color: #2b91af">IExternalCommand</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">&#0160; {        <br /></span><span><span style="color: #0000ff">&#0160;&#0160;&#0160; #region</span></span></span><span style="font-family: calibri"><span style="color: #000000"> IExternalCommand Members        <br />        <br />&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">public</span></span><span style="color: #000000">&#0160;</span><span><span style="color: #2b91af">Result</span></span></span><span style="font-family: calibri"><span style="color: #000000"> Execute(        <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">ExternalCommandData</span></span></span><span style="font-family: calibri"><span style="color: #000000"> commandData,        <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">ref</span></span><span style="color: #000000">&#0160;</span><span><span style="color: #0000ff">string</span></span></span><span style="font-family: calibri"><span style="color: #000000"> message,&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">ElementSet</span></span></span><span style="font-family: calibri"><span style="color: #000000"> elements        <br />&#0160;&#0160;&#0160;&#0160;&#0160; )         <br />&#0160;&#0160;&#0160; {         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Get the application and document from command data</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">       <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">UIApplication</span></span></span><span style="font-family: calibri"><span style="color: #000000"> uiapp = commandData.Application;        <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">UIDocument</span></span></span><span style="font-family: calibri"><span style="color: #000000"> uidoc = uiapp.ActiveUIDocument;        <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">Document</span></span></span><span style="font-family: calibri"><span style="color: #000000"> doc = uidoc.Document;        <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">ICollection</span></span><span style="color: #000000">&lt;</span><span><span style="color: #2b91af">ElementId</span></span></span><span style="font-family: calibri"><span style="color: #000000">&gt; elemIds =&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; uidoc.Selection.GetElementIds();         <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">ElementId</span></span><span style="color: #000000"> categoryId = </span><span><span style="color: #0000ff">null</span></span></span><span style="font-family: calibri"><span style="color: #000000">;        <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">ElementId</span></span><span style="color: #000000"> keyElemId = </span><span><span style="color: #0000ff">null</span></span></span><span style="font-family: calibri"><span style="color: #000000">;        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">if</span></span></span><span style="font-family: calibri"><span style="color: #000000"> (elemIds.Count &gt; 0)        <br />&#0160;&#0160;&#0160;&#0160;&#0160; {         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">foreach</span></span><span style="color: #000000"> (</span><span><span style="color: #2b91af">ElementId</span></span><span style="color: #000000"> elemId </span><span><span style="color: #0000ff">in</span></span></span><span style="font-family: calibri"><span style="color: #000000"> elemIds)        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Use category of one of the assembly elements</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; keyElemId = elemId;         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; categoryId = doc.GetElement(elemId).Category.Id;         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">break</span></span></span><span style="font-family: calibri"><span style="color: #000000">;        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }         <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">Transaction</span></span><span style="color: #000000"> transaction = </span><span><span style="color: #0000ff">new</span></span><span style="color: #000000">&#0160;</span><span><span style="color: #2b91af">Transaction</span></span></span><span style="font-family: calibri"><span style="color: #000000">(doc);        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Check if the Category name is valid</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">if</span></span><span style="color: #000000"> (</span><span><span style="color: #2b91af">AssemblyInstance</span></span></span><span style="font-family: calibri"><span style="color: #000000">.IsValidNamingCategory(        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; doc, categoryId, elemIds         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; ))         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transaction.Start(</span><span><span style="color: #a31515">&quot;Create Assembly Instance&quot;</span></span></span><span style="font-family: calibri"><span style="color: #000000">);        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">AssemblyInstance</span></span></span><span style="font-family: calibri"><span style="color: #000000"> assemblyInstance =&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">AssemblyInstance</span></span></span><span style="font-family: calibri"><span style="color: #000000">.Create(doc, elemIds, categoryId);        <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Commit the transaction that creates the </span></span>      <br /><span style="color: #000000">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// assembly instance before modifying the </span></span>      <br /><span style="color: #000000">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// instance&#39;s name</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transaction.Commit();&#0160; <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Create another transaction for assigning name to the</span></span>       <br /><span style="color: #000000">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// assembly instance</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transaction.Start(</span><span><span style="color: #a31515">&quot;Set Assembly Name&quot;</span></span></span><span style="font-family: calibri"><span style="color: #000000">);        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; assemblyInstance.AssemblyTypeName =&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #a31515">&quot;My Assembly Name &quot;</span></span></span><span style="font-family: calibri"><span style="color: #000000"> + keyElemId.ToString();        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transaction.Commit();         <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Create assembly views for this assembly instance</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">if</span></span></span><span style="font-family: calibri"><span style="color: #000000"> (assemblyInstance.AllowsAssemblyViewCreation())&#0160; <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; {         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transaction.Start(</span><span><span style="color: #a31515">&quot;View Creation&quot;</span></span></span><span style="font-family: calibri"><span style="color: #000000">);        <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Create Orthographic view</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">View3D</span></span><span style="color: #000000"> view3d = </span><span><span style="color: #2b91af">AssemblyViewUtils</span></span></span><span style="font-family: calibri"><span style="color: #000000">.Create3DOrthographic(        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; doc, assemblyInstance.Id         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );         <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #008000">// Create Part list</span></span>       <br /></span><span style="font-family: calibri"><span style="color: #000000">       <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #2b91af">View</span></span><span style="color: #000000"> partList = </span><span><span style="color: #2b91af">AssemblyViewUtils</span></span></span><span style="font-family: calibri"><span style="color: #000000">.CreatePartList(        <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; doc, assemblyInstance.Id         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; );         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; transaction.Commit();         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }         <br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; }         <br />&#0160;&#0160;&#0160;&#0160;&#0160; }         <br />        <br />&#0160;&#0160;&#0160;&#0160;&#0160; </span><span><span style="color: #0000ff">return</span></span><span style="color: #000000"> Autodesk.Revit.UI.</span><span><span style="color: #2b91af">Result</span></span><span style="color: #000000">.Succeeded;        <br />&#0160;&#0160;&#0160; }         <br /></span></span></p>  <p><span style="font-family: calibri"><span style="color: #000000"><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01676952cfda970b-pi"><img alt="Assembly" border="0" height="296" src="/assets/image_588743.jpg" style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="Assembly" width="555" /></a></span></span></p>  <p>&#0160;</p>  <p>Also a blog post by Jeremy shows how to split walls into parts. I recommend to take a look at PartUtils class in the API reference document for what you can do with parts.</p>  <p><a href="http://thebuildingcoder.typepad.com/blog/2011/10/retrieving-detailed-wall-layer-geometry.html">http://thebuildingcoder.typepad.com/blog/2011/10/retrieving-detailed-wall-layer-geometry.html</a></p>  <p>Here is a Jeremy’s post in case if you want to create certain AssemblyInstance elements in the model programmatically and would like to prevent the user from being able to modify those elements.</p>  <p><a href="http://thebuildingcoder.typepad.com/blog/2011/11/lock-the-model-eg-prevent-deletion.html">http://thebuildingcoder.typepad.com/blog/2011/11/lock-the-model-eg-prevent-deletion.html</a></p>
