---
layout: "post"
title: "Change door&rsquo;s Room Calculation Point parameter value in model document"
date: "2013-12-05 00:48:46"
author: "Joe Ye"
categories: []
original_url: "https://adndevblog.typepad.com/aec/2013/12/change-doors-room-calculation-point-parameter-value-in-model-document.html "
typepad_basename: "change-doors-room-calculation-point-parameter-value-in-model-document"
typepad_status: "Draft"
---

<p><a href="http://adndevblog.typepad.com/aec/joe-ye.html">Joe Ye</a></p>  <p>&#160;</p>  <p>We got the following query from Remy van den Bor from ICN Solutions BV.</p>  <p>I want to make a door showing its &quot;Calculation Point parameter” mark in the plan view. Manually we can change this by edit this door’s family and check the family’s “Calculation Point Parameter” value in the family’s editor. Then reload the Family and overwrite the parameter values.</p>  <p>&#160;&#160;&#160;&#160;&#160;&#160; <a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b019b022cb9cf970b-pi"><img style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="image" border="0" alt="image" src="/assets/image_884049.jpg" width="209" height="244" /></a></p>  <p>&#160;</p>  <p>So I wrote this DevelopSharp code to do this. Using RevitLookup I can see this family’s “Room Calculation Point” parameter value was changed.&#160; However it cannot make the door showing the Room Calculation Point mark.&#160; Even I call Regenerate() method, it cannot make it showing.</p>  <div style="font-family: 新宋体; background: white; color: black; font-size: 9pt">   <p style="margin: 0px"><span style="color: #2b91af">&#160; </span></p> </div>  <div style="font-family: 新宋体; background: white; color: black; font-size: 9pt">   <p style="margin: 0px">&#160; <span style="color: blue">public</span> <span style="color: blue">void</span> ChangeFamilyParam()</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Document doc = <span style="color: blue">this</span>.ActiveUIDocument.Document;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Selection sel = <span style="color: blue">this</span>.ActiveUIDocument.Selection;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Reference ref1 = sel.PickObject(ObjectType.Element, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Please pick an door&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; FamilyInstance f = doc.GetElement(ref1) <span style="color: blue">as</span> FamilyInstance;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Transaction t = <span style="color: blue">new</span> Transaction(doc);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; t.Start(<span style="color: #a31515">&quot;rcp&quot;</span>);</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">foreach</span> (Parameter par <span style="color: blue">in</span> f.Symbol.Family.Parameters)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">if</span> (par.Definition.Name == <span style="color: #a31515">&quot;Room Calculation Point&quot;</span>)</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; par.Set(1);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; t.Commit();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Transaction Trans = <span style="color: blue">new</span> Transaction(doc);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Trans.Start(<span style="color: #a31515">&quot;asd&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.Regenerate();</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Trans.Commit();</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p> </div>  <p>How can I make the mark visible for door programmatically?</p>  <p>&#160;</p>  <p><strong>Solution</strong></p>  <p>We can simulate the whole process like you did manually to make it visible programmatically.&#160; </p>  <p>Here are the steps.</p>  <p>1. Get the target Family;</p>  <p>2. Open the document of this family;</p>  <p>3. Get the parameter from the ownerFamily property;</p>  <p>4. Start a transaction for docFamily. Then Change the parameter value by&#160; param.Set(1);</p>  <p>5. Submit the transation of the family document;    <br />6. Load the family document back to Revit model;</p>  <p>7. This should make the door’s calculation point visible;</p>  <p>&#160;</p>  <p>The full code sample is like this:</p>  <div style="font-family: 新宋体; background: white; color: black; font-size: 9pt">   <p style="margin: 0px"><span style="color: blue">using</span> System;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System.Collections.Generic;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System.Text;</p>    <p style="margin: 0px"><span style="color: blue">using</span> System.Windows.Forms;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.Revit.DB;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.Revit.UI;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.Revit.ApplicationServices;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.Revit.Attributes;</p>    <p style="margin: 0px"><span style="color: blue">using</span> Autodesk.Revit.UI.Selection;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="color: blue">public</span> <span style="color: blue">class</span> <span style="color: #2b91af">familyOverride</span> : IFamilyLoadOptions</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">bool</span> IFamilyLoadOptions.OnFamilyFound(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">bool</span> familyInUse, <span style="color: blue">out</span> <span style="color: blue">bool</span> overwriteParameterValues)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; overwriteParameterValues = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">bool</span> IFamilyLoadOptions.OnSharedFamilyFound(Family sharedFamily, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">bool</span> familyInUse, <span style="color: blue">out</span> FamilySource source, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">out</span> <span style="color: blue">bool</span> overwriteParameterValues)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; source = FamilySource.Family;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; overwriteParameterValues = <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> <span style="color: blue">true</span>;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">}</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">[TransactionAttribute(TransactionMode.Manual)]</p>    <p style="margin: 0px"><span style="color: blue">public</span> <span style="color: blue">class</span> <span style="color: #2b91af">RevitCommand</span> : IExternalCommand</p>    <p style="margin: 0px">{</p>    <p style="margin: 0px">&#160;&#160;&#160; <span style="color: blue">public</span> Result Execute(ExternalCommandData commandData,</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160; <span style="color: blue">ref</span> <span style="color: blue">string</span> messages, ElementSet elements)</p>    <p style="margin: 0px">&#160;&#160;&#160; {</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; UIApplication app = commandData.Application;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Document doc = app.ActiveUIDocument.Document;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Selection sel = app.ActiveUIDocument.Selection;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Reference ref1 = sel.PickObject(ObjectType.Element, </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Please pick a door&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; FamilyInstance f = doc.GetElement(ref1) <span style="color: blue">as</span> FamilyInstance;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Document familyDoc = doc.EditFamily(f.Symbol.Family);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Transaction transF = <span style="color: blue">new</span> Transaction(familyDoc);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; transF.Start(<span style="color: #a31515">&quot;ChgCalPnt&quot;</span>);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: green">//&quot;Room Calculation Point&quot;</span></p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Parameter param = familyDoc.OwnerFamily.get_Parameter(</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; BuiltInParameter.ROOM_CALCULATION_POINT); </p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; param.Set(1);</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; transF.Commit();</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; familyDoc.LoadFamily(doc, <span style="color: blue">new</span> <span style="color: #2b91af">familyOverride</span>());</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span> Result.Succeeded;</p>    <p style="margin: 0px">&#160;&#160;&#160; }</p>    <p style="margin: 0px">}</p>    <p style="margin: 0px"></p>    <p style="margin: 0px"></p> </div>
