---
layout: "post"
title: "Change the boundary of floors/slabs"
date: "2013-10-10 03:01:25"
author: "Joe Ye"
categories:
  - ".NET"
  - "Joe Ye"
  - "Revit"
  - "Revit Architecture"
  - "Revit Structure"
original_url: "https://adndevblog.typepad.com/aec/2013/10/change-the-boundary-of-floorsslabs.html "
typepad_basename: "change-the-boundary-of-floorsslabs"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/joe-ye.html">Joe Ye</a></p>  <p>&#160;</p>  <p>Revit didnâ€™t expose the API to edit floors/slabs boundary. Here introduce a trick to edit the boundary.</p>  <p>For a Revit slab or floor, there are mapping model lines to representing the boundary of tha slab. If a floor boundary has 6 segments, there are 6 corresponding model lines for this floor. When we change those model line's position or shape, the slab or floor's shape will be updated accordingly. </p>  <p>There probably are many model lines in a document. How can we find the model lines that representing the slab is the key point.</p>  <p>Here is the solution: You need to create a tempt transaction. During this temp transaction, delete the target slab by Document.Delete() method. This method will return all the deleted elements' ids after the slab is deleted. So the slab's boundary model line can be find by iterating all the return id (get the element from those ids and compare the object type if they are ModelLine class). Finally abort this temp transaction. </p>  <p>After get the boundary's boundary model lines, you can change the model line's shape by changing those ModelLine object ( use this method </p>  <p>LocationCurve lCurve = modelLine.Location as LocationCurve;    <br />lCurve.Curve = newcurve.</p>  <p>I just did a very quick test, this works.    <br />&#160; <br />Here is the complete command code.     <br />For simplicity, it just moves the floor by creating new boundary lines by moving the old segment.&#160; Here suppose the segment lines are all straight lines.</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%">[Autodesk.Revit.Attributes.</span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%">(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.Attributes.</span><span style="line-height: 140%; color: #2b91af">TransactionMode</span><span>.Manual)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="color: blue">class</span><span style="line-height: 140%"> </span><span style="color: #2b91af">ChangeFloor</span><span style="line-height: 140%"> : </span><span style="color: #2b91af">IExternalCommand</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> Autodesk.Revit.UI.</span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%"> Execute(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ExternalCommandData</span><span style="line-height: 140%"> commandData,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">ref</span><span style="line-height: 140%"> </span><span style="color: blue">string</span><span style="line-height: 140%"> message,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ElementSet</span><span style="line-height: 140%"> elements)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = commandData.Application.ActiveUIDocument.Document;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.UI.Selection.</span><span style="line-height: 140%; color: #2b91af">Selection</span><span> sel = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; commandData.Application.ActiveUIDocument.Selection;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Reference</span><span style="line-height: 140%"> ref1 = sel.PickObject (Autodesk.Revit.UI.Selection.</span><span style="line-height: 140%; color: #2b91af">ObjectType</span><span>.Element, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #a31515">&quot;Please pick a floor to edit&quot;</span><span>);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Floor</span><span style="line-height: 140%"> f = doc.GetElement(ref1) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Floor</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> transTemp = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%">(doc);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; transTemp.Start (</span><span style="line-height: 140%; color: #a31515">&quot;tempDelete&quot;</span><span>);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ICollection</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">ElementId</span><span style="line-height: 140%">&gt; ids = doc.Delete(f);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; transTemp.RollBack ();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">ModelLine</span><span style="line-height: 140%">&gt; mLines = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="color: #2b91af">ModelLine</span><span style="line-height: 140%">&gt;();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ElementId</span><span style="line-height: 140%"> id </span><span style="color: blue">in</span><span style="line-height: 140%"> ids)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Element</span><span style="line-height: 140%"> ele = doc.GetElement (id);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (ele </span><span style="line-height: 140%; color: blue">is</span><span style="line-height: 140%"> </span><span style="color: #2b91af">ModelLine</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; mLines.Add(ele </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ModelLine</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> trans = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%">(doc);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Start(</span><span style="line-height: 140%; color: #a31515">&quot;ChangeFloor&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">ModelLine</span><span style="line-height: 140%"> mline </span><span style="color: blue">in</span><span style="line-height: 140%"> mLines)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">LocationCurve</span><span style="line-height: 140%"> lCurve = mline.Location </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">LocationCurve</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> c = lCurve.Curve </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%"> pt1 = c.GetEndPoint(0);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%"> pt2 = c.GetEndPoint(1);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transform</span><span style="line-height: 140%"> transform = </span><span style="line-height: 140%; color: #2b91af">Transform</span><span style="line-height: 140%">.CreateTranslation(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%">(1, 1, 0)); </span><span style="color: green">//move the line.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%"> pt1New = transform.OfPoint (pt1);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%"> pt2New = transform.OfPoint (pt2);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> newLine = </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%">.CreateBound(pt1New, pt2New);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; lCurve.Curve = newLine;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; trans.Commit ();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%">.Succeeded;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p> </div>
