---
layout: "post"
title: "How to get the duct section shape for duct type object"
date: "2013-03-14 02:04:43"
author: "Joe Ye"
categories: []
original_url: "https://adndevblog.typepad.com/aec/2013/03/how-to-get-the-duct-section-shape-for-duct-type-object.html "
typepad_basename: "how-to-get-the-duct-section-shape-for-duct-type-object"
typepad_status: "Publish"
---

<div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue"></span></p>    <p style="margin: 0px">By <a href="http://adndevblog.typepad.com/aec/joe-ye.html">Joe Ye</a></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">For a given duct object, we can get its section shape by the parameters. For example, rectangle duct has Height and Width parameter, and circle duct has Radius parameter.</p>    <p style="margin: 0px">However, for a given duct type, no methods/parameters/properties can be used to get the section shape. Here share a workaround how to retrieve the section shape for a given duct type.</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">The solution is to get the shape from the duct type’s related duct elbow fitting’s connector shape. The duct type has the parameter for different type of fittings, for example, “Elbow Fitttings”, “T Fittings”. We can get the fitting type. It is an FamilySymbol instance. Then open the family document that defined the elbow fitting. And get the DuctConnector objects. Now we can get the section shape by DuctConnector.Shape method.</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">Though this command can work, the performance is not good for a list of duct type. Because it needs to open family, this takes time for each one. Revit engineering team already know the request of a more efficient API to retrieve the duct section shape from the duct type.</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">Here is the full code for the command to get the duct type that is picked.</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">&#160;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">&#160;</span></p> </div>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"></p>    <p style="margin: 0px"><span style="line-height: 140%"></span></p>     </div>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Collections.Generic;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Text;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Windows.Forms;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%">&#160; Autodesk.Revit .DB;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.UI;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit .ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.Attributes ;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.DB.Mechanical;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.UI.Selection;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; [TransactionAttribute(TransactionMode.Manual)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">RevitCommand</span><span style="line-height: 140%"> : IExternalCommand</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> Result Execute(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ExternalCommandData commandData, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">ref</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> messages, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; ElementSet elements)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; UIApplication app = commandData.Application;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Document doc = app.ActiveUIDocument.Document;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Selection sel = app.ActiveUIDocument.Selection;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Reference ref1 = sel.PickObject(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; ObjectType.Element, </span><span style="line-height: 140%; color: #a31515">&quot;please pick a duct&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Duct duct = doc.GetElement(ref1) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> Duct;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%">(duct == </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; messages = </span><span style="line-height: 140%; color: #a31515">&quot;You didn't select a duct&quot;</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> Result.Failed;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; DuctType ductType = duct.DuctType;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: green">//Get the duct type's elbow parameter value.</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Parameter param = ductType.get_Parameter(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; BuiltInParameter.RBS_CURVETYPE_DEFAULT_ELBOW_PARAM);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; FamilySymbol symbol = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; doc.get_Element(param.AsElementId()) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> FamilySymbol;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Family family = symbol.Family;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Document familyDoc = doc.EditFamily(family);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; FilteredElementCollector collector = </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> FilteredElementCollector(familyDoc);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; collector.OfClass(</span><span style="line-height: 140%; color: blue">typeof</span><span style="line-height: 140%">(ConnectorElement));</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; Element firstConnector = collector.FirstElement();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; DuctConnector connector = firstConnector </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> DuctConnector;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; TaskDialog.Show(</span><span style="line-height: 140%; color: #a31515">&quot;Duct Section Shape&quot;</span><span style="line-height: 140%">, connector.Shape.ToString());</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; familyDoc.Close(</span><span style="line-height: 140%; color: blue">false</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> Result.Succeeded ;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">}</span></p> </div>
