---
layout: "post"
title: "Create stirrup rebar by given model curves via Revit API"
date: "2013-05-23 03:47:04"
author: "Joe Ye"
categories: []
original_url: "https://adndevblog.typepad.com/aec/2013/05/create-stirrup-rebar-by-given-model-curves-via-revit-api.html "
typepad_basename: "create-stirrup-rebar-by-given-model-curves-via-revit-api"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/joe-ye.html">Joe Ye</a></p>  <p>As creating a stirrup rebar shape family is not so easy. Users would like to sketch up the shape of the stirrup within a column. This article introduce how to create a stirrup by several model curves within a column.</p>  <p>&#160;</p>  <div style="font-family: courier new; background: white; color: black; font-size: 8pt">   <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Collections.Generic;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Linq;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> System.Text;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.ApplicationServices;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.UI;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.DB.Structure;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.DB;</span></p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">using</span><span style="line-height: 140%"> Autodesk.Revit.UI.Selection;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%; color: blue">namespace</span><span style="line-height: 140%"> MyCreateRebar</span></p>    <p style="margin: 0px"><span style="line-height: 140%">{</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; [Autodesk.Revit.Attributes.</span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%">(Autodesk.Revit.Attributes.</span><span style="line-height: 140%; color: #2b91af">TransactionMode</span><span style="line-height: 140%">.Manual)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; [Autodesk.Revit.Attributes.</span><span style="line-height: 140%; color: #2b91af">Regeneration</span><span style="line-height: 140%">(Autodesk.Revit.Attributes.</span><span style="line-height: 140%; color: #2b91af">RegenerationOption</span><span style="line-height: 140%">.Manual)]</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">class</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Command1</span><span style="line-height: 140%"> : </span><span style="line-height: 140%; color: #2b91af">IExternalCommand</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">public</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%"> Execute(</span><span style="line-height: 140%; color: #2b91af">ExternalCommandData</span><span style="line-height: 140%"> commandData, </span><span style="line-height: 140%; color: blue">ref</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: blue">string</span><span style="line-height: 140%"> message, </span><span style="line-height: 140%; color: #2b91af">ElementSet</span><span style="line-height: 140%"> elements)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">UIApplication</span><span style="line-height: 140%"> uiApp = commandData.Application;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Selection</span><span style="line-height: 140%"> sel = uiApp.ActiveUIDocument.Selection;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Application</span><span style="line-height: 140%"> app = uiApp.Application;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Document</span><span style="line-height: 140%"> doc = uiApp.ActiveUIDocument.Document;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">RebarBarType</span><span style="line-height: 140%"> barType = </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">RebarHookType</span><span style="line-height: 140%"> hookType = </span><span style="line-height: 140%; color: blue">null</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%"> transaction = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Transaction</span><span style="line-height: 140%">(doc, </span><span style="line-height: 140%; color: #a31515">&quot;CreateRebar Tool&quot;</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">try</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; transaction.Start();</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">IList</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%">&gt; curves1 = </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">List</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%">&gt;();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">ElementSet</span><span style="line-height: 140%"> eleset = sel.Elements;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Element</span><span style="line-height: 140%"> e </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> eleset)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">if</span><span style="line-height: 140%"> (e </span><span style="line-height: 140%; color: blue">is</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ModelLine</span><span style="line-height: 140%">)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> l = (e </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">ModelLine</span><span style="line-height: 140%">).GeometryCurve </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Line</span><span style="line-height: 140%"> line = app.Create.NewLineBound(l.get_EndPoint(0), l.get_EndPoint(1));</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; curves1.Add(line);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">RebarBarType</span><span style="line-height: 140%"> bt </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> doc.RebarBarTypes)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; barType = bt;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">break</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">foreach</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">RebarHookType</span><span style="line-height: 140%"> ht </span><span style="line-height: 140%; color: blue">in</span><span style="line-height: 140%"> doc.RebarHookTypes)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; hookType = ht;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Reference</span><span style="line-height: 140%"> hasPickOne = sel.PickObject(</span><span style="line-height: 140%; color: #2b91af">ObjectType</span><span style="line-height: 140%">.Element);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">FamilyInstance</span><span style="line-height: 140%"> hostFi = doc.get_Element(hasPickOne.ElementId) </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">FamilyInstance</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Rebar</span><span style="line-height: 140%"> rebar = CreateRebar1(uidoc, curves1, hostFi, barType, hookType);</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">catch</span><span style="line-height: 140%"> (</span><span style="line-height: 140%; color: #2b91af">Exception</span><span style="line-height: 140%"> ex)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; message += ex.Message;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> Autodesk.Revit.UI.</span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%">.Failed;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">finally</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; {</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; transaction.Commit();</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">Result</span><span style="line-height: 140%">.Succeeded;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Rebar</span><span style="line-height: 140%"> CreateRebar1(</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; Autodesk.Revit.UI.</span><span style="line-height: 140%; color: #2b91af">UIDocument</span><span style="line-height: 140%"> uidoc,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">IList</span><span style="line-height: 140%">&lt;</span><span style="line-height: 140%; color: #2b91af">Curve</span><span style="line-height: 140%">&gt; curves,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">FamilyInstance</span><span style="line-height: 140%"> column,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">RebarBarType</span><span style="line-height: 140%"> barType,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">RebarHookType</span><span style="line-height: 140%"> hookType)</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; {</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">LocationPoint</span><span style="line-height: 140%"> location = column.Location </span><span style="line-height: 140%; color: blue">as</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">LocationPoint</span><span style="line-height: 140%">;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%"> origin = location.Point;</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">Rebar</span><span style="line-height: 140%"> rebar = </span><span style="line-height: 140%; color: #2b91af">Rebar</span><span style="line-height: 140%">.CreateFromCurves(uidoc.Document, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">RebarStyle</span><span style="line-height: 140%">.StirrupTie, barType, hookType, hookType,</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; column, </span><span style="line-height: 140%; color: blue">new</span><span style="line-height: 140%"> </span><span style="line-height: 140%; color: #2b91af">XYZ</span><span style="line-height: 140%">(0, 0, 1), curves, </span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: #2b91af">RebarHookOrientation</span><span style="line-height: 140%">.Left, </span><span style="line-height: 140%; color: #2b91af">RebarHookOrientation</span><span style="line-height: 140%">.Left, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">, </span><span style="line-height: 140%; color: blue">true</span><span style="line-height: 140%">);</span></p>    <p style="margin: 0px">&#160;</p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160;&#160;&#160; </span><span style="line-height: 140%; color: blue">return</span><span style="line-height: 140%"> rebar;</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160;&#160;&#160; }</span></p>    <p style="margin: 0px"><span style="line-height: 140%">&#160; }</span></p>    <p style="margin: 0px"></p> </div>
