---
layout: "post"
title: "Structural Section"
date: "2014-07-11 10:34:51"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "Revit"
  - "Revit Structure"
original_url: "https://adndevblog.typepad.com/aec/2014/07/structural-section.html "
typepad_basename: "structural-section"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>This sample was created by Andrzej Trelinski from Revit development team. Thanks!</p>  <p>It shows how add a structural section for a beam. The interesting point is about the FamilySymbol.HasStructuralSection method that, despite the name, return true if the symbol can contain a structural section. </p>  <p>Finally, only StructuralSectionPipeStandard and StructuralSectionRoundHSS can be instantiated via API. Below is a sample code.</p>  <p>&#160;</p>  <p><span style="color: #2b91af">UIApplication</span> uiApp = commandData.Application;    <br /><span style="color: #2b91af">Application</span> app = uiApp.Application;    <br /><span style="color: #2b91af">UIDocument</span> uiDoc = uiApp.ActiveUIDocument;    <br /><span style="color: #2b91af">Document</span> doc = uiDoc.Document;    <br />     <br /><span style="color: blue">var</span> collector = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">FilteredElementCollector</span>(doc);    <br />collector.OfCategory(<span style="color: #2b91af">BuiltInCategory</span>.OST_StructuralFraming);    <br />     <br /><span style="color: blue">if</span> (uiDoc.Selection.GetElementIds().Count &lt; 1)    <br />{    <br />&#160; <span style="color: #2b91af">TaskDialog</span>.Show(<span style="color: #a31515">&quot;Warning&quot;</span>, <span style="color: #a31515">&quot;No element selected!&quot;</span>+    <br />&#160;&#160;&#160; <span style="color: #a31515">&quot; Select strutcural framing element, like eg. Beam&quot;</span>);    <br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled;    <br />}    <br />     <br /><span style="color: blue">using</span> (<span style="color: #2b91af">Transaction</span> tran = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Transaction</span>(doc,    <br />&#160; <span style="color: #a31515">&quot;AddStructuralSection&quot;</span>))    <br />{    <br />&#160; tran.Start();    <br />     <br />     <br />&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">ElementId</span> id <span style="color: blue">in</span> uiDoc.Selection.GetElementIds())    <br />&#160; {    <br />&#160;&#160;&#160; <span style="color: #2b91af">Element</span> elem = doc.GetElement(id);    <br />&#160;&#160;&#160; <span style="color: blue">if</span> (!(elem <span style="color: blue">is</span>&#160;<span style="color: #2b91af">FamilyInstance</span>))    <br />&#160;&#160;&#160; {    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">TaskDialog</span>.Show(<span style="color: #a31515">&quot;Warning&quot;</span>, <span style="color: blue">string</span>.Format(    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Element ID='{0}' is not FamilyInstance. &quot;</span>+    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Only FamilyInstance elements can have StructuralSection&quot;</span>,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; elem.Id.IntegerValue));    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled;    <br />&#160;&#160;&#160; }    <br />     <br />&#160;&#160;&#160; <span style="color: #2b91af">FamilyInstance</span> famInst = elem <span style="color: blue">as</span>&#160;<span style="color: #2b91af">FamilyInstance</span>;    <br />     <br />&#160;&#160;&#160; <span style="color: green">// HasStructuralSection() check if element</span>    <br />&#160;&#160;&#160; <span style="color: green">// can have StructuralSection</span>    <br />&#160;&#160;&#160; <span style="color: blue">if</span> (!famInst.Symbol.Family.HasStructuralSection())&#160; <br />&#160;&#160;&#160; {    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">TaskDialog</span>.Show(<span style="color: #a31515">&quot;Warning&quot;</span>, <span style="color: blue">string</span>.Format(    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Element ID='{0}' can not have Structural section. &quot;</span> +&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: #a31515">&quot;Pick different family&quot;</span>,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; elem.Id.IntegerValue));    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled;    <br />&#160;&#160;&#160; }    <br />     <br />&#160;&#160;&#160; {    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: green">// create new Structural Section</span>    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> diameter = 5.25;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> sectionArea = 3.14159265358979 * diameter * diameter;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> perimeter = 3.14159265358979 * diameter;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> centroidHorizontal = 2.5;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> centroidVertical = 1.5;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> principalAxesAngle = 1.57;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> elasticModulusStrongAxis = 10e7;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> elasticModulusWeakAxis = 9e7;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> momentOfInertiaStrongAxis = 100;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> momentOfInertiaWeakAxis = 80;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> nominalWeight = 1023;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> plasticModulusStrongAxis = 120;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> plasticModulusWeakAxis = 55;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> shearAreaStrongAxis = 1;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> shearAreaWeakAxis = 2;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> torsionalModulus = 10;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> torsionalMomentOfInertia = 15;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> warpingConstant = 5;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> wallDesignThickness = 1.2;    <br />&#160;&#160;&#160;&#160;&#160; <span style="color: blue">double</span> wallNominalThickness = 1.1978;    <br />     <br />&#160;&#160;&#160;&#160;&#160; <span style="color: #2b91af">StructuralSectionPipeStandard</span> SSPipeStandard =    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">StructuralSectionPipeStandard</span>(    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; diameter, centroidHorizontal,&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; centroidVertical, principalAxesAngle,&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; wallNominalThickness, wallDesignThickness,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; sectionArea, perimeter, nominalWeight,&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; momentOfInertiaStrongAxis,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; momentOfInertiaWeakAxis, elasticModulusStrongAxis,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; elasticModulusWeakAxis, plasticModulusStrongAxis,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; plasticModulusWeakAxis, torsionalMomentOfInertia,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; torsionalModulus, warpingConstant,    <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; shearAreaStrongAxis, shearAreaWeakAxis);    <br />&#160;&#160;&#160;&#160;&#160; famInst.Symbol.SetStructuralSection(SSPipeStandard);    <br />&#160;&#160;&#160; }    <br />&#160; }    <br />     <br />&#160; <span style="color: blue">if</span> (tran.Commit() != <span style="color: #2b91af">TransactionStatus</span>.Committed)    <br />&#160; {    <br />&#160;&#160;&#160; <span style="color: #2b91af">TaskDialog</span>.Show(<span style="color: #a31515">&quot;ERROR&quot;</span>, <span style="color: #a31515">&quot;ERROR: Committing transaction failed&quot;</span>);    <br />&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Failed;    <br />&#160; }    <br />}    <br />     <br /><span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Succeeded;</p>
