---
layout: "post"
title: "Reading Revit Links hierarchy"
date: "2015-12-18 05:23:00"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "Revit"
original_url: "https://adndevblog.typepad.com/aec/2015/12/reading-revit-links-hierarchy.html "
typepad_basename: "reading-revit-links-hierarchy"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/augusto-goncalves.html">Augusto Goncalves</a>&#0160;(<a href="https://twitter.com/augustomaia">@augustomaia</a>)</p>
<p>Basically we need to play with GetParentId and GetChilds methods to understand the hierarchy of the linked files. There is also a GetRootId method, but we’re not using here.</p>
<p>From the documentation, we can see that GetParentId results InvalidElementId for root elements, so we do a first run through to find all root elements. Then, for each get again and recursively get the childs again.</p>
<p>It’s not easy to show a hierarchical result, so let’s create a <a href="https://msdn.microsoft.com/en-us/library/system.windows.forms.treeview(v=vs.110).aspx">TreeView</a>, as shown below. Note the result is similar to Revit UI. Cool!</p>
<p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb08a0a468970d-pi"><img alt="Code results vs. Revit UI" border="0" height="327" src="/assets/image_929155.jpg" style="display: inline; border: 0px;" title="Code results vs. Revit UI" width="605" /></a></p>
<p>&#0160;</p>
<pre style="font-size: 13px; font-family: consolas; background: white; color: black;"><span style="color: blue;">public</span>&#0160;<span style="color: #2b91af;">Result</span> Execute(<br /><span style="color: #2b91af;">ExternalCommandData</span> commandData,<br /><span style="color: blue;">ref</span>&#0160;<span style="color: blue;">string</span> message,<br /><span style="color: #2b91af;">ElementSet</span> elements)<br />{<br />&#0160; <span style="color: green;">// get active document</span><br />&#0160; <span style="color: #2b91af;">Document</span> mainDoc = commandData.Application.ActiveUIDocument.Document;<br /> <br />&#0160; <span style="color: green;">// prepare to show the results...</span><br />&#0160; <span style="color: #2b91af;">TreeNode</span> mainNode = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">TreeNode</span>();<br />&#0160; mainNode.Text = mainDoc.PathName;<br /> <br />&#0160; <span style="color: green;">// start by the root links (no parent node)</span><br />&#0160; <span style="color: #2b91af;">FilteredElementCollector</span> coll = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">FilteredElementCollector</span>(mainDoc);<br />&#0160; coll.OfClass(<span style="color: blue;">typeof</span>(<span style="color: #2b91af;">RevitLinkInstance</span>));<br />&#0160; <span style="color: blue;">foreach</span> (<span style="color: #2b91af;">RevitLinkInstance</span> inst <span style="color: blue;">in</span> coll)<br />&#0160; {<br />&#0160;&#0160;&#0160; <span style="color: #2b91af;">RevitLinkType</span> type = mainDoc.GetElement(inst.GetTypeId()) <span style="color: blue;">as</span>&#0160;<span style="color: #2b91af;">RevitLinkType</span>;<br />&#0160;&#0160;&#0160; <span style="color: blue;">if</span> (type.GetParentId() == <span style="color: #2b91af;">ElementId</span>.InvalidElementId)<br />&#0160;&#0160;&#0160; {<br />&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">TreeNode</span> parentNode = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">TreeNode</span>(inst.Name);<br />&#0160;&#0160;&#0160;&#0160;&#0160; mainNode.Nodes.Add(parentNode);<br /> <br />&#0160;&#0160;&#0160;&#0160;&#0160; GetChilds(mainDoc, type.GetChildIds(), parentNode);<br />&#0160;&#0160;&#0160; }<br />&#0160; }<br /> <br />&#0160; <span style="color: green;">// show the results in a form</span><br />&#0160; System.Windows.Forms.<span style="color: #2b91af;">Form</span> resultForm = <span style="color: blue;">new</span> System.Windows.Forms.<span style="color: #2b91af;">Form</span>();<br />&#0160; <span style="color: #2b91af;">TreeView</span> treeView = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">TreeView</span>();<br />&#0160; treeView.Size = resultForm.Size;<br />&#0160; treeView.Anchor |= <span style="color: #2b91af;">AnchorStyles</span>.Bottom | <span style="color: #2b91af;">AnchorStyles</span>.Top;<br />&#0160; treeView.Nodes.Add(mainNode);<br />&#0160; resultForm.Controls.Add(treeView);<br />&#0160; resultForm.ShowDialog();<br /> <br />&#0160; <span style="color: blue;">return</span>&#0160;<span style="color: #2b91af;">Result</span>.Succeeded;<br />}<br /> <br /><span style="color: blue;">private</span>&#0160;<span style="color: blue;">void</span> GetChilds(<span style="color: #2b91af;">Document</span> mainDoc, <span style="color: #2b91af;">ICollection</span>&lt;<span style="color: #2b91af;">ElementId</span>&gt; ids,<br />&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160;&#0160; <span style="color: #2b91af;">TreeNode</span> parentNode)<br />{<br />&#0160; <span style="color: blue;">foreach</span> (<span style="color: #2b91af;">ElementId</span> id <span style="color: blue;">in</span> ids)<br />&#0160; {<br />&#0160;&#0160;&#0160; <span style="color: green;">// get the child information</span><br />&#0160;&#0160;&#0160; <span style="color: #2b91af;">RevitLinkType</span> type = mainDoc.GetElement(id) <span style="color: blue;">as</span>&#0160;<span style="color: #2b91af;">RevitLinkType</span>;<br /> <br />&#0160;&#0160;&#0160; <span style="color: #2b91af;">TreeNode</span> subNode = <span style="color: blue;">new</span>&#0160;<span style="color: #2b91af;">TreeNode</span>(type.Name);<br />&#0160;&#0160;&#0160; parentNode.Nodes.Add(subNode);<br /> <br />&#0160;&#0160;&#0160; <span style="color: green;">// then go to the next level</span><br />&#0160;&#0160;&#0160; GetChilds(mainDoc, type.GetChildIds(), subNode);<br />&#0160; }<br />}</pre>
