---
layout: "post"
title: "Automating placement of lights families"
date: "2015-04-29 11:53:33"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "Revit"
  - "Revit MEP"
original_url: "https://adndevblog.typepad.com/aec/2015/04/automating-placement-of-lights-families.html "
typepad_basename: "automating-placement-of-lights-families"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>We’re always trying to automate tasks, it’s actually a common request when the adoption of tools increase and the amount of work follow it. As we know, this is a great area for API: the machine is amazing doing simple math and repetitive tasks.</p>  <p>This time the discussion was based on daily challenges at <a href="http://www.mha.com.br">MHA</a>, a Brazilian engineering firm localized in São Paulo. They are/were involved in several important projects, especially in MEP discipline, including the <a href="http://en.wikipedia.org/wiki/Centro_Empresarial_Na%C3%A7%C3%B5es_Unidas">business center</a> where Autodesk is located here in São Paulo.</p>  <p>&#160;<a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb0825fc6c970d-pi"><img title="MarginalPinheiros" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; display: inline; border-top-width: 0px" border="0" alt="MarginalPinheiros" src="/assets/image_313201.jpg" width="467" height="302" /></a>     <br />Image source: <a href="http://en.wikipedia.org/wiki/Centro_Empresarial_Na%C3%A7%C3%B5es_Unidas">Wikipedia</a>&#160; </p>  <p>One task currently consuming a long time is around placing light families on a Revit project. Of course the whole process cannot be automated as is based on the engineer’s analysis and experience, but the initial step of loading and placing the required number can be speed up.</p>  <p>Here are the steps we identifies: </p>  <ol>   <li>Select a family (.rfa) file that has a Light fixture. (in this code, the category of the family is not checked) </li>    <li>Choose one symbol on the family just loaded </li>    <li>Ask user to select reference plane, space and a pick a box on the project. These are used to calculate the number and location of the families. </li>    <li>Do some basic math (but yet not so simple logic) to find where to place the instances </li>    <li>Finally, in a loop, place all family instances. </li> </ol>  <p>This is not intended to replace the engineer, of course not. But by placing all the instance needed, the engineer can now move and adjust it, knowing the lumens requirement is meet (number of lights/lumens per room/space).</p>  <p>Let’s see the code, please follow the comments.</p>  <pre style="font-size: 13px; font-family: consolas; background: white; color: black"><span style="color: #2b91af">UIApplication</span> uiapp = commandData.Application;<br /><span style="color: #2b91af">UIDocument</span> uidoc = uiapp.ActiveUIDocument;<br /><span style="color: #2b91af">Application</span> app = uiapp.Application;<br /><span style="color: #2b91af">Document</span> doc = uidoc.Document;<br /> <br /><span style="color: green">// ask user to select a family file</span><br />System.Windows.Forms.<span style="color: #2b91af">OpenFileDialog</span> fileDlg = <br />&#160; <span style="color: blue">new</span> System.Windows.Forms.<span style="color: #2b91af">OpenFileDialog</span>();<br />fileDlg.Filter = <span style="color: #a31515">&quot;Revit Family (*.rfa)|*.rfa&quot;</span>;<br />fileDlg.Multiselect = <span style="color: blue">false</span>;<br /><span style="color: blue">if</span> (fileDlg.ShowDialog() <br />&#160; != System.Windows.Forms.<span style="color: #2b91af">DialogResult</span>.OK)<br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled;<br /> <br /><span style="color: green">// load the selected family</span><br /><span style="color: #2b91af">Family</span> fam;<br /><span style="color: blue">if</span> (!doc.LoadFamily(fileDlg.FileName, <span style="color: blue">out</span> fam))<br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Failed;<br /> <br /><span style="color: green">// select the symbol on the loaded family</span><br /><span style="color: green">// this is a simple WindowsForm with a </span><br /><span style="color: green">// ComboBox and a Button (action OK)</span><br /><span style="color: #2b91af">FormSelSymbol</span> frm = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">FormSelSymbol</span>();<br /><span style="color: blue">foreach</span> (<span style="color: #2b91af">ElementId</span> symbolId <span style="color: blue">in</span> fam.GetFamilySymbolIds())<br />{<br />&#160; <span style="color: #2b91af">FamilySymbol</span> s = doc.GetElement(symbolId) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">FamilySymbol</span>;<br />&#160; frm.cboSymbols.Items.Add(s);<br />}<br /><span style="color: green">// as the FamilySymbol is stored on the combo box</span><br /><span style="color: green">// let's make it show the Name property</span><br />frm.cboSymbols.DisplayMember = <span style="color: #a31515">&quot;Name&quot;</span>;<br /><span style="color: blue">if</span> (frm.ShowDialog()<br />&#160; != System.Windows.Forms.<span style="color: #2b91af">DialogResult</span>.OK)<br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled;<br /><span style="color: green">// and get the selected item</span><br /><span style="color: #2b91af">FamilySymbol</span> symbol = <br />&#160; frm.cboSymbols.SelectedItem <span style="color: blue">as</span>&#160;<span style="color: #2b91af">FamilySymbol</span>;<br /> <br /><span style="color: green">// for this case, we'll first select the reference plane</span><br /><span style="color: #2b91af">ElementId</span> refPlaneId;<br /><span style="color: #2b91af">ReferencePlane</span> refPlane;<br /><span style="color: blue">try</span><br />{<br />&#160; refPlaneId = uidoc.Selection.PickObject(<span style="color: #2b91af">ObjectType</span>.Element,<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">GenericFilter</span>&lt;<span style="color: #2b91af">ReferencePlane</span>&gt;(),<br />&#160;&#160;&#160; <span style="color: #a31515">&quot;Select reference plance&quot;</span>).ElementId;<br />&#160; refPlane =&#160; doc.GetElement(refPlaneId) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">ReferencePlane</span>;<br />}<br /><span style="color: blue">catch</span> (Autodesk.Revit.Exceptions.<span style="color: #2b91af">OperationCanceledException</span>)<br />{<br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled; <span style="color: green">// clean command exit</span><br />}<br /> <br /><span style="color: green">// space to get lumens data</span><br /><span style="color: #2b91af">Space</span> space;<br /><span style="color: blue">try</span><br />{<br />&#160; <span style="color: #2b91af">ElementId</span> id = uidoc.Selection.PickObject(<span style="color: #2b91af">ObjectType</span>.Element,<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">GenericFilter</span>&lt;<span style="color: #2b91af">Space</span>&gt;(),<br />&#160;&#160;&#160; <span style="color: #a31515">&quot;Select space&quot;</span>).ElementId;<br />&#160; space = doc.GetElement(id) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">Space</span>;<br />}<br /><span style="color: blue">catch</span> (Autodesk.Revit.Exceptions.<span style="color: #2b91af">OperationCanceledException</span>)<br />{<br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled; <span style="color: green">// clean command exit</span><br />}<br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br /><span style="color: green">// ask user to select a pick box where the lights </span><br /><span style="color: green">// will be created (along the reference plane</span><br /><span style="color: #2b91af">PickedBox</span> box;<br /><span style="color: blue">try</span><br />{<br />&#160; box = uidoc.Selection.PickBox(<span style="color: #2b91af">PickBoxStyle</span>.Crossing,<br />&#160;&#160;&#160; <span style="color: #a31515">&quot;Select pick box&quot;</span>);<br />}<br /><span style="color: blue">catch</span> (Autodesk.Revit.Exceptions.<span style="color: #2b91af">OperationCanceledException</span>)<br />{<br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Cancelled; <span style="color: green">// clean command exit</span><br />}<br /> <br /><span style="color: green">// now it's time for some math</span><br /><span style="color: green">// let's calculate the axis where </span><br /><span style="color: green">// the lights will be created</span><br /><span style="color: blue">double</span> h = box.Max.X - box.Min.X;<br /><span style="color: blue">double</span> w = box.Max.Y - box.Min.Y;<br /><span style="color: #2b91af">Line</span> axis;<br /><span style="color: blue">if</span> (h &gt; w)<br />&#160; axis = <span style="color: #2b91af">Line</span>.CreateBound(<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">XYZ</span>(<br />&#160;&#160;&#160;&#160;&#160; box.Min.X, <br />&#160;&#160;&#160;&#160;&#160; (box.Max.Y - box.Min.Y) / 2 + box.Min.Y,<br />&#160;&#160;&#160;&#160;&#160; refPlane.BubbleEnd.Z),<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">XYZ</span>(<br />&#160;&#160;&#160;&#160;&#160; box.Max.X,<br />&#160;&#160;&#160;&#160;&#160; (box.Max.Y - box.Min.Y) / 2 + box.Min.Y,<br />&#160;&#160;&#160;&#160;&#160; refPlane.BubbleEnd.Z));<br /><span style="color: blue">else</span><br />&#160; axis = <span style="color: #2b91af">Line</span>.CreateBound(<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">XYZ</span>(<br />&#160;&#160;&#160;&#160;&#160; (box.Max.X - box.Min.X) / 2 + box.Min.X,<br />&#160;&#160;&#160;&#160;&#160; box.Min.Y,<br />&#160;&#160;&#160;&#160;&#160; refPlane.BubbleEnd.Z),<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">XYZ</span>(<br />&#160;&#160;&#160;&#160;&#160; (box.Max.X - box.Min.X) / 2 + box.Min.X,<br />&#160;&#160;&#160;&#160;&#160; box.Max.Y,<br />&#160;&#160;&#160;&#160;&#160; refPlane.BubbleEnd.Z));<br /> <br /><span style="color: green">// now calculate the number of required lights</span><br /><span style="color: green">// first the Luminous of each light (from the family symbol)</span><br /><span style="color: blue">double</span> lightLuminous = symbol.get_Parameter(<br />&#160; <span style="color: #2b91af">BuiltInParameter</span>.FBX_LIGHT_LIMUNOUS_FLUX).AsDouble();<br /><span style="color: green">// and get the information from the Space</span><br /><span style="color: green">// assuming it was assigned as a Space Style param</span><br /><span style="color: blue">double</span> requiredLuminous = doc.GetElement(<br />&#160; space.get_Parameter(<span style="color: #a31515">&quot;Space Style&quot;</span>).AsElementId())<br />&#160; .get_Parameter(<span style="color: #a31515">&quot;Luminous&quot;</span>).AsDouble();<br /> <br /><span style="color: green">// now the number of lights</span><br /><span style="color: blue">int</span> numerOfLights = (<span style="color: blue">int</span>)<span style="color: #2b91af">Math</span>.Round((requiredLimunous / lightLimunous));<br /><span style="color: green">// and the distance between them </span><br /><span style="color: blue">double</span> distanceBetweenLights = axis.ApproximateLength / (numerOfLights + 2);<br /> <br /><span style="color: green">// all set, time to add the lights!</span><br /><span style="color: green">// place family instances at the locations</span><br /><span style="color: blue">for</span> (<span style="color: blue">int</span> p = 1; p &lt;= numerOfLights; p++)<br />{<br />&#160; <span style="color: green">// evaluate a point along the axis</span><br />&#160; <span style="color: green">// remember the Evaluate can be parametric, therefore</span><br />&#160; <span style="color: green">// normalized between 0 and 1</span><br />&#160; <span style="color: #2b91af">XYZ</span> pointOnAxis = axis.Evaluate(<br />&#160;&#160;&#160; p * distanceBetweenLights / axis.ApproximateLength,<br />&#160;&#160;&#160; <span style="color: blue">true</span>);<br />&#160; doc.Create.NewFamilyInstance(<br />&#160;&#160;&#160; refPlane.Reference,<br />&#160;&#160;&#160; pointOnAxis, <br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">XYZ</span>(0, 0, 0), symbol);<br />}<br /><br /> <br /><span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Succeeded;</pre>

<p>And here is the GenericFilter class used on this code, a simple class that implements the filter interface</p>

<pre style="font-size: 13px; font-family: consolas; background: white; color: black"><span style="color: blue">public</span>&#160;<span style="color: blue">class</span>&#160;<span style="color: #2b91af">GenericFilter</span>&lt;T&gt; : <span style="color: #2b91af">ISelectionFilter</span><br />{<br />&#160; <span style="color: blue">public</span>&#160;<span style="color: blue">bool</span> AllowElement(<span style="color: #2b91af">Element</span> elem)<br />&#160; {<br />&#160;&#160;&#160; <span style="color: blue">return</span> (elem <span style="color: blue">is</span> T);<br />&#160; }<br /> <br />&#160; <span style="color: blue">public</span>&#160;<span style="color: blue">bool</span> AllowReference(<span style="color: #2b91af">Reference</span> reference, <span style="color: #2b91af">XYZ</span> position)<br />&#160; {<br />&#160;&#160;&#160; <span style="color: blue">return</span>&#160;<span style="color: blue">true</span>;<br />&#160; }<br />}</pre>
