---
layout: "post"
title: "Autodesk Answer Days - Revit and Create a Roof from the API"
date: "2015-09-26 15:34:37"
author: "Jaime Rosales"
categories:
  - ".NET"
  - "Announcements"
  - "Events"
  - "Jaime Rosales"
  - "Jeremy Tammik"
  - "Revit"
  - "Revit Architecture"
  - "Revit MEP"
  - "Revit Structure"
original_url: "https://adndevblog.typepad.com/aec/2015/09/autodesk-answer-days-revit-and-create-a-roof-from-the-api.html "
typepad_basename: "autodesk-answer-days-revit-and-create-a-roof-from-the-api"
typepad_status: "Publish"
---

<p><a href="http://adndevblog.typepad.com/aec/jaime-rosales.html">By Jaime Rosales</a> (@<a href="https://twitter.com/AfroJme">afrojme</a>)</p>  <p>Autodesk Answer Days – Revit, October 7, 2015</p>  <p>Do you have any Revit® or Revit LT® questions that you’ve always wanted to ask?</p>  <p>If yes, then join the latest installment of Ask Autodesk Anything events on October 7, 2015. This event is dedicated to answering your questions about Revit and Revit LT. We’ll have some DevTech engineers attending the event to answer your API questions. The event runs from 6 am to 6 pm Pacific Time and will take place in Autodesk Community. Come spend a minute, an hour, or the whole day in the Autodesk Community to interact directly with the folks who bring this award-winning building information modeling software!</p>  <p><a href="http://www.autode.sk/answerdays">Click here</a> for more information.</p>  <p>&#160;</p>  <p><strong><img title="answer_day.png" border="0" alt="answer_day.png" src="/assets/image_343662.jpg" /></strong></p>  <p>&#160;</p>  <p>This week I have a chance to help a developer looking for a way on how to create a roof through the API. Interesting question since I don’t think I never tried that before so it was a fun piece to work on. Here is the question from our Forum community. </p>  <p><strong>Question</strong>:&#160; I'm having trouble to create a roof via code. I know how to create a stairs for example : I start a StairsEditScope and use CreateSketchedLanding with all the right parameters to create my stairs and just commit the StairsEditScope, but for a roof i cant find a clue on how to create it from scratch, any leads?</p>  <p>And if there isn't a way, for example: ceiling i know there isn't a way so i need to use a floor as a ceiling workaround. But for roof I don't have a workaround.</p>  <p><strong>Answer</strong>:Here is a command to create a roof, Just make sure you have some walls to hold it and also one of your levels is named &quot;Roof&quot;. </p>  <p>I created a simple 4 walls rectangle and the selected them and ran the command that I'm providing. </p>  <p>You can read more about this sample in the Revit Help file, here is the <a href="http://help.autodesk.com/view/RVT/2016/ENU/?guid=GUID-33E6A6BD-96AA-4FAF-B660-1DD0C06CCD29">link</a>.</p>  <blockquote>   <div class="code"><font color="#0000ff">#region</font><font color="#000000"> Namespaces</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">System</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">System.Collections.Generic</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">System.Diagnostics</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">Autodesk.Revit.ApplicationServices</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">Autodesk.Revit.Attributes</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">Autodesk.Revit.DB</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">Autodesk.Revit.UI</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">Autodesk.Revit.UI.Selection</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">using</font><font color="#808080">&#160;</font><font color="#000000">System.Linq</font><font color="#0000ff">;</font><font color="#808080">        <br /></font><font color="#0000ff">#endregion</font><font color="#808080">        <br />        <br /></font><font color="#0000ff">namespace</font><font color="#808080">&#160;</font><font color="#000000">CreateRoof</font><font color="#808080">        <br /></font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160; </font><font color="#000000">[Transaction(TransactionMode.Automatic)]</font><font color="#808080">        <br />&#160;&#160;&#160; </font><font color="#0000ff">public</font><font color="#808080">&#160;</font><font color="#0000ff">class</font><font color="#808080">&#160;</font><font color="#000000">Command</font><font color="#808080">&#160;</font><font color="#000000">:</font><font color="#808080">&#160;</font><font color="#000000">IExternalCommand</font><font color="#808080">        <br />&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">public</font><font color="#808080">&#160;</font><font color="#000000">Result</font><font color="#808080">&#160;</font><font color="#000000">Execute(</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">ExternalCommandData</font><font color="#808080">&#160;</font><font color="#000000">commandData,</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">ref</font><font color="#808080">&#160;</font><font color="#0000ff">string</font><font color="#808080">&#160;</font><font color="#000000">message,</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">ElementSet</font><font color="#808080">&#160;</font><font color="#000000">elements)</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">UIApplication</font><font color="#808080">&#160;</font><font color="#000000">uiapp</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">commandData.</font><font color="#2b91af">Application</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">UIDocument</font><font color="#808080">&#160;</font><font color="#000000">uidoc</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">uiapp.ActiveUIDocument</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#2b91af">Application</font><font color="#808080">&#160;</font><font color="#000000">app</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">uiapp.</font><font color="#2b91af">Application</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">Document</font><font color="#808080">&#160;</font><font color="#000000">doc</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">uidoc.Document</font><font color="#0000ff">;</font><font color="#808080">        <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#006400">// Before invoking this sample, select some walls to add a roof over.        <br /></font><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#006400">// Make sure there is a level named &quot;Roof&quot; in the document.        <br /></font><font color="#808080">       <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#006400">// find the Roof level        <br /></font><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">FilteredElementCollector</font><font color="#808080">&#160;</font><font color="#000000">collector</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#0000ff">new</font><font color="#808080">&#160;</font><font color="#000000">FilteredElementCollector(doc)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">collector.OfClass(</font><font color="#0000ff">typeof</font><font color="#000000">(Level))</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">var</font><font color="#808080">&#160;</font><font color="#000000">elem</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#0000ff">from</font><font color="#808080">&#160;</font><font color="#000000">element</font><font color="#808080">&#160;</font><font color="#0000ff">in</font><font color="#808080">&#160;</font><font color="#000000">collector</font><font color="#808080">&#160;</font><font color="#0000ff">where</font><font color="#808080">&#160;</font><font color="#000000">element.Name</font><font color="#808080">&#160;</font></div>    <div class="code"><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">==</font><font color="#808080"> &quot;Roof&quot; </font><font color="#0000ff">select</font><font color="#808080">&#160;</font><font color="#000000">element</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">Level</font><font color="#808080">&#160;</font><font color="#000000">level</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">elem.Cast&lt;Level&gt;().ElementAt&lt;Level&gt;(</font><font color="#800000">0</font><font color="#000000">)</font><font color="#0000ff">;</font><font color="#808080">        <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">collector</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#0000ff">new</font><font color="#808080">&#160;</font><font color="#000000">FilteredElementCollector(doc)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">collector.OfClass(</font><font color="#0000ff">typeof</font><font color="#000000">(RoofType))</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">RoofType</font><font color="#808080">&#160;</font><font color="#000000">roofType</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">collector.FirstElement()</font><font color="#808080">&#160;</font><font color="#0000ff">as</font><font color="#808080">&#160;</font><font color="#000000">RoofType</font><font color="#0000ff">;</font><font color="#808080">        <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#006400">// Get the handle of the application        <br /></font><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">Autodesk.Revit.ApplicationServices.</font><font color="#2b91af">Application</font><font color="#808080">&#160;</font><font color="#000000">application</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">doc.</font><font color="#2b91af">Application</font><font color="#0000ff">;</font><font color="#808080">        <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#006400">// Define the footprint for the roof based on user selection        <br /></font><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">CurveArray</font><font color="#808080">&#160;</font><font color="#000000">footprint</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">application.Create.NewCurveArray()</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#2b91af">ICollection</font><font color="#000000">&lt;ElementId&gt;</font><font color="#808080">&#160;</font><font color="#000000">selectedIds</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">uidoc.Selection.GetElementIds()</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">if</font><font color="#808080">&#160;</font><font color="#000000">(selectedIds.Count</font><font color="#808080">&#160;</font><font color="#000000">!</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#800000">0</font><font color="#000000">)</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">foreach</font><font color="#808080">&#160;</font><font color="#000000">(ElementId</font><font color="#808080">&#160;</font><font color="#000000">id</font><font color="#808080">&#160;</font><font color="#0000ff">in</font><font color="#808080">&#160;</font><font color="#000000">selectedIds)</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">Element</font><font color="#808080">&#160;</font><font color="#000000">element</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">doc.GetElement(id)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">Wall</font><font color="#808080">&#160;</font><font color="#000000">wall</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">element</font><font color="#808080">&#160;</font><font color="#0000ff">as</font><font color="#808080">&#160;</font><font color="#000000">Wall</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">if</font><font color="#808080">&#160;</font><font color="#000000">(wall</font><font color="#808080">&#160;</font><font color="#000000">!</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#0000ff">null</font><font color="#000000">)</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">LocationCurve</font><font color="#808080">&#160;</font><font color="#000000">wallCurve</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">wall.Location</font><font color="#808080">&#160;</font><font color="#0000ff">as</font><font color="#808080">&#160;</font><font color="#000000">LocationCurve</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">footprint.Append(wallCurve.Curve)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">continue;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">ModelCurve</font><font color="#808080">&#160;</font><font color="#000000">modelCurve</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">element</font><font color="#808080">&#160;</font><font color="#0000ff">as</font><font color="#808080">&#160;</font><font color="#000000">ModelCurve</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">if</font><font color="#808080">&#160;</font><font color="#000000">(modelCurve</font><font color="#808080">&#160;</font><font color="#000000">!</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#0000ff">null</font><font color="#000000">)</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">footprint.Append(modelCurve.GeometryCurve)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">else</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">throw</font><font color="#808080">&#160;</font><font color="#0000ff">new</font><font color="#808080">&#160;</font><font color="#2b91af">Exception</font><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (</font><font color="#808080">&quot;You should select a curve loop, </font></div>    <div class="code"><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; or a wall loop, or loops combination </font></div>    <div class="code"><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; \nof walls and curves to create a footprint roof.&quot;</font><font color="#000000">)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">ModelCurveArray</font><font color="#808080">&#160;</font><font color="#000000">footPrintToModelCurveMapping</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#0000ff">new</font><font color="#808080">&#160;</font><font color="#000000">ModelCurveArray()</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">FootPrintRoof</font><font color="#808080">&#160;</font><font color="#000000">footprintRoof</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">doc.Create.NewFootPrintRoof</font></div>    <div class="code"><font color="#000000">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; (footprint,</font><font color="#808080">&#160;</font><font color="#000000">level,</font><font color="#808080">&#160;</font><font color="#000000">roofType,</font><font color="#0000ff">out</font><font color="#808080">&#160;</font><font color="#000000">footPrintToModelCurveMapping)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">ModelCurveArrayIterator</font><font color="#808080">&#160;</font><font color="#000000">iterator</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font></div>    <div class="code"><font color="#808080">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">footPrintToModelCurveMapping.ForwardIterator()</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">iterator.Reset()</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">while</font><font color="#808080">&#160;</font><font color="#000000">(iterator.MoveNext())</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">{</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">ModelCurve</font><font color="#808080">&#160;</font><font color="#000000">modelCurve</font><font color="#808080">&#160;</font><font color="#0000ff">=</font><font color="#808080">&#160;</font><font color="#000000">iterator.Current</font><font color="#808080">&#160;</font><font color="#0000ff">as</font><font color="#808080">&#160;</font><font color="#000000">ModelCurve</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">footprintRoof.set_DefinesSlope(modelCurve,</font><font color="#808080">&#160;</font><font color="#0000ff">true</font><font color="#000000">)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">footprintRoof.set_SlopeAngle(modelCurve,</font><font color="#808080">&#160;</font><font color="#800000">0</font><font color="#000000">.</font><font color="#800000">5</font><font color="#000000">)</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br />        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#0000ff">return</font><font color="#808080">&#160;</font><font color="#000000">Result.Succeeded</font><font color="#0000ff">;</font><font color="#808080">        <br />&#160;&#160;&#160;&#160;&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br />&#160;&#160;&#160; </font><font color="#000000">}</font><font color="#808080">        <br /></font><font color="#000000">}</font> </div> </blockquote>  <p>Let me know how it goes. </p>  <p>Also the same question, or at least that is how it looks like, got asked in Stack Overflow. The answer this time came by our API Guru Jeremy Tammik. It is nice to see how we are covering same questions across different support forums for Revit API, I call that a great collaboration across forums. You are best of continuing your questions in the Revit API forum, but we are also looking out for those questions that get posted in other places, like Stack Overflow for example.&#160; </p>  <p>Here is the response that Jeremy wrote in Stack Overflow. </p>  <p><strong>Answer</strong>: Revit provides different kinds of roofs. It is best to understand the various types from an end user point of view before starting to drive them programmatically. The simplest one is defined by a horizontal outline. You can create a roof from such an outline using the Document.NewFootPrintRoof method. Such a roof can be flat, or you can specify a slope for each edge of the outline profile. The Building Coder Xtra labs provide a working sample in the external command Lab2_0_CreateLittleHouse in Labs2.cs:</p>  <p><a href="https://github.com/jeremytammik/AdnRevitApiLabsXtra/blob/master/XtraCs/Labs2.cs">https://github.com/jeremytammik/AdnRevitApiLabsXtra/blob/master/XtraCs/Labs2.cs</a></p>  <p>Here are some other roof-related posts on The Building Coder:</p>  <ul>   <li><a href="http://thebuildingcoder.typepad.com/blog/2008/09/roomsroofs-sdk.html">RoomsRoofs SDK Sample</a> </li>    <li><a href="http://thebuildingcoder.typepad.com/blog/2009/08/roof-eave-cut-in-revit-and-aca.html">Roof Eave Cut</a> </li>    <li><a href="http://thebuildingcoder.typepad.com/blog/2014/09/events-again-and-creating-an-extrusion-roof.html">Creating an Extrusion Roof</a> </li> </ul>  <p>I hope this helps.</p>  <p>Thanks for reading and until next time. </p>
