---
layout: "post"
title: "JoinGeometry for walls and columns"
date: "2015-08-04 12:05:19"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "Revit"
original_url: "https://adndevblog.typepad.com/aec/2015/08/joingeometry-for-walls-and-columns.html "
typepad_basename: "joingeometry-for-walls-and-columns"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/augusto-goncalves.html">Augusto Goncalves</a> (@<a href="https://twitter.com/augustomaia">augustomaia</a>)</p>  <p>I was actually looking for a sample of JoinGeometry on the blogs and could not find one, so here it is. </p>  <p>This method, like many others on the API, mimic the UI behavior: it requires 2 elements to join. So the ‘trick’ is find those elements. For this sample, let’s assume we have a model with walls and columns to join. We cannot call join for all walls and columns, it’s a exponential problem. Jeremy wrote a cool sample that help us <a href="http://thebuildingcoder.typepad.com/blog/2010/12/find-intersecting-elements.html">find intersecting elements</a>, so let’s use it.</p>  <p>Basically just get all Walls, then for each wall, get intersecting Columns (via Bounding Box) and call JoinGeometry for these 2 elements.</p>  <pre style="font-size: 13px; font-family: consolas; background: white; color: black"><span style="color: #2b91af">UIApplication</span> uiapp = commandData.Application;<br /><span style="color: #2b91af">UIDocument</span> uidoc = uiapp.ActiveUIDocument;<br /><span style="color: #2b91af">Application</span> app = uiapp.Application;<br /><span style="color: #2b91af">Document</span> doc = uidoc.Document;<br /> <br /><span style="color: green">// get all walls on the active view</span><br /><span style="color: #2b91af">FilteredElementCollector</span> collWalls = <br />&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">FilteredElementCollector</span>(doc, doc.ActiveView.Id);<br />collWalls.OfClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">Wall</span>));<br /> <br /><span style="color: blue">foreach</span> (<span style="color: #2b91af">Wall</span> w <span style="color: blue">in</span> collWalls)<br />{<br />&#160; <span style="color: green">// get columns on the active view</span><br />&#160; <span style="color: #2b91af">FilteredElementCollector</span> collColumnsOnThisWall =<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">FilteredElementCollector</span>(doc, doc.ActiveView.Id);<br />&#160; collColumnsOnThisWall.OfClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">FamilyInstance</span>));<br />&#160; collColumnsOnThisWall.OfCategory(<br />    <span style="color: #2b91af">BuiltInCategory</span>.OST_StructuralColumns);<br /> <br />&#160; <span style="color: green">// as we don't want all columns, let's filter</span><br />&#160; <span style="color: green">// by the wall bounding box (intersect)</span><br />&#160; <span style="color: #2b91af">BoundingBoxXYZ</span> bb = w.get_BoundingBox(doc.ActiveView);<br />&#160; <span style="color: #2b91af">Outline</span> outline = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">Outline</span>(bb.Min, bb.Max);<br />&#160; <span style="color: #2b91af">BoundingBoxIntersectsFilter</span> bbfilter =<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">BoundingBoxIntersectsFilter</span>(outline);<br />&#160; collColumnsOnThisWall.WherePasses(bbfilter);<br /> <br />&#160; <span style="color: green">// finally, call JOIN on the wall and column</span><br />&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">FamilyInstance</span> column <span style="color: blue">in</span> collColumnsOnThisWall)<br />&#160; {<br />&#160;&#160;&#160; <span style="color: #2b91af">JoinGeometryUtils</span>.JoinGeometry(doc, w, column);<br />&#160; }<br />}</pre>
