---
layout: "post"
title: "Revit API Training and some manual work automation"
date: "2015-04-22 13:31:00"
author: "Augusto Goncalves"
categories:
  - ".NET"
  - "Augusto Goncalves"
  - "Revit"
original_url: "https://adndevblog.typepad.com/aec/2015/04/revit-api-training-and-some-manual-work-automation.html "
typepad_basename: "revit-api-training-and-some-manual-work-automation"
typepad_status: "Publish"
---

<p>By <a href="http://adndevblog.typepad.com/aec/augusto-goncalves.html">Augusto Goncalves</a></p>  <p>Last week I went to <a href="http://en.wikipedia.org/wiki/Belo_Horizonte">Belo Horizonte</a> for a quick Revit API Training. It was a good time visit my <a href="http://en.wikipedia.org/wiki/Universidade_Federal_de_Minas_Gerais">university campus</a> and remember the good times as a Civil Engineer student (and we’re about to celebrate 10 years now, time flies!).</p>  <p>If you haven’t visit this part of the word, here is a quick view of the <a href="http://en.wikipedia.org/wiki/Church_of_Saint_Francis_of_Assisi">Church of Saint Francis of Assisi (Igreja de Sao Francisco de Assis)</a> designed by famous Brazilian architect <a href="http://en.wikipedia.org/wiki/Oscar_Niemeyer">Oscar Niemeyer</a>. Is a nice piece of curved concrete (now it’s the Civil Engineer speaking).</p>  <p><a href="http://adndevblog.typepad.com/.a/6a0167607c2431970b01bb0821c534970d-pi"><img title="Church of Saint Francis of Assisi" style="border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px; display: inline" border="0" alt="Church of Saint Francis of Assisi" src="/assets/image_97726.jpg" width="469" height="353" /></a> </p>  <p>During the Revit API training we used the <a href="https://github.com/ADN-DevTech/RevitTrainingMaterial/releases/tag/2015.0.0.0">2015 version of our training material</a> with the <a href="http://thebuildingcoder.typepad.com/blog/2014/05/add-in-wizards-for-revit-2015.html">Visual Studio template</a>. I enjoy doing training where we have a problem to solve, which is a good background to teach some API concepts. The problem in hand is: for a 3D view with equipments (represented by generic models), create individual views for each equipment and export to DWG files.</p>  <p>One way is by the code below. Basically we get all generic model instances on the active view, then the respective families. Now create a view using each family name. This was the easy part… </p>  <p>To make the view show only the specific family instance, we need to create and set a view filter. Actually <a href="http://thebuildingcoder.typepad.com/blog/2015/01/isolating-elements-of-a-given-system.html">Jeremy did a similar code</a> that we reused and adjusted here. Finally export all the created views.</p>  <p>Check the code below, the comments should help understand the steps. </p>  <pre style="font-size: 13px; font-family: consolas; background: white; color: black"><span style="color: green">// get the active document from the command Execute param</span><font size="2"><span style="color: #2b91af"><br />Document</span> doc = commandData.Application.ActiveUIDocument.Document;<br /> <br /><span style="color: green">// get all generic models on the current 3D View</span><br /><span style="color: #2b91af">FilteredElementCollector</span> collGenericModels =<br />&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">FilteredElementCollector</span>(doc, doc.ActiveView.Id);<br />collGenericModels.OfClass(<span style="color: blue">typeof</span>(<span style="color: #2b91af">FamilyInstance</span>));<br />collGenericModels.OfCategory(<span style="color: #2b91af">BuiltInCategory</span>.OST_GenericModel);<br /> <br /><span style="color: green">// but we need the families of these generic models, </span><br /><span style="color: green">// so let's create a list with the family IDs</span><br /><span style="color: #2b91af">List</span>&lt;<span style="color: blue">int</span>&gt; genericModelsFamiliesIds = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">List</span>&lt;<span style="color: blue">int</span>&gt;();<br /><span style="color: blue">foreach</span> (<span style="color: #2b91af">FamilyInstance</span> equip <span style="color: blue">in</span> collGenericModels)<br />{<br />&#160; <span style="color: #2b91af">ElementId</span> symbolId = equip.Symbol.Id;<br />&#160; <span style="color: blue">if</span> (!genericModelsFamiliesIds.Contains(symbolId.IntegerValue))<br />&#160;&#160;&#160; genericModelsFamiliesIds.Add(symbolId.IntegerValue);<br />}<br /> <br /><span style="color: green">// get the active view</span><br /><span style="color: #2b91af">View3D</span> activeView = doc.ActiveView <span style="color: blue">as</span>&#160;<span style="color: #2b91af">View3D</span>;<br /><span style="color: blue">if</span> (activeView == <span style="color: blue">null</span>)<br />{<br />&#160; <span style="color: green">// the active view is required in this case</span><br />&#160; <span style="color: green">// as it will be duplicated with</span><br />&#160; message = <span style="color: #a31515">&quot;Please run command from a 3D View&quot;</span>;<br />&#160; <span style="color: blue">return</span>&#160;<span style="color: #2b91af">Result</span>.Failed;<br />}<br /> <br /><span style="color: green">// control copy numbers</span><br /><span style="color: blue">int</span> copy = 1;<br /> <br /><span style="color: green">// this list will store the views created</span><br /><span style="color: #2b91af">List</span>&lt;<span style="color: #2b91af">ElementId</span>&gt; viewIds = <span style="color: blue">new</span>&#160;<span style="color: #2b91af">List</span>&lt;<span style="color: #2b91af">ElementId</span>&gt;();<br /> <br /><span style="color: blue">foreach</span> (<span style="color: blue">int</span> genericModelId <span style="color: blue">in</span> genericModelsFamiliesIds)<br />{<br />&#160; <span style="color: green">// get the family</span><br />&#160; <span style="color: #2b91af">FamilySymbol</span> famSymbol = doc.GetElement(<br />     <span style="color: blue">new</span>&#160;<span style="color: #2b91af">ElementId</span>(genericModelId)) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">FamilySymbol</span>;<br /> <br />&#160; <span style="color: green">// create the view by duplicating the active view</span><br />&#160; <span style="color: #2b91af">ElementId</span> genericModelViewId = activeView.Duplicate(<br />     <span style="color: #2b91af">ViewDuplicateOption</span>.Duplicate);<br />&#160; <span style="color: green">// and add to the list</span><br />&#160; viewIds.Add(genericModelViewId);<br />&#160; <span style="color: green">// and open for further processing</span><br />&#160; <span style="color: #2b91af">View3D</span> genericModelView = doc.GetElement(<br />     genericModelViewId) <span style="color: blue">as</span>&#160;<span style="color: #2b91af">View3D</span>;<br /> <br />&#160; <span style="color: green">// here you can adjust the view name</span><br />&#160; <span style="color: green">// according to internal rules</span><br />&#160; <span style="color: blue">string</span> viewName = <span style="color: blue">string</span>.Format(<span style="color: #a31515">&quot;MM-{0}&quot;</span>, famSymbol.Name);<br />&#160; <span style="color: blue">try</span><br />&#160; {<br />&#160;&#160;&#160; <span style="color: green">// try apply a name</span><br />&#160;&#160;&#160; genericModelView.ViewName = viewName;<br />&#160; }<br />&#160; <span style="color: blue">catch</span><br />&#160; {<br />&#160;&#160;&#160; <span style="color: green">// should not happen, except for </span><br />&#160;&#160;&#160; <span style="color: green">// wrong project standard</span><br />&#160;&#160;&#160; viewName = <span style="color: blue">string</span>.Format(<span style="color: #a31515">&quot;{0} - Copy ({1})&quot;</span>, viewName, copy);<br />&#160;&#160;&#160; genericModelView.ViewName = viewName;<br />&#160;&#160;&#160; copy++;<br />&#160; }<br /> <br />&#160; <span style="color: green">// the new view may come without the categories</span><br />&#160; <span style="color: green">// configured for generic models, so let's set all</span><br />&#160; <span style="color: green">// as Visible=false, then set GenericModel=true</span><br />&#160; <span style="color: blue">foreach</span> (<span style="color: #2b91af">Category</span> cat <span style="color: blue">in</span> doc.Settings.Categories)<br />&#160; {<br />&#160;&#160;&#160; <span style="color: blue">try</span> { genericModelView.SetVisibility(cat, <span style="color: blue">false</span>); }<br />&#160;&#160;&#160; <span style="color: blue">catch</span> { <span style="color: green">/* não aplicável */</span>}<br />&#160; }<br />&#160; <span style="color: #2b91af">Category</span> catGenericModel = doc.Settings.Categories.<br />     get_Item(<span style="color: #2b91af">BuiltInCategory</span>.OST_GenericModel);<br />&#160; genericModelView.SetVisibility(catGenericModel, <span style="color: blue">true</span>);<br /> <br />&#160; <span style="color: green">// now create a new filter using the view name</span><br />&#160; <span style="color: green">// and prefixed by F_</span><br />&#160; <span style="color: #2b91af">ParameterFilterElement</span> newFilter = <br />    <span style="color: #2b91af">ParameterFilterElement</span>.Create(<br />&#160;&#160;&#160; doc, <span style="color: blue">string</span>.Format(<span style="color: #a31515">&quot;F_{0}&quot;</span>, viewName),<br />&#160; <span style="color: blue">new</span>[] { catGenericModel.Id });<br />&#160; <span style="color: green">// with a rule to show only the family we filter</span><br />&#160; <span style="color: #2b91af">FilterRule</span> rule = <span style="color: #2b91af">ParameterFilterRuleFactory</span>.<br />    CreateNotEqualsRule(<br />&#160;&#160;&#160; <span style="color: blue">new</span>&#160;<span style="color: #2b91af">ElementId</span>(<span style="color: #2b91af">BuiltInParameter</span>.ALL_MODEL_TYPE_NAME),<br />&#160; famSymbol.Name, <span style="color: blue">true</span>);<br />&#160; <span style="color: green">// and apply the rule</span><br />&#160; newFilter.SetRules(<span style="color: blue">new</span>[] { rule });<br />&#160; <span style="color: green">// last step is add the filter and set as false </span><br />&#160; <span style="color: green">// as the Rule is Not Equals</span><br />&#160; genericModelView.AddFilter(newFilter.Id);<br />&#160; genericModelView.SetFilterVisibility(newFilter.Id, <span style="color: blue">false</span>);<br />}<br /> <br /><span style="color: green">// finally we have all views, one for each element</span><br /><span style="color: green">// let's export it to DWG files using the view id list</span><br /><span style="color: #2b91af">DWGExportOptions</span> options = <span style="color: #2b91af">DWGExportOptions</span>.GetPredefinedOptions(<br />   doc, <span style="color: #a31515">&quot;Standard&quot;</span>);<br />doc.Export(<span style="color: #a31515">&quot;c:\\temp_rvt\\&quot;</span>, <span style="color: #a31515">&quot;GenericModels&quot;</span>, viewIds, options);</font></pre>
